### ISSUE TITLE
[bug] Disappearing accents in MQTT messages

### ISSUE THREAD

**Issue by Micka41** [zwave-js/zwavejs2mqtt#1003]
### Version

**Checklist:**

- [X] I am **not** using HomeAssistant. **Or:** a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is **not** described there.
- [X] I have read the changelog problem was **not** mentioned there.

Build/Run method

- [ ] Docker
- [ ] PKG
- [ ] Snap package
- [X] Manually built (git clone - npm install - npm run build )

zwavejs2mqtt version: <version here, you can find it on control panel>
zwave-js version: <version here, you can find it on control panel>
After an git clone https://github.com/zwave-js/zwavejs2mqtt today

### Describe the bug

The accent (éèàë ...) contained in the location or the name are replaced in the MQTT messages by "empty".

Fenêtre -> Fentre
Lumière -> Lumire ....

The problem did not exist in 2.4.1

### To Reproduce

Update in 3.1
Set name or location with an accent
See MQTT message with MQTT Explorer

### Expected behavior

Accents allowed as before.

**Comment by robertsLando** [comment]
I think this is due to the new regex used to sanitize topics, I think we should add also accent chars to allowed ones.

**Comment by Micka41** [comment]
It's work !
Thank you
