### ISSUE TITLE
[question] Overriding device config / enabling compat options

### ISSUE THREAD

**Issue by matejdro** [zwave-js/zwavejs2mqtt#1011]
When running zwavejs2mqtt via docker, what is the best way to add [compatibility options](https://github.com/zwave-js/node-zwave-js/blob/master/docs/config-files/file-format.md#compat) on my devices?

Recent changes have broken my Aeotec Nano Switch setup. I have the switch set to only emit basic set events whenever switch is toggled, so I can control switch's relay state independently of the actual physical rocker. Up until now zwavejs was first syncing this with the switch state, then it exported basic value into separate property and now it seems like these basic set events are ignored.

From what I see, the best solution would be to enable `treatBasicSetAsEvent` option, so I can receive these switch events.

**Comment by robertsLando** [comment]
@matejdro There is an hidden property `options` in zwave settings that can be used to set all driver configuration properties. This can be changed by manually editing the `settings.json` file  

```js
{
    "mqtt": {
        // mqtt settings
    },
    "gateway": {
        // gw settings
    },
    "zwave": {
        "port": "/dev/ttyACM0",
        // other settings ...
        "options": {
          "treatBasicSetAsEvent": true
         }
    }
}

```

**Comment by matejdro** [comment]
But from what I see, this will set this compat setting globaly to all devices?

**Comment by robertsLando** [comment]
Sorry I misunderstood your question, that is an example about how to extend zwaveoptions, but the `treatBasicSetAsEvent` it's not a [zwaveOption](https://zwave-js.github.io/node-zwave-js/#/api/driver?id=zwaveoptions) of driver constructor. In order to do that you need to manually edit the device config file I think. BTW @AlCalzone could tell you more about this

**Comment by AlCalzone** [comment]
You'll have to figure out which one is the correct file for your device, then add/extend the `compat` section of that file. When using Docker, you can then mount the file into the correct location (`/some/path/node_modules/@zwave-js/config/config/devices/<manufacturer>/<filename>.json`) and restart

**Comment by matejdro** [comment]
Thanks a lot, it worked!

For anyone looking for this, I mounted the file as a volume by adding following switch to the `docker run` command:

`-v /path/to/config/on/host/pc/zw116.json:/usr/src/app/node_modules/@zwave-js/config/config/devices/0x0086/zw116.json`
