### ISSUE TITLE
[bug] unable to modify files in the store section

### ISSUE THREAD

**Issue by oeiber** [zwave-js/zwavejs2mqtt#1013]
I'm using zwavejs2mqtt from docker registry, running on my pi4.
the container runs with default settings (http on port 8091) and is proxied using nginx.
when i publish zwavejs2mqtt to the root folder (https://domain.tld/) it works fine. But when publishing to a subfolder (e.g. https://domain.tld/zwave/) i'm unable to access files in the store section in the frontend.
X-External-Path header is set correctly as descriped in the manual. when i try to modify a file i can see the following error ishown in the webinterface:
`"Request failed with status code 404" `
at the same time docker logs the following error:
`Error: Not Found
    at /usr/src/app/app.js:979:15
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:317:13)
    at /usr/src/app/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/src/app/node_modules/express/lib/router/index.js:275:10)
    at /usr/src/app/node_modules/express-session/index.js:502:7
    at readCallback (/usr/src/app/node_modules/session-file-store/lib/session-file-helpers.js:193:20)
    at /usr/src/app/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:75:3)`

btw this behavior can also be reproduced using supervised homeassistant with ingress functionality.

**Comment by robertsLando** [comment]
This is a bug with the zwavejs2mqtt addon not here

**Comment by oeiber** [comment]
I don't think so, because this problem also occours using zwavejs2mqtt as standalone container.
Where should I report the bug?

**Comment by robertsLando** [comment]
> I don't think so, because this problem also occours using zwavejs2mqtt as standalone container.

I cannot reproduce your issue so. When i edit files I get no error

**Comment by oeiber** [comment]
did you also publish the webinterface to a subdir as well? i‘m using docker image zwavejs/zwavejs2mqtt:latest

**Comment by robertsLando** [comment]
> did you also publish the webinterface to a subdir as well

I don't know what you mean. I simply did this: 

```
mkdir testZ2M
cd testZ2M
mkdir store
docker pull zwavejs/zwavejs2mqtt:latest // to be sure I have latest
docker run --rm -it -p 8091:8091 --device=/dev/ttyACM0 -v $(pwd)/store:/usr/src/app/store zwavejs/zwavejs2mqtt:latest
```

**Comment by oeiber** [comment]
> I don't know what you mean. I simply did this:

The problem only occurs when using zwavejs behind a reverse proxy, in my case nginx:

When I use the root directory of the webserver everything works fine:

 `location   / {
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_pass http://zwave:8091;
}`

But when is try to map zwavejs webinterface to a subdirectory, I'm unable to edit files in the frontend:

 `location   /temp/ {
        proxy_set_header X-External-Path /temp;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_pass http://zwave:8091/;
}`

As you can see above, I also set the X-External-Path header as described in the manual: [https://zwave-js.github.io/zwavejs2mqtt/#/usage/reverse-proxy](url)

**Comment by robertsLando** [comment]
> The problem only occurs when using zwavejs behind a reverse proxy, in my case nginx:

This is the same problem that occurs with hass z2m addon as I think they also use a reverse proxy. Seems that the reverso proxy tranlastes the path in the url... 

On my side I do: https://github.com/zwave-js/zwavejs2mqtt/blob/master/src/apis/ConfigApis.js#L102

The `encodeURIComponent` tranlsates urls so all special chars are escaped. Seems that the reverse proxy removes the escapes chars and this causes the url to become wrong causing a 404 error.

Maybe this could be a fix: 

https://stackoverflow.com/questions/28995818/nginx-proxy-pass-and-url-decoding
https://stackoverflow.com/questions/20496963/avoid-nginx-decoding-query-parameters-on-proxy-pass-equivalent-to-allowencodeds

**Comment by oeiber** [comment]
Thank you! Now it's working.

Here my NGINX config:

```
location   /temp/ {
        rewrite ^ $request_uri;
        rewrite '^/zwave(/.*)$' $1 break;
        proxy_set_header X-External-Path /temp;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_pass http://zwave:8091$uri;;
}
```

Maybe the documentation should be updated as well, shouldn't it?

**Comment by robertsLando** [comment]
Could you make a PR for docs?

**Comment by robertsLando** [comment]
I already updated the docs.

**Comment by robertsLando** [comment]
@oeiber Just for info, isn't 

`proxy_pass http://zwave:8091$uri;`

enought? Do you need also:

```
rewrite ^ $request_uri;
rewrite '^/zwave(/.*)$' $1 break;
```

?
