### ISSUE TITLE
[bug] Add default on all HA templates for attributes

### ISSUE THREAD

**Issue by drjjr2** [zwave-js/zwavejs2mqtt#1020]
### Version

**Checklist:**

- [ ] I am **not** using HomeAssistant. **Or:** a developer has told me to come here.
- [X ] I have checked the troubleshooting section and my problem is **not** described there.
- [ ] I have read the changelog problem was **not** mentioned there.

Build/Run method

- [ X] Docker
- [ ] PKG
- [ ] Snap package
- [ ] Manually built (git clone - npm install - npm run build )

zwavejs2mqtt version: 3.2.0
zwave-js version: 7.1.1

### Describe the bug

Similar to the issue for zigbee2mqtt described [here](https://github.com/Koenkk/zigbee2mqtt/pull/6988) 

### To Reproduce

1. start zwave2jsmqtt
2. home_assistant.log shows lots of 
`WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'value' when rendering '{{ {}[value_json.value] | default(value_json.value) }}'`
and
`WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'value' when rendering '{{ value_json.value}}'`

### Expected behavior

There should not be warnings.

**Comment by robertsLando** [comment]
hummm that's strange, I mean the warning is strange, has this been introduced in a recent update? If so what kind of payload type are you using? Just value or Json time value or entire zwave object?

**Comment by drjjr2** [comment]
I am using the entire zwave object. And, yes, this just started with the 2021.4.0 update yesterday.

**Comment by robertsLando** [comment]
@drjjr2 The fix is not that easy to do, we should firstly detect for each device why that field is missing... Check the discussion on the PR you linked

**Comment by drjjr2** [comment]
OK, I'll try to do some digging. The HA logs don't give me any indication of which device is causing the warning.

**Comment by robertsLando** [comment]
Thanks! Let me know

**Comment by drjjr2** [comment]
OK, so I can see this happening when I have a GE 14291 light switch. The node interview shows it has
```
switch_switch	switch	switch	Yes	Enabled
sensor_scene_state_sceneid	sensor	scene_state_sceneid	Yes	Enabled
sensor_scene_state_dimmingduration	sensor	scene_state_dimmingduration	Yes	Enabled
```
But sceneid and dimmingduration are unknown.  In fact, it's not even a dimmable switch. I modified the JSON to include extra spaces before the }} and could see them show up in the log.
```
2021-04-12 18:11:57 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'value' when rendering '{{ value_json.value   }}'
2021-04-12 18:11:59 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'value' when rendering '{{ value_json.value  }}'
2021-04-12 18:12:00 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'value' when rendering '{{ value_json.value   }}'
```

My guess is every switch that has those sensors that aren't reporting anything are causing this error.

**Comment by robertsLando** [comment]
I think this may be related to https://github.com/zwave-js/zwavejs2mqtt/issues/1020 , can you tell your payload type settings?

**Comment by drjjr2** [comment]
> I think this may be related to #1020 , can you tell your payload type settings?

Yes, I submitted #1020. This is more information that I am finding. The payload is the entire zwave object.

**Comment by robertsLando** [comment]
LOL this is #1020, sorry 😆 Are you able to see with mqtt explorer what's the payload sent there? I think this could be due to the "value" property set to `undefined` in some cases

**Comment by drjjr2** [comment]
OK, I'm no MQTT expert but in HA if I look at the last message received for sceneid, there is no "value" in the JSON:
```
homeassistant/Garage_Light/43/0/sceneId
Received 10:15:00 PM
QoS: 0, Retained
Payload: {
  "id": "22-43-0-sceneId",
  "nodeId": 22,
  "commandClass": 43,
  "commandClassName": "Scene Activation",
  "endpoint": 0,
  "property": "sceneId",
  "propertyName": "sceneId",
  "type": "number",
  "readable": true,
  "writeable": true,
  "label": "Scene ID",
  "stateless": false,
  "min": 1,
  "max": 255,
  "list": false,
  "lastUpdate": 1618264281471
}
```

**Comment by robertsLando** [comment]
Yeah that's what I mean, I think that we could convert undefined fields to null or maybe just ignore undefined values

**Comment by drjjr2** [comment]
Looks like the zigbee2mqtt folks decided on null:
[](https://github.com/Koenkk/zigbee2mqtt/pull/7032)

**Comment by frenck** [comment]
> I think that we could convert undefined fields to null or maybe just ignore undefined values

There is a difference. Missing should be unexpected, while a null value is there but unknown.

**Comment by drjjr2** [comment]
I haven't looked at all the devices that are causing the warnings that I am seeing, but at least in the case of the GE 14291, it has a dimming duration that shouldn't even apply to it (it's not a dimming switch). I guess sceneid should report null if no scene has been activated on it.

**Comment by towerhand** [comment]
Yea, out of the 4 entitites in my GE switches only 2 have `"value_template": "{{ value_json.value}}"` in the discovery payload. ("sensor_scene_state_dimmingduration" and "sensor_scene_state_sceneid")

All entities in zooz and inovelli switches I own have `"value_template": "{{ value_json.value}}"` in the discovery payload. 

Yale lock too, except two entities that have `"value_template": "{{ {}[value_json.value] | default(value_json.value) }}"` which also shows a warning in HA.

This is the full Hass device JSON for one of my switches. Any recommendations @frenck 

```
{
  "type": "switch",
  "object_id": "switch",
  "discovery_payload": {
    "payload_off": false,
    "payload_on": true,
    "value_template": "{{ value_json.value }}",
    "command_topic": "zwave2jsmqtt/dining_room_lights/37/0/targetValue/set",
    "state_topic": "zwave2jsmqtt/dining_room_lights/37/0/currentValue",
    "device": {
      "identifiers": [
        "zwavejs2mqtt_0xead969cf_node7"
      ],
      "manufacturer": "Inovelli",
      "model": "In-Wall Switch (On/Off) Scene Enabled (NZW30S)",
      "name": "dining_room_lights",
      "sw_version": "1.3"
    },
    "name": "dining_room_lights_switch",
    "unique_id": "zwavejs2mqtt_0xead969cf_7-37-0-currentValue"
  },
  "discoveryTopic": "switch/dining_room_lights/switch/config",
  "values": [
    "37-0-currentValue",
    "37-0-targetValue"
  ],
  "persistent": false,
  "ignoreDiscovery": false,
  "id": "switch_switch"
}

**Comment by scyto** [comment]
FWIW i have this on 12 devices - few locks, couple of my odd rgbw devices.
![image](https://user-images.githubusercontent.com/11369180/116837623-0c922500-ab80-11eb-8e0f-00c238d0956c.png)

**Comment by robertsLando** [comment]
@scyto you mean you see that warning from 12 devices?

**Comment by scyto** [comment]
I see one warning per long line above i believe.  Logging in hass is less than good at actually telling me.

**Comment by scyto** [comment]
i lied, I see 36 lines - have yet to prove they are all from mqtt

![image](https://user-images.githubusercontent.com/11369180/116916995-e792c600-ac02-11eb-93f1-f7c9087e9b91.png)

**Comment by drjjr2** [comment]
I'm fairly certain all (or most) of the errors I have are for the various scene_state_scene_xxx, scene_state_slowrefresh, along with dimming_duration (for some non-dimming switches). I did a dump of all the entities in HA with '' as their state (58 total). Things like alarmlevel for locks that is no longer reported, etc.
I'm not sure how to go about reporting which devices are having all of these issues.

**Comment by robertsLando** [comment]
yeah the problem is that some values are `undefined` and this is causing the errors you are seeing there

**Comment by jerobins** [comment]
Let me know what I can provide to help. This is my log immediately after HA startup:

`Template variable warning: 'dict object' has no attribute 'value' when rendering '{{ value_json.value}}'
3:36:00 PM – (WARNING) helpers/template.py - message first occurred at 3:35:38 PM and shows up 136 times`

All from zwavejs2mqtt.

**Comment by robertsLando** [comment]
Like I said, after a certain hass version hass started complain about undefined fields in payload, not a bid deal, but we could detect the affected values and take the correct approach based on it. Sometimes an undefined value is used to 'reset' a valueId, like for notifications

**Comment by frenck** [comment]
The question is: Do we even need those entity attributes? A general direction in Home Assistant, is to reduce those attributes as much as possible.  (Please note, this comment lack knowledge about the exact content of those attributes).

**Comment by emichael** [comment]
I'm seeing the same behavior as @drjjr2 with my GE switches, but I'm using the Json Time Value. The `scene_state_scene_001` and `scene_state_scene_002` sensors (the up and down buttons on the rocker switch) both don't report a value after they're no longer being pressed, so any time you press a button on the switch, you get a new warning in the log.

**Comment by robertsLando** [comment]
in general any `stateless` value by default gets an undefined message pèublished to reset the state after an event is received
