### ISSUE TITLE
[bug]FGS211

### ISSUE THREAD

**Issue by lvandenbussche** [zwave-js/zwavejs2mqtt#1022]
Hello,

since the last update of JS Zwave my FGS211 / FGS221 not return the status of one switch.
He works but I don’t know if is switch on or off.

Any idea ?

Thx

**Comment by robertsLando** [comment]
without any log it's difficult to debug

**Comment by lvandenbussche** [comment]
Sorry for my bad English
I can't see anything in the logs when I flip the switch.
No information

**Comment by AlCalzone** [comment]
Please read and follow the troubleshooting section on missing updates from devices:
https://zwave-js.github.io/node-zwave-js/#/troubleshooting/no-updates

You're going to need the `zwave-js` logs for that.

**Comment by davyrolink** [comment]
Seems to be the same issue as https://github.com/zwave-js/node-zwave-js/issues/2267

**Comment by AlCalzone** [comment]
Might be, but I'll need the full zwave-js logs including a re-interview to verify.
