### ISSUE TITLE
[feat] Add ability to enable basic events per-device

### ISSUE THREAD

**Issue by matejdro** [zwave-js/zwavejs2mqtt#1029]
**Is your feature request related to a problem? Please describe.**

Aeotec Nano Switch (zw116) has a config option that configures whether presses of the physical switch will toggle the state of the load directly or whether button press will only be passed to the gateway as basic set events.

By default, this setting is set to control the load directly. This is fine for most use cases as user would probably want connected light to toggle whenever he/she presses the switch.

However, I have smart bulb wired to that switch. Smart bulbs are controlled directly and you should not ever cut electricity to them. That is why Nano Switch that is wired to the bulb is always in the "ON" position and aforementioned config option is set to send basic set events to the gateway (these events then toggle the smart bulb via Home Assistant automation). That way I can retain both smart bulb features and physical switch to toggle the bulb.

However, with recent version, zwavejs seems to ignore these basic set events. I cannot find a way (without editing config files) to receive these events and process them in Home Assistant.

**Describe the solution you'd like**

It would be useful it there was a way to enable transmission of basic set events via MQTT on per device basis. Maybe by creating special value that would reflect last basic set event, similar to how OpenZwave did it when appropriate flags were enabled (https://github.com/OpenZWave/qt-openzwave/issues/60)?

**Describe alternatives you've considered**

I'm currently using modified config for nano switch (https://github.com/zwave-js/zwavejs2mqtt/issues/1011) with `treatBasicSetAsEvent` compatibility flag enabled. This works, but it is cumbersome, I'm not getting any config updates automatically and it is applied to all nano switches in my network (I only want this behavior on one).

**Comment by blhoward2** [comment]
Can you post some logs? It would be helpful to see what is being sent and where it's being ignored. We'll need the node-zwave-js log at a silly or debug level. 

Note that zwavejs2mqtt can't really do anything with this. There is no way for it to tell node-zwave-js to send basic events if node is ignoring them. That's not to say it can't be implemented but doing so would require upstream fixes too. 

What happens if you don't use the compat flag but enable the parameter and toggle it. Can you show us that too in a log? For some devices that'll work but not if the the endpoint the report is mapped to continues to control the relay.

**Comment by matejdro** [comment]
Huh I just checked and I seem to get the event even with `treatBasicSetAsEvent` disabled:

```
2021-04-11 08:25:11.991 INFO ZWAVE: Node 51: value notification: 32-0-event 0
2021-04-11 08:25:16.119 INFO ZWAVE: Node 51: value notification: 32-0-event 255
```

Maybe I screwed up something when testing before. Anyway, when this value notification happens, event will get emitted on `zwave/_EVENTS/ZWAVE_GATEWAY-zwavejs2mqtt/node/node_value_updated`:

```
{
    "data": [
        {
      ...
        },
        {
            "commandClassName": "Multilevel Switch",
            "commandClass": 38,
            "endpoint": 0,
            "property": "currentValue",
            "newValue": 0,
            "prevValue": 0,
            "propertyName": "currentValue"
        }
    ]
}
```

However, event is buried at the bottom of this very long JSON, making it a bit cumbersome to parse with Home Assistant templates. Any chance this value could be saved into some value instead of just being an event?

**Comment by blhoward2** [comment]
You have to restart and then reinterview the device after changing the config file.

**Comment by blhoward2** [comment]
@robertsLando another note about the event not showing up under 32

**Comment by matejdro** [comment]
I did restart and reinterview the device. It still works without compat options.

**Comment by blhoward2** [comment]
Ah, I misread it. The basic command class is 32 not 38. Without the compat flag it's being mapped to the multi sensor CC not treated as an event.

**Comment by matejdro** [comment]
Reading other issue, basic events being posted in their own topic is exactly what I want (https://github.com/zwave-js/zwavejs2mqtt/issues/1044#issuecomment-817585539). I think this can be closed as duplicate of the other issue.
