### ISSUE TITLE
[feat]HAve the possibility to declare a dead node

### ISSUE THREAD

**Issue by Sellig28** [zwave-js/zwavejs2mqtt#1030]
**Is your feature request related to a problem? Please describe.**
I takes ages to initialize my zawve network as I have some devices out of order and no possibility to remove them from my controller.

**Describe the solution you'd like**
I would like to force scanning a node of my choice. SO If I know if a node is dead and no more there, scanning zwave network will be faster.

**Describe alternatives you've considered**
same as upper.

**Additional context**

Because of some devices are no more there my network is almost not working, so finding a solution to force marking dead node could be the solution.

Thanks.

**Comment by robertsLando** [comment]
You should mark those nodes as failed. cc @AlCalzone

**Comment by AlCalzone** [comment]
> Because of some devices are no more there my network is almost not working, so finding a solution to force marking dead node could be the solution.

Uhm... Why don't you remove them with `removeFailedNode` then?

**Comment by Sellig28** [comment]
Sorry for my late answer.

I try to remove failed node from advanced button in node part.

here is the result:

2021-04-20 19:12:22.708 INFO ZWAVE: Timeout while waiting for an ACK from the controller removeFailedNode {
success: false,
message: 'Timeout while waiting for an ACK from the controller'
}
2021-04-20 19:12:26.959 INFO ZWAVE: Timeout while waiting for an ACK from the controller removeFailedNode {
success: false,
message: 'Timeout while waiting for an ACK from the controller'
}

**Comment by Sellig28** [comment]
the node is recognize as failed with yes status but the calling api failed.

2021-04-20 19:21:20.031 INFO ZWAVE: Calling api removeFailedNode with args: [ 14, [length]: 1 ]
2021-04-20 19:21:28.515 INFO ZWAVE: Timeout while waiting for an ACK from the controller removeFailedNode {
success: false,
message: 'Timeout while waiting for an ACK from the controller'
}

**Comment by Sellig28** [comment]
Ha just something which could be interesting ! I have two zwave lights bulb and unfortunatly I use them with a physical switch. the controller can see them as dead when not switch on. No idea for a new feature not to remove a false dead device.

Despite some bad api result, I succeed to remove the failed node. My error was not to choose the right option in the node part from advanced button and not refresh the web page which display old node state.

Noob question. Is this a software removal or a physical one from the controller ?

**Comment by AlCalzone** [comment]
I'm not entirely sure I understand the question, but the `removeFailed` and `replaceFailed` APIs remove the node from the stick's memory. The node itself will still think that it is part of the network, so it has to be reset in order to be re-included later.

**Comment by Sellig28** [comment]
Yes Sorry, I'm not always clear. Everything is ok, I just badly understand how to remove failed node.

As I said before, two bulb devices was removed as they are power on or off by a "normal" switch and unfortunatly was power at the time I do remove failed.

I have to reset my bulb node and re-include.

Sorry to disturb you for that, finally, it could be interesting for other to read that and understand better than me.

Thank you. If you are agree this issue can be closed.
