### ISSUE TITLE
[question] Has events stopped to work?

### ISSUE THREAD

**Issue by haavardNO** [zwave-js/zwavejs2mqtt#1032]
After a lot of problems with scene activation I transitioned to trigger on events in Home Assistant and Node Red.
After the I updated my systems this has stopped to work and I am not able to see any events in HASS on zwave_js_event.

Has there been any braking changes here?

**Comment by haavardNO** [comment]
Think I figured it out.
Had to change to zwave_js_value_notification. Then it works again :)

**Comment by robertsLando** [comment]
Fixed so?

**Comment by haavardNO** [comment]
Yes! 😊
