### ISSUE TITLE
Qubino 3-Phase Smart Meter support

### ISSUE THREAD

**Issue by snitkjaer** [zwave-js/zwavejs2mqtt#1033]
I would like to use the Qubino 3-Phase Smart Meter in HomeAssistant through zwavejs.

I can connect it through Zwave but only basic information get through however the meters like Power and Energy does not show.

<img width="1428" alt="Skærmbillede 2021-04-10 kl  16 33 48" src="https://user-images.githubusercontent.com/5526848/114273599-00042c00-9a1b-11eb-802a-fd3b1fda5edb.png">

If I connect it to HomeAssistant through a SmartThings Hub it works fine.

**Comment by robertsLando** [comment]
I need logs please

**Comment by snitkjaer** [comment]
Here is the node16 json
[node_16.json.txt](https://github.com/zwave-js/zwavejs2mqtt/files/6291663/node_16.json.txt)

Log files
[zwavejs_1.log](https://github.com/zwave-js/zwavejs2mqtt/files/6291683/zwavejs_1.log)
[zwavejs2mqtt.log](https://github.com/zwave-js/zwavejs2mqtt/files/6291684/zwavejs2mqtt.log)

As far as I can tell the metered values do get published to MQTT like the power
zwave/Skur_-_EV_meter/50/1/value/66049

**Comment by robertsLando** [comment]
Hummmm this is so strange, what version are you running?

**Comment by snitkjaer** [comment]
I was on
zwavejs2mqtt 3.2.0
zwavejs 7.1.1
Home Assistant 2021.3.4

I just did a docker-compose pull and restarted my containers and now it works... really strange but now it works :-)

Thanks for looking at it!
