### ISSUE TITLE
[bug] Qubino ZMNHJD (flush pilot) - bad multilevel switch discovery

### ISSUE THREAD

**Issue by joffrey71** [zwave-js/zwavejs2mqtt#1035]
### Version

**Checklist:**

- [x] I am **not** using HomeAssistant. **Or:** a developer has told me to come here.
- [x] I have checked the troubleshooting section and my problem is **not** described there.
- [x] I have read the changelog problem was **not** mentioned there.

Build/Run method

- [x] Docker
- [ ] PKG
- [ ] Snap package
- [ ] Manually built (git clone - npm install - npm run build )

zwavejs2mqtt version: 3.2.0
zwave-js version: 7.1.1

### Describe the bug

One of my Qubino ZMNHJD1 (the lastest bought) does not discover Multilevel Switch (use for the flush pilot wire).
When interview's done, I get 2 switch (number 2 and 3) but I should have only one (number 0).

![image](https://user-images.githubusercontent.com/23659848/114285056-69546100-9a54-11eb-9451-ac4f0733db81.png)

### To Reproduce

1. Include Qubino ZMNHJD1
2. Wait node complete
3. Check Multilevel Switch discovering

### Expected behavior

It was OK in the version 2.4.X

![image](https://user-images.githubusercontent.com/23659848/114285084-a1f43a80-9a54-11eb-804c-3c41e80466ef.png)

### Additional context

I have 2 others older Qubino ZMNHJD1 and they work fine in the last version 3.2.0

You can find more infos (Node 24) in my logfiles :
[zwavejs_1.log](https://github.com/zwave-js/zwavejs2mqtt/files/6290799/zwavejs_1.log)
[zwavejs2mqtt.log](https://github.com/zwave-js/zwavejs2mqtt/files/6290803/zwavejs2mqtt.log)

Thanks

**Comment by robertsLando** [comment]
@AlCalzone

**Comment by AlCalzone** [comment]
@joffrey71 can you do one more re-interview with loglevel "debug"? I can't see everything but the device does both report 3 endpoints and 1 endpoint. This usually happens for devices that offer an additional endpoint when an external sensor is connected. These require to be excluded (without resetting) and re-included for the changed capabilities to take full effect.

**Comment by joffrey71** [comment]
@AlCalzone  here le debug log files : 
[zwavejs2mqtt (1).log](https://github.com/zwave-js/zwavejs2mqtt/files/6294663/zwavejs2mqtt.1.log)
[zwavejs_1 (1).log](https://github.com/zwave-js/zwavejs2mqtt/files/6294664/zwavejs_1.1.log)

I tried to exclude (without resetting) and re-include the device but I got the same Multilevel Switch values.

I don't know why I have this 2 extra multilevel switch (number 2 and 3) becasue I only wire the Neutral lead et the Live lead like it's mentionned in the documentation :
[qubino-flush-pilot-wire-plus-user-manual-v1-1-eng.pdf](https://github.com/zwave-js/zwavejs2mqtt/files/6294689/qubino-flush-pilot-wire-plus-user-manual-v1-1-eng.pdf)

**Comment by AlCalzone** [comment]
@joffrey71 how old is that device? My contact at Qubino mentioned that it had been discontinued before 2016, but your comment sounds like you recently bought it.

**Comment by joffrey71** [comment]
@AlCalzone I bought this one last January on [amazon.](https://www.amazon.fr/ZMNHJD1-Module-pilote-radiateur-%C3%A9lectrique/dp/B01HHCCVGY)  
I have 2 others Qubino like this one that I bought in second hands and they both work great.

So to my mind the one not working is the mosy recent. 

When I check the working Qubino devices, I noticed that it's a older version than the broken one :
![Screenshot_20210412_230813](https://user-images.githubusercontent.com/23659848/114462910-01cd1b80-9be4-11eb-9032-edf1cff38060.jpg)
 
But it was working fine in 2.4.X version.

**Comment by AlCalzone** [comment]
I'm guessing this only comes to light now because of some changes to endpoint handling we did. Ultimately the device is contradicting itself when asked for the number of endpoints. You're seeing the values for endpoint 2, because it does respond when we query which kind of multilevel switch endpoint 2 is.

I'll have to think how to best work around the problem.

**Comment by AlCalzone** [comment]
@joffrey71 can you test https://github.com/zwave-js/node-zwave-js/pull/2329 please?
https://zwave-js.github.io/zwavejs2mqtt/#/troubleshooting/docker_custom_builds for details how to do that.

**Comment by joffrey71** [comment]
@AlCalzone Thanks for the fix, it's working as expected. After re-interviewed the node, I have the right Multilevel Switch.

Do you plan to merge  this branch in master and release it  ?

Great jobs again 👍  !

**Comment by AlCalzone** [comment]
Now that I have confirmation, I will.
