### ISSUE TITLE
Confusing usage of valueId in _addSceneValue/_removeSceneValue

### ISSUE THREAD

**Issue by BlackLight** [zwave-js/zwavejs2mqtt#1043]
The docs [report the signature of `_addSceneValue`](https://zwave-js.github.io/zwavejs2mqtt/#/guide/mqtt?id=apis) as `_addSceneValue(sceneId, valueId, value, timeout)`.

One would think that `valueId` is the ID of a value, but if you pass `valueId` as a string all you get is:

```
Node undefined not found
```

Which is weird, considering that no node information should be explicitly passed, according to the docs.

When I [look at the source code](https://github.com/zwave-js/zwavejs2mqtt/blob/58f4368fa83751eb06056c783acaff973fa66770/lib/ZwaveClient.js#L2006), however, I see that the `nodeId` and other attributes are apparently expected to be present on `valueId`. That really doesn't match the expected signature. Passing the whole value when only the ID is actually need is very redundant, and at the very least the expected schema should be documented.

**Comment by BlackLight** [comment]
Ok, I have just noticed that `valueId` is actually defined as an object [here](https://zwave-js.github.io/node-zwave-js/#/api/valueid?id=valueid).

I still find it very confusing to have an `*Id` field that is actually an object. What's the reason not to go for an approach where `valueId` can be a string in the format `<nodeId>-<commandClass>-<endpoint>-<property>`?

**Comment by robertsLando** [comment]
> What's the reason not to go for an approach where valueId can be a string in the format <nodeId>-<commandClass>-<endpoint>-<property>

There is no particular reason, just a matter of preference :)

**Comment by robertsLando** [comment]
This now is much more clear with Typescript. Closing it :)
