### ISSUE TITLE
[feat] Z-wave congestion indicator

### ISSUE THREAD

**Issue by jaimevisser** [zwave-js/zwavejs2mqtt#1052]
**Is your feature request related to a problem? Please describe.**
I have a large (50+ devices), compact z-wave network and am trying to figure out how often I can let sensors report without congesting the z-wave network.

**Describe the solution you'd like**
I'd love it if there was some utilisation/dropped packets/delayed packets indication on the management panel (or exposed as a sensor to mqtt/HA) so I can see when I need to dial down reporting intervals.

**Describe alternatives you've considered**
I'm currently monitoring updates from sensors using influx/grafana but this doesn't give a good indication of congestion on the z-wave network.

**Additional context**
N/A.

**Comment by robertsLando** [comment]
This needs stats on zwave-js, it is currently an open feature request.

cc @AlCalzone

**Comment by robertsLando** [comment]
Follow updates here: https://github.com/zwave-js/node-zwave-js/issues/985
