### ISSUE TITLE
Binary Switch target value misleading

### ISSUE THREAD

**Issue by mrherman** [zwave-js/zwavejs2mqtt#1065]
The UI for switching a binary switch is a bit misleading.  Since the True/False lights up it indicates the last command sent; however, at GUI start it doesn't align with the current value or if the current value is changed via mqtt.  The colorful button also stands out more than the plain text of the current value next to it so it draws the users focus there which could lead to confusion on what the current state is.

<img width="492" alt="firefox_hhVzWzo0B3" src="https://user-images.githubusercontent.com/1773927/114921111-30234480-9df8-11eb-8b8e-e3ebdf01142e.png">

**Comment by robertsLando** [comment]
Targt value has no state

**Comment by mrherman** [comment]
> 
> 
> Target value has no state, you just use it to send commands

I think that is my point, but the UI contains a state (if true or false is lit up).  Programmatically it still works, but is confusing (obviously that's an opinion)  The target binary value UI shouldn't have a state.

**Comment by Madelaide** [comment]
I agree, the filled background implies a state. I would prefer a choice of 2, none selected until the user selects one and sends the command.

**Comment by robertsLando** [comment]
I could remove the fill if that makes confusion

**Comment by robertsLando** [comment]
I just checked and it seems that the value has 2 states as it is also readable. The state should be persisted btw it could be that targetValue is different from current

**Comment by Madelaide** [comment]
I am not sure what you meant in the previous note, but unfilled would be clearer.  Even more clear would be to change the 'Current State" to match. ie in the initial post, "current state is true" and "target value is OFF"; for me, ideally the terminology would be consistent, so True and TRUE/FALSE, or ON, and ON/OFF, respectively.

**Comment by robertsLando** [comment]
The valueId has two properties `readable` and `writable`. If it is also `readable` it means it also provides a state, the state in that 'widget' is shown by filling the ON/OFF button

**Comment by mrherman** [comment]
I think my only comment is that on page load the state (by default) it shows OFF, but at that point I guess it is stateless (never been pushed) or just hasn't been read.

If the only thing that it shows is the last state selected that probably doesn't need to be displayed.  You mentioned that it is a readable property, if you show state based on a read value that would also make sense (maybe there are devices out there where this readable property is important); however, I don't think that is happening (atleast at page load) because the state will be different between refreshing the page (on before the refreash/off after).

**Comment by AlCalzone** [comment]
@robertsLando I agree with @mrherman. The default looks like its OFF when it is `undefined` or unknown.

**Comment by robertsLando** [comment]
I have submitted a fix for this. Now the type is checked and musty be `true` or `false` in order to 'select' a ON or OFF state
