### ISSUE TITLE
[bug] Need a fullpage refresh to get association groups populated for new devices

### ISSUE THREAD

**Issue by jmgiaever** [zwave-js/zwavejs2mqtt#1072]
### Version

**Checklist:**

- [x] I am **not** using HomeAssistant. **Or:** a developer has told me to come here.
- [x] I have checked the troubleshooting section and my problem is **not** described there.
- [x] I have read the changelog problem was **not** mentioned there.

Build/Run method

- [ ] Docker
- [ ] PKG
- [x] Snap package
- [ ] Manually built (git clone - npm install - npm run build )

zwavejs2mqtt: 3.3.0.b2f3402
zwave-js: 7.2.2

### Describe the bug

When a new device is added the list of association groups is not populated. 

![Screenshot from 2021-04-17 08-58-34](https://user-images.githubusercontent.com/7188121/115104905-0be07880-9f5c-11eb-9eea-fbbc19919ac0.png)

You have to do a fullpage refresh to fill the list.

### To Reproduce

1. add new device
2. wait for it to complete the inclusion
3. go to groups and select the dropdown
4. now do a refresh of the page and the list should be populated

### Expected behavior

List to be populated with the groups

**Comment by robertsLando** [comment]
Will look at this on Monday :)

**Comment by jmgiaever** [comment]
PR i made for [zwjs](https://github.com/zwave-js/node-zwave-js/pull/2382#issuecomment-821791044).
