### ISSUE TITLE
What is Session_secret for?

### ISSUE THREAD

**Issue by ParadingLunatic** [zwave-js/zwavejs2mqtt#1077]
I noticed the only place the environment variable SESSION_SECRET is mentioned is in the docker compose yml....but there's no documentation that states what it's used for.  It's not mentioned anywhere else.

What in the world is it for?

**Comment by ParadingLunatic** [comment]
Ok so I found this in the documentation "Used as secret for session. If not provided the default one is used"

Still not exactly sure what it means though.

**Comment by robertsLando** [comment]
It's used by express session: https://github.com/expressjs/session#secret

**Comment by shred86** [comment]
Can Docker secrets be used to set `SESSION_SECRET`? Example, `SESSION_SECRET=/run/secrets/zwave_session_secret`?

I just recently started using Docker secrets and updating my docker-compose.yml but I can't tell if Z-Wave UI is actually compatible or if it's just using the default session secret. Thanks!

**Comment by robertsLando** [comment]
> Can Docker secrets be used to set SESSION_SECRET

**Comment by shred86** [comment]
Sorry for my ignorance but while I understand it’s an env var, I was under the impression the Docker image has to support reading an env var from a file. For example, [Frigate](https://github.com/blakeblackshear/frigate/discussions/6250#discussioncomment-5805337)  does not currently support setting an env var from a file. Another example is this Samba Timemachine Docker container [where you can see checks](https://github.com/mbentley/docker-timemachine/blob/ec1f6b12fdda81b7aac31ab502f24a83364b8b00/entrypoint.sh#L51)  if you’re using a separate env var that supports pulling from a file.

**Comment by robertsLando** [comment]
Sorry I misunderstood your question. In order to be able to use docker secret we need to read them from container, this module could help with this: https://www.npmjs.com/package/docker-secret. Would you like to submit a feature request for that?

@chrisns anything against this?

**Comment by chrisns** [comment]
there should be no need to use the module. you could have a thing of reading the file from `/run/secrets/SESSION_SECRET`
all that lib does is read the file like ^
