### ISSUE TITLE
[feat] Ability to query based on node parameters / generate reports

### ISSUE THREAD

**Issue by kelchm** [zwave-js/zwavejs2mqtt#1078]
**Is your feature request related to a problem? Please describe.**
As the size of my Z-Wave network grows, doing things like finding which nodes of a particular model have out of date firmware has increasingly become a chore. Similarly, there's no mechanism to easily find that nodes may not have a configuration parameter set to the 'standard' value for my uses.

**Describe the solution you'd like**
Ideally I'd like a mechanism to ask zwavejs2mqtt to provide me a filtered list of nodes based on things like:
- Having a firmware firmware version lower than some value
- A config parameter which is not set to a certain value

**Describe alternatives you've considered**
This type of reporting is likely possible via MQTT -- perhaps we could generate some better documentation / examples around these types workflows? I admittedly also haven't looked at the capabilities of the API -- it might be possible to accomplish the same goal by writing a script to query the API and write the results to a csv file, etc.

**Comment by robertsLando** [comment]
You could use the `getNodes` api to get all nodes and make a script to filter them by your needs. This would be quite easy to do with node-red.
