### ISSUE TITLE
[bug] Missing sensors for three (of four) of the Octan NodOn Remote Controller scenes

### ISSUE THREAD

**Issue by katiuskt** [zwave-js/zwavejs2mqtt#108]
**Version**

Build/Run method
- [X] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build ) 

zwavejs2mqtt version: I'm not sure how to get this. I'm using zwavejs/zwavejs2mqtt:dev pulled on 24th Dec

**Describe the bug**
Missing HASS devices for NodOn Octan Remote Controller CRC-3100.
Manufacturer ID: 357
Product Type: 2
Product ID: 1

Once you hace included your Noctan Octan remote controller into the ZWave network, with this configuration (Central Scene):
![image](https://user-images.githubusercontent.com/75622100/103091423-6c862700-45f4-11eb-8a2c-dca12291fd66.png)

Each botton is identified like this into ZWaveJS2MQTT GUI:
![image](https://user-images.githubusercontent.com/75622100/103091459-8b84b900-45f4-11eb-87df-d6e1ede3def9.png)

Meaning, each one is identified by [node]-91-0-scene-00X with X=1, 2, 3, 4

However, not all of them are "converted" to devices for HASS. 

"sensor_scene_state" is for topic "91/0/slowRefresh"
![image](https://user-images.githubusercontent.com/75622100/103091584-e28a8e00-45f4-11eb-9e76-9adc80cfc75e.png)

And the relevant one "sensor_scene_state_0" is created for topic "91/0/scene/002":
![image](https://user-images.githubusercontent.com/75622100/103091629-06e66a80-45f5-11eb-9aa8-fe0f88833a13.png)

There are no devices for scenes 001, 003 or 004 hence HASS isn't aware when you click (or double click or hold,...) the other three buttons.

I've defined these devices manually and it did the trick. 
Note: The "sensor_scene_state_02" is basically the same than the automatically discovered "sensor_scene_state_0" but just assigning a name with the same pattern than the 01/03/04 to make it a little bit more consistent:

```
{
  "type": "sensor",
  "object_id": "scene_state_01",
  "discovery_payload": {
    "state_topic": "zwavejs/LR/RemoteNodOn/91/0/scene/001",
    "value_template": "{{ value_json.value}}",
    "json_attributes_topic": "zwavejs/LR/RemoteNodOn/91/0/scene/001",
    "device": {
      "identifiers": [
        "zwavejs2mqtt_0xf77d3d75_node9"
      ],
      "manufacturer": "ID-RF",
      "model": "Octan Remote Control (CRC-3100)",
      "name": "LR-RemoteNodOn",
      "sw_version": "2.3"
    },
    "name": "LR-RemoteNodOn_scene_state_01",
    "unique_id": "zwavejs2mqtt_0xf77d3d75_9-91-0-scene-001"
  },
  "discoveryTopic": "sensor/LR-RemoteNodOn/scene_state_001/config",
  "values": [
    "91-0-scene-001"
  ],
  "persistent": false,
  "ignoreDiscovery": false,
  "id": "sensor_scene_state_01"
}

{
  "type": "sensor",
  "object_id": "scene_state_02",
  "discovery_payload": {
    "state_topic": "zwavejs/LR/RemoteNodOn/91/0/scene/002",
    "value_template": "{{ value_json.value}}",
    "json_attributes_topic": "zwavejs/LR/RemoteNodOn/91/0/scene/002",
    "device": {
      "identifiers": [
        "zwavejs2mqtt_0xf77d3d75_node9"
      ],
      "manufacturer": "ID-RF",
      "model": "Octan Remote Control (CRC-3100)",
      "name": "LR-RemoteNodOn",
      "sw_version": "2.3"
    },
    "name": "LR-RemoteNodOn_scene_state_02",
    "unique_id": "zwavejs2mqtt_0xf77d3d75_9-91-0-scene-002"
  },
  "discoveryTopic": "sensor/LR-RemoteNodOn/scene_state_002/config",
  "values": [
    "91-0-scene-002"
  ],
  "persistent": false,
  "ignoreDiscovery": false,
  "id": "sensor_scene_state_02"
}

{
  "type": "sensor",
  "object_id": "scene_state_03",
  "discovery_payload": {
    "state_topic": "zwavejs/LR/RemoteNodOn/91/0/scene/003",
    "value_template": "{{ value_json.value}}",
    "json_attributes_topic": "zwavejs/LR/RemoteNodOn/91/0/scene/003",
    "device": {
      "identifiers": [
        "zwavejs2mqtt_0xf77d3d75_node9"
      ],
      "manufacturer": "ID-RF",
      "model": "Octan Remote Control (CRC-3100)",
      "name": "LR-RemoteNodOn",
      "sw_version": "2.3"
    },
    "name": "LR-RemoteNodOn_scene_state_03",
    "unique_id": "zwavejs2mqtt_0xf77d3d75_9-91-0-scene-003"
  },
  "discoveryTopic": "sensor/LR-RemoteNodOn/scene_state_003/config",
  "values": [
    "91-0-scene-003"
  ],
  "persistent": false,
  "ignoreDiscovery": false,
  "id": "sensor_scene_state_03"
}

{
  "type": "sensor",
  "object_id": "scene_state_04",
  "discovery_payload": {
    "state_topic": "zwavejs/LR/RemoteNodOn/91/0/scene/004",
    "value_template": "{{ value_json.value}}",
    "json_attributes_topic": "zwavejs/LR/RemoteNodOn/91/0/scene/004",
    "device": {
      "identifiers": [
        "zwavejs2mqtt_0xf77d3d75_node9"
      ],
      "manufacturer": "ID-RF",
      "model": "Octan Remote Control (CRC-3100)",
      "name": "LR-RemoteNodOn",
      "sw_version": "2.3"
    },
    "name": "LR-RemoteNodOn_scene_state_04",
    "unique_id": "zwavejs2mqtt_0xf77d3d75_9-91-0-scene-004"
  },
  "discoveryTopic": "sensor/LR-RemoteNodOn/scene_state_004/config",
  "values": [
    "91-0-scene-004"
  ],
  "persistent": false,
  "ignoreDiscovery": false,
  "id": "sensor_scene_state_04"
}
```

Is it possible for ZWaveJS2MQTT to autodiscover the four scenes and not just one of them? Or am I missing something?

Thank you in advance

**Comment by robertsLando** [comment]
@katiuskt Is there a valueId in control panel for those values? Could you shwom me the console log? Also could you export the node from the contorl panel and attach it here?

**Comment by katiuskt** [comment]
Yes, in control panel I can see the 4 scenes and a switch/option I didn't saw before at OZW. Only one scene + that switch creates a HASS device:
![imagen](https://user-images.githubusercontent.com/75622100/103155264-4a300d00-479e-11eb-9400-ee52a0c41b7d.png)

Here you have the node JSON exported from GUI: 
[node_9.zip](https://github.com/zwave-js/zwavejs2mqtt/files/5743328/node_9.zip)

Regarding the console log, I'm afraid I'm not sure how to get that. I set "Log Level = Debug" and "Log to file" is selected but I'm not able fo find any log (I look into the same folder I passed to the docker (where I can see the settings.json, nodes.json,... and that stuff).

Taking a look at the docker log I can see this (but I'm not sure it helps you). Be aware 

> 2020-12-26 16:21:44.837 INFO ZWAVE: Node 9 is now asleep
> 2020-12-26 16:21:59.029 INFO ZWAVE: Node 9: value updated: 91-0-scene-003
> 2020-12-26 16:21:59.117 INFO ZWAVE: Node 9 is now awake
> 2020-12-26 16:22:02.419 INFO ZWAVE: Node 9: value updated: 128-0-level
> 2020-12-26 16:22:02.421 INFO ZWAVE: Node 9: value updated: 128-0-isLow
> 2020-12-26 16:22:12.439 INFO ZWAVE: Node 9 is now asleep
> 2020-12-26 16:22:17.910 INFO ZWAVE: Node 9: value updated: 91-0-scene-003
> 2020-12-26 16:22:17.999 INFO ZWAVE: Node 9 is now awake
> 2020-12-26 16:22:18.228 INFO ZWAVE: Node 9: value updated: 132-0-wakeUpInterval
> 2020-12-26 16:22:18.231 INFO ZWAVE: Node 9: value updated: 132-0-controllerNodeId
> 2020-12-26 16:22:18.457 INFO ZWAVE: Node 9: value updated: 132-0-wakeUpInterval
> 2020-12-26 16:22:18.459 INFO ZWAVE: Node 9: value updated: 132-0-controllerNodeId
> 2020-12-26 16:22:18.513 INFO ZWAVE: Node 9: metadata updated: 112-0-1
> 2020-12-26 16:22:18.516 INFO ZWAVE: Node 9: metadata updated: 112-0-2
> 2020-12-26 16:22:18.519 INFO ZWAVE: Node 9: metadata updated: 112-0-3
> 2020-12-26 16:22:18.521 INFO ZWAVE: Node 9: metadata updated: 112-0-4
> 2020-12-26 16:22:18.524 INFO ZWAVE: Node 9: metadata updated: 112-0-5
> 2020-12-26 16:22:18.527 INFO ZWAVE: Node 9: metadata updated: 112-0-6
> 2020-12-26 16:22:18.529 INFO ZWAVE: Node 9: metadata updated: 112-0-7
> 2020-12-26 16:22:18.532 INFO ZWAVE: Node 9: metadata updated: 112-0-8
> 2020-12-26 16:22:18.687 INFO ZWAVE: Node 9: value updated: 132-0-wakeUpInterval
> 2020-12-26 16:22:18.690 INFO ZWAVE: Node 9: value updated: 132-0-controllerNodeId
> 2020-12-26 16:22:18.921 INFO ZWAVE: Node 9: value updated: 112-0-1
> 2020-12-26 16:22:19.151 INFO ZWAVE: Node 9: value updated: 112-0-2
> 2020-12-26 16:22:19.392 INFO ZWAVE: Node 9: value updated: 112-0-3
> 2020-12-26 16:22:19.611 INFO ZWAVE: Node 9: value updated: 112-0-4
> 2020-12-26 16:22:19.841 INFO ZWAVE: Node 9: value updated: 112-0-5
> 2020-12-26 16:22:20.079 INFO ZWAVE: Node 9: value updated: 112-0-6
> 2020-12-26 16:22:20.301 INFO ZWAVE: Node 9: value updated: 112-0-7
> 2020-12-26 16:22:20.531 INFO ZWAVE: Node 9: value updated: 112-0-8
> 2020-12-26 16:22:22.198 INFO ZWAVE: Node 9: interview completed, all values are updated
> 2020-12-26 16:22:23.291 INFO ZWAVE: Node 9 is now asleep

**Comment by billiaz** [comment]
@katiuskt is this the soft remote?
An node export would help

**Comment by billiaz** [comment]
@robertsLando I observe the same behaviour on my NodOn soft remote. I will debug further with it.
@katiuskt
