### ISSUE TITLE
[bug] ZW074 MultiSensor Gen5 motion sensor doesn't reset

### ISSUE THREAD

**Issue by matteskonto** [zwave-js/zwavejs2mqtt#1089]
### Version

Build/Run method

- [ ] Docker (HomeAssistant AddOn)

zwavejs2mqtt: 3.5.0
zwave-js: 7.2.4

### Describe the bug

The motion sensor of AEON Labs ZW074 MultiSensor Gen5 doesn´t return from "7 - Motion Detected" after first trigger.
When I re-interview the node I get no motion on the sensor but when motion is first detected then it never resets again until I re-Interview again. Refresh values etc. does not fix this.

### To Reproduce

Re-Interview node, no motion is detected.
Wave in front of the sensor and motion is triggered
Motion is never reset.

After a re-interview the motion is not triggered until a "real" motion so the sensor is working correctly. The sensor is powered by mains and has a good link to the controller, all other values (temp, lux, humidity) are updating just fine.

### Expected behavior

Motion should be reset after 240 sec

### Additional context

The sensor was working fine until some weeks ago after an update and I haven't update or changed any configuration on the sensor recently.

[node_43.json.txt](https://github.com/zwave-js/zwavejs2mqtt/files/6348472/node_43.json.txt)

Logs seems to indicate that the reset command is incorrectly interpreted as value 7?

2021-04-21 08:03:48.474 INFO ZWAVE: Node 43: metadata updated: 48-0-Any
2021-04-21 08:03:48.477 INFO ZWAVE: Node 43: value updated: 48-0-Any false => true
2021-04-21 08:03:48.680 INFO ZWAVE: Node 43: value updated: 113-0-Home Security-Motion sensor status 0 => 7
2021-04-21 08:07:52.993 INFO ZWAVE: Node 43: metadata updated: 48-0-Any
2021-04-21 08:07:52.995 INFO ZWAVE: Node 43: value updated: 48-0-Any true => false
2021-04-21 08:07:53.196 INFO ZWAVE: Node 43: value updated: 113-0-Home Security-Motion sensor status 7 => 7

**Comment by robertsLando** [comment]
> Logs seems to indicate that the reset command is incorrectly interpreted as value 7?

How was it interpreted before?

**Comment by matteskonto** [comment]
It should send "113-0-Home Security-Motion sensor status 7 => 0" to reset the motion but I don't know if it is interpretation or what the problem is. 

When I Re-Interview the node the value is reported correctly so I don't know.

The sensor was working great since Jan when I moved to Zwave JS but now some weeks ago the motion sensor is behaving like this.

**Comment by robertsLando** [comment]
Could you also provide zwave-js logs please. Let's see what @AlCalzone says about this

**Comment by AlCalzone** [comment]
We have recently disabled the auto-magic reset of notification variables after 5 minutes because there are some motion sensors that do send an idle notification and were broken by the auto-reset because they never triggered again.

To resolve it, the compat flag https://zwave-js.github.io/node-zwave-js/#/config-files/file-format?id=forcenotificationidlereset must be added to the config file for your sensor.

**Comment by blhoward2** [comment]
Closed with https://github.com/zwave-js/node-zwave-js/pull/2414
