### ISSUE TITLE
[bug] Name/Location restrictions differ from Home Assistant

### ISSUE THREAD

**Issue by justindthomas** [zwave-js/zwavejs2mqtt#1091]
### Version

**Checklist:**

- [X] I am **not** using HomeAssistant. **Or:** __a developer has told me to come here__.
- [X] I have checked the troubleshooting section and my problem is **not** described there.
- [X] I have read the changelog problem was **not** mentioned there.

Build/Run method

- [X] Docker
- [ ] PKG
- [ ] Snap package
- [ ] Manually built (git clone - npm install - npm run build )

zwavejs2mqtt version: 0.13.0
zwave-js version: 7.2.4 / 1.5.0

### Describe the bug

The Name and Area fields in zwavejs2mqtt don't allow apostrophes (single quotes). That puts it at odds with the other components in Home Assistant which all do and makes things inconsistent (e.g., I have to leave the fields blank in zwavejs2mqtt which will make it difficult to know what is what as I continue to add more devices).

I opened an issue at HomeAssistant Core and was redirected here.

### To Reproduce

1. Edit a name or location on a Zwave node in the ZwaveJS2MQTT console. Attempt to add an apostrophe.

![zwave name](https://user-images.githubusercontent.com/354734/115602349-b1188b00-a293-11eb-9d80-8f830d24d20c.png)

### Expected behavior

The field should accept the same types of characters as are otherwise allowed in Home Assistant. For example, I have an area called "Jacob's Room" defined in Home Assistant that I cannot assign in the ZwaveJS2MQTT console because of this restriction.

**Comment by robertsLando** [comment]
Nammes are also used on mqtt topics, some chars are not allowed

**Comment by justindthomas** [comment]
I've noticed that Home Assistant replaces problem characters with "_" in instances where there are limitations (so for the purposes of MQTT, "Jacob's Room" could be "jacob_s_room"), while keeping the display name intact.

**Comment by blhoward2** [comment]
IMO this isn't a bug. As @robertsLando says there are different requirements for mqtt. It would be a lot of unnecessary work to make the topic replace disallowed chars with an _ and then track and somehow display the original name. And it invites confusion among users because they'd need to use the sanitized topic name when interacting with mqtt regardless of what is displayed.

**Comment by justindthomas** [comment]
Seems like it's serving a dual purpose today (e.g., setting the parameters there will be copied over to HA upon a server restart - unless maybe it's already defined in HA? I haven't figured out exactly how that works yet) when it should be more explicitly defined.

If MQTT is the target, then it seems like maybe the Location could be eliminated in zwavejs2mqtt and just the name kept while specifying that it's the MQTT label. Let HA handle its areas and labels without trying to coordinate since the requirements are not compatible.

**Comment by blhoward2** [comment]
Many people use the location in mqtt. You can sort the topics by location, then device.

**Comment by justindthomas** [comment]
Okay. I'll close this since it doesn't seem like something that can be easily improved. I do think the Location integration with HA invites the kind of confusion you're trying to avoid in the topic naming.

Because it's a predefined list in HA, what happens if I assign a non-existing name for the location to approximate one that does exist? Like "Jacobs Room" instead of the already defined "Jacob's Room"? Does it create a second area that I then need to go in and clean up? If it does, can the unwanted name be deleted in HA or will the integration try to recreate it because it exists in zwavejs2mqtt and I want to use the punctuationally incorrect version for MQTT?

Trying to coerce the data in fields for one use-case as input for an incompatible use-case seems messy. But maybe that's a problem for another team to tackle (the HA integration folks). Thanks for your review and feedback!

**Comment by blhoward2** [comment]
It'll create a second area. If you change any of this after the fact in HA it doesn't clobber anything. What was in zjs2mqtt stays there and HA keeps the new name/location.
