### ISSUE TITLE
[bug] When refreshing a node, values are empty

### ISSUE THREAD

**Issue by billiaz** [zwave-js/zwavejs2mqtt#110]
After a Refresh Info command, values are empty

trying to fix this as also
1. UI has empty values
2. Log shows no values in console

**Comment by robertsLando** [comment]
Could you show me the logs when you send a refresh info command?

**Comment by robertsLando** [comment]
> Log shows no values in console

I think this is caused by some `logger.info(a,b,c)` that should be `logger.info(${a} ${b} ${c})`, something missed in the swtich to winston logger

**Comment by billiaz** [comment]
i made this change too, but still that was not the case. as node is not ready. values never updated in ui
