### ISSUE TITLE
[bug] Dark Theme - color fix required IMHO

### ISSUE THREAD

**Issue by Masterz69** [zwave-js/zwavejs2mqtt#1100]
### Version

**Checklist:**

- [ ] I am **not** using HomeAssistant. **Or:** a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is **not** described there.
- [X] I have read the changelog problem was **not** mentioned there.

Build/Run method

- [ ] Docker
- [ ] PKG
- [ ] Snap package
- [ ] Manually built (git clone - npm install - npm run build )
- [X] `HomeAssistant` version 2021.4.6

zwavejs2mqtt: 3.4.0
zwave-js: 7.2.4

### Describe the bug

F.e. configuration item descriptions still Black in Dark Theme - actually become unreadable.
![image](https://user-images.githubusercontent.com/15225823/116001479-5073b000-a5fd-11eb-8561-733ae8f6e07c.png)

### To Reproduce

1. Go to 'Z-Wave JS Control Panel'
2. Click on 'Dark Theme'
3. Scroll down to 'any device f.e. configuration'

### Expected behavior

Black text to become white in Dark Theme.

### Additional context

n/a

**Comment by robertsLando** [comment]
Already fixed on master :) see #1094
