### ISSUE TITLE
Disconnected neighbors in network graph

### ISSUE THREAD

**Issue by dvanderb** [zwave-js/zwavejs2mqtt#1110]
I have a fully healed network(healed yesterday) that is showing a set of devices as not connected to any neighbors, however when I view the data dump those devices(eg: Garage_Opener) have neighbors listed as appropriate.  Attached is the json dump and a screenshot.

Note: 2 devices are "dead" so those are expected to be disconnected which are Zooz_Double_Plug and BBQ_Island_Led

zwavejs2mqtt: 3.5.0
zwave-js: 7.2.4

![Screenshot 2021-04-27 7 15 26 AM](https://user-images.githubusercontent.com/873665/116256887-6e89ff00-a728-11eb-85fa-c3f65358c5b7.png)

[nodes_dump.txt](https://github.com/zwave-js/zwavejs2mqtt/files/6385227/nodes_dump.txt)

**Comment by robertsLando** [comment]
It could be that there is actually no node that forwords packets that have them as neighbors, try to enable. Try to expand options and on edges select All Neighbors

**Comment by dvanderb** [comment]
This seems to have magically resolved itself after adding another node..
