### ISSUE TITLE
[feat] stringify node export with tab on export

### ISSUE THREAD

**Issue by blhoward2** [zwave-js/zwavejs2mqtt#1119]
Currently, when you go to Advanced-->Export to export a node the resulting json is not stringified with tabs, making it very difficult to read:

{"id":97,"deviceId":"634-40970-28672","manufacturer":"Zooz","manufacturerId":634,"productType":28672,"productId":40970,"name":"","loc":"","values":[{"id":"97-37-0-currentValue","nodeId":97,"commandClass":37,"commandClassName":"Binary Switch","endpoint":0,"property":"currentValue","propertyName":"currentValue","type":"boolean","readable":true,"writeable":false,"label":"Current value","stateless":false,"list":false,"value":false,"isCurrentValue":true,"targetValue":"37-0-targetValue","lastUpdate":1619738791043,"newValue":false},{"id":"97-37-0-targetValue","nodeId":97,"commandClass":37,"commandClassName":"Binary Switch","endpoint":0,"property":"targetValue","propertyName":"targetValue","type":"boolean","readable":true,"writeable":true,"label":"Target value","stateless":false,"list":false,"value":false,"lastUpdate":1619738791045,"newValue":false},{"id":"97-37-0-duration",

It would be much easier to read and digest while providing support if it wasn't one massive block of text.

**Comment by robertsLando** [comment]
This could be easily formatted with any code editor out there (even online json formatters/viewer tools). Is this a bid deal? BTW the change to make it prettier is not so difficult

**Comment by blhoward2** [comment]
It can be formatted after the fact, sure, but if it's almost always going to be formatted when referenced then why not just do it up front?
