### ISSUE TITLE
Minimote (DSA03XXX-ZW) Interview stuck at Nodeinfo, ones which have been completed going back to Nodeinfo stage

### ISSUE THREAD

**Issue by kan84** [zwave-js/zwavejs2mqtt#1155]
1. Are you using HomeAssistant?
Confirmed with HA dev, its not a HA issue. Interview needs to be completed fire events originating from the node.
https://github.com/home-assistant/core/issues/50244

  2. Check the troubleshooting section if your problem is described there:
Logs for zwavejs attached. Did not find any log for zwavejs2mqtt with file name zwavejs2mqtt.log
Both are set to silly and I tried doing re interviews for couple. 
[zwave_js_dump.json.zip](https://github.com/zwave-js/zwavejs2mqtt/files/6442498/zwave_js_dump.json.zip)
[zwavejs2mqtt-store.zip](https://github.com/zwave-js/zwavejs2mqtt/files/6442500/zwavejs2mqtt-store.zip)

  3. Check the changelog if your problem was already fixed recently.
 I have the latest version in Docker. 
zwavejs2mqtt: 4.0.1
zwave-js: 7.3.0

  4. Make sure to provide the necessary information, as described here:
  https://zwave-js.github.io/zwavejs2mqtt/#/troubleshooting/bug_report
  
  If you are using HomeAssistant, this is how you do it:
  Home Assistant -> settings -> Integrations -> Z-Wave JS -> Configure -> Create dump -> zip the json file and post it here.

  🙏🏻🙏🏻🙏🏻 Thanks, now onto your issue:
-->

### Version

**Checklist:**

- [ X] I am **not** using HomeAssistant. **Or:** a developer has told me to come here.
- [ ] I have checked the troubleshooting section and my problem is **not** described there.
- [ ] I have read the changelog problem was **not** mentioned there.

Build/Run method

- [ X] Docker
- [ ] PKG
- [ ] Snap package
- [ ] Manually built (git clone - yarn install - yarn run build )

zwavejs2mqtt: 4.0.1
zwave-js: 7.3.0

### Describe the bug

I have three minimotes Node 8, 18 and 19 which have been working fine and I have been updating zwave version as well in Docker. Since last few days it stopped working turns out that interview stage is stuck at Nodeinfo. It starts at processinfo and when i wake the device it moves to Nodeinfo and then its stuck even after waking device multiple times. 

I was able to somehow pair Node 8 accidentally by waking it multiple times twice, it starts working in HA etc but then it goes back to NodeInfo stage again and then stops working. 18 I have been waking the device multiple times to complete interview but no luck.

Also another pecuiliar thing I noticed is popup on top right notification to download latest config. Might be unrelated but whenever i try to interview minimote at some point it pops up.

### To Reproduce

Goto dashboard and check interview status of minimotes. Screenshot attached
![image](https://user-images.githubusercontent.com/23491305/117467024-4e74ef80-af21-11eb-8b5f-b3757379105d.png)

### Expected behavior
Interview should be complete so that Home Assistant can use the remote fire event for doing operation like automation

### Additional context

One logs and zwavejs dump from homeassistant attached. Let me know anything else is required, HA version is 2021.5.0
Added zwavejs2mqtt log as well i had forgot to turn on logging to file. 
[zwavejs2mqtt-store(1).zip](https://github.com/zwave-js/zwavejs2mqtt/files/6442734/zwavejs2mqtt-store.1.zip)

**Comment by robertsLando** [comment]
@AlCalzone

**Comment by AlCalzone** [comment]
Last seen: never?

Looks like the cache files got lost altogether if both zwave-js and zwavejs2mqtt think they have never talked to the node.

**Comment by kan84** [comment]
Also node 8 shows last seen as never but when i press any button I can see the event in debug

2021-05-07 12:04:01.537 INFO ZWAVE: Node 8: value added 8-43-0-sceneId => 1
2021-05-07 12:04:01.541 INFO ZWAVE: Node 8: value notification: 43-0-sceneId 1
2021-05-07 12:04:01.545 INFO ZWAVE: Node 8: value added: 43-0-dimmingDuration => [Duration: 0 seconds]

![image](https://user-images.githubusercontent.com/23491305/117477920-8df50900-af2c-11eb-9759-55aafaf32e29.png)

**Comment by josco95** [comment]
I'm having similar issues with a pair of Zooz ZSE40s 4-in-1 sensors which stopped reporting motion after a container update today to the same version ( zwavejs2mqtt: 4.0.1, zwave-js: 7.3.0 ). They were perfectly fine before the update, but now after an exclude/reset/include cycle, it just sits at NodeInfo and doesn't seem to get any further.

**Comment by AlCalzone** [comment]
@kan84 your device is asleep, so the interview can't progress until you wake it up.
If that doesn't help, please share a zwave-js (driver) log with loglevel `"debug"`, so we can see whats going on.

**Comment by kan84** [comment]
@AlCalzone Uploaded both the logs after setting it to debug
1) Woke node 18 and 19 multiple times, could see awake on the dashboard
2) All three minimotes last seen was never. 
2) Node 8, did not try waking it up but can see button event in log. 
[zwavejs2mqtt-store.zip](https://github.com/zwave-js/zwavejs2mqtt/files/6448064/zwavejs2mqtt-store.zip)

**Comment by kan84** [comment]
I did not restart anything on the server. Two days back when you mentioned that it has become never, I woke up the device and it got a timestamp at that point of time. After that I never checked anything until I saw your reply today and when I opened the dashboard it showed never again. 
What I can try doing is leave both logs to debug and see if I can  capture it when it rolls back to never?

**Comment by AlCalzone** [comment]
> What I can try doing is leave both logs to debug and see if I can capture it when it rolls back to never?

You can do that, but please delete your current logfile first, so we don't have any old data. And make sure that the re-interview actually completes. Node 18 never finishes the interview in your last log because it goes back to sleep first.

**Comment by kan84** [comment]
Ok will do. Another thing I saw is on top right it showed a notification that driver has been destroyed as it is not ready or not available. 
I ll try completing interview by waking device 5-10 times and then send the log.

**Comment by AlCalzone** [comment]
> Another thing I saw is on top right it showed a notification that driver has been destroyed as it is not ready or not available.

That could be a crash. @robertsLando do we have any way to find out **why** a driver instance was destroyed?

**Comment by robertsLando** [comment]
> That could be a crash. @robertsLando do we have any way to find out why a driver instance was destroyed?

I destroy the driver in only two cases:

- When the start fails
- When the ZwaveClient is closed (this can happen when the user submits new settings for example)

Based on the logs sent I don't understand what's going on as in z2m logs I don't see restarts, in zwavejs logs I see repeated driver destroy and I think that's from a failed start

**Comment by AlCalzone** [comment]
The zwave-js logfile includes some very old logs, only the last start is on v7.3.0. That's why I asked him to delete the old logs first.

**Comment by kan84** [comment]
Uploading updated logs, I deleted the old files.
I did tried pairing 18 and 19 node by waking it multiple times during the day yesterday but no luck. Did initiate re-interview multiple times still no luck. Previously the device will complete interview in one go (One awake) and then in subsequent awakes you could configure it as scene controller. 
The last seen values are still present for both the nodes. I will try un-pairing and re-pairing at least one of the minimotes and see if it helps. 
[zwavejs2mqtt-store.zip](https://github.com/zwave-js/zwavejs2mqtt/files/6452294/zwavejs2mqtt-store.zip)

**Comment by kan84** [comment]
Thanks, will try doing this. Just to be clear, I will initiate Interview once and then keep waking the device when it goes to sleep. 
I should not re-interview the log, need to do it once and then keep waking the device when it goes to sleep in log until its complete right?
