### ISSUE TITLE
[HASS] zwavejs and zwavejs2mqtt no longer working together after upgrade to core-2021.5.0

### ISSUE THREAD

**Issue by dhomoney** [zwave-js/zwavejs2mqtt#1156]
[zwavejs_374.zip](https://github.com/zwave-js/zwavejs2mqtt/files/6443377/zwavejs_374.zip)
[zwavejs2mqtt-store.zip](https://github.com/zwave-js/zwavejs2mqtt/files/6443378/zwavejs2mqtt-store.zip)

### Version

Hass OS on Raspberry Pi 4

Docker
Git Clone + yarn install + yarn run build + yarn start
Pkg

zwavejs2mqtt version: 4.0.1
zwavejs version: 7.3.0

### Describe the bug

After upgrading to HA to core-2021.5.0 zwavejs and zwavejs2mqtt no longer work together. They lock each other out of comms with the zwave controller, whichever one starts first wins. Error at the top of the zwavejs2mqtt panel is "Driver: Error Resource temporarily unavailable Cannot lock port" as you will also see in the logs.

**Comment by blhoward2** [comment]
You can only run one addon. You could only ever run one addon. You should be running one addon or the other and the integration.
