### ISSUE TITLE
Log file rotation

### ISSUE THREAD

**Issue by steve28** [zwave-js/zwavejs2mqtt#1158]
**Is your feature request related to a problem? Please describe.**
Log files grow unbounded.  This can lead to issues when detailed logging levels are selected or an installation has been running for a long time.

**Describe the solution you'd like**
Rotate the `zwavejs2mqtt.log` and zwavejs.log files either at a size limit or daily.  Have old logs fall off... the usual log rotation scheme.  Ideally user-configurable in the settings, but probably not necessary 

**Describe alternatives you've considered**
scripts to do it myself 

**Additional context**
N/A

**Comment by blhoward2** [comment]
https://www.npmjs.com/package/winston-daily-rotate-file

**Comment by ivdimitro** [comment]
I was thinking to configure log rotate in the container. Do you think the JS package is better idea?

**Comment by blhoward2** [comment]
I'm not sure that's possible, but you could try. I haven't tried in a while but it used to be that if you disturbed/nuked the log file it wouldn't log again until you restarted the container even if you created a new one.

**Comment by frenck** [comment]
This is not something an application should solve. The OS support things like logrotation.

**Comment by robertsLando** [comment]
@frenck I know but most users haven't much experience to do it, so after many and many requests I decided to implement it (it's just few lines of code)

**Comment by frenck** [comment]
Sorry, but that makes no sense in my universe.
Instead of adding "fluff" to an application that it shouldn't have, you could teach, document or explain how it should be done. Now you are going to get stuck with stuff that doesn't belong here.

I think you should strongly consider reverting this change.

**Comment by blhoward2** [comment]
You can't rotate the log file in the OS. The driver fails to write to it after you do so even if it's recreated.

**Comment by frenck** [comment]
> You can't rotate the log file in the OS. 

?! I'm sorry, I'm not even going to try to respond to that insanely wrong answer.

**Comment by blhoward2** [comment]
You have your theory of application design, evidently. There is nothing that says an application that provides for its own logging abounding provide maintenance feature around that logging. That's absurd.

**Comment by frenck** [comment]
> You have your theory of application design, evidently. 

> That's absurd.

I would recommend reading a book or two on the subject.

Anyways. I'll deal with it don't give a darn 👋

**Comment by chennin** [comment]
> You can't rotate the log file in the OS. The driver fails to write to it after you do so even if it's recreated.

You can: that's what the `copytruncate` directive in `logrotate` is for.

```
       copytruncate
              Truncate  the  original  log  file to zero size in place after creating a copy, instead of moving the old log file and optionally creating a new one.  It can be used when some
              program cannot be told to close its logfile and thus might continue writing (appending) to the previous log file forever.  Note that there is a very small time  slice  between
              copying the file and truncating it, so some logging data might be lost.  When this option is used, the create option will have no effect, as the old log file stays in place.
```

**Comment by robertsLando** [comment]
@frenck @chennin As I said I implemented this just because many users where asking for it, also zwave-js has this feature implemented in the driver when log to file is enabled. I suggest to let users decide? 

I mean we could create a pool here give it a week and check the number of thumbs up/down?

**Comment by chennin** [comment]
I don't have strong opinions on its existence, but I did already implement OS-level rotation and I do have a question: can I disable this feature? I did check the docs, for reference:
```
Z2M_LOG_MAXFILES: The maximum number of files to keep in the log directory, if you add d suffix this will set the number of days to keep logs. Default is 7d
Z2M_LOG_MAXSIZE: The maximum size of a single log file. Default is 50m (50MB)
```
and from `winston-daily-rotate-file`:
```
 maxSize: Maximum size of the file after which it will rotate. This can be a number of bytes, or units of kb, mb, and gb. If using the units, add 'k', 'm', or 'g' as the suffix. The units need to directly follow the number. (default: null)
maxFiles: Maximum number of logs to keep. If not set, no logs will be removed. This can be a number of files or number of days. If using days, add 'd' as the suffix. (default: null)
```
Does that mean if I set both env vars to `"null"`, it will be disabled, or will the string not pass through correctly?

**Comment by robertsLando** [comment]
> Does that mean if I set both env vars to "null", it will be disabled, or will the string not pass through correctly?

Nope, if them are not set they will use the default value. @chennin If you are interested I could add a env var to disable the log rotation

**Comment by blhoward2** [comment]
Ultimately, this is a decision that must accommodate different installation methods. If we don't do it (as the driver already does), then WE have to worry about supporting it across multiple operating systems and installation methods and explaining how to do it. And lots of users use docker volumes which makes it even more complicated. It's just not worth it. MANY other applications all provide for their own log rotation.

**Comment by chennin** [comment]
> Nope, if them are not set they will use the default value. @chennin If you are interested I could add a env var to disable the log rotation

Yeah, I'd appreciate a way to disable it since I already have OS-level set up!

**Comment by blhoward2** [comment]
It may make sense to allow it to be disabled. I don't know what they involves.

**Comment by robertsLando** [comment]
@chennin https://github.com/zwave-js/zwavejs2mqtt/pull/1755

**Comment by blhoward2** [comment]
I'd also add, we need to consider the average user's expectations here. Currently, users turn on log to file then come back months later to a 10 GB log file. Sometimes it fills the SD card and crashes the whole thing. Pointing such users to documentation about something else they need to install to fix the issue creates a negative impressions of the project. If we create the file, an average user would expect it to be our business what happens to it. Hence why users come here asking about it.
