### ISSUE TITLE
[bug] TCP connection drop leads to undefined behavior

### ISSUE THREAD

**Issue by andyboeh** [zwave-js/zwavejs2mqtt#1167]
### Version

**Checklist:**

- [x] I am **not** using HomeAssistant. **Or:** a developer has told me to come here.
- [x] I have checked the troubleshooting section and my problem is **not** described there.
- [x] I have read the changelog problem was **not** mentioned there.

Build/Run method

- [x] Docker
- [ ] PKG
- [ ] Snap package
- [ ] Manually built (git clone - yarn install - yarn run build )

zwavejs2mqtt version: 4.0.1
zwave-js version: 7.3.0

### Describe the bug

I'm using ser2net to connect my exposed Z-Wave USB dongle to zwavejs2mqtt. This works very well as long as the connection is stable. I had to restart the device with the dongle and this is where zwavejs2mqtt started to misbehave:

As long as no command is sent to the dongle, nothing is logged (but the controller is actually dead!). If I start inclusion, I end up with the Add/Remove device modal window that cannot be closed (i.e. no button is visible) and the following in the log:

```
2021-05-10 16:07:53.719 INFO ZWAVE: Calling api startInclusion with args: [ false, [length]: 1 ]
2021-05-10 16:07:54.956 INFO ZWAVE: Failed to send the message after 3 attempts startInclusion {
success: false,
message: 'Failed to send the message after 3 attempts'
}
```
Any further action after reloading the web page, including changing the ZWave settings, leads to the following in the log:
```
2021-05-10 16:10:00.614 ERROR ZWAVE: undefined
```

The only way I was able to fix this behavior was to restart the zwavejs2mqtt container.

I suppose that there are actually two problems: 
1. The modal window that cannot be closed
2. A communication problem on the zwavejs side.

### To Reproduce

1. Connect the Z-Wave dongle via TCP, i.e. `tcp://dongle.lan:5000`
2. Drop the connection or just shutdown ser2net on the host with the dongle
3. Start inclusion inside zwavejs2mqtt

### Expected behavior

1. The dropped connection should be automatically detected and restored by the zwavejs driver
2. The add device modal window should contain a close or cancel button

### Logs
Slightly redacted logs (removed homeid and ip address)

[zwavejs2mqtt.log.zip](https://github.com/zwave-js/zwavejs2mqtt/files/6460060/zwavejs2mqtt.log.zip)

**Comment by robertsLando** [comment]
@andyboeh Could you attach logs file please?

**Comment by robertsLando** [comment]
Sorry completely missed them. BTW by checking them I don't find what is causing the issue... Let's see if @AlCalzone has some thoughts

**Comment by andyboeh** [comment]
According to https://stackoverflow.com/questions/44261512/how-to-detect-if-net-socket-connection-dies-node-js one option would be to call .setKeepalive() on the socket...?

**Comment by andyboeh** [comment]
@poldim This bug is about a connection problem between zwavejs (the driver) and the Dongle, which is connected over TCP. In my case, I run the software stack on a server in the basement while the Z-Wave dongle is connected to my OpenWrt router on the second floor.

Your dongle is connected via USB and you seem to have problems with the WebSocket connection between HomeAssistant and zwavejs2mqtt.
