### ISSUE TITLE
[feat] mention ZWAVEJS_EXTERNAL_CONFIG in quick-start.md and docker-compose.yml

### ISSUE THREAD

**Issue by phipolis** [zwave-js/zwavejs2mqtt#1180]
Now that zwave-js has the `ZWAVEJS_EXTERNAL_CONFIG` var, it would be helpful if it were mentioned in quick-start.md's docker instructions and perhaps as a commented line in docker-compose.yml.

One thing that's unclear to me that these docs might address: should `ZWAVEJS_EXTERNAL_CONFIG` be used in addition to the `/usr/src/app/store` mount? I assume the latter is for zwavejs2mqtt's config, while the former is for zwavejs', but I'm not sure.

**Comment by mwav3** [comment]
I'm confused on this as well.  I had previously setup a volume mounted at /usr/src/app/node_modules/@zwave-js/config to persist the config files with --mount source=zwave-config,target=/usr/src/app/node_modules/@zwave-js/config. Can I keep that or should I somehow use the environment variable now?  Is the config directory different now I see references to /usr/src/app/store/.config-db in the comment from @kpine .  .config-db is not in my store directory currently do I need to create it?

**Comment by robertsLando** [comment]
`ZWAVEJS_EXTERNAL_CONFIG` by default is set to `/usr/src/app/store/.config-db` on docker images but in the last one published it is missing for some reasons I forgot to add it to the main Dockerfile. So a temporary solution could be to add that env var to docker compose until next patch release.

@kpine you right, if you are using a custom store directory you should also edit that env var according:

```
STORE_DIR=/my/custom/path
ZWAVEJS_EXTERNAL_CONFIG=/my/custom/path/.config-db
```
