### ISSUE TITLE
[bug] Upgrade from 4.0.1 to 4.1.0 or 4.2.0 loses all data on battery powered devices

### ISSUE THREAD

**Issue by gregg098** [zwave-js/zwavejs2mqtt#1197]
### Version

**Checklist:**

- [x ] I am **not** using HomeAssistant. **Or:** a developer has told me to come here.
- [x ] I have checked the troubleshooting section and my problem is **not** described there.
- [x ] I have read the changelog problem was **not** mentioned there.

Build/Run method

- [x ] Docker
- [ ] PKG
- [ ] Snap package
- [ ] Manually built (git clone - yarn install - yarn run build )

zwavejs2mqtt version: 4.0.1
zwave-js version: 7.3.0

### Describe the bug

Running ZWaveJS2MQTT docker container and have about 50 devices paired to an Aeotec stick. Has been running flawlessly for the last few months. Running with the "latest" tag in my docker compose file so today it pulled in 4.2.0 and started. Noticed right away I was missing a bunch of node data. Looking closer in the web UI, pretty much every battery powered device shows no data like it needs to re-interview the node. I did not check completely to see if it truly is only battery powered devices since I had to get things running again.

Since I've had something similar happen in the past, I stopped the docker container, removed it, manually specified 4.0.1 in my docker compose file, then replaced all the persistent volume data with a backup from last night. Started up and all is working just fine.

Tried again by changing the tag to latest and pulling in 4.2.0. Stopped Home Assistant first just to keep it isolated while testing. 
 Same problem, a good majority of my devices have no node data again. This is 15 or so minutes later so my network should have "settled down" by then.

Needed a working system so I downgraded to 4.0.1 again with my backup data and am back to a working state again.

I owe some log files when I get to a chance to re-produce this later today.

### To Reproduce

See above

### Expected behavior

Reviewed the changelog and didnt see any breaking changes so I expected the upgrade to be normal.

### Additional context

I am using Home Assistance container, but this issue is isolated to the ZwaveJS2MQTT setup. The same thing happens regardless of if Home Assistant is running or not.

**Comment by robertsLando** [comment]
Please update to 4.2.1

**Comment by gregg098** [comment]
FIxed. Thank you.
