### ISSUE TITLE
[feat] Built in healthcheck?

### ISSUE THREAD

**Issue by ZetaPhoenix** [zwave-js/zwavejs2mqtt#1210]
**Is your feature request related to a problem? Please describe.**
I saw that in the guide you could set up a health check using curl and upon doing more research on how to do that with a docker run command I saw that it could be done inside the container with a simple script.

**Describe the solution you'd like**
Add `HEALTHCHECK` to the docker file with a script to update the status.

**Describe alternatives you've considered**

**Additional context**
Example with .js file: https://blog.sixeyed.com/docker-healthchecks-why-not-to-use-curl-or-iwr/

**Comment by robertsLando** [comment]
Interesting, didn't know about custom healthchecks :)

**Comment by jstenvall-ducksify** [comment]
On a side note, the healthcheck is very useful in the case you deploy with Nomad (Hashicorp). You are able to perform healthchecks for the service as seen here: https://www.nomadproject.io/docs/job-specification/service#check.

**Comment by robertsLando** [comment]
I have deviced to don't implement an healtcheck inside docker image but instead I have added docs and scripts to explain how to add it. This because once you run the app the first time the zwave client isn't connected and this would cause continue restarts

**Comment by JvdMaat** [comment]
For other people finding this looking for a docker healthcheck, the documentation is here: https://zwave-js.github.io/zwavejs2mqtt/#/guide/healthcheck

**Comment by ltomes** [comment]
> For other people finding this looking for a docker healthcheck, the documentation is here: https://zwave-js.github.io/zwavejs2mqtt/#/guide/healthcheck
> 
> EDIT: Having tried it, there's no curl in the image. So I substituted with: healthcheck: test: 'wget --no-verbose --tries=1 --spider localhost:8091/health/zwave --header "Accept: text/plain" || exit 1'

For anyone still looking for this, the URI has changed to: https://zwave-js.github.io/zwave-js-ui/#/guide/healthcheck
