### ISSUE TITLE
[feat] Modify sendCommand to accept command class names in addition to CC IDs

### ISSUE THREAD

**Issue by TheKorn2** [zwave-js/zwavejs2mqtt#1219]
Request to modify sendCommand so it'll accept the command class human readable names ("Multilevel Switch") in addition/in lieu of their command class numbers.

See discussion in #1196 .  

(copy pasta from there)

@robertsLando I think it would be good if the mqtt API not only accepted the CC IDs (numbers) but also their names as defined in node-zwave-js. So for a startLevelChange the command could look like this:

{ "args": [
  {
    "nodeId": 23,
    "commandClass": "Multilevel Switch",
    "endpoint": 0,
  },
  "startLevelChange",
]}

**Comment by robertsLando** [comment]
PR ready
