### ISSUE TITLE
[bug] lastActive or nodeinfo only refreshed at start on Docker

### ISSUE THREAD

**Issue by Gis70** [zwave-js/zwavejs2mqtt#1220]
Checklist:

- [X]  I am not using HomeAssistant. Or: a developer has told me to come here.
- [X]  I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog problem was not mentioned there.
Build/Run method

- [X] Docker
- [ ] PKG
- [ ] Snap package
- [ ] Manually built (git clone - yarn install - yarn run build )

![image](https://user-images.githubusercontent.com/16589132/118316311-f4fb5a80-b4f6-11eb-85ec-f4e781ed644c.png)

### Describe the bug

i don't see any variation of lasActive (and maybe all nodeinfo). The only way to make it working is to re start Docker.

![image](https://user-images.githubusercontent.com/16589132/118315940-73a3c800-b4f6-11eb-8c5f-832c9df719e5.png)
Epoch converted in human readable time : 
![image](https://user-images.githubusercontent.com/16589132/118316177-c9787000-b4f6-11eb-9e8a-557d49f1ad5a.png)

`{"id":5,"deviceId":"345-82-3","manufacturer":"Qubino","manufacturerId":345,"productType":3,"productId":82,"name":"Volet_Cassydie","loc":"","neighbors":[1,2,6,7,8,9,10,11,13,14,15,18,20,21],"ready":true,"available":true,"failed":false,"lastActive":1621013034723,"firmwareVersion":"1.1","isSecure":false,"keepAwake":false,"maxBaudRate":null,"isRouting":true,"isFrequentListening":false,"isListening":true,"inited":true,"hexId":"0x0159-0x0003-0x0052","dbLink":"https://devices.zwave-js.io/?jumpTo=0x0159:0x0003:0x0052:1.1","productLabel":"ZMNHCD","productDescription":"Flush Shutter","protocolVersion":3,"zwavePlusVersion":1,"zwavePlusNodeType":0,"zwavePlusRoleType":5,"endpointsCount":0,"endpointIndizes":[],"isControllerNode":false,"dataRate":40000,"deviceClass":{"basic":4,"generic":17,"specific":7},"status":"Alive","interviewStage":"Complete"}`
### To Reproduce

My config :  
![image](https://user-images.githubusercontent.com/16589132/118316425-1ceabe00-b4f7-11eb-91c2-f5e837128940.png)

![image](https://user-images.githubusercontent.com/16589132/118316484-2ffd8e00-b4f7-11eb-8964-4b67eb1d1e75.png)

### Expected behavior

In the docs, it's said nodeinfo is refreshed everytime an update it's done on the node.

**Comment by robertsLando** [comment]
> i don't see any variation of lasActive (and maybe all nodeinfo). The only way to make it working is to re start Docker.

This only change when the node changes his state (Alive, Dead, Asleep...) or there is any kind of event coming from that node, it could be that that node isn't reporting any state change?

**Comment by Gis70** [comment]
Hmm no because they change state very often. (Pir sensor, heat module, door contact...) And nothing is refreshed, for no one of my node. And in the UI it is refreshed and i expect timestamp is refreshed as in the GUI. Is it the correct behavior expected?

**Comment by robertsLando** [comment]
So in the UI is refreshed correctly, it isn't updated correctly in MQTT so? What topic are you looking for?

**Comment by Gis70** [comment]
yes correct, the topic is :  

![image](https://user-images.githubusercontent.com/16589132/118453576-a9fc6580-b6f7-11eb-914f-03e2f539107f.png)

but it's not a topic problem because if i restart the docker, it is refreshed.

**Comment by robertsLando** [comment]
@Gis70 That's because that topic is only updated when node changes it's status (like I said, ALive, Dead, Asleep ...)

**Comment by Gis70** [comment]
Understood, sorry for my misunderstanding, and when does a node will go in "Dead" mode ? is it when the wakeup time parameter is overtaken ? 
Could it be possible to obtain by MQTT the LastUpdated value like in the GUI ? @robertsLando

**Comment by robertsLando** [comment]
a node becomes dead when the controller cannot reach him for some reson (network issues or broken device). A node becomes asleep only if it's battery powered after a certain period of activity (to save battery). About your request you could use MQTT apis to get all nodes array when needed.

Use `getNodes` api with https://zwave-js.github.io/zwavejs2mqtt/#/guide/mqtt?id=send-command

**Comment by Gis70** [comment]
Hello @robertsLando I come back to you regarding my needs, getNodes is to huge, would it be possible to get at least getNodes(myNode) ? and in an ideal world getNodes(myNode,myParams) ==> example getNodes(21, lastActive)
It would be very useful, light and simple for us (users). Thank you

**Comment by Gis70** [comment]
This is what i tryied but without success that why I asked : 

Result in debug : 

Topic to publish : 

`zwave/_CLIENTS/ZWAVE_GATEWAY-zwavejs2mqtt/api/driverFunction/set`

```
2021-10-11 18:44:24.052 INFO ZWAVE: Calling api driverFunction with args: [
'const nodeId = 25, const node = this.zwaveClient._nodes.get(nodeId), return node.lastActive',
[length]: 1
]
2021-10-11 18:44:24.054 INFO ZWAVE: Unexpected token 'const' driverFunction undefined
```

**Comment by Gis70** [comment]
OK i found the problem, it's because of line break. It doesn't work in a json string, we must add dot comma. Like this it's work :-)
`{"args":["const nodeId = 26; const node=this.zwaveClient._nodes.get(nodeId); return node.lastActive"]}`
