### ISSUE TITLE
Using local device configuration files

### ISSUE THREAD

**Issue by gustden** [zwave-js/zwavejs2mqtt#1223]
In the release notes for zwavejs2mqtt, it shows in version 4.0 there is support for loading a custom device configuration files.

- allow loading custom device configs from store/config (#1096) (3988049)

I have been attempting to load a modified version of the file to support the Minoston(MS11Z) variant of this switch by placing in the store/config directory.   It is a copy of https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/devices/0x0312/zw31.json with one additional product type code added.

The file works correctly if I rebuild zwavejs2mqtt with my edits, but it does not get loaded if placed in the store/config directory.  I am running zwavejs2mqtt directly ( not in a container ) and  the store is in the working directory.   I can see the file from within the file browser of zwavejs2mqtt in the config directory,  but it does not appear to get loaded.

**Comment by blhoward2** [comment]
What do your file permissions look like?

**Comment by gustden** [comment]
The process is running under the user 'hass' which owns all files.  

drwxrwxr-x 4 hass hass      4096 May 14 22:44 store
drwxrwxr-x 4 hass hass  4096 May 14 15:23 config
store/config:
-rw-r--r-- 1 hass hass 7592 May 14 09:46 zw31.json

**Comment by robertsLando** [comment]
Are you using this folder? 

`deviceConfigPriorityDir: storeDir + '/config'`

Remember that you also must respect the directories tree (you must place the config file inside a folder of its manufacturer like in the original config db

**Comment by AlCalzone** [comment]
> Remember that you also must respect the directories tree (you must place the config file inside a folder of its manufacturer like in the original config db

You don't.

**Comment by robertsLando** [comment]
🤷🏼‍♂️  I remember it wrong or it was like that initially?

**Comment by AlCalzone** [comment]
The PR https://github.com/zwave-js/node-zwave-js/pull/2406 does not specifically mention it, but there is no special structure necessary. It isn't even necessary for the internal DB, we just do it to keep an overview.

**Comment by robertsLando** [comment]
Ok perfect :)

**Comment by anonymustard** [comment]
Chiming in to say "me too". I have the json file in store/config. It is a copy of an existing file, except that I changed the productId, label, and description. File permissions are 644, and it's owned by the user that is running zwavejs2mqtt. I've tried restarting zwavejs2mqtt, re-interviewing the affected node, and excluding and re-including the node. It still doesn't pull in the specified config.

Is there any kind of positive feedback I should see in zwavejs or zwavejs2mqtt logs that would indicate that it can actually see the file?

![image](https://user-images.githubusercontent.com/238341/119875903-4e9b5600-bef5-11eb-9b8c-704e78daea2f.png)

**Comment by anonymustard** [comment]
I noticed in #1096 that the `deviceConfigPriorityDir` option is constructed using string concatenation. Elsewhere in the file, `utils.joinPath()` is used instead to create `ZWAVEJS_LOG_FILE`.

**Comment by robertsLando** [comment]
Because storeDir is already an absolute path

**Comment by AlCalzone** [comment]
> Is there any kind of positive feedback I should see in zwavejs or zwavejs2mqtt logs that would indicate that it can actually see the file?

yes, right when you start up in the driver log:
```
10:32:09.322 CNTRLR   [Node 001] Embedded device config loaded
10:32:09.329 CNTRLR   [Node 007] Embedded device config loaded
10:32:09.331 CNTRLR   [Node 015] Embedded device config loaded
10:32:09.351 CNTRLR   [Node 017] Embedded device config loaded
10:32:09.374 CNTRLR   [Node 025] Embedded device config loaded
```
This would be "User-provided" instead of "Embedded" when your custom file is loaded.

**Comment by robertsLando** [comment]
http://localhost:34067/#/development/intro?id=testing-custom-devices-config 

Should I also mention the log feedback?

**Comment by robertsLando** [comment]
@gustden That is z2m logs, we need driver logs: https://zwave-js.github.io/zwavejs2mqtt/#/troubleshooting/bug_report?id=driver-logs

**Comment by gustden** [comment]
Thanks for this,  as I was unaware there were separate driver logs.    I am seeing the 'device config loaded", but nothing about the local file 'store/config/zw31.json' being loaded. 


2021-05-28T13:29:10.499Z CNTRLR   [Node 006] No device config found
2021-05-28T13:29:10.508Z CNTRLR   [Node 011] No device config found
2021-05-28T13:29:10.520Z CNTRLR   [Node 015] No device config found

[zwavejs_395236.log_2021-05-28.log](https://github.com/zwave-js/zwavejs2mqtt/files/6561218/zwavejs_395236.log_2021-05-28.log)

**Comment by gustden** [comment]
Problem is resolved in the latest release.   Thanks!
