### ISSUE TITLE
[bug] MQTT no longer respect QOS or retain setttings

### ISSUE THREAD

**Issue by Lopton** [zwave-js/zwavejs2mqtt#1225]
### Version

**Checklist:**

- [ ] I am **not** using HomeAssistant. **Or:** a developer has told me to come here.
- [x] I have checked the troubleshooting section and my problem is **not** described there.
- [X] I have read the changelog problem was **not** mentioned there.

Build/Run method

- [X] Docker
- [ ] PKG
- [ ] Snap package
- [ ] Manually built (git clone - yarn install - yarn run build )

zwavejs2mqtt version: 4.2.1
zwave-js version: 7.4.0

### Describe the bug
The mqtt publish function does not respect either the QOS setting or the retain flag in the config after upgrading to 4.2.1 from 4.0.1. All MQTT messages, when published will be QOS: 0 and Retain: false even though in the SILLY logs it says the message was sent with QOS: 0 and Retain: true.

### To Reproduce

1. Go to Control Panel set MQTT QOS setting to 2 and Retain to True,
2. Save Settings
3. Change a state or re-discover a device. The resulting MQTT message in the broker will show QOS 0 and retain false

### Expected behavior

QOS and retain settings should be respected

**Comment by Lopton** [comment]
I spent sometime trying to dig into this, everything seems right up to [MqttClient.js : 172 ](https://github.com/zwave-js/zwavejs2mqtt/blob/dfd624cff78900fe3c4763cb62c5bdec0d614dab/lib/MqttClient.js#L172). However I am not following how to go past that. 

In the logs I can clearly see this message: 
`2021-05-15 14:09:45.453 INFO ZWAVE: Node 8: value updated: 38-0-duration [Duration: 0 seconds] => [Duration: 0 seconds]
2021-05-15 14:09:45.454 DEBUG MQTT: Publishing to ZwaveJs700/Dining_Room/DR_Ring_Dimmer/38/0/currentValue: { time: 1621087785454, value: 97 } with options { qos: 2, retain: true }`

But the MQTT message is QOS 0 retain false.

**Comment by Lopton** [comment]
sigh, this seems to have resolved it self, or I'm losing my mind... either way I'll close this issue.

**Comment by robertsLando** [comment]
Let me know if you expect this again
