### ISSUE TITLE
[question] How to hide devices?

### ISSUE THREAD

**Issue by Swiftnesses** [zwave-js/zwavejs2mqtt#123]
Good day,

New user here 👍 

I was wondering how I make changes to ID's permanent. For example on my Philio 4-in-1 sensor it shows the contact sensor as ""object_id": "contact_0" (hence it shows as this in HA). How can I change it to just "contact"?

Further, I'd like to hide certain items, i.e. stop them being discovered (which don't appear to work). I know I can do this in HA, but would rather do it in the control panel by highlighting them and clicking delete, but when my sensor wakes or refreshes itself they reappear?

**Comment by blhoward2** [comment]
Highlight the node, go to the bottom of the screen. Click Store. Click the sensor and makes our changes. Then save it.

**Comment by Swiftnesses** [comment]
I've done that, how do I get the changes to push back to HASS (in the right way)? I can delete the node from the MQTT integration and 'refresh the node', but that's not easy for battery sensors? If I click rediscover node, it's rediscovered but my changes to 'ignoreDiscovery' for each item are lost.

**Comment by blhoward2** [comment]
Do you have retain discovery turned on? If so you need to delete the MQTT topic. Then restart HA.

**Comment by robertsLando** [comment]
There is an ignore discovery flag on the discover json

**Comment by Swiftnesses** [comment]
@robertsLando found it after posting (tested, works OK), will close now. Thanks!
