### ISSUE TITLE
[bug] Group editors hasn't well separated context

### ISSUE THREAD

**Issue by andras-tim** [zwave-js/zwavejs2mqtt#1231]
### Version

**Checklist:**

- [x] I am **not** using HomeAssistant. **Or:** a developer has told me to come here.
- [x] I have checked the troubleshooting section and my problem is **not** described there.
- [x] I have read the changelog problem was **not** mentioned there.

Build/Run method

- [x] Docker
- [ ] PKG
- [ ] Snap package
- [ ] Manually built (git clone - yarn install - yarn run build )

zwavejs2mqtt version: 4.2.1
zwave-js version: 7.4.0

### Describe the bug

When I open more than one group editor, the last always updates the others. (Maybe the editor widget uses a shared groups variable)

### To Reproduce

https://user-images.githubusercontent.com/619016/118552615-76552600-b75f-11eb-9ca9-ca1df054aee5.mp4

### Expected behavior

I can open several Group editors that don't update each other.

**Comment by robertsLando** [comment]
Thanks for this will try to fix the issue asap

**Comment by robertsLando** [comment]
PR Ready. Could you give it a try?

**Comment by andras-tim** [comment]
> PR Ready. Could you give it a try?

Wow! You are blazing fast. :smiley: 

I checked, and now it works!

Many thanks!
