### ISSUE TITLE
[bug] After adding a device or healing the network, the graph is wrong

### ISSUE THREAD

**Issue by andyboeh** [zwave-js/zwavejs2mqtt#1241]
### Version

**Checklist:**

- [x] I am **not** using HomeAssistant. **Or:** a developer has told me to come here.
- [x] I have checked the troubleshooting section and my problem is **not** described there.
- [x] I have read the changelog problem was **not** mentioned there.

Build/Run method

- [x] Docker
- [ ] PKG
- [ ] Snap package
- [ ] Manually built (git clone - yarn install - yarn run build )

zwavejs2mqtt version: 4.2.1
zwave-js version: 7.4.0

### Describe the bug

After adding a new device to the network or healing the network with changed routes, the network graph is not updated. The neighbor information in the log is correct, but the graph is out of sync. A full page reload is required to make it work.

### To Reproduce

1. A network with at least one node disconnected
2. Visualize the graph, notice a disconnected device
3. Heal the network
4. Visualize the graph, still notice a disconnected device

OR

I've also seen this after adding a new device.

### Expected behavior

At 4. the device should be connected.

### Additional context

I'm using Firefox on Arch Linux.
After a network heal, my network graph looks like this:

![Screenshot-20210518-0949](https://user-images.githubusercontent.com/3099753/118612840-759fac80-b7be-11eb-949a-0743f1d2bd2a.png)

Reloading the entire page leads to the updated graph:

![Screenshot-20210518-0951](https://user-images.githubusercontent.com/3099753/118612970-936d1180-b7be-11eb-85de-acba9e05b2c1.png)

This is a follow-up to #739

**Comment by robertsLando** [comment]
@andyboeh Could you try to change graph options to see if it is updated correctly then? An option change triggers a refresh of the graph. Try to change grouping or else and let me know
