### ISSUE TITLE
[feat] Need event emitted when writeValue API is invoked

### ISSUE THREAD

**Issue by timothyh** [zwave-js/zwavejs2mqtt#1252]
**Is your feature request related to a problem? Please describe.**
I have a plugin that needs to track some device values, in my case it's the indicator.

If the writeValue API is invoked by the web interface (or Home Assistant), that value can be changed without the plugin being aware of it.

**Describe the solution you'd like**

In the ZwaveClient writeValue API, at around line 1661, add something like
        ```this.emit('valueWritten', valueId, value)```
as in
```
        } else {
          result = await this.getNode(valueId.nodeId).setValue(valueId, value)
         this.emit('valueWritten', valueId, value)
       }
```
**Describe alternatives you've considered**
Polling the device to detect changes but .....

**Additional context**
It's up to the event consumer as to how the event information is used. They can either use the new value directly, or trigger the ```refreshCCValues``` API depending on the device.

This is to address the case where a device doesn't automatically send an update when values are updated using Zwave.

**Comment by robertsLando** [comment]
@timothyh PR?
