### ISSUE TITLE
[feat] Please add the ability to ping a node

### ISSUE THREAD

**Issue by kpine** [zwave-js/zwavejs2mqtt#1253]
**Is your feature request related to a problem? Please describe.**
Some battery nodes can wake up, but zwave-js will not automatically put them to sleep. They may go to sleep in reality but zwave-js never checks so they are marked as Awake until some command fails later.

**Describe the solution you'd like**
Any command sent to a non-listening node (battery) that fails will put it to sleep. The easiest way to do this is using a No Operation command which exists for such scenarios. Sending a NoOp to a sleeping node will force an awake/sleeping check.

This is also useful for testing mains-powered needs to determine if they are failed or not.

The NoOp command is lighter weight than using other CCs and doesn't require any specific knowledge about the node's functionality.

**Describe alternatives you've considered**
Send some other command such as a Get.

**Additional context**
See this issue: https://github.com/zwave-js/node-zwave-js/issues/2643

node-zwave-js provides a Node ping method that implements the No Operation command.

**Comment by robertsLando** [comment]
PR ready @kpine :)

**Comment by kpine** [comment]
Just to confirm, works perfectly, thanks. 👍

**Comment by robertsLando** [comment]
Thanks for the feedback @kpine 🚀
