### ISSUE TITLE
[question] Upgrade from 3.4.0 to newest version

### ISSUE THREAD

**Issue by tampiss** [zwave-js/zwavejs2mqtt#1260]
Hello, Im new to all this.. I have successfully installed zwavejs2mqtt on my Raspi4 via the method

**git clone https://github.com/zwave-js/zwavejs2mqtt
cd zwavejs2mqtt
yarn install
yarn run build
yarn start**

Now, Id like to **upgrade** to the newest version, yet not sure of which would be the best steps to take...

My configuration is working and I would not like to break anything..

Thank you for your help.
Martin

**Comment by robertsLando** [comment]
```
git pull
yarn build
yarn start
```
