### ISSUE TITLE
[feat] support for secondary controllers (and maybe transfer etc?)

### ISSUE THREAD

**Issue by scyto** [zwave-js/zwavejs2mqtt#127]
**Is your feature request related to a problem? Please describe.**
I want to add an ISY 994i as a secondary controller (i already have it as my current home automation engine)

**Describe the solution you'd like**
I would like the same option as in zwave2mqtt on the controller node - where there were options for multiple controller management (i would have to respin the docker to get the exact names, can do that if needed).  

**Describe alternatives you've considered**
switching back to zwave2mqtt

**Additional context**
I am using a RaZberry zwave module with this project (the previous test done on zwave2mqtt used a different controller, just incase that matters?

**Comment by robertsLando** [comment]
I think this is something that needs to be implemented on zwavejd and I think there is already an open issue. @AlCalzone

**Comment by AlCalzone** [comment]
Yup https://github.com/zwave-js/node-zwave-js/issues/1070
Main problem is, this will require quite some manual testing and I do not have a secondary controller.

**Comment by scyto** [comment]
Happy to do some testing I have multiple (isy994i and a vera and an aeon/aeo stick or two)

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by robertsLando** [comment]
Closing this, comment on that issue so :)
