### ISSUE TITLE
zwavejs2mqtt not working on windows 10 - initial setup

### ISSUE THREAD

**Issue by KelvinHelmholtz** [zwave-js/zwavejs2mqtt#1270]
I am unable to get zwavejs2mqtt running on Windows 10.  

I start the package as:

P:\T2\ZWJS2TT>npm start

> zwavejs2mqtt@4.3.0 start P:\T2\ZWJS2TT
> node bin/www

 ______                       _     ___                  _   _
|___  /                      (_)   |__ \                | | | |
   / /_      ____ ___   _____ _ ___   ) |_ __ ___   __ _| |_| |_
  / /\ \ /\ / / _` \ \ / / _ \ / __| / /| '_ ` _ \ / _` | __| __|
 / /__\ V  V / (_| |\ V /  __/ \__ \/ /_| | | | | | (_| | |_| |_
/_____|\_/\_/ \__,_| \_/ \___| |___/____|_| |_| |_|\__, |\__|\__|
                            _/ |                      | |
                           |__/                       |_|

2021-05-24 16:07:53.752 WARN STORE: settings.json not found
2021-05-24 16:07:53.808 WARN STORE: scenes.json not found
2021-05-24 16:07:53.810 WARN STORE: nodes.json not found
'git' is not recognized as an internal or external command,
operable program or batch file.
2021-05-24 16:09:11.063 INFO APP: Version: 4.3.0
2021-05-24 16:09:11.073 INFO APP: Application path:P:\T2\ZWJS2TT
2021-05-24 16:09:14.302 ERROR GATEWAY: Zwave settings are not valid
2021-05-24 16:09:14.347 INFO APP: Listening on port 8091 host 0.0.0.0 protocol HTTP

The package waits here, then I try to connect via the browser at 127.0.0.1:8091, the browser session returns a blank (nothing at all) page while console shows:

2021-05-24 16:34:29.350 INFO APP: GET / 200 591.669 ms - 1331
2021-05-24 16:34:29.648 INFO APP: GET /static/css/style.css 200 131.659 ms - 117
2021-05-24 16:34:29.725 INFO APP: GET /static/js/app.js 200 233.972 ms - 25916

I suspect issues with installation starting with missing %base_Dir%\dist folder which I manually created but have no knowledge about it. My method of install was based on the instructions on this gitsite:

1. Downloaded zip from https://github.com/zwave-js/zwavejs2mqtt
2. Unzipped into P:\T2\ZWJS2TT and ran the following in DOS:Administrator console:
3. npm install
4. npm build
5. npm start

On first run the package failed for lack of P:\T2\ZWJS2TT\dist folder (which apparently was to contain \static\css and \js folders).  I looked but was unable to find reasons, so just to test further I:
  1. created folders 
        P:\T2\ZWJS2TT\dist\static\css, and,  
        P:\T2\ZWJS2TT\dist\static\js
  2. Copied
       style.css (forgotten original location) into css folder above 
       app.js (from P:\T2\ZWJS2TT\) into js folder above

Zwave controllers and attached devices are working fine with openHAB, and openzwave/MinOZW.  At the time of zwavejs2mqtt tests neither openhab nor MinOZW were running and the controller on com6 was available for grabs.

My current config:
 Hardware/OS: 
    MS Surface GO & Windows 10 Home
    USB HUB:
        Via USB  -> COM6 ZWave controller
                           ->  ZWave enabled Honeywell Thermostat
        Via USB  -> Zigbee controller on com4
                           ->  IKEA TRADFRI devices
        Via WiFi:
                       Wiz Plugs, Bulbs (wall Dimmers TBD) 

Base/Required software packages:
 1. Device Drivers for USB Zwave and Zigbee controllers (working)
 2. Mosquitto Broker (working)
 3. Zigbee2MQTT (working fine with all devices configured)
 4. Zulu JAVA (working)
 5. NodeJS (working)
 6. OpenZwave base with MinOZW app (working and is able to find the Zwave controller and Thermostat)
 
Applications:
 1. Node-Red with MQTT, openhab (working)
 
 2. openHAB with MQTT, ZWave with:
      -> Zwave Thermostat (working) 
      -> IKEA devices (working but some functions like effects on Bulbs needed a manual MQTT thing/channel)

 3. Home Assistant portable (from github/AlexIT) with MQTT/IKEA Devices (working), wiz lights (working), Zwave (NOT WORKING) 

FYI: Due to several issues I prefer to stay on windows 10 for this project.

**Comment by AlCalzone** [comment]
Just to chime in: I'm developing `node-zwave-js` on Windows 10 and have no problems testing it from time to time in zwavejs2mqtt.

**Comment by robertsLando** [comment]
In this issue you are doing so much things that seems useless to me. This should work:

```
wget https://github.com/zwave-js/zwavejs2mqtt/archive/refs/heads/master.zip
unzip master.zip
cd zwavejs2mqtt-master
yarn run build
yarn start
```

**Comment by KelvinHelmholtz** [comment]
Thank you both for the help.  The install issue is solved.  My notes:

I retried the process but this time with the following changes:
 1. Instead of CMD, I used powershell (also with admin privs)
 2. Downloaded fresh copy of source from robertsLando's url
 3. I did not have yarn but downloaded installed
 4. installing with yarn failed as follows:
       yarn install v1.22.5
      [1/5] Validating package.json...
      [2/5] Resolving packages...
      [3/5] Fetching packages...
      info There appears to be trouble with your network connection. Retrying...
      info There appears to be trouble with your network connection. Retrying...
      info There appears to be trouble with your network connection. Retrying...
      info There appears to be trouble with your network connection. Retrying...
     info There appears to be trouble with your network connection. Retrying...
 5. So I resorted to npm install, npm run build and npm start per  AlCalzone and that started web server.  
 
 Also, I am setting the Zwave the controller params now and look forward to progressing.

Again thank you for help with this issue.
