### ISSUE TITLE
[bug] Heal-status becomes blank

### ISSUE THREAD

**Issue by jmgiaever** [zwave-js/zwavejs2mqtt#1274]
### Version

**Checklist:**

- [x] I am **not** using HomeAssistant. **Or:** a developer has told me to come here.
- [x] I have checked the troubleshooting section and my problem is **not** described there.
- [x] I have read the changelog problem was **not** mentioned there.

Build/Run method

- [ ] Docker
- [ ] PKG
- [x] Snap package
- [ ] Manually built (git clone - yarn install - yarn run build )

zwavejs2mqtt: 4.4.0.1c7359d
zwave-js: 7.5.2

### Describe the bug

Heal status disappear if the control-panel is refreshed. It will clear the data in the column for every node, and won't refresh until another node is healed.

I realized it after the status for one node became blank (neither icon/status 'waiting', 'failed' or 'complete') and I refreshed to try to restore the state. 

I'm not sure if it happens on larger networks as refreshing the page just/short after a heal is started is working fine. 

### To Reproduce

1. Go to control-panel
2. Click on heal-network under advanced.
3. Press heal and wait for the network to start healing. Then refresh the page and the column will clear. I have around 50 nodes.  

### Expected behavior

Refreshing the page should restore the heal-status for every node.

**Comment by robertsLando** [comment]
Will store the heal state on the nodes too

**Comment by robertsLando** [comment]
@jmgiaever Try this when you can and let me know :) It works great on my side

**Comment by jmgiaever** [comment]
Just need to re-interview all nodes first, as they all showed up as «uknown» after a reboot and I don't have time to wake all ~30 battery powered devices until tonight. I'll let you know when it's tested. :D

**Comment by robertsLando** [comment]
You can do it using a driver function, save this snippet: 

```js
for (const [, node] of driver.controller.nodes) {
      await node.refreshInfo()
}
```

**Comment by jmgiaever** [comment]
Yes, I've used it already. But it takes time until all battery devices is interviewed, and I don't have time to wake them up now 😅
