### ISSUE TITLE
[feat]provide option for z-wave logs to be written to /store instead of /usr/src/app/bin

### ISSUE THREAD

**Issue by scyto** [zwave-js/zwavejs2mqtt#128]
**Is your feature request related to a problem? Please describe.**
attaching to the docker containers console to look at zwave logs is a minor annoyance

**Describe the solution you'd like**
let me write logs to /store - this means logs are persistent over time even if destroy the container, also means it is more transparent if logs are bloating vs hidden in the container (i connect to the docker host all the time)

**Describe alternatives you've considered**
installing SSH in the container image to fetch the log files

considered mapping /usr/src/app/bin to the host but that seems silly, now if the default location was somepath/logs then i could map that as a volume - that would be ok alterative rather than a UI based option.

**Additional context**
none

**Comment by blhoward2** [comment]
I second this though if you aren't on the dev image it looks like there are committed logging changes. In any event you can map just the log file instead of the directory in docker compose.

**Comment by scyto** [comment]
@blhoward2 i looked at the log and it had a -1 at the end, i assumed (maybe incorrectly) that this indicated rolling logs where that number changes?  if not they yes i can map the log file as a bind mount.

**Comment by robertsLando** [comment]
@scyto there is an open pr for this, I was waiting zwavejs 6 to be released as it needs configurable logging options that was not available right now in zeavejs

**Comment by robertpeteuil** [comment]
Agreed this would be great.  Looking forward to zwavejs 6.

**Comment by scyto** [comment]
once these are merged whats the lag / process to the docker being updated (for example i see the dev docker was 5 days ago and the latest one 12 days ago).  is dev docker generally safe to use for external testing by folks like ourselves or should we wait for :latest to be updated.

PS didn't  realize how new this project is! I literally had not used this or the predecessor before 2 weeks ago!  Thanks for leading it.

**Comment by blhoward2** [comment]
You can build your own image easily. The directions are at the bottom. https://github.com/zwave-js/zwavejs2mqtt/tree/master/docker

**Comment by robertpeteuil** [comment]
Ya, I'm new to it as well, but I've been using the dev containers from the start as they contain a couple of key fixes I need.  

It's been working great, other than an occasional hiccup - usually due a mistake I've made.

**Comment by robertsLando** [comment]
It's almost always safe to use `dev`
