### ISSUE TITLE
Question: How can I determine why my ZW3008 dimmer is suddenly reporting 112 entities that don't exist?

### ISSUE THREAD

**Issue by uberDoward** [zwave-js/zwavejs2mqtt#1280]
Yeah, so yesterday this started.   I have a ZW3008 Dimmer motion sensor that's in my kitchen pantry.   Node 53.   Attaching a debug log (search Pantry, you'll see this over and over as new entities):

2021-05-26 00:51:22.226 DEBUG GATEWAY: Publishing discovery: {,
  type: 'light',,
  object_id: 'dimmer_111',,
  discovery_payload: {,
    command_topic: 'zwave/Kitchen/Pantry_Light/38/111/targetValue/set',,
    state_topic: 'zwave/Kitchen/Pantry_Light/38/111/currentValue',,
    state_value_template: '{{ "OFF" if value_json.value == 0 else "ON" }}',,
    brightness_command_topic: 'zwave/Kitchen/Pantry_Light/38/111/targetValue/set',,
    brightness_scale: 99,,
    brightness_state_topic: 'zwave/Kitchen/Pantry_Light/38/111/currentValue',,
    brightness_value_template: '{{ value_json.value }}',,
    on_command_type: 'brightness',,
    device: {,
      identifiers: [ 'zwavejs2mqtt_0xf70bd2c6_node53', [length]: 1 ],,
      manufacturer: 'GE/Jasco',,
      model: 'In-Wall Smart Motion Dimmer (26932 / 26933 / ZW3008)',,
      name: 'Kitchen-Pantry Light',,
      sw_version: '5.32',
    },,
    name: 'Kitchen-Pantry Light_dimmer_111',,
    unique_id: 'zwavejs2mqtt_0xf70bd2c6_53-38-111-currentValue',
  },,
  discoveryTopic: 'light/Kitchen-Pantry_Light/dimmer_111/config',,
  values: [ '38-111-currentValue', '38-111-targetValue', [length]: 2 ],,
  persistent: false,,
  ignoreDiscovery: false,
},
2021-05-26 00:51:22.227 DEBUG GATEWAY: Publishing discovery: {,
  type: 'light',,
  object_id: 'dimmer_112',,
  discovery_payload: {,
    command_topic: 'zwave/Kitchen/Pantry_Light/38/112/targetValue/set',,
    state_topic: 'zwave/Kitchen/Pantry_Light/38/112/currentValue',,
    state_value_template: '{{ "OFF" if value_json.value == 0 else "ON" }}',,
    brightness_command_topic: 'zwave/Kitchen/Pantry_Light/38/112/targetValue/set',,
    brightness_scale: 99,,
    brightness_state_topic: 'zwave/Kitchen/Pantry_Light/38/112/currentValue',,
    brightness_value_template: '{{ value_json.value }}',,
    on_command_type: 'brightness',,
    device: {,
      identifiers: [ 'zwavejs2mqtt_0xf70bd2c6_node53', [length]: 1 ],,
      manufacturer: 'GE/Jasco',,
      model: 'In-Wall Smart Motion Dimmer (26932 / 26933 / ZW3008)',,
      name: 'Kitchen-Pantry Light',,
      sw_version: '5.32',
    },,
    name: 'Kitchen-Pantry Light_dimmer_112',,
    unique_id: 'zwavejs2mqtt_0xf70bd2c6_53-38-112-currentValue',
  },,
  discoveryTopic: 'light/Kitchen-Pantry_Light/dimmer_112/config',,
  values: [ '38-112-currentValue', '38-112-targetValue', [length]: 2 ],,
  persistent: false,,
  ignoreDiscovery: false,
},
2021-05-26 00:51:22.228 DEBUG GATEWAY: Publishing discovery: {,
  type: 'light',,
  object_id: 'dimmer_113',,
  discovery_payload: {,
    command_topic: 'zwave/Kitchen/Pantry_Light/38/113/targetValue/set',,
    state_topic: 'zwave/Kitchen/Pantry_Light/38/113/currentValue',,
    state_value_template: '{{ "OFF" if value_json.value == 0 else "ON" }}',,
    brightness_command_topic: 'zwave/Kitchen/Pantry_Light/38/113/targetValue/set',,
    brightness_scale: 99,,
    brightness_state_topic: 'zwave/Kitchen/Pantry_Light/38/113/currentValue',,
    brightness_value_template: '{{ value_json.value }}',,
    on_command_type: 'brightness',,
    device: {,
      identifiers: [ 'zwavejs2mqtt_0xf70bd2c6_node53', [length]: 1 ],,
      manufacturer: 'GE/Jasco',,
      model: 'In-Wall Smart Motion Dimmer (26932 / 26933 / ZW3008)',,
      name: 'Kitchen-Pantry Light',,
      sw_version: '5.32',
    },,
    name: 'Kitchen-Pantry Light_dimmer_113',,
    unique_id: 'zwavejs2mqtt_0xf70bd2c6_53-38-113-currentValue',
  },,
  discoveryTopic: 'light/Kitchen-Pantry_Light/dimmer_113/config',,
  values: [ '38-113-currentValue', '38-113-targetValue', [length]: 2 ],,
  persistent: false,,
  ignoreDiscovery: false,
},

[zwave-js_log_pantry.log](https://github.com/zwave-js/zwavejs2mqtt/files/6546182/zwave-js_log_pantry.log)

**Comment by robertsLando** [comment]
@uberDoward I suggest you to enable zwavejs server in settings and use zwavehjs hass integration for a better support, I don't plan to keep mqtt discovery maitained
