### ISSUE TITLE
Netwok graph : flat, no links

### ISSUE THREAD

**Issue by ludisnet** [zwave-js/zwavejs2mqtt#1288]
### Version

**Checklist:**

- [x] I am **not** using HomeAssistant. **Or:** a developer has told me to come here.
- [x] I have checked the troubleshooting section and my problem is **not** described there.
- [x] I have read the changelog problem was **not** mentioned there.

Build/Run method

- [ ] Docker
- [x] PKG
- [ ] Snap package
- [ ] Manually built (git clone - yarn install - yarn run build )

zwavejs2mqtt version: <version here, you can find it on control panel>
zwave-js version: <version here, you can find it on control panel>

**Comment by robertsLando** [comment]
@ludisnet Did you try to press on the fab button you find on bottom left corner?

**Comment by ludisnet** [comment]
outch ! , this is ok now ..... 

Thanks for reply !

regards.

Ludisnet

![image](https://user-images.githubusercontent.com/5323220/119962596-7ea33180-bfa7-11eb-8c02-0cd47fb70fce.png)
