### ISSUE TITLE
[bug] Philio fails to report item to HASS (caused by '/' ?)

### ISSUE THREAD

**Issue by Swiftnesses** [zwave-js/zwavejs2mqtt#129]
Running latest docker dev.

My Philio 4-in-1 sensors fails to report an item to HASS.

`{
  "type": "binary_sensor",
  "object_id": "contact_0",
  "discovery_payload": {
    "payload_on": true,
    "payload_off": false,
    "value_template": "{{ value_json.value }}",
    "device_class": "door",
    "state_topic": "zwavejs2mqtt/44/48/0/Door/Window",
    "json_attributes_topic": "zwavejs2mqtt/44/48/0/Door/Window",
    "device": {
      "identifiers": [
        "zwavejs2mqtt_0xfa81a924_node44"
      ],
      "manufacturer": "Philio Technology Corp",
      "model": "Slim Multi-Sensor (PIR/Door/Temperature/Illumination) (PST02A)",
      "name": "nodeID_44",
      "sw_version": "1.16"
    },
    "name": "zwave_nodeID_44_contact_0",
    "unique_id": "zwavejs2mqtt_0xfa81a924_44-48-0-Door/Window"
  },
  "discoveryTopic": "binary_sensor/nodeID_44/contact_0/config",
  "values": [
    "48-0-Door/Window"
  ],
  "persistent": false,
  "ignoreDiscovery": false,
  "id": "binary_sensor_contact_0"
}`

I assume it's related to the '/' in 'Door/Window'?

You can see the full sensor below, the other 'contact' item reports okay (even though it's useless :) )

<img width="1817" alt="Screenshot 2020-12-31 at 11 24 49" src="https://user-images.githubusercontent.com/1001877/103408600-161c6980-4b5b-11eb-8f09-20919e7bf0cc.png">

**Comment by Swiftnesses** [comment]
I can confirm how I fixed it, I changed:

`"discoveryTopic": "binary_sensor/nodeID_44/contact_0/config"`

TO

`"discoveryTopic": "binary_sensor/nodeID_44/contact_zero/config"`

I assume a quirk of HASS MQTT discovery?

**Comment by robertsLando** [comment]
@Swiftnesses so you confirm it's not cause by the slash in the unique id? @billiaz thoughts on this?

**Comment by billiaz** [comment]
i have encounterednoumerous issues with slashes on hass. Sanitising the names even more is good to have.
Unique_id should use only underscores and hyphens. but we need to confirm.

**Comment by robertsLando** [comment]
@billiaz We should have a sanitize function, we could add sanification also for `/`. Can you make this in a PR?

**Comment by billiaz** [comment]
it is obvious topic creates a subtopic due to slash! we need to change it

@Swiftnesses can you show a list of topics under `zwavejs2mqtt/44/48/0`

**Comment by billiaz** [comment]
@Swiftnesses I have the same sensor Philip PTS02A but I have no CC 48! is the dipswitches the ones i need to change for this to appear?

**Comment by robertsLando** [comment]
I think this shuld be fixed now
