### ISSUE TITLE
[question] Association controlling HA entities?

### ISSUE THREAD

**Issue by MRobi1** [zwave-js/zwavejs2mqtt#1290]
I’ve setup an association so when my basement hallway light switch is pressed, the front theatre and back theatre lights also come on/off. The association itself is working fine.

What I’m noticing is that the entities light.theatre_light_front and light.theatre_light_back do not turn on/off even though the switch itself is turning on through the association.

Aside from creating an automation to turn the 2 entities on/off when the hallway light turns on (defeating the purpose of association), is there a way to get the entities in HA to turn on/off when controlled through association? All devices are GE 14294 dimmers.

EDIT: This may be specific to the GE switches. I just tested associating an Inovelli switch and the entity is turning on/off

**Comment by robertsLando** [comment]
If I got it well you have a light A, B, C and you want to make them work in the same way, if one turns on/off also the others should turn on/off. If so you have to setup associations in every light with the others

**Comment by MRobi1** [comment]
> If I got it well you have a light A, B, C and you want to make them work in the same way, if one turns on/off also the others should turn on/off. If so you have to setup associations in every light with the others

Not quite. I have light A, B, C. I want light A to control light B and C. And it does with no issue.
But when I use light A to turn on light's B and C, the entity in home assistant doesn't update, it still displays as off even though the light is actually on. So the issue is light B and C aren't updating the entity in HA when controlled through association.

I've tested on Inovelli switches and they work as expected so this is strictly with the GE devices.

**Comment by robertsLando** [comment]
Ok now the issue is more clear. Can you upload logs export please? https://zwave-js.github.io/zwavejs2mqtt/#/troubleshooting/bug_report
