### ISSUE TITLE
Mismatched/missing controls in HASS for Honeywell TH6320ZW Thermostat (-> HASS via mosquitto/zwavejs2mqtt) 

### ISSUE THREAD

**Issue by KelvinHelmholtz** [zwave-js/zwavejs2mqtt#1291]
I am consolidating three separate issues occurring in the hass lovelace UI card into one issue here (for efficiency of attention).  Will be happy to separate them out should experts so deem/advise:

1.  Changing temperature setting through the dial does not work.
2.  Of the five setting options 'auto' and 'dry' do not work; only heat, cool, off and work.
3.  FanMode is missing

------------
1.  Changing temperature setting through the dial does not work:
I have set the physical device to operate in Fahrenheit.  Its screen reflects and changes values in Fahrenheit.  The lovelaceUI card reflects the current temp identical to the physical device (Fahrenheit).  But the smaller display shows 40 and when moving the dial the numbers are lower (presumably in Celsius though I have not confirmed).

From nodes_dump for this device: 
          "unit": "°C",

The thermostat on receiving a lower temp than lowest allowed (40F), resorts to 40 as follows::
...
2021-05-28 17:53:04.307 INFO MQTT: Message received on zwave/GroundFloor/MainThermostat/67/0/setpoint/1/set, '20.5'
2021-05-28 17:53:04.310 INFO ZWAVE: Writing 20.5 to 3-67-0-setpoint-1
2021-05-28 17:53:11.950 DEBUG MQTT: Publishing to zwave/GroundFloor/MainThermostat/67/0/setpoint/1: { time: 1622249591950, value: 40 } with options { qos: 1, retain: true }
2021-05-28 17:53:11.953 INFO ZWAVE: Node 3: value updated: 67-0-setpoint-1 20.5 => 40
2

When I tried to refresh the multisensor listing on zwavejs2mqtt web front end, the reading changed substantially reflecting a likely mismatch in the units  (i am attaching two pics reflecting the before and after refresh readings in case pertinent to diagnosis). 

Left me wondering if this was a bug in the device's zwave reporting, or, a (USB or Zwavejs) driver fill-in issue.  Should it be determined to be a bug with the device, I will contact Honeywell for a fix but would appreciate a workaround.

-------------
2.  Of the five setting options 'auto' and 'dry' do not work; only heat, cool, off and work.
LovelaceUI card option for auto and dry seems to send command values in string whereas the thermostat is expecting a number (ref: nodes_dump.json below).  On attempting auto on the lovelace UI card, the log shows:

2021-05-28 18:19:33.415 INFO MQTT: Message received on zwave/GroundFloor/MainThermostat/64/0/mode/set, 'auto'
2021-05-28 18:19:38.421 INFO ZWAVE: Writing undefined to 3-64-0-mode
2021-05-28 18:19:38.437 INFO ZWAVE: Controller status: Driver: Thermostat Mode: "mode" must be of type "number", received "undefined"
2021-05-28 18:19:38.443 ERROR ZWAVE: Unable to write undefined on 3-64-0-mode

Is I manually tried publishing the auto mode, the thermostat refused anyway.  The thermostat only would allow 0:Off, 1:heat, 2:cool, 11 energy_heat (heat in away mode) and 12 energy_cool (cooling in away mode)  - Away modes have different setpoints.
 
Further, the thermostat stores the target temperatures for colling and heating modes in separate variables, therefore the target number appearing the lovelaceUI card would need to be auto-modified based on which mode (if any) was selected.

Would appreciate a fix/workaround.

-------------
3. The Fan only options ( ref: nodes_dump.json below) available on the thermostat/hvac does not appear on the lovelace card.

Would appreciate a fix/workaround.

-------------
On a side node, I considered creating a thermostat entity manually with all the examples but that required json transformation to translate the hass climate entities mode and fanmode into number commands - any pointers from the experts on this would be appreciated.
--------------
[2021-05-27.nodes_dump.json.txt](https://github.com/zwave-js/zwavejs2mqtt/files/6563908/2021-05-27.nodes_dump.json.txt)
![Capture](https://user-images.githubusercontent.com/84689765/120055277-d5315f80-bfe9-11eb-814d-bd8cea3417ce.jpg)
![Capture2](https://user-images.githubusercontent.com/84689765/120055281-d9f61380-bfe9-11eb-81e3-560f645bf1da.JPG)

**Comment by robertsLando** [comment]
@KelvinHelmholtz I think you are using mqtt discovery, right? Have you considered to enable zwave-js server and use hass integration? It has a better support then mqtt discovery

**Comment by KelvinHelmholtz** [comment]
Hi, you're correct about my use of mqtt discovery.  Went that route as I was unable to get zwave-js server integration on my instance of hass portable/windows.  The hass portable/windows only allowed me openzwave (which I built and tested barebones and tested with minOZW but was not successful with the packaged version that has the mqttservice apparently required by hass portable's available integration).

From reading the dumps and logs more: the fan issue is a mismatch of the thermostat's expected read writes on 3-67-0 versus the 3-68-0 being published by zwavejs2mqtt.  Probably a quick correction.  

I created a logical thermostat (climate entity via config.yaml) in hass and mapped the thermostat's mqtt read and writes from nodes_dump.json with node red's mqtt service (with a minimal state mgt/checking) and was able to all the functions to map correctly.  The only issue is reliability - the ops seem to freeze sometimes when either node red or hass or zwavejs2mqtt apparently await a key entry on the respective dos command boxes before proceeding (with pent up messages).  It would be wonderful to get the zwavejs2mqtt to hass work directly and fully with this thermostat.

Also, btw, the current implementation is also missing thehumidity sensor integratio into the climate entity and its a bummer that while hass' climate entity allows for a humidity sensor, the config.yaml climate entry does not offer a direct tie in like it does for temperature.

Thanks for your review

**Comment by robertsLando** [comment]
> 2021-05-28 18:19:33.415 INFO MQTT: Message received on zwave/GroundFloor/MainThermostat/64/0/mode/set, 'auto'
2021-05-28 18:19:38.421 INFO ZWAVE: Writing undefined to 3-64-0-mode

When climate entities are created there is an entry that maps modes to values as HASS sends string values and zwavejs expects a number value. Check an example [here](https://github.com/zwave-js/zwavejs2mqtt/blob/master/hass/devices.js#L43). 

What you could try is to create an entry for your thermostat in this file to fix the discovery, also about humidity that is not suppported

**Comment by KelvinHelmholtz** [comment]
Thank you for the pointer to the file, I see there is some room to redo the map.  Once I go through this may I post the changes back to you for a review.  Also what would I need to do get the changes incorporated.

Thanks also for letting me know about the support for the humidity sensor status.  I guess I can just make a separate device/ui card for it.

**Comment by robertsLando** [comment]
The changes are automatically picked up by z2m on startup

**Comment by KelvinHelmholtz** [comment]
Thank you. I will try to define the device specs and post here for a review.

**Comment by KelvinHelmholtz** [comment]
I tried the attached devices.js (placed in the hass sub folder), same issues.  

BTW the commented lines were an attempt to map the data from z2m nodes_dump to the devices.js entity but z2m launch was failing with these in there so I commented them out.

[devices.js.txt](https://github.com/zwave-js/zwavejs2mqtt/files/6601688/devices.js.txt)
