### ISSUE TITLE
[bug] NEO Coolcam Roller Shutter - Curtain Switch - NAS-SC03ZE-2-T-V3 disappears

### ISSUE THREAD

**Issue by Goldwing1973** [zwave-js/zwavejs2mqtt#1293]
**Checklist:**

- [X] I am **not** using HomeAssistant. **Or:** a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is **not** described there.
- [X] I have read the changelog problem was **not** mentioned there.

Build/Run method

- [X] Docker
- [ ] PKG
- [ ] Snap package
- [ ] Manually built (git clone - yarn install - yarn run build )

zwavejs2mqtt version: zwavejs2mqtt: 4.5.0
zwave-js version: zwave-js: 7.7.0

### Describe the bug

I have 3 NEO Coolcam Roller Shutter - Curtain Switch - NAS-SC03ZE-2-T-V3’s
One is presumed dead by Z-WaveJS because it isn’t powered on/not connected and is still visible in the control panel.
But the other 2 just vanished, like they where Excluded.
It’s not the first time it happened, a couple of months ago it happened before. 

### To Reproduce

There are no steps to actually reproduce it, it just happens.

**Comment by robertsLando** [comment]
Missing logs

**Comment by Gis70** [comment]
These curtains switch are just peace of shit. I bought 3 of them,they will going to the bin. They lost the pairing suddently too and it's not zwavejs the problem. (i was on ozw 1.4 before it was the same)

**Comment by Goldwing1973** [comment]
> These curtains switch are just peace of shit. I bought 3 of them,they will going to the bin. They lost the pairing suddently too and it's not zwavejs the problem. (i was on ozw 1.4 before it was the same)

That doesn’t explain how they disappeared in the list of devices in ZwaveJS.
If the device loses pairing it should still be in ZwaveJS as a dead device.

**Comment by Gis70** [comment]
> > These curtains switch are just peace of shit. I bought 3 of them,they will going to the bin. They lost the pairing suddently too and it's not zwavejs the problem. (i was on ozw 1.4 before it was the same)
> 
> That doesn’t explain how they disappeared in the list of devices in ZwaveJS.
> If the device loses pairing it should still be in ZwaveJS as a dead device.

Yes you're right.

**Comment by robertsLando** [comment]
Without a startup log or else I cannot help you I'm sorry

**Comment by Goldwing1973** [comment]
> Without a startup log or else I cannot help you I'm sorry

I have set the logging to “debug” hoping it will be reoccurring soon.

**Comment by robertsLando** [comment]
News? Can we close this?

**Comment by Goldwing1973** [comment]
> News? Can we close this?

Yes, I will reopen an issue when it occurs again, and then with the logs.

**Comment by wube1** [comment]
@pawkakol1 Hi pawkakol1, sorry to fish you oout here like that, i have a question regarding some other branch you were contributing to. May I ask if there is a way to contact you with priv messages? Thanks a lot in advance for your reply.

**Comment by pawkakol1** [comment]
@wube1 go a head. My e-mail is visible

**Comment by Goldwing1973** [comment]
Nearly a year later, but I’m going to trash the devices.
Ik ‘m reading more and more from others having the same problem, apparently the device is buggy as hell and invokes a reset on its own from time to time.
I now ordered a Fibato Walli roller shutter, if that works better I’ll replace them all.
@AlCalzone , thank you for your efforts.

**Comment by pawkakol1** [comment]
I noticed, that device resets itself if on network are some baterry powered devices, and one of such device will discharge. Earlier I didnt pay attention on discharged devices, and my NAS-SC03ZE-2-T-V3 device was resetting every few days. Since I noticed association with baterry discharging, I started to charge them before they were discharged about 3 mounths ago. Up today I havent had any situation of reset NAS-SC03ZE-2-T-V3 device, and I hope it will be last as long as possible.
I suppose, that non-baterry powered, but powered down devices will affect likewise.

**Comment by AlCalzone** [comment]
> I suppose, that non-baterry powered, but powered down devices will affect likewise.

If that's the case, there is something seriously wrong with the device.

**Comment by Goldwing1973** [comment]
> > I suppose, that non-baterry powered, but powered down devices will affect likewise.
> 
> If that's the case, there is something seriously wrong with the device.

If you want, i can send you one (at my expense) to fool around with it, and i don't need/want it back

**Comment by Goldwing1973** [comment]
One last attempt...
I installed HA + Z-WaveJS2mqtt on a Pi3, plugged a factory reset Aeon Labs ZW090 stick in it and added the curtain switch.
After adding i pressed some buttons and then i kept on pressing the down button, and yes, the device also registered my finger on the center button and after 10 seconds or so, it factory resetted.
But... i was NOT removed from Z-WaveJS, it remained as a DEAD node after i pinged it.
I;ve attached a log (silly level), could you taken one more look @AlCalzone ? maybee you can see why it is not removed from Z-WaveJS this time.
[zwavejs2mqtt_2022-05-07.log](https://github.com/zwave-js/zwavejs2mqtt/files/8645139/zwavejs2mqtt_2022-05-07.log)

**Comment by AlCalzone** [comment]
That's not a driver log, so I can't tell

**Comment by robertsLando** [comment]
@AlCalzone Maybe it's worth to add a comment on this device config file to warn about this?

**Comment by AlCalzone** [comment]
Yeah, I guess.
