### ISSUE TITLE
zwavejs2mqtt unofficial add-on for hassos installs

### ISSUE THREAD

**Issue by johntdyer** [zwave-js/zwavejs2mqtt#130]
I would love to run zwavejs2mqtt on my HassOS install.  

**Describe the solution you'd like**
The typical approach would be an add-on, and I am hoping for an unoffical add-on repository 

**Describe alternatives you've considered**
n/a

**Comment by robertsLando** [comment]
I think this is wasy to do by forking the existing addon for the Zwave2Mqtt , are you able to do it?

**Comment by blhoward2** [comment]
Just a note that you can do so even without an add on. Just install portainer and then install the docker image.

**Comment by scyto** [comment]
the biggest reason to do the add-on is to remove the old addon if zwave2mqtt is to be deprecated, where is the addon located in terms of source (i assume it just pull's roberts container rather than anyone elses) as such can't be too hard to replicate and change - even a no-coder like me might be able to do it....

**Comment by scyto** [comment]
oh, just read this https://github.com/hassio-addons/addon-zwave2mqtt/issues/70 does that mean even if we created an add-on they wouldn't take it - or just that they don't want to work on it?

**Comment by blhoward2** [comment]
You can build your own image easily. The directions are at the bottom. https://github.com/zwave-js/zwavejs2mqtt/tree/master/docker

A lot changed from that post, including the maintainer of qt-openzwave effectively stepping back. There is a proposal to change the path forward to a new server built on the same backend as this project (node-zwave-js).

**Comment by scyto** [comment]
@blhoward2 thanks, i happy to use Roberts image for now and know how to create my own docker images if it is missing something, i was more trying to give back to community  and the code for the add-on isn't really code but mostly docker config - was willing to fork it and attempt to create an add-on... but if folks thinks thats not needed i certainly don't want to push water up hill :-)

**Comment by blhoward2** [comment]
It wouldn’t hurt for now, actually. I’ve heard no plans to make a Zwavejs2mqtt add on as the integration won’t use that project. Right now it’s difficult for people to install and they need to use Portainer. 

@robertsLando @AlCalzone Have you heard differently?

**Comment by robertsLando** [comment]
@frenck Do you know about last news? Could you think about making a new addon now?

**Comment by frenck** [comment]
I have no time for that at this point, furthermore, things seem to be in early development stages. Happy to jump in at some point, but not now.

**Comment by robertsLando** [comment]
@frenck Ok no problem. I dunno if you are aware of this but actually we are working with hass team in: https://github.com/zwave-js/zwave-js-server that will be installed in zwavejs2mqtt and will communicate with a new hass addon to create entities (something like the ozw beta integration is doing now with qt-openzwave)

**Comment by frenck** [comment]
Yes, I'm part of the core team, I'm aware.

**Comment by jcam** [comment]
Are all of the addons in https://addons.community managed by the core team / @frenck , or could we build out our own and have it added?

Worst case, we just set up our own addon repository that people would need to add via the interface until it becomes 'official'.

As for the timeline @blhoward2 the official integration already supports the switch, sensor, and light class, it is in the dev nightlies, and is being added to quickly. I'd be surprised if we didn't see some sort of beta by February

**Comment by frenck** [comment]
It is planned for the first Wednesday of February release indeed.

The community add-ons is my private project.

We have discussed it in our team yesterday, an official, core supported and maintained, add-on will me made.

The Aim, is to have a first version ready to support the first integration version, before the February release.

**Comment by robertsLando** [comment]
Closing this

**Comment by frenck** [comment]
WIP: https://github.com/hassio-addons/addon-zwavejs2mqtt

**Comment by robertsLando** [comment]
Thanks @frenck

**Comment by frenck** [comment]
No problem @robertsLando! Are you on discord btw?

**Comment by robertsLando** [comment]
Nope, should I?

**Comment by frenck** [comment]
No not needed. Will uses issues instead.
