### ISSUE TITLE
[question] Plugin example is confusing

### ISSUE THREAD

**Issue by kvaster** [zwave-js/zwavejs2mqtt#1303]
I'm trying to write some plugins for myself (i.e. updated prometheus exporter, some simple alerting system without external tools like home assistent). And I'm facing problems. I'm not experienced in js programming, but...

About [example](https://zwave-js.github.io/zwavejs2mqtt/#/guide/plugins): I think that it will be good to update example, cause generally this one will not work, cause MyPlugin function should return something :) i.e.:

```
class MyPlugin {
  constructor(ctx) {
    this.zwave = ctx.zwave
    this.mqtt = ctx.mqtt
    this.logger = ctx.logger
    this.app = ctx.app
    ...
  }
}

module.exports = function (ctx) {
  return new MyPlugin(ctx)
}
```

And my main problem is using express app. Example advice is using following:

```
this.express.get('/my-route', function(req, res) {...})
```

But this will not work.

1) All requests without accept header (`Accept: application/json, text/plain`) will be routed to 404 error (i.e. `/health` route).

2) With accept header only standard requests will be processed - you will still get 404 error with code from example. I think this is cause middleware with forcing 404 error and redirecting to error page is registered before plugin initialization.

3) The only way is to patch zwavejs2mqtt:

```
// ### ERROR HANDLERS

const pluginApp = express()
app.use(pluginApp)

// catch 404 and forward to error handler
...
```

And to pass pluginApp insteadof app to plugins...

**Comment by robertsLando** [comment]
You right about the routes, I need to create a router and add it to express before passing it to plugins or init plugins before initing erro handlers. 

> I think that it will be good to update example, cause generally this one will not work, cause MyPlugin function should return something

Could you update the example please? 

Also once your plugin is done tell me and I will add to the list of available plugins

**Comment by kvaster** [comment]
> You right about the routes, I need to create a router and add it to express before passing it to plugins or init plugins before initing erro handlers.
> 
> > I think that it will be good to update example, cause generally this one will not work, cause MyPlugin function should return something
> 
> Could you update the example please?

I will do, but we need to create router first.
I will need little help for checking code - do not know 'good practices' for js :)
 
> Also once your plugin is done tell me and I will add to the list of available plugins

Just waiting for router fixes.

**Comment by kvaster** [comment]
Also it will be good to have standartized way for configuring plugins

**Comment by robertsLando** [comment]
@kvaster I'm doing a big refactor switching to typescript in #1297. I prefer to end with that before adding new features/fix bugs, could you hold a bit?

**Comment by kvaster** [comment]
Great news! Will be waiting!

**Comment by kvaster** [comment]
Just for info. Two small plugins:

* [Prometheus metrics plugin](https://github.com/kvaster/zwavejs-prom)
* [Simple alert plugin](https://github.com/kvaster/zwavejs-alert)

**Comment by robertsLando** [comment]
Added a fix in #1297

**Comment by Gis70** [comment]
@robertsLando I don't see the 2 plugins mentionned above in the plugin list in the UI, did you add them ?

**Comment by robertsLando** [comment]
@kvaster are those plugins available on npm? BTW @Gis70 you can use them by just installing them somewhere and enter in plugins settings the path to the folder where the plugin is installed. 

Example: 

Let's say you create a `plugins` directory on `store`, you can git clone and compile the two plugins here and then in plugins write the path to that folder (better if using a absolute path like `/usr/app/store/plugins/zwavejs-prom`

**Comment by frittes** [comment]
> Done ! it is working, i receive telegram alert. thx a lot for your help, hope it will be helpfull for other people like me :-)

How have you done it? How can I compile the cloned git-repo?

**Comment by Gis70** [comment]
> > Done ! it is working, i receive telegram alert. thx a lot for your help, hope it will be helpfull for other people like me :-)
> 
> How have you done it? How can I compile the cloned git-repo?

I just copied the file in a directory. I didn't compile and it have worked. (For telegram alert)
