### ISSUE TITLE
Freak error in "driver ready" handler

### ISSUE THREAD

**Issue by AlCalzone** [zwave-js/zwavejs2mqtt#1309]
See screenshot from Sentry:
![grafik](https://user-images.githubusercontent.com/17641229/120939497-a5383980-c718-11eb-9902-facb70b8b0cf.png)

I have no clue why this happens, because from `zwave-js` perspective, the controller **is** ready. It does affect 4 users though. Maybe this could be handled more gracefully on your end?

**Comment by robertsLando** [comment]
Process. nexttick?

**Comment by AlCalzone** [comment]
Don't see how that helps. The code that emits the event you're using is basically:
```ts
this._controller = ...
// ...
this.emit("driver ready")
```
and the error that is happening is:
```ts
if (!this._controller) throw new Error(...)
```
so I have no fucking clue how that can happen, except that the driver is destroyed in the meantime.

**Comment by robertsLando** [comment]
So what do you suggest? to check if there is actually a controller before binding events? and if not what should I do?

**Comment by AlCalzone** [comment]
I'd say Just put the part in a try catch and restart the driver if it throws.
