### ISSUE TITLE
[question] Logging and cache file

### ISSUE THREAD

**Issue by rwa** [zwave-js/zwavejs2mqtt#131]
First, amazing project! I am really glad there's an alternative developing to OZW. Looks like really solid work.

I'm testing this out on my zwave network by running the control panel.  I installed from source, and started the control panel using npm. I was initially getting very detailed logging under the "debug" tab - down to specific frames. I then changed the configuration to specify the logging level, and now I seem to only get a much less detailed view of the logging, no matter which level I pick and "save" in the configuration.

When I select "log to file", what is the path to the logfile?

Also, on subsequent restarts, I notice some nodes say they are starting from cache.  Can I blow away this cache file and start fresh? Where is it located?

**Comment by rwa** [comment]
I think I figured out the cache thing. I noticed that a fresh checkout has nothing under store/, and if I blew away everything under there, it seemed to start fresh.

**Comment by robertsLando** [comment]
Everything is located in store folder, except the zwavejs log file that is located in bin folder (there is an open pr on zwavejs repo to fix this)

**Comment by robertsLando** [comment]
Just for info: 
There are 2 loggers, one for zeavejs (zwave driver that replace ozw) and one for z2m.
Everything is store in store folder, settings.json contains the settings (gateway, zwave and mqtt), scenes contains scenes and other files are ozw cache files and start with the home hex number as prefix
