### ISSUE TITLE
[bug] Changing node name doesn't update topics that the node uses for set commands.

### ISSUE THREAD

**Issue by mrherman** [zwave-js/zwavejs2mqtt#1311]
### 4.5.1

**Checklist:**

- [ X ] I am **not** using HomeAssistant. **Or:** a developer has told me to come here.
- [ X ] I have checked the troubleshooting section and my problem is **not** described there.
- [ X ] I have read the changelog problem was **not** mentioned there.

Build/Run method

- [ X ] Docker
- [ ] PKG
- [ ] Snap package
- [ ] Manually built (git clone - yarn install - yarn run build )

zwavejs2mqtt version: 4.5.1
zwave-js version: 7.7.1

### Describe the bug

Nodes do not respond to incoming mqtt set commands using new node name after changing the name of the node.

### To Reproduce

In Settings->Gateway select Use nodes name instead of numeric nodeIDs
(Aside, there is a typo, it should be Use node names or Use node's name)

Send a mqtt set topic/command to one of your zwave devices, confirm you can control it.
Change the node name of the zwave device.
Send a mqtt message using the new name in the topic, you should see it does not work.
Send a mqtt message using the old name in the topic, it will control the device.

restart mqtt2zwavejs and it'll work as expected.

### Expected behavior

The zwave device should respond to mqtt topics using the new name immediately.

### Additional context

zwavejs2mqtt does send mqtt topics with the new name immediately.  This is only an issue for mqtt messages that zwavejs2mqtt is receiving.

**Comment by robertsLando** [comment]
After changing a node name or location you should press on node Advanced button and press on `Update Topics > Update` in order to update its topics :) 
![Schermata da 2021-06-09 17-23-56](https://user-images.githubusercontent.com/11502495/121383345-abf8c380-c947-11eb-8d0e-131aff8132d7.png)

**Comment by mrherman** [comment]
Thanks for pointing that out, I didn't know about that menu.  

I think this might still be worth thinking about.  The time between changing the node name and hitting update topics, messages sent from zwavejs2mqtt use the new name, while not reading from the new name; therefore, it is not consistent.

I would vote for just updating topics when the name/location are changed (and not having to do it manually in that menu); although, more importantly just being consistent with both incoming and outgoing messages.

**Comment by robertsLando** [comment]
Ok will add that to my todos :)
