### ISSUE TITLE
[question] Philio PAN in-wall-relay workaround that worked in OZW, how to implement?

### ISSUE THREAD

**Issue by Swiftnesses** [zwave-js/zwavejs2mqtt#132]
Hello,

One of my Philio PAN in wall switches requires polling to ensure the correct switch states.

I previously used Node Red to call the Home Assistant zwave refresh for the endpoints. How can I achieve this?

BTW - Spent the day setting this up and getting everything working right in HASS (needed some minor persistent tweaks, but nothing too major!). Thank you for creating such a solid platform, looking forward to future developments!

Screenshot of how I updated the endpoints before:
<img width="589" alt="Screenshot 2021-01-01 at 18 09 59" src="https://user-images.githubusercontent.com/1001877/103444058-f9685a80-4c5c-11eb-802d-1efba2461f6a.png">

**Comment by robertsLando** [comment]
@Swiftnesses Unfortunally polling is not supported by zwavejs yet :(

**Comment by billiaz** [comment]
@robertsLando @Swiftnesses I think v6 supports it right @robertsLando ?

**Comment by robertsLando** [comment]
@billiaz No, AFAIK. There is no work in progress in polling

**Comment by blhoward2** [comment]
This is now achievable with #245 to refresh just the dynamic values. Recommend closing @robertsLando.

**Comment by robertsLando** [comment]
Yep thanks :pray: :smile:

**Comment by Swiftnesses** [comment]
@blhoward2 I tried this via the UI and it works! How do I trigger a refresh via MQTT? Thank you, both.

**Comment by blhoward2** [comment]
Publish to:

homeassistant/_CLIENTS/ZWAVE_GATEWAY-[nodeid]/api/refreshValues/set

With a payload of:

{
"args": [nodeid]
}

Replace the [nodeid]s. 

That's for manual polling basically. If you want polling on a set interval there is now polling support too.

**Comment by Swiftnesses** [comment]
Sorted just as you posted, thank you, this was the only thing missing from OZW.
