### ISSUE TITLE
[feat] Target Value should be selectable by user

### ISSUE THREAD

**Issue by Lopton** [zwave-js/zwavejs2mqtt#133]
**Is your feature request related to a problem? Please describe.**
Currently the targetValue is a toggle switch. This toggle is (by design?) out of sync with the current state of the switch. So what happens is that the "current value" will show true, but the target value will show false. Now to turn off the switch I have to issue two commands, once to toggle the target value on then, then another to toggle the target value off.

<img width="711" alt="TargetValue" src="https://user-images.githubusercontent.com/6832191/103462714-0ed09980-4cdc-11eb-926a-64ae5fc3a7d7.png">

**Describe the solution you'd like**
I would like to have the option to select which target value I want to send. 

**Describe alternatives you've considered**
You could ignore this request :)

**Additional context**

**Comment by robertsLando** [comment]
@Lopton Thanks for your issue, @AlCalzone I don't remember our last discussion about target/current values but shouldn't (at least on startup) targetValue be equal to current?

**Comment by AlCalzone** [comment]
Guess I need a log to know why they aren't in sync. IMO it should be possible somehow to re-send the same target value through the UI for exactly this case.

**Comment by robertsLando** [comment]
@AlCalzone Maybe they could be out of sync when the switch is switchef manually and not from hass or ui

**Comment by AlCalzone** [comment]
Might be, depending on the device configuration.

**Comment by billiaz** [comment]
I face the same issue, but I never use the UI here. 
Can be also that is easier to use a Dropdown than slider and dorce the command, or even better 2 buttons! true/false!

**Comment by robertsLando** [comment]
We could use 2 buttons for this, and make target value stateless ?

**Comment by robertsLando** [comment]
@billiaz @Lopton COuld someone give me a feedback about https://github.com/zwave-js/zwavejs2mqtt/pull/151 ?

**Comment by AlCalzone** [comment]
targetValue is not stateless. Some devices do report both current and targetValue (so you know where the transition is going to)

**Comment by robertsLando** [comment]
@AlCalzone You right, I have added state to the new implementation. If you have any suggestion let me know :)
