### ISSUE TITLE
[feat] and [bug] Nowhere to see what version you are running?

### ISSUE THREAD

**Issue by blhoward2** [zwave-js/zwavejs2mqtt#134]
**Is your feature request related to a problem? Please describe.**

As far as I can tell, there is nowhere easily accessible to determine your build date. Additionally, where it is meant to display the major version number is cut off by the fixed width of the sidebar. 

![Screen Shot 2021-01-02 at 7 12 43 PM](https://user-images.githubusercontent.com/33612110/103469107-85968280-4d2e-11eb-8768-211b9b438e69.png)

**Describe the solution you'd like**
Display the build version or build date being run in the control panel.

**Describe alternatives you've considered**
Manually verifying whether any new dev docker images exist.

**Additional context**

**Comment by robertsLando** [comment]
@blhoward2 It's there but since it also has `apha.X` the text is too long now. Would you like a tooltip?

**Comment by blhoward2** [comment]
Perhaps. I just think it would be easier for testing to ask people what version they’re running...

**Comment by robertsLando** [comment]
@blhoward2 PR ready: https://github.com/zwave-js/zwavejs2mqtt/compare/uiVersion?expand=1

**Comment by blhoward2** [comment]
Thanks! The speed with which you and @AlCalzone approach these changes is impressive. Thanks for your hard work.

**Comment by robertsLando** [comment]
Just tring to make things better :) thanks to user issues
