### ISSUE TITLE
[question] Can I use port 80 for the control panel instead of 8091?

### ISSUE THREAD

**Issue by sofakng** [zwave-js/zwavejs2mqtt#1341]
Can I configure zwavejs2mqtt to use port 80 instead of 8091?

I'm using zwavejs2mqtt with docker compose and macvlan networking so it has a dedicated ip address (and it's easier to navigate to http://192.168.1.10 instead of http://192.168.1.10:8091)

**Comment by kpine** [comment]
Use PORT environment variable. See docs: https://zwave-js.github.io/zwavejs2mqtt/#/guide/env-vars

**Comment by sofakng** [comment]
Sorry, I see that now.  I should have checked first.
