### ISSUE TITLE
[bug] Node.js 15 is unsupported, migrate to next version? (Docker)

### ISSUE THREAD

**Issue by kpine** [zwave-js/zwavejs2mqtt#1342]
### Version

**Checklist:**

- [X] I am **not** using HomeAssistant. **Or:** a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is **not** described there.
- [X] I have read the changelog problem was **not** mentioned there.

Build/Run method

- [X] Docker
- [ ] PKG
- [ ] Snap package
- [ ] Manually built (git clone - yarn install - yarn run build )

zwavejs2mqtt version: 5.0.1
zwave-js version: 7.7.3

### Describe the bug

The official docker release uses Node.js 15.11.0. Node.js 15 became [unsupported](https://nodejs.org/en/about/releases/) as of June 1, 2021. Would it make sense to begin migrating to 16?

Another thing I've noticed is that `Dockerfile.contrib` use the image `node:erbium-buster`, AKA Node.js 12. Would it also make sense to match this version to the same one as the official image, e.g. `node:16.3.0-alpine` and `node:16.3.0-buster`?

**Comment by robertsLando** [comment]
I didn't updated the image because Dependabot PR was failing: https://github.com/zwave-js/zwavejs2mqtt/pull/1305

Will see if I can make it working today

**Comment by kpine** [comment]
@robertsLando Do you have any details on [what isn't working](https://github.com/zwave-js/zwavejs2mqtt/pull/1353) with the node:16.3.0-alpine image? I built a container using commit e86a24a719202822bfc4c74e7d027558ac2bad01 and everything is working fine so far. I run it on a RPI4 with debian aarch64. I'm wondering if there's some problem I'm not noticing.

**Comment by robertsLando** [comment]
The problem is with armv7, don't know the root cause of but it's related to node 16.3.0 alpine-3.13

**Comment by kpine** [comment]
Do you have any links you could point me to? Like I said, I am using that build with 16.3.0 alpine-3.13, and an RPi4 which is armv7.

**Comment by robertsLando** [comment]
I don't have any link, I just had this report from a user on slack and after some investigation It turns out that the problem was related to that specific image, even a simply docker run of node:16.3.0-alpine3.13 got the same error.

Here a link to the comment on slack: https://zwave-js.slack.com/archives/C01DQ24SDKL/p1623921735113100

**Comment by kpine** [comment]
Thanks. From that I could find a lot of issues related to this, one of them being https://github.com/nodejs/docker-node/issues/1477

What's odd is my system has libseccomp2 version 2.3.3-4, which is supposed to be broken, yet it's working fine. 🤷

**Comment by robertsLando** [comment]
Yeah really weird error 😕
