### ISSUE TITLE
[bug] HA discovery for FGR223 not working

### ISSUE THREAD

**Issue by darootler** [zwave-js/zwavejs2mqtt#1343]
### Version

Build/Run method

- [X] Docker
- [ ] PKG
- [ ] Snap package
- [ ] Manually built (git clone - yarn install - yarn run build )

zwavejs2mqtt version: 5.0.2
zwave-js version: 7.7.4

### Describe the bug

As already mentioned [here ](https://github.com/zwave-js/zwavejs2mqtt/issues/830) the covers do not update the state to "closed" or "open".

Here is the original payload:

```
{
  "state_topic": "zwave/Buro/Buro_Jalousie/38/1/currentValue",
  "command_topic": "zwave/Buro/Buro_Jalousie/38/1/targetValue/set",
  "position_topic": "zwave/Buro/Buro_Jalousie/38/1/currentValue",
  "set_position_topic": "zwave/Buro/Buro_Jalousie/38/1/targetValue/set",
  "position_template": "{{ value_json.value | round(0) }}",
  "position_open": 99,
  "position_closed": 0,
  "payload_open": 99,
  "payload_close": 0,
  "device": {
    "identifiers": [
      "zwavejs2mqtt_0xd563c48f_node2"
    ],
    "manufacturer": "Fibargroup",
    "model": "Roller Shutter 3 (FGR223)",
    "name": "Buro-Buro Jalousie",
    "sw_version": "5.1"
  },
  "name": "Buro-Buro Jalousie_position_1",
  "unique_id": "zwavejs2mqtt_0xd563c48f_2-38-1-currentValue"
}
```

If i remove "state_topic" and store the cover the status is updated correctly:

```
{
  "command_topic": "zwave/Buro/Buro_Jalousie/38/1/targetValue/set",
  "position_topic": "zwave/Buro/Buro_Jalousie/38/1/currentValue",
  "set_position_topic": "zwave/Buro/Buro_Jalousie/38/1/targetValue/set",
  "position_template": "{{ value_json.value | round(0) }}",
  "position_open": 99,
  "position_closed": 0,
  "payload_open": 99,
  "payload_close": 0,
  "device": {
    "identifiers": [
      "zwavejs2mqtt_0xd563c48f_node2"
    ],
    "manufacturer": "Fibargroup",
    "model": "Roller Shutter 3 (FGR223)",
    "name": "Buro-Buro Jalousie",
    "sw_version": "5.1"
  },
  "name": "Buro-Buro Jalousie_position_1",
  "unique_id": "zwavejs2mqtt_0xd563c48f_2-38-1-currentValue"
}
```

### To Reproduce

1. Pair a FGR223 roller shutter with Z-Wave JS
2. Use autodiscover with HA
3. Open and shut the cover and check the status

### Expected behavior

States are reported correctly as "closed" and "open"

### Additional context

In this [post](https://github.com/zwave-js/zwavejs2mqtt/issues/1327#issuecomment-859728676) someone posted the discovery information and there is no "state_topic". He is using a FGR222 and i am using a FGR223, in my discovery topic there is still a "state_topic".

**Comment by robertsLando** [comment]
so the solution would be to remove the state topic from discovery payload, right?

**Comment by darootler** [comment]
In my opinion yes, state_topic should be removed.

Regards
Richard

**Comment by bushvin** [comment]
@darootler what version of HA do you use?
I currenlty have 2021.6.3 and it works.

This is the JSON device in the Home assistant section of my device:
```json
{
  "type": "cover",
  "object_id": "position",
  "values": [
    "38-0-currentValue",
    "38-0-targetValue"
  ],
  "discovery_payload": {
    "command_topic": "zwave/fibaro_fgr222_00/38/0/targetValue/set",
    "position_topic": "zwave/fibaro_fgr222_00/38/0/currentValue",
    "set_position_topic": "zwave/fibaro_fgr222_00/38/0/targetValue/set",
    "position_template": "{{ (value_json.value / 99 * 100) | round(0) }}",
    "position_open": 99,
    "position_closed": 0,
    "payload_open": "99",
    "payload_close": "0",
    "device": {
      "identifiers": [
        "zwavejs2mqtt_0xc883eb3e_node18"
      ],
      "manufacturer": "Fibargroup",
      "model": "Roller Shutter 2 (FGR222)",
      "name": "fibaro_fgr222_00",
      "sw_version": "25.25"
    },
    "name": "fibaro_fgr222_00_position",
    "unique_id": "zwavejs2mqtt_0xc883eb3e_Node18_position"
  },
  "discoveryTopic": "cover/fibaro_fgr222_00/position/config",
  "persistent": false,
  "ignoreDiscovery": false,
  "id": "cover_position"
}
```
as you can see, I have no `state_topic` key.

**Comment by darootler** [comment]
I am using HA 2021.6.4, but this problem exists since at least 2021.3 ([see post here](https://github.com/zwave-js/zwavejs2mqtt/issues/830#issuecomment-800057865)).

Exactly, the difference is that you do not have a state_topic in your payload, besides the HA version (i don't think thats the problem) the only difference is that you are using a FGR222 and i am using a FGR223. The question is why do i have a state_topic in the payload and you don't?

Regards
Richard

**Comment by darootler** [comment]
To clarify:

I am able to control the covers without any issues, the only problem is that the state is not updated correctly if state_topic is in the payload.

Regards
Richard

**Comment by bushvin** [comment]
I only got the issue when migrating to 2021.6.3, and I came from 2021.6.1, I believe.

What I did do was clean up my entire mqtt stack as I thought the issue was on my end.
so with mosquitto and ha stopped, I removed the mosquitto db and cleaned up any reference to the device in `core.device_registry`, `core.entity_registry` and `core.restore_state` in `config/.storage`

I'm not sure if this will help, but tha's my history

**Comment by bushvin** [comment]
Just updated to 2021.6.4, and I do not see any python error messages complaining about `state_topic`

**Comment by darootler** [comment]
Z-Wave JS gives you the possibilty to rediscover the node and as far as i understand the whole topic will be recalculated:

![image](https://user-images.githubusercontent.com/11849583/122037359-c95ce000-cdd4-11eb-9224-44d3807cece5.png)

Here is my manual corrected topic:

![image](https://user-images.githubusercontent.com/11849583/122037577-fdd09c00-cdd4-11eb-9fed-9e04bce25523.png)
![image](https://user-images.githubusercontent.com/11849583/122037856-4ab47280-cdd5-11eb-81b9-6ea97fe34b72.png)

And here is the topic after i rediscover the topic:

![image](https://user-images.githubusercontent.com/11849583/122037982-6b7cc800-cdd5-11eb-98c8-d5cc39226938.png)
![image](https://user-images.githubusercontent.com/11849583/122038289-bb5b8f00-cdd5-11eb-93d9-8931e5af19f5.png)

In my opinion the "state_topic" comes from the Z-Wave JS side and has nothing to do with HA. Correct me if i am wrong.

Regards
Richard

**Comment by bushvin** [comment]
@robertsLando I think, I may have found the source, but I don't have enough knowledge on this to be certain.
`hass/configurations.ts`:
```
...
120         cover_position: {
121                 type: 'cover',
122                 object_id: 'position',
123                 discovery_payload: {
124                         state_topic: true,
125                         command_topic: true,
126                         position_topic: true,
127                         set_position_topic: true,
128                         position_template: '{{ value_json.value | round(0) }}',
129                         position_open: 99,
130                         position_closed: 0,
131                         payload_open: '99',
132                         payload_close: '0',
133                 },
134         },
...
```
Does line 124 imply a `state_topic` needs to be provided? If I'm not mistaken, it should be disabled when using `position_template` and not `value_template`

**Comment by robertsLando** [comment]
Sorry for the delay, PR ready

**Comment by darootler** [comment]
@robertsLando 

Thank you, i'll report back if everthing works as expected.

Regards
Richard

**Comment by darootler** [comment]
Discovery payload is now without "state_topic" and the FGR223 covers are working as expected.

Thank you!

Regards
Richard
