### ISSUE TITLE
Troubleshooting: MQTT message recieved but no Z-Wave command sent.

### ISSUE THREAD

**Issue by Lopton** [zwave-js/zwavejs2mqtt#135]
I'm looking for any advice on how to provide meaningful data for a problem I'm having with a multiswitch relay (1 device 3 binary switches) where I see Zwavejs2mqtt get a mqtt message but then does not do anything (ie. does not send a zwave command). This is the log message
`2021-01-03 01:57:31.663 INFO MQTT: Message received on zwaveJs2Mqtt/Backyard/24/37/3/targetValue/set`
I can get the switch to operate from the Zwavejs2mqtt control panel, but it just ignores MQTT messages

If do another switch that does work I see these two messages.
```
2021-01-03 01:58:31.523 INFO MQTT: Message received on zwaveJs2Mqtt/Office/13/37/0/targetValue/set
2021-01-03 01:58:31.524 INFO ZWAVE: Writing true to 37-0-targetValue
```

But I don't seem to have any thing else to provide or information on how to troubleshoot further.

**Comment by Lopton** [comment]
I looked at the MQTT messages and don't see much difference, could it be that the switch I'm working with has multiple endpoints?

MQTT for currentValue for switch that doesn't work:
`{"id":"24-37-3-currentValue","nodeId":24,"commandClass":37,"commandClassName":"Binary Switch","endpoint":3,"property":"currentValue","propertyName":"currentValue","type":"boolean","readable":true,"writeable":false,"label":"Current value","list":false,"value":true,"isCurrentValue":true,"targetValue":"37-3-targetValue","lastUpdate":1609639465023}
MQTT for currentValue for switch that does work:
``{"id":"13-37-0-currentValue","nodeId":13,"commandClass":37,"commandClassName":"Binary Switch","endpoint":0,"property":"currentValue","propertyName":"currentValue","type":"boolean","readable":true,"writeable":false,"label":"Current value","list":false,"value":true,"isCurrentValue":true,"targetValue":"37-0-targetValue","lastUpdate":1609639361580}`

**Comment by Lopton** [comment]
Well, today it started working. Shrug. I'll close this issue.

**Comment by stefanhaustein** [comment]
FTR: I had the same problem today for all my qubino devices. A restart "fixed" it.
