### ISSUE TITLE
[HASS]

### ISSUE THREAD

**Issue by p4p3r** [zwave-js/zwavejs2mqtt#1352]
### Version

Using the HA official add-on.

addon-zwavejs2mqtt version: 0.19.1
zwavejs2mqtt version: 5.0.2
zwavejs version: 7.7.4

### Describe the bug

I'm using Zwavejs2mqtt but without MQTT and instead using directly the websocket integration between zwavejs and homeassistant.

The stop control on my Aeotec Nanoshutters (ZW141) in HA doesn't work. All other controls seems to be working fine (up/down, position and state are reported correctly).
I initially reported the problem directly to homeassistant-core, but I was instructed to report it upstream. I don't know if this belongs here or should go directly to node-zwave-js.

The node seem to be discovered properly. In zwave2mqtt's UI I have two entities that allows me to open/close the cover and stop the up/down movement:
* [3-38-0-On] Perform a level change (On)
* [3-38-0-Off] Perform a level change (Off)

<img width="1198" alt="multilevel_switch" src="https://user-images.githubusercontent.com/20265881/122372416-f0e0b380-cf60-11eb-9a97-6db78b850f09.png">

In the past I solved a similar issue with a custom MQTT cover template in HA [](https://github.com/OpenZWave/Zwave2Mqtt/issues/329#issuecomment-707638886) but it really seems to me like something that should be supported out-of-the-box.

Something I noticed is that the homeassistant UI seems to be "unresponsive" while the cover is executing a command (i.e. open, close or move to position) and for a short while after. For example, if I move the cover to a certain position, I cannot move it again for a few seconds after the cover has moved to the position.

### Logs and node dump
These are the logs I captured when opening the cover, then trying to stop three times, closing the cover and trying to stop again three times.
In the archive there's also the json dump of the node I was operating (there are move aeotec covers in the network).
[node_and_logs.zip](https://github.com/zwave-js/zwavejs2mqtt/files/6669066/node_and_logs.zip)

**Comment by robertsLando** [comment]
@p4p3r I don't get where is the error here, I mean I don't understand if the stop works from z2m or not

**Comment by p4p3r** [comment]
If I use the two on/off switches in the screenshot above it works fine: 3-38-0-On open (and stop opening) the cover, 3-38-0-Off closes (and stop closing) the cover.

**Comment by robertsLando** [comment]
Ok so the issue is for sure with hass integration, everything works on z2m side :)
