### ISSUE TITLE
[bug] Node number isn't reused after node was removed

### ISSUE THREAD

**Issue by guillaumebignon** [zwave-js/zwavejs2mqtt#1355]
### Version

**Checklist:**

- [x] I am **not** using HomeAssistant. **Or:** a developer has told me to come here.
- [x] I have checked the troubleshooting section and my problem is **not** described there.
- [x] I have read the changelog problem was **not** mentioned there.

Build/Run method

- [x] Docker
- [ ] PKG
- [ ] Snap package
- [ ] Manually built (git clone - yarn install - yarn run build )

zwavejs2mqtt: 5.0.4
zwave-js: 7.7.5

### Describe the bug

Deleteted nodes numbers are not reusable after failed node replace.

### To Reproduce

I tried to replace my node 6 but the inclusion failed (i didn't start the inclusion mode on my device fast enougth).
Since the node 6 doesn't apear in my node list and when i add the node I want to use in replacement, it increments its node number after the last one.

### Expected behavior

The node 6 number should be reusable after it was deletet

**Comment by robertsLando** [comment]
This is by design, it's not an error on z2m side. If you want to replace a node you should use replace failed node instead

**Comment by guillaumebignon** [comment]
Thank's for the quick answer

How can i replace a failed node that doesn't show in my control panel anymore ?

**Comment by robertsLando** [comment]
If you have already removed it you cannot replace it. AFAIK there is no way to replace a removed node as it is not marked as 'failed' in the controller. @AlCalzone

**Comment by AlCalzone** [comment]
Correct. Replacing a failed node just means removing the old one and including a new one under the same ID. When inclusion then fails, the ID is gone and there's nothing we can do about it, since that part is handled by the stick.

**Comment by guillaumebignon** [comment]
Ok, thank you for your answers.

I found an ugly way to do it: i used an old docker image of zwave2mqtt (not the JS version) witch had an option to show hidden nodes, so I was able to do the replace procedure again.

Wouldn't be possible to include a similar feature in zwave2mqtt JS ?

**Comment by AlCalzone** [comment]
I've talked about this in the path with someone who knows the Z-Wave internals much better than I do.
It is not a good idea to "replace" nodes that are not known to the controller. It might have worked for you but worst case it messes up your controller's memory.

**Comment by guillaumebignon** [comment]
Ok, thanks again for your answers, I think we can close this issue.

**Comment by cbho** [comment]
BTW:
The node number isn't lost forever - when you add new devices (or add and remove devices) for long enough, you'll eventually reach node no. 255.
When adding the next device, it will get the lowest available number that is not in use anymore - untill of course you reach 255 working z-wave devices - then your a-wave network is full.

**Comment by AlCalzone** [comment]
232, not 255. But the gist is correct.

**Comment by guillaumebignon** [comment]
Ok, that's good to know !
Tu doesn't solve my problem when I try to replace a node and the paring fails but I undurstand there is reasons to forbid this.

(I will not explain the dirty way I found to replace a deleted node, but I was able to do it. I undurstand it may cause problems on my network, I'll keep watching!)
