### ISSUE TITLE
[bug] COMMAND_CLASS_BARRIER_OPERATOR not showing for Aeotec Garage Door Controller

### ISSUE THREAD

**Issue by awulf** [zwave-js/zwavejs2mqtt#136]
Hi, not sure if this is a bug, help, or feature request issue. But the barrier operator function seems to be missing from the device control panel. 
I'm just looking to migrate from using Home Assistant OZW to this, if I can get the garage door barrier working it looks like it be the way to go, as all the other devices seem to be working fine, and much more responsive than in Home Assistant.

Browsing through source code it seems there's meant to be barrier support, but not sure where it's going wrong.

The exported node file from the control panel:
[node_8.json.zip](https://github.com/zwave-js/zwavejs2mqtt/files/5761288/node_8.json.zip)

The configuration file exists: https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/devices/0x0086/zw062.json

https://aeotec.freshdesk.com/support/solutions/articles/6000168304-garage-door-controller-technical-specifications-

![Screen Shot 2021-01-03 at 5 15 06 pm](https://user-images.githubusercontent.com/186606/103473335-46783800-4de7-11eb-85d2-5c61c200768c.png)

Running in Docker,
zwavejs2mqtt version: 1.0.0-alpha.2

**Comment by billiaz** [comment]
@awulf this is not supported yet by the driver https://github.com/zwave-js/node-zwave-js/issues/6

I believe @AlCalzone looks for contributors to implement classes, also made a nice documentation (how to) https://zwave-js.github.io/node-zwave-js/#/development/implementing-cc

**Comment by awulf** [comment]
Thanks that would explain it, so nothing to be done in this project for now. I might take a stab and try to implement that command class.

**Comment by billiaz** [comment]
> Thanks that would explain it, so nothing to be done in this project for now. I might take a stab and try to implement that command class.

I am also looking to implement some of these! I am really happy to work together and learn this implementation process. I've been busy with some Hass details so took me a bit time to focus on implementing CC

Disclaimer: I am not the author of node-zwave-js nor zwavejs2mqtt! just helping out, as Much as I can

**Comment by billiaz** [comment]
Work is in progress. Draft PR: https://github.com/zwave-js/node-zwave-js/pull/1337

**Comment by billiaz** [comment]
@awulf PR is ready for test drive thanks to @AlCalzone for finalizing it!
Want help to test drive this pr?

**Comment by awulf** [comment]
@billiaz I'd like to help to test, but I'm not sure how? I modified the `Dockerfile` for `zwavejs2mqtt` to use the branch `cc/barrier-operator`, built the image and have it running (all done on my Synology NAS). But not seeing any barrier operations.

I've attached the node json file just incase it's of any use.
[node_8.json.txt](https://github.com/zwave-js/zwavejs2mqtt/files/5925500/node_8.json.txt)

Couple weeks ago I tried spending a few hours setting up a development environment on my Mac running macOS 11.2 but been getting a bunch of errors I couldn't figure out.

**Comment by awulf** [comment]
Saw that 6.2.0 has it in it now, built a new docker container and it works under zwavejs2mqtt for my garage door controller

**Comment by billiaz** [comment]
once you ahve this, can you export the node from zj2m. Then i can make the HASS payload and test it!
we will manually add it here, once is working as expected. I will make a Zj2m patch

**Comment by awulf** [comment]
Have attached the node copied from zwavejs2mqtt. It might already be working, haven't had the time to experiment with home assistant. 
[barrier_node.json.txt](https://github.com/zwave-js/zwavejs2mqtt/files/5962144/barrier_node.json.txt)

**Comment by robertsLando** [comment]
@billiaz I think barrier operator state could be treated like notifications in discovery
