### ISSUE TITLE
Issues with NGD00Z-4 Cover populating in Home assistant

### ISSUE THREAD

**Issue by crazypyro136** [zwave-js/zwavejs2mqtt#1363]
zwavejs2mqtt: 5.0.4
zwave-js: 7.7.5

HA:  core-2021.6.5

Recently My garage doors are no longer showing the options for opening and closing. It seems like the cover status is not working correctly anymore between Home assistant and zwavejs2mqtt. The options are showing and work in the zwavejs2mqtt control panel.
[Node Info.txt](https://github.com/zwave-js/zwavejs2mqtt/files/6688134/Node.Info.txt)
![Garage door 1](https://user-images.githubusercontent.com/26356098/122795923-6f9c6000-d283-11eb-9849-b3df75a15c4f.PNG)
![Garage door 2](https://user-images.githubusercontent.com/26356098/122795924-7034f680-d283-11eb-935a-137bae560da4.PNG)

**Comment by robertsLando** [comment]
I know there have been changes with hass covers in latest version, are you using latest hass version?

**Comment by crazypyro136** [comment]
Both HASS and zwavejas2mqtt are updated to the latest, I think it was the recent update that killed it

**Comment by crazypyro136** [comment]
I am getting the following in the logs. It sounds like zigbee2mqtt had to update covers, is there something I can do to fix this

Exception in async_discover when dispatching 'mqtt_discovery_new_cover_mqtt': ({'command_topic': 'zwave/Small_garage_door/102/0/targetState/set', 'state_topic': 'zwave/Small_garage_door/102/0/currentState', 'position_template': '{{ value_json.value }}', 'device_class': 'garage', 'payload_open': 255, 'payload_close': 0, 'payload_stop': 253, 'state_open': 255, 'state_opening': 254, 'state_closed': 0, 'state_closing': 252, 'device': {'identifiers': ['zwavejs2mqtt_0xdb1d31ed_node45'], 'manufacturer': 'Nortek Security & Control LLC', 'model': 'Garage Door Controller (NGD00Z-4)', 'name': 'Small_garage_door', 'sw_version': '2.1'}, 'name': 'Small_garage_door_barrier_state', 'unique_id': 'zwavejs2mqtt_0xdb1d31ed_45-102-0-currentState', 'platform': 'mqtt'},) Traceback (most recent call last): File "/usr/local/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 272, in __call__ return self._compiled([], data) File "/usr/local/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 817, in validate_callable return schema(data) File "/usr/src/homeassistant/homeassistant/components/mqtt/cover.py", line 130, in validate_options raise vol.Invalid( voluptuous.error.Invalid: 'position_template' must be set together with 'position_topic'. During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/mqtt/mixins.py", line 179, in async_discover config = schema(discovery_payload) File "/usr/local/lib/python3.9/site-packages/voluptuous/validators.py", line 218, in __call__ return self._exec((Schema(val) for val in self.validators), v) File "/usr/local/lib/python3.9/site-packages/voluptuous/validators.py", line 341, in _exec raise e if self.msg is None else AllInvalid(self.msg, path=path) File "/usr/local/lib/python3.9/site-packages/voluptuous/validators.py", line 337, in _exec v = func(v) File "/usr/local/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 276, in __call__ raise er.MultipleInvalid([e]) voluptuous.error.MultipleInvalid: 'position_template' must be set together with 'position_topic'.

**Comment by crazypyro136** [comment]
Current zwave Version:
zwavejs2mqtt: 5.4.0
zwave-js: 8.0.3
home id: 3676123629
home hex: 0xdb1d31ed


Current home assistant:
Version | core-2021.7.3

**Comment by robertsLando** [comment]
Is this related to https://github.com/zwave-js/zwavejs2mqtt/issues/1348 ?

**Comment by crazypyro136** [comment]
It looks like it is. Is there anything that I could test or logs that would help do you think?

**Comment by robertsLando** [comment]
The question is, that issue should have fixed the covers for latest hass version, so are you using latest hass version?

**Comment by thd6n75** [comment]
This issue affects me too.  Using the latest docker images:

homeassistant/home-assistant:2021.7

zwavejs/zwavejs2mqtt:5.4.2


This error is in homeassistant logs when rediscovering the node in zwavejs2mqtt:

```
2021-07-27 20:50:26 ERROR (MainThread) [homeassistant.util.logging] Exception in async_discover when dispatching 'mqtt_discovery_new_cover_mqtt': ({'command_topic': 'zwavejs2mqtt/garage_door_cover/102/0/targetState/set', 'state_topic': 'zwavejs2mqtt/garage_door_cover/102/0/currentState', 'position_template': '{{ value_json.value }}', 'device_class': 'garage', 'payload_open': 255, 'payload_close': 0, 'payload_stop': 253, 'state_open': 255, 'state_opening': 254, 'state_closed': 0, 'state_closing': 252, 'device': {'identifiers': ['zwavejs2mqtt_0xe24c5f98_node66'], 'manufacturer': 'Nortek Security & Control LLC', 'model': 'Garage Door Controller (NGD00Z-4)', 'name': 'garage_door_cover', 'sw_version': '1.0'}, 'name': 'garage_door_cover_barrier_state', 'unique_id': 'zwavejs2mqtt_0xe24c5f98_66-102-0-currentState', 'platform': 'mqtt'},)
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 817, in validate_callable
    return schema(data)
  File "/usr/src/homeassistant/homeassistant/components/mqtt/cover.py", line 130, in validate_options
    raise vol.Invalid(
voluptuous.error.Invalid: 'position_template' must be set together with 'position_topic'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/mqtt/mixins.py", line 179, in async_discover
    config = schema(discovery_payload)
  File "/usr/local/lib/python3.9/site-packages/voluptuous/validators.py", line 218, in __call__
    return self._exec((Schema(val) for val in self.validators), v)
  File "/usr/local/lib/python3.9/site-packages/voluptuous/validators.py", line 341, in _exec
    raise e if self.msg is None else AllInvalid(self.msg, path=path)
  File "/usr/local/lib/python3.9/site-packages/voluptuous/validators.py", line 337, in _exec
    v = func(v)
  File "/usr/local/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 276, in __call__
    raise er.MultipleInvalid([e])
voluptuous.error.MultipleInvalid: 'position_template' must be set together with 'position_topic'.
```

Here's the JSON that gets published to MQTT during discovery:

```
{
  "command_topic": "zwavejs2mqtt/garage_door_cover/102/0/targetState/set",
  "state_topic": "zwavejs2mqtt/garage_door_cover/102/0/currentState",
  "position_template": "{{ value_json.value }}",
  "device_class": "garage",
  "payload_open": 255,
  "payload_close": 0,
  "payload_stop": 253,
  "state_open": 255,
  "state_opening": 254,
  "state_closed": 0,
  "state_closing": 252,
  "device": {
    "identifiers": [
      "zwavejs2mqtt_0xe24c5f98_node66"
    ],
    "manufacturer": "Nortek Security & Control LLC",
    "model": "Garage Door Controller (NGD00Z-4)",
    "name": "garage_door_cover",
    "sw_version": "1.0"
  },
  "name": "garage_door_cover_barrier_state",
  "unique_id": "zwavejs2mqtt_0xe24c5f98_66-102-0-currentState"
}
```

There's no `position_topic` key in what zwavejs2mqtt is publishing.

**Comment by robertsLando** [comment]
Found the problem, PR ready

**Comment by crazypyro136** [comment]
Thanks for the help on this. Much appreciated. I am getting the entity now in Home Assistant after I updated, but now its giving me an error saying:

Payload is not supported (e.g. open, closed, opening, closing, stopped): {"time":1627680942354,"value":255}
Payload is not supported (e.g. open, closed, opening, closing, stopped): {"time":1627680990007,"value":0}

![image](https://user-images.githubusercontent.com/26356098/127714204-600ce50e-1125-4574-a6f4-ea0fd701e220.png)

**Comment by thd6n75** [comment]
Thanks @robertsLando - bought you some coffees :)  Cheers.

**Comment by robertsLando** [comment]
Thanks for the ☕ @thd6n75 ! :) BTW The latest release is already available on docker, just pull latest.

@crazypyro136 I think I need to also change `state_open` with `position_open` same for close. Could you try to manually change that on the discoveryu payload from the ui to check if it's working?

**Comment by robertsLando** [comment]
Check: https://www.home-assistant.io/integrations/cover.mqtt/

I think the discovery paylaod sent is missing something, maybe: 

```
position_closed: 0,
position_open: 255,
```

**Comment by crazypyro136** [comment]
Sorry had a baby 3 nights ago and have not had a chance to check\test yet

**Comment by thd6n75** [comment]
Pulled the :latest docker image.  zwavejs2mqtt is now publishing the following to topic `homeassistant/cover/garage_door_cover/barrier_state/config` during discovery:

```
{
  "position_topic": "zwavejs2mqtt/garage_door_cover/102/0/currentState",
  "state_topic": "zwavejs2mqtt/garage_door_cover/102/0/currentState",
  "position_template": "{{ value_json.value }}",
  "device_class": "garage",
  "payload_open": 255,
  "payload_close": 0,
  "payload_stop": 253,
  "state_open": 255,
  "state_opening": 254,
  "state_closed": 0,
  "state_closing": 252,
  "device": {
    "identifiers": [
      "zwavejs2mqtt_0xe24c5f98_node66"
    ],
    "manufacturer": "Nortek Security & Control LLC",
    "model": "Garage Door Controller (NGD00Z-4)",
    "name": "garage_door_cover",
    "sw_version": "1.0"
  },
  "name": "garage_door_cover_barrier_state",
  "unique_id": "zwavejs2mqtt_0xe24c5f98_66-102-0-currentState"
}
```


Here's what I tried to publish to MQTT manually.  Changed state_open to position_open, and state_closed to position_closed

```
{
  "position_topic": "zwavejs2mqtt/garage_door_cover/102/0/currentState",
  "state_topic": "zwavejs2mqtt/garage_door_cover/102/0/currentState",
  "position_template": "{{ value_json.value }}",
  "device_class": "garage",
  "payload_open": 255,
  "payload_close": 0,
  "payload_stop": 253,
  "position_open": 255,
  "state_opening": 254,
  "position_closed": 0,
  "state_closing": 252,
  "device": {
    "identifiers": [
      "zwavejs2mqtt_0xe24c5f98_node66"
    ],
    "manufacturer": "Nortek Security & Control LLC",
    "model": "Garage Door Controller (NGD00Z-4)",
    "name": "garage_door_cover",
    "sw_version": "1.0"
  },
  "name": "garage_door_cover_barrier_state",
  "unique_id": "zwavejs2mqtt_0xe24c5f98_66-102-0-currentState"
}
```


Nothing happens.  I see the cover entity in HA (`cover.garage_door_cover_barrier_state`) but there aren't any buttons to open or close the door.



For reference, here's a zigbee cover (an Ikea shade) from koenkk/zigbee2mqtt:1.20.0 that works well.  topic `homeassistant/cover/0xd0cf5efffeef51d2/cover/config`:

```
{
  "availability": [
    {
      "topic": "zigbee2mqtt/bridge/state"
    }
  ],
  "command_topic": "zigbee2mqtt/living_room_shade_l/set",
  "device": {
    "identifiers": [
      "zigbee2mqtt_0xd0cf5efffeef51d2"
    ],
    "manufacturer": "IKEA",
    "model": "FYRTUR roller blind (E1757)",
    "name": "living_room_shade_l",
    "sw_version": "Zigbee2MQTT 1.20.0"
  },
  "json_attributes_topic": "zigbee2mqtt/living_room_shade_l",
  "name": "living_room_shade_l",
  "position_template": "{{ value_json.position }}",
  "position_topic": "zigbee2mqtt/living_room_shade_l",
  "set_position_template": "{ \"position\": {{ position }} }",
  "set_position_topic": "zigbee2mqtt/living_room_shade_l/set",
  "unique_id": "0xd0cf5efffeef51d2_cover_zigbee2mqtt"
}
```

**Comment by thd6n75** [comment]
I added the following, and immediately a button appears to raise/lower the cover in the UI:

```
"command_topic": "zwavejs2mqtt/garage_door_cover/foobar",
```

So I think that's one thing that's missing.

**Comment by robertsLando** [comment]
Ok that's an easy fix, thanks for your report!
