### ISSUE TITLE
[HASS] Template rendering warnings in Home Assistant logs for value_template

### ISSUE THREAD

**Issue by emichael** [zwave-js/zwavejs2mqtt#1365]
It looks like [this issue](https://github.com/Koenkk/zigbee2mqtt/issues/6987) affects zwavejs2mqtt, too. I'm getting lots of these warnings in my Home Assistant logs.

```
Logger: homeassistant.helpers.template
Source: helpers/template.py:1366
First occurred: 12:17:22 AM (21 occurrences)
Last logged: 12:15:38 PM

Template variable warning: 'dict object' has no attribute 'value' when rendering '{{ value_json.value}}'
```

I manually updated the `value_template` to `"{{ value_json.value | default(None, true) }}"` for my entities in zwavejs2mqtt and sent the config packets to Home Assistant. I'll update later if I still see error messages, but this should fix the issue.

### Version info
zwavejs2mqtt: 5.0.4
zwave-js: 7.7.5

Home Assistant is latest.

**Comment by emichael** [comment]
Update: it should be something like `default('')`. The second argument to default shouldn't be true, the reporter of that previous issue got it backwards.

**Comment by robertsLando** [comment]
Yeah this is a duplicate of #1020 . I think we should detect the affected values and add that default to the value template of just those values, not all

**Comment by emichael** [comment]
Gotcha, sorry about the dupe.

**Comment by robertsLando** [comment]
No wories, If you want to help there just tell me the affected valueIds :)
