### ISSUE TITLE
[bug] Can’t lock/unlock Schlage BE469 (via HASS Discovery)

### ISSUE THREAD

**Issue by bachya** [zwave-js/zwavejs2mqtt#137]
**Version**

Build/Run method
- [x] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build ) 

zwavejs2mqtt version: 1.0.0-alpha.2

**Describe the bug**
Connected to Home Assistant via HASS Discovery. When HASS loads, the lock shows an `unlocked` state no matter what. When I attempt to lock/unlock the lock, I get an error:

```
2021-01-03 07:06:01.353 INFO MQTT: Message received on zwavejs2mqtt/16/98/0/targetMode/set
2021-01-03 07:06:01.354 INFO ZWAVE: Writing LOCK to 98-0-targetMode
2021-01-03 07:06:01.355 INFO ZWAVE: Controller status: Driver: Door Lock: "targetMode" must be of type "number", received "string"
2021-01-03 07:06:01.356 ERROR ZWAVE: Unable to write LOCK on 98-0-targetMode
```

**Comment by billiaz** [comment]
I want to help fix this discovery
I suggest 
1. to export the node json and post it. I am interested to find out where it stucks.
2. enable log to file forl the driver and add silly as mode, then once everything is interviewed exeute the command and send us the driver output. until new version (6.0) is added, we will need to get these info from the `bin/zwave-<pid>.log` of your docker container. <pid> usuallys is 1

That for now :)

**Comment by bachya** [comment]
Thanks, @billiaz. Appreciate your help.

Nodes: https://gist.github.com/bachya/0954e9827cd4466a2f36110cc6cc9ac8

Log: https://gist.github.com/bachya/07d984a1f9dedf58bc3d1ca6cf002503

**Comment by billiaz** [comment]
i suspect something needs to be fixed on targetMode! we faced a similar in climate. 
Can you help me a bit with 

1. get an export of the node and not the whole list, as the whole list shows only highlevel info
![troubleshoot_export](https://user-images.githubusercontent.com/4048920/103523856-d5835f80-4e7c-11eb-9510-c8804c44bf54.png)


2. can you paste the   `zwavejs2mqtt/16/98/0/targetMode` payload on mqtt side?

**Comment by bachya** [comment]
@billiaz Here you go!

Schlage BE469 Node Info: https://gist.github.com/bachya/bfaa5a32776f00873ddf3353b5115eac

When I lock/unlock the lock, this is the only payload that appears under `zwavejs2mqtt/16/98/0/targetMode`:

```json
{"time":1609771434569}
```

**Comment by billiaz** [comment]
targetmode supports the following:
```
        {
          "text": "Unsecured",
          "value": 0
        },
        {
          "text": "UnsecuredWithTimeout",
          "value": 1
        },
        {
          "text": "InsideUnsecured",
          "value": 16
        },
        {
          "text": "InsideUnsecuredWithTimeout",
          "value": 17
        },
        {
          "text": "OutsideUnsecured",
          "value": 32
        },
        {
          "text": "OutsideUnsecuredWithTimeout",
          "value": 33
        },
        {
          "text": "Unknown",
          "value": 254
        },
        {
          "text": "Secured",
          "value": 255
        }
      ],
```

what value do you try to set? 

from the currentValue topic i can see ```      "value": 255,``` which reflects Secured
can you send a command to topic `zwavejs2mqtt/16/98/0/targetMode/set` and the text `plaintext` be `Unsecured`.
And tell me what happened

**Comment by bachya** [comment]
@billiaz The Home Assistant MQTT Discovery configuration for this node (`homeassistant/lock/nodeID_16/lock/config`) shows this:

```json
{
  "command_topic": "zwavejs2mqtt/16/98/0/targetMode/set",
  "state_locked": "true",
  "state_unlocked": "false",
  "value_template": "{% if value_json.value == false %} false {% elif value_json.value == true %} true {% else %} unknown {% endif %}",
  "state_topic": "zwavejs2mqtt/16/98/0/currentMode",
  "json_attributes_topic": "zwavejs2mqtt/16/98/0/currentMode",
  "device": {
    "identifiers": [
      "zwavejs2mqtt_0xc8341d86_node16"
    ],
    "manufacturer": "Allegion",
    "model": "Touchscreen Deadbolt (BE469)",
    "name": "nodeID_16",
    "sw_version": "113.22"
  },
  "name": "-nodeID_16_lock",
  "unique_id": "zwavejs2mqtt_0xc8341d86_16-98-0-currentMode"
}
```

When I attempt to lock the lock and look at the command topic (`zwavejs2mqtt/16/98/0/targetMode/set`), I see:

```
LOCK
```

So, to your point, that looks like the issue: we need to be sending an integer that corresponds to the lock state. I will test shortly and follow up!

**Comment by robertsLando** [comment]
@billiaz can we customize the template to make it send a number instead of lock and unlock? otherwise we need to parse the value on gateway side, if the value has states look for states text matching and take the state text value as valid value

**Comment by bachya** [comment]
Okay, additional follow-up. Here are the results of my tests (posting various raw payloads to `zwavejs2mqtt/16/98/0/targetMode/set`):

* `0`: unlocked the door (but no update of the `lock` entity's state in Home Assistant)
* `255`: locked the door (but no update of the `lock` entity's state in Home Assistant)
* `Unsecured`: no change (and the same Docker console log: `"targetMode" must be of type "number", received "string"`)
* `Secured`: no change (and the same Docker console log: `"targetMode" must be of type "number", received "string"`)

So, preliminarily, I think two things need to happen with Discovery:

1. `zwavejs2mqtt/16/98/0/targetMode/set` needs to receive integers, not strings
2. The `value_template` needs to be changed to reflect those integers – perhaps something like:

```jinja
"{% if value_json.value == 0 %} false {% elif value_json.value == 255 %} true {% else %} unknown {% endif %}"
```

(Although, that template should probably be made more robust to include the other integer code possibilities listed above, but I'll leave that to someone wiser than I. 😉)

**Comment by billiaz** [comment]
> Okay, additional follow-up. Here are the results of my tests (posting various raw payloads to `zwavejs2mqtt/16/98/0/targetMode/set`):
> 
> * `0`: unlocked the door (but no update of the `lock` entity's state in Home Assistant)
> * `255`: locked the door (but no update of the `lock` entity's state in Home Assistant)
> * `Unsecured`: no change (and the same Docker console log: `"targetMode" must be of type "number", received "string"`)
> * `Secured`: no change (and the same Docker console log: `"targetMode" must be of type "number", received "string"`)
> 
> I think the Home Assistant entity not updating is related to the `value_template` looking for boolean values.
> 
> So, preliminarily, I think two things need to happen with Discovery:
> 
> 1. `zwavejs2mqtt/16/98/0/targetMode/set` needs to receive integers, not strings
> 2. The `value_template` needs to be changed to reflect those integers – perhaps something like:
> 
> ```
> {% if value_json.value == 0 %} false {% elif value_json.value == 255 %} true {% else %} unknown {% endif %}
> ```
> 
> (Although, that template should probably be made more robust to include the other integer code possibilities listed above [assuming they are useful across various lock types], but I'll leave that to someone wiser than I. 😉)

you do not this complexity if you only use the 255 and 0

reading this https://www.home-assistant.io/integrations/lock.mqtt/ should be easy to patch payloads for lock. i need a bit of time and setup this.

**Comment by bachya** [comment]
@billiaz Great! Let me know how I can support you: I'm a core Home Assistant member and obviously have this lock, so I'm at your disposal.

**Comment by billiaz** [comment]
@bachya 
```
{
  "command_topic": "zwavejs2mqtt/16/98/0/targetMode/set",
  "state_locked": 255,
  "state_unlocked": 0,
  "payload_lock": 255,
  "payload_unlock": 0,
  "value_template": "{{ if value_json.value }}",
  "state_topic": "zwavejs2mqtt/16/98/0/currentMode",
  "json_attributes_topic": "zwavejs2mqtt/16/98/0/currentMode",
  "device": {
    "identifiers": [
      "zwavejs2mqtt_0xc8341d86_node16"
    ],
    "manufacturer": "Allegion",
    "model": "Touchscreen Deadbolt (BE469)",
    "name": "nodeID_16",
    "sw_version": "113.22"
  },
  "name": "test_lock",
  "unique_id": "zwavejs2mqtt_0xc8341d86_test"
}
```
can you try this? 
How can you try this?

on the bottom of Zj2m interface you can on the right side ADD a new device.. if you paste this code and click ADD you should be able to add this! it is temporary. this will give it an entity name in HASS `test_lock`
if this works I can then make a patch in z2m! but testing it will help me!

**Comment by johnsonnc** [comment]
I got this to work - but the state topic isn't read correctly, so hass shows it still unlocks.

```
{
  "type": "lock",
  "object_id": "lock",
  "discovery_payload": {
    "command_topic": "homeassistant/FrontDoor/98/0/targetMode/set",
    "state_locked": 255,
    "state_unlocked": 0,
    "payload_lock": 255,
    "payload_unlock": 0,
    "value_template": "{{ value.x }}",
    "json_attributes_topic": "homeassistant/FrontDoor/98/0/currentMode",
    "device": {
      "identifiers": [
        "zwavejs2mqtt_0xeeb41e63_node52"
      ],
      "manufacturer": "Allegion",
      "model": "Touchscreen Deadbolt (BE469)",
      "name": "FrontDoor",
      "sw_version": "128.22"
    },
    "name": "FrontDoor_lock",
    "unique_id": "zwavejs2mqtt_0xeeb41e63_52-98-0-currentMode"
  },
  "discoveryTopic": "lock/FrontDoor/lock/config",
  "values": [
    "98-0-currentMode",
    "98-0-targetMode"
  ],
  "persistent": true,
  "ignoreDiscovery": false,
  "id": "lock_lock"
}
```

**Comment by bachya** [comment]
@billiaz When I select my node, input that JSON, click "Add," then click "Rediscover," I don't see the new entity in Home Assistant. Did I miss a step?

**Comment by billiaz** [comment]
change `value.x` on template with `value_json.value`

also delete the discovery and readd

**Comment by johnsonnc** [comment]
This appears to be working for me now! Thanks @billiaz @bachya !

```
{
  "type": "lock",
  "object_id": "lock",
  "discovery_payload": {
    "command_topic": "homeassistant/FrontDoor/98/0/targetMode/set",
    "state_locked": 255,
    "state_unlocked": 0,
    "payload_lock": 255,
    "payload_unlock": 0,
    "value_template": "{{ value_json.value }}",
    "json_attributes_topic": "homeassistant/FrontDoor/98/0/currentMode",
    "device": {
      "identifiers": [
        "zwavejs2mqtt_0xeeb41e63_node52"
      ],
      "manufacturer": "Allegion",
      "model": "Touchscreen Deadbolt (BE469)",
      "name": "FrontDoor",
      "sw_version": "128.22"
    },
    "name": "FrontDoor_lock",
    "unique_id": "zwavejs2mqtt_0xeeb41e63_52-98-0-currentMode"
  },
  "discoveryTopic": "lock/FrontDoor/lock/config",
  "values": [
    "98-0-currentMode",
    "98-0-targetMode"
  ],
  "persistent": true,
  "ignoreDiscovery": false,
  "id": "lock_lock"
}
```

**Comment by bachya** [comment]
@billiaz Sorry, I'm still not clear. Your payload is different from what @johnsonnc posted; yours still doesn't work for me.

Am I supposed to add @johnsonnc's payload as a new device under the actual lock node (`16` in my case)?

**Comment by billiaz** [comment]
yes! once you do this! and you both confirm works as expected. I will add this on one of the next releases (create patch)

**Comment by bachya** [comment]
@billiaz Sorry to be such a noob, but it's not working. Here's what I'm doing, explicitly:

1. I click on Node 16, which is this lock.
2. I paste this JSON into the `Hass Device JSON` text area:

```json
{
  "type": "lock",
  "object_id": "lock",
  "command_topic": "zwavejs2mqtt/16/98/0/targetMode/set",
  "state_locked": 255,
  "state_unlocked": 0,
  "payload_lock": 255,
  "payload_unlock": 0,
  "value_template": "{{ if value_json.value }}",
  "state_topic": "zwavejs2mqtt/16/98/0/currentMode",
  "json_attributes_topic": "zwavejs2mqtt/16/98/0/currentMode",
    "device": {
      "identifiers": [
        "zwavejs2mqtt_0xc8341d86_node16"
      ],
      "manufacturer": "Allegion",
      "model": "Touchscreen Deadbolt (BE469)",
      "name": "nodeID_16",
      "sw_version": "113.22"
    ,
    "name": "test_lock",
    "unique_id": "zwavejs2mqtt_0xc8341d86_test"
  }
}
```

3. I click `ADD`. Nothing happens (i.e., I don't see this new `test_lock` device in the list to the left).
4. I click `REDISCOVER NODE`. No change.
5. I try restarting the Docker container. No change.

I also tried a different JSON payload that included key/value pairs that @johnsonnc had present

```json
{
  "type": "lock",
  "object_id": "lock",
  "command_topic": "zwavejs2mqtt/16/98/0/targetMode/set",
  "state_locked": 255,
  "state_unlocked": 0,
  "payload_lock": 255,
  "payload_unlock": 0,
  "value_template": "{{ if value_json.value }}",
  "state_topic": "zwavejs2mqtt/16/98/0/currentMode",
  "json_attributes_topic": "zwavejs2mqtt/16/98/0/currentMode",
    "device": {
      "identifiers": [
        "zwavejs2mqtt_0xc8341d86_node16"
      ],
      "manufacturer": "Allegion",
      "model": "Touchscreen Deadbolt (BE469)",
      "name": "nodeID_16",
      "sw_version": "113.22"
    ,
    "name": "test_lock",
    "unique_id": "zwavejs2mqtt_0xc8341d86_test"
  },
  "discoveryTopic": "lock/nodeID_16/lock/config",
  "values": [
    "98-0-currentMode",
    "98-0-targetMode"
  ],
  "persistent": false,
  "ignoreDiscovery": false,
  "id": "lock_test_lock"
}
```

...but again, same steps, no change.

What am I doing wrong?

**Comment by johnsonnc** [comment]
delete `"state_topic": "zwavejs2mqtt/16/98/0/currentMode",`
and change `"value_template": "{{ if value_json.value }}",` -> `"value_template": "{{ value_json.value }}",`

In then click "Update", click the local entity again, click 'Rediscover' next to 'Update'. 

I would then check under the device in HA, under 'MQTT Info' and look for the Lock Entity Discovery payload and see if it updated. 
![Screen Shot 2021-01-05 at 12 59 19 PM](https://user-images.githubusercontent.com/1338373/103698185-d50ac780-4f55-11eb-9a69-d53d2b4dbc1f.png)

**Comment by bachya** [comment]
@johnsonnc Here's what I did:

1. Click on Node 16.
2. Click on the existing lock device `lock_lock`.
3. Updated the `Hass Device JSON` to mirror your suggestion above.
4. Clicked `UPDATE`.
5. Clicked `REDISCOVER`.

No change: I went to Home Assistant, attempt to lock/unlock the lock and there was no response. I went into the `lock_lock` device and saw the old `Hass Device JSON`.

I don't know where to check for your last sentence:

> under the device in HA, under 'MQTT Info' 

I don't see that in zwavejs2mqtt.

**Comment by johnsonnc** [comment]
Those steps with this version. If it doesn't work, I am curious if you have discovery on in HA and zwavejs2 on? 

```
{
  "type": "lock",
  "object_id": "lock",
  "discovery_payload": {
    "command_topic": "zwavejs2mqtt/16/98/0/targetMode/set",
    "state_locked": 255,
    "state_unlocked": 0,
    "payload_lock": 255,
    "payload_unlock": 0,
    "value_template": "{{ value.x }}",
    "json_attributes_topic": "zwavejs2mqtt/16/98/0/currentMode",
    "device": {
      "identifiers": [
        "zwavejs2mqtt_0xc8341d86_node16"
      ],
      "manufacturer": "Allegion",
      "model": "Touchscreen Deadbolt (BE469)",
      "name": "nodeID_16",
      "sw_version": "113.22"
    },
    "name": "-nodeID_16_lock",
    "unique_id": "zwavejs2mqtt_0xc8341d86_16-98-0-currentMode"
  },
  "discoveryTopic": "lock/-nodeID_16_lock/lock/config",
  "values": [
    "98-0-currentMode",
    "98-0-targetMode"
  ],
  "persistent": true,
  "ignoreDiscovery": false,
  "id": "lock_lock"
}
```

**Comment by bachya** [comment]
That payload "worked" (in that it was saved and updated), but then, back in Home Assistant, nothing happens when I try to unlock/lock.

Discovery is enabled, yes?

<img width="1133" alt="Screen Shot 2021-01-05 at 4 46 22 PM" src="https://user-images.githubusercontent.com/47216/103711901-a6044e00-4f75-11eb-9fbb-938f332654e2.png">

**Comment by johnsonnc** [comment]
This is what mine looks like.

<img width="1821" alt="Screen Shot 2021-01-05 at 5 36 20 PM" src="https://user-images.githubusercontent.com/1338373/103718830-89b7df80-4f7c-11eb-9e8e-edf49d86c058.png">

**Comment by bachya** [comment]
Thanks for your help, @johnsonnc.
I'll get back on this tomorrow.

**Comment by billiaz** [comment]
@bachya do not spend time struggling with, with the positive reply from @johnsonnc I am going to write the patch! and ask for review through that. If you have patience a few days! :) 

I am also sometimes struggling with entities, as HASS do not really update them.

The setting I see posted are for Auto generated ones! and how topics stored. to avoid going into a mess of your setup do not change these for now! but let me finish the auto discovery bit and I will ask for your review. I will also build a container on my private docker hub registry to test against.

**Comment by bachya** [comment]
Sounds good, @billiaz – I am relieved. 😂 I'll await the official release and will test then. Thank you!

**Comment by billiaz** [comment]
@bachya pushed a pull request based on @johnsonnc payload. this should fix it.
feel free to compile branch fix-137 and give feedback.
Alternatively you can use the docker from : docker hub `varet/zwavejs2mqtt:fix-137`

**Comment by bachya** [comment]
@billiaz Used the `varet/zwavejs2mqtt:fix-137` image and can confirm: I can lock/unlock my locks from Home Assistant and the state is updated immediately! 🥳 Well done!
