### ISSUE TITLE
[bug] Heal status for a node not updated in UI when healing single node

### ISSUE THREAD

**Issue by jmgiaever** [zwave-js/zwavejs2mqtt#1375]
### Version

**Checklist:**

- [x] I am **not** using HomeAssistant. **Or:** a developer has told me to come here.
- [x] I have checked the troubleshooting section and my problem is **not** described there.
- [x] I have read the changelog problem was **not** mentioned there.

Build/Run method

- [ ] Docker
- [ ] PKG
- [x] Snap package
- [ ] Manually built (git clone - yarn install - yarn run build )

zwavejs2mqtt: 5.0.4.ebfd0b3
zwave-js: 7.7.5

### Describe the bug

The «heal-colum» in the UI doesn't update if you heal a single node. Only when you heal the whole network. 

### To Reproduce

1. Go to control paneø
2. Click on a node and then advanced
3. Choose heal node
4. The heal status is the UI will not update.

### Expected behavior

The status should update also on single node heals. E.g if you heal the whole network and some nodes fails, it should be possible to heal a single node and then get the process/status for the node, like for when healing the whole network.

**Comment by robertsLando** [comment]
@AlCalzone Maybe you should emit the update in progress event even for a single heal?

**Comment by AlCalzone** [comment]
I don't see the need for that additional complexity. If you heal a single node, there's one of 3 possible states:
1. in progress (which is after you started it)
2. done with success (the promise resolved to true)
3. done with failure (the promise resolved to false)

Should be easy enough to handle in the UI?
