### ISSUE TITLE
[question] fibaro223 not properly discovered

### ISSUE THREAD

**Issue by dvbit** [zwave-js/zwavejs2mqtt#138]
Ciao
As per the title I have a couple or fibaro 223 that are not fully discovered. Just one sub device is presented (one out of two devices).
I see at the Zwjs level they have just ine switch. Not only at hass. It was previously correctly enumerated on other integrations (I have done no reinclusion).
Already tried node refresh , heal rediscover and network heal.  Unfortunate no success. Thanks for the great software ! It was needed from years.
More details: zwjs in docker . Latest. Hosted on raspberry 2 . Hass in a vm in pc . Supervised .

**Comment by billiaz** [comment]
I have multiple 223 and work as expected. Are you running the latest build from dev ?
can you give some examples what is missing? Also you can export the node json from the nodes themselves!

If you provide with a json export of the node, and some more specific example I might be helpful

**Comment by dvbit** [comment]
Ok . I will try to switch to dev .
Try because I am using a docker is there a dev image available?

By The way : I have checked that the devices are not recognized completely also in Zwave2mqtt and OpenZwave (Hass component),

That is strange as, before having to reformat due to a problem, they were correctly recognized

**Comment by dvbit** [comment]
Ok Just read the instructions to build the docker.
git clone https://github.com/zwave-js/zwavejs2mqtt.git
cd zwavejs2mqtt/docker
docker build -f docker/Dockerfile --build-arg Z2M_GIT_SHA1=master -t zwavejs/zwavejs2mqtt:latest .

**Comment by dvbit** [comment]
Uhm. Which branch is the dev? I see just 3 tags alpha-0 - 1 -2
Alpha 2?

**Comment by billiaz** [comment]
I meant to use the Docker from dev (build form master branch)! alpha.2 would also do the work
Now on the other hand is this a HASS issue or the webinterface is not identifying the device?

can you post a screenshot? also when you click on a device can you post the information below ?

I have 5 FGS 223 without any issues

![Screenshot 2021-01-04 at 09 16 53](https://user-images.githubusercontent.com/4048920/103514770-9d285500-4e6d-11eb-895a-b382e1ee65b6.png)

**Comment by dvbit** [comment]
I have done a fresh install of the latest image in docker and I can now see two switches.
The value report the correct value (i.e. when I press the physical switch the software twin status updates correctly).
The actuation however does not work: if, from control panel, I set the value of one of the switches I have a toast of "Correctly written value from the API but the switch does not turn on and the software twin does not update.

Can I ask the polling values you have setup?

another unrelated question: how do I retrigger the discovery ni homeassistant I already did a rediscover but no effect.

Thanks for the support

**Comment by billiaz** [comment]
@dvbit i cannot find the message you posted, although i received a mail :\

**Comment by dvbit** [comment]
I deleted... since I had an update in progress.
So:
repulled fresh latest image
recreated docker
rediscoverd nodes
and 223 seem now to be there and complete.
They take sometime to be updated / reactive (always happened to me also in other implementation with "secure" nodes)
So I would say this issue can be closed.
Thanks for the support : keep on zwavejs2mqtt is really promising to be THE integration to zwave world

**Comment by dvbit** [comment]
uhm... too fast.
Works in the panel
not in homeassistant.
Homeassistant Software Switch is not sending signal to zwavejs (or is not received,,,)

**Comment by robertsLando** [comment]
@dvbit I think @billiaz means you should try with `dev` tag instead of `latest`

**Comment by dvbit** [comment]
Ok I switched to dev.
All properties are exposed to HassOS MQTT broker Addon but just for 223 switch is not actuating on zwavejs2mqtt side.
From zwavejs2mqtt control panel same 223 is reacting (fast!) to commands
this is an example of the json object for one of the two switches in zwavejs2mqtt panel
`{
  "type": "switch",
  "object_id": "switch",
  "discovery_payload": {
    "payload_off": false,
    "payload_on": true,
    "value_template": "{{ value_json.value }}",
    "command_topic": "zwave/3/37/1/targetValue/set",
    "state_topic": "zwave/3/37/1/currentValue",
    "device": {
      "identifiers": [
        "zwavejs2mqtt_0xf69990fa_node3"
      ],
      "manufacturer": "Fibargroup",
      "model": "Double Switch 2 (FGS223)",
      "name": "nodeID_3",
      "sw_version": "3.3"
    },
    "name": "nodeID_3_switch",
    "unique_id": "zwavejs2mqtt_0xf69990fa_3-37-1-currentValue"
  },
  "discoveryTopic": "switch/nodeID_3/switch/config",
  "values": [
    "37-1-currentValue",
    "37-1-targetValue"
  ],
  "persistent": true,
  "ignoreDiscovery": false,
  "id": "switch_switch"
}`

**Comment by dvbit** [comment]
and I can see in the debug log that I receive an mqtt message to set the switch
`2021-01-04 16:26:34.677 INFO ZWAVE: Node 15: metadata updated: 49-0-Illuminance
2021-01-04 16:26:34.693 INFO ZWAVE: Node 15: value updated: 49-0-Illuminance 38 => 0
2021-01-04 16:26:35.062 INFO ZWAVE: Node 15: metadata updated: 48-0-Any
2021-01-04 16:26:35.070 INFO ZWAVE: Node 15: value updated: 48-0-Any false => true
2021-01-04 16:26:35.121 INFO ZWAVE: Node 15: value updated: 48-0-Any true => true
2021-01-04 16:26:43.497 INFO MQTT: Message received on zwave/3/37/1/targetValue/set
2021-01-04 16:27:00.970 INFO MQTT: Message received on zwave/3/37/2/targetValue/set
2021-01-04 16:27:05.830 INFO ZWAVE: Node 15: metadata updated: 48-0-Any
2021-01-04 16:27:05.839 INFO ZWAVE: Node 15: value updated: 48-0-Any true => false
2021-01-04 16:27:05.879 INFO ZWAVE: Node 15: value updated: 48-0-Any false => false`

See node 37 set value 1 and 2 above.
However in hassos the ui rebound back to off and the light is still off.

**Comment by billiaz** [comment]
do you send on both endpoints a set value? or you click once and changes both at once?

I also edited your comments and changed the code snippet (sorry for this, they where more readeable that way)

Can you send me the second switch (switch_2) and also:
when you press the actuator from HASS do you see two payloads set? or one?

**Comment by dvbit** [comment]
Ok. I finally nailed down the cause of unresponsiveness on hass commands.
Somehow the entiry created in Homeassistant was inconsistent (half of it was named after renamed node in zwjs2mqtt the other half with the original naming).
After deleting the entity and rediscovering it everything fine.
regarding the original problem after rediscovering nodes properties all was populated properly.
In the initial node description just a few properies were reported (for example no configuration menu).
Now I think everything is there.
Congrats: for the first time in years I see a complete representation of a zwave device in a open source software!
Way to go. Best os zwave software so far! @robertsLando Complimenti!

**Comment by dvbit** [comment]
reopening...

**Comment by dvbit** [comment]
I have most  of the sensor loaded in HassOs with custom naming (according to template).
And most of it under the internal "node" nomenclature.
That part is unresponsive.
The other 223 that I have is working fine.

**Comment by billiaz** [comment]
@dvbit As much as I would like to help. It makes no sense to me what the issue currently is.

If the discovery of one device works the other device might face:
1. stored Hass discovery under zwavejs2mqtt, this could be fixed by pressing `delete store` and rediscover node
2. broken HassOs discovery storage, which needs cleanup

**Comment by dvbit** [comment]
Thanks for trying.
First workday so..can answer just now.
What would be the right process to reimport just those two devices as freshly as possible (they are now both unresponsive).
I am going to try the following:
- delete store
- stop zj2m
- delete mqtt entties from ha
- start zj2m
- rediscover node
- store
- restart ha

Should discover flag in zj2m be enabled or not?

**Comment by dvbit** [comment]
no success.
What is also strange is that I could delete the device in hass without it complainng (usually hass complains if the corresponfing integration is still pushing info and will not let you delete a device.

**Comment by dvbit** [comment]
Final update... 
Heal node + refresh info and the nodes are now responsive.
There is still one entity missing in both *.slowrefresh
but , for now, I will leave it as is since I do not use that info currently

**Comment by dvbit** [comment]
Give it time... today also the last property appeared.
I close the issue.
Once again thanks for the perfect tool.
a zwaver since 2010
