### ISSUE TITLE
Add/Remove Inclusion command with MQTT message/topic

### ISSUE THREAD

**Issue by archerixx** [zwave-js/zwavejs2mqtt#1382]
**Is your feature request related to a problem? Please describe.**
Trying to make system that works with MQTT messages only. So problem in some way would be that I need to access website to activate Inclusion instead of activating it through PUBLISH message.

**Describe the solution you'd like**
I would like if possible to have topic that I can PUBLISH to with MQTT messages, so I can start/stop Inclusion process with
Example: 
Topic: zwave/_EVENTS/ZWAVE_GATEWAY-zwave/controller/inclusion_started/set
Message (JSON): {"value":true}

I tried searching for it myself to add, but I am getting a bit lost with all of this. It would be great if this feature would be approved or if there is alternative to it where I can use MQTT to activated/deactivate Inclusion process.

**Comment by robertsLando** [comment]
You can do it by using MQTT Apis: https://zwave-js.github.io/zwavejs2mqtt/#/guide/mqtt?id=zwave-apis

Topic

`<mqtt_prefix>/_CLIENTS/ZWAVE_GATEWAY-<mqtt_name>/api/startInclusion/set`

Payload

```json
{
  "args": [true] // set this to true to start a secure inclusion, false otherwise
}
```

**Comment by archerixx** [comment]
Thanks a million, saved my hours 🗡️
