### ISSUE TITLE
[bug] docker :  switching from 4.5.2 to 5.0.0 or latest fail

### ISSUE THREAD

**Issue by Gis70** [zwave-js/zwavejs2mqtt#1385]
### Version

**Checklist:**

- [ x] I am **not** using HomeAssistant. **Or:** a developer has told me to come here.
- [x ] I have checked the troubleshooting section and my problem is **not** described there.
- [x ] I have read the changelog problem was **not** mentioned there.

Build/Run method

- [x ] Docker
- [ ] PKG
- [ ] Snap package
- [ ] Manually built (git clone - yarn install - yarn run build )

zwavejs2mqtt version: 4.5.2
zwave-js version: 7.7.2

### Describe the bug

switching from 4.5.2 to 5.0.0 or latest fail : 
`Error: Cannot find module 'moment-timezone'
Require stack:
- /usr/src/app/node_modules/@zwave-js/config/node_modules/@zwave-js/core/build/util/date.js
- /usr/src/app/node_modules/@zwave-js/config/node_modules/@zwave-js/core/build/index.js
- /usr/src/app/node_modules/@zwave-js/config/build/ConfigManager.js
- /usr/src/app/node_modules/@zwave-js/config/build/index.js
- /usr/src/app/node_modules/zwave-js/build/lib/commandclass/MultilevelSensorCC.js
- /usr/src/app/node_modules/zwave-js/build/lib/commandclass/index.js
- /usr/src/app/node_modules/zwave-js/CommandClass.js
- /usr/src/app/node_modules/zwave-js/index.js
- /usr/src/app/server/lib/ZwaveClient.js
- /usr/src/app/server/app.js
- /usr/src/app/server/bin/www.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:941:15)
    at Function.Module._load (node:internal/modules/cjs/loader:774:27)
    at Module.require (node:internal/modules/cjs/loader:1013:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (/usr/src/app/node_modules/@zwave-js/config/node_modules/@zwave-js/core/src/util/date.ts:2:1)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
    at Module.require (node:internal/modules/cjs/loader:1013:19)
Error: Cannot find module 'moment-timezone'`

### To Reproduce
Recreate docker container from portainer with latest. No problem to do it like this before upgrading to 5.0.0 or newer

**Comment by robertsLando** [comment]
Please share your docker compose file

**Comment by Gis70** [comment]
> Please share your docker compose file

Hello, voilà :  
`services:
  zwavejs2mqtt:
    container_name: zwavejs2mqtt
    image: zwavejs/zwavejs2mqtt:latest
    restart: always
    tty: true
    stop_signal: SIGINT
    networks:
      - zwave
    devices:
      - '/dev/ttyACMZWave:/dev/ttyACMZWave'
    volumes:
      - ./store:/usr/src/app/store
      - zwave-config:/usr/src/app/node_modules/@zwave-js/config
     # - ./package-lock.json:/usr/src/app/package-lock.json
    ports:
      - '8091:8091' # port for web interface
      - '3000:3000' # port for zwave-js websocket server
networks:
  zwave:
volumes:
  zwave-config:
    name: zwave-config`

**Comment by robertsLando** [comment]
> - zwave-config:/usr/src/app/node_modules/@zwave-js/config

Remove that line and everything will work.

**Comment by Gis70** [comment]
It's fine thanks.
