### ISSUE TITLE
[bug] Qubino Mini Dimmer not updating entity states

### ISSUE THREAD

**Issue by thecobra666** [zwave-js/zwavejs2mqtt#1389]
- [ ] I am **not** using HomeAssistant. **Or:** a developer has told me to come here.
- [x] I have checked the troubleshooting section and my problem is **not** described there.
- [x] I have read the changelog problem was **not** mentioned there.

Build/Run method

- [x] Docker

zwavejs2mqtt: 5.1.0
zwave-js: 7.9.0

Connected to HA with the zwaveJS websocket.

### Describe the bug

Qubino Mini Dimmer ZMNHHD does not push it's changed state when toggled with a fysical switch. I have 2 of them. One is on firmware 20.0 and the other is on 20.2. The one on firmware 20.0 works like expected. The other does not change it's state in HA unless manually polled.

`alias: Zwave Polling
description: ''
trigger:
  - platform: time_pattern
    seconds: /2
condition: []
action:
  - service: zwave_js.refresh_value
    data:
      entity_id: light.toilet_boven
mode: single`

### To Reproduce

Enable the light via the switch. HA entity not updated on dimmer with firmware 20.2.  Because of this I'm unable to actually use the dimmer for what I bought it. In the day the dimmer may stay on 100% but when it's night, I want to dim the light to 30%. 

### Expected behavior

Entity status updated.

### Additional context

I have attached the debug info below.

//edit 29/06/21 added zwavejs2mqtt log

[qubinozmnhhd-fw20.0.txt](https://github.com/zwave-js/zwavejs2mqtt/files/6724847/qubinozmnhhd-fw20.0.txt)
[qubinozmnhhd-fw20.2.txt](https://github.com/zwave-js/zwavejs2mqtt/files/6724848/qubinozmnhhd-fw20.2.txt)
[json files nodes.zip](https://github.com/zwave-js/zwavejs2mqtt/files/6725492/json.files.nodes.zip)
[zwavejs2mqtt.log](https://github.com/zwave-js/zwavejs2mqtt/files/6731238/zwavejs2mqtt.log)

**Comment by robertsLando** [comment]
> Connected to HA with the zwaveJS websocket.

I have no control of that, you should open the issue on hass repo
