### ISSUE TITLE
[feat] Provide a way to distinguish changes

### ISSUE THREAD

**Issue by dvbit** [zwave-js/zwavejs2mqtt#139]
Include a field in mqtt set message to differentiate UI/Automation  originated state changes vs Physical pressure originated 
Include a field in mqtt status  to differentiate mark how sttus was set UI / Automation vs Physical pressure

Objective: Provide a simple way for automation override

**Comment by billiaz** [comment]
can you explain more in this request? some detailed example could help.

**Comment by dvbit** [comment]
Sure. 
I mean that I would like to know if a device like a switch has changed its status due to a physical action (being pushed) or programmatically via mqtt setvalue or an automation. 
I have some automation that stop working for a set time if the user pushes a button. 
Example : light goes off after 5 min of no movement but if light was manually turned on that time limit is changed to say 10 min or until user turns off manually 
I have done that through some workaround in nodered .
It would be nice to do it in a simpler way.

**Comment by dvbit** [comment]
Can be closed. Did it in ho,e assistant
