### ISSUE TITLE
Fibaro FGS-223 does not complete interview

### ISSUE THREAD

**Issue by gabichan** [zwave-js/zwavejs2mqtt#1407]
I have a Fibaro FGS-223 double switch that was working fine for a few weeks with a previous version of Zwave2MQTT. Suddenly, 2 weeks ago, It became dead, and I can't recover it. I had upgraded Zwave2MQTT 3 or 4 days before, but I don't think it to be the cause.

The NodeInfo stage is completed always, but it remains in that state forever.

Here is the log for an interview performed today (node 017):
[zwavejs_2021-07-06.log](https://github.com/zwave-js/zwavejs2mqtt/files/6770071/zwavejs_2021-07-06.log)

Hope you can help.

This is a great job what you're doing here, by the way.

**Comment by AlCalzone** [comment]
It does not respond to most queries:

> Timed out while waiting for a response from the node

That **might** be because it is included securely, but it also does not respond to the query where the driver tests that. You could try cutting the power to the device for a couple of seconds and then try re-interviewing again.

**Comment by gabichan** [comment]
It worked!!!!

Thank you very much.
