### ISSUE TITLE
[feat] Hard exit or restart of driver when it gets destroyed

### ISSUE THREAD

**Issue by wilmardo** [zwave-js/zwavejs2mqtt#1409]
**Is your feature request related to a problem? Please describe.**
I am running Zwavejs2mqtt with a remote TCP serial connection to a Z-Wave adapter. Sometimes the connection seems to get interrupted and I need to restart the container.
```
2021-07-07 11:41:25.499 INFO ZWAVE: Node 6: value updated: 50-0-value-66561 230.28 => 230.1
2021-07-07 11:41:26.505 INFO ZWAVE: Node 6: value updated: 50-0-value-66817 0 => 0
2021-07-07 11:44:55.340 INFO ZWAVE: Controller status: Driver: read ETIMEDOUT
2021-07-07 14:25:35.072 INFO MQTT: Message received on zwave/nodeID_6/37/0/targetValue/set, <Buffer 54 72 75 65>
2021-07-07 14:25:35.073 INFO ZWAVE: Writing true to 6-37-0-targetValue
2021-07-07 14:25:35.079 ERROR ZWAVE: Error while writing true on 6-37-0-targetValue: The driver is not ready or has been destroyed
2021-07-07 14:25:35.080 ERROR ZWAVE: Unable to write true on 6-37-0-targetValue
```

**Describe the solution you'd like**
I see two solutions:

* an hard exit on the driver being not ready anymore. Since I am using Kubernetes (but will also work with docker/docker-compose with the restart option set) the container will restart and re-init the driver.
* a restart of the driver when it gets destroyed within the zwavejs2mqtt process

I am in favor of the first, it shouldn't be hard to implement and it seems like logical behavior to me, zwavejs2mqtt is nothing without the connection to the adapter so a hard crash seems fine to me.

**Comment by robertsLando** [comment]
> a restart of the driver when it gets destroyed within the zwavejs2mqtt process

This should already be handled when zwave js throws a driver error. @AlCalzone Could it be possible to throw a driver error when receaving an `ETIMEDOUT` ?

**Comment by AlCalzone** [comment]
We added this a while ago: https://github.com/zwave-js/node-zwave-js/pull/2601
With zwave-js v7.9.0, any serial disconnections should cause the driver to be destroyed. AFAIK zwavejs2mqtt picks that up and restarts the driver.

@wilmardo how exactly are you configuring the remote USB connection?

**Comment by wilmardo** [comment]
> @wilmardo how exactly are you configuring the remote USB connection?

I don't exactly know what you mean by remote USB connection but I have my port defined like this:
```
tcp://192.168.1.23:23
```

And I use esp-link on a ESP8266 with a RaZberry shield connected.

Does that provide the answer you looking for?

**Comment by AlCalzone** [comment]
> tcp://192.168.1.23:23

Is that the address that's given to the driver? In that case, `zwave-js` should be able to detect the disconnection and destroy itself.
I've tested with a similar setup with `ser2net` on a Raspberry Pi. As soon as `ser2net` was shut down or the network was disconnected, the driver was destroyed.

However, the automatic disconnection only works starting in `v7.9.0` - not sure which one you are on.

**Comment by robertsLando** [comment]
Closing this for now, I think that an update to latest should fix the errors
