### ISSUE TITLE
[bug] X-External-Path header not working for js + css include

### ISSUE THREAD

**Issue by gorootde** [zwave-js/zwavejs2mqtt#1411]
### Version

**Checklist:**

- [x] I am **not** using HomeAssistant. **Or:** a developer has told me to come here.
- [x] I have checked the troubleshooting section and my problem is **not** described there.
- [x] I have read the changelog problem was **not** mentioned there.

Build/Run method

- [x] Docker
- [ ] PKG
- [ ] Snap package
- [ ] Manually built (git clone - yarn install - yarn run build )

zwavejs2mqtt version: 5.2.1
zwave-js version: 7.10.1

### Describe the bug

Adding the `X-External-Path` header via reverse proxy to `/zwave` serves the `index.html` without any error. However, the included css and js paths return 404. 

Paths of these files:
- https://my.server/zwave/static/css/app.3ef71e230a7d149d2175.css
- https://my.server/zwave/static/js/app.7bde19f1c2c0dbfd53e1.js

### To Reproduce

1. configure a reverse proxy as described above
2. visit the configured URL
3. Open web inspector and have a look at the error console

### Expected behavior

Page loads css and js as it also does when used without reverse proxy

**Comment by robertsLando** [comment]
Please be sure you followed all the docs in https://zwave-js.github.io/zwavejs2mqtt/#/usage/reverse-proxy and https://github.com/zwave-js/zwavejs2mqtt/discussions/1396#discussioncomment-956576
