### ISSUE TITLE
[bug] Custom config is not read

### ISSUE THREAD

**Issue by Seraph1m89** [zwave-js/zwavejs2mqtt#1421]
In order to test the configuration add it as a pull request, I need a way to create a custom config for this device.
I'm running zwavejs2mqtt as a docker container. I followed the instructions from https://zwave-js.github.io/zwavejs2mqtt/#/getting-started/quick-start everything is running smooth but when I try to follow the steps in this example https://zwave-js.github.io/zwavejs2mqtt/#/development/intro?id=testing-custom-devices-config but they don't work.
STR:
1. Run docker of zwave2mqtt as described in official guide https://zwave-js.github.io/zwavejs2mqtt/#/getting-started/quick-start
2. Have a device that is not yet in the config database
3. Write custom device configuration as .json file
4. Add configuration to store/config folder (can be done through UI or via terminal)
5. Restart docker, reinterview the node
AR:
Configuration is not read from the file. COnfig section is empty
ER:
File is read and it is indicated in the logs. Device has additional config properties after interviewing.

**Comment by robertsLando** [comment]
Could you attach zwavejs logs? You should see a log when a custom config is loaded

**Comment by Seraph1m89** [comment]
The problem is I don't see any logs regarding custom configs. I can only see nodes loading but nothing about custom configs. I also tried to verify validity of my config but am always retrieving various errors on running yarn run lint:config on npm run lint:config from a cloned repository

**Comment by Seraph1m89** [comment]
The problem was on my side due o incorrect config, sorry
