### ISSUE TITLE
[question] entity names

### ISSUE THREAD

**Issue by rwa** [zwave-js/zwavejs2mqtt#144]
I am considering trying to migrate from ozw, but it appears that all of my entities would change names to do so.  In order to ease that transition, I was wondering if it was even theoretically possible to change out the entity names auto-generated by zwavejs2mqtt to be the same as what I customized them to in ozw.

Looking at the code, it kind of looks like entity names are possibly not arbitrarily user-settable, they have to conform to some (configurable) pattern?  Is that right? Or do they exist in a config file somewhere that I could swap them out for whatever I wanted (in particular, my current ozw entity names)?

**Comment by rwa** [comment]
Working on this a bit further, it looks I can indeed edit the entity names however I like within HA, and these are stored for HA purposes.

So I was trying to see if I could dump out my ozw entities, and programmatically generate a mapping from their names to the default names I could expect from this package. For a switch, this was easy, it was (for example):

switch.nodeID_2_switch

but with more complex entities, it became mysterious.  For example:

sensor.nodeID_3_electric1_a_meter_66817_value

where did 66817 come from?

**Comment by robertsLando** [comment]
@rwa Did you try with https://community.home-assistant.io/t/qt-openzwave-beta-vs-zwavejs2mqtt/263801/14?

**Comment by rwa** [comment]
Yes.  I came to the conclusion it wasn't going to be possible (or at least worth the effort). Closing.
