### ISSUE TITLE
[question] recommended settings for broker

### ISSUE THREAD

**Issue by rwa** [zwave-js/zwavejs2mqtt#145]
I think the documentation could be improved by giving default suggestions for the following settings, for ease of giving things a spin when you're just learning MQTT (or just prefilling defaults).

"Reconnect period: Milliseconds between two reconnection tries"
I don't know what to put here.  10? 1000? How do I know what's a reasonable setting?

"Prefix: The prefix where all values are published"
How do I choose this? Is it totally arbitrary? Does it have to match anything somewhere else?

"QoS: Quality Of Service (check MQTT specs) of outgoing packets"
I get the basic idea of it, but I don't know what to prefer here.

"Retain: The retain flag of outgoing packets"
Clean: Sets the clean flag when connecting to the broker
Store: Enable/Disable persistent storage of packets (QoS > 0)"
How do I know what to choose for these?  Why should I prefer one or the other?

**Comment by robertsLando** [comment]
I think this is a dup of #147 that is more generic. CLosing this and continue there. I think the solution to this is to provide some defaults values and improve the docs
