### ISSUE TITLE
[question] Move to a new controller?

### ISSUE THREAD

**Issue by agrieco** [zwave-js/zwavejs2mqtt#1455]
I have had zwavejs2mqtt up and running and wanted to move to a new controller.  I run in a container, so I blow away the the old container, create the new on passing in the new device and fire it up.  No problem- controller is recognized, I've selected it for zwave in the zwavejs2mqtt web interface and I've confirmed the network key is the same....yet...the only node that shows up is that of the new controller. 

What am I missing?  I would have expected to see my nodes populate over time- yet 3 hrs in- still only my controller.

I went from the ZooZ ZST10 to the ZST10 700.  

thx

**Comment by marc-gist** [comment]
z-wave network is stored on the controller usb device.  Check google or manufacture site to see if they have a tool to backup from the ZooZ old stick and restore to the new.  the Aeotec tool may work, as I've heard rumor that the ZooZs are just re-branded Aoetecs.

**Comment by AlCalzone** [comment]
A 500-series backup might not work with the new Z-Wave 700 sticks, as the memory layout is different.
You might wanna give this a try: https://github.com/zwave-js/node-zwave-js/discussions/2927#discussioncomment-959007

**Comment by agrieco** [comment]
> A 500-series backup might not work with the new Z-Wave 700 sticks, as the memory layout is different.
> You might wanna give this a try: [zwave-js/node-zwave-js#2927 (reply in thread)](https://github.com/zwave-js/node-zwave-js/discussions/2927#discussioncomment-959007)

very useful.  thank you.
