### ISSUE TITLE
Dockerfile.contrib gets broken by upgrading to v8 of `zwave-js`

### ISSUE THREAD

**Issue by AlCalzone** [zwave-js/zwavejs2mqtt#1463]
See https://zwave-js.github.io/node-zwave-js/#/development/installing-from-github for reference.

This should not be done
https://github.com/zwave-js/zwavejs2mqtt/blob/698958e55413af49f00ad93ec41b9612f7d20743/docker/Dockerfile.contrib#L27

This is unnecessary
https://github.com/zwave-js/zwavejs2mqtt/blob/698958e55413af49f00ad93ec41b9612f7d20743/docker/Dockerfile.contrib#L28

Yarn v3 no longer has a --network-timeout param:
https://github.com/zwave-js/zwavejs2mqtt/blob/698958e55413af49f00ad93ec41b9612f7d20743/docker/Dockerfile.contrib#L29
Use https://yarnpkg.com/configuration/yarnrc#httpTimeout instead or set it as an env variable:
```
YARN_HTTP_TIMEOUT=... yarn install
```

The `build:full` command is deprecated, use `build` instead
https://github.com/zwave-js/zwavejs2mqtt/blob/698958e55413af49f00ad93ec41b9612f7d20743/docker/Dockerfile.contrib#L30

The `--frozen-lockfile` parameter is now called `--immutable`
https://github.com/zwave-js/zwavejs2mqtt/blob/698958e55413af49f00ad93ec41b9612f7d20743/docker/Dockerfile.contrib#L31

This doesn't work:
https://github.com/zwave-js/zwavejs2mqtt/blob/698958e55413af49f00ad93ec41b9612f7d20743/docker/Dockerfile.contrib#L31
Creating a production install should be done with this `yarn` plugin instead:
https://gitlab.com/Larry1123/yarn-contrib/-/tree/master/packages/plugin-production-install

Not sure if versioning that way works:
https://github.com/zwave-js/zwavejs2mqtt/blob/698958e55413af49f00ad93ec41b9612f7d20743/docker/Dockerfile.contrib#L34-L36
but in any case, `yarn workspaces foreach --include ... ` should be used instead to run commands in the workspaces. Linking that way won't work either, better use the aforementioned plugin and overwrite the install path with `"resolutions"` as described here:
https://zwave-js.github.io/node-zwave-js/#/development/installing-from-github

/cc @larstobi

**Comment by robertsLando** [comment]
@larstobi Could you apply the required changes to that file? I don't use it

**Comment by thecobra666** [comment]
So I can asume upgrading will result in bricking my docker container install? Do I wait for this fix?

**Comment by robertsLando** [comment]
@thecobra666 This is just for the ones that are building their custom docker containers from z2m and zjs branches. It's mostly used to test things not for production builds
