### ISSUE TITLE
[bug] /SET does not work when Gateway Topic Type is set to Configured Manually

### ISSUE THREAD

**Issue by rickoman** [zwave-js/zwavejs2mqtt#1464]
### Version
Tested with 5.2.2/7.12.0 and latest 5.3.0/8.0.1

**Checklist:**

- [x] I am **not** using HomeAssistant. **Or:** a developer has told me to come here.
- [x] I have checked the troubleshooting section and my problem is **not** described there.
- [x] I have read the changelog problem was **not** mentioned there.

Build/Run method

- [x] Docker
- [ ] PKG
- [ ] Snap package
- [ ] Manually built (git clone - yarn install - yarn run build )

zwavejs2mqtt version: 5.3.0
zwave-js version: 8.0.1

### To Reproduce

There appears to be a bug when the **Gateway Topic Type** is set to **Configured Manually**.  When the container is started it does not subscribe to the /set topic.  

Tested with 5.2.2/7.12.0 and latest 5.3.0/8.0.1

I edited my /etc/mosquito/mosquito.conf file to include the following directives so that I could monitor subscription changes made by zwavejs2mqtt.

```
log_type subscribe
log_type unsubscribe
```

I changed the **Gateway Topic Type** to **Configured Manually**, saved and restarted the docker container.  Watching the mosquito.log for subscriptions I get this. Notice no subscription to any /set topics

```
1626790638: ZWAVE_GATEWAY-house 0 house/_CLIENTS/ZWAVE_GATEWAY-house/broadcast/#
1626790638: ZWAVE_GATEWAY-house 0 house/_CLIENTS/ZWAVE_GATEWAY-house/api/#
1626790638: ZWAVE_GATEWAY-house 0 house/_CLIENTS/ZWAVE_GATEWAY-house/multicast/#
1626790743: ZWAVE_GATEWAY-house 0 homeassistant/status
```

Then I changed the **Gateway Topic Type** to **Named Topics**, saved and restarted. It properly subscribes to the /set topic

```
1626790924: ZWAVE_GATEWAY-house 0 house/+/+/+/+/+/+/set
1626790944: ZWAVE_GATEWAY-house 0 homeassistant/status
1626790944: ZWAVE_GATEWAY-house 0 house/_CLIENTS/ZWAVE_GATEWAY-house/broadcast/#
1626790944: ZWAVE_GATEWAY-house 0 house/_CLIENTS/ZWAVE_GATEWAY-house/api/#
1626790944: ZWAVE_GATEWAY-house 0 house/_CLIENTS/ZWAVE_GATEWAY-house/multicast/#
1626790951: ZWAVE_GATEWAY-house 0 house/+/+/+/+/+/set
```

Then I changed the **Gateway Topic Type** to **ValueId**, saved and restarted. It also properly subscribes to the /set topic

```
1626791006: ZWAVE_GATEWAY-house 0 house/+/+/+/+/+/+/set
1626791038: ZWAVE_GATEWAY-house 0 homeassistant/status
1626791038: ZWAVE_GATEWAY-house 0 house/_CLIENTS/ZWAVE_GATEWAY-house/broadcast/#
1626791038: ZWAVE_GATEWAY-house 0 house/_CLIENTS/ZWAVE_GATEWAY-house/api/#
1626791038: ZWAVE_GATEWAY-house 0 house/_CLIENTS/ZWAVE_GATEWAY-house/multicast/#
1626791044: ZWAVE_GATEWAY-house 0 house/+/+/+/+/+/set
```

Then I changed the **Gateway Topic Type** back to **Configured Manually**, SAVED, DID NOT restart. This time it subscribed to /set but the pattern wrong I believe it should be house/+/+/+/set 

```
1626791044: ZWAVE_GATEWAY-house 0 house/+/+/+/+/+/+/set
1626791128: ZWAVE_GATEWAY-house 0 homeassistant/status
```

Then shutdown and restart.  Notice no subscription to /set after restarting the container.

```
1626791128: ZWAVE_GATEWAY-house 0 house/_CLIENTS/ZWAVE_GATEWAY-house/broadcast/#
1626791128: ZWAVE_GATEWAY-house 0 house/_CLIENTS/ZWAVE_GATEWAY-house/api/#
1626791128: ZWAVE_GATEWAY-house 0 house/_CLIENTS/ZWAVE_GATEWAY-house/multicast/#
1626791225: ZWAVE_GATEWAY-house 0 homeassistant/status
```

**Comment by robertsLando** [comment]
When configured manually z2m subscribes just to the values added to gateway values table that are not read only. Can I see your settings file?

**Comment by robertsLando** [comment]
Found the reason that could cause this. PR is ready
