### ISSUE TITLE
[bug] 5.4.1 shows all manufacturers/products as unknown

### ISSUE THREAD

**Issue by decairn** [zwave-js/zwavejs2mqtt#1469]
### Version
5.4.1

**Checklist:**

- [X] I am **not** using HomeAssistant. **Or:** a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is **not** described there.
- [X] I have read the changelog problem was **not** mentioned there.

Build/Run method

- [X] Docker
- [ ] PKG
- [ ] Snap package
- [ ] Manually built (git clone - yarn install - yarn run build )

zwavejs2mqtt version: 5.4.1
zwave-js version: 8.0.4

### Describe the bug

UI panel shows Unknown manufacturer and Unknown product for every node on version 5.4.1.  Roll back to 5.4.0 and they're all filled in as expected.

### To Reproduce

Install 5.4.1 Docker. Start up. Open UI.

### Expected behavior

The manufacturers and products are all known

**Comment by decairn** [comment]
Zwave and zwave2mqtt logs

[logs.zip](https://github.com/zwave-js/zwavejs2mqtt/files/6862407/logs.zip)

**Comment by robertsLando** [comment]
Wait next release, it's coming

**Comment by decairn** [comment]
5.4.2 fixes it
