### ISSUE TITLE
"ERROR GATEWAY: Zwave settings are not valid" upon starting docker container

### ISSUE THREAD

**Issue by fracture-point** [zwave-js/zwavejs2mqtt#1473]
### Version

**Checklist:**

- [x] I am **not** using HomeAssistant. **Or:** a developer has told me to come here.
- [x] I have checked the troubleshooting section and my problem is **not** described there.
- [x] I have read the changelog problem was **not** mentioned there.

Build/Run method

- [x] Docker
- [ ] PKG
- [ ] Snap package
- [ ] Manually built (git clone - yarn install - yarn run build )

zwavejs2mqtt version: latest (unable to access webui)
zwave-js version: latest (unable to access webui)

### Describe the bug

I'm stuck at step 0 - I try to spin this up in a docker container using the following command:
`docker run --rm -it -p 8091:8091 -p 3000:3000 --device=/dev/ttyACM1 -v $(pwd)/config-zwave:/usr/src/app/store zwavejs/zwavejs2mqtt:latest`

...on a Raspberry pi4 running Raspbian (and the zigbee stick is at ttyACM1), and I immediately get this error:

```
/bin/sh: git: not found
2021-07-23 13:41:38.603 INFO APP: Version: 5.4.2
2021-07-23 13:41:38.610 INFO APP: Application path:/usr/src/app

 ______                       _     ___                  _   _   
|___  /                      (_)   |__ \                | | | |  
   / /_      ____ ___   _____ _ ___   ) |_ __ ___   __ _| |_| |_ 
  / /\ \ /\ / / _` \ \ / / _ \ / __| / /| '_ ` _ \ / _` | __| __|
 / /__\ V  V / (_| |\ V /  __/ \__ \/ /_| | | | | | (_| | |_| |_ 
/_____|\_/\_/ \__,_| \_/ \___| |___/____|_| |_| |_|\__, |\__|\__|
                            _/ |                      | |        
                           |__/                       |_|        

2021-07-23 13:41:38.647 WARN STORE: settings.json not found
2021-07-23 13:41:38.652 WARN STORE: scenes.json not found
2021-07-23 13:41:38.655 WARN STORE: nodes.json not found
2021-07-23 13:41:38.710 INFO APP: Listening on port 8091 host 0.0.0.0 protocol HTTP
2021-07-23 13:41:38.814 ERROR GATEWAY: Zwave settings are not valid
```
I am unable to access the UI on 8091 - it times out. No other containers are accessing the stick. The app correctly populates the `config-zwave` folder:

```
ls -la config-zwave/
total 16
drwxr-xr-x 3 root root 4096 Jul 23 09:36 .
drwxr-xr-x 5 pi   pi   4096 Jul 23 09:36 ..
drwxr-xr-x 2 root root 4096 Jul 23 09:36 sessions
-rw-r--r-- 1 root root  186 Jul 23 09:36 users.json
```

**Comment by robertsLando** [comment]
That's ok you should be able to access the ui as the app is listening

**Comment by fracture-point** [comment]
Ah right you are.  What I hadn't noticed was that docker assigned a random host port mapped to the container port.  E.g. a `docker ps` showed:
```
CONTAINER ID   IMAGE                                               COMMAND                  CREATED        STATUS        PORTS                                                                               NAMES
e27f9145aeb6   zwavejs/zwavejs2mqtt:latest                         "docker-entrypoint.s…"   2 hours ago    Up 2 hours    0.0.0.0:49176->3000/tcp, 0.0.0.0:49175->8091/tcp                                    z-wave-js-server
```
...so of course, I couldn't access it on port 8091.  I adjusted my docker-compose yaml to specify the host port.  Thanks!
