### ISSUE TITLE
[bug] Cannot remove association to not existing device

### ISSUE THREAD

**Issue by calveth** [zwave-js/zwavejs2mqtt#1474]
### Version

**Checklist:**

- [x] I am **not** using HomeAssistant. **Or:** a developer has told me to come here.
- [x] I have checked the troubleshooting section and my problem is **not** described there.
- [ ] I have read the changelog problem was **not** mentioned there.

Build/Run method

- [x] Docker
- [ ] PKG
- [ ] Snap package
- [ ] Manually built (git clone - yarn install - yarn run build )

zwavejs2mqtt version: 5.4.2
zwave-js version: 8.0.5

### Describe the bug
I have one zwave device, which is associated with not existing device. I would like to remove this association, but this action results in an error (see log output from below).

```
2021-07-23 17:43:21.507 INFO ZWAVE: Calling api removeAssociations with args: [
{ nodeId: 14, endpoint: 0 },
3,
[ { nodeId: 41 }, [length]: 1 ],
[length]: 3
]
2021-07-23 17:43:21.510 INFO ZWAVE: Assocaitions: Removing associations from Node 14 Group 3: [ { nodeId: 41 }, [length]: 1 ]
2021-07-23 17:43:21.513 WARN ZWAVE: Error while removing associations from Node 14: Group 3 does not exist on node 14
2021-07-23 17:43:21.515 INFO ZWAVE: Success zwave api call removeAssociations undefined
2021-07-23 17:43:22.511 INFO ZWAVE: Calling api getAssociations with args: [ 14, [length]: 1 ]
2021-07-23 17:43:22.517 INFO ZWAVE: Success zwave api call getAssociations [
{ endpoint: 0, groupId: 3, nodeId: 41, targetEndpoint: undefined },
[length]: 1
]
```

### To Reproduce

1. Go to device
2. Click on groups
3. Click on trash icon of the regarding association
4. See error in the debug window

### Expected behavior

The association has to be deleted (regardless of target device status).

**Comment by robertsLando** [comment]
@AlCalzone ?

**Comment by AlCalzone** [comment]
The error message says that you're trying to remove an association from an association group that does not exist on Node 14. Please share your cache file `<homeid>.values.jsonl`, so I can figure out how this situation appeared.

**Comment by calveth** [comment]
Meanwhile i found a workaround and deleted the association using FHEM. You can look at the file, maybe it will be helpfull for you. 
[home_id.values.jsonl.zip](https://github.com/zwave-js/zwavejs2mqtt/files/6880113/home_id.values.jsonl.zip)

**Comment by calveth** [comment]
see previous comment
