### ISSUE TITLE
[question] set value with mqtt

### ISSUE THREAD

**Issue by mpuff** [zwave-js/zwavejs2mqtt#1477]
hello,

i have set in the gateway settings for topic type **named topic** and for payload type **just value**.

i get the status from mqtt:

zwave/Kleiderzimmer/Thermostat_Kleiderzimmer/thermostat_setpoint/endpoint_0/setpoint/1
21

than i tried to send a value:

zwave/Kleiderzimmer/Thermostat_Kleiderzimmer/thermostat_setpoint/endpoint_0/setpoint/1/set
19

but this does not work, what do i need to change in the publish topic?

**Comment by robertsLando** [comment]
what's the payload type you are using? If you set the json time value you should send a json. BTW what z2m version are you using?

**Comment by mpuff** [comment]
Payload type is just value, I use the latest version of zwavejs

**Comment by robertsLando** [comment]
Is that value writeable? Can you set it from the UI?

**Comment by mpuff** [comment]
![image](https://user-images.githubusercontent.com/13885599/126963625-53aa025e-7553-4f78-a46a-e1dd33ae4b06.jpeg)

**Comment by mpuff** [comment]
I can change it in the gui

**Comment by mpuff** [comment]
![2021-07-26_16h56_04](https://user-images.githubusercontent.com/13885599/127010903-a85e876d-c96d-4595-b598-29fa606aa271.png)

i get the current value of the thermostat with the **zwave/Bad_OG/Thermostat_Bad_OG/thermostat_setpoint/endpoint_0/setpoint/1** topic.

when i send a value like 20 with /set at the end of the topic, the value doesnt change.

![2021-07-26_16h56_28](https://user-images.githubusercontent.com/13885599/127011120-bb3ae33a-ee7c-4403-ba6a-23ddedc103f7.png)

**Comment by robertsLando** [comment]
What z2m version are you using? there was a fix in latest versions that fixed a bug in the set

**Comment by mpuff** [comment]
5.3.0

**Comment by mpuff** [comment]
with 5.4.2 i get a respond with the current value on the topic, but in the gui, it is the value that was before

**Comment by mpuff** [comment]
![2021-07-26_18h33_18](https://user-images.githubusercontent.com/13885599/127025488-aadd38f6-b17c-4d49-b886-a3f50e5859ea.png)

**Comment by mpuff** [comment]
and when i wait a little bit, i get again the value 19 back
so the value is not written

**Comment by robertsLando** [comment]
Can you share z2m debug logs please? You should see in logs 'Message received on' ... And also on startup you should see logs like 'Subscribed to <valueId> changes'

**Comment by mpuff** [comment]
now it is working, i also need to clear the browser cache

**Comment by mpuff** [comment]
thank you for the help
