### ISSUE TITLE
[feat] add a brief explainer for zwave2mqtt users

### ISSUE THREAD

**Issue by phrz** [zwave-js/zwavejs2mqtt#149]
**Is your feature request related to a problem? Please describe.**
I was kindly pointed to this repo by [the author](https://github.com/OpenZWave/Zwave2Mqtt/issues/257#issuecomment-753451720), but arriving here left me unsure about this project's relationship to zwave2mqtt, and the migration pathway. By default, in the Home Assistant and Homebridge automation worlds, zwave2mqtt gets brought up, and I would suggest those users need more background information about this project. 

**Describe the solution you'd like**
Add a highly visible FAQ to the README that answers some of the following, assuming the audience is familiar with zwave2mqtt:

1. What differentiates this project from zwave2mqtt: is it a frontend rewrite? Does it rely on a different Z-Wave implementation?
2. Is this project going to replace zwave2mqtt in the long run?
3. Is this project ready for stable daily use if it is being recommended to users? I only see an alpha release. 
4. Is there a way to migrate from zwave2mqtt without starting over at naming things and having auto-named topics? I'm interested but do not know where to jump. 
5. Are there any breaking changes zwave2mqtt users should know about?
6. Are there any new features that would convince a zwave2mqtt user to switch?

**Describe alternatives you've considered**
None, I have not been able to find context that would otherwise help me understand the applicability of this project to my use case. 

**Additional context**
See the GitHub issue linked above.

**Comment by robertsLando** [comment]
@phrz You can find most answers:

https://zwave-js.github.io/zwavejs2mqtt/#/getting-started/why
https://zwave-js.github.io/zwavejs2mqtt/#/guide/migrating

It is started to completely replace the old Zwave2Mqtt that is based on OZW. The reason of this switch is well explained in the `why` section. About stability it is stable enought, it's alpha for now but all the features of z2m are already available. 

Hass discovery works better and now also climates devices are auto discovered but there is a work in progress on this to integrate it with an hass addon to improve discovery even more. Also zwavejs allows to send OTA updates to devices directly from the ui

This is essentially the future and z2m the past

**Comment by phrz** [comment]
Thank you for taking the time to clarify! Apologies for not seeing the getting started page, I did not see the website's menu button while on mobile. And thanks for your work on this great project!
