### ISSUE TITLE
[bug] README missing info

### ISSUE THREAD

**Issue by ikkemaniac** [zwave-js/zwavejs2mqtt#152]
**Version**

**Describe the bug**
None of the readme modules are linked/loaded. I need to browse to the docs folder and open subfolders/md files to read the info

**To Reproduce**
[click](https://zwave-js.github.io/zwavejs2mqtt/#/) and [click](https://github.com/zwave-js/zwavejs2mqtt)

**Expected behavior**
Show all the readme

**Comment by billiaz** [comment]
@ikkemaniac I cannot reproduce it, can you give some more details on how the problem arrises?

**Comment by robertsLando** [comment]
@ikkemaniac Because I think you are exloring docs from github and not from https://zwave-js.github.io/zwavejs2mqtt/#/

**Comment by ikkemaniac** [comment]
Right, both links i provided i don't see the full docs. Turns out after further testing that the io domain issue is on my side with all the js that gets loaded, sorry. 

On the GH page only readme.md get's loaded. There's a ton of badges and links to other stuff but no link or explanation at all where to go for documentation, found the domain via google.

**Comment by robertsLando** [comment]
> There's a ton of badges and links to other stuff but no link or explanation at all where to go for documentation, found the domain via google.

The side menu?
