### ISSUE TITLE
[bug] Gateways mapping of ON/OFF does not match values expected by target

### ISSUE THREAD

**Issue by rickoman** [zwave-js/zwavejs2mqtt#1540]
### Version

**Checklist:**

- [x] I am **not** using HomeAssistant. **Or:** a developer has told me to come here.
- [x] I have checked the troubleshooting section and my problem is **not** described there.
- [x] I have read the changelog problem was **not** mentioned there.

Build/Run method

- [x] Docker

zwavejs2mqtt version: 5.4.2
zwave-js version: 8.0.5

### Describe the bug

I have an Inovelli LZW31 Dimmer.  I would like to send .../set/ON or .../set/OFF to turn the dimmer to full on or off.  

I thought I would have to write a 'Parse Send/Recv' function to handle this but it appears the Gateway is already mapping ON/OFF and TRUE/FALSE. 

The Gateway maps ON=255 OFF=0  and TRUE=255 FALSE=0

The Inovelli LZZW31 uses 0 for OFF and 99 for ON

### Expected behavior
The Multilevel Switch Target has a min/max value.  Shouldn't the Gateway map ON/OFF TRUE/FALSE to the min/max for that target?

Is there a list of things that get auto-magically mapped by the Gateway?

```
{
  id: '4-38-0-targetValue',
  nodeId: 4,
  commandClass: 38,
  commandClassName: 'Multilevel Switch',
  endpoint: 0,
  property: 'targetValue',
  propertyName: 'targetValue',
  type: 'number',
  readable: true,
  writeable: true,
  label: 'Target value',
  stateless: false,
  min: 0,
  max: 99,
  list: false,
  value: 0,
  lastUpdate: 1628104843948,
  conf: [Object]
}
```

**Comment by robertsLando** [comment]
I dunno if mapping to min max is always good, based on my experience 255 means turn on to latest value (the value it was before going off), it's strange your device isn't working like that. You could create a parseReceive function that maps 255 to 99?

**Comment by rickoman** [comment]
After sleeping on this I agree. I think parse send/recv just need additional documentation/examples.

**Comment by robertsLando** [comment]
The function has this signature: `function(value,valueId,node,logger)`

It means you should do something like: 

```
return value === 255 ? 99 : value
```

And you are done :)
