### ISSUE TITLE
[fix] Use dfifferent icon for clear node/location text fields

### ISSUE THREAD

**Issue by LordMike** [zwave-js/zwavejs2mqtt#1542]
### Version

**Checklist:**

- [x] I am **not** using HomeAssistant. **Or:** a developer has told me to come here.
- [x] I have checked the troubleshooting section and my problem is **not** described there.
- [x] I have read the changelog problem was **not** mentioned there.

_this is not entirely true, I use HASS, but I don't think it is relevant here_

Build/Run method

- [x] Docker
- [ ] PKG
- [ ] Snap package
- [ ] Manually built (git clone - yarn install - yarn run build )

zwavejs2mqtt: 5.4.3
zwave-js: 8.0.6

### Describe the bug

The little "x" in text fields usually indicates to me that clicking it will clear the text field. This is not the case in ZJ2M.

### To Reproduce

![recording](https://user-images.githubusercontent.com/1027111/128390504-6b5bc097-aa24-4a55-b6b8-8475d7845414.gif)

### Expected behavior

"x" clears the field.

### Additional context

N/A

**Comment by robertsLando** [comment]
@LordMike That's on purpose, the reset restores to the actual value

**Comment by LordMike** [comment]
Ooh. Ok. :)

Might I suggest a different icon, like a reset / revert icon. Like below - not sure which icon package was used in zjs2m. 

https://www.iconfinder.com/icons/769751/arrow_rotate_undo_revert_icon
