### ISSUE TITLE
All nodes showing "Unknown manufacturer"  "Unknown product"

### ISSUE THREAD

**Issue by rvb89** [zwave-js/zwavejs2mqtt#1562]
Hello,
I have a recent snap installation of zwavejs2mqtt, version 5.4.5.0ad7537 and zwave-js: 8.0.8
And tonight when I checked the control panel I saw that all the nodes shows "Unknown manufacturer"  "Unknown product".
I tried to launch re-interview but no success.
I also shutdown the machine and left it a few minutes turned off to leave the time to the zwave controller to turn off and re launch the interview but no success, it seems the nodes are working.

when re-doing the interview the logs show for example:
`2021-08-14 01:30:40.691 INFO ZWAVE: Node 27 ready: Unknown manufacturer 0x019b - Unknown product 0x0001 (0x0001)
`
Also it keeps saying 8.0.9-20210810 is available but launching the update has no effect.

how can I fix this ?
Thanks

**Comment by rvb89** [comment]
From the logs I think I found the issue, the config files seems to be missing but I have no idea, how to restore them?
[zwavejs_2021-08-15.log](https://github.com/zwave-js/zwavejs2mqtt/files/6988618/zwavejs_2021-08-15.log)

Thanks

**Comment by nicolaasuni** [comment]
I experienced the same issue and looking at the /var/log/syslog I found the following error:

```
Error loading device config /var/snap/zwavejs2mqtt/183/.ext-config/devices/0x0086/zw120.json: ZWaveError: Tried to import config file "/var/snap/zwavejs2mqtt/183/.ext-config/devices/0x0086/zw120.json" outside of root directory "/var/snap/zwavejs2mqtt/179/.ext-config/devices"!
```

So I fixed the issue by running the following commands:

```
sudo sed -i 's|zwavejs2mqtt/179|zwavejs2mqtt/183|g' /var/snap/zwavejs2mqtt/183/.ext-config/devices/index.json
sudo snap restart zwavejs2mqtt
```

**Comment by rvb89** [comment]
Thanks it works now!
