### ISSUE TITLE
Monoprice (Vision) ZM1701 Door Lock issue

### ISSUE THREAD

**Issue by danielbrunt57** [zwave-js/zwavejs2mqtt#1570]
### Version

**Checklist:**

- [x] I am **not** using HomeAssistant. **Or:** a developer has told me to come here.
- [x] I have checked the troubleshooting section and my problem is **not** described there.
- [x] I have read the changelog problem was **not** mentioned there.

Build/Run method

- [x] Docker
- [ ] PKG
- [ ] Snap package
- [ ] Manually built (git clone - yarn install - yarn run build )

zwavejs2mqtt version: 0.23.4
zwave-js version: 
Driver Version: 8.0.8
Server Version: 1.9.2
Home ID: 3328259840
Nodes ready: 23 / 23

### Describe the bug

Monoprice/Vision ZM1701 Door Lock is not updating status change when door lock is operated via the handle or the keypad on the door lock.  I have another door lock (Kwikset) which **is** working so that tends to rule out my controller. This device has worked properly for years in HomeSeer, for a brief while in OpenZWave, then ZWaveJS, then ZWaveJS2MQTT (door lock logging not working but door lock/unlock was being reported), then HomeSeer and now again in ZWaveJS2MQTT where door lock logging is still not working but this time I just noticed that operation at the lock via inside handle or outside keypad is not being seen by ZWaveJS2MQTT.  It does respond to commands to lock/unlock and once in sync, those work okay. I have set the log levels to "silly" but there is nothing in there when I operate the lock at the door.

### Additional context

![image](https://user-images.githubusercontent.com/49846893/129519432-388da0f9-29ed-4216-a62c-014d1f872d2f.png)

**Comment by AlCalzone** [comment]
Please upload a driver log (loglevel "debug") where you operate the lock.

**Comment by danielbrunt57** [comment]
![image](https://user-images.githubusercontent.com/49846893/129849637-9a311485-c95b-424f-b290-84bfff910f18.png)
[zwavejs_2021-08-17.log](https://github.com/zwave-js/zwavejs2mqtt/files/7005049/zwavejs_2021-08-17.log)

**Comment by danielbrunt57** [comment]
Here is a log where I unlocked the door via Z-Wave and then went to the dock and manually locked it.  If I click refresh in the UI panel, the status updates...
![image](https://user-images.githubusercontent.com/49846893/129851738-7fb2cae7-63ed-429a-ab50-5f510881dc17.png)
[zwavejs_2021-08-17.log](https://github.com/zwave-js/zwavejs2mqtt/files/7005218/zwavejs_2021-08-17.log)

**Comment by AlCalzone** [comment]
Can you share the cache file `<homeid>.json`? If I understand the manual correctly, the device doesn't support associations.
If that's the case, Homeseer probably polled it regularly to get the updated status. `zwave-js` doesn't do that by default, but you can configure it in zwavejs2mqtt somewhere.

**Comment by danielbrunt57** [comment]
Here it is...
[c6613700.json.txt](https://github.com/zwave-js/zwavejs2mqtt/files/7008537/c6613700.json.txt)
FYI, the status update in Homeseer is instantaneous so I doubt it is a polled status change.
For reference, here is the node config in Homeseer...
![image](https://user-images.githubusercontent.com/49846893/129932353-e3c21175-a4ad-4249-a34d-d7acb961e221.png)
where it looks like association is supported in secure mode.  I am not sure if I re-added it (this time around) securely or not. Let me re-add it to ZWJS securely...
Okay, It's secure this time but no change in behavior.  Here's the new cache file...
[c6613700-new.json.txt](https://github.com/zwave-js/zwavejs2mqtt/files/7008642/c6613700-new.json.txt)

**Comment by AlCalzone** [comment]
Ok, that looks normal. How are the associations configured in zwave-js? If you also have Homeseer to compare that would be really helpful.

**Comment by danielbrunt57** [comment]
It had no associations...
![image](https://user-images.githubusercontent.com/49846893/129977125-d77bb551-15c9-4ae9-a327-a9ec3afbe1e4.png)

I added Node 0, Unnamed Group 1  and after clicking refresh it looks like this:
![image](https://user-images.githubusercontent.com/49846893/129977560-49a88c49-69a6-4adf-884c-eff97649bcbe.png)
and the status is now updating when I operate the lock at the door!

Thanks for pointing me in the right direction!!

**Comment by danielbrunt57** [comment]
One more thing,,,

It supports CC Door Lock Logging and hopefully that will be supported sometime in the not too distant future by ZWJS.  The Kwikset 910 I have supports ALARM which is reported by the lock to the controller in ZWJS with the alarm level indicating the new state, which I templated into a log sensor.  The 1701 does not have that and in Homeseer the Kwikset reported the alarm log level and the log record automatically updated.  For the 1701 since there's no CC ALARM, I had to create an automation triggered by the lock changing states and issue a GET LATEST RECORD to the logging "feature" of the parent which then retrieved and updated the latest log record.  Any idea if anyone is thinking about door lock logging?  I've already added my vote to the wish list for this.

**Comment by AlCalzone** [comment]
> It had no associations...

That's weird. zwave-js should set up associations if they are missing. If you don't mind, I'd be interested in seeing a driver log of this: Delete association, then re-interview.

>  I've already added my vote to the wish list for this.

I'll get to it at some point.

**Comment by danielbrunt57** [comment]
Done.

I deleted the old log, enabled logging, interviewed the node and waited about 30-40 seconds after the interview while refreshing the group associations where nothing showed up.  I then re-added the group and then disabled logging.

Thanks,
Daniel

**Comment by AlCalzone** [comment]
You need to upload files via the Github UI. Attaching them to emails doesn't work.

**Comment by danielbrunt57** [comment]
Sorry...got lazy!

[zwavejs_2021-08-18.log](https://github.com/zwave-js/zwavejs2mqtt/files/7012625/zwavejs_2021-08-18.log)

**Comment by AlCalzone** [comment]
Ok, thanks. The node doesn't support Z-Wave+, so we cannot automatically assume that Association Group 1 is the lifeline. I'll update the config file which should fix this going forward.

**Comment by danielbrunt57** [comment]
Thank you!
