### ISSUE TITLE
[feat] Try to look up manufacturer name if device doesn't have a config file

### ISSUE THREAD

**Issue by AlCalzone** [zwave-js/zwavejs2mqtt#1571]
Instead of displaying "unknown manufacturer 0x1234", z2m should use this method to try and look up the manufacturer name first:
https://zwave-js.github.io/node-zwave-js/#/api/config-manager?id=lookupmanufacturer
which is exposed via the driver's `configManager` instance.

If that doesn't return anything, falling back to "unknown manufacturer" is fine IMO.

**Comment by AlCalzone** [comment]
See commit comment. I don't think your fix does what it's supposed to.

**Comment by robertsLando** [comment]
Fixed now, sorry
