### ISSUE TITLE
[question] Woundering what the roadmap for supporting S2 is now that zwave-js supports it.

### ISSUE THREAD

**Issue by asucrews** [zwave-js/zwavejs2mqtt#1574]
Hello, 

I am wondering what the roadmap for S2 support would looks like now that ZWave-JS supports it.  The reason I ask is because i thought the latest release would support it but looks like was wrong. 

I get this error when I tried a know S2 sensor.
Driver: Node 023 supports Security S2, but no network key was configured. Continuing interview non-securely. 
https://github.com/home-assistant/core/issues/54774

**Comment by thecobra666** [comment]
Not supported yet, the zwavejs version is still older then the one with s2 in it. Let's hope a new build comes soon.

**Comment by robertsLando** [comment]
I'm on vacation now, will add the support once I come back on Monday

**Comment by asucrews** [comment]
So wonderful news! I hope you enjoyed your vacation!

**Comment by robertsLando** [comment]
Closed by #1585
