### ISSUE TITLE
[HASS] quotes needed for mode_state_template

### ISSUE THREAD

**Issue by klim123123** [zwave-js/zwavejs2mqtt#1578]
zwavejs2mqtt: 5.4.6
zwave-js: 8.1.1

HASS MQQT Discovery can't recognize thermostat mode status, because quotes need to be added.

in config created by zwavejs2mqtt i found:
"mode_state_template": "{{ {0: "off", 1: "heat"}[value] | default('off') }}",

when value changing from 0 to 1, there is no any reaction.

it's should be:
mode_state_template: '{{ {"0": "off", "1": "heat"}[value] | default(''off'') }}'
(need to add quotes near 0 and 1)

after i add quotes, thermostat works fine.

![image](https://user-images.githubusercontent.com/64870895/130148522-3412a99d-fd3c-44f8-83d1-fe65465f2467.png)

![image](https://user-images.githubusercontent.com/64870895/130149744-adbb5e1d-98ae-4204-8d1e-b00343ad3626.png)

![image](https://user-images.githubusercontent.com/64870895/130149856-c9057d5d-411c-41b2-9b07-0585397c954c.png)

full config created by zwavejs2mqtt 
{
  "min_temp": 5,
  "max_temp": 40,
  "temp_step": 0.5,
  "modes": [
    "off",
    "heat"
  ],
  **"mode_state_template": "{{ {0: \"off\", 1: \"heat\"}[value] | default('off') }}",**
  "current_temperature_topic": "zwave/Zal/Fibaro_HC_Zal1/49/2/Air_temperature",
  "current_temperature_template": "{{ value }}",
  "temperature_state_topic": "zwave/Zal/Fibaro_HC_Zal1/67/0/setpoint/1",
  "temperature_state_template": "{{ value }}",
  "temperature_command_topic": "zwave/Zal/Fibaro_HC_Zal1/67/0/setpoint/1/set",
  "mode_state_topic": "zwave/Zal/Fibaro_HC_Zal1/64/0/mode",
  "mode_command_topic": "zwave/Zal/Fibaro_HC_Zal1/64/0/mode/set",
  "temperature_unit": "C",
  "precision": 0.1,
  "device": {
    "identifiers": [
      "zwavejs2mqtt_0xeca59111_node5"
    ],
    "manufacturer": "Fibargroup",
    "model": "Thermostatic Valve (FGT001)",
    "name": "Zal-Fibaro HC Zal1",
    "sw_version": "4.7"
  },
  "name": "Zal-Fibaro HC Zal1_climate",
  "unique_id": "zwavejs2mqtt_0xeca59000_Node5_climate"
}

**Comment by robertsLando** [comment]
I remember that I had to remove quotes in order to fix another problem in the past, btw I can add them back if needed

**Comment by klim123123** [comment]
In this case, looks like it's needed. Please add them back. Thank you!

> I remember that I had to remove quotes in order to fix another problem in the past, btw I can add them back if needed

**Comment by robertsLando** [comment]
I have changed this, if someone will have breaking changes I will revert my commit

**Comment by matejdro** [comment]
I'm experiencing same issue with the 5.8.0, even though quotes are there:

` "mode_state_template" : "{{ {\"0\": \"off\", \"1\": \"heat\", \"11\": \"cool\"}[value_json.value] | default('off') }}"`

Maybe Home Assistant does not unescape the quotes well? What if we just switched to the single quotes like the example in the first post?
