### ISSUE TITLE
[bug] No "currentValue" update when Fibaro Roller Shuter FGR223

### ISSUE THREAD

**Issue by ODINServ** [zwave-js/zwavejs2mqtt#16]
Hi,

I am migrating from openhab zwave implementation via zwave2mqtt to zwavejs2mqtt (I was pointed to here via an other issue).

My environment:
I am running zwavejs2mqtt ("patched" dev image see #15) in a docker (podman) container on my linux pc.
For testing purposes i've removed one of my Firabro Roller Shutter 3 units (FGR223) from the wall and put it next to me.

I have a Aeotec Z‐Stick Gen5 USB Controller, and paired to only one FGR223 for the moment.

My problem:
No 38/1/currentValue update when movement stops when: 
* I send a level request to the "zwavejs2mqtt/2/38/1/targetValue/set" topic i only get one position update back in the "zwavejs2mqtt/2/38/1/currentValue" topic when movement starts.
* I send a UP or DOWN or STOP (false) to the corresponding topics, i also don't see a current value beeing reported (also no update when movement starts).

See logs:
* Level change from position 99 -> 80 -> 60 -> 40, the next level request is send some seconds after i hear the relay click to stop.
[99-80-60-40.log](https://github.com/zwave-js/zwavejs2mqtt/files/5537333/99-80-60-40.log)

* Sending "UP" and STOP to the UP topic.
[log-up-stop.log](https://github.com/zwave-js/zwavejs2mqtt/files/5537334/log-up-stop.log)

My analysis:
My feeling is that this might be a OpenZwave issue since it seems like the same behavior i have in openhab (not sure if that is actually OpenZwave, but looks pretty similar with the zwave-xml files), but never the less.
Or maby the device just not reports when it is done, but do see a electricity report update after a second or two after the relay clicks.

Question:
I was also wondering if there is an work-around available by the means of a "/get" on the topic so that the controller will re-request the value from the device.
Why, because if i restart the zwavejs2mqtt container, i do get the correct value in the currentValue topic.

Thnx!

**Comment by AlCalzone** [comment]
> My feeling is that this might be a OpenZwave

zwavejs2mqtt does not use OpenZWave.

> Level change from position 99 -> 80 -> 60 -> 40

```
14:44:49.381 DRIVER « [Node 002] [REQ] [ApplicationCommand]
                      └─[MultiChannelCCCommandEncapsulation]
                        │ source:      1
                        │ destination: 0
                        └─[SupervisionCCReport]
                            session id:          35
                            more updates follow: false
                            status:              Fail
                            duration:            [Duration: 0seconds]
```
I didn't see a single SupervisionCCReport that had status `Success` in that log, so something is fishy. Might be worth to request an update in the failure case too - the driver doesn't do this yet.

> Sending "UP" and STOP to the UP topic.

AFAIK with StartLevelChange it is not possible to get automatic reports when the level change is completed. For StopLevelChange, it could make sense to request an update after the success report.

**Comment by ODINServ** [comment]
> zwavejs2mqtt does not use OpenZWave.
Ah good to know!, i do like the new log format as well.

From the zwave2mqtt issue:
> That's Roller Shutter 3, isn't it? AFAIK it should be controlled with the Supervision CC which lets us know when the motor has stopped. If that's not working, something must have broken it, because it 100% worked a while back.

And this issue:
> I didn't see a single SupervisionCCReport that had status Success in that log, so something is fishy

I think I've found the fish .. well in my (test) case there is no motor ..
So i've also disabled the Motor operation detection (112/0/155) parameter.., which did work with the zwave2mqtt version, to have at least my sliders updated in openhab..
 to 0..

I'd reconnect the FGR223 to the blind and put that back to the original 10 watt value..
And now i do see the Supervision reports and it now works like a charm!

I think that is called a user error?
It could be improved, but in i guess also not a valid use case (at least in Roller blind mode when the motor has build in end switches..)

Thanks for Fishing at least..

**Comment by robertsLando** [comment]
Closing this so :+1:
