### ISSUE TITLE
DSK PIN on small screens doesn't display correctly

### ISSUE THREAD

**Issue by tsoslow** [zwave-js/zwavejs2mqtt#1617]
### Version

**Checklist:**

- [x] I am **not** using HomeAssistant. **Or:** a developer has told me to come here.
- [x] I have checked the troubleshooting section and my problem is **not** described there.
- [x] I have read the changelog problem was **not** mentioned there.

Build/Run method

- [x] Docker
- [ ] PKG
- [ ] Snap package
- [ ] Manually built (git clone - yarn install - yarn run build )

zwavejs2mqtt version: 5.5.1
zwave-js version: 8.2.1

### Describe the bug

Interface for entering DSK PIN on small screens (like iPhone) is pretty bad. The whole DSK number does not fit on the screen and there does not appear to be a place to enter the PIN. When entering the PIN you cannot actually see the number. Also the form allows all text, it would be easier if it explicitly only allowed numbers.

### To Reproduce

1. Login to zwavejs2mqtt on a small screen
2. Enter inclusion mode
3. Add a device with S2 security
4. View screen with DSK PIN entry form

### Expected behavior

For small screens, it would probably make sense to split up into 5 digit numbers so that you can more easily see the entire number. The PIN definitely needs to be on its own line. The input tag should also be `type="number"` so that mobile keyboards only show numbers for entry.

### Additional context

See screenshot for additional information
![dsk-iphone](https://user-images.githubusercontent.com/1187202/131064474-0cac578b-f43a-487d-9a26-10aa89d668d2.jpg)

**Comment by libby2cm** [comment]
Yes, this is a problem on web and mobile app.  Have to haul a laptop around to do s2 enrollments on devices.

**Comment by robertsLando** [comment]
Fixed in latest version
