### ISSUE TITLE
[bug] LZW30-SN unable to change local protection via zwavejs2mqtt

### ISSUE THREAD

**Issue by nmsousa76** [zwave-js/zwavejs2mqtt#1618]
### Version

**Checklist:**

- [x] I am **not** using HomeAssistant. **Or:** a developer has told me to come here.
- [x] I have checked the troubleshooting section and my problem is **not** described there.
- [x] I have read the changelog problem was **not** mentioned there.

Build/Run method

- [ ] Docker
- [ ] PKG
- [ ] Snap package
- [ ] Manually built (git clone - yarn install - yarn run build )

zwavejs2mqtt version: zwavejs2mqtt: 5.5.1
zwave-js: 8.2.1

Unable to change the local protection settings for LZW30-SN (all other Models of Inovelli seem to be fine). All values are showing up as unknown and are unable to be defined.

![image](https://user-images.githubusercontent.com/65356035/131062950-cb1732c1-90ac-426a-9096-48e610166693.png)

### Expected behavior

This is a screenshot from a working from a LZW31-SN
![image](https://user-images.githubusercontent.com/65356035/131066947-7fd97245-15b5-4e27-a00e-da1054da64cf.png)

### Additional context

Turning on silly logging and outputting to file, broke my zwave network.   I will try to upload the logs once I get environment stable again.

**Comment by robertsLando** [comment]
Did you try to re-interview your device? Seems a problem with it's configuration load

**Comment by nmsousa76** [comment]
Yes reinterview was done.   upgraded firmware, tested on clean machine with only a single device.   issue seems to be device specific.    Looks like the reinterview process is pulling back values of 0x08, 0x09, 0x0a instead 0x00, 0x01, and 0x02.   

I have opened a case with inovelli as well.  (https://support.inovelli.com/portal/en/ticket/407409000033235320) and you can use LZW30-SN unable to change local protection via zwavejs2mqtt home-assistant/core#55305 for a further details on the issue.

**Comment by blhoward2** [comment]
Closing this issue, as it’s already reported at the driver and cannot be fixed on our end. 

https://github.com/zwave-js/node-zwave-js/issues/3252
