### ISSUE TITLE
Central scene commands not recognized with S2 secure switch

### ISSUE THREAD

**Issue by mwav3** [zwave-js/zwavejs2mqtt#1620]
**Checklist:**

- [ ] I am **not** using HomeAssistant. **Or:** a developer has told me to come here. - I am using Home Assistant but problem exists outside of Home Assistant.  Home Assistant's docker container was stopped throughout this process so as not to interfere.
- [ x] I have checked the troubleshooting section and my problem is **not** described there.
- [ x] I have read the changelog problem was **not** mentioned there.

Build/Run method

- [ x] Docker
- [ ] PKG
- [ ] Snap package
- [ ] Manually built (git clone - yarn install - yarn run build )

zwavejs2mqtt version: 5.5.1
zwave-js version: 8.2.1

### Describe the bug

When a Jasco Enbrighten 46203 switch is included with S2 security, the central scene commands created by double and triple taps are no longer recognized.  When attempted to activate central scene commands at the switch the log shows - "Dropping message because it could not be deserialized".  Other control of the switch, including on/off, dimming, and status, works fine with S2 security but the central scene commands are not recognized.  The switch functions fine when included with no security and all central scene commands generated by double and triple taps are recognized.  

### To Reproduce

Exclude non-secure switch
Include switch with S2 inclusion and enter valid DSK
Attempt double and triple taps at the switch - not recognized and log error results.

### Expected behavior

All central scene controls are deserialized and recognized when the switch is included with S2 inclusion.

### Additional context

The most relevant logs are included in the ZwaveJS logs.  On the included logs the following events match the times:
Node 43, GE dimmer switch was excluded at 15:12
The same dimmer switch was included with S2 security at 15:13 as node 45
Various double and triple taps were attempted at 15:16 with log errors showing:
2021-08-27T15:16:00.733Z DRIVER   Dropping message because it could not be deserialized: SupervisionCCGet: deser
                                                              ialization not implemented
An identical model switch at Node 44 was tested which was not included securely at 15:17.  All central scene commands were recognized successfully
The s2 included switch at node 45 was excluded at 15:20
The switch was re-included without security and became node 46
Central scene commands were tested on node 46 at 15:22 and worked without issues

See attached logs and files.  Please let me know if you need any other info
[zwavejs2mqtt.log](https://github.com/zwave-js/zwavejs2mqtt/files/7068166/zwavejs2mqtt.log)
[zwavejs_2021-08-27.log](https://github.com/zwave-js/zwavejs2mqtt/files/7068167/zwavejs_2021-08-27.log)
[node_46.log](https://github.com/zwave-js/zwavejs2mqtt/files/7068172/node_46.log)
Had to rename the .json file to .log to attach

**Comment by kpine** [comment]
This is already captured at https://github.com/zwave-js/node-zwave-js/issues/3201

**Comment by mwav3** [comment]
Ok I'll close it since it's a duplicate issue
