### ISSUE TITLE
[feat] - exportable zwavejs log in the UI (for Docker)

### ISSUE THREAD

**Issue by jaburges** [zwave-js/zwavejs2mqtt#163]
**Is your feature request related to a problem? Please describe.**
Especially in the early days accessing the log regularly to debug is painful. 
Referring specifically to the Zwavejs (not the zwavejs2mqtt log)

**Describe the solution you'd like**
someway of either writing the log to the `/store` mapped volume (not /bin) - or symlink to the bin folder to a bin folder in the /store directory
or a way to export the log from the UI to the root docker folder (or as its a web UI trigger a download?)

**Describe alternatives you've considered**
mapping the volume works, but is unlikely to be something everyone can do. I'm assuming the more people that use this the more issues will be discovered, so an easy way of dealing with it would help out.

**Comment by scyto** [comment]
i like the idea of all longs being in one place and easily accessible (there are a couple of other issues and prs floating around for the zwave log).

it would be great if the UI had a place for each log with say a tail of each log of 50 or 100 (or whatever) lines and that this refreshed as needed and an export button for folks who really hate command line.

**Comment by robertsLando** [comment]
I'm thinking about a way to access everything on store folder, with a basic editor

**Comment by blhoward2** [comment]
> I'm thinking about a way to access everything on store folder, with a basic editor

Just please make sure it isn't super resource intensive! I tried running the vscode-server within HA and it makes my Pi 4 sit proc sit at ~85% vs 5% normally.

**Comment by robertsLando** [comment]
@blhoward2 For now I have added a button to export them, the problem is that there is no way to delete them atm

**Comment by jaburges** [comment]
What's the desired behavior of the average user?
1. Spend 99% in the UI and export/ download the log when there is an issue?
2. Rummage in the docker mapped folder?

I'm assuming ideally, once set up it would be best to keep the user in the UI.

**Comment by robertsLando** [comment]
For sure the answer is 1, I know this
