### ISSUE TITLE
[feat] Show battery status on nodes table

### ISSUE THREAD

**Issue by ahochsteger** [zwave-js/zwavejs2mqtt#1638]
**Is your feature request related to a problem? Please describe.**
When doing device maintenance of battery-powered device you have to look into the details of every device to see if the battery is still in a good state.

**Describe the solution you'd like**
Showing the battery state on the nodes table gives a quick overview and lets you sort by percentage to quickly see which have to be replaced.

**Describe alternatives you've considered**
Use scripts to extract the information from the device data (not user-friendly).

**Additional context**
-

**Comment by robertsLando** [comment]
I'm +1 for this, would you like to submit a PR?

**Comment by ahochsteger** [comment]
@robertsLando, that's my plan, but it may take a bit until I find some time for it ;-).
