### ISSUE TITLE
[question] The status of customDevices.json? 

### ISSUE THREAD

**Issue by ivdimitro** [zwave-js/zwavejs2mqtt#1641]
I read some of the previous tickets and it seems the mqtt will not be focus of future development. It also seems that customDevices.json is currently only supported for mqtt. 
Are there any plans to bring the customDevices.json to the WS integration? 
Are there alternative methods to achieve the same functionality for the WS integration (defining custom entities to be published to HA)?
Thanks.

**Comment by robertsLando** [comment]
> Are there any plans to bring the customDevices.json to the WS integration?

There is no way to do this

> Are there alternative methods to achieve the same functionality for the WS integration (defining custom entities to be published to HA)?

Yes, you could manually define your entities on hass: https://zwave-js.github.io/zwavejs2mqtt/#/guide/homeassistant?id=manually-create-entities

In this scenario you should:

1. On z2m side: Enable zwavejs server and mqtt gateway, disable the mqtt discovery
2. On hass side: add a broker, zwavejs integration and mqtt integration
3. Use values published to mqtt in the manually configured entities like defined in previous docs
