### ISSUE TITLE
[feat] Support S0 only inclusion mode

### ISSUE THREAD

**Issue by pdawg17** [zwave-js/zwavejs2mqtt#1645]
### Is your problem within Home Assistant (Core or Z-Wave JS Integration)?

YES, BUT a Home Assistant developer has told me to come here

### Is your problem within ZWaveJS2MQTT?

YES, BUT a ZWaveJS2MQTT developer has told me to come here

### Checklist

- [X] I have checked the [troubleshooting section](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index) and my problem is **not** described there.

- [X] I have read the [changelog](https://github.com/zwave-js/node-zwave-js/blob/master/CHANGELOG.md) and my problem was **not** mentioned there.

### Describe the bug

What causes the bug?

When I try to incluse the opener, it gets added as a node but with security "None". Therefore, I cannot control the opener since it is not a secure node.

What do you observe?

When starting inclusion, whether I select "force security" or not, it gets added but with security "None"

What did you expect to happen?

This opener does support s0, so I expected it to be added as s0 legacy.

  1. Go to inclusion
  2. Click on start
  3. Click button on opener which starts the inclusion
  4. Screen says "node xx added with security "none"
 

### Device information

Manufacturer: Nortek
Model name: GD00Z-4
Node ID in your network:  currently node 30

### How are you using `node-zwave-js`?

- [ ] `zwavejs2mqtt` Docker image (latest)
- [ ] `zwavejs2mqtt` Docker image (dev)
- [ ] `zwavejs2mqtt` Docker manually built _(please specify branches)_
- [ ] `ioBroker.zwave2` adapter _(please specify version)_
- [X] `HomeAssistant zwave_js` integration  _(please specify version)_
- [ ] `pkg`
- [ ] `node-red-contrib-zwave-js` _(please specify version, double click node to find out)_
- [ ] Manually built from GitHub _(please specify branch)_
- [ ] Other _(please describe)_

### Which branches or versions?

version:
`node-zwave-js` branch: 8.2.1
`zwavejs2mqtt` branch: 5.5.1

### Did you change anything?

no

### Did this work before?

Don't know, this is a new device

### Attach Driver Logfile

[zwavejs_2021-08-30.log](https://github.com/zwave-js/node-zwave-js/files/7079686/zwavejs_2021-08-30.log)

IN LOG FILE UPLOADED, NODE 29 IS WITH SECURITY FORCED AND NODE 30 IS WITHOUT

**Comment by kpine** [comment]
> This workaround no longer works. I just tried to add the device in home assistant's integration using the "use secure inclusion" checkbox" and it did not work.

@dansrogers Are you using HA 2021.9 or 2021.8?
