### ISSUE TITLE
[feat] Allow use of 'Devices values configuration' when MQTT gateway is disabled.

### ISSUE THREAD

**Issue by crkochan** [zwave-js/zwavejs2mqtt#1648]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to leverage [the "Device values configuration" feature](https://zwave-js.github.io/zwavejs2mqtt/#/usage/setup?id=device-values-configuration) in order to apply common device settings for the multiple devices of the same type in my mesh.

The feature seems to be implemented with MQTT in mind, and I'm currently using zwavejs2mqtt with the gateway disabled, using the websocket server to communicate with Home Assistant.

**Describe the solution you'd like**
In a websocket-only configuration, I'd like to be able to manually specify values for a given device and valueId in the control panel UI, with data maintained and sourced from the store location.

**Comment by kpine** [comment]
Click on the "NEW VALUE" button. It will allow you to enable polling for the devices, even with MQTT disabled.

**Comment by crkochan** [comment]
Correct, I can enable polling, but even with it turned on, device configurations are not changed.

Let say I have the following set...

Device | Value | Post Operation | Poll 
-- | -- | -- | -- 
[798-1-1] Red Series Dimmer (Inovelli) | LED Indicator Brightness (112-0-14) | No operation | Interval: 30s 

At the configured interval, I will see in the debug log...
```
2021-09-06 08:04:44.924 INFO ZWAVE: Node 67: value updated: 112-0-14 0 => 0
2021-09-06 08:04:46.301 INFO ZWAVE: Node 68: value updated: 112-0-14 5 => 5
```

Basically, the config value is being set to its existing value. There's no apparent way to specify what I want the config values to be updated on all devices.

I grant you, I may be completely mis-understanding what this feature is supposed to do.

**Comment by robertsLando** [comment]
Please set log level to `debug`, you should see logs like: 

```js
`${vID} will be polled in ${interval} seconds`
```

When polling is setup on startup

**Comment by crkochan** [comment]
Yes, I do see that.

```2021-09-06 09:02:13.636 DEBUG ZWAVE: 138-112-0-14 will be polled in 30 seconds```

It's not that polling is not occurring, it's that there's no changes in the configuration occurring.

The header on the table in the UI states...
```
Add here valueIds specific configurations for each device. This means that if you create an entry here this configuration will be applied to each valueId of each device of the same type in your Network.
```

I can specify the device. I can specify the configuration option that I want to be updated. I cannot specify the value that I want the configuration option to be set to for those devices.

I'll come at it from a different direction and say that I've interpreted the information in the UI and the documentation to mean that the purpose of this table is to be able to automatically set a given configuration option the same way on every identical device in my network. Just as if I'd manually gone to each device in the control panel in turn, expanded their configuration section, and set the configuration option. Do I have that right?

**Comment by robertsLando** [comment]
>  I've interpreted the information in the UI and the documentation to mean that the purpose of this table is to be able to automatically set a given configuration option the same way on every identical device in my network

Nope, the purpose is just to setup some valueId specific settings, like mqtt parse functions and topics, some hass related stuff (just for mqtt discovery) and also polling. What you are asking for could be an interesting feature to add BTW, the problem is that on every startup z2m would send those config values to all your devices and could create some delay in large networks. For this I suggest to use multicast/broadcast commands instead

**Comment by crkochan** [comment]
Ah, got it. Thanks for elaborating.
