### ISSUE TITLE
[bug] ZWAVE-SERVER Error when trying to turn off multiple switches at once

### ISSUE THREAD

**Issue by JT114881** [zwave-js/zwavejs2mqtt#1649]
### Version

**Checklist:**

- [ X] I am **not** using HomeAssistant. **Or:** a developer has told me to come here.
- [ X] I have checked the troubleshooting section and my problem is **not** described there.
- [ X] I have read the changelog problem was **not** mentioned there.

Build/Run method

- [ X] Docker
- [ ] PKG
- [ ] Snap package
- [ ] Manually built (git clone - yarn install - yarn run build )

zwavejs2mqtt version: 0.24.1
zwave-js version: 
-Driver Version: 8.2.1
-Server Version: 1.10.1

### Describe the bug

Zwave network stops responding when sending multiple commands and produces the attached errors

### To Reproduce

1. Turn on multiple switches at once. Usually happens when I turn on/off groups of lights
2. See error

### Expected behavior

Zwave network does not crash

### Additional context

Things I have tried:
-Upgrading Controller and Aeotec battery powered sensors to the latest firmware
-Unpairing all devices, resetting the Z-Wave controller, setting up the network from scratch (multiple times)
-Blowing away HomeAssistant and starting from scratch in combination with above
-Putting the controller on a quality USB 3.0 extension cable and putting it up high
-Drinking

It looks like others are experiencing similar issues with different Switches: https://community.inovelli.com/t/lzw31-duplicate-messages-flooding-zwave-network/8594
For some reason this error does not show up in the logging to file despite silly/trace being selected, so I have attached a screenshot. I am happy to allow access to my instance for direct troubleshooting as well. Anything that will help please let me know.

![errors](https://user-images.githubusercontent.com/18473943/132107139-4c450ad2-28ee-4080-aa51-54d020eadc34.png)
[Logs_And_Dumps.zip](https://github.com/zwave-js/zwavejs2mqtt/files/7110448/Logs_And_Dumps.zip)

**Comment by AlCalzone** [comment]
Status Fail means that your controller can't send the messages for some reason. I took a glance at the linked thread and it seems like the switches themselves are flooding the network to the point that the controller doesn't get any time to "speak".

So nothing we can fix on the driver side I'm afraid.
