### ISSUE TITLE
[question] Toggle a binary switch

### ISSUE THREAD

**Issue by Isilorn** [zwave-js/zwavejs2mqtt#1669]
Hello,

I have started a migration from the Jeedom Zwave plugin to ZWavejs2MQTT. The migration went well (I recovered all my devices) and now I'm recreating the commands in Jeedom.

I'm stuck (for the moment) on an Aeotec ZW175 socket and its binary switch.

<img width="368" alt="image" src="https://user-images.githubusercontent.com/7522688/132466322-c2c58518-2856-48b5-b59d-1c907462e9be.png">

I can control it via the switch in the interface of ZWavejs2MQTT but I can't control it via "targetValue". I tried everything via zwave/nodeID_32/37/0/targetValue/set :

`{"value":"true"}`
`{"value":true}`
`{"value":1}`
`{"value":"on"}`
`{"true"}`
`{true}`
`{1}`

etc.

I'm probably doing it wrong but I admit that I'm stuck here...

**Comment by robertsLando** [comment]
When you send the mqtt packet do you see a log in console? Valid payloads are

- { "value": true }
- "true"

**Comment by Isilorn** [comment]
That's odd...

When I send {"value":true} :

`2021-09-08 18:52:03.185 INFO MQTT: Message received on zwave/nodeID_32/37/0/targetValue/set, <Buffer 7b 22 76 61 6c 75 65 22 3a 22 31 22 7d>`

When I send "true" :

`2021-09-08 18:53:28.308 INFO MQTT: Message received on zwave/nodeID_32/37/0/targetValue/set, <Buffer 22 74 72 75 65 22>`

**Comment by robertsLando** [comment]
Could you send me a full log file of a startup? I need to check if the value is registered for updates

**Comment by Isilorn** [comment]
Here it is, I changed the log level to "silly" so that it is the most verbose

By the way, ZWavejs2MQTT is in container as well as Mosquitto

[zwavejs2mqtt.log](https://github.com/zwave-js/zwavejs2mqtt/files/7134525/zwavejs2mqtt.log)

**Comment by robertsLando** [comment]
Could you give a try to https://github.com/zwave-js/zwavejs2mqtt/pull/1671 ?

**Comment by Isilorn** [comment]
Ok could you provide me with the corresponding docker image ? Or can I just build it from the Dockerfile with the following change ;

`ARG zwavejs=https://github.com/zwave-js/node-zwave-js/archive/fixSubscribe.tar.gz`

instead of

`ARG zwavejs=https://github.com/zwave-js/node-zwave-js/archive/master.tar.gz`

?

**Comment by robertsLando** [comment]
You can use `Dockerfile.contrib` and set the Z2M_BRANCH to `fixSubscribe`

**Comment by Isilorn** [comment]
Just tested it, it works 😄 

Do you want some log or is it ok ?

**Comment by robertsLando** [comment]
It's ok, will merge it so :)
