### ISSUE TITLE
[bug] Thermostat card not updating operation

### ISSUE THREAD

**Issue by slippern** [zwave-js/zwavejs2mqtt#1670]
### Version

**Checklist:**

- [x] I am **not** using HomeAssistant. **Or:** a developer has told me to come here.
- [x] I have checked the troubleshooting section and my problem is **not** described there.
- [x] I have read the changelog problem was **not** mentioned there.

Build/Run method

- [x] Docker
- [ ] PKG
- [ ] Snap package
- [ ] Manually built (git clone - yarn install - yarn run build )

zwavejs2mqtt version: 5.5.1
zwave-js version: 8.2.1
### Describe the bug

Thermostat card is not updating operation/status values (on, off, cooling, heat).

### To Reproduce

1: I clicked on varme(heat).
<img width="258" alt="image" src="https://user-images.githubusercontent.com/1651061/132545493-0652abaa-c73e-4315-8abe-4ac732e32b42.png">

2: Debug log:
`2021-09-08 18:12:51.516 INFO MQTT: Message received on zwave2mqtt/Varmekabler-Yttergang/64/1/mode/set, <Buffer 68 65 61 74>
2021-09-08 18:12:51.521 INFO ZWAVE: Writing 1 to 4-64-1-mode
2021-09-08 18:12:56.715 DEBUG MQTT: Publishing to zwave2mqtt/Varmekabler-Yttergang/64/1/mode: {
time: 1631117576715,
value: 1,
nodeName: 'Varmekabler-Yttergang',
nodeLocation: 'Yttergang'
} with options { qos: 1, retain: true }
2021-09-08 18:12:56.716 INFO ZWAVE: Node 4: value updated: 64-1-mode 1 => 1
2021-09-08 18:13:18.501 DEBUG MQTT: Publishing to zwave2mqtt/Varmekabler-Yttergang/50/4/value/65537: {
time: 1631117598501,
value: 314,
nodeName: 'Varmekabler-Yttergang',
nodeLocation: 'Yttergang'
} with options { qos: 1, retain: true }
`
The thermostat still showing it is off:
<img width="261" alt="image" src="https://user-images.githubusercontent.com/1651061/132546096-9e54d8fb-627b-4245-813b-90debcb95207.png">

### Expected behavior

It should change to on/off/cooling/heat..

**Comment by robertsLando** [comment]
@slippern Are you using hass integration or mqtt discovery?

**Comment by slippern** [comment]
> @slippern Are you using hass integration or mqtt discovery?

Im using MQTT discovery.

**Comment by robertsLando** [comment]
Could you try with latest release? I just release a new version with a possible fix to it

**Comment by slippern** [comment]
I will updates asap, the hassio addon has not been updated yet.

**Comment by slippern** [comment]
Im now running 
zwavejs2mqtt: 5.6.0
zwave-js: 8.3.1

and im still having the same issue.

**Comment by robertsLando** [comment]
Considered to swith to official hass integration? Just need to enable zwavejs server in hass settings

**Comment by slippern** [comment]
I have switched to the official hass integration, and the thermostat card is now working as expected..
