### ISSUE TITLE
onNotification does not handle all parameter types correctly

### ISSUE THREAD

**Issue by AlCalzone** [zwave-js/zwavejs2mqtt#169]
https://github.com/zwave-js/zwavejs2mqtt/blob/8f326de2a8c4f6dcce49180c7b8c6d772128558b/lib/Gateway.js#L330-L346

`.toString()` doesn't cut it, since the parameters can be different things and even CC instances or Records. Here's my reference implementation:

https://github.com/AlCalzone/ioBroker.zwave2/blob/9504bc06a1747913c76da940574646e07fdb7472/src/lib/objects.ts#L453-L558

**Comment by AlCalzone** [comment]
Note that this doesn't actually handle CommandClass payloads - I should probably convert them to a record inside zwave-js

**Comment by robertsLando** [comment]
OMG... :cry:

**Comment by robertsLando** [comment]
@AlCalzone Is this documented? What could I get specifically in that field? Could I treat it as an object and pass the entire payload?

**Comment by AlCalzone** [comment]
Isn't that what types are for?
![grafik](https://user-images.githubusercontent.com/17641229/103904527-adeefa00-50fd-11eb-90ab-af10989871a7.png)
![grafik](https://user-images.githubusercontent.com/17641229/103904559-b8a98f00-50fd-11eb-8179-4d7f91a2b191.png)

**Comment by AlCalzone** [comment]
IMO:
* Buffer: no clue what's in there -> I would export as hex or raw
* Duration: depends on how you want to display it
* CommandClass: 🤷🏻‍♂️, should probably convert it before exposing
* Record: export each property separately

**Comment by robertsLando** [comment]
@AlCalzone In docs it says just Buffer for parameters
