### ISSUE TITLE
HowTo remove/delete Zwave2MQTT npm package

### ISSUE THREAD

**Issue by HubertusH** [zwave-js/zwavejs2mqtt#1698]
Hi all,
i move my zwave net from Zwave2Mqtt to ZwaveJS2MQTT and the questin now: how can i remove the old zwave2mqtt (npm package) from my raspberry?

Thank you 
BR
Hubertus

**Comment by robertsLando** [comment]
It's not a npm package, btw just remove the folder if you installed it using the nodejs way, otherwise just drop the docker image and container

**Comment by HubertusH** [comment]
Thank you - i try it.
