### ISSUE TITLE
[feat] Add api to get app version

### ISSUE THREAD

**Issue by lddubeau** [zwave-js/zwavejs2mqtt#1701]
**Is your feature request related to a problem? Please describe.**

I need to get the zwavejs2mqtt version number *of the running instance* from Home Assistant.

**Describe the solution you'd like**
A REST endpoint that returns the version number of zwavejs2mqtt, and possibly the server, etc. when called. e.g `GET .../api/version` would return

```
{
  "zwavejs2mqtt": "5.5.0",
  "zwavejs": "whatever",
  "driver": "...",
  // etc. whatever version numbers make sense.
}
```

*Note that I don't want to turn on the MQTT bridge only to have this capability.* I don't use the bridge.

**Describe alternatives you've considered**

Home Assistant already provides version numbers when you click on the Z-Wave JS integration but it does not provide the zwavejs2mqtt version number. (Besides this does not appear to be obtained by a REST call.)

I've also searched documentation, etc. but did not find a REST endpoint that I can query from the Home Assistant side.

**Additional context**

I need this so that I can get warnings when parts of my system have been superseded by new versions. I have a docker-compose file with nginx, ha, mosquitto and zwavejs2mqtt. There's only zwavejs2mqtt that won't allow me to get the version number of the running instance.

**Comment by robertsLando** [comment]
The not documented alternative would be to use the websocket that is actually used on client side to retrieve those informations, BTW making an api for this is really easy so I would go for it, just give soem days as I will be back from Holidays on Monday :)

**Comment by lddubeau** [comment]
I got busy but the change sounds good. Thank you!
