### ISSUE TITLE
[question] Only send some entities of node to HA

### ISSUE THREAD

**Issue by jasonkelly214** [zwave-js/zwavejs2mqtt#1704]
I'm having a hard time wrapping my head around the procedure or settings to have zwavejs2mqtt send only send discovery for one entity of a node. 

Here's what I've tried most recently...

Home assistant tab of node. 
Delete entities I don't want in HA with DELETE button on right
Click disable discovery on left side
Click store
click rediscover (right side)

I have retain OFF in the MQTT settings. I have MQTT Discovery ON in the HA settings. And I have Manual Discover turned ON for HA as well.

When I restart HA and zwavejs2mqtt and click the node, I have all the entities listed again despite deleting them. Is it unnecessary to delete them so long as manual discovery is enabled? If so, what does the disable discovery button do?

**Comment by robertsLando** [comment]
Hi @jasonkelly214 , for HASS I really suggest you to enable zwavejs server in settings and use it with hass zwavejs integration, mqtt discovery is limited comprared to that

**Comment by robertsLando** [comment]
> What is the sequence of buttons in order to properly save the entities such that zwavejs2mqtt will discover only the devices I want (like I have in manual mode) but will also send them at birth?

You should set the ignore disvovery flag in the discovery json to true in the devices you don't want to discover and store them in nodes.json by pressing the store button from hass devices table

**Comment by jasonkelly214** [comment]
That worked thanks
