### ISSUE TITLE
[bug]

### ISSUE THREAD

**Issue by decairn** [zwave-js/zwavejs2mqtt#1705]
### Version

**Checklist:**

- [] I am **not** using HomeAssistant. **Or:** a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is **not** described there.
- [X] I have read the changelog problem was **not** mentioned there.

Build/Run method

- [X] Docker
- [ ] PKG
- [ ] Snap package
- [ ] Manually built (git clone - yarn install - yarn run build )

zwavejs2mqtt version: 5.5.1
zwave-js version: 8.2.1

### Describe the bug

Zooz ZSE41 device showing in panel as unknown device, yet it appears in the online db (https://devices.zwave-js.io/?jumpTo=0x027a:0x7000:0xe001:0.0)

### To Reproduce

Added new device straight out the box ( with no security)
Driver discovered and found all its CC values

### Expected behavior

Product and product code columns are populated

### Additional context

zwavejz2mqtt log line:
2021-09-19 16:27:12.860 INFO ZWAVE: Node 29 ready: Zooz - Unknown product 0xe001 (0x7000)

zwavejs log line:
2021-09-19T23:26:01.132Z CNTRLR « [Node 029] received response for manufacturer information:
                                    manufacturer: Zooz (0x027a)
                                    product type: 0x7000
                                    product id:   0xe001

**Comment by kpine** [comment]
The device config was added in node-zwave-js [v8.2.2](https://github.com/zwave-js/node-zwave-js/releases/tag/v8.2.2), so you'll need to upgrade zwavejs2mqtt to a newer version to pick it up. That, or temporarily download the config file into the `store/config` directory to use a [custom config](https://zwave-js.github.io/zwavejs2mqtt/#/usage/custom-device-files).
