### ISSUE TITLE
I would like to see the COMMAND_CLASS_CLOCK at LC-13

### ISSUE THREAD

**Issue by HubertusH** [zwave-js/zwavejs2mqtt#1712]
**Is your feature request related to a problem? Please describe.**
The danfoss device "living connect" LC-13 supports the device class COMMAND_CLASS_CLOCK becouse the device made a check once every week

**Describe the solution you'd like**
It would be great if the COMMAND_CLASS_CLOCK with the parameters get/set day / hour / minute to read and reset the clock.

In the "older" gateway Zwave2MQTT with openZwave the class exists.

**Comment by robertsLando** [comment]
@AlCalzone

**Comment by AlCalzone** [comment]
The driver supports `Clock CC` and automatically corrects the clock on the device if it receives a clock report that's off too much. If I understand your comment
> becouse the device made a check once every week

correctly, this should happen already. We don't have separate values for each property, but you can use this API to set the clock manually:
https://zwave-js.github.io/node-zwave-js/#/api/CCs/Clock?id=set

The weekday must be one of those values:
```
export enum Weekday {
	Unknown = 0x00,
	Monday = 0x01,
	Tuesday = 0x02,
	Wednesday = 0x03,
	Thursday = 0x04,
	Friday = 0x05,
	Saturday = 0x06,
	Sunday = 0x07,
}
```

**Comment by AlCalzone** [comment]
If this is a request to have UI to get/set the clock, zwavejs2mqtt should handle it.

**Comment by tommyjlong** [comment]
If you are interested in more details for setting the clock using the API, here is a thread that ended up working for me (using ZwaveJS2MQTT)....(just jump to the last couple of discussion points):
https://github.com/zwave-js/zwavejs2mqtt/issues/1386

**Comment by AlCalzone** [comment]
I KNEW it had to be somewhere - didn't remember if it was on Slack or here

**Comment by HubertusH** [comment]
Perfect! Thank you all.

**Comment by HubertusH** [comment]
i try the api call 0x81 (129) to get the clock of the device - i get one! But it's wrong.
When the driver automatically corrects the clock?

BR
Hubertus

**Comment by AlCalzone** [comment]
> When the driver automatically corrects the clock?

When the device sends the driver an unsolicited Clock Report. After a Get, it won't react automatically. If it's that off, it doesn't seem like the device requests the current time on its own, so you'll have to issue a Clock Set yourself.
