### ISSUE TITLE
[feat] Z-wave logging and log to file enabled by default

### ISSUE THREAD

**Issue by daphatty** [zwave-js/zwavejs2mqtt#1713]
**Is your feature request related to a problem? Please describe.**
Depends. Could be yes, could be no. 

**Describe the solution you'd like**
I'd like to request that Z-wave logging and log to file for Z-wave events be enabled and set to Debug/Silly log level by default.

**Describe alternatives you've considered**
A forced UI element during initial set up of the AddOn that prompts a user with the choice to enable Z-wave logging and log to file. This UI element should include STRONG encouragement to turn on logging.

**Additional context**
With log rotation and file compression having been implemented, the logging capabilities of JS2Mqtt are quite robust. As such, the impact to the file system should be minimal even with Silly level logging. Below is an example screenshot showing logs that were created over a four day period at Silly log level for a Z-wave network consisting of 36 devices, three of which report energy consumption data every 30 seconds.

![image](https://user-images.githubusercontent.com/28716334/134210736-cd4bdbe4-27a3-4d7f-831d-ee82220fd9e0.png)

As you can see, the file size footprint is quite small.

In many cases, receiving helpful guidance via discord or this forum is predicated on a user's ability to provide tangible evidence of the issue at hand. Anecdotally, I've seen many users arrive at the #zwave channel seeking assistance only to be presented with the "do you have logs?" barrier.  If logging were on by default, the answer would be "Yes" 100% of the time. 

Logging by default would also benefit issue identification In cases where it may not be practical or possible for the end user to recreate the problem. Examples include nodes that randomly disappear from the z-wave network, or inclusion errors which occur during the initial setup of an elaborate Z-wave network.

Feedback via logging will ultimately benefit the development of the AddOn and those who invest their time doing so. The fact that JS2Mqtt has such a robust logging system is, in fact, the reason why I switched to this AddOn. Thank you for your consideration.

**Comment by robertsLando** [comment]
@daphatty enable logging by default actually could cause some unexpected side effects expecially with zwavejs2mqtt logs as them have no limits and have no rotation. @blhoward2 @AlCalzone thoughts on this?

**Comment by AlCalzone** [comment]
I think this is about the driver logs which already use logrotation. I absolutely agree with `debug` level by default. I can't count how often I've asked for logs to diagnose an issue, only to be presented with useless info level logging.

**Comment by robertsLando** [comment]
Done here: https://github.com/zwave-js/zwavejs2mqtt/pull/1746/files/bdb203df29a5b06c01d89323a87c185766f7ddf1..3ac098859af9a08a2b948b794820067b4633498b
