### ISSUE TITLE
[bug] The icons are no longer displayed

### ISSUE THREAD

**Issue by Micka41** [zwave-js/zwavejs2mqtt#1728]
### Version

**Checklist:**

- [x] I am **not** using HomeAssistant. **Or:** a developer has told me to come here.
- [x] I have checked the troubleshooting section and my problem is **not** described there.
- [x] I have read the changelog problem was **not** mentioned there.

Build/Run method

- [ ] Docker
- [ ] PKG
- [ ] Snap package
- [x] Manually built (git clone - yarn install - yarn run build )

zwavejs2mqtt: 5.6.1.9daf577
zwave-js: 8.3.1

### Describe the bug

The icons are no longer displayed

### To Reproduce

Show zwavejs2mqtt

**Comment by Micka41** [comment]
![Sans titre](https://user-images.githubusercontent.com/10485916/134640989-f54cd25b-b572-4f3f-9188-81887cc62455.png)

**Comment by mamoel666** [comment]
I can confirm this.

**Comment by bburgschat** [comment]
Same on Docker Images

**Comment by ScratMan** [comment]
Confirmed here on a docker container.
Seems that the ZWave network is still working, and I could not find errors in log about missing icons.
[_zwave-js_logs.txt](https://github.com/zwave-js/zwavejs2mqtt/files/7225377/_zwave-js_logs.txt)

**Comment by mupsje** [comment]
pfiew, I thought I was the only one :)

Here same issue.......
Docker

**Comment by tprelog** [comment]
Hi, I have the same issue after upgrading to `5.6.1`

![image](https://user-images.githubusercontent.com/35702532/134678037-8581b376-600b-46f8-bf27-a61278340a58.png)

I'm also using the Docker container

**Comment by MastrUsr** [comment]
Docker image. Same for me...

**Comment by ahochsteger** [comment]
This PR fixes the issue:
https://github.com/zwave-js/zwavejs2mqtt/pull/1729
