### ISSUE TITLE
[bug] Confusing thermostat mode_command_topic field.

### ISSUE THREAD

**Issue by GaTechThomas** [zwave-js/zwavejs2mqtt#1735]
The Home Assistant MQTT documentation on this repo has unclear info for mode_command_topic. The specific page is:

https://github.com/zwave-js/zwavejs2mqtt/blob/master/docs/guide/homeassistant-mqtt.md

The description for mode_command_topic says, 
```"If true this values are subscribed to this topics to send commands from Hass to change this values."```

This field is particularly nuanced, so it would be helpful to clearly explain what is going on here. Part of the difficulty is that the items that end in "_topic" usually list an actual topic. This item does not match that pattern - the description seems to indicate that it's a boolean only, and what that boolean controls has room for much clarity.

To speculate, it seems that this is an indicator that commands can be sent from Home Assistant in order to change the values. It's not clear how that is done. Does this mean that each topic in the section is used for both events and commands? If so, is that a good idea? Which specific topics are in play - which scope?

Additionally, it would be helpful to use a different naming scheme for this type of field, since it's not specifying a topic. Clear naming is very helpful in the long-term health of a code base.

Thanks!

**Comment by robertsLando** [comment]
Hi @GaTechThomas, did you ever considered to move to hass zwave js integration? You can enable it from hass settings and it's the raccomended way now, mqtt is much more limited and I don't plan to keep it supported in the future as it's frequently broken by hass updates

**Comment by GaTechThomas** [comment]
Well that's disappointing. The zwave js integration has been a massive disaster for me. I spent many fully weekends over this year trying to piece together enough info to get it working. Only when I dumped the zwave js integration altogether and started using zwavejs2mqtt's MQTT devices directly did things start working again. (FWIW, I have 20+ years of systems software development, so I'm pretty technically savvy.)

I'll back things up and give it another try now that I have a functional starting point. 🤞

Is there a way to mark MQTT as deprecated so that others don't spend big efforts getting it working this way only to have it quickly become unmaintained?

**Comment by robertsLando** [comment]
@GaTechThomas I'm sorry for that, in docs we clearly Say that the preferred way it's the zwavejs integration: https://zwave-js.github.io/zwavejs2mqtt/#/homeassistant/homeassistant-mqtt. MQTT discovery it's just an alternative

**Comment by GaTechThomas** [comment]
"Alternative" is not nearly as strong as "deprecated". If it's going to be discontinued soon, then it would be helpful to users to see it described as deprecated.

The good news is that I have it working fully with zwavejs, no MQTT at all. It seems that switching from Aeotec Z-Stick Gen5 to Gen5 Plus did the trick.

**Comment by robertsLando** [comment]
I will fix the docs to make it more clear so. Thanks 🙏🏼

**Comment by jefft4** [comment]
> Hi @GaTechThomas, did you ever considered to move to hass zwave js integration? You can enable it from hass settings and it's the raccomended way now, mqtt is much more limited and I don't plan to keep it supported in the future as it's frequently broken by hass updates

@robertsLando  That's bad news for those using something other than HASS - e.g. Domoticz!  The authors of Domoticz have just recently started recommending zwavejs2mqtt and auto-discovery in place of the old OZW.  If you're not planning to support it, is there any plan for a domoticz native integration?  Personally I'd rather the MQTT method were the primary - direct integrations always have the potential to hang or crash the core system, whereas keeping things 'at arms length' via MQTT means one device handler crashing can't bring down the core.

**Comment by robertsLando** [comment]
> If you're not planning to support it, is there any plan for a domoticz native integration

No plan right now, I'm really busy at work and I'm focusing on bug fixes and to keep z2m compatible with latest zwavejs version
