### ISSUE TITLE
[bug] X-External-Path header ignored in some cases.

### ISSUE THREAD

**Issue by frenck** [zwave-js/zwavejs2mqtt#1756]
### Version

**Checklist:**

- [x] I am **not** using Home Assistant. **Or:** a developer has told me to come here.
- [x] I have checked the troubleshooting section and my problem is **not** described there.
- [x] I have read the changelog and my problem is **not** mentioned there.

Build/Run method

- [ ] Docker
- [ ] PKG
- [ ] Snap package
- [x] Manually built (git clone - yarn install - yarn run build )

Zwavejs2Mqtt version: 5.7.x (both .0 & .1)
Z-Wave JS version: Whatever was shipped with the above

### Describe the bug

> A clear and concise description of what the bug is.

Some assets don't load when using the `X-External-Path`, as the header seems to be ignored.

![image](https://user-images.githubusercontent.com/195327/134943194-542f094c-ce5e-4ee9-8e8c-ad4ad18f3de0.png)

### To Reproduce

Set up a reverse proxy putting Z-Wave2MQTT in a subfolder, ensure `X-External-Path` is sent.
See browser debug console it doesn't load the woff2 files, as the subpath passed is ignored.

### Expected behavior

To work

### Additional context

Introduced in 5.7.0

**Comment by robertsLando** [comment]
@frenck Could you show me if you have warnings or errors in console log?

**Comment by frenck** [comment]
No, no warnings in the console. Only a 404 on the path, as the external path header was ignored when retrieving the woff2 files

**Comment by robertsLando** [comment]
Quite sure it's something related to https://github.com/zwave-js/zwavejs2mqtt/commit/c2bd96784ab34a48757f1cd1a02c805e10b812cc.

If I open a PR could you test it? @frenck

**Comment by frenck** [comment]
> If I open a PR could you test it? @frenck

Yes

**Comment by robertsLando** [comment]
@frenck PR ready

**Comment by frenck** [comment]
Installing...

**Comment by frenck** [comment]
Some changes visible, but no sigar

![image](https://user-images.githubusercontent.com/195327/135050353-566e7ccc-5fc1-4286-a701-34b5eb7a4f10.png)


![image](https://user-images.githubusercontent.com/195327/135050331-9c45431e-8930-40b2-9233-0162aed03e07.png)

The filenames have changed, there is a notable double dot (`.`) before the filename extension. However, as you can see on the right side, the request URL is missing the forwarded path.

For comparison a JS file:

![image](https://user-images.githubusercontent.com/195327/135050587-0e6ee70b-eb0a-4b25-b2cd-6cf1e04a4903.png)

**Comment by robertsLando** [comment]
Sincerly I have no clue why that happens, I will do another try, if still not working I will revert the css-loader to previous version

**Comment by robertsLando** [comment]
Try last commit please

**Comment by frenck** [comment]
@robertsLando I'm still recovering from surgery, so not full-time online. At this point, I'm working towards the Home Assistant beta, which has a higher priority. I'll get back to this asap.

**Comment by robertsLando** [comment]
I'm sorry, hope you are well. Don't worry take your time

**Comment by frenck** [comment]
The last commits make no difference in terms of visible results and in results in the browser debugger.

![image](https://user-images.githubusercontent.com/195327/135436840-8547860c-227d-4290-a394-ec7d7b959d69.png)

**Comment by robertsLando** [comment]
Cannot detect why this is happening BTW I know that the only thing I touched is webpack build to update css-loader here c2bd96784ab34a48757f1cd1a02c805e10b812cc so I have reverted that commit. Try now please

**Comment by frenck** [comment]
Yep... works

![image](https://user-images.githubusercontent.com/195327/135504894-80376754-e5df-4546-9b0a-7a3a12f311c9.png)
