### ISSUE TITLE
[bug] ID Lock 150 not locking

### ISSUE THREAD

**Issue by martindlarsson** [zwave-js/zwavejs2mqtt#178]
**Version**

Build/Run method
- [ x] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build ) 

zwavejs2mqtt version: latest at 8th january 2021.

**Describe the bug**
I have an ID Lock 150 and trying to lock it over zwave has no effect. I get an error message in the debug log. Im not sure what more information you need to fix this issue or if this is something I can fix?

**Expected behavior**
The lock should lock.

**Additional context**
Debug log:
2021-01-08 22:04:53.506 INFO MQTT: Message received on zwavejs/nodeID_22/door_lock/endpoint_0/targetMode/set
2021-01-08 22:04:53.508 INFO ZWAVE: Writing LOCK to 98-0-targetMode
2021-01-08 22:04:53.512 INFO ZWAVE: Controller status: Driver: Door Lock: "targetMode" must be of type "number", received "string"
2021-01-08 22:04:53.515 ERROR ZWAVE: Unable to write LOCK on 98-0-targetMode

**Comment by AlCalzone** [comment]
Thats a UI bug. zwave-js does not accept the string, so the command is never sent to the log.

**Comment by martindlarsson** [comment]
The state of the device (lock entetie) in Home Assistant is also incorrect.
This worked in the stock zwave integration in HA.
Is there some configuration I can change to make it work?

**Comment by AlCalzone** [comment]
I'd wait for #84 to be merged, then we can debug this further with a working log.

**Comment by billiaz** [comment]
at #137 we changed the way lock works as due to payload. can you share with me the node exported in json?
you can do that https://zwave-js.github.io/zwavejs2mqtt/#/troubleshooting/node_export
@martindlarsson

**Comment by martindlarsson** [comment]
Here is my exported node information. Thanks!

[node_22.json.zip](https://github.com/zwave-js/zwavejs2mqtt/files/5791413/node_22.json.zip)

**Comment by billiaz** [comment]
@martindlarsson your lock seems to be the same as the other locks. and I do see the old payload (before the patch)

```
    "hassDevices": {
        "lock_lock": {
            "type": "lock",
            "object_id": "lock",
            "discovery_payload": {
                "command_topic": "zwavejs/nodeID_22/door_lock/endpoint_0/targetMode/set",
                "state_locked": "true",
                "state_unlocked": "false",
                "value_template": "{% if value_json.value == false %} false {% elif value_json.value == true %} true {% else %} unknown {% endif %}",
                "state_topic": "zwavejs/nodeID_22/door_lock/endpoint_0/currentMode",
                "json_attributes_topic": "zwavejs/nodeID_22/door_lock/endpoint_0/currentMode",
                "device": {
                    "identifiers": [
                        "zwavejs2mqtt_0xd54a0707_node22"
                    ],
                    "manufacturer": "ID Lock AS",
                    "model": "Z wave module for ID Lock 150 and 101 (ID-150)",
                    "name": "nodeID_22",
                    "sw_version": "1.5"
                },
                "name": "nodeID_22_lock",
                "unique_id": "zwavejs2mqtt_0xd54a0707_22-98-0-currentMode"
            },
            "discoveryTopic": "lock/nodeID_22/lock/config",
            "values": [
                "98-0-currentMode",
                "98-0-targetMode"
            ],
            "persistent": false,
            "ignoreDiscovery": false
        },
```
this means you are not running a newer than a few days version, which contains the patch I mentioned, if you move to latest release this payload should update to the new one.

**Comment by martindlarsson** [comment]
Im running :latest which is 11 days old

**Comment by billiaz** [comment]
can you try the :dev ? this is the one compiles every night from master

**Comment by martindlarsson** [comment]
Ill try :)

**Comment by martindlarsson** [comment]
Now it wokrs!! Thank you all for super wokrk! Im really impressed with how zwavejs works at this early stage.

**Comment by AlCalzone** [comment]
Well, it has been in development for 3 years ;)
