### ISSUE TITLE
[feat] S2 DSK database

### ISSUE THREAD

**Issue by mazmar** [zwave-js/zwavejs2mqtt#1782]
Would it be possible to create a txt/json S2 DSK database providing full 16 numbers in a file (or UI i don't mind) when device is then added via inclusion it would check if the DSK is in the database and automatically setup S2 without PIN request.

This might sound stupid but I'll explain what happened to me:
I bought 23 Fibaro Walli Switches which are S2 enabled. I Installed all of them on ZwaveJS 5.0 without S2. Now After an upgrade i want to reinclude them to S2. But I have 23 boxes with QR codes and the DSK on them but I have no idea which box belongs to which switch. All of the switches have the PIN portion written on back of the switch but that would require to disassemble which I will not do ...

So if I could enter the DSK into a list it would be possible to reinclude the devices, now I will leave them unauthenticated rather then doing it manually

**Comment by robertsLando** [comment]
Could make sense. BTW I would also know @blhoward2 and @AlCalzone opinion about this

**Comment by AlCalzone** [comment]
That's basically SmartStart. It's on my to do list.

**Comment by blhoward2** [comment]
I thought SmartStart required you to have the QR available? He's saying let the user create a database of them that the front end then searches and returns from if there is a match.

**Comment by AlCalzone** [comment]
SmartStart requires you to enter the DSKs of the devices to be included. You can do that with QR codes or by hand.

**Comment by mazmar** [comment]
Just to be sure, smartscan does not require scanning/inputting the DSK just before inclusion? Because that would not solve the issue when i have multiple QR codes and no idea which switch belongs to which box. I want to be able to input all DSK at the same time and then start inclusion so DSK would be auto matched.

**Comment by AlCalzone** [comment]
Startsmart works like you described in the OP. You can enter a list of DSKs beforehand and you don't need to know which node is which.

**Comment by AlCalzone** [comment]
solved, right?

**Comment by robertsLando** [comment]
Yes, I think :)
