### ISSUE TITLE
[question] How do you set/change a value via MQTT topics!?

### ISSUE THREAD

**Issue by mriksman** [zwave-js/zwavejs2mqtt#1787]
I have everything working well. I can change the state of the device in the zwavejs2mqtt GUI no problem.
![image](https://user-images.githubusercontent.com/20112339/136115960-40f3508c-1b98-4bb2-9a60-e32e6897a37b.png)

But I can't work out what topic/message to send to MQTT. Shouldn't I be writing to targetValue..??
![image](https://user-images.githubusercontent.com/20112339/136116068-55229178-e895-45a4-8bc7-bd3a82dd80f1.png)

**Comment by robertsLando** [comment]
https://zwave-js.github.io/zwavejs2mqtt/#/guide/mqtt?id=set-values

**Comment by mriksman** [comment]
That link/documentation talks about `/set`, but that topic doesn't exist for me. It doesn't seem to relate at all...?

I tried writing `false` raw and json  `{"value": false}` to `targetValue`, but nothing happens.

**Comment by robertsLando** [comment]
If you read the docs, it says that in order to send write requests you have to manually add `/set` to the topic

**Comment by mriksman** [comment]
Ugh. Thanks. I feel like an idiot. I'm a pretty clever guy, but I didn't find this to be clear...
![image](https://user-images.githubusercontent.com/20112339/136180076-3eabfcb0-68bc-488b-ae48-c7fd6379e7ea.png)

What confused me is that using the GUI, there was only a `targetValue` topic. There was no `set` topic. And `targetValue` never seemed to update/change. So I couldn't 'reverse engineer' where I should write too. I assume the GUI is not using the MQTT topics to change the values, but the js API...?

Anyway, THANK YOU!! :)

**Comment by robertsLando** [comment]
Nope gui is using socket.io to communicate with the backend :)
