### ISSUE TITLE
[feat] Logs are currently multiple lines and inconcistent formats

### ISSUE THREAD

**Issue by LordMike** [zwave-js/zwavejs2mqtt#182]
**Is your feature request related to a problem? Please describe.**
Some users will probably try to store logs in databases for long term archiving and searchability. Some of the log output is currently in two lines and with multiple formats, which makes it tricky to interpret and search through.

F.ex. grepping through syslog storage is made difficult with the current output.

That being said. It's very neat to have colored output :)

**Describe the solution you'd like**
Ensure all logs are on one line each and in consistent formats.

**Describe alternatives you've considered**
N/A

**Additional context**
Example multiple lines:
![image](https://user-images.githubusercontent.com/1027111/104109252-505cd800-52cc-11eb-84c8-d54d4b823da8.png)

Example with multiple formats
![image](https://user-images.githubusercontent.com/1027111/104109323-00cadc00-52cd-11eb-896e-0e928747e783.png)

**Comment by LordMike** [comment]
I've just noticed that there are multiple timestamp formats too. I think the ozw logs are different from the zwavejs logs?... or perhaps the zwavejs2mqtt logs are different from the zwavejs logs?

I'll amend this request to be more about consistency.

**Comment by robertsLando** [comment]
@LordMike You see both zwavejs and zwavejs2mqtt logs there. About the single/multiline the only thing I can think is that we could provuide a custom winston transport to let you handle logs in your preferred way

**Comment by LordMike** [comment]
I really expected the logs to come through the same system. Log events should really have been a type with a timestamp, message etc.. Then you, as the application, would define the format that the timestamp of _all_ log message should be in, as well as the fields you'd want written out.

Anyhoo. My suggestion is to make it easier for consumers of the log, by making them more consistent. :)

There are other benefits in centralizing the logs through one system - it'd allow us to set filters for all kinds of things, like different severity filters for different components.. Maybe zjs2m should be logging Information, while the MQTT component should log Debug... or some other combination of filters.

**Comment by robertsLando** [comment]
@LordMike Every module has it's own log system, mqtt uses debug for example, zwave-js uses winston and I use winston too. Winston allows to provide transports,  what I could suggest is to think about a custom transpost (shared in both zwavejs and zwavejs2mqtt that stores log in a json format in a database for example)

**Comment by LordMike** [comment]
Well, sucks that some components don't use a configurable log system.

Zwavejs configures itself to use the console as a transport then? ... it shouldn't do that... it's a library..

But yea, if you, in this app, control the logging transports, then everything should work out :)

**Comment by robertsLando** [comment]
> Zwavejs configures itself to use the console as a transport then? ... it shouldn't do that... it's a library..

With latest changes now I can configure both zwavejs and zwavejs2mqtt transports. So just let me know how you would like this to be implemented

**Comment by LordMike** [comment]
I've come to think it would be infeasible to change zwave-js' output.. It relies heavily on the formatting to be legible.
