### ISSUE TITLE
[bug] getNodes JSON properties with multiple types (string/int)

### ISSUE THREAD

**Issue by LordMike** [zwave-js/zwavejs2mqtt#184]
**Version**

Build/Run method
- [x] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build ) 

zwavejs2mqtt version: v1.0.0-alpha.2

**Describe the bug**
When devices have not yet been discovered, some properties in the nodes json will be of a string type rather than integers. I'm calling `getNodes` to dump the nodes.

Example discovered:
![image](https://user-images.githubusercontent.com/1027111/104109754-4093c280-52d1-11eb-8e6a-ded6fc91c054.png)

Example not yet discovered:
![image](https://user-images.githubusercontent.com/1027111/104109745-35d92d80-52d1-11eb-918e-13504fe8acc6.png)

**To Reproduce**
1. Have devices not yet discovered in ZJS2M
2. Call getNodes API via MQTT
3. Observe string-types for what's usually integers

**Expected behavior**
Types for properties in JSON stay consistent. If values are not known, exclude them or set them to `null`. 

**Additional context**
N/A

**Comment by robertsLando** [comment]
@LordMike Would you prefer them to be undefined instead?

**Comment by robertsLando** [comment]
@LordMike Just to know, are you using this in a JS application? Because you could simply check `!!node.manufacturer` to se if it is set or not as `''` is `false`

**Comment by LordMike** [comment]
I'm interpreting this in .NET / C#, it has a hard time when types change. :)

I'd prefer if the values were not present. This makes the json smaller, while also indicating that "the value was not known". Alternatively, if it's needed for discovery (that a value might exist), it could be set to `null`.

**Comment by robertsLando** [comment]
@LordMike Fixe on master :)
