### ISSUE TITLE
[feat] Driver status to mqtt

### ISSUE THREAD

**Issue by robertsLando** [zwave-js/zwavejs2mqtt#1840]
Ref: https://github.com/zwave-js/node-zwave-js/issues/3509#issuecomment-943095220

- [x] driver status when service is working normally --> normal updates to mqtt
- [ ] driver status when service gets killed/times out --> set last will on that topic to set the driver status to false

- [ ] driver status when service exists normally --> before mqtt disconnect set that status to false

**Comment by robertsLando** [comment]
@vladbabii about points 2/3 here, what mqtt broker are you using?

**Comment by vladbabii** [comment]
I don't see how last will would not be published unless 
1. broker dies - in which case all clients should assume the zwave is dead (unreachable by clients anyway)
2. you normally disconnect and don't publish anything before

$SYS is a good alternative if you know the client id or some other information about  that client, but last will works very well.

Some background: 
I've been running something like this in my home for the past 3 years and it works fine -- but it's a very complex setup, i use home assistant as zwavejs and nodered as mqtt2js, 5 copies of each for 5 zwave sticks. Zwave2mqtt would make things much simpler and elegant. I will just need to add a second docker to check status and if needed reboot the network device or ser2net with the zwave chip via ssh - there were cases when the zwave chip itself got in a bad state and no serial connection (local or remote) worked anymore and had to power cycle.... So by having zwavejs2mqtt and the "helper" container i can identify any issues, fix them without any user intervention.

**Comment by robertsLando** [comment]
@vladbabii I know how MQTT works, and also brokers (I help maintain some brokers and mqtt related stuff here in github too) I just prefer to avoid will topics when possible as I had problem in past expecially because when you send the message before disconnect there could be delays in client close process (or stuck the process at all) expecially when using persistent mqtt stores. 

BTW the client id is fixed as it depends on the name you set in settings, this is why I asked you if it could be possible to look at it, it's just more reliable then the other solution based on my experience
