### ISSUE TITLE
[bug] UI for a dimming duration shows "[object Object]"

### ISSUE THREAD

**Issue by LordMike** [zwave-js/zwavejs2mqtt#185]
**Version**

Build/Run method
- [x] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build ) 

zwavejs2mqtt version: v1.0.0-alpha.2

**Describe the bug**
A wall switch with built in dimmer (ZDB5100 Matrix) has a multilevel switch section in ZJS2M. In the UI, the duration parameter shows up as `[object Object]`. In the `getNodes` json, I see that the value of this field is:

![image](https://user-images.githubusercontent.com/1027111/104109915-d2e89600-52d2-11eb-95a7-50f188b732cb.png)

The UI probably doesn't handle the value+unit combo very well. :)

**To Reproduce**
N/A

**Expected behavior**
A dropdown or selector (maybe?) for value+unit... I expect only the value is settable, so maybe just display the unit next to the input box?

**Additional context**
Screenshot of the UI with the JS object outputted:

![image](https://user-images.githubusercontent.com/1027111/104109893-9c128000-52d2-11eb-9a71-3bb3ecf0bd30.png)

**Comment by robertsLando** [comment]
@LordMike Uh never saw this! I think it comes from last updates? I have durations values too but them were not showed in that way on ui. @AlCalzone Breaking change from 6.0.0?

**Comment by AlCalzone** [comment]
Nothing changed in that regard. `Duration` is not a primitive value, but you can use `toJSON()` or work with its properties directly: https://github.com/zwave-js/node-zwave-js/blob/b1df89733dc088ae6084b6a97516db4736a5641b/packages/core/src/values/Duration.ts#L73-L80

**Comment by AlCalzone** [comment]
Basically you need to select/edit both the value (0-127) and the unit (minutes/seconds)

**Comment by robertsLando** [comment]
Humm I think I need to parse it in a different way. When I set it should I pass a Duration on the setValue too?

**Comment by AlCalzone** [comment]
Probably, but you cannot set the duration yet. https://github.com/zwave-js/node-zwave-js/issues/1321

**Comment by robertsLando** [comment]
@AlCalzone Just to knnow but wouldn't a `type: Duration` be more appropiated instead of `any`?

**Comment by AlCalzone** [comment]
good point. I've treated `"any"` more like a: You cannot be sure what comes here, better check before assuming.
For non-primitive values it could make sense to add new keys.

**Comment by robertsLando** [comment]
@LordMike So keep this open until the support is available on zwave-js

**Comment by LordMike** [comment]
My 0.02$ would be not to make the available types more complex than primitives. So I wouldn't add a "duration-with-minute-and-seconds" type, that supports "minutes" and "seconds", only to add one that also supports "hours" later when a device comes along supporting that.

I would do one of two things:

* Work with a concept of "timespans", like "5s" or "10m". When you get "5 seconds" from the device, you emit "5s" (as a string). Likewise, setting it to "1h" submits "1 hour" to the device.
  * This gets even better for usability, if the device f.ex. doesn't support hours. You can convert "1h" into "60m" or "3600s" before sending it.
* Expose this as two separate values, one as an integer and one as a list of units. It sucks due to the extra set of messages though.

**Comment by AlCalzone** [comment]
How would you configure a value of 127 seconds with that approach? 
Not trying to argue against it, just discussing the dirty details of zwave.

**Comment by LordMike** [comment]
"127s" or "2m7s" .. both are identical. The tricky part (for you) is distilling that down to a value that z-wave can work with, and abiding by any limitations by the device. 

You obviously can't send that as a z-wave value, in anything but seconds. If you were to send it as minutes, the best you could do was "120s" (2 minutes).. I don't imagine the message supports floats :)

**Comment by AlCalzone** [comment]
I'm wondering if that is intuitive that you can set 2m7s but not 2m8s (which cannot be represented and AFAIK all durations have the same encoding).

**Comment by LordMike** [comment]
If they're all in the low end or represented by seconds, why not just skip the unit and go with a "number" ?

I imagine validation comes naturally for numbers, with the min/max values. 

Ooh, the 128..255 values are then minutes?

If so, the seconds can still work, but validation will be trickier. You could simply log an error and not send the message, if a user puts in 179 seconds, instead of a valid value of 180 seconds.

**Comment by AlCalzone** [comment]
> Ooh, the 128..255 values are then minutes?

Yep that is the tricky part. When setting a duration:
![grafik](https://user-images.githubusercontent.com/17641229/104243793-6bad1c00-5461-11eb-9189-61eba794e6ce.png)

and when decoding a report:
![grafik](https://user-images.githubusercontent.com/17641229/104243816-79fb3800-5461-11eb-9283-0a670591773a.png)

So just using a number won't work (well it will, but it is suuuuper unintuitive). I kinda like going with a hybrid approach:
* Keep Duration objects, but give library users a way to work with them (https://github.com/zwave-js/node-zwave-js/issues/1348 as a first step)
* Add a method to serialize them as either a timespan string like you proposed or the current object format
* Add a method to deserialize them from a timespan string or the current object format. Trying to use an invalid combination will throw.

Devs can then decide whether they need to work with timespan strings, value+unit objects or the original Duration object.

**Comment by LordMike** [comment]
Will all Durations be like that?... Like _all_ ? I would be worried that suddenly a device comes along, which operates in increments of 10s.

So one third way is simply to expose the 0..255 value. :) Additional metadata / functions could then help users in translating between timespans, Durations, or something else entirely. 

Anyhoo, if it's always minutes and seconds, it's probably fine. Let's hope a `Duration2` doesn't appear :D

**Comment by AlCalzone** [comment]
> So one third way is simply to expose the 0..255 value

I don't like exposing values which need additional interpretation. The aim of a library is to abstract away the ugly details (or at least make them intuitive to work with). I think we're on a good way with the additions to Duration.

**Comment by robertsLando** [comment]
I think that Duration value is good, I just think that the type should be `Duration` and not `any`
