### ISSUE TITLE
5.9.0 not sending data to Home Assistant

### ISSUE THREAD

**Issue by Altycoder** [zwave-js/zwavejs2mqtt#1863]
### Version

**Checklist:**

- [x ] I am **not** using Home Assistant. **Or:** a developer has told me to come here.
- [ x] I have checked the troubleshooting section and my problem is **not** described there.
- [ x] I have read the changelog and my problem is **not** mentioned there.

Build/Run method

- [ x] Docker
- [ ] PKG
- [ ] Snap package
- [ ] Manually built (git clone - yarn install - yarn run build )

Zwavejs2Mqtt version: 5.9.0
Z-Wave JS version: not obvious where this is in control panel

### Describe the bug

5.9.0 not sending data to home assistant, rolling back to 5.8.0 immediately solves issue. No obvious errors in the log.

Sensors in HA appear frozen in their state, if I restart mosquitto or HA they report no data at all.

### To Reproduce

Move from 5.8.0 to 5.9.0

### Expected behavior

5.9.0 should work as 5.8.0

### Additional context

None

Please let me know what else I can attach for debugging purposes

**Comment by robertsLando** [comment]
let's wait for new zwavejs update to see if it's still broken or not

**Comment by Altycoder** [comment]
I haven't dared upgrade beyond 5.8.0 yet as upgrading this image is always potluck.  

Whilst I appreciate your efforts on making zwavejs2mqtt available for free ( :-) ), there needs to be a beta channel for testing before you push things out to latest.  I run around 20 docker containers and this one is by far the most unreliable with quite frequent breakages.

I should be able to test the latest latest version on Monday but can't right now so am pinned to 5.8.0.

**Comment by robertsLando** [comment]
@Altycoder I'm sorry for this, there is some things BTW that doesn't depend on me, most of this is caused by changes on the underlying zwave-js

**Comment by Altycoder** [comment]
@robertsLando I understand that, that's why moving to a beta release, with a corresponding stable release after 1-2 weeks of testing would be beneficial?

I've tried 5.10.1 this morning and it seems to work so far (2 min of testing)

**Comment by robertsLando** [comment]
> I understand that, that's why moving to a beta release, with a corresponding stable release after 1-2 weeks of testing would be beneficial?

Could make sense, yes :) I need to understand how I could manage this on docker as now tags point to releases

**Comment by Altycoder** [comment]
@robertsLando could you not tag each new release as "beta" and move the previous release from "beta" to "stable" rather than "latest" once you know that there aren't any issues?  That way most users can track "stable" rather than "latest" which can be a bit too bumpy.  I now pin my zwavejs2mqtt container to a specific release (e.g. 5.10.1 now) and then check on here for issues before I move up a release.  By moving to beta/stable you'd effectively be doing the same which would give most users a much smoother ride.

However you would need a number of users to be willing to track "beta" and provide feedback otherwise this wouldn't work.

**Comment by Altycoder** [comment]
Hi, I think I spoke too soon, 5.10.1 still isn't sending data to home assistant correctly.  I've just moved to the new HA stable image and all my zwave sensors are unavailable after 10 min.  Moving back to 5.8.0 fixes immediately.

**Comment by robertsLando** [comment]
@Altycoder JTK are you using mqtt discovery or hass integration?

**Comment by Altycoder** [comment]
mqtt discovery (Mosquitto broker)

**Comment by robertsLando** [comment]
Is store flag enabled under mqtt settings?

**Comment by Altycoder** [comment]
Yes

**Comment by robertsLando** [comment]
Ok that's the problem. Iin 5.9.0 I swithed from mqtt nedb store to level store because nedb is bugged and the package wasn't maintained anymore, turns out also level store is bugged, in next releases I simply disable persistent storage on backend side until I found a working store (I think I may need to implement my own as there aren't other alternatives right now).

**Comment by Altycoder** [comment]
So those of us using home assistant should stay pinned to 5.8.0 or should it work if we disable the store flag?

**Comment by robertsLando** [comment]
> So those of us using home assistant should stay pinned to 5.8.0 or should it work if we disable the store flag?

Last version should work as I have disabled store

**Comment by Altycoder** [comment]
Just moved to 5.11.0 and store is enabled under z-wave settings, does this matter or should I turn it off?

I'll report back later or tomorrow if it works with HA or not as sometimes it takes a little while to fully test.

**Comment by robertsLando** [comment]
>  does this matter or should I turn it off?

Nope, it's disabled at all in MqttClient code, so enabled or not in settings it doesn't change

**Comment by Altycoder** [comment]
Seems to be working fine now, thanks
