### ISSUE TITLE
[feat] DSK input improvements

### ISSUE THREAD

**Issue by jmgiaever** [zwave-js/zwavejs2mqtt#1895]
**Is your feature request related to a problem? Please describe.**

There seems to be a very short time-frame (down to 8 seconds) to enter the DSK and confirm it, when adding some device with S2_*.

**Describe the solution you'd like**

Suggest the following UI improvements, to be able complete the process more quickly:

- Auto focus the DSK input field when it appear
- Allow submitting the DSK with the enter-key
- Display a numeric keyboard on mobile phones

**Comment by hanerd** [comment]
Adding the DSK as a field when starting inclusion would be brilliant. 

I'm also curious how you'll be handling SmartStart (which it appears made it out today). Will that be accessible via mobile devices?

**Comment by robertsLando** [comment]
We are still thinking about the best way to integrate smart start in application :)

**Comment by jmgiaever** [comment]
Ok. Does it mean that the PIN way of doing thing, will disappear? 

We'll see how Smart Start work. I understand there's two ways of inclusion with Smart Start. One with the QR code and one where a button push to confirm the inclusion (or something) on the device? 

I would prefer the PIN over the QR code, as the QR code way would require me to partly unmount most S2 main powered devices if I want to re-include them. 😅
