### ISSUE TITLE
Mini Motes and CommandClass 48 no longer reporting to MQTT

### ISSUE THREAD

**Issue by jbardi** [zwave-js/zwavejs2mqtt#1897]
### Version

**Checklist:**

- [x] I am **not** using Home Assistant. **Or:** a developer has told me to come here.
- [ ] I have checked the troubleshooting section and my problem is **not** described there.
- [ ] I have read the changelog and my problem is **not** mentioned there.

Build/Run method

- [x] Docker
- [ ] PKG
- [ ] Snap package
- [ ] Manually built (git clone - yarn install - yarn run build )

Zwavejs2Mqtt version: 5.10.1
Z-Wave JS version: 8.6.1

### Describe the bug

All docker images of zwavejs2mqtt since version 5.9.0 no longer report changes with CommandClass 48 (binary sensors) and Mini Mote _EVENTS to MQTT. This causes all our binary tilt sensors and Mini Mote actions to not make their way to Node-Red via MQTT. The zwave logs are reporting CommandClass 48 and MiniMote changes, they are simply not being pushed over to MQTT.

### To Reproduce

1. Use any docker image of zwavejs2mqtt from version 5.9.0 to version 5.10.1 and both device types stop reporting to MQTT
2. Switching back to image version 5.8.0 results in both device types once again reporting correctly to MQTT

### Expected behavior

Mini Mote _EVENTS and Binary Sensor state changes that use CommandClass 48 should have their changes being sent over to MQTT

**Comment by robertsLando** [comment]
This should be fixed on master now
