### ISSUE TITLE
[feat] Formatting of timestamps (and other values)

### ISSUE THREAD

**Issue by LordMike** [zwave-js/zwavejs2mqtt#190]
**Is your feature request related to a problem? Please describe.**
Timestamps are currently formatted as AM/PM and some variation of dates.. I'd like to be more ISO8601-ish.

I tried setting my browser language to danish, which shouldn't use AM/PM, but with no change on the site.

I'm using `v1.0.0-alpha.2`

**Describe the solution you'd like**
Formatting configuration for units / dates / times ..

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by robertsLando** [comment]
You mean in logs?

**Comment by LordMike** [comment]
No, the UI. This is Z2M, but it has the same issue.. :)

![image](https://user-images.githubusercontent.com/1027111/104227840-4b259780-544a-11eb-86b9-58ce1960eb38.png)

**Comment by robertsLando** [comment]
Actually I'm using: https://github.com/zwave-js/zwavejs2mqtt/blob/master/src/components/nodes-table/index.vue#L88

That is: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleString

IMO this format is mostly user friendly, would you prefer it to be 24h ?

**Comment by LordMike** [comment]
Hmm.. (I would prefer it .. but the issue is elsewhere)

I should already be seeing it in 24h, but apparently my browser doesn't think that.

**Comment by LordMike** [comment]
Hillarious. Edge shows it in 24h + Day/month/year - Chrome/FF shows it in 12h (and month/date/year)..

This is likely a browser thing then.
