### ISSUE TITLE
[question] Best way to deal with device file that didn't migrate

### ISSUE THREAD

**Issue by tommyjlong** [zwave-js/zwavejs2mqtt#191]
I'm looking to migrate over from ZWave2MQTT to ZWavejs2MQTT.
I'm looking at the device files and it appears that all my devices are supported except for one.

[zwave-js FortezZ devices](https://github.com/zwave-js/node-zwave-js/tree/master/packages/config/config/devices/0x0084)
versus
[OpenZWave FortrezZ devices](https://github.com/OpenZWave/open-zwave/tree/master/config/fortrezz)

In particular the fts05p.xml did not get migrated over (or hasn't yet migrated).

What is the best way to deal with this?
If its the case that the migration will be done, just hasn't happened yet, then that's OK.
However if there is no plan to migrate it over, I would like to give it a go.
I have looked at the [developer config-files](https://zwave-js.github.io/node-zwave-js/#/development/config-files) for starters.

**Comment by jcam** [comment]
Best would be for you to make a device file! There isn't clarity from the OZW guy yet whether we can bulk import OpenZWave device configs (see https://github.com/zwave-js/node-zwave-js/pull/1112), which is why it hasn't happened yet. Unfortunately the licenses are not currently compatible.

**Comment by tommyjlong** [comment]
OK...I'm not a node developer, so not familiar with the development environment.
Here is what I have done so far:
1. Created a new device `fts05p.json` file.
2.  Followed the [directions ](https://zwave-js.github.io/node-zwave-js/#/development/installing-from-github) for downloading and building a local zwave-js repository.
3. Placed my fts05p.json file in the same directory with all the other FortrezZ device files.
4.  Followed the [directions ](https://zwave-js.github.io/node-zwave-js/#/development/config-files?id=contributing-configuration-files) for updating the index file and running lint.

I see the device index file did populate json attributes of my fts05p.json file, and no errors were reported from my file.
As a sanity check I created an error in fts05p.json and re-ran lint and it flagged the error.  

So I think my fts05p.json file is now ready to be tested with zwavejs2mqtt.

What would be my next steps for getting my `fts05p.json` (and I guess the updated device `index `file) into zwavejs2mqtt?  
I suppose I could copy the fts05p.json and the updated index file into the location where zwavejs2mqtt installs the zwave-js node_modules? or is there a better way?

**Comment by robertsLando** [comment]
@tommyjlong There is a command that help you to start with a device config file translated from the ozw one. 

Check https://github.com/zwave-js/node-zwave-js/pull/1243#issue-544762844

**Comment by tommyjlong** [comment]
The following worked
`$npm run config -- import -s ozw -Dmid --ids 0x0084-0x020e-0x00a3`
This created a fts05p.json file that I have working with zwavejs2mqtt.
Shall I submit a PR for the new file?

**Comment by robertsLando** [comment]
Absolutely!
