### ISSUE TITLE
[bug] - HASS entity naming convention not respected...

### ISSUE THREAD

**Issue by Swiftnesses** [zwave-js/zwavejs2mqtt#193]
Running latest docker 'dev' version.

I've set the entity naming convention of 'zwave_%nid_%o', but when I add a name and location (to be sent as part of the info), it renames the entities too?

I'd expect that the name and location appears in the dashboard and is sent when the option 'include node info', but the entities follow the naming convention set...

**Comment by robertsLando** [comment]
> I've set the entity naming convention of 'zwave_%nid_%o', but when I add a name and location (to be sent as part of the info), it renames the entities too?

Yes but you need to rediscover the all nodes or restart the application (by save settings again for example) in order to get all the entities uypdated

**Comment by Swiftnesses** [comment]
I do that, but that's the issue. When I rediscover them it adds the name and location to the entity name -  I expect it shouldn't, as I've set a naming convention I want respected?

**Comment by robertsLando** [comment]
> When I rediscover them it adds the name and location to the entity name

@billiaz ?

**Comment by billiaz** [comment]
@Swiftnesses Currently this is how it works, which probably is not right.
The entity name on your example should be: zwave_<1-255>_<objectId>

I will check what breaks on rediscovery! even though I did not have any issue to this!

Two questions
1. Is this a discovery from custom devices (customDevices.json), non custom or Both!?
2. What container you run on? and date of container. You can also give me the container hash, to be sure latest dev runs.

Thanks

**Comment by robertsLando** [comment]
Maybe would be useful to see the actual gateway settings?

**Comment by billiaz** [comment]
also could be. I will test this on my nodes now!
Will perform a rediscover node and see if this happens, as I use different than standard naming setup

Tested:
In my latest dev (yesterday build) I do not face this on non CustomDevices

**Comment by larstobi** [comment]
After updating to yesterdays dev image, I'm not seeing this anymore. Not sure what was fixed in the last three days, but it seems to have worked. :-D

**Comment by Swiftnesses** [comment]
I'm not convinced this is fixed, either that or my expectations are not aligned with how it should work.

<img width="585" alt="Screenshot 2021-01-13 at 19 12 50" src="https://user-images.githubusercontent.com/1001877/104498309-6ec81980-55d3-11eb-9157-c15711b7c1e5.png">
<img width="1207" alt="Screenshot 2021-01-13 at 19 12 41" src="https://user-images.githubusercontent.com/1001877/104498312-78518180-55d3-11eb-99aa-7dd0dfe5bb69.png">
<img width="353" alt="Screenshot 2021-01-13 at 19 10 36" src="https://user-images.githubusercontent.com/1001877/104498313-6ff94680-55d3-11eb-9145-ef39df53de67.png">

As you can see, the MQTT topic still includes the location, as does the entity name (the entities themselves look fine).

**Comment by billiaz** [comment]
@Swiftnesses I do not understand your second and third screenshots, where these come from, they are so well cropped i need more details.

**Comment by Swiftnesses** [comment]
Sorry @billiaz - 2nd screenshot is showing the mqtt topic, the 3rd shows the entity in Home Assistant.

**Comment by billiaz** [comment]
I found where is happening. I will create a patch for this @robertsLando will need to review with me the solution.

**Comment by Swiftnesses** [comment]
Thank you :)

**Comment by billiaz** [comment]
@Swiftnesses if you can compile the branch:  `fix-hass_ignoreLoc` 
it would be helpful to get your point of view

**Comment by robertsLando** [comment]
Done

**Comment by Swiftnesses** [comment]
Just reployed the dev docker and this looks fixed. Awesome work guys - thank you!
