### ISSUE TITLE
[question] Possible to convert values from 0-99 to 0-100?  (ie. force 0-100 value range?)

### ISSUE THREAD

**Issue by sofakng** [zwave-js/zwavejs2mqtt#1934]
Is it possible to have zwavejs2mqtt force/convert a value range of 0-100 instead of 0-99?

For example, I have several Z-Wave bulbs (Zooz) that only support a maximum brightness of 99.  There is a configuration parameter to modify this but it doesn't support value 100.

The problem is that another system I'm using (Homebridge MQTT-Thing) only supports a value range of 0-100.  The other problem is that if you send value 100 to these Zooz bulbs it's simply ignored and doesn't modify itself to use value 99.

**Comment by kpine** [comment]
99 is the maximum level brightness defined by the Z-Wave Specification, which is why it doesn't work. It's not just Zooz.

**Comment by sofakng** [comment]
Ahhh, OK ... Thanks for the information!

**Comment by kpine** [comment]
I don't use MQTT, but you can parse incoming values. If you want to send 100, just setup a parser to convert 100 to 99, or whatever logic you want. I haven't tried it, but I think that's the purpose.

![image](https://user-images.githubusercontent.com/791794/140579073-e62c2e98-48a5-4082-a8b0-e7760ba14533.png)

**Comment by sofakng** [comment]
Oh, that's interesting and I didn't know about it.  Thanks so much!

I wonder why Z-Wave chose 99 instead of 100 as the maximum.  It seems to make more sense to set something to 100% brightness rather than 99.

I understand 0-99 is actually 100 values, but 0 brightness should be the same as 'off'.

**Comment by robertsLando** [comment]
You should use `value` instead of `v` but what @kpine suggested is correct
