### ISSUE TITLE
[bug] Import QR opens the camera

### ISSUE THREAD

**Issue by jmgiaever** [zwave-js/zwavejs2mqtt#1936]
### Version

**Checklist:**

- [x] I am **not** using Home Assistant. **Or:** a developer has told me to come here.
- [x] I have checked the troubleshooting section and my problem is **not** described there.
- [x] I have read the changelog and my problem is **not** mentioned there.

Build/Run method

- [ ] Docker
- [ ] PKG
- [x] Snap package
- [ ] Manually built (git clone - yarn install - yarn run build )

zwavejs2mqtt: 5.11.0.474d303
zwave-js: 8.7.5

### Describe the bug

Import QR on a smart phone opens up the camera instead of the file explorer. 

### To Reproduce

1. Go to Manage nodes
2. Click on Inclusion
3. Scroll down to Smart Start and select «Import».
4. Camera opens and not the file explorer

### Expected behavior

Should open the phone (default) file explorer so you can pick from the gallery.

**Comment by robertsLando** [comment]
@jmgiaever Are you on an iphone or an android phone? From iphone you should be able to press on bottom left bottom to add it from library

**Comment by jmgiaever** [comment]
Android 😅

**Comment by jmgiaever** [comment]
![Screenshot_20211108-155924.jpg](https://user-images.githubusercontent.com/7188121/140765195-cacc9aec-1a33-46c9-9cb6-10165f2057f1.jpg)

Is the icon you're referring to here? I've tried to click the "drop here" icon, but that's what opening up the camera app.

**Comment by doug62** [comment]
I am an iPhone user, SCAN doesn't do anything, IMPORT and then click Drop.... Turns camera on and takes a photo (not properly labeled but I like this).

**** HOWEVER! - It fails to recognize/find a QR/DSK code.

**Comment by jmgiaever** [comment]
Scan should work as you like the import feature. The camera should open. Have you maybe denied access to the camera? 

The first time you've visited the scan section it (z2m in your browser) will ask for permission to use your camera. If you deny access it will not load.

**Comment by robertsLando** [comment]
Please give a try to https://github.com/zwave-js/zwavejs2mqtt/pull/1956

BTW Are you running it using https?

**Comment by jmgiaever** [comment]
Me or @doug62 ? I'm running it behind a reverse proxy. Z2m itself is http, but I always request it over the reverse proxy since I've blocked every other ports on this device.

**Comment by robertsLando** [comment]
It was for @doug62 

BTW the PR attached should fix all the issues expect the `**** HOWEVER! - It fails to recognize/find a QR/DSK code.` , I have no clue about that as all my qr codes are correctly parsed. I would need the qr code to test

**Comment by doug62** [comment]
![t](https://user-images.githubusercontent.com/5632034/141303345-e97a5c21-c118-4ce0-93d9-53c7da87e83d.jpg)
@robertsLando I attached the file to an earlier bug #1958 but attached here as well, I have tried 5 different codes, my phone parses them but zwavejs2mqtt doesn't.  Thanks for your awesome work, I'm hankering to contribute when i get more up to speed w HA

**Comment by robertsLando** [comment]
@doug62 In fact I'm able to add it when scanning from camera but not when adding it as an image (weird). Let me investigate

**Comment by robertsLando** [comment]
@doug62 I have a feel the problem is that the QR code is too big in the image and the detect fails, just to make a double check could you try to make a new picture of it?

**Comment by robertsLando** [comment]
Just tried to use this (simply reduced browser zoom and made a screenshot and it is working: 

![Schermata da 2021-11-11 14-25-43](https://user-images.githubusercontent.com/11502495/141306065-6d9232e9-e579-4774-b644-cafd4dda5489.png)
