### ISSUE TITLE
[bug] Show 100% instead of off immediately after dimmer is turned on

### ISSUE THREAD

**Issue by mwolter805** [zwave-js/zwavejs2mqtt#1937]
### Version

**Checklist:**

- [X] I am **not** using Home Assistant. **Or:** a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is **not** described there.
- [X] I have read the changelog and my problem is **not** mentioned there.

Build/Run method

- [X] Docker
- [ ] PKG
- [ ] Snap package
- [ ] Manually built (git clone - yarn install - yarn run build )

Zwavejs2Mqtt version: 5.10.1
Z-Wave JS version: 8.6.1

### Describe the bug

Hello,
This is not a new issue. It has happened for as long as I can remember (many months). Zwave and all devices are working fine, this is more of a usability issue. 

The issue is, if a dimmer (multilevel switch) is turned on from the UI, the device is not indicated as "on" in the UI for several seconds. The physical device is turned on immediately, it's only the indication in the UI that is delayed. It does not happen when the same dimmer is turned off. Turning the device off is indicated immediately in the UI.

This only happens with dimmers and not with switches and other devices. Their "on" indication is received immediately.

This delayed indication happens with both the zwaveJS2mqtt interface as well as home assistant and causes confusion since the user does not think the device is turned on. They end up trying to turn the device over and over until the UI updates several seconds later. It appears this delayed indication comes from zwaveJS2mqtt and is then communicated to downstream clients (home assistant).

In this screenshot, the value 255 was sent to the device, then several seconds later the value 255 appeared. However, sending 0 was indicated immediately.
![Screen Recording 2021-11-05 at 3 51 51 PM 2](https://user-images.githubusercontent.com/24851651/140593149-0ae31bb1-add1-41c7-abc4-1702059a1d6e.gif)

In this screenshot, the device was only turned on once. However, you can see it immediately turns off by itself, then turns on approx five seconds later.
![RPReplay_Final1636156055 2](https://user-images.githubusercontent.com/24851651/140593166-71ad68cd-48fc-456a-8fb2-8841479ad150.gif)

### To Reproduce

1. Go to the dimmer in the zwaveJS2mqtt UI
2. Expand Multilevel Switch
3. Type "255" in target value
4. Press the triangle to send the value.
5. Wait five seconds for value to show 255.

### Expected behavior

Would like for the device to be indicated as "on" immediately instead of "off" after the value is sent. In my previous home automation system (homeseer) the dimmer was immediately indicated as 100% on, then a few seconds later the indication showed the actual dim level. So after the user turned on the device, the indicator showed 100%, then dropped to the actual dim level (ie 25%). 

This was much more user friendly and more consistent with other devices that indicate status immediately as the current operation confuses users and they end up clicking the button again. 

[zwavejs2mqtt-store_2021-11-05.zip](https://github.com/zwave-js/zwavejs2mqtt/files/7489524/zwavejs2mqtt-store_2021-11-05.zip)

**Comment by blhoward2** [comment]
This is a known issue and isn't ours. This is an HA UI issue.

https://github.com/home-assistant/core/issues/47388#issuecomment-791820724

**Comment by mwolter805** [comment]
Hello @blhoward2,
Thank you for the reply. Wouldn’t a fix be zwaveJS2mqtt assuming 100% until the actual brightness is received from the device? Imagine this could be helpful for mqtt integrations as well.

**Comment by blhoward2** [comment]
Us assuming 100% would fix it, but we're not going to do that. We have to maintain compatibility with different UIs and it's an HA issue. The driver isn't going to report false information.

**Comment by mwolter805** [comment]
created https://github.com/home-assistant/core/issues/59379 🤞
