### ISSUE TITLE
[feat] Add HTTPS control within the UI Settings

### ISSUE THREAD

**Issue by blhoward2** [zwave-js/zwavejs2mqtt#1947]
Presently, you can enable https only via an environment variable. Addon users cannot set the environment variable, though, and https is likely to be of greater interest to support cameras for SmartStart.

I think that we should add options to enable https, and to specify the SSL cert/key (to enable central certificates to be used) to the Settings UI.

If a user clicks to use the camera and we aren't running https, we should consider displaying a message to the user explaining that limitation.

**Comment by myklup** [comment]
I believe this feature is unintentionally locking people out of zwavejs2mqtt that didn't know it was more involved than "check this box" as seen here https://github.com/hassio-addons/addon-zwavejs2mqtt/issues/309

**Comment by blhoward2** [comment]
I don't think this is our issue. @frenck makes modifications for ingress to work in the addon and that seems to be breaking this.

**Comment by frenck** [comment]
With ingress HTTPS is provided by Home Assistant. Not zwavejs2mqtt or the addon.

**Comment by blhoward2** [comment]
I edited my comment. I agree but the issue seems to be that we have a UI option for other installs to allow https. I'm not sure that we could fix that at all on our end.

**Comment by blhoward2** [comment]
Maybe we could detect we're running in your docker and then disable the setting. I'm not sure what modifications you make. Is there a file or something inside the container that is unique that we could look for to know we're in your docker and not ours?

**Comment by frenck** [comment]
> I'm not sure what modifications you make.

None.

**Comment by blhoward2** [comment]
Ok. Do you build your own docker image? If so, can you touch a file for us to check for? I'm not sure how else to distinguish your image vs ours.
