### ISSUE TITLE
zwavejs2mqtt beyond 5.9.0 (5.10.0 and above) breaks usbip service

### ISSUE THREAD

**Issue by xImportExportx** [zwave-js/zwavejs2mqtt#1948]
I am sharing my wave controller via usbip on an rPI.

When I use the docker image with tag 5.10.0 or above as soon as the container starts the usbip service fails and the usb device is no longer shared to the target host. I need to do this as I run docker on a VM in my environment and just have the rPI closer to the wave devices I am trying to control.

This worked perfectly since you released zwavejs2mqtt. I tried a bunch of versions from 5.10.0 upwards all the way to the latest tag with no luck.

Let me know if I can get you any more info to assist.

**Comment by blhoward2** [comment]
If you're running zjs2mqtt, you need to disable soft reset in the settings or set the environment variable to do so. This is a known issue caused by the new soft reset functionality.

**Comment by xImportExportx** [comment]
Thank you that resolved my issue
