### ISSUE TITLE
[feat] Select camera when scanning a QR code

### ISSUE THREAD

**Issue by ArchLayperson** [zwave-js/zwavejs2mqtt#1957]
**Is your feature request related to a problem? Please describe.**
On my machine, I have four video input devices, only one of which is a webcam. When I attempt to scan a QR code, the first camera (in this case, a virtual camera) is activated, and there is nothing in the UI to switch to the actual camera.

**Describe the solution you'd like**
If multiple cameras are available, display a combobox to select the active camera.

**Describe alternatives you've considered**
I've seen browsers offer a camera selector in some cases, but I am unsure how that can be triggered.

**Additional context**
I also ran into this on a phone, where the front facing camera was selected, and it was unable to focus on the s2 barcode well enough to get a scan.
Workaround: Take a image with other software, and import that image.

**Comment by doug62** [comment]
On iPhone, camera is activated when you click drop area, doesn't find/recognize a QR/DSK.

**Comment by robertsLando** [comment]
PR ready
