### ISSUE TITLE
[bug] Power status values in the control panel UI are set "Battery level: unknown" after restarting

### ISSUE THREAD

**Issue by kpine** [zwave-js/zwavejs2mqtt#1967]
### Version

**Checklist:**

- [X] I am **not** using Home Assistant. **Or:** a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is **not** described there.
- [X] I have read the changelog and my problem is **not** mentioned there.

Build/Run method

- [X] Docker
- [ ] PKG
- [ ] Snap package
- [ ] Manually built (git clone - yarn install - yarn run build )

Zwavejs2Mqtt version: 5.12.0
Z-Wave JS version: 8.7.6

### Describe the bug

When restarting zwavejs2mqtt, the Power status for all nodes is lost and they show as `Battery level: unknown`. Only a re-interview will correct the value. However, even that is lost again after a restart.

![image](https://user-images.githubusercontent.com/791794/142069869-0b19271a-98fb-4250-b0ee-f1d312000039.png)

### To Reproduce

1. Open a browser window to the control panel
2. Restart z2m
3. Notice the WS connection is lost, and all the battery, awake/sleep status, etc. reset to unknown values 
4. Wait while the network loads, notice some icons like the awake/sleep status are updated
5. Notice the battery icons remain "unknown"
6. Refresh the browser window and everything looks OK
7. Repeat steps 2-6

### Expected behavior

The power status is shown correctly after restart.

### Additional context

I think this started occurring with release 5.11.0, but I'm not 100% sure. That's the first release I noticed.

**Comment by kpine** [comment]
Strangely enough, a battery device waking up will update the Power status, even if no battery information is provided. I guess it's triggering some kind of internal refresh in z2m? After this event the battery level is shown correctly:

```
2021-11-16 13:39:22.309 INFO ZWAVE: Node 12 CC Notification {
  type: 9,
  event: 5,
  label: 'System',
  eventLabel: 'Heartbeat',
  parameters: undefined
}
2021-11-16 13:39:22.539 INFO ZWAVE: Node 12 is now awake
2021-11-16 13:39:23.643 INFO ZWAVE: Node 12 is now asleep
```

Pinging or refreshing CC values on a mains-powered node has no effect.

**Comment by robertsLando** [comment]
@ahochsteger I think maybe the power status is only updated when battery CC event is catched?

**Comment by kpine** [comment]
I checked today and all the icons were correct. So I looked a bit more, and it appears to _only_ be an issue after you restart and keep the same browser window open. If you reload the page, or open a new tab, the icons and status will load correctly. I've updated the reproduction steps in the original issue.

The other icons and statuses update, it's only the power ones that do not.

**Comment by ahochsteger** [comment]
@kpine could you confirm that the battery status is already up-to-date if you reload the UI a minute or two after the restart?
@robertsLando I've observed this behavior on my side es well and I think it has to do that the UI doesn't get informed about the updated power status information.
Relevant are the values `isBatteryPowered`, `minBatteryLevel` and `batteryLevels`.
Any idea what the problem could be?

**Comment by robertsLando** [comment]
> and it appears to only be an issue after you restart and keep the same browser window open

IMO the problem is that the event that updates those info is for value updated and the value that updates node is node update so when those values are update we should send that event instead

**Comment by kpine** [comment]
> @kpine could you confirm that the battery status is already up-to-date if you reload the UI a minute or two after the restart?

I don't have to wait anytime at all. Once I see the battery icons go unknown, I just open another browser window or refresh the current one and they will be correct, no waiting necessary. It's only the browser window that was open _during_ the restart that never updates.

**Comment by robertsLando** [comment]
Yeah like I said it's just a matter of events, there is no event that updates the node

**Comment by robertsLando** [comment]
Fix ready in #1970. @kpine @ahochsteger could you  test that when you have a moment? much have changed and I want to be sure I didn't break anything

In my tests everything seems working BTW

**Comment by ahochsteger** [comment]
@ahochsteger I can confirm that it's working now - all battery information is updated in the UI at the same time as other columns (e.g. 'Last active').

**Comment by robertsLando** [comment]
In general now control panel should also be much more responsive as data sent to websockets arejust the essential ones (in the previous implementation I was always sending the entire node object when a node had an update and some nodes are huge considering also the values)
