### ISSUE TITLE
[bug] Sorting the node table has problems with certain edge cases

### ISSUE THREAD

**Issue by ahochsteger** [zwave-js/zwavejs2mqtt#1977]
### Version

**Checklist:**

- [x] I am **not** using Home Assistant. **Or:** a developer has told me to come here.
- [x] I have checked the troubleshooting section and my problem is **not** described there.
- [x] I have read the changelog and my problem is **not** mentioned there.

Build/Run method

- [x] Docker

Zwavejs2Mqtt version: Current master branch (based on 5.12.0)
Z-Wave JS version: 8.7.7

### Describe the bug

The sorting of some columns does not work in certain conditions, e.g.:
1. Power: Fails if there are nodes with unknown power information
2. Security, Beaming: These columns don't react on sort changes at all

### To Reproduce

1. Sort by one of the columns "Power", "Security", "Beaming"

### Expected behavior

Sorting should work in all cases, even if the value in the column is undefined.

### Additional context

I'll try to debug and fix the bug myself.

**Comment by robertsLando** [comment]
@ahochsteger FYI if you don't see some columns in controller node is because now I'm hiding them
