### ISSUE TITLE
[question] Aeotec Nanomote Quad zwave events being blocked?

### ISSUE THREAD

**Issue by tboyko** [zwave-js/zwavejs2mqtt#1990]
First, thank you for your work on this project. It's so much snappier than the old z-wave implementation.

I have an Aeotec Nanomote Quad z-wave device. When I press one of the keys, the logs show the following:

```
2021-11-25 05:05:30.077 DEBUG ZWAVE: Node 16: mapping value(s) of property 'level' (level) from CC 128 (Battery) to node property 'minBatteryLevel
2021-11-25 05:05:30.078 DEBUG ZWAVE: Node 16: mapping value(s) of property 'level' (level) from CC 128 (Battery) to node property 'batteryLevels
2021-11-25 05:05:30.078 INFO ZWAVE: Node 16: value updated: 128-0-level 28 => 0
2021-11-25 05:05:30.078 INFO ZWAVE: Node 16: value updated: 128-0-isLow false => true
2021-11-25 05:05:30.133 DEBUG GATEWAY: Skipping send of stateless value 16-91-0-scene-004: it's from cache
2021-11-25 05:05:30.134 INFO ZWAVE: Node 16: value notification: 91-0-scene-004 0
2021-11-25 05:05:31.136 DEBUG GATEWAY: Skipping send of stateless value 16-91-0-scene-004: it's from cache
```

In HomeAssistant, monitoring for `*` events in the developer tool section produces no result.

What can I do so that these value changes are not skipped? Any help is much appreciated!

**Comment by robertsLando** [comment]
@tboyko Are you using mqtt or zwavejs integration?

**Comment by tboyko** [comment]
@robertsLando In the settings section I have Z-wave and HomeAssistant enabled. I've disabled the MQTT gateway by toggling the "Disable MQTT" gateway option.

**Comment by robertsLando** [comment]
> In the settings section I have Z-wave and HomeAssistant enabled

If you mean you have zwave js server enabled it means this is handled on hass side and not by me. You should open an issue there. Dunno if @AlCalzone can help in this too but you can ignore those logs as them are on z2m side

**Comment by tboyko** [comment]
@robertsLando I may be misspeaking as I'm not totally familiar with how this project works. My understanding is that it bridges z-wave interactions to MQTT, but that it can also bridge straight to HomeAssistant using some other sort of non-MQTT protocol. I'm not positive on how I have it set up, either, which is why I shared my settings in qwavejs2mqtt, above. I believe I'm doing a z-wave (js) to native HomeAssistant integration but could be wrong.

I also believe that the issue lies in this project, as the debug message I'm receiving `Skipping send of stateless value` is [from the codebase](https://github.com/zwave-js/zwavejs2mqtt/blob/b18067abf095b12f6262b673210fc469c1f87362/lib/Gateway.ts#L1855). I assume that this project is not forwarding the event on to HomeAssistant.

**Comment by robertsLando** [comment]
This project can actually be used as control panel, mqtt gateway (if you have mqtt enabled, that's not your case), and could also init zwavejs server that can be used paired with hass zwavejs integration to control your devices directly from hass. If the problem is that

> In HomeAssistant, monitoring for * events in the developer tool section produces no result.

It means it is something related to the zwavejs server that is not forwarding events to the hass integration and I have no control of that, I just init the server but the logic inside it is out of z2m control. On my side based on the logs you shown me it seems like your device is not marked as ready for some reason BTW I would need a full log file to check why this is happening

**Comment by tboyko** [comment]
Ok, I see what you are saying, but still a bit confused on why "the logic inside it is out of z2m control" since it's in the codebase, [here](https://github.com/zwave-js/zwavejs2mqtt/blob/b18067abf095b12f6262b673210fc469c1f87362/lib/Gateway.ts#L1855). But, since I already shared that, I'm guessing that I'm missing something.

In the event that it is out of this project's control, should I be contacting the Home Assistant project?

I'm happy to provide additional logs. What is helpful?

**Comment by tboyko** [comment]
I re-paired the device with my z-wave network and the issue seems to have resolved itself. 🤦 Apologies for the trouble!

**Comment by robertsLando** [comment]
> "the logic inside it is out of z2m control" since it's in the codebase

You right in fact that comes from the codebase, but the events I manage on my side are also managed by zwavejs server: https://github.com/zwave-js/zwave-js-server

On startup of zwave client on my side if zwavejs server option is enabled I start it passing zwavejs driver as argument then everything they send to hass is managed by them, not z2m :) Glad you fixed your problem BTW, hope I have been more clear now about why I said that. If you have some problems with control panel or else let me know :)
