### ISSUE TITLE
[bug] AEON Labs Z‐Stick Gen5 USB Controller ZW090 fails firmware update

### ISSUE THREAD

**Issue by psychogun** [zwave-js/zwavejs2mqtt#2003]
### Version

**Checklist:**

- [ ] I am **not** using Home Assistant. **Or:** a developer has told me to come here.
- [x] I have checked the troubleshooting section and my problem is **not** described there.
- [x] I have read the changelog and my problem is **not** mentioned there.

Build/Run method

- [x] Docker
- [ ] PKG
- [ ] Snap package
- [ ] Manually built (git clone - yarn install - yarn run build )

Zwavejs2Mqtt version: 5.12.0
Z-Wave JS version: 8.7.6
### Describe the bug

Upgrading my AEON Labs Z‐Stick Gen5 USB Controller ZW090 fails with this error message:

```
2021-11-27 15:47:09.221 INFO ZWAVE: Calling api beginFirmwareUpdate with args: [
1,
'ZStick_G5_EU_V1_02.exe',
<Buffer 4d 5a 90 00 03 00 00 00 04 00 00 00 ff ff 00 00 b8 00 00 00 00 00 00 00 40 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ... 697294 more bytes>,
0,
[length]: 4
]
2021-11-27 15:47:09.228 INFO ZWAVE: Unable to extract firmware from file: This does not appear to be a valid Aeotec updater (invalid firmware length)! (ZW0322) beginFirmwareUpdate undefined
```

### To Reproduce

1. Go to https://help.aeotec.com/support/solutions/articles/6000252294-z-stick-gen5-v1-02-firmware-update and 'Download the correct Z-Wave Frequency of your Z-Stick Gen5.' Extract this .zip download. 
2. Expand the device in Z-Wave JS MQTT Control panel and click Advanced. 
3. Select firmware update 'BEGIN'. The Target is 0. 
4. Click OK and select the ZStick_G5_EU_V1_02.exe file.  
5. See error above message above. 

### Expected behavior

Expected behavoir is somewhere along the lines of 'SUCCESS'; https://github.com/zwave-js/zwavejs2mqtt/issues/493

### Additional context

I have confirmed by looking on the backside of the stick that I have the 'AEON Labs Z‐Stick Gen5 USB Controller ZW090' and not the 'AEON Labs Z‐Stick Gen5+ USB Controller ZW090' dongle. 

The firmware currently installed is 1.0.

**Comment by tungmeister** [comment]
Just attempted this myself with the same results.

**Comment by kpine** [comment]
At this time you cannot upgrade the firmware of a USB controller zwavejs2mqtt/node-zwave-js, that functionality is only for other nodes. You'll need to use the software provided by Aeotec.

**Comment by psychogun** [comment]
@kpine Thank you for your answer.
