### ISSUE TITLE
Is there a way to control priority for network meshing? [question] 

### ISSUE THREAD

**Issue by tamahau30494** [zwave-js/zwavejs2mqtt#2006]
I have two battery devices that are being used as 1 hop devices in my mesh. It's killing their batteries and I just had batteries go dead and had network issues because of it.

My question is, can I change the controller or zwave-js settings to not use battery devices as major mesh points?

**Comment by robertsLando** [comment]
I don't think so. cc @AlCalzone

**Comment by AlCalzone** [comment]
> I have two battery devices that are being used as 1 hop devices in my mesh

That cannot be. Only permanently-listening devices can and will be used for meshing.

**Comment by robertsLando** [comment]
@tamahau30494 could you share your z2m version and a screenshot of your network map please? A nodes dump would be good too

**Comment by tamahau30494** [comment]
Just following up on this. I needed to reset my ZWave controller and include all my nodes again. I see how the map is showing the battery devices with no mesh partners. I lost the previous configuration, but I most likely was reading the map wrong. I appreciate the help.
