### ISSUE TITLE
[feat] Allow API_KEY or USER/PASS for WS gateway

### ISSUE THREAD

**Issue by slashfoo** [zwave-js/zwavejs2mqtt#2010]
**Is your feature request related to a problem? Please describe.**
I see a way to guard the mqtt gateway, as well as http UI behind user/password, but don't see a way of guarding the WS gateway on port 3000

**Describe the solution you'd like**
Setting the gateway to authenticate against a valid HA api key, or have WS authenticate with HTTP credentials defined in the app.

**Describe alternatives you've considered**
If such mechanisms exist, a change in the documentation/settings pages.

**Additional context**
N/A

**Comment by jmgiaever** [comment]
Hi, I think you'll have to report this directly to the HA core team. This is related to the zwave-js-server which they maintain.

It's btw mentioned there, in it's repo, that they do not offer security.

**Comment by jmgiaever** [comment]
> Authentication
> Z-Wave JS Server does not handle authentication and allows all connections to the websocket API. If you want to add authentication, add authentication middleware to your Express instance or run NGINX in front of Express instance.

**Comment by kpine** [comment]
You can use Basic Auth + HTTPS, and a proxy frontend like Nginx or Traefik (I use the latter). Basic Auth works with the HA integration, although it's not documented because it's not an explicitly supported feature, it just happens to work. I suppose z2m could also implement Basic Auth, but I'm not sure it's worth it to do so since any proxy can do it.

Any other kind of authentication scheme would require changes to HA and the zwave-js-server before anything could be done here.

**Comment by jmgiaever** [comment]
Didn't know this actually. Great to know!

I've simply just blocked outside connections to the WS instance by blocking the port to it in ufw, since my WS instance is running on the same machine as HA.

Only a few ports are open from the outside.

**Comment by kpine** [comment]
I'd say most people are running the server and HA on the same network. I think HA devs have prioritized work in regards to HAOS users, which means everything is on the same host and network.

To use basic auth you just set the WS URL in the integration configuration as `wss://user@password:hostname:port`. Use `ws` if you don't use HTTPS, but I wouldn't recommend that with basic auth. The only downside to this setup is that the integration configuration page in HA shows the full URL which includes the username/password.

**Comment by jmgiaever** [comment]
Ok. Good to know, and now the TS have a few options to choose from. 

I'd recommend just blocking the port, from the outside, if it runs on the same **host**. If it's on the same network I would control access by (static) IPs. 

(Even better to block every port and just open up those that are needed, but that is another chapter)
