### ISSUE TITLE
[Home Assistant]

### ISSUE THREAD

**Issue by giovi321** [zwave-js/zwavejs2mqtt#2011]
[zwavejs2mqtt-store(1).zip](https://github.com/zwave-js/zwavejs2mqtt/files/7637324/zwavejs2mqtt-store.1.zip)

### Version

Build/Run method:

[ ] Docker
[ ] Git Clone + yarn install + yarn run build + yarn start
[x] Pkg

Zwavejs2Mqtt version: zwavejs2mqtt: 5.11.0.474d303
Z-Wave JS version: zwave-js: 8.7.5

### Describe the bug

Two main issues:
1. Nodes 8, 11, 13, 15 keep showing "unavailable" and then available on home assistant;
2. In particular, nodes 13 and 15 are respectively in "NodeInfo" and "ProtocolInfo" states every now and then

I'm using a brand new 700 Series-based Controller and the whole installation has been done from scratch (see issue #1992)

**Comment by robertsLando** [comment]
It may be related to a known issue on zwavejs side. Wait for next update

**Comment by robertsLando** [comment]
cc @AlCalzone

**Comment by robertsLando** [comment]
@giovi321 Could you submit silly level zwavejs logs please?

**Comment by AlCalzone** [comment]
> in "NodeInfo" and "ProtocolInfo" states every now and then

Every now and then? That sounds more like the cache files are getting deleted.

**Comment by giovi321** [comment]
Isn't it already at silly level? That's what I can see from the UI

**Comment by AlCalzone** [comment]
It is, yeah. There are some strange things going on:

> 2021-12-01T20:15:26.147Z CNTRLR   [Node 008] ping failed: Octal literals are not allowed in strict mode.

zwave-js doesn't use octal literals anywhere, so this must have something to do with pkg.

Then there's this constellation of commands that shouldn't happen:
```
2021-12-01T20:15:31.251Z DRIVER » [Node 013] [REQ] [SendDataBridge]
                                  │ source node id:   1
                                  │ transmit options: 0x25
                                  │ route:            0, 0, 0, 0
                                  │ callback id:      9
                                  └─[Security2CCMessageEncapsulation]
                                    │ sequence number: 252
                                    │ extensions:
                                    │ · type: SPAN
                                    │   sender EI: 0x8e8fac1255ed6abcca9ec7d64dea59d7
                                    └─[SecurityCCCommandsSupportedGet]
```
which might be a bug in the driver => https://github.com/zwave-js/node-zwave-js/issues/3833

Not sure where the cache files are located with pkg, but you should have three files with `d2857316` in the name somewhere. 
Stop zwavejs2mqtt, delete them, start zwavejs2mqtt again and make a log of that, so we can investigate further if it still goes wrong.

**Comment by giovi321** [comment]
Any clue on where to start to look for these files?

**Comment by giovi321** [comment]
Or maybe downgrade the package?

**Comment by AlCalzone** [comment]
@robertsLando Can you help?

**Comment by robertsLando** [comment]
> Not sure where the cache files are located with pkg

pkg is just a packaged version of the application, the store folder should be in the same folder of the executable so the cache files should be there

**Comment by giovi321** [comment]
Another hint would be super helpful!

**Comment by giovi321** [comment]
I tried /snap/zwavejs2mqtt/current/bin but can't find cache there

**Comment by giovi321** [comment]
The sockets keeps connecting and disconnecting now...

**Comment by robertsLando** [comment]
Oh so it's snap not pkg 😕 . I dunno about snap, should ask to @jmgiaever that is the snap package author

**Comment by robertsLando** [comment]
I think the repo is this: https://git.giaever.org/joachimmg/zwavejs2mqtt

The store folder is the mentioned `$SNAP_DATA` but I cannot find where it is set

**Comment by giovi321** [comment]
@jmgiaever let me know if you need a summary of what's going on.

**Comment by jmgiaever** [comment]
Hi, 

It's the read only filesystems in `/snap/zwavejs2mqtt/[...]`. 

The store is in `/var/snap/zwavejs2mqtt/<revision>/`. 

You can swap `<revision>` with `current` if you don't know the revision you're on. 

Sorry my late response, but I've been super busy today.

**Comment by giovi321** [comment]
No worries, actually thanks for the response.
I restarted zwavejs2mqtt and this is the log, the situation is not looking good as every node is showing no info at al
[zwavejs2mqtt-store.zip](https://github.com/zwave-js/zwavejs2mqtt/files/7643299/zwavejs2mqtt-store.zip)
.

**Comment by jmgiaever** [comment]
Did you delete the cache, as @AlCalzone? Make sure you're logging to file with the level `debug` under the Z-Wave field under settings in z2m

Stop zwavejs2mqtt

```
sudo snap stop zwavejs2mqtt
```

Delete cache

```
sudo rn /var/snap/zwavejs2mqtt/current/d285731*
```

And start zwavejs2mqtt again

```
sudo snap start zwavejs2mqtt
```

Could you also dump the information from

```
sudo snap connections zwavejs2mqtt
```

**Comment by giovi321** [comment]
That's what  I tried but all the info of all the nodes have disappeared. After some hours they started to reappear except for one Danfoss LC13 (that shows E5 on the display btw). On home assistant all the vautes are unavailable intermittently

**Comment by jmgiaever** [comment]
What is the **interview** status on all nodes?

**Comment by giovi321** [comment]
NodeInfo on 3,4,5,6,8,15,16
ProtocolInfo on 11
Sometimes some of them are Complete bu tthen go back to NodeInfo

**Comment by giovi321** [comment]
[zwavejs2mqtt-store(1).zip](https://github.com/zwave-js/zwavejs2mqtt/files/7649000/zwavejs2mqtt-store.1.zip)

**Comment by jmgiaever** [comment]
> Sometimes some of them are Complete bu tthen go back to NodeInfo

Do they go from complete randomly during run-time or between restarts?

How large is your network? How many main powered devices and how many battery powered?

**Comment by jmgiaever** [comment]
PS! Can you do an update `sudo snap refresh zwavejs2mqtt` and then give me the output from `snap info zwavejs2mqtt`

**Comment by AlCalzone** [comment]
> I restarted zwavejs2mqtt and this is the log, the situation is not looking good as every node is showing no info at al

I asked for a log directly after you delete the cache files. I'm not seeing that in the files you posted.
I am seeing many, many startups, all seemingly from the same half-interviewed state.

Please:
1. stop zwavejs2mqtt
2. delete the cache files, delete the logs
3. start zwavejs2mqtt and wait a bit
4. do nothing else
5. post the new log

**Comment by giovi321** [comment]
To answer to everyone:
@jmgiaever: completely randomly they change state, this is a gist of what you asked https://gist.github.com/giovi321/fb5aa7d5b92e4f3bdd5ba906161980a5
@AlCalzone: I followed your instructions very closely and here you can find attached the new log, hopefully I did everything right.
[backup-OpenWrt-2021-11-25.tar.gz](https://github.com/zwave-js/zwavejs2mqtt/files/7649860/backup-OpenWrt-2021-11-25.tar.gz)

**Comment by giovi321** [comment]
To answer to everyone:
@jmgiaever: completely randomly they change state, this is a gist of what you asked https://gist.github.com/giovi321/fb5aa7d5b92e4f3bdd5ba906161980a5
@AlCalzone: I followed your instructions very closely and here you can find attached the new log, hopefully I did everything right
[zwavejs2mqtt-store.zip](https://github.com/zwave-js/zwavejs2mqtt/files/7649922/zwavejs2mqtt-store.zip)
.

**Comment by jmgiaever** [comment]
Did you do the refresh?

**Comment by giovi321** [comment]
Yes I did the refresh
```
root@GC01hass:/var/snap/zwavejs2mqtt/current# sudo snap refresh zwavejs2mqtt
Fetch and check assertions for snap "zwavejs2mqtt" (260)                                                                                                             \
error: cannot perform the following tasks:
- Run configure hook of "zwavejs2mqtt" snap if present (run hook "configure": 
-----
/snap/zwavejs2mqtt/260/snap/hooks/configure: line 20: [: too many arguments
logger: socket /dev/log: Connection refused
-----)

```

**Comment by jmgiaever** [comment]
Hmmm something isn't right in your system. I recommend that you purge your install and install it again:

```
sudo snap remove --purge zwavejs2mqtt
sudo snap install zwavejs2mqtt
```

Then connect:

```
sudo snap connect zwavejs2mqtt:raw-usb
sudo snap connect zwavejs2mqtt: hardware-observe
```

**Comment by giovi321** [comment]
Will do!

**Comment by giovi321** [comment]
Thanks for the help @jmgiaever, but unfortunately I get this error message:
```
root@GC01hass:~# sudo snap remove --purge zwavejs2mqtt
snap "zwavejs2mqtt" is not installed
root@GC01hass:~# sudo snap install zwavejs2mqtt
error: cannot perform the following tasks:
- Run install hook of "zwavejs2mqtt" snap if present (run hook "install": logger: socket /dev/log: Connection refused)

```

**Comment by jmgiaever** [comment]
Which operating system is this? There's something fishy with your setup. Never seen this error before.

**Comment by giovi321** [comment]
Debian 11.1
Linux 5.10.63-v7l+ #1459 SMP Wed Oct 6 16:41:57 BST 2021 armv7l GNU/Linux

**Comment by jmgiaever** [comment]
It's strange that you have been able to install it in the past, and now you don't have access to the logger. 

Have you tried to power off and do a cold boot?

```
sudo shutdown -PH now
```

Unplug the power for a few seconds and plug it in again.

**Comment by giovi321** [comment]
I just tried to reboot earlier. Now I tried to cold boot but nothing changed :(
I don't fully understand what is the problem here...

**Comment by giovi321** [comment]
I even tried to purge snapd and reinstall everything with no success... But what is the error message saying basically? I can't get it

**Comment by jmgiaever** [comment]
Hi,

can you test running this: `logger "Hello" && journalctl -xefg "Hello"`

**Comment by jmgiaever** [comment]
> [...] logger: socket /dev/log: Connection refused)

https://unix.stackexchange.com/questions/317064/how-do-i-restore-dev-log-in-systemdrsyslog-host

**Comment by giovi321** [comment]
logger: socket /dev/log: Connection refused

**Comment by jmgiaever** [comment]
Then it's an issue outside of the Snap environment, it's actually something that is broken in your system. 

Follow my previous link and try to solve that issue first.

**Comment by AlCalzone** [comment]
@giovi321 after the fresh start, the communication looks a bit better. The interview wasn't done yet when you posted the file, but until then there was nothing that stood out.

You should still try to fix the system, in case this is the root of the issue.

**Comment by giovi321** [comment]
Ok it was as easy as a system upgrade that was very painful.
However, I cannot start zwavejs2mqtt now:
```
root@GC01hass:~# sudo zwavejs2mqtt.exec
Missing plug: «serial-port»
OPTIONAL plug
Connect with: $ sudo snap connect zwavejs2mqtt:serial-port
Missing plug: «hardware-observe»
Connect with:
$ sudo snap connect zwavejs2mqtt:hardware-observe

```

**Comment by jmgiaever** [comment]
Connect them, as described in the output, and in my previous post. 

> [...]
> Then connect:
> 
> ```
> sudo snap connect zwavejs2mqtt:raw-usb
> sudo snap connect zwavejs2mqtt: hardware-observe
> ``` [...]

**Comment by giovi321** [comment]
I get the following error:

```
root@GC01hass:/var/lib/docker# sudo snap connect zwavejs2mqtt: hardware-observe
error: invalid value: "zwavejs2mqtt:" (want snap:name or snap)

```

**Comment by jmgiaever** [comment]
/var/liv/docker? Are you inside a docker container?

**Comment by jmgiaever** [comment]
> ```
> root@GC01hass:/var/lib/docker# sudo snap connect zwavejs2mqtt: hardware-observe
> error: invalid value: "zwavejs2mqtt:" (want snap:name or snap)
> ```

Drop the space between `:` and `hardware-observe`

```
sudo snap connect zwavejs2mqtt:hardware-observe
```

**Comment by giovi321** [comment]
Sorry for going back and forth, now I'm getting the following error when I execute `sudo zwavejs2mqtt.exec`
`2021-12-03 21:52:53.879 ERROR GATEWAY: Zwave settings are not valid`

**Comment by AlCalzone** [comment]
Open the zwavejs2mqtt control panel and check the settings

**Comment by giovi321** [comment]
I can't connect to it

**Comment by jmgiaever** [comment]
```
snap set zwavejs2mqtt server.host=0.0.0.0
```
to listen on any interface, I guess. 

Not sure how your network is, but there might not be a loopback to 127.0.0.1.

**Comment by giovi321** [comment]
it has always been listening to every interface... I usually connect to the local network 192.168.1.65

**Comment by jmgiaever** [comment]
Ok.

**Comment by giovi321** [comment]
Success. Don't know how, don't know why. I have restored the nodes from the backup as well as the settings, let's see how it goes as the nodes talk.

**Comment by jmgiaever** [comment]
Good. Please close this issue now.

**Comment by giovi321** [comment]
Yes I did
