### ISSUE TITLE
TypeError: endpointGroups is not iterable

### ISSUE THREAD

**Issue by Martijn02** [zwave-js/zwavejs2mqtt#2012]
### Is your problem within Home Assistant (Core or Z-Wave JS Integration)?

NO, my problem is NOT within Home Assistant or the ZWave JS integration

### Is your problem within ZWaveJS2MQTT?

NO, my problem is NOT within ZWaveJS2MQTT

### Checklist

- [X] I have checked the [troubleshooting section](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index) and my problem is **not** described there.

- [X] I have read the [changelog](https://github.com/zwave-js/node-zwave-js/blob/master/CHANGELOG.md) and my problem was **not** mentioned there.

### Describe the bug

What causes the bug?

I'm running zwavejs2mqtt in a docker to manage my ZWave network. I have several devices, some are battery-operated. Whenever I update my zwavejs2mqtt from version 5.2.0 (node-zwave-js 7.10.0) to any higher version. (node-zwave-js 8.x) It gets in a "bootloop" where zwavejs triggers an error. 

What do you observe?

zwavejs2mqtt no longer starts because of an error produced by node-zwave-js.
```
2021-12-02T08:16:46.682Z DRIVER   Failed to initialize the driver: TypeError: endpointGroups is not iterable
                                      at ZwaveClient.getGroups (/usr/src/app/server/lib/ZwaveClient.js:440:46)
                                      at ZwaveClient._onNodeReady (/usr/src/app/server/lib/ZwaveClient.js:1927:1
                                  4)
                                      at ZWaveNode.emit (node:events:406:35)
                                      at ZWaveNode.emit (node:domain:470:12)
                                      at ZWaveNode.onReadyChange (/usr/src/app/node_modules/zwave-js/src/lib/nod
                                  e/Node.ts:478:19)
                                      at /usr/src/app/node_modules/zwave-js/src/lib/node/Node.ts:264:10
                                      at Interpreter.update (/usr/src/app/node_modules/xstate/lib/interpreter.js
                                  :265:9)
                                      at /usr/src/app/node_modules/xstate/lib/interpreter.js:110:15
                                      at Scheduler.process (/usr/src/app/node_modules/xstate/lib/scheduler.js:69
                                  :7)
                                      at Scheduler.schedule (/usr/src/app/node_modules/xstate/lib/scheduler.js:4
                                  8:10)
```
which triggers node-zwave-js to restart.

What did you expect to happen?

I expect to zwavejs2mqtt to start, and not constantly try to restart.

### Device information

The device in question that triggers the issue is:

Manufacturer: Neo Coolcam / Shenzhen Neo Electronics Co., Ltd.
Model name: NAS-DS01Z
Node ID in your network: 20

If I try to exclude the device from my network, it fails on the next battery-operated device it encounters. Before it failed on this device, it failed on a Fibaro door window sensor (fgk-101)

### How are you using `node-zwave-js`?

- [X] `zwavejs2mqtt` Docker image (latest)
- [ ] `zwavejs2mqtt` Docker image (dev)
- [ ] `zwavejs2mqtt` Docker manually built _(please specify branches)_
- [ ] `ioBroker.zwave2` adapter _(please specify version)_
- [ ] `HomeAssistant zwave_js` integration  _(please specify version)_
- [ ] `pkg`
- [ ] `node-red-contrib-zwave-js` _(please specify version, double click node to find out)_
- [ ] Manually built from GitHub _(please specify branch)_
- [ ] Other _(please describe)_

### Which branches or versions?

version: 
`node-zwave-js` version:  8.8.2
`zwavejs2mqtt` version: 6.0.1

Last working version:
`node-zwave-js` version:  7.10.0
`zwavejs2mqtt` version: 5.2.0

### Did you change anything?

no

### Did this work before?

Yes (please describe)

### If yes, where did it work?

Last working version:
`node-zwave-js` version:  7.10.0
`zwavejs2mqtt` version: 5.2.0

### Attach Driver Logfile

[zwavejs_2021-12-02.log](https://github.com/zwave-js/node-zwave-js/files/7640650/zwavejs_2021-12-02.log)

**Comment by AlCalzone** [comment]
@robertsLando you should really turn on TypeScript's strict mode:
![grafik](https://user-images.githubusercontent.com/17641229/144398267-002ea196-8604-422a-b3c2-71a656642f90.png)

**Comment by Martijn02** [comment]
Thank you very much for the quick fix. I updated my container to sha-6886825 and can confirm that this fixed the issue I had.

You guys are awesome. I'm extremely grateful for your work.

**Comment by robertsLando** [comment]
@Martijn02 Thanks 🙏🏼 😄
