### ISSUE TITLE
ZWave JS suddenly losing devices and entities names . System renaming them by itself!

### ISSUE THREAD

**Issue by Alan-Guggenheim** [zwave-js/zwavejs2mqtt#2018]
On my standard Raspberry 4 hass.io ZWave JS integration, Nortek HUSBZB-1 my automations have started suddenly to fail to execute.

I noticed then that the entities have changed name in many devices
out of 81 devices and 425 entities, about half of them show now renamed to some default name like GE Quick-fit Smart In-Wall Paddle Switch, In-Wall Smart Fan Control, In-Wall Smart Switch,...
What is causing the issue?
How to stop and avoid this?
How to fix it? (short of renaming 500+ items by hand and then losing them again?

**Comment by robertsLando** [comment]
@Alan-Guggenheim It's not something on my side, I don't have any control of what happen on hass side it looks something related to hass integration or maybe with latest zwave-js-server update. What version are you running? 

cc @raman325

**Comment by Alan-Guggenheim** [comment]
@robertsLando 
Driver Version: 8.7.7
Server Version: 1.12.0
Do you know where and by what module the devices and entities names are saved?

**Comment by robertsLando** [comment]
Home assistant repo

**Comment by Alan-Guggenheim** [comment]
@robertsLando  Thanks a lot

**Comment by jmgiaever** [comment]
@raman325 can this be related to the issue where the there's a cache-crash, and HA loose track of custom naming etc?

**Comment by jmgiaever** [comment]
https://github.com/home-assistant/core/issues/58874

**Comment by raman325** [comment]
Yes it could be related to that PR

**Comment by johntdyer** [comment]
This just happened to me again, latest version of HASS ( core-2021.12.5 ) ,.  So annoyed that I have to go back and rename 63 devices and 193 entities

**Comment by Alan-Guggenheim** [comment]
It keeps happening to me. Not all devices and entities, though.

**Comment by jmgiaever** [comment]
Hi,

This is an issue with the HA integration. That actually was fixed and closed today.

**Comment by jmgiaever** [comment]
https://github.com/home-assistant/core/issues/58874

**Comment by Alan-Guggenheim** [comment]
That would be great.

**Comment by johntdyer** [comment]
Glad to head its resolved soon... Incase others stumble across tyhis I was able to restore a core snapshot from 3 days ago and get my names back...

**Comment by jmgiaever** [comment]
Yeah. I stopped using HA for over a month because of this. New Core out today, but it doesn't seem to be included unfortunately. We might have to wait until 2022.2 (February).

**Comment by Alan-Guggenheim** [comment]
That is pretty bad news. My whole system is more and more unstable. Also I am concerned that the description of the closed issue does not seem to apply here: It mentions "Replacing a failed node removes the device and all customizations" but I did not use the replace feature. Does it apply also in other circumstances?

**Comment by jmgiaever** [comment]
Hi. If you read the whole issue and the references from other issues, then you'll see that it's related. :)

**Comment by Alan-Guggenheim** [comment]
Yes, I had not read about the related issues. Now we need to get it pushed, hopefully as an emergency update without waiting for February.

**Comment by johntdyer** [comment]
so what do we do to get this pushed along ?

**Comment by jmgiaever** [comment]
It's coming with 2022.2. February release.

**Comment by kpine** [comment]
If this problem is occurring to you, then I would recommend further debugging and analysis. It is not normal for HA to lose all the devices. The fix being discussed here will preserve the devices, but it means you have much bigger problems.
