### ISSUE TITLE
[feat] Transmit data via HTTP

### ISSUE THREAD

**Issue by pabatribick** [zwave-js/zwavejs2mqtt#2021]
It is possible, to transmit data as HTTP requests instead of MQTT?

Your platform works perfectly and without problems, so I want to use it without HomeAssistant and other things as standalone software to direct data to a website.

Or is there a known workaround for it?

**Comment by jmgiaever** [comment]
Hi, why not use the websocket to connect to HA? 
And then you can query the API of HA for whatever you want. Or you can make your website talk directly with the same websocket.  

There's an own section under settings that is just for the HA integration (zwave-js-server).

**Comment by robertsLando** [comment]
I agree with @jmgiaever, mqtt isn't something related to hass, this software is firstly born as zwave2mqtt gateway, it means you can use mqtt to do everything you need, mqtt discovery is something hass related but you can use the application without enabling it

**Comment by pabatribick** [comment]
Thanks for your fast response!

Right, I don't want to use HA because I don't need these unnecessary functions and won't overload my raspberty.

This Websockets must be connected permanently to get data, right? Are there only "Webhooks" available to send data on for example a door sensor sends action for open/close and transmit it to a website via HTTP?

**Comment by jmgiaever** [comment]
You should probably look online for a MQTT to HTTP bridge or something. Something that can stay connected to your MQTT broker and send those requests whenever changes are made.

**Comment by pabatribick** [comment]
Okay I found a "half solution" with websocket. It is possible to get the output of the websocket as JSON format?

**Comment by robertsLando** [comment]
@pabatribick What websocket are you speaking about? Zwavejs server websocket or the one used by the frontend?

**Comment by pabatribick** [comment]
Oh sorry, i forgot to write that. I meant the zwavejs server websocket. Is there a possible output for JSON format?

**Comment by robertsLando** [comment]
@pabatribick I don't maintain that and it's totally out of control the data sent. Try asking in their repo: https://github.com/zwave-js/zwave-js-server

**Comment by kpine** [comment]
> Oh sorry, i forgot to write that. I meant the zwavejs server websocket. Is there a possible output for JSON format?

The websocket API is JSON.
