### ISSUE TITLE
can't connect to stick

### ISSUE THREAD

**Issue by john55021** [zwave-js/zwavejs2mqtt#2040]
I'm not a Linux guy by any stretch. But got zwavejs2mqtt going via docker.
I used this command to download and start:
docker run --rm -it -p 8091:8091 -p 3000:3000 --device=/dev/ttyUSB0:/dev/zwave -v $(pwd)/store:/usr/src/app/store zwavejs/zwavejs2mqtt:latest

what do I use on subsequent starts?

Is it possible to make it start if the system reboots?
Thanks
John

**Comment by robertsLando** [comment]
@john55021 First question is if your device is mapped to `/dev/ttyUSB0` (you should prefer using /dev/serial path instead) also did you set the  `/dev/zwave` path in UI Zwave settings?

**Comment by robertsLando** [comment]
@john55021 I suggest you to use this method: https://zwave-js.github.io/zwavejs2mqtt/#/getting-started/docker?id=run-as-a-service

```Dockerfile
version: "3.7"
services:
  zwavejs2mqtt:
    container_name: zwavejs2mqtt
    image: zwavejs/zwavejs2mqtt:latest
    restart: always
    tty: true
    stop_signal: SIGINT
    environment:
      - SESSION_SECRET=mysupersecretkey
      - ZWAVEJS_EXTERNAL_CONFIG=/usr/src/app/store/.config-db
      # Uncomment if you want log times and dates to match your timezone instead of UTC
      # Available at https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
      #- TZ=America/New_York
    networks:
      - zwave
    devices:
      # Do not use /dev/ttyUSBX serial devices, as those mappings can change over time.
      # Instead, use the /dev/serial/by-id/X serial device for your Z-Wave stick.
      - '/dev/serial/by-id/usb-Silicon_Labs_CP2102N_USB_to_UART_Bridge_Controller_38aff6294d45eb11bf4da552b003b68c-if00-port0:/dev/zwave'
    volumes:
      - zwave-config:/usr/src/app/store
    ports:
      - "8091:8091" # port for web interface
      - "3000:3000" # port for Z-Wave JS websocket server
networks:
  zwave:
volumes:
  zwave-config:
    name: zwave-config
```

Steps:

1. Create a folder, let's call it 'z2m'
2. Create the docker-compose file inside it
3. Start application using `docker-compose up` command

Now your application will automatically start on startup

**Comment by john55021** [comment]
I so appreciate your response.First, it took several hours to get docker-compose installed. Evidently there are hardware considerations. And various suggestions failed here and there but I eventually found one command that worked. I have no idea what that was anymore. But I also have no idea how much code has been loaded onto the system from failed attempts.
So I created a file named docker-compose.yml and inserted the configuration below and followed your directions.
I should say first, that the docker version of this, ended up running out of the pi user within a folder named store that various instructions used as an example. I just want the thing to work. And, all my .json and other files are happily sitting there. So I created the docker-compose.yml file within pi/z2m
However, it failed:
zwavejs2mqtt    | /bin/sh: git: not foundzwavejs2mqtt    | 2021-12-15 00:14:41.800 INFO APP: Version: 6.1.0zwavejs2mqtt    | 2021-12-15 00:14:41.807 INFO APP: Application path:/usr/src/appzwavejs2mqtt    | zwavejs2mqtt    |  ______                       _     ___                  _   _   zwavejs2mqtt    | |___  /                      (_)   |__ \                | | | |  zwavejs2mqtt    |    / /_      ____ ___   _____ _ ___   ) |_ __ ___   __ _| |_| |_ zwavejs2mqtt    |   / /\ \ /\ / / _` \ \ / / _ \ / __| / /| '_ ` _ \ / _` | __| __|zwavejs2mqtt    |  / /__\ V  V / (_| |\ V /  __/ \__ \/ /_| | | | | | (_| | |_| |_ zwavejs2mqtt    | /_____|\_/\_/ \__,_| \_/ \___| |___/____|_| |_| |_|\__, |\__|\__|zwavejs2mqtt    |                             _/ |                      | |        zwavejs2mqtt    |                            |__/                       |_|        zwavejs2mqtt    | zwavejs2mqtt    | 2021-12-15 00:14:41.847 WARN STORE: settings.json not foundzwavejs2mqtt    | 2021-12-15 00:14:41.853 WARN STORE: scenes.json not foundzwavejs2mqtt    | 2021-12-15 00:14:41.856 WARN STORE: nodes.json not foundzwavejs2mqtt    | 2021-12-15 00:14:41.880 WARN STORE: users.json not foundzwavejs2mqtt    | 2021-12-15 00:14:41.910 INFO APP: Listening on port 8091 host 0.0.0.0 protocol HTTPzwavejs2mqtt    | 2021-12-15 00:14:42.162 ERROR GATEWAY: Zwave settings are not valid

I'm not sure if /bin/sh git not found is bad or not, and it sure would be nice to no what zwave settings are not valid.
Ok, then thinking that the configuration file wanted all this in /usr/src/app/store (I have no idea what the /usr folder is for), I changed both the ZWAVE_JS_EXTERNAL_CONFIG and zwave-config from the setting below to /home/pi/store with the .yml in pi/store. 
It failed pretty quickly with this message:


Creating zwavejs2mqtt ... error
ERROR: for zwavejs2mqtt  Cannot create container for service zwavejs2mqtt: Conflict. The container name "/zwavejs2mqtt" is already in use by container "a3a1a3d2b214ab22cd2800f2b8d2cd67abec64d84417c4fb508fdebc2a6065c9". You have to remove (or rename) that container to be able to reuse that name.
ERROR: for zwavejs2mqtt  Cannot create container for service zwavejs2mqtt: Conflict. The container name "/zwavejs2mqtt" is already in use by container "a3a1a3d2b214ab22cd2800f2b8d2cd67abec64d84417c4fb508fdebc2a6065c9". You have to remove (or rename) that container to be able to reuse that name.ERROR: Encountered errors while bringing up the project. 
One problem is, don't know if there really is a Service like there is in windows, or if this is just a feature of Docker. So I don't know how to remove or rename the container, or frankly know what a container is. I'm guessing it's all the files required to run the program, but I thought that was an image. So that's why I thought it might be a Docker issue.
Anyways, I'm lost. I've tried. This is very frustrating for a (Linux) novice. I want to see Home Assistant succeed, but it's clear that this is not for the faint of heart. I was a professional programmer who started a company and sold it at the height of the dot com era, and retired at 45. The only reason I say this is that I have a significant background in computers, I admit PC's. As a side note, my first application was on DOS. Unix was around but a computer, it's OS, and development kit was going to cost me well north of $200,000. My house wasn't worth that. And this is back in 1987. Windows came around with the whole works for under $1000, and you could talk to people at Microsoft. I, probably like a lot of people who would like to use this, don't want to take the time and effort to learn all this. I think github is a great place, and people like yourself are doing great things. But I think the community needs to step back a bit and think about their users - just my opinion.
In any case, can you help me?thanksJohn Nauman

-----Original Message-----

**Comment by robertsLando** [comment]
@john55021 AFAIK docker on windows doesn't allow you to map COM ports to docker container, at least this is what some users told me some time ago but maybe could be fixed now.

If you are using an Rpi in order to install docker you can use this command:

```bash
curl -fsSL https://get.docker.com -o get-docker.sh
sudo sh get-docker.sh

sudo usermod -aG docker $USER

docker version

# test it
docker run --rm -it hello-world
```

To clean up your docker you could do (BE AWARE THIS WILL REMOVE EVER DOCKER CONTAINER/IMAGE/VOLUME)

```bash
docker container stop $(docker container ls -aq)
docker container rm $(docker container ls -aq)
docker system prune -a
```

Now that your docker instance is cleaned try again with the steps I told you:

```
mkdir zwavejs2mqtt
cd zwavejs2mqtt
# put inside the docker-compose.yml file
docker compose up
```

**Comment by john55021** [comment]
Hi Daniel,I guess I'm confused if this is in response to my email from about 12 hours ago.  As i mentioned,  I did get docker-compose eventually installed. I followed your directions, i used the folder z2m instead of zwavejs2mqtt but everything failed as the logs showed.Are you saying i do need to clean all this up before it will work?And as I also asked, in a round about way,  where should all this be done? I created a user name,  logged in as such, but everything i do is still under user Pi. Some of the directions said to create a folder 'store' (I know there just examples) so i did,  and eventually got zwave2mqtt working with just docker. All my config files are there.  So is it still possible to reference those when using docker-compose?Sent via the Samsung Galaxy S10, an AT&T 5G Evolution capable smartphone
-------- Original message --------From: Daniel Lando ***@***.***> Date: 12/15/21  1:45 AM  (GMT-06:00) To: zwave-js/zwavejs2mqtt ***@***.***> Cc: john55021 ***@***.***>, Mention ***@***.***> Subject: Re: [zwave-js/zwavejs2mqtt] can't connect to stick (Issue #2040) 
@john55021 AFAIK docker on windows doesn't allow you to map COM ports to docker container, at least this is what some users told me some time ago but maybe could be fixed now.
If you are using an Rpi in order to install docker you can use this command:
curl -fsSL https://get.docker.com -o get-docker.sh
sudo sh get-docker.sh

sudo usermod -aG docker $USER

docker version

# test it
docker run --rm -it hello-world
To clean up your docker you could do (BE AWARE THIS WILL REMOVE EVER DOCKER CONTAINER/IMAGE/VOLUME)
docker container stop $(docker container ls -aq)
docker container rm $(docker container ls -aq)
docker system prune -a
Now that your docker instance is cleaned try again with the steps I told you:
mkdir zwavejs2mqtt
cd zwavejs2mqtt
# put inside the docker-compose.yml file
docker compose up

**Comment by robertsLando** [comment]
> Some of the directions said to create a folder 'store' (I know there just examples) so i did,  and eventually got zwave2mqtt working with just docker. All my config files are there.  So is it still possible to reference those when using docker-compose?

**Comment by john55021** [comment]
I see others are also having problems with git, but evidently it doesn't matter.scenes.json & git not found - githubmemory


-----Original Message-----

**Comment by john55021** [comment]
Followed your directions below, other than install docker since I have it installed, and got this, same error.
***@***.***:~/zwavejs2mqtt $ docker-compose upCreating network "zwavejs2mqtt_zwave" with the default driverPulling zwavejs2mqtt (zwavejs/zwavejs2mqtt:latest)...latest: Pulling from zwavejs/zwavejs2mqtt420c7481a3a7: Pull complete42c5f0fd37b3: Pull completef87d282ad34c: Pull complete9b943cd5a9bc: Pull complete30c5e505c917: Pull complete6a635e562682: Pull completeDigest: sha256:5a9424d599a3ccdbc55d27195cea366a4627b617a107b3b3580575f88b71146bStatus: Downloaded newer image for zwavejs/zwavejs2mqtt:latestCreating zwavejs2mqtt ... doneAttaching to zwavejs2mqttzwavejs2mqtt    | /bin/sh: git: not foundzwavejs2mqtt    | 2021-12-15 15:57:05.771 INFO APP: Version: 6.1.0zwavejs2mqtt    | 2021-12-15 15:57:05.778 INFO APP: Application path:/usr/src/appzwavejs2mqtt    | zwavejs2mqtt    |  ______                       _     ___                  _   _   zwavejs2mqtt    | |___  /                      (_)   |__ \                | | | |  zwavejs2mqtt    |    / /_      ____ ___   _____ _ ___   ) |_ __ ___   __ _| |_| |_ zwavejs2mqtt    |   / /\ \ /\ / / _` \ \ / / _ \ / __| / /| '_ ` _ \ / _` | __| __|zwavejs2mqtt    |  / /__\ V  V / (_| |\ V /  __/ \__ \/ /_| | | | | | (_| | |_| |_ zwavejs2mqtt    | /_____|\_/\_/ \__,_| \_/ \___| |___/____|_| |_| |_|\__, |\__|\__|zwavejs2mqtt    |                             _/ |                      | |        zwavejs2mqtt    |                            |__/                       |_|        zwavejs2mqtt    | zwavejs2mqtt    | 2021-12-15 15:57:05.821 WARN STORE: settings.json not foundzwavejs2mqtt    | 2021-12-15 15:57:05.826 WARN STORE: scenes.json not foundzwavejs2mqtt    | 2021-12-15 15:57:05.829 WARN STORE: nodes.json not foundzwavejs2mqtt    | 2021-12-15 15:57:05.901 INFO APP: Listening on port 8091 host 0.0.0.0 protocol HTTPzwavejs2mqtt    | 2021-12-15 15:57:05.971 ERROR GATEWAY: Zwave settings are not valid

I even tried to load git, by doing ***@***.***:~/zwavejs2mqtt $ sudo apt-get install gitReading package lists... DoneBuilding dependency tree       Reading state information... Donegit is already the newest version (1:2.20.1-2+deb10u3).0 upgraded, 0 newly installed, 0 to remove and 364 not ***@***.***:~/zwavejs2mqtt $ docker-compose upStarting zwavejs2mqtt ... done
same results.

-----Original Message-----

**Comment by robertsLando** [comment]
@john55021 I don't see any error in those logs, did you try to open a browser to the application?

**Comment by john55021** [comment]
I wonder if some of the stuff I'm sending you doesn't get there. This is the log:
Attaching to zwavejs2mqttzwavejs2mqtt    | /bin/sh: git: not foundzwavejs2mqtt    | 2021-12-15 16:27:21.927 INFO APP: Version: 6.1.0zwavejs2mqtt    | 2021-12-15 16:27:21.934 INFO APP: Application path:/usr/src/appzwavejs2mqtt    | zwavejs2mqtt    |  ______                       _     ___                  _   _   zwavejs2mqtt    | |___  /                      (_)   |__ \                | | | |  zwavejs2mqtt    |    / /_      ____ ___   _____ _ ___   ) |_ __ ___   __ _| |_| |_ zwavejs2mqtt    |   / /\ \ /\ / / _` \ \ / / _ \ / __| / /| '_ ` _ \ / _` | __| __|zwavejs2mqtt    |  / /__\ V  V / (_| |\ V /  __/ \__ \/ /_| | | | | | (_| | |_| |_ zwavejs2mqtt    | /_____|\_/\_/ \__,_| \_/ \___| |___/____|_| |_| |_|\__, |\__|\__|zwavejs2mqtt    |                             _/ |                      | |        zwavejs2mqtt    |                            |__/                       |_|        zwavejs2mqtt    | zwavejs2mqtt    | 2021-12-15 16:27:21.982 WARN STORE: settings.json not foundzwavejs2mqtt    | 2021-12-15 16:27:21.987 WARN STORE: scenes.json not foundzwavejs2mqtt    | 2021-12-15 16:27:21.990 WARN STORE: nodes.json not foundzwavejs2mqtt    | 2021-12-15 16:27:22.067 INFO APP: Listening on port 8091 host 0.0.0.0 protocol HTTPzwavejs2mqtt    | 2021-12-15 16:27:22.146 ERROR GATEWAY: Zwave settings are not valid
The last line seems to be a major error, and yes, I have tried to browser into 8091.

-----Original Message-----

**Comment by robertsLando** [comment]
> The last line seems to be a major error, and yes, I have tried to browser into 8091.

Them just means that for some reason the settings.json  file in your store directory/volume is not valid but the application should be running so you should be able to edit settings from ui

**Comment by john55021** [comment]
I think you're giving me too much credit. When I ran straight Docker within the folder 'store', which works, there is a settings.json file along with a bunch of other files and folders. However within the zwavejs2mqtt folder, where I'm trying to start with 'docker-compose up', there is absolutely nothing other than the docker-compose.yml file.


-----Original Message-----

**Comment by john55021** [comment]
Also, with usr/src folder, the only folder is 'sense-hat'. There is not 'app/store folder which I would expect to see.


-----Original Message-----

**Comment by john55021** [comment]
Now I'm really confused. I ran the three commands to clear out the docker files that your sent.
I changed docker-compose.yml to this:
version: "3.7"services:  zwavejs2mqtt:    container_name: zwavejs2mqtt    image: zwavejs/zwavejs2mqtt:latest    restart: always    tty: true    stop_signal: SIGINT    environment:      - SESSION_SECRET=mysupersecretkey      - ZWAVEJS_EXTERNAL_CONFIG=/usr/src/app/store/.config-db      # Uncomment if you want log times and dates to match your timezone instead of UTC      # Available at https://en.wikipedia.org/wiki/List_of_tz_database_time_zones      #- TZ=America/Chicago    networks:      - zwave    devices:      # Do not use /dev/ttyUSBX serial devices, as those mappings can change over time.      # Instead, use the /dev/serial/by-id/X serial device for your Z-Wave stick.      - '/dev/serial/by-id/usb-Silicon_Labs_CP2102N_USB_to_UART_Bridge_Controller_38aff6294d45eb11bf4da552b003b68c-if00-port0:/dev/zwave'    volumes:      - zwave-config:/usr/src/app/store    ports:      - "8092:8092" # port for web interface      - "3000:3000" # port for Z-Wave JS websocket servernetworks:  zwave:volumes:  zwave-config:    name: zwave-config

Notice that I changed ports to 8092. It still says "INFO APP: Listening on port 8091 host 0.0.0.0 protocol HTTP"
HUH????
-----Original Message-----

**Comment by john55021** [comment]
OK, forget everything in the past. I finally got it working.
Thank you for the help and patience.John


-----Original Message-----

**Comment by robertsLando** [comment]
Glad you made it :)

**Comment by john55021** [comment]
Thanks for your help Daniel. All my issues were Linux, Docker and Docker-Compose related. It turns out so many of the instruction and/or suggestions one finds are tied to hardware and OS versions. Especially with Docker-compose. I thought one of the purposes of Docker was to manage that. zwavejs2mqtt is wonderful.Sent via the Samsung Galaxy S10, an AT&T 5G Evolution capable smartphone
-------- Original message --------From: Daniel Lando ***@***.***> Date: 12/16/21  1:47 AM  (GMT-06:00) To: zwave-js/zwavejs2mqtt ***@***.***> Cc: john55021 ***@***.***>, Mention ***@***.***> Subject: Re: [zwave-js/zwavejs2mqtt] can't connect to stick (Issue #2040) 
Closed #2040.

**Comment by john55021** [comment]
Daniel,Quick question. I added a device without a device.json type file. The manufacturer sent me one (zw31s.json) and I added it to the config-db/devices/0xxxx folder for that manufacturer. When re-interviewing it's not getting picked up. Do you use the https://devices.zwave-js.io/ website to pull down device info or actually use the local folder. And is there something else I have to update to find the device, since the file name is zw31s as opposed to the hex name.Thanks John


-----Original Message-----

**Comment by robertsLando** [comment]
Follow docs: https://zwave-js.github.io/zwavejs2mqtt/#/device-support/custom-device-files
