### ISSUE TITLE
[bug] Qubino Flush Dimmer does not send off topic 

### ISSUE THREAD

**Issue by hestiap** [zwave-js/zwavejs2mqtt#2047]
Hi,
I have an issue with 2 Qubino Flush Dimmers as there are no OFF messages sent to Dz

### Version
Build/Run method: [ ] Docker
Zwavejs2Mqtt version: 5.12.0
Z-Wave JS version: 8.7.6

### Describe the bug
When I switched OFF the Qubino Flush Dimmer Plus  ZMNHDD (in the wall) there are no message OFF in mqtt
The light in real life is switched OFF
It was ok when it's switched ON

### To Reproduce
Switch OFF the light fram the switch in the wall and noting is sent by mqtt

### Expected behavior
A message is expected from mqtt (to domoticz for me)

### Additional context
The same for another another Flush Dimmer, but others works.
The Watt are well reporting 
I did several refresh, re-interviews
Today the issue was reversed sometimes after some  refresh, re-interviews, I saw some OFF messages, no ON messages (the log are from yesterday test)

[113-134-0-libraryType] Library type
[3] Enhanced Slave
[113-134-0-protocolVersion] Z-Wave protocol version
4.38
[113-134-0-firmwareVersions] Z-Wave chip firmware versions
["3.8","3.10"]
[113-134-0-hardwareVersion] Z-Wave chip hardware version
4

[zwavejs2mqtt_2021-12-11.log](https://github.com/zwave-js/zwavejs2mqtt/files/7698572/zwavejs2mqtt_2021-12-11.log)

**Comment by hestiap** [comment]
@robertsLando
I'll redo the log.
Before, just to be sure, I've done another quick test with this log

Initial context: the switch is off in real and in dz
To ON
2021-12-15 17:25:22.056 INFO ZWAVE: Node 113: value updated: 38-0-currentValue 0 => 99
2021-12-15 17:25:23.095 INFO ZWAVE: Node 113: value updated: 50-0-value-66049 0 => 4.5
OK : 38-0-currentValue 0 => 99

To OFF
2021-12-15 17:25:33.109 INFO ZWAVE: Node 113: value updated: 50-0-value-66049 4.5 => 0
2021-12-15 17:25:34.113 INFO ZWAVE: Node 113: value updated: 50-0-value-66049 0 => 0
NO 38-0-currentValue 99 => 0

To ON
2021-12-15 17:25:41.097 INFO ZWAVE: Node 113: value updated: 38-0-currentValue 99 => 99
2021-12-15 17:25:42.134 INFO ZWAVE: Node 113: value updated: 50-0-value-66049 0 => 4.1
From 99, not from 0

To OFF
2021-12-15 17:25:49.152 INFO ZWAVE: Node 113: value updated: 50-0-value-66049 4.1 => 0
NO 38-0-currentValue 99 => 0

**Comment by robertsLando** [comment]
@hestiap What I don't understand here is if when you switch off the switch in real you actually see the change in UI or not

**Comment by hestiap** [comment]
@robertsLando
After switched ON the real switch and refresh the browser
![image](https://user-images.githubusercontent.com/73014953/146897787-f8283ec6-3df9-4ea6-87a4-8b8821f40486.png)
no change in the UI.

After REFRESH
![image](https://user-images.githubusercontent.com/73014953/146897979-b0d50190-f275-427f-ad5b-71a6e139da12.png)
it's ok.

The same when switched off

So no change in UI

**Comment by andyboeh** [comment]
Did you try the procedure listed in the Home Assistant forum at https://community.home-assistant.io/t/zwavejs2mqtt-and-qubino-flush-dimmer/278515/12? I also have ZMNHDD dimmers and the status reported does not match the actual status. However, I haven't had the time to try the linked procedure.

**Comment by robertsLando** [comment]
Most of the times this is a device issue, if you don't see the change there it means it's the device that isn't reporting it's state change to the controller. This could be solved with a firmware update, a device configuration or with group associations, it's not a bug with z2m or zwavejs. 

Thanks @andyboeh for the link, let's see if that helps

**Comment by andyboeh** [comment]
I took this as an opportunity to finally test it on my four ZMNHDDs: So far, it seems to fix the issue for me.

**Comment by hestiap** [comment]
@andyboeh 
Thanks for the solution.
In my case I already have the parameters set (but I'm not sure I did the exclusion / inclusion, I'll try but pretty risky with the devices in the wall...).
One other point is that I think I have recent HW and FW
![image](https://user-images.githubusercontent.com/73014953/147000549-5d99a940-9c65-4dc2-ace1-f05b023b4810.png)
![image](https://user-images.githubusercontent.com/73014953/147000620-76afd991-7f06-4fcf-ab8c-37412cc45ecd.png)

So perhaps the solution is not appropriate

@robertsLando 

> Most of the times this is a device issue, if you don't see the change there it means it's the device that isn't reporting it's state change to the controller. This could be solved with a firmware update, a device configuration or with group associations, it's not a bug with z2m or zwavejs.

I not so sure it is a device issue as it was working with OpenZwave before I moved to zwaveje2mqtt
What do you mean by "with group associations" please?

**Comment by hestiap** [comment]
I've found results of test I did before moving from OWZ to z2m and on basic testing it was working
![image](https://user-images.githubusercontent.com/73014953/147001931-aa4f6489-f812-4e64-bff8-71b8d815c783.png)
In August, I could not find the version
Now:
zwavejs2mqtt: 6.1.1
zwave-js: 8.9.0-beta.1

**Comment by robertsLando** [comment]
@hestiap Did you try to enable poll of that value?

**Comment by andyboeh** [comment]
> In my case I already have the parameters set (but I'm not sure I did the exclusion / inclusion, I'll try but pretty risky with the devices in the wall...).

Yeah for whatever reason, I never succeeded to get the Qubino in inclusion/exclusion mode with the attached switch - not even when installing the first time. With Fibaros, it always worked on the first or second try.

You should be able to tell whether you excluded/included by the number of available endpoints, they are only changed when the device is excluded/included. If I'm not mistaken, this information is available in the manual.

**Comment by hestiap** [comment]
> @hestiap Did you try to enable poll of that value?
When it was working with OZW there was no polling
When I've got some tests working with zwavejs2mqtt there was no polling
Now, I did it like this
![image](https://user-images.githubusercontent.com/73014953/147389808-0644fcc9-f7b2-4b67-8219-5f8e6ced73c6.png)
No progress, no change, no off message when I switched off the real switch

**Comment by hestiap** [comment]
@andyboeh 
> You should be able to tell whether you excluded/included by the number of available endpoints, they are only changed when the device is excluded/included. If I'm not mistaken, this information is available in the manual.

I didn't find it in the manual. Anyway, I know I excluded/included these devices several times, but I couldn't know if I set the parameters before or after

**Comment by robertsLando** [comment]
Dunno if @AlCalzone has any tips here

**Comment by AlCalzone** [comment]
All I know is that many Qubino devices (at least the ones where you can add/remove endpoints with a config parameter) need to be excluded without reset and re-included for the changes to take effect. Without this, they won't include the new endpoints in their capability lists, so Z-Wave JS doesn't know about them.
Also, the endpoint configuration may have an influence on how the lifeline associations need to be set up for reports to work properly.

@hestiap if you're not sure you did the exclusion-inclusion dance, I'd start there.

**Comment by hestiap** [comment]
@AlCalzone 
regarding the endpoint, they are like this
![image](https://user-images.githubusercontent.com/73014953/147468210-46c892e2-5794-4e6b-bdd0-653060653015.png)
Is this good? No lifeline available when I use ADD!
I'll do the exclusion-inclusion dance, probably next week...

**Comment by AlCalzone** [comment]
Your Screenshot is showning associations, not endpoints.

**Comment by hestiap** [comment]
@AlCalzone 
> @hestiap if you're not sure you did the exclusion-inclusion dance, I'd start there.

I did the exclusion-inclusion dance... with no better outcome :-(
I did it on 2 different modules
Also I did it after I made a reset, inclusion with zwavejs and waiting more than 30 s
It's still the same: I'd got the on topic but not the off ones

What is strange is that I've got another Flush Dimmer with the same version that works well and 4 that doesn't work!!!

```
ON after an ON/OFF
2022-01-14 19:31:30.586 INFO ZWAVE: Node 146: value updated: 38-0-currentValue 99 => 99

2022-01-14 19:31:32.081 INFO ZWAVE: Node 146: value updated: 50-0-value-66049 0 => 11.4

OFF
2022-01-14 19:31:35.633 INFO ZWAVE: Node 146: value updated: 50-0-value-66049 11.4 => 0

2022-01-14 19:31:58.726 INFO ZWAVE: Node 146: value updated: 50-0-value-66049 0 => 0
```

I've added a group
![image](https://user-images.githubusercontent.com/73014953/149577941-31dccb71-20e7-4aec-8436-edc59d778327.png)
and with this there are topic on On and Off
```
ON
2022-01-14 19:57:46.973 INFO ZWAVE: Node 146: value updated: 32-0-currentValue 0 => 255
2022-01-14 19:57:47.896 INFO ZWAVE: Node 146: value updated: 38-0-currentValue 0 => 99
2022-01-14 19:57:48.928 INFO ZWAVE: Node 146: value updated: 50-0-value-66049 0 => 11.6
OFF
2022-01-14 19:58:19.810 INFO ZWAVE: Node 146: value updated: 32-0-currentValue 255 => 0
2022-01-14 19:58:21.061 INFO ZWAVE: Node 146: value updated: 50-0-value-66049 11.6 => 0

2022-01-14 19:58:22.062 INFO ZWAVE: Node 146: value updated: 50-0-value-66049 0 => 0
ON
2022-01-14 19:58:39.482 INFO ZWAVE: Node 146: value updated: 32-0-currentValue 0 => 255
2022-01-14 19:58:41.110 INFO ZWAVE: Node 146: value updated: 38-0-currentValue 99 => 99
OFF
2022-01-14 19:58:58.060 INFO ZWAVE: Node 146: value updated: 32-0-currentValue 255 => 0
2022-01-14 19:58:59.212 INFO ZWAVE: Node 146: value updated: 50-0-value-66049 11 => 0
2022-01-14 19:59:00.212 INFO ZWAVE: Node 146: value updated: 50-0-value-66049 0 => 0
```
But I get nothing in Domoticz...
Could it be something to dig or do you have another idea?

**Comment by AlCalzone** [comment]
> this there are topic on On and Off

Your logs still show that updates for the Multilevel Switch CC (38) aren't sent on off. The association just caused a Basic CC Set to be sent (which is normally used to control other devices).

If you haven't already, you should contact the Qubino support. Either this is a misconfiguration which they should be able to tell you quickly, or faulty devices in which case this is something for the support anyways.

**Comment by hestiap** [comment]
@AlCalzone
I'll do it... again
I did it in 2019 but their answer was that Domoticz OZW was faulty!

> 
> Le 22/11/2019 à 08:26, Qubino Support a écrit :
> ...
>     That is definitely an issue of the integration, also all of the functions of our devices are tested well before we sent them into the production. I can tell you that we forward our findings and the issues reported from customers that have problems of integration to the developers of the gateway so that they have the list of the things to check / fix for the next releases

**Comment by AlCalzone** [comment]
> Domoticz OZW was faulty

Well, now you can say that Z-Wave JS doesn't work with the device either and the logs definitely show that the device doesn't send any message.

**Comment by AlCalzone** [comment]
> In my case I am in "dimmer mode" and the binary switch report is not reporting its status automatically as well, except if I click "refresh" in Zwavejs2mqtt control panel

I would say this is expected. The device is in dimmer mode and should be controlled through the corresponding CC (Multilevel Switch), which should get updated automatically on status changes.

**Comment by hestiap** [comment]
@AlCalzone 
after some discussion with Qubino, I've got a dimmer upgraded with the last FW.
And the problem is solved.
I going to send the others.
Thanks for your help :-)
