### ISSUE TITLE
[bug] climate CC discovery on some devices

### ISSUE THREAD

**Issue by Moffus** [zwave-js/zwavejs2mqtt#2059]
### Version

**Checklist:**

- [X ] I am **not** using Home Assistant. **Or:** a developer has told me to come here.
(Problem found with HA or without HA.)
- [X ] I have checked the troubleshooting section and my problem is **not** described there.
- [ X] I have read the changelog and my problem is **not** mentioned there.

Build/Run method

- [X] Docker
- [ ] PKG
- [X] Snap package
- [ ] Manually built (git clone - yarn install - yarn run build )
(Snap & docker checked, no difference)

Zwavejs2Mqtt version: 6.1.0
Z-Wave JS version: 8.9.0-beta.0

### Describe the bug

Climate CC not discovered well
Direct MQTT call to value API works well, direct setpoint manipulation in Zwavejs2mqtt CP - Ok.
Other high level API's - not.

### To Reproduce
Insert Heltun FL2 thermostat to Z-Wave network

5. Device not exposed as thermostat with thermostat setpoint trow all interfaces (Websockets, MQTT, etc)

### Expected behavior

Expectiion: Climate CC found and translated trow all API's and interfaces

### Additional context

from zwavejs2mqtt log:
```
2021-12-15 12:01:34.425 ERROR GATEWAY: Error while discovering device climate_climate of node 48: Cannot read property 'nodeId' of undefined Cannot read property 'nodeId' of undefined
TypeError: Cannot read property 'nodeId' of undefined
    at Gateway.valueTopic (/usr/src/app/server/lib/Gateway.js:358:44)
    at Gateway.discoverDevice (/usr/src/app/server/lib/Gateway.js:543:80)
    at /usr/src/app/server/lib/Gateway.js:1453:50
    at Array.forEach (<anonymous>)
    at Gateway._onNodeInited (/usr/src/app/server/lib/Gateway.js:1453:25)
    at ZwaveClient.emit (node:events:394:28)
    at ZwaveClient.emit (node:domain:470:12)
    at ZwaveClient.emitNodeStatus (/usr/src/app/server/lib/ZwaveClient.js:780:18)
    at ZwaveClient._onNodeStatus (/usr/src/app/server/lib/ZwaveClient.js:1893:18)
    at ZwaveClient._onNodeReady (/usr/src/app/server/lib/ZwaveClient.js:1942:14)

```
How nodes exposed:
```

INFO GATEWAY: New climate device discovered: {
  type: 'climate',
   object_id: 'climate',
   discovery_payload: {
     min_temp: 5,
     max_temp: 40,
     temp_step: 0.5,
     modes: [ 'off', 'dry', 'auto', 'heat', 'cool', [length]: 5 ],
     mode_state_template: '{{ value_json.value }}',
     current_temperature_topic: '49-0-Air temperature',
     current_temperature_template: '{{ value_json.value }}',
     temperature_state_topic: true,
     temperature_state_template: '{{ value_json.value }}',
     temperature_command_topic: true,
     mode_state_topic: '64-0-mode',
     mode_command_topic: '64-0-mode/set',
     action_topic: '66-0-state'
   },
   values: [ '49-0-Air temperature', '64-0-mode', '66-0-state', [length]: 3 ],
   mode_map: {
     off: 0,
     dry: undefined,
     auto: undefined,
     heat: undefined,
     cool: undefined
   },
   setpoint_topic: {},
   default_setpoint: undefined,
   action_map: {
     '0': 'idle',
     '1': 'heating',
     '2': 'cooling',
     '3': 'fan',
     '4': 'idle',
     '5': 'idle',
     '6': 'fan',
     '7': 'heating',
     '8': 'heating',
     '9': 'cooling',
     '10': 'heating',
     '11': 'heating'
   }
 }

```
[zwavejs2mqttnodedebug.txt](https://github.com/zwave-js/zwavejs2mqtt/files/7718024/zwavejs2mqttnodedebug.txt)

[ha_zwave_js_dump.json.txt](https://github.com/zwave-js/zwavejs2mqtt/files/7718052/ha_zwave_js_dump.json.txt)

**Comment by Moffus** [comment]
Looks like i found 2 bugs and fixes in Gateway.js.
1. Mode mapping from Z-wave to HA. Simple coding bug
```
***************
*** 741,747 ****
                          i < allowedModes.length) {
                          hM = allowedModes[i++];
                      }
!                     config.mode_map[hM] = availableModes[m];
                      config.discovery_payload.modes.push(hM);
                      if (m > 0) {
                          // find the mode setpoint, ignore off
--- 741,747 ----
                          i < allowedModes.length) {
                          hM = allowedModes[i++];
                      }
!                     config.mode_map[hM] = m;
                      config.discovery_payload.modes.push(hM);
                      if (m > 0) {
                          // find the mode setpoint, ignore off
```
availableModes[m] not good, because we already in loop:
```
for (const m of availableModes) {
....
```
Now it filled.
mode_map: 

Was: 
```
{}
```
Now: 
```
{ off: 0, dry: 8, auto: 10, heat: 11, cool: 13, fan_only: 15 },
```

2. Logical problem
Now, Zwavejs2mqtt assumed:
a) "All setpoint types always have t's own setpoint"
Not always. Some heating thermostats have only 1 heating setpoint for all modes of heating. 
b) "At least Heat setpoint can be found in every cases" 
Not in every. If thermostat have different heating modes, simple "Heat" (1) may be omitted, but Energy heat, Full power, Away heat - not.

Most of Z-Wave controllers are not confused by this, Zwavejs2mqtt - not too, after patch
```
***************
*** 751,756 ****
--- 751,760 ----
                              config.values.push(setId);
                              config.setpoint_topic[m] = setId;
                          }
+                     else {
+                             config.values.push(setpoints[0]);
+                             config.setpoint_topic[m] = setpoints[0];
+                         }
                      }
                  }
                  // set the default setpoint to 'heat' or to the first setpoint available

``` 
Was
```
setpoint_topic: {}
```
Now
```
setpoint_topic: {
    '8': '67-0-setpoint-1',
    '10': '67-0-setpoint-1',
    '11': '67-0-setpoint-1',
    '13': '67-0-setpoint-1',
    '15': '67-0-setpoint-1'
  },
```
Checked: MQTT: Setpoint changed by device, if mode changed. It's Ok.
Checked HA: Now Thermostat found in UI, manipulated, it's Ok.
![image](https://user-images.githubusercontent.com/93212096/146601265-95756889-dbea-4b20-9d7f-0b6f90525faf.png)

**Comment by robertsLando** [comment]
@Moffus Could you submit a PR with the fix?

**Comment by Moffus** [comment]
Yes, i can.
I want to perform some additional tests at weekend before post a PR.

**Comment by Moffus** [comment]
Another bug found.
Wrong mode mapping in hassModes.

Then: 
Last valid index of array - 0x0e, no Z-Wave mode for this :)
Mode 0x0f - mapped to undefined. instead of 'heat' and called 'manufacturer specific'

Now:
Checked and fixed. 

Tested on:
Heltun wall thermostat - 1 setpoint for all modes. It perfect now. (only throw MQTT! WS not touched!)
Remotec ZXT-120 aircon IR thermostat. Have setpoint for each mode. Nothing changed. 
Eurotronics Spirit, valve thermostat (2 modes, 2 setpoints). Nothing changed.

TODO:
Better to change the flat, offset based hassModes array to key-value.

PR coming.
