### ISSUE TITLE
[bug] Node overview shows battery status for always-listening (mains powered) node

### ISSUE THREAD

**Issue by AlCalzone** [zwave-js/zwavejs2mqtt#2071]
Zwavejs2Mqtt version: latest / github
Z-Wave JS version: 8.9.0-beta.something

### Describe the bug

This multisensor was included on USB power and is therefore an always listening node (at least until it is re-included on battery):
![grafik](https://user-images.githubusercontent.com/17641229/146404484-d605e447-b3a3-473c-aed1-0ec28d233955.png)

It does not have a battery. 

### Expected behavior

Show the cable/plug icon when a node is listening. Only show battery when `isListening: false`.

**Comment by robertsLando** [comment]
Actually we only check for battery cc presence to say if it's battery powered or not, should be check for that property instead?

**Comment by AlCalzone** [comment]
That's what I'm proposing

**Comment by kpine** [comment]
I have the opposite issue. My old Aeon Minimote, which is a battery device but doesn't support the Battery CC (but does have `isListening: false`), shows up as mains-powered:


![image](https://user-images.githubusercontent.com/791794/146465851-ca351bdc-25f3-4f3b-bc78-9a049c1bc916.png)

**Comment by asucrews** [comment]
This is always happening on Aeotec MultiSensor 7, i have two, one show battery powered, and the other shows like mains powered. Is there anyway to fix the one show mains powered?

![image](https://user-images.githubusercontent.com/5163575/180142329-b91e894d-a58c-472f-97a6-6b22174fb6eb.png)

**Comment by robertsLando** [comment]
@asucrews z2m version?

**Comment by AlCalzone** [comment]
You probably included one on USB power and one on battery. The devices will continue to be treated like this so if one is wrong you need to re-include it.

**Comment by kpine** [comment]
>  i have two, one show battery powered, and the other shows like mains powered

The screenshot posted shows both nodes having battery icons. Did you mean to say or show something else?

**Comment by AlCalzone** [comment]
@kpine One is sleeping, the other one is alive (mains powered).

**Comment by asucrews** [comment]
> @asucrews z2m version? Did you tried to re-interview your device?

I am on the lastest docker with watchtower.

**Comment by asucrews** [comment]
So step to fix my issues.
1. excluded and include - nothing same results.
2. re flashed the device  - nothing same results.
3 exclude, factory reset, and include - now reporting as it should.

I am not 100% sure why factory reset clear it up.

**Comment by AlCalzone** [comment]
Me neither, but glad it worked 😅
