### ISSUE TITLE
[question] What is the correct way of integrating this with the official zwavejs?

### ISSUE THREAD

**Issue by henrikrox** [zwave-js/zwavejs2mqtt#2075]
Hi, I have 40 devices in zwave js, but I wanted another frontend/gui for control of the zwave network, from reading the documentation this will be possible with zwavejs2mqtt. 

However I don't quite fully understand how am I supposed to set it up, it mentions use of port 3000.

Is the official zwavejs supervisor add-on supposed to be stopped, deleted?
is the zwavejs2mqtt need to have the zwave usb stick set?

I tried doing like it said in the manual, but the devices had weird names in zwavejs2mqtt, and zwavejs stopped working. Am I missing something?

**Comment by robertsLando** [comment]
In order to make integration work with zwavejs2mqtt you have to enable zwavejs server flag in Settings Tab
