### ISSUE TITLE
[question] More than one WS connection / Multiple Home Assistant WS connections to one Zwave2MQTT instance?

### ISSUE THREAD

**Issue by rct** [zwave-js/zwavejs2mqtt#2076]
Is it possible to have more than one WS connection to ZwaveJS?

Would two Home Assistant instances connecting simultaneously be somewhat expected to work?

I realize It isn't a tested (or supported) configuration, but wanted to know if there were any reasons to avoid that.

My first use case is simply, can both my "test" and "production" Home Assistant instances access my Zwave network?

Thanks!

**Comment by kpine** [comment]
It has always worked fine for me. Did you try it?

**Comment by rct** [comment]
> It has always worked fine for me. Did you try it? The server does support multiple clients. z2m simply embeds the server.

Ok thanks.   I had tried it.  I had started to see some strange behavior where turning lights on and off in home assistant seemed to be failing silently when I had both connected but probably something else was going on.

I’ll try it again.

**Comment by rct** [comment]
Multiple Hass instances pointing to Zwavejs2MQTT WS seems to work fine -- closing issue
