### ISSUE TITLE
[Home Assistant] Cannot add node that was previously in network

### ISSUE THREAD

**Issue by giovi321** [zwave-js/zwavejs2mqtt#2077]
[zwavejs2mqtt-store.zip](https://github.com/zwave-js/zwavejs2mqtt/files/7739191/zwavejs2mqtt-store.zip)

### Version

Build/Run method:

[ ] Docker
[ ] Git Clone + yarn install + yarn run build + yarn start
[x] Pkg

Zwavejs2Mqtt version: zwavejs2mqtt: 6.1.0.19e2052
Z-Wave JS version: zwave-js: 8.9.0-beta.3

### Describe the bug

I had a thermostatic valve in my network but the batteries died, so I replaced them. When I turned it back on it was factory reset for some reason. The controller correctly marked is ad dead and I proceeded to remove it.
Now I'm unable to add the node back into the network as nothing happens when trying to incude it.
The device is a Eutronics Spirit Thermostatic Valve.
EDIT: I'm using a  ZST10-700 controller and I have already tried the method of using a usb extender.

**Comment by jmgiaever** [comment]
Have you tried to actually perform the factory reset on the device yourself too after you removed the dead entity in Z2M? Check the manual on it, do the factory reset and try again. 

A restart of Z2M + unplugging the USB stick might help too. 

By devices I mean the thermostatic valve, not your USB stick.

**Comment by giovi321** [comment]
1) yes i did factory reset correctly the device
2) I was trying to unplug and replug the usb stick but i get the following message
```
root@GC01hass:/home# sudo snap connect zwavejs2mqtt:raw-usb    
root@GC01hass:/home# zwavejs2mqtt.restart 
Missing plug: «serial-port»
OPTIONAL plug
Connect with: $ sudo snap connect zwavejs2mqtt:serial-port
root@GC01hass:/home# 

```

**Comment by jmgiaever** [comment]
Yes, but you don't need that plug if you're using the raw-usb plug. It's _optional_

**Comment by jmgiaever** [comment]
It's more important to see your zwjs logs. Not z2m logs.

**Comment by giovi321** [comment]
[zwavejs2mqtt-store(1).zip](https://github.com/zwave-js/zwavejs2mqtt/files/7739605/zwavejs2mqtt-store.1.zip)

**Comment by jmgiaever** [comment]
@AlCalzone

**Comment by robertsLando** [comment]
@giovi321 If you aren't able to add it back to the controller the only reason I can find is that you didn't reset it correctly and it still thinks to be connected to the stick
