### ISSUE TITLE
Should releases using node-zwave-js 8.9.0betaX really be marked "stable"?

### ISSUE THREAD

**Issue by mundschenk-at** [zwave-js/zwavejs2mqtt#2080]
I'm not sure that packaging the beta releases of the driver as "stable" is correct (e.g. the official HA addon gets tagged from the latest no-pre-release of zwavejs2mqtt).

**Comment by robertsLando** [comment]
@mundschenk-at That has been a mistake on my side, the automated release action didn't picked the beta tag correctly
