### ISSUE TITLE
[question] Backup NVM regularly?

### ISSUE THREAD

**Issue by LordMike** [zwave-js/zwavejs2mqtt#2084]
Hey,

I'm considering switching z-wave stick, and in that process I realized that the memory of the stick isn't backed up at all, when backing up the `store` directory. Clicking the "NVM Backup" creates a `NVM_.....bin` file in the `store` directory - but is there any way to:

* Create this file regularly? (every month/week/night/on include/exclude f.ex.)
  * I think the current API call is through websockets, which I don't want to automate in curl :P
* Remove old bin files, so there is a rolling set of N files
  * Alternatively overwrite the same one always, then my own backup program can show me snapshots

Note: The warning says the z-wave radio is disabled while backing up, so I can understand why you would _not_ want to do this backup immediately after inclusion/exclusion... Maybe a compromise could be that every night, a backup job runs that checks if anything has changed since last backup. I imagine the NVM backup won't contain stuff like states -- although it might contain neighbor/route maps, which can change once in a while..

Mike.

**Comment by kpine** [comment]
See discussion https://github.com/zwave-js/zwavejs2mqtt/discussions/2068

**Comment by robertsLando** [comment]
@LordMike Hi Mike! Join the discussion on #2068 :) We are speaking about that.
