### ISSUE TITLE
[bug] Cache file gets truncated upon service shutdown

### ISSUE THREAD

**Issue by gzone156** [zwave-js/zwavejs2mqtt#2085]
### Version

**Checklist:**

- [X] I am **not** using Home Assistant. **Or:** a developer has told me to come here.
- [ ] I have checked the troubleshooting section and my problem is **not** described there.
- [X] I have read the changelog and my problem is **not** mentioned there.

Build/Run method

- [ ] Docker
- [ ] PKG
- [ ] Snap package
- [X] Manually built (git clone - yarn install - yarn run build )

Zwavejs2Mqtt version: 6.1.1
Z-Wave JS version: 8.9.0-beta.3

### Describe the bug

Installed on RaspberryPiOs Bullseye using manual method (git clone / npm install / npm build / npm start). Upon service restart and/or system reboot, sometimes the cache file gets truncated, incurring in a subsequent re-interview of the entire network upon restart, and loosing *some* of HomeAssistant already mapped devices/entities (weird).

### To Reproduce

Stop zwavejs2mqtt process

### Expected behavior

Cache file doesn't get truncated

Attached is the main application log, in silly level and a screenshot of the instant the cache file got truncated.

![Run1](https://user-images.githubusercontent.com/62515544/146919857-86796400-9078-4766-8416-baca14b33eb9.png)

[zwavejs2mqtt_2021-12-21.log](https://github.com/zwave-js/zwavejs2mqtt/files/7752899/zwavejs2mqtt_2021-12-21.log)

**Addendum:** on a second run, with driver log enabled in silly level, the last row of the driver log says correctly "2021-12-21T11:14:53.792Z DRIVER   destroying driver instance...", with no further entries logged

**Comment by robertsLando** [comment]
@gzone156 Could you try to send a SIGINT instead of a SIGTERM?

**Comment by gzone156** [comment]
@robertsLando issuing a SIGINT via proper systemd service configuration did the trick, either during a manual service stop or a system reboot.

I noticed that the cache file is overwritten during service termination, either if no changes are made (and I can guess it is the most frequent scenario... network already setup and no changes made in nodes inclusion / exclusion or configurations). Shouldn't the cache file be left untouched in that case?

In any way, thanks for the super-prompt response.

**Comment by robertsLando** [comment]
> I noticed that the cache file is overwritten during service termination, either if no changes are made (and I can guess it is the most frequent scenario... network already setup and no changes made in nodes inclusion / exclusion or configurations). Shouldn't the cache file be left untouched in that case?

I think that is by design, BTW that cache file is handled by zwavejs so I left @AlCalzone answer to this

**Comment by AlCalzone** [comment]
The way the json cache is built, its not easy to detect changes atm. https://github.com/zwave-js/node-zwave-js/issues/3091 should solve this when done.

**Comment by robertsLando** [comment]
@gzone156 please close this issue if you think it's fixed

**Comment by gzone156** [comment]
Thanks, it's all clear now.

About the handling of the SIGTERM vs SIGINT, do you think it is an open subject? Should this issue be used for a deeper analysis of that subject, or will it be more appropriate to open an issue on zwave-js project?

**Comment by robertsLando** [comment]
I actually catch both signals but maybe for some reason SIGTERM doesn't give the app the time to close gracefully: https://github.com/zwave-js/zwavejs2mqtt/blob/master/app.ts#L1220

**Comment by AlCalzone** [comment]
The driver (node-zwave-js) doesn't handle signals. When the application destroys the driver it must make sure to give it enough time to save everything to disk.

**Comment by gzone156** [comment]
Ok, I'll stick using SIGINT and close this issue.

Thanks for the wonderful job you're doing with this project! 🙇🏼
