### ISSUE TITLE
[bug] Can't connect to Aeotec ZWave Stick over Ser2Net after upgrade

### ISSUE THREAD

**Issue by Chrisgozd** [zwave-js/zwavejs2mqtt#2086]
### Version

**Checklist:**

- [x] I am **not** using Home Assistant. **Or:** a developer has told me to come here.
- [x] I have checked the troubleshooting section and my problem is **not** described there.
- [x] I have read the changelog and my problem is **not** mentioned there.

Build/Run method

- [x] Docker
- [ ] PKG
- [ ] Snap package
- [ ] Manually built (git clone - yarn install - yarn run build )

Zwavejs2Mqtt version: 6.1.1
Z-Wave JS version: 8.9.0-beta.1

### Describe the bug

After upgrading from 5.9.0, ZWaveJs2Mqtt does not connect to my Zwave stick over Set2Net.  Downgrading back to 5.9.0 fixes the issue instantly.

### To Reproduce

1. Set up Raspberry PI and plug in Aeotec Zwave stick
2. install Set2Net on the raspberry pi
3. Use the serial port tcp://192.168.1.x:3333 in ZwaveJS2Mqtt

### Expected behavior

ZWaveJS2Mqtt should connect to my Zwave stick over Ser2Net.

[zwavejs_2021-12-22.log](https://github.com/zwave-js/zwavejs2mqtt/files/7763762/zwavejs_2021-12-22.log)
[zwavejs2mqtt_2021-12-22.log](https://github.com/zwave-js/zwavejs2mqtt/files/7763763/zwavejs2mqtt_2021-12-22.log)

**Comment by robertsLando** [comment]
@Chrisgozd Could you try to disable soft-reset from zwave options?

**Comment by Chrisgozd** [comment]
@robertsLando That worked, thanks so much.

**Comment by tastyratz** [comment]
This is still happening with the latest docker container as well for me.
There is no option to disable soft-reset under settings? I see no mention of it anywhere but
The only way for me to successfully set up was to deploy 5.9.0. I'm also using an Aeotec ZWave Stick @ /dev/serial/by-id/usb-0658_0200-if00

Do we know what version that option gets added in?

**Comment by robertsLando** [comment]
5.10.1+ versions comes with soft reset

**Comment by robertsLando** [comment]
This should work with latest version
