### ISSUE TITLE
[feat] Application backup and restore

### ISSUE THREAD

**Issue by robertsLando** [zwave-js/zwavejs2mqtt#2090]
Following discussion https://github.com/zwave-js/zwavejs2mqtt/discussions/2068

- [ ] Add backup/restore buttons in store UI. This will download the files in store needed for backup
- [ ] Add a setting to automatically backup NVM after each node operation (add/remove/replace)
- [ ] Add Bckup/Restore section to docs explaining when NVM and/or Store files should be bakuped/restored

**Comment by onedr0p** [comment]
Hi @robertsLando 👋🏼 

This would be great to have, I am looking to have zwavejs2mqtt manage backups for me. I run this in Kubernetes and mount local storage to `/usr/src/app/store` and a NFS volume to `/usr/src/app/store/backups/` so I can have backups on more durable storage (NFS backed by ZFS). Having a nightly backup or on configuration change would be great with retention settings so the backups do not grow exponentially.

**Comment by robertsLando** [comment]
Forgot to close this
