### ISSUE TITLE
[question]  Loss of connection to ws://ipaddress Im guessing

### ISSUE THREAD

**Issue by trickiegt** [zwave-js/zwavejs2mqtt#2094]
Driver Version: 8.9.0-beta.1
Server Version: 1.13.0
Home ID: 3581443114
Server URL: ws://192.168.10.14:3000

So I've been having problems lately where I can not toggle lights / locks / thermostats.  The fix for this is to either restart the docker container of zwavejs2mqtt  OR  disable the js server -> save -> re-enable js server -> save
It seems to last somewhere around 12 hours...  What's interesting is the fact that server still recieves data from the zwave devices... ie motion / temp / humidity

I run Home Assistant and try to stay on the latest version as much as possible currently Version supervisor-2021.12.2 / core-2021.12.5 
I do not believe the issue resides with HA, something is going on with the server.  I say this because I have tried a multitude of work arounds.  
My original setup was NUCi8 running Mint Linux --- Home assistant was running in a VM --- zwavejs2mqtt was running as a supervisor addon and I was not using the MQTT feature (I prefer the GUI for zwavejs2mqtt over zwavejs)

Once the problem started, I put up with it for a bit just restarting the entire VM -> then I tried using the MQTT side of things but that does not support thermostats natively and HA does not recommend using that format... so then I tried a fresh install of everything -- Linux Host / Home Assistant VM (with backup restore) -- same results //////// Next attempt -> remove zwavejs2mqtt from HA supervior addons... install it on the host machine in docker and then let home assistant connect to the host ip.  Same issue //////// Next attempt -> Took a mini industrial pc and installed HA OS on it (no more virtual machine) set everything back up including the zwavejs2mqtt supervisor addon ---- Same issue....  Removed the addon, installed the docker image back on the NUC (now only running a linux distro)  same issue....

So I've tried different PCs and different methods of resets... I'm pretty sure the docker image is at fault as (again) I can correct this issue simply by diabling the js server and then re-enabling it.  And agian, the logbook shows that it is constantly recieving information from my zwave network... Just something is lost / hung / broken in the js server... Restarting HA has no effect, reconfiguring HA's connection to js server has no effect... only restarting the js server works.

Sorry I know thats a lot to read... but thanks for your time and interest <3
Chris
[zwavejs_2021-12-23.log](https://github.com/zwave-js/zwavejs2mqtt/files/7772056/zwavejs_2021-12-23.log)
`2021-12-23 20:24:01 ERROR (MainThread) [homeassistant.core] Error executing service: <ServiceCall switch.turn_on (c:c0ec0e45f141416efb2c820f016b7fd5): entity_id=['switch.driveway_postlamp_switch_current_value']>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1511, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 209, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 663, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 896, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 700, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/zwave_js/switch.py", line 78, in async_turn_on
    await self.info.node.async_set_value(self._target_value, True)
  File "/usr/local/lib/python3.9/site-packages/zwave_js_server/model/node.py", line 449, in async_set_value
    result = await self.async_send_command(
  File "/usr/local/lib/python3.9/site-packages/zwave_js_server/model/node.py", line 406, in async_send_command
    result = await self.client.async_send_command(message, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/zwave_js_server/client.py", line 77, in async_send_command
    await self._send_json_message(message)
  File "/usr/local/lib/python3.9/site-packages/zwave_js_server/client.py", line 329, in _send_json_message
    raise NotConnected
zwave_js_server.exceptions.NotConnected`

**Comment by jmgiaever** [comment]
Hi. This is a known issue. Please give 8.9.0 (not the beta's a try).

**Comment by trickiegt** [comment]
Ha, thanks for pointing that out... I didn't even realize I was on a beta... normally the 'latest' tag doesn't give me beta drivers...  I see there is a new "latest" version that was released yesterday.  I just redeployed my docker image with "pull latest" and now I am no longer on a beta driver.  Odd. 
zwavejs2mqtt: 6.2.0
zwave-js: 8.9.1
home id: 3581443114
home hex: 0xd5787c2a

Thanks for the intel! Merry Christmas to all / Happy Holidays

**Comment by jmgiaever** [comment]
Z2M 6.1 was released with the beta.1 by mistake. Hope this solves it for you. :)

**Comment by mostlychris** [comment]
I am also on beta somehow and these symptoms sound a lot like what I am seeing on my network. I get data from devices but can't control anything. Restarting the zwavejs2mqtt add-on fixes things for a bit. I don't have an update in supervised Home Assistant yet. Is there a way to force it off the beta in the add-on?

**Comment by trickiegt** [comment]
Depends on your setup really.  Probably the easiest thing to do would be to message [frenck](https://github.com/sponsors/frenck) and ask him to update the add-on.   I am not currently using the add-on for HA.  I have it running via docker on a different linux machine (I moved my adapter to the other machine as well.)

If you really want to have it working NOW -- [make your own supervisor add-on](https://github.com/hassio-addons/addon-example) for zwavejs2mqtt.  Just MAKE SURE you download all the files from the 'store' folder --- you can do it via the web based page in home assistant
and make sure you save/write down/whatever the codes for your zwave stick (s2 unauthenticated / authenticated / access control / s0 legacy)  --- They can all be found in the settings page/Zwave tab in the same web interface.

I'll help you if you need anything -- Just send me a private message
-Chris

**Comment by trickiegt** [comment]
Also, I will confirm that I no longer have issues after updating to the latest release

P.S -> mostlychris -> there are many other ways to get you up and running on the latest version, I just don't know what you have to work with or what you want to work with... those 2 options keep you in HA and will allow HA to make a backup of the add-on    --- pretty sure any other route you go HA will not be able to maintain a backup for you
-But speaking of backup's .... Perhaps another option for you...  
**Load up a backup!**
The Last working version pushed by frenck was "Release of add-on Z-Wave JS to MQTT 0.31.1" -- it is running ⬆️ Upgrades ZwaveJS2Mqtt to v6.0.3 @frenck (#307)

That update was released 23 days ago... and was then updated again 11 days ago..

Soooo if you have any backups from that window in time, you can reload it!
Usually I do FULL backups... sooo here's what I would do...
1) Create new FULL backup of current system.
2) Load backup from time period where zwavejs2mqtt was working version
3) create a backup of ONLY zwavejs2mqtt
4) Load LATEST backup that you made in step 1
5) Load backup of zwavejs2mqtt that you made in step 3
6) Create new FULL backup

That should fix everything for you & just dont update the add-on until frenck pushes the latest version

(Hopefully you have backups for this idea)

<3
-Chris

**Comment by mostlychris** [comment]
After making my comment above, I went back to 31.1. I'll assume that one will resolve the issue for now. I don't want to go the route of rolling my own at this point since I don't have a lot of time for that. I'll watch for updates to fix the beta issue and then upgrade at that point.  Thanks!
