### ISSUE TITLE
[question]  Migrating from Openhab to zwavejs

### ISSUE THREAD

**Issue by giejay** [zwave-js/zwavejs2mqtt#2097]
I would like to move the controller logic to this project instead of using Openhab.

I would like to prevent re-pairing all my nodes (which are in the wall), do I just need to copy paste my 1 security key from Openhab into all 4 keys in zwavejs? 

KEY_S0_Legacy
KEY_S2_Unauthenticated
KEY_S2_Authenticated
KEY_S2_AccessControl

Or is the Openhab one a legacy key and do I only need to copy it in that environment variable?

Edit: just saw that Openhab does not support S2: https://github.com/openhab/org.openhab.binding.zwave/issues/1124.
I guess that means that copying s0 is enough?

**Comment by jmgiaever** [comment]
Yes. S0 is enough. You need to create new keys for each of the S2 security protocols.

**Comment by giejay** [comment]
Thanks for the quick reply!
