### ISSUE TITLE
[bug] Unable to remove dead node

### ISSUE THREAD

**Issue by sstarcher** [zwave-js/zwavejs2mqtt#2099]
### Version
zwavejs2mqtt 6.2.0
zwavejs 8.9.1

**Checklist:**

- [X] I am **not** using Home Assistant. **Or:** a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is **not** described there.
- The link to the troubleshooting section did not seem to show anything
- [X] I have read the changelog and my problem is **not** mentioned there.

Build/Run method

- [X] PKG

Zwavejs2Mqtt version:  6.2.0
Z-Wave JS version: 8.9.1

`Why does your template have Version at the top, but you also ask for it here?`

### Describe the bug

A dozen failed nodes in the control-panel, but I am unable to remove any of them.

### To Reproduce

1. Go to control panel
2. Click on the node -> Advanced -> Failed Nodes(Remove)
3. Nothing happens

### Expected behavior

Node gets removed

### Additional context

I'm using a Aeotec G7 controller and trying to enroll a BE469ZP lock which is failing to be detected, but the main issue here is the inability to remove the dozen failed nodes.  After doing the interview process once over the next 12 hours additional nodes kept appearing.

[zwavejs2mqtt.log](https://github.com/zwave-js/zwavejs2mqtt/files/7775894/zwavejs2mqtt.log)
![Screen Shot 2021-12-25 at 7 42 52 AM](https://user-images.githubusercontent.com/3778974/147386326-7cf205dd-1aef-4a05-be57-726b4d3505c5.png)

**Comment by robertsLando** [comment]
Please upload zwavejs logs too

**Comment by sstarcher** [comment]
Thanks, sorry I missed the second portion of the docs.  I saw the download logs and stopped after the first one.


[zwavejs2mqtt-store.zip](https://github.com/zwave-js/zwavejs2mqtt/files/7777005/zwavejs2mqtt-store.zip)

**Comment by robertsLando** [comment]
Check your logs at startup: 

> Writing the device index to disk failed: File or directory '/**/zwavejs2mqtt/node_modules/@zwave-js/config/config/devices/index.json' was not included into executable at compilation stage. Please recompile adding it as asset or script

I think this is an error related to pkg setup, I need to try to add that as an asset

**Comment by sstarcher** [comment]
Interesting, I have always used the package and I have been able to remove nodes in the past.
