### ISSUE TITLE
[bug] Grouping by security level has duplicate groups

### ISSUE THREAD

**Issue by LordMike** [zwave-js/zwavejs2mqtt#2101]
### Version

zwavejs2mqtt: 6.2.0
zwave-js: 8.9.1
home id: 3815907651
home hex: 0xe3722143

**Checklist:**

- [x] I am **not** using Home Assistant. **Or:** a developer has told me to come here.
- [x] I have checked the troubleshooting section and my problem is **not** described there.
- [x] I have read the changelog and my problem is **not** mentioned there.

Build/Run method

- [x] Docker
- [ ] PKG
- [ ] Snap package
- [ ] Manually built (git clone - yarn install - yarn run build )

### Describe the bug

When grouping by Security level, I get the below image - the "None" security has been duplicated into two seperate groups. The groups with blank texts ("") are probably a migration thing.

![image](https://user-images.githubusercontent.com/1027111/147387948-f4d98e13-7254-4d93-bf08-242363cf90bf.png)

### To Reproduce

On my end I simply group the security column, and there are duplicate groups.

![image](https://user-images.githubusercontent.com/1027111/147388026-574ad5c6-c125-43c0-996d-09b61bda5d26.png)

### Expected behavior

Only one of each grouped value appears. All devices are moved to the corresponding group.

### Additional context

* If I minimize one of the "None" groups, _all_ of the None groups are minimized. So they are likely the "same", just not visually grouped.

**Comment by robertsLando** [comment]
@ahochsteger ?

**Comment by ahochsteger** [comment]
I guess it has to do with #1977 - I'll look into it.

**Comment by robertsLando** [comment]
@ahochsteger Thanks! :)

**Comment by robertsLando** [comment]
Fixed by #2414
