### ISSUE TITLE
[feat] Visualize running firmware updates

### ISSUE THREAD

**Issue by LordMike** [zwave-js/zwavejs2mqtt#2110]
**Is your feature request related to a problem? Please describe.**
See #2093

Visualize a progress bar for OTA updates, so the progress is visible to users.

**Describe the solution you'd like**
@robertsLando hinted to making a new column on the devices list for this, but I suggest reusing the "fw" column -- it will only contain additional data when an update is running.

I've tried to prototype it with HTML editing in the picture below. (I know that a more fancy progress bar exists, so please use that :P)

![image](https://user-images.githubusercontent.com/1027111/147491985-b78d40fe-568c-4f3f-8cfa-025457575375.png)

**Comment by LordMike** [comment]
Could also include the next-version (use an icon for the arrow, ofc.):

![image](https://user-images.githubusercontent.com/1027111/147492285-4af0eca4-e91b-4f33-b02e-08b173717067.png)

**Comment by robertsLando** [comment]
Thanks for the issue @LordMike , will try to find some time next week :)
