### ISSUE TITLE
[feat] Implement health reporting between controller<->nodes or node<->node

### ISSUE THREAD

**Issue by LordMike** [zwave-js/zwavejs2mqtt#2113]
**Is your feature request related to a problem? Please describe.**
I'm always partially troubleshooting a z-wave issue, where I can't always put my finger on what's wrong. Usually I can explain it with a lot of traffic (ex: turn of _all_ lights at once), or distance (4 hops according to graph)..

But I'm worried that something larger is at play, f.ex. I sometimes (anecdotally) experience huge delays between two nodes that should communicate directly (associations).

**Describe the solution you'd like**
I was probing the zwave-js issue tracker, and [noticed this](https://github.com/zwave-js/node-zwave-js/pull/3744).

Would it be possible to get a form of "network health" overview in zwavejs2mqtt?

It'd be really cool to schedule a check (like healing) where all nodes are visited and probed by some checking code, like the one above, to evaluate if there are any issues. I imagine an end result could be an entire view by itself showing:

* Last reports by node, with top-level scores and possibly more detailed scores for each neighbor (or whatever info can be obtained)
* Listing of "issues", such as:
  * Nodes are "far away" (3+ hops from controller)
  * Nodes have few/many neighbors (I could gather from the PR that too many neighbors is bad)
    * Alternate: Nodes have many neighbors with equal weight
    * Nodes have neighbors with a high preference (low weight?), which are battery powered (would this even happen?)
  * High values in error/retry rates on controller / nodes (do we get the stats for nodes?)
  * Nodes of same make/model, with differences in firmware versions

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by robertsLando** [comment]
So to be clear:

- [ ] Add a setting to schedule health check of the network at a specific time
- [ ] Add new tab, let's call it `health`, where we show the general network health with the result of `checkLifelineHealth` and `checkRouteHealth`, maybe the second one should just be used to test routes between neighbors?

@AlCalzone Do you have any tips here about how the UI could looks and if doing this could cause any kind of problem in the network?

**Comment by LordMike** [comment]
And as a stretch goal, the "issues" system I mentioned.. Kind of like a "fix it" system or some such. The goal would be to have a set of rules of best practices, that the user could apply - be it better positioning of the controller or purchasing more powered routing devices.. :)

I could move that to a different issue.

**Comment by AlCalzone** [comment]
> * I could gather from the PR that too many neighbors is bad

Too **few** neighbors is bad.

> High values in error/retry rates on controller / nodes (do we get the stats for nodes?)

You do. Hover over the **↑↓** in the nodes list.

> neighbors with equal weight

There's no such thing. Z-Wave operates mostly by using the last working route (LWR) or next to last working route (NLWR). Once a working route (even if not the best) was found, it will be used until it doesn't work. They can be extracted from the controller memory, but not on the fly during normal operation.
Instead, I'm working on a way to expose the routing info included in the transmit reports as part of the node statistics. When that is done, it can be used to draw an actual routing map, i.e. which routes are being used and how "good" are they? Only you won't be able to see the direct connections.

> Add new tab, let's call it health, where we show the general network health with the result of checkLifelineHealth and checkRouteHealth

Yeah, that should be a tool on its own. Extra tab sounds good. Or maybe include it in the network map?

> maybe the second one should just be used to test routes between neighbors?

That's what it is for.

>  schedule health check of the network at a specific time

I wouldn't do that. Like healing where every node pings every other node (~10k messages for a 100-node network), a health check is very heavy on the network.
IMO that should be done on demand - for single nodes, when diagnosing issues or after (un)installing nodes - and under supervision (so one can do something with the results).

**Comment by LordMike** [comment]
I'm psyched to get some automatic recommendations to improve the network. Any form of automated rules, like "too few neighbors" or "high retry/drop rates on node X" could be great to highlight as actionable issues.

As for scheduling - when I read it I read "start it now, and like healing, run it on all nodes (once) as they wake up" - which was fine. But if it's a "run it every N hours" then no, it's prob. bad.

**Comment by LordMike** [comment]
> > Or maybe include it in the network map
> 
> Thoguht about that, I need ideas about how

Map and health:

* Color lines based on health
* Add symbols to lines with icons indicating issues or lack of issues
* If a node is only available through links with issues, perhaps indicate this somehow -- maybe this happens automatically, as that node will inherit all issues in its own health checks

**Comment by robertsLando** [comment]
PR ready @LordMike

**Comment by LordMike** [comment]
Exciting. You really must (please.. :)) make an on-demand build job that makes a docker tag for each PR - so that when someone like me comes by we can simply consume it and test :)

**Comment by robertsLando** [comment]
@LordMike already done. Check `test` tag 😎
