### ISSUE TITLE
[bug] Wrong device state

### ISSUE THREAD

**Issue by Brian-lub** [zwave-js/zwavejs2mqtt#2116]
### Version

**Checklist:**

- [x ] I am **not** using Home Assistant. **Or:** a developer has told me to come here.
- [x ] I have checked the troubleshooting section and my problem is **not** described there.
- [x] I have read the changelog and my problem is **not** mentioned there.

Build/Run method

- [ ] Docker
- [ ] PKG
- [ ] Snap package
- [ ] Manually built (git clone - yarn install - yarn run build )

Zwavejs2Mqtt version: <version here, you can find it on control panel>
Z-Wave JS version: <version here, you can find it on control panel>

### To Reproduce

1. Go to the entitie and activate
2. See the entitie go on wait 3-4 sec the entitie wil go off but the device will still be on
3. To turn it off again i have to turn on and off quick then i will go of

### Expected behavior

When i activate the device in HA or Z-wave2MQTT i would like it to show the state og the device, but it always goes back to off,

if it will help you can contact me and we can do a TeamViewer meeting so you can try it yourself 

### Additional context

[zwavejs2mqtt-store (1).zip](https://github.com/zwave-js/zwavejs2mqtt/files/7789505/zwavejs2mqtt-store.1.zip)
[zwavejs2mqtt-store.zip](https://github.com/zwave-js/zwavejs2mqtt/files/7789507/zwavejs2mqtt-store.zip)
[Dump and node.zip](https://github.com/zwave-js/zwavejs2mqtt/files/7789511/Dump.and.node.zip)
[Debug info Node 59.txt](https://github.com/zwave-js/zwavejs2mqtt/files/7789509/Debug.info.Node.59.txt)
![2021-12-29 09_35_22-Window](https://user-images.githubusercontent.com/47833231/147675671-104bcf92-37bb-479e-9952-95594fe4046a.png)

**Comment by robertsLando** [comment]
@Brian-lub Are you using zwave integration?

**Comment by Brian-lub** [comment]
> @Brian-lub Are you using zwave integration?

Yes i am using z-wave js,

**Comment by jmgiaever** [comment]
I guess @robertsLando is asking if you're using zwave-js-server through zwavejs2mqtt ("zwave integration") or the zwave-js-server. 

Anyway, please include version of Z2M and zwjs.

**Comment by Brian-lub** [comment]
![SmartSelect_20211229-193806_Home Assistant.jpg](https://user-images.githubusercontent.com/47833231/147693258-217740af-30e9-468e-8b56-959f3357f5a4.jpg)![SmartSelect_20211229-193722_Home Assistant.jpg](https://user-images.githubusercontent.com/47833231/147693262-002bee20-b659-4d03-9284-d52114515597.jpg)

**Comment by jmgiaever** [comment]
This just happens on this device, or any switch?

**Comment by Brian-lub** [comment]
Only on this device, never on any other devices of mine

**Comment by robertsLando** [comment]
@Brian-lub If you are using z2m with hass integration I have no control on the behaviour of the entities created, on my side the messages are received correctly

**Comment by Brian-lub** [comment]
Okay, do you have any idea what is going wrong. I have tried so much with this device, i am about to give up.

**Comment by Brian-lub** [comment]
> @Brian-lub If you are using z2m with hass integration I have no control on the behaviour of the entities created, on my side the messages are received correctly

But if you see the picture of the entity card and log, you see it comes with a true to false message but the device is still on

**Comment by robertsLando** [comment]
@Brian-lub the device is reporting what you see on debug windows so the problem it's on the device that isn't reporting the correct state, If I understand it correctly what happens is that you turn on the device, it phisically turns on, but then you see the ui switch to off and the device is still turned on. IMO it's a device issue as it is reporting a wrong state

**Comment by Brian-lub** [comment]
Okay, i will get another device for my floorheating, it works with Vera and Fibaro homecenter, but nothing else apparently.
Thank you for your time,

**Comment by robertsLando** [comment]
@Brian-lub Try to check if there is a device firmware update or a device configuration setting could also fix it

**Comment by Brian-lub** [comment]
> @Brian-lub Try to check if there is a device firmware update or a device configuration setting could also fix it
> 

> I have done the update and it does not work, the manufacturer will not help, i have  been in contact with them several times and they want me to bye there new device at full price, but can't confirm that it will fix my problem, in vera you should make a lot of parameter changes to make it work, https://logic-group.com/produkt/zif5020/
If you look in chapter 8 in the manual

**Comment by AlCalzone** [comment]
It could be possible that
1. the device takes longer than 1s to toggle to the target state and
2. it does not automatically the new state

Can't tell without seeing driver logs though. At the very least you could try to refresh the value after a couple of seconds and see if it is still wrong.
