### ISSUE TITLE
[feat] Use new `restoreNVM` API to restore NVM backups

### ISSUE THREAD

**Issue by kpine** [zwave-js/zwavejs2mqtt#2119]
**Describe the solution you'd like**

Z2M currently uses the `restoreNVMRaw` API to restore a backed up NVM. This API requires the the source and target controller NVMs are compatible. node-zwave-js v8.9.0 added a new [`restoreNVM` API](https://zwave-js.github.io/node-zwave-js/#/api/controller?id=nvm-backup-and-restore) which automatically converts the NVM backup to the correct target format. Using the new one would allow users to backup from a 500 and restore to a 700, for example.

Unless I'm missing something, there doesn't seem to be any reason for applications to use `restoreNVMRaw` anymore with this new API available.

**Comment by robertsLando** [comment]
@kpine Thanks! It's a quick fix, just need to change the api name
