### ISSUE TITLE
How to Control Light Switches?

### ISSUE THREAD

**Issue by ryanagler** [zwave-js/zwavejs2mqtt#2124]
I am wondering if I am missing somewhere in the UI that you can control a light switch (turn it on/off)?  The README says "Control Panel UI: Directly control your nodes and their values from the UI".

In the default Z-Wave JS UI, each device in the list has a "Controls" toggle button you can turn the light on/off.   That is incredibly useful when testing switches.  So I assume the much more advanced zwavejs2mqtt UI must have something similar I am just missing.

**Comment by LordMike** [comment]
It does - under each node you can visually see all "command classes" you can manipulate. For lights, you're looking for Binary Switch and Multilevel Switch (dimmers).

![image](https://user-images.githubusercontent.com/1027111/147856724-bddbb32f-42ca-4827-b748-070545d1fce0.png)

Note that there may be multiple "endpoints".
