### ISSUE TITLE
[feat] Allow setting additional color components in Color Switch Set, for device without support

### ISSUE THREAD

**Issue by LordMike** [zwave-js/zwavejs2mqtt#2127]
**Is your feature request related to a problem? Please describe.**
I have some wall switches with LEDS, where I've finally figured out how to make them blink. The vendor has (mis-)used an unused color component to transmit stuff like "enable blinking" and "blink interval".

Turns out that the color switch set is used in this project as red/green/blue (components 2, 3 and 4).. This vendor uses component 0 to configure other stuff.

**Describe the solution you'd like**
This is advanced, and unusual, so I imagined a setup where the MQTT topics can receive commands with additional components beyond the normal RGB:

```
> zwavejs2mqtt/NODE/51/1/targetColor
{"red":255,"green":0,"blue":0,"0":255}
```

This would tell zwave-js to map "red" to component 2 (as today), etc.. and then for component "0" to be this value `255`. Others can use their own components to configure those as well.

In principal, this should be identical:
```
> zwavejs2mqtt/NODE/51/1/targetColor
{"2":255,"3":0,"4":0,"0":255}
```

**Describe alternatives you've considered**
I also considered a format with arrays, like `[255,null,255,255,255]`, where null indicates the component shouldn't be sent. This deviates from the current setup, so it's probably not useful.

**Additional context**
N/A

**Comment by LordMike** [comment]
I found this code within zwavejs, so I thought I could perhaps already use it today:
https://github.com/zwave-js/node-zwave-js/blob/27bb4ee0cce202a93e1479aa4aca4ce5e2589a58/packages/zwave-js/src/lib/commandclass/ColorSwitchCC.ts#L62-L72

But sending the new component yields an error:
```
2022-01-01 15:57:39.222 INFO MQTT: Message received on zwavejs2mqtt/wallswitch_30_1/51/1/targetColor/set: '{"red": 0, "green": 0, "blue": 15,"Warm white":10}'
2022-01-01 15:57:39.223 INFO ZWAVE: Writing { red: 0, green: 0, blue: 15, 'Warm white': 10 } to 76-51-1-targetColor
2022-01-01 15:57:39.225 ERROR ZWAVE: Unable to write { red: 0, green: 0, blue: 15, 'Warm white': 10 } on 76-51-1-targetColor
```

**Comment by robertsLando** [comment]
@LordMike AFAIK what you wrote there should be supported, `targetColor` is a virtual value that has been created on purpose to handle all the colors in one in a json format. Dunno why the `warmWhite` isn't picked up by zwavesjs, is warmWhite present in your valueIds? Because I don't see it reported on currentColor so I think that's the problem

cc @AlCalzone

**Comment by AlCalzone** [comment]
@LordMike does your device report support for other color components than red, green and blue?

**Comment by LordMike** [comment]
Ah - I've never seen other components in `currentColor`, so the device likely doesn't report it.

I've tested with Z-wave pc controller, and it does _respond_ to it.. I can poke the vendor, but they likely won't implement it, as they misuse it to transmit a byte of configuration, rather than an actual "warmWhite" value, so if anybody used it as "warmWhite", it wouldn't work as expected.

Is there something I can do to enable support for my usecase?

**Comment by AlCalzone** [comment]
> they misuse it to transmit a byte of configuration

Nice. What the hell is a standard anyways...

> Is there something I can do to enable support for my usecase?

Edit the `.values.jsonl` cache file while Z2m is offline and add the missing color component to the list of supported ones. Then never re-interview the device again.

Or wait for https://github.com/zwave-js/node-zwave-js/issues/1625

**Comment by LordMike** [comment]
What would you _need_ a standard for .. It's just glorified hindrance :)

I'll make do without the component for now :)

 .. should we close this / mark as blocked?

**Comment by AlCalzone** [comment]
You could use the CC API https://zwave-js.github.io/node-zwave-js/#/api/CCs/ColorSwitch?id=set, which doesn't have the additional check

**Comment by robertsLando** [comment]
> You could use the CC API zwave-js.github.io/node-zwave-js/#/api/CCs/ColorSwitch?id=set, which doesn't have the additional check

You should use sendCommand api or driverCommand to do that

**Comment by LordMike** [comment]
I wonder if these devices require me to send all 4 components to work, when this "Enhanced LED mode" is enabled.. (which enables the hack for blinking).

.. when I enable the setting and just set the three components as usual, they don't respond.. So I always assumed it wasn't working, until I actually found out about the fourth component... 

Hmm..

But thanks - I can make that work :)

**Comment by scyto** [comment]
> Nice. What the hell is a standard anyways...

![image](https://user-images.githubusercontent.com/11369180/148136226-c7cbecd8-9ad1-4dd5-aff9-d62de36d85d5.png)

sorry couldn't resist
