### ISSUE TITLE
[bug] nodes.json contains invalid/old data

### ISSUE THREAD

**Issue by jmgiaever** [zwave-js/zwavejs2mqtt#2129]
### Version

**Checklist:**

- [x] I am **not** using Home Assistant. **Or:** a developer has told me to come here.
- [x] I have checked the troubleshooting section and my problem is **not** described there.
- [x] I have read the changelog and my problem is **not** mentioned there.

Build/Run method

- [ ] Docker
- [ ] PKG
- [x] Snap package
- [ ] Manually built (git clone - yarn install - yarn run build )

zwavejs2mqtt: 6.2.0.fa6b2ab
zwave-js: 8.9.3-0-pr-4011-940427a
home id: 3685395904
home hex: 0xdbaaadc0

### Describe the bug

`nodes.json` contain nodes that is removed from the network. Shouldn't cause big issues, but I guess when the controller reaches #232 it will start re-use node id's, then causing new nodes using old `nodes.json` data.

### Expected behavior

`nodes.json` to be in sync with the nodes in the network.

**Comment by robertsLando** [comment]
> nodes.json contain nodes that is removed from the network. Shouldn't cause big issues, but I guess when the controller reaches #232 it will start re-use node id's, then causing new nodes using old nodes.json data.

I know that, I did it on purpose as nodes.json could be also restored from an old network. Let's say you want to add all nodes back to a new controller and you have a nodes.json backup you can add a node and you will get it automatically named as it is added

**Comment by jmgiaever** [comment]
But that will require you to re-include them in the same order, and be lucky to not fail the inclusion so they actually get the same id? 

If you restore, then you probably have a backup of the nodes.json file too?

**Comment by robertsLando** [comment]
I mean it doesn't create any issue to me, when I needed to restore a network I simply re-added all nodes one by one in the same order (and If I did it worng I just renamed them) but if this is causing issues I can just keep it in sync with the actual network

**Comment by jmgiaever** [comment]
But I guess you have a quite small network. In my case I'm already on node id 182. That's simply because a Smart Start device failed to include for long, so around 40 ids was used without me doing anything, just for that node.  

I've never been able to re-build the network exactly the same. I have at the time 56 nodes, but around 20 nodes are still missing. I would expect to hit the limit of 232 nodes when I'm going to include them since inclusion of 56 nodes have gotten me to node 182 already. 🤪

Do you have a context, that could prevent auto-removal, when the context is in "replace failed node"?

But this doesn't make a huge problem though, except confusion when a new node is identified as something unexpected. Especially in large networks. 

One possible solution could be to ask the user to re-use the data in nodes.json after including a device - if there is data for that node id in nodes.json?

**Comment by robertsLando** [comment]
>  I would expect to hit the limit of 232 nodes when I'm going to include them since inclusion of 56 nodes have gotten me to node 182 already. 🤪

I think that once reached the id limit controller will start to use the free ids :) 

BTW I should add a check in replace failed call that sets a var that could prevent the remove to drop nodes.json data

**Comment by jmgiaever** [comment]
But that's my point; there's IDs with data in the nodes that I consider "free", that the controller will pick when I hit the limit and it will start picking unused IDs in-between (I assume) old nodes.
