### ISSUE TITLE
How can I change the default password?

### ISSUE THREAD

**Issue by bplatypus** [zwave-js/zwavejs2mqtt#2135]
Hi!

First, thanks for this gateway & control panel, installation was flawless!

I wanted to change the default 'zwave' password to something else but not sure how to do it... didn't find something in the UI to do it. I noticed the users.json file but I would still need something to generate the hash for my new password.

I was about to go check how the hash is calculated in the source code but I'm pretty sure I'm missing something :-D

Thanks for the help.

**Comment by jmgiaever** [comment]
If i remember correctly there's a lock icon (or was it a person?) in the upper right corner area that you can click to change password and manage users.

**Comment by bplatypus** [comment]
> If i remember correctly there's a lock icon (or was it a person?) in the upper right corner area that you can click to change password and manage users.

ooohhhhh thanks! Was searching in the settings, but that's it. Thanks :-)
