### ISSUE TITLE
Add option to reset security classes on re-interview

### ISSUE THREAD

**Issue by AlCalzone** [zwave-js/zwavejs2mqtt#2139]
`refreshInfo` now has an option to also reset the security classes: https://zwave-js.github.io/node-zwave-js/#/api/node?id=refreshinfo

This is important when the security classes have been wrongly detected, e.g. if the keys were wrong. Without this, users have to edit the cache file to get their devices working again.

**Comment by AlCalzone** [comment]
Nevermind, I'm just blind.

**Comment by robertsLando** [comment]
@AlCalzone I feel better now that also happens you too 😆
