### ISSUE TITLE
[question] Server URL is reset when restarting HASS

### ISSUE THREAD

**Issue by rcdailey** [zwave-js/zwavejs2mqtt#2151]
I'm using HASS OS and I have zwavejs2mqtt plugin installed. The ZWave integration initially sets the URL to `ws://a0d7b954-zwavejs2mqtt:3000`, but I manually change it to `ws://localhost:3000` (because I mapped port 3000 to the host in the supervisor settings for the plugin). But when I restart HASS, it resets the URL back to the first version. How can I prevent it from changing it?

**Comment by kpine** [comment]
This is the wrong repository, this project has nothing to do with the zwave-js integration. You would want to report integration issues with the HA core repo.

But why are you exposing the server port and changing the integration server setting? There is no reason to do so.

Localhost is invalid either way, the server is not accessible from the HA container localhost. The exposed port would be accessible on the host's IP address or hostname.

**Comment by rcdailey** [comment]
Because the integration is failing often to communicate with the plugin using the generated domain name. I'm assuming it's a routing issue so this was my attempt to remedy it. Localhost is working when I use it, I assume that means HASS itself is on the host and when I expose ports in plugin configuration that makes plugins accessible to integration. But I don't really know what the HASS OS architecture is, nor have I found documentation explaining it so this is an assumption based on my observations.

**Comment by kpine** [comment]
OK, it does appear that exposing the port does make it available on localhost from HA. That is surprising to me.

All of the add-ons are containers, so they are accessible by name on the Docker network. The HA container is part of the same Docker network. If the default address, `ws://a0d7b954-zwavejs2mqtt:3000` is not working, then something is indeed not working as intended.

Regardless, this is still the wrong place to open an issue. You either need to submit a [new issue](https://github.com/home-assistant/core/issues/new/choose) with the HA core project, or get technical support from one of the [community support channels](https://www.home-assistant.io/help/#communication-channels). This project, zwavejs2mqtt, is not responsible for the Z-Wave JS integration.

**Comment by robertsLando** [comment]
Thanks @kpine
