### ISSUE TITLE
[bug/feat] Device files in the container

### ISSUE THREAD

**Issue by lazyoldbear** [zwave-js/zwavejs2mqtt#216]
The way the official container is created, it contains a lot of device files (created explicitly, all right). Including the essential ones, like `/dev/ttyACM[01]`.
Now, that might be convenient if one just runs the thing throught a container engine, or is fine living with `privileged` in orchestrators. 
There is, however, a better way, at least for Kubernetes: [smarter device manager](https://community.arm.com/developer/research/b/articles/posts/a-smarter-device-manager-for-kubernetes-on-the-edge). It propagates host resources to the nodes, and allows also to keep track over allocation (so that you don't start two pods asking for the same dongle). And no more `privileged`. 
However, the existence of a device with the same numbers in the container interferes, so that the device file is not created. Since the access to the device is propagated, you can still use the device in an unprivileged container, but it requires to know the naming, which is hard to maintain over reloads. 

The suggestion, which can be interpreted either as bug or feature request, is to remove device files from the official container.

**Comment by robertsLando** [comment]
>  is to remove device files from the official container

Are you able to draft this in a PR?

**Comment by lazyoldbear** [comment]
Perhaps, although not instantly: I have neither any environment at hand to play with Docker, nor a registry. 

However, I reckoned that whoever chose to add the devices, did it on purpose, so it would feel safer to first clarify if those reasons interfere with the current issue.

**Comment by blhoward2** [comment]
The docker container contains a full Linux distribution, so the dev files are likely populated by the distribution’s setup.

**Comment by lazyoldbear** [comment]
@blhoward2 That is just incorrect. As a quick experiment, compare the image internals with the base (`node:erbium-alpine`). It does have _some_ devices, necessary for basic operations like tty and stuff.

Looks like this comes through Dockerfile ARG `updateDevices` (line 4), which is used to trigger a violent action on line 31.  
Killing the ARG is not at all unfullfilable, but I assume that there is a less dramatic way, like narrowing the set of devices to really necessary. Or even migrating to the entrypoint.

**Comment by blhoward2** [comment]
> @blhoward2 That is just incorrect. As a quick experiment, compare the image internals with the base (`node:erbium-alpine`). It does have _some_ devices, necessary for basic operations like tty and stuff.
> 
> Looks like this comes through Dockerfile ARG `updateDevices` (line 4), which is used to trigger a violent action on line 31.
> Killing the ARG is not at all unfullfilable, but I assume that there is a less dramatic way, like narrowing the set of devices to really necessary. Or even migrating to the entrypoint.

The docker files build off Dockerfile.contrib as far as I know. At leas they do when you manually build them using the docker build kit.

**Comment by lazyoldbear** [comment]
No, I don't even have Docker anywhere, or anything else that builds images. 
Besides, I don't need to build it: I know that if "excessive" device files are removed, everything will work properly. 
However, as I mentioned above, I assume that whoever started creating them devices, did it on purpose. 
So I assumed that asking a question might be a quick way to bring the context in sync with possible stakeholders.

**Comment by lazyoldbear** [comment]
But I did try pods on `zwavejs2mqtt` and `node:erbium-alpine`, to make sure. 
What I did not try is to alter `zwavejs2mqtt` specifically, for it requires building an image and putting it to some registry.

**Comment by blhoward2** [comment]
Just spin up the base image like you would the final image and see if they are there?

**Comment by lazyoldbear** [comment]
Yes, that I did, in the first place. Apologies for not being clear.

**Comment by blhoward2** [comment]
And they were not in the base image? Could you list the specific device files (some examples)?

**Comment by lazyoldbear** [comment]
All right, the problem was in the [chart](https://github.com/k8s-at-home/charts/blob/master/charts/zwavejs2mqtt/values.yaml). It had default `privileged: true`, and needed explicit `false`. 
I am sorry for the fuzz.

**Comment by blhoward2** [comment]
Glad you got it figured out. I was surprised it would be that breakable.

**Comment by lazyoldbear** [comment]
Well, I was confused by the black magic with devices. 
And the last thing I expected from a chart is to have privileged as default (working on a pull request there). :-) 
Sorry again.
