### ISSUE TITLE
[feat] Add custom driver snippets

### ISSUE THREAD

**Issue by blhoward2** [zwave-js/zwavejs2mqtt#2176]
**Is your feature request related to a problem? Please describe.**
Limited UI space and ever expanding features creates challenges. 

**Describe the solution you'd like**
As discussed, we should look at implementing script snippets that allow scripts for custom driver functions to be reused and saved. For example:

1. Copying one device's parameters to another device

2. Replace a failed node and copy parameters from current device (e.g. if you're going to have to reinclude a node, you could save off the parameters and then restore them after inclusion.)

3. Change region on 700 sticks

**Comment by jmgiaever** [comment]
+1 it's just a few days since I thought about the same. Maybe run snippets from a directory within the store folder could work as a solution?

**Comment by robertsLando** [comment]
> Maybe run snippets from a directory within the store folder could work as a solution?

Snippets are run using driver function

**Comment by jmgiaever** [comment]
Yeah, but if you have them in a folder in a store, it should be possible to import them?

**Comment by robertsLando** [comment]
> Yeah, but if you have them in a folder in a store, it should be possible to import them?

I would prefer to simply write snippets in the popup dialog, users can copy/paste them there if needed, the idea is to just add a dropdown menu where there are snippets templates that once selected show the code in the code editor with some comments to help users edit them based on their needs

**Comment by jmgiaever** [comment]
For me it's the same, as long as you could re-use them. 

But how would you overcome backing them up? I was thinking that if you had them in a sub directory of the store directory (e.g `store/snippets`, where snippets could be stored) it would make them easy to backup too. 

...And I don't know how many times the my VIM habit have closed the «driver function» window and cleared everything when I've pressed `ESC` when done and ready to execute :rofl: 

Then they could be listed and fetched when selected in a drop-down.

**Comment by robertsLando** [comment]
@jmgiaever Oh yeah I think having them in files in a folder makes sense :)

**Comment by jmgiaever** [comment]
Just adding to this feature, as suggested by @robertsLando, that the logger needs to be included in the «driver function», so the output generated can be added to logs. 

Also reading through the feature made me unsure if I had misunderstood the concept explained, and therefor adding a photo which describes better what I meant.

![Screenshot from 2022-08-31 14-44-53](https://user-images.githubusercontent.com/7188121/187691597-26041507-c889-4d39-ac1a-85b697a7a420.png)
