### ISSUE TITLE
[feat] Allowing setting name/location before regular inclusion

### ISSUE THREAD

**Issue by blhoward2** [zwave-js/zwavejs2mqtt#2183]
**Is your feature request related to a problem? Please describe.**

HA parses and sets up entity domains based on the device's name and location at the time it receives a Node Ready. Subsequent name changes in zjs2mqtt are updated for the device name in HA (so long as it hasn't been renamed there), but the entity domains aren't updated after creation. 

**Describe the solution you'd like**

Allow the user to preset the name/location prior to inclusion like they can with SmartStart. Set this as soon as possible post-inclusion but before the Node becomes ready.

**Comment by Botched1** [comment]
I think that would be very useful, too.

**Comment by jmgiaever** [comment]
+1 from me ☺️ I always have to shut down the zwave-js-server when adding nodes, and when I forget I decide to re-include the device instead of going through the renaming process.
