### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by adwuk** [zwave-js/zwavejs2mqtt#2189]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Manually built (git clone - yarn build - yarn install

### Zwavejs2Mqtt version

zwavejs2mqtt: 6.2.0.bd8c933

### ZwaveJS version

zwave-js: 8.9.2

### Describe the bug

Two Aeotec Multisensor 6 units installed - one is detected as battery powered and the other as mains powered (as shown on the dashboard). Both are battery powered and the exported JSON for the two nodes has the correct current state for the property:
```
"propertyName": "Current Power Mode"
"states": [{"text": "USB Power", "value": 0},{"text": "Battery", "value": 1}],
"value": 1,
```
JSON files are attached for the two nodes, as well as a screenshot of the ZWaveJS2MQTT device dashboard.  Node 5 is the one that is displayed as mains powered.  I have seen the node marked as dead, presumably because it didn't reply to a ping, when it was in fact asleep.

[node_9.json.txt](https://github.com/zwave-js/zwavejs2mqtt/files/7875084/node_9.json.txt)
[node_5.json.txt](https://github.com/zwave-js/zwavejs2mqtt/files/7875085/node_5.json.txt)
![Screenshot 2022-01-15 140010](https://user-images.githubusercontent.com/17555423/149624397-eed8a850-9db5-45b9-8222-940c07847eb2.jpg)

### To Reproduce

I have re-interviewed the nodes when on battery power and there has been no change to the power icon on the main dashboard.

### Expected behavior

The nodes should be displayed as battery powered, along with the battery percentage.

**Comment by robertsLando** [comment]
@AlCalzone I have checked the 2 nodes.json export, one has the isListening property set to true and the other one has it to false, this is why I'm displaing one as main and one as battery powered. Is there any reason why node 5 is reported as isListening even if it is battery powered?

**Comment by AlCalzone** [comment]
Yeah, it was included on USB power and that doesn't change without excluding and re-including on battery power.

**Comment by adwuk** [comment]
No idea why there would be a difference.  I had a third one which was also showing as mains powered, so I excluded/included it and it is now showing as battery powered.  It is possible that I included node 5 with it connected to USB power.  Just seen your latest comment. OK, I will sort out node 5 in the same way. Thanks.
