### ISSUE TITLE
[question] Docker container won't run without privileged

### ISSUE THREAD

**Issue by lidocaineus** [zwave-js/zwavejs2mqtt#2190]
If I run the container with docker-compose and the example compose file with some minor modifications (explicitly setting volumes and ports), it will fail to start with 

ERROR APP: Port 8091 requires elevated privileges

Running in privileged mode gets around this, but is obviously not preferred (plus it messes up device mapping due to /dev getting auto-mapped in). That port isn't normally privileged to begin with, so I'm not sure what's going on here…

**Comment by robertsLando** [comment]
Thre has been lot discussions about this and we ended up that running container in privilege mode is the preferred method

ref #783
