### ISSUE TITLE
[Bug]: Using Aeotec ZWA024, luminance is reported with wrong value

### ISSUE THREAD

**Issue by paifre** [zwave-js/zwavejs2mqtt#2191]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Zwavejs2Mqtt version

6.4.0

### ZwaveJS version

8.11.0

### Describe the bug

Aeotec ZWA024-C (EU) firmware 1.1 + Zstick7 + Docker zwavejs2mqtt image on Pi0w
The differents thresholds parameters are configured to reports high/low on temperature, humidity, luminance not UV 
To qualify the problem, multisensor installed in a 100% dark room with a remote controlled light.
Data are also captured using MQTT Explorer.
While displaying a luminance of 0 Lux, at some point of time, Lux value jumps to 748 Lux.
Each time this problem has been seen, same value: 748 or 749 Lux, mostly 748.
Turning the light, correct 45 Lux was reported initially then keeping the light on, value bumped from 45 to 789 (748+45=793 ??)
see screenshot from MQTT explorer
Clicking on refresh, value to reported as expected either 0 if in dark or 45-48 if light's on
Motion detection is reported correctly. Values from other sensors (Temp/Hum) are corrects compairing those  values with other devices installed nearby.

Few minutes ago, doing a manual refresh of multisensor values: luminance suddendly dropped to 105.  (see screenshot 2022-01-16_13-16-17.jpg)
So I will deploy an Gen5 sensor to compare values, but anyway right now I'm not able to know who's wrong : silabs zwave api layer, zwavejs api layer, frontend layer or hardware layer. Need some guidance here please.
![2022-01-16_13-16-17](https://user-images.githubusercontent.com/37601174/149659688-fc4f8fa7-3e72-46e1-b160-77f4a0f62f0b.jpg)

_Another small detail : Having done three re-interviews, the second interview reported value for Configuration to "vundefined" instead of "v4". Other two, reported correctly v4_

![AeotecZWA024_Luminance_Report_Issue](https://user-images.githubusercontent.com/37601174/149659423-27a3c8e0-5d65-44af-a258-d8bf6dac4059.jpg)
[zwavejs_2022-01-16.log](https://github.com/zwave-js/zwavejs2mqtt/files/7876904/zwavejs_2022-01-16.log)
[zwavejs2mqtt_2022-01-16.log](https://github.com/zwave-js/zwavejs2mqtt/files/7876905/zwavejs2mqtt_2022-01-16.log)

_I've tried to run in debug mode, but strange message in debug window ?
Error: Not Found
at /usr/src/app/server/app.js:934:17
at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:317:13)
at /usr/src/app/node_modules/express/lib/router/index.js:284:7
at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:335:12)
at next (/usr/src/app/node_modules/express/lib/router/index.js:275:10)
at session (/usr/src/app/node_modules/express-session/index.js:479:7)
at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:317:13)
at /usr/src/app/node_modules/express/lib/router/index.js:284:7_

I'll keep you posted once deploying a second luminance sensor to baseling comparison.

### To Reproduce

See Bug description

### Expected behavior

Correct value reported

**Comment by paifre** [comment]
Luminance reported by Multisensor 6 is close to value reported by Gen7.  Gen7 sensors seems ok.

**Comment by robertsLando** [comment]
@paifre That error could just be a 404 so nothing related to the sensor, about your error I think it could be a device issue. cc 
@AlCalzone

**Comment by AlCalzone** [comment]
Yep, zwave-js doesn't do any correction for values. They are passed through 1:1 from the device. Some allow calibration, but if that doesn't help, it's a case for the Aeotec support.

**Comment by paifre** [comment]
Tomorrow, I'm working remotely. So I will connect with Simplicity studio and let things run. I should know what is pushed by the multilevel sensor.

**Comment by paifre** [comment]
Hello,  as you've correctly highlighted, I confirm that PC Controller reports also 750Lux
I can see a nice 02 EE at the end...

**Comment by paifre** [comment]
Hello, some update.... for resolution record
Resetting (hw reset) the sensor, problem disappeared.
This was a software stack issue on Aeotec side, could bad configuration being pushed generating such weird behavior (remember value was correct using a refresh, wrong when pushed at device initiative...). 
Also on the other hand, I've not done exactly same setup. Outlimit related parameters are not used this time, only report on threshold.
Rule of thumbs: remove, reset, include again !
