### ISSUE TITLE
Move the inclusion information to a seperate tab

### ISSUE THREAD

**Issue by Roagert** [zwave-js/zwavejs2mqtt#2197]
![image](https://user-images.githubusercontent.com/33527165/150073971-f128e6dc-95b8-4b6f-b035-c48f9889b6f8.png)

This seems like a long description for a device and should maybe have its own tab. This is occupying alot of area in the overview tab.

**Comment by robertsLando** [comment]
Thanks Thomas, will sort this out soon :)

**Comment by Roagert** [comment]
Amazing that you already did this :) Thanks !
