### ISSUE TITLE
Schlage BE468 missing sensors when using zwavejstomqtt

### ISSUE THREAD

**Issue by githubbuh** [zwave-js/zwavejs2mqtt#2204]
Environment
core-2021.12.10
zwavejstomqtt 0.34.1
docker 20.10.12
zwave controller aeotec z-stick gen5+ (brand new this week)

background
While using ozw with homeassistant 0.99, an aeotec z-stick gen5, and node-red, it was possible to automate the use of the Schlage BE468 using the sensor.door_lock_access_control (lock "event type". Schage button, exterior key pad entry, or interior knob) and the sensor.door_lock_alarm_level (index into the user access code array to determine the user code entered).

When using zwavejstomqtt, neither of the required sensors (access_control and alarm_level) are available, which makes it impossible to integrate with the BE468. 

There are no errors in the zwavejstomqtt log.

**Comment by robertsLando** [comment]
Are you using z2m as mqtt gateway? You mean you don't see access control and alarm level values? Neighter on control panel?

**Comment by githubbuh** [comment]
@robertsLando , I am not using z2m as an mqtt gateway.  There are no entities for the device called access control or alarm level.

An update -- i backed out z2m, installed the deprecated ozw integration and noticed that the lock no longer has an access control sensor.  it appears to have been replaced by alarm type.  alarm level is still available.

**Comment by kpine** [comment]
In HA, alarm_level and alarm_type are hidden by default. You would need to go to the device page, expand the disabled entities, and enable them. However, these entities are only available for older locks which zwave-js does not automatically map to notifications (if you have one of these locks, consider submitting an issue to node-zwave-js so it's mapped properly).

For newer locks, or older locks that have alarm to notification mapping, you would use the [notification event](https://www.home-assistant.io/integrations/zwave_js/#node-events-notification).

**Comment by githubbuh** [comment]
@kpine,

super helpful information.  thank you.

I wonder if some of your response would be helpful to others if it were added to the [Home Assistant - Lock page](https://www.home-assistant.io/integrations/lock/)

Thanks again.

**Comment by githubbuh** [comment]
@kpine

Thanks again for your help. I had time today to get the zwave event working. Event 1 and 2 are lock and unlock from inside. 5 and 6 are the event types for lock and unlock from outside. 

It was pretty painless. 

Thanks in advance,

Frederick

On Jan 24, 2022, at 11:07 PM, kpine ***@***.***> wrote:

﻿
In HA, alarm_level and alarm_type are hidden by default. You would need to go to the device page, expand the disabled entities, and enable them. However, these entities are only available for older locks which zwave-js does not automatically map to notifications (if you have one of these locks, consider submitting an issue to node-zwave-js so it's mapped properly).

For newer locks, or older locks that have alarm to notification mapping, you would use the notification event.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by kpine** [comment]
> Thanks again for your help. I had time today to get the zwave event working. Event 1 and 2 are lock and unlock from inside. 5 and 6 are the event types for lock and unlock from outside.

If you report this information to [node-zwave-js](https://github.com/zwave-js/node-zwave-js/issues/new/choose), then probably mappings could be created for the device to map these events to the "modern" notifications.
