### ISSUE TITLE
cant get docker container to listen to mqtt

### ISSUE THREAD

**Issue by th48178** [zwave-js/zwavejs2mqtt#2207]
I have deployed the docker container using docker compose like in the sample and while I can get this to work with home assistant and the ws server, I can not get mqtt working using mqtt lens. Scanning the ports of the pi that holds the docker confirms nothing is listening on 1883 .

the log shows errors

2022-01-25 03:16:59.927 INFO ZWAVE-SERVER: Client disconnected
2022-01-25 03:17:00.522 INFO MQTT: MQTT client reconnecting
2022-01-25 03:17:00.528 ERROR MQTT: Mqtt client error connect ECONNREFUSED XXX.XXX.XXX.XXX:1883

repeating every few seconds.

I tried to add the port 1883 to the docker compose template, but that did nothing.
I tried to change the host url in the config to mqtt://XXX.XXX.XXX.XXX
but the errors persist and nothing seems to make a difference.

zwavejs2mqtt is at version 6.4.1 which is latest as of this moment I think. I tried previous versions and they seem to behave the same.

is there a guide how to make this work or a more detailed error to track this down 

thanks

**Comment by kpine** [comment]
zwavejs2mqtt is not an mqtt broker (server). You need to install and setup an mqtt broker yourself, like mosquitto, and tell zwavejs2mqtt to connect to the broker. Your broker listens on port 1883 and you would configure zwavejs2mqtt to connect to it.

**Comment by th48178** [comment]
Thank you for that clarification. Works beautifully with eclipse.
