### ISSUE TITLE
[Bug]: Inputing name during inclusion does not work

### ISSUE THREAD

**Issue by Matt-PMCT** [zwave-js/zwavejs2mqtt#2210]
### Checklist

- [ ]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Zwavejs2Mqtt version

6.4.1

### ZwaveJS version

8.11.1

### Describe the bug

The new interface from pull #2194 is a very nice feature. However, I have included 3 devices on two different instances of zwave-js2mqtt and the name never gets applied to the device. Instead, the device has no name/location one inclusion is completed. 

### To Reproduce

Include a device, write in a name, once inclusion is complete the device will still have no name

### Expected behavior

The name you input should be applied :)

**Comment by robertsLando** [comment]
Hi @Matt-PMCT I cannot reproduce your bug, could you attach some application logs please? (debug level)

Logs should include an inclusion attemp

**Comment by joostvkempen** [comment]
I've just started with ZwaveJS2MQTT, only just added one device (Fibaro Dimmer 2) and experienced the same. So I found this issue. Still figuring out things, I'll try some logging when adding more devices.

**Comment by jmgiaever** [comment]
Hi,
Still and issue
```
zwavejs2mqtt: 6.5.0.5844e6c
zwave-js: 8.11.2
```
[zwavejs2mqtt_2022-02-06 (1).log](https://github.com/zwave-js/zwavejs2mqtt/files/8011275/zwavejs2mqtt_2022-02-06.1.log)

I'm adding the «name» and «location» myself at `2022-02-06 22:12:12.885`

**Comment by kpine** [comment]
> I'm adding the «name» and «location» myself at `2022-02-06 22:12:12.885`

That's not what this issue is referring to. When you initiate a classic inclusion, it now prompts for a name and location. If provided, these properties will be set as soon as the node is added.

![image](https://user-images.githubusercontent.com/791794/152711987-115cf14a-42bc-461c-99a5-548186f870ff.png)

Setting the names after the node already included will not work, HA has already created the devices and entities. If working properly, this feature mentions will name the node prior to HA creating anything.

FWIW, I tried it once and it worked.

**Comment by kpine** [comment]
Tried it again with 6.5.0 and was successful, Here's what the inclusion logs look like when it's working:

```
2022-02-06 17:47:05.841 INFO ZWAVE: Calling api startInclusion with args: [
  0,
  { forceSecurity: false, name: 'Motion Sensor', location: 'Office' },
  [length]: 2
]
2022-02-06 17:47:05.865 INFO ZWAVE: Controller status: Secure inclusion started
2022-02-06 17:47:05.866 INFO ZWAVE: Success zwave api call startInclusion true
2022-02-06 17:47:10.387 INFO ZWAVE: Controller status: Inclusion stopped
2022-02-06 17:47:10.813 DEBUG ZWAVE: Updating store nodes.json
2022-02-06 17:47:10.814 DEBUG ZWAVE: Setting node name 'Motion Sensor' to node 3
2022-02-06 17:47:10.815 DEBUG ZWAVE: Setting node location 'Office' to node 3
2022-02-06 17:47:10.816 DEBUG ZWAVE: Binding to node 3 events
2022-02-06 17:47:10.816 DEBUG ZWAVE: Node 3 has been added to nodes array
2022-02-06 17:47:10.816 INFO ZWAVE: Node 3: added with security HIGH SECURITY
```

I provided the node name and location in the initial inclusion dialog, and they are set as soon as it's possible (inclusion stopped event).

![image](https://user-images.githubusercontent.com/791794/152712826-dff705b8-429d-4db9-a3de-21be3e5a5637.png)

[inclusion.log](https://github.com/zwave-js/zwavejs2mqtt/files/8011782/inclusion.log)

**Comment by Matt-PMCT** [comment]
Finally got around to it on my end today.

I used the prompts to add a new node, filled out the info, choose non-encrypted for security. No names were passed on. I am still on 6.4.1. 
![firefox_ZuZgf3F90y](https://user-images.githubusercontent.com/6832191/152717700-92b59e48-b991-41f7-a42a-ce9256a4aa23.png)
![firefox_0iRRzCBeP6](https://user-images.githubusercontent.com/6832191/152717708-34a538e9-878a-4ddb-a386-2997f70665e9.png)
![firefox_XWCqP6XwRD](https://user-images.githubusercontent.com/6832191/152717709-af28b556-a4b8-438e-9c0c-def3174875b5.png)

![firefox_jUx4AeMwVU](https://user-images.githubusercontent.com/6832191/152717713-f113ac75-d240-4018-ad2d-1041a6296fc2.png)

[zwavejs2mqtt-store.zip](https://github.com/zwave-js/zwavejs2mqtt/files/8012036/zwavejs2mqtt-store.zip)

**Comment by kpine** [comment]
> I am still on 6.4.1.

I would suggest upgrading. There were some naming related fixes included in 6.5.0.

**Comment by robertsLando** [comment]
Like @kpine said I fixed that in latest release. Please upgrade to that one

**Comment by jmgiaever** [comment]
I'm on 6.5.0. Issue is there.

**Comment by kpine** [comment]
@jmgiaever Do you have any new logs then?

**Comment by jmgiaever** [comment]
New logs? I have this: https://github.com/zwave-js/zwavejs2mqtt/issues/2210#issuecomment-1030918528

**Comment by kpine** [comment]
Can you describe your problem then? According to your logs and statement, you did not set the name and location during inclusion, which is what this issue is about.

**Comment by jmgiaever** [comment]
> That's not what this issue is referring to. When you initiate a classic inclusion, it now prompts for a name and location. If provided, these properties will be set as soon as the node is added.

It's what this issue is about. Check the attached log. I'm using that form to add details (line 12 - 20), but they are lost during the inclusion. 

And then I add it manually at `2022-02-06 22:12:12.895` (name) and `2022-02-06 22:12:18.885` (location)

**Comment by kpine** [comment]
Sorry, I already realized that and corrected myself. I previously just focused on your statement about setting them manually...

Does it work if you don't force security and just include normally? I'm guessing the security bootstrapping takes longer than 2 seconds. Z2m throws away the node name and location if it takes more than 2 seconds to go from "inclusion stopped" to "node added".

**Comment by jmgiaever** [comment]
No worries. I actually didn't get it until now that most post after mine yesterday was addressed to me. So suddenly had a some post to read through. 

I just added a node that doesn't have any security (HS1MS-Z) and it worked.

Got to admit that I have barely experienced the bootstrapping taking less than 2 sec :grin: As of the 700-issue I've been waiting to add all devices. Now having 61 one in and still counting. ~90%+ of my devices are included S2, the rest is S0 and «none». Over 50% are main powered, but not spamming the network. 

I guess the 2 seconds-rule is the cause here yes. Is there a reason why Z2M throws any of this away as long as inclusion doesn't fail?

**Comment by jmgiaever** [comment]
I guess the driver emits `inclusion-stopped` in both cases where inclusion fails or succeeds. 

There was an issue where node data would be reused (from `nodes.json`) when you've reached the 232 limit and starts reusing old id's. 

Daniel wanted to preserve them in the case of «replace failed nodes», which I absolutely agree with :+1: He talked about - if my memory is correct - using a boolean that would prevent writing to the file in the situation of replacing a node, but I'm not sure what he ended up with. Haven't checked the code.

**Comment by Matt-PMCT** [comment]
I did the same test in 6.5.0 and it worked for me this time. I'm ready for the issue to be closed. But maybe there is still more to be looked at?

**Comment by robertsLando** [comment]
>  Z2m sets a timer after the first event for 2 seconds and clears the inclusion name and location, which would be set in the second event.

I sincerly have no idea how much time it's ok to wait here. I firstly didn't set a timeout at all at it was working, then @jmgiaever told me it wasn't so I added that to delay the reset. What I could do eventually is to don't reset them there and just do the reset when the inclusion is started or the node is added successfully

**Comment by robertsLando** [comment]
Anyone that could give a try to #2247 ?
