### ISSUE TITLE
/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by 

### ISSUE THREAD

**Issue by pw44** [zwave-js/zwavejs2mqtt#2211]
Hya,

i downloaded the package zwavejs2mqtt-v6.4.1.zip (latest) on ubuntu 18.04 and when trying to run, i get an error.

# ./zwavejs2mqtt 
pkg/prelude/bootstrap.js:1697
      throw error;
      ^

Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/7d1250c91f3ad911ea616a8053cbb5ddbd230baa12d642277907cf905e8c0071/bindings.node)
    at tryImporting (pkg/prelude/bootstrap.js:2028:37)

Any clue? No, i'm not able to upgrade the OS.

**Comment by robertsLando** [comment]
Unfortunately there is no way to fix this ATM. It's something related to serialport module, see https://github.com/serialport/node-serialport/issues/2266

**Comment by robertsLando** [comment]
Try with latest version. Sohuld be ok now
