### ISSUE TITLE
[feat] Automatically ping / poll any dead or unresponsive nodes upon status change

### ISSUE THREAD

**Issue by harryfrishberg** [zwave-js/zwavejs2mqtt#2227]
**Problem/Motivation**

I have been experiencing a higher than usual occurrence of the "unknown" status on various Z-Wave nodes. 99% of the time, this problem is immediately fixed by running the ping command. But with 50+ devices, it becomes a daily chore. I have tried healing the network, re-interviewing frequent offenders, but nothing seems to work.

**Proposed changes**

If possible, could an optional function be added to ping or poll any nodes that have become "unknown" or otherwise unresponsive until they become "alive" again? After a set amount of time, if no response is heard, the devices can be marked as "dead".

---

PS - I've attempted to create a Home Assistant automation with this functionality, but my knowledge of scripting is subpar and I can't seem to get it working. In case anyone can spot an error in my ways, here is the automation:

id: 'xxxxxxxxxxx'
alias: Red October
description: Pings any dead or unknown nodes on Z Wave Network until a response is heard
trigger:
platform: event
event_type: state_changed
condition:
condition: and
conditions:
condition: template
value_template: '{{ trigger.event.data.new_state.domain == "sensor, switch, lock, light" }}'
condition: template
value_template: '{{ trigger.event.data.new_state.state == "dead, unavailable, unknown, none" }}'
action:
repeat:
until:
- condition: template
value_template: '{{ trigger.event.data.new_state.state == "alive" }}'
sequence:
- service: zwave_js.ping
target:
entity_id: '{{ trigger.entity_id }}'
- delay:
hours: 0
minutes: 1
seconds: 0
milliseconds: 0
mode: parallel
max: 5

**Comment by AlCalzone** [comment]
No, for multiple reasons:

1. Attempting communication with dead devices can introduce relatively long timeouts/delays. Some sticks even go haywire under specific circumstances.
2. Frequently dead devices mean there is a bigger issue with the mesh that should be solved and not just masked by essentially "ignoring" the fact that the communication has issues.
3. Frequently **unknown** devices can **only** happen after startup when the stick doesn't boot properly or stops to function for a longer timeframe. This can be somewhat mitigated with the softreset on startup, but many users have that turned off due to additional host-level configuration that is required to support it on many 500 series sticks.  
This also means that the driver isn't done initializing, because the driver actually pings unknown devices on startup to determine if they are alive or dead.

**Comment by christopherthiele** [comment]
Briefly on the subject of Home Assistant automation: The conditions are wrong.

`'{{ trigger.event.data.new_state.state == "dead, unavailable, unknown, none" }}'`
This means the state must match the complete value "dead, unavailable, unknown, none" exactly - all at once.

But the state only assumes one of these possible values. So it must be like this.
`{{ trigger.event.data.new_state.state in ["dead", "unavailable", "unknown", "none"] }}`
The same applies to domain.

PS: The automation will run "forever" if the device is actually broken.

**Comment by harryfrishberg** [comment]
Thanks @AlCalzone for explaining the barriers to a feature like this. 

I can disable the "softreset" option my 5+ stick, but the problem doesn't seem to happen at startup. It'll be running for hours (or days) without issue and then suddenly a couple nodes will suddenly become "unknown". I can ping them and they immediately respond and change status back to "alive". 

Does this still sound like a startup issue?

It sounds like it's not a really a viable change to the zwavejs2mqtt software. If it's a problem on my 5+ Z stick, do you recommend updating its firmware? or maybe changing to a new stick?

And appreciate the code fix, @christopherthiele -- is there a way I could have the ping commands run a few times and then stop it if the devices are indeed offline?

**Comment by christopherthiele** [comment]
Yes. You can extend the until condition:
`{{ trigger.event.data.new_state.state == "alive" or repeat.index >= 10 }}`
This exits the loop when the node is alive **or** 10 iterations have been reached.

**Comment by AlCalzone** [comment]
> I can disable the "softreset" option my 5+ stick

That's not what I meant. It should ideally be **enabled**.

> without issue and then suddenly a couple nodes will suddenly become "unknown"

There is no state transition that allows the node status to become unknown. Its more likely that the driver is restarting for some reason (do you have driver logs?) and then you're experiencing startup issues.

**Comment by harryfrishberg** [comment]
@christopherthiele - I will give that a try, thank you! 

@AlCalzone - copy that. I have reenabled "softreset" and will see how it goes. Right now, all nodes are showing as alive and well, but when I get up tomorrow, I will see if there are any issues. I'll provide logs if there are! Thank you for the help on this.
