### ISSUE TITLE
A legend for the Network Graph [feat]

### ISSUE THREAD

**Issue by mr-ransel** [zwave-js/zwavejs2mqtt#2228]
**Is your feature request related to a problem? Please describe.**
I've been looking at the Network Graph visualization, and I can tell there's a wealth of information to see, but most of it is unexplained or undocumented as to what it means?

**Describe the solution you'd like**
A more detailed legend that includes items for:
All the different node-icon shapes and what they each mean
The meaning of the gradient color-background on a node-icon (when it's only half-filled)
The difference between solid, red-dotted, and green-dotted lines under "All neighbors"

Separately maybe few words/description of "relevant neighbors" vs "all neighbors" ? What makes a neighbor "relevant"?
 I'm not aware of that as an industry term.

**Describe alternatives you've considered**
I tried to find these answers by googling, and asking around on discord, and short of reading the source code I don't have any idea how else to get this information, since it's seemingly undocumented.

**Additional context**

Seems like this should be a pretty quick fix. Even a little note somewhere in documentation would be greatly appreciated.

**Comment by robertsLando** [comment]
I have refactored options a bit in https://github.com/zwave-js/zwavejs2mqtt/pull/2248

Seems some of them were a bit useless, I have also added filters
