### ISSUE TITLE
ZWaveJS2MQTT docker settings wiped clean after update

### ISSUE THREAD

**Issue by Kodemikkel** [zwave-js/zwavejs2mqtt#2235]
Hi,
I recently updated my ZWaveJS2MQTT Docker running on Unraid, and after the update, all my settings and devices were wiped clean. After a bit of reading online, I figured it was because I didn't set a persistent storage location outside of the docker container, shame on me for that.
Anyway, after starting my, now clean, ZWaveJS2MQTT-container I noticed that there are no settings under the "Z-Wave" settings page except "Disable MQTT Gateway". There are no fields for network key, gateway path, or anything else.
When starting the docker container I get:

[90m2022-02-03 14:50:24.477[39m [33mWARN[39m [1mSTORE[22m: settings.json not found
[90m2022-02-03 14:50:24.487[39m [33mWARN[39m [1mSTORE[22m: scenes.json not found
[90m2022-02-03 14:50:24.488[39m [33mWARN[39m [1mSTORE[22m: nodes.json not found
[90m2022-02-03 14:50:24.503[39m [33mWARN[39m [1mSTORE[22m: users.json not found
[90m2022-02-03 14:50:24.515[39m [32mINFO[39m [1mAPP[22m: Listening on port 8091 host 0.0.0.0 protocol HTTP
[90m2022-02-03 14:50:24.659[39m [31mERROR[39m [1mGATEWAY[22m: Zwave settings are not valid

My questions would be:
1. What is going on here?
2. Is there any way to restore my old settings (no backups, although I do have my previously used network key available)?
3. Might fix the issue, but will make question 2 not viable anymore, I guess; but would a factory reset of my stick sort things out?

I am very new to Docker, so I might need a bit of help if there is anything fancy I need to do in regards to that.

Thanks for reading and I am hoping for any suggestions :)

**Comment by Kodemikkel** [comment]
Sorted itself out.
After a couple of restarts, the settings appeared and allowed me to enter my old network key and thus getting my devices back.

**Comment by robertsLando** [comment]
Glad you fixed, let me know if the problem persists
