### ISSUE TITLE
[question] Unable to include FGMS001 for replace a failed node.

### ISSUE THREAD

**Issue by candrea77** [zwave-js/zwavejs2mqtt#2241]
zwavejs2mqtt: 6.5.0
zwave-js: 8.11.2

I'm trying to include an FGMS001 (firmware v3.2) for replace a filed device (Node ID 139) 
The process fail every time (both NoEncryption and S0)

I've got a Fibaro HC : same new device can be included in the Fibaro Controller with no problem.

I'm using an Aeotec ZW090 Firmware 1.2
You can find attached the Log of the inclusion process

Can someone help me find out the problem ?

[zwavejs_2022-02-04.log](https://github.com/zwave-js/zwavejs2mqtt/files/8005455/zwavejs_2022-02-04.log)

**Comment by candrea77** [comment]
After multiple retry , Node is now correctly included in S0 security.

**Comment by candrea77** [comment]
Hi [robertsLando](https://github.com/robertsLando), sorry for reopen this.

By my point of view seems that there is some problem  .....
I've got same issue doing another Node replace (I've also try the Inclusion process with same problem)
This time the node is an FGS223 Firmware 3.2

In order to complete the replace I've had to use the PC - Controller software from Silabs because using zwavejs2mqtt i wasn't able to do that.

There is a better specific place to open this reporting in order to allow someone to analyze it ?

**Comment by jmgiaever** [comment]
Hi. Seems like a zwavejs issue @AlCalzone

**Comment by candrea77** [comment]
Quick update : in order to get device included with zwavejs , I've had to remove device using zwave controller.
At this point, adding as new node ID do the tricks.

**Comment by AlCalzone** [comment]
I've noticed that sometimes you have to start and abort an exclusion process first before including works. Due to the lack of driver logs I can only guess here though.
