### ISSUE TITLE
[Bug]: Can not open network graphs since 6.5.0

### ISSUE THREAD

**Issue by Botched1** [zwave-js/zwavejs2mqtt#2242]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Zwavejs2Mqtt version

6.5.0

### ZwaveJS version

8.11.2

### Describe the bug

The network graph page will not load since upgrading to 6.5.0.

### To Reproduce

Since upgrading to z2m 6.5.0, when I go to the network graph page, it starts refreshing neighbors and then never loads the graph and eventually chrome complains about the page being unresponsive, and offers to close it. I've tried waiting >5 minutes, and the graph never shows up.

This is on a reasonably large mesh - 110 assets.

### Expected behavior

Network graph page should load.

### Additional context

![image](https://user-images.githubusercontent.com/19985320/152591699-0280c6e6-1222-400b-b943-e1b6e30755bf.png)

**Comment by robertsLando** [comment]
@Botched1 Could you send me a node export please? 

Also I would like to ask you if you can open the chrome dev tools and tell me if you see errors on console

**Comment by Botched1** [comment]
No errors on the console when going to the network map page.

![image](https://user-images.githubusercontent.com/19985320/152815890-19035436-eb87-436f-8964-d7c2f568510d.png)

Node dump attached.
[nodes_dump.zip](https://github.com/zwave-js/zwavejs2mqtt/files/8016404/nodes_dump.zip)

**Comment by robertsLando** [comment]
@Botched1 I just tried using your nodes and yeah webpage freezes... Seems everything on my side is processed correctly then everything freezes when calling d3 `render` method. I will try to see if there are ways to improve the rendiring of the graph :(

**Comment by robertsLando** [comment]
Getting a bit far, tring to show just 80 of your 110 nodes seems working, at first sight the problem may be there are too much edges 🤔 Each one of your node has lot of neighbors, that is good from a network side but increases computation a lot...

**Comment by robertsLando** [comment]
I have just submitted https://github.com/zwave-js/zwavejs2mqtt/pull/2248

That could help partially solve your issue. With that you will be able to filter nodes to show in the graph

**Comment by Botched1** [comment]
Thanks @robertsLando !

I don't really use the graph a lot, so it isn't critical to me. I only opened it in the new version to try to see the new health info, and I believe that is the only place it is available.

**Comment by Botched1** [comment]
@robertsLando 
Just an FYI (not complaining) that I still can't open the mesh maps in 6.5.1. Basically as soon as I open the mesh tab it locks up. 

I can't sometimes click one of the drop downs before it freezes, but thus far have never been able to actually select anything to narrow it down before the tab freezes.

**Comment by robertsLando** [comment]
@Botched1 That's strange, on my instance the graph isn't loaded until the reload button is pressed, I need to investigate I'm sorry for that :(

**Comment by Botched1** [comment]
No worries! I appreciate everything you do here.

I'm running z2m in a docker container, case it matters. I assume it shouldn't but thought I would mention it anyway.

**Comment by robertsLando** [comment]
@Botched1 Did you try with 6.6.0?

**Comment by Botched1** [comment]
I did, and it is working now. Not sure if it was an update in your end, or a chrome update, but it worked in 6.6.0.

**Comment by robertsLando** [comment]
Awesome, thanks!
