### ISSUE TITLE
[Bug]: Log cleanup works for zwavejs logfiles, but not for zwavejs2mqtt logfiles?

### ISSUE THREAD

**Issue by ualex73** [zwave-js/zwavejs2mqtt#2254]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Zwavejs2Mqtt version

6.4.1

### ZwaveJS version

8.11.1

### Describe the bug

I have enabled logging for zwavejs and zwavejs2mqtt. I notice that the zwavejs logfiles are removed after roughly 6 days, but the zwavejs2mqtt are not removed after 6 days. I couldn't find a configuration item for this, so i am assuming it is never cleaned?

The "ls -l *.gz" in the zwavejs2mqtt directory shows the following files:
- zwavejs2mqtt_2022-01-24.log.gz
- zwavejs2mqtt_2022-01-25.log.gz
- zwavejs2mqtt_2022-01-26.log.gz
- zwavejs2mqtt_2022-01-27.log.gz
- zwavejs2mqtt_2022-01-28.log.gz
- zwavejs2mqtt_2022-01-29.log.gz
- zwavejs2mqtt_2022-01-31.log.gz
- zwavejs2mqtt_2022-02-01.log.gz
- zwavejs2mqtt_2022-02-02.log.gz
- zwavejs2mqtt_2022-02-03.log.gz
- zwavejs2mqtt_2022-02-04.log.gz
- zwavejs2mqtt_2022-02-05.log.gz
- zwavejs2mqtt_2022-02-06.log.gz
- zwavejs2mqtt_2022-02-07.log.gz
- zwavejs2mqtt_2022-02-08.log.gz
- zwavejs_2022-02-03.log.gz
- zwavejs_2022-02-04.log.gz
- zwavejs_2022-02-05.log.gz
- zwavejs_2022-02-06.log.gz
- zwavejs_2022-02-07.log.gz
- zwavejs_2022-02-08.log.gz

### To Reproduce

Let zwavejs2mqtt run for 14+ days (i got it running from the 24th of January)

### Expected behavior

Automatic cleanup of zwavejs2mqtt logfiles.

**Comment by robertsLando** [comment]
@ualex73 are you using `Z2M_LOG_MAXFILES` env var?

**Comment by ualex73** [comment]
@robertsLando No, i was not using this environment variable. The default value of "7d" for Z2M_LOG_MAXFILES does not seem to be used?

**Comment by ualex73** [comment]
Thanks 👍  The only environment variable i have configured in zwavejs2mqtt is "TZ=Europe/Amsterdam".

**Comment by robertsLando** [comment]
I have just do some tests on my system using `faketime` library. It seems to work, after 7d of logs files are removed. Could you try to set env var Z2M_LOG_MAXFILES to `7` instead of `7d` to try if that works?

**Comment by ualex73** [comment]
Sorry for the late reply, but no change with "Z2M_LOG_MAXFILES=7". The logfiles are still there from 24-Jan-2022.

**Comment by robertsLando** [comment]
@ualex73 That's really strange as I'm using the exactly same logging library of zwave-js and the same rotating package, I really have no clue what could be the reason... Did you try to check permissions on those files? maybe for some reason they have a permission that doesn't allow application to delete them 🤷🏼‍♂️

**Comment by robertsLando** [comment]
@ualex73 Did you already tried to delete old files? Just to see if maybe there was a specific file that caused the rotating to fail
