### ISSUE TITLE
[Bug]: Home Assistant can no longer connect on reboot

### ISSUE THREAD

**Issue by Altycoder** [zwave-js/zwavejs2mqtt#2255]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [ ] I have checked the troubleshooting section and my problem is not described there.
- [ ] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Zwavejs2Mqtt version

6.5.1

### ZwaveJS version

8.11.4

### Describe the bug

On rebooting my server, Home Assistant can no longer connect to zwavejs2mqtt and I have to restart home assistant for a connection to be made.

I have raised a bug with home assistant ([link](https://github.com/home-assistant/core/issues/65644#issuecomment-1034644001)) but they are suggesting that they haven't changed anything related for home assistant 2022.02.XX and that the issue must lie eleswhere.

When I updgraded from home assistant 2021.12.XX to 2022.02.XX I also upgraded zwavejs2mqtt from 6.1.1 to 6.50 and now 6.5.1. So the question is what's changed between 6.1.1 and 6.5.0/6.5.1 to have caused this?

(I have tried rolling back to 6.1.1 but was not successful).

### To Reproduce

Restart server and home assistant cannot connect to zwavejs2mqtt

### Expected behavior

On server restart home assistant can connect to zwavejs2mqtt

### Additional context

See the link below for the error home assistant throws and associated log.

https://github.com/home-assistant/core/issues/65644#issuecomment-1034644001

**Comment by robertsLando** [comment]
>  I have to restart home assistant for a connection to be made

If restarting hass fixes the issue this means the issue is there, I think for some reason they try to connect to the server on boot but it is not immediatly ready and then stops retring
