### ISSUE TITLE
[question] How to retrieve scene ID on a Fibaro FGD-212 when using wall switch

### ISSUE THREAD

**Issue by paifre** [zwave-js/zwavejs2mqtt#2257]
Hello,

Env. Pi0 + Docker image 6.5.0 +ZStick7

I'm not able to find how to retrieve scene ID using a Fibaro FGD-212 v3.5 when actionning a wall switch
Indeed Scene parameter has been enabled (112-0-28) :). 
As a comparaison, using Jeedom + native Openzwave implementation, scene info is updated with value 10 (switch on ) or 11 (switch off). Good way to know if wall switch has been turned on or off.

Please, have a look to page 27, parameter 28 for Toggle switches
[https://manuals.fibaro.com/content/manuals/en/FGD-212/FGD-212-EN-T-v1.2.pdf](url)

I was looking for similar, but monitoring with MQTT explorer, I don't see any parameter updated related to module scene ID
I see an update of parameter 43-0 which is associated to scene activation CC
I was expecting some SceneID value related to the chart of page 27 of the documentation

I'm lost on this behavior :(  Would highly appreciate if you can provide me inputs

Thanks in advance

**Comment by robertsLando** [comment]
I think them are sent as event, did you tried to check if you see something in logs?

**Comment by paifre** [comment]
Hello,
Deep diving in the content of _EVENTS, I've been able to see in a set a multiple event messages that value attribute is populated with a value of 20 (ON) or 21(OFF).  Thanks for pointing me in the right direction, I will try to catch this information on MQTT using a small program to detect, reformat and publish as I'm not sure I can deal with _EVENTS on client program side. I have to think about. Thx
.....
id: '7-43-0-sceneId'
....
**value: 21**,
lastUpdate: 1645168814407
},

**Comment by robertsLando** [comment]
@paifre It could also be it is published with notification CC (113) or entry control CC (111), check also topics related to this CCs
