### ISSUE TITLE
[question] Setting a value with mqtt has no effects

### ISSUE THREAD

**Issue by graphicsxp** [zwave-js/zwavejs2mqtt#2266]
I am new to zwavejs2mqtt. I have managed to configured my zwave controller in HomeAssistant with the zwavejs2mqtt add-on as well as a Fibaro roller shutter module.
I can control the shutter from the UI just fine : 
![image](https://user-images.githubusercontent.com/4160415/154083161-bf632b8e-054d-465c-bae0-108b148d0cdd.png)

![image](https://user-images.githubusercontent.com/4160415/154083203-82415588-a1db-458f-b22d-65f8f892c33f.png)

Setting the target value will roll up or down the shutter to the correct position.

Now I want to achieve the same thing by publishing a mqtt message. I do so from MQTT Explorer :  

![image](https://user-images.githubusercontent.com/4160415/154083671-c1140e1c-aff9-466d-8b28-545d032d8f6e.png)

I have followed the documention and added /Set at the end of the topic. However nothing happens. Is there a log where I can see the mqtt message ? There's nothing in the logs of my mqtt broker. Is this the correct way to set the value ?

**Comment by graphicsxp** [comment]
yes I had tried both already but it does not change anything.

**Comment by robertsLando** [comment]
@graphicsxp Show me applications logs when sending an mqtt message to a topic that ends with `/set`

Also what application version are you running?

**Comment by graphicsxp** [comment]
I was on 0.35 and I just upgraded to 0.35.1 but it makes no difference

I just fround this in the logs:  
```
2022-02-15 16:37:26.528 ERROR MQTT: Error subscribing to zwave/+/+/+/+/set, client doesn't have permmission to subscribe to it
2022-02-15 16:37:26.531 ERROR MQTT: Error subscribing to zwave/+/+/+/+/+/set, client doesn't have permmission to subscribe to it
```

That sounds like the root of the problem... How do I set this permission ? (funny there's a typo in the log : 'permmission')

**Comment by graphicsxp** [comment]
I have changed the following setting to enable Auth : 
![image](https://user-images.githubusercontent.com/4160415/154099055-e975ef7d-1b6f-4543-9ddf-240a1e65cf91.png)


and now when i publish a message from MQTT explorer, I get that in the log:

2022-02-15 16:54:29.792 INFO MQTT: Message received on zwave/nodeID_2/38/1/targetValue/set: '50'

... But still with no effect :(   Am I not passing the parameter correctly ?

**Comment by graphicsxp** [comment]
Mosquitto broker in home assistant. 

But it's fine now, I don't thet the auth error anymore. However, see my previous message with new log. The message is received, but it seems it never calls the zwave api to execute the action

**Comment by robertsLando** [comment]
@graphicsxp Try to set logging level to debug and retry. Also be sure there is no typo in the topic.

**Comment by graphicsxp** [comment]
I get this :  
```
2022-02-15 17:28:28.311 INFO MQTT: Message received on zwave/nodeID_2/38/1/targetValue/set: '43'
2022-02-15 17:28:28.316 DEBUG GATEWAY: No writeable valueId found for nodeID_2/38/1/targetValue
```

**Comment by graphicsxp** [comment]
I'm unable to find them :(  
I can only see real-time log in home assistand add-on ui.
I have set the following options :  

![image](https://user-images.githubusercontent.com/4160415/154113012-023c6481-4e06-4f1f-bbc0-a9ea772b2fae.png)


But I don't see this folder on the filesystem (home assistant is installed on raspberry pi)

**Comment by graphicsxp** [comment]
I have noticed in the zwave2mqtt debug info console that the definition of my value is : 

`   {
      "id": "2-38-1-targetValue",
      "nodeId": 2,
      "commandClass": 38,
      "commandClassName": "Multilevel Switch",
      "endpoint": 1,
      "property": "targetValue",
      "propertyName": "targetValue",
      "type": "number",
      "readable": true,
      "writeable": true,
      "label": "Target value",
      "stateless": false,
      "commandClassVersion": 4,
      "min": 0,
      "max": 99,
      "list": false,
      "value": 43,
      "lastUpdate": 1644944707032,
      "newValue": 43
    },`

the id contains hypens instead of slashes and when I send the message from mqtt explorer, the log complains it cannot find nodeID_2/38/1/targetValue. 
Also, I find it strange that there is nodeID_2. Should I not call the topic `zwave/2/38/1/targetValue/set` instead of `zwave/nodeID_2/38/1/targetValue/set` ?  I tried that but it makes no difference though.

**Comment by graphicsxp** [comment]
ok, it works now but I'm confused.

The Gateway was configured with Topic Type = Named Topics.

The name of my node is `fibaro` so publishing my message to  `zwave/fibaro/38/1/targetValue/set`  does work.

![image](https://user-images.githubusercontent.com/4160415/154117070-b40912d5-0b4a-4f34-8958-060bbd3144b1.png)

However, I switched it to ValueID topics and restarted the add-on, but publishing to `zwave/fibaro/38/1/targetValue/set`  still works. And publishing to `zwave/nodeID_2/38/1/targetValue/set` does not.

Any idea what I should do ?

**Comment by robertsLando** [comment]
There is a specific option in mqtt setting to use or not node names instead of numeric id
