### ISSUE TITLE
[Bug]: Health Check of one particular node never ends

### ISSUE THREAD

**Issue by kdknigga** [zwave-js/zwavejs2mqtt#2267]
### Checklist

- [ ]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Zwavejs2Mqtt version

6.5.1

### ZwaveJS version

8.11.4

### Describe the bug

When running a health check on one particular node, the health check will never return.  It will seemingly run indefinitely.  Even if I click "close", the checking continues until I restart zwavejs2mqtt.

This is a 2-hop node, but health check works for other 2-hop nodes on my network.  Also, this is a Leviton DZ15S, but health check works for other DZ15Ss I have, including other 2-hop DZ15Ss.  The firmware versions match, too.

Other communication with this node seemingly works just fine.

### To Reproduce

Run health check on this particular node.

### Expected behavior

Health check returns with a result in a minute or so.

### Additional context

[node_34.json.txt](https://github.com/zwave-js/zwavejs2mqtt/files/8081875/node_34.json.txt)
[zwavejs2mqtt_health_check_doesnt_stop.txt](https://github.com/zwave-js/zwavejs2mqtt/files/8081877/zwavejs2mqtt_health_check_doesnt_stop.txt)

In the log file you can see I can successfully run the health check on other nodes (11, 50, and 14).  The node that never ends is 34.

**Comment by kdknigga** [comment]
This is a neat feature, by the way.  Thanks!

**Comment by kpine** [comment]
This is probably the same as https://github.com/zwave-js/node-zwave-js/issues/4075. "Avoid infinite loop when nodes don't progress on their Powerlevel test".

**Comment by kdknigga** [comment]
Ah, maybe!  It certainly looks similar.
