### ISSUE TITLE
Node statistics not updating while hovering

### ISSUE THREAD

**Issue by AlCalzone** [zwave-js/zwavejs2mqtt#2271]
This is during an ongoing firmware upgrade. Notice how the green arrows are blinking and the firmware update is progressing, but no stats are changing:

https://user-images.githubusercontent.com/17641229/154560803-d0952df8-af02-430f-ac1c-2e5b41e2ef89.mp4

**Comment by AlCalzone** [comment]
Actually, it never updates...
![grafik](https://user-images.githubusercontent.com/17641229/154561803-16d7ff15-ff87-4517-abaa-a0dbdc4904a1.png)

**Comment by robertsLando** [comment]
@AlCalzone Are you running latest from master?

**Comment by AlCalzone** [comment]
Which browser?
