### ISSUE TITLE
SmartStart provisioning entries should disable non-requested security classes

### ISSUE THREAD

**Issue by AlCalzone** [zwave-js/zwavejs2mqtt#2274]
so users don't get confused when they change the classes to something that won't work.

Depends on https://github.com/zwave-js/node-zwave-js/issues/4250

**Comment by robertsLando** [comment]
Let me know when that is merged

**Comment by AlCalzone** [comment]
> Add status column to show provisioning entries status

I'd make this a checkbox "active"
