### ISSUE TITLE
[question] SetOutdoorTemp for Stelpro Thermostat?

### ISSUE THREAD

**Issue by carldebilly** [zwave-js/zwavejs2mqtt#228]
## Introduction
I have a bunch of Stelpro Ki thermostats that I installed few years ago when I was using SmartThings. Those thermostats were always working great.

## The feature: display outdoor temperature
The have a feature to show outdoor temperature that works well with SmartThings [the code for that is here](https://github.com/stelpro/Ki-Z-Wave-Thermostat/blob/d106ec8c640d3288850e672bf88352beff6f57c7/devicetypes/stelpro/stelpro-ki-thermostat.src/stelpro-ki-thermostat.groovy#L359_L371).

## The failure
I switched to Home Assistant (which is using OpenZWave) and I never found how to use this feature.

## Specs
On SmartThings, it's using the [`sensorMultilevelV3.sensorMultilevelReport`](https://graph.api.smartthings.com/ide/doc/zwave-utils.html#sensorMultilevelV3) to send this information to the device.

[spec sheet on z-wave alliance](https://products.z-wavealliance.org/products/1603):
```
Outdoor Temperature

When connected to a Z-Wave network, the thermostat may display the outdoor temperature provided by an external sensor.
When available, the outdoor temperature is displayed instead of the set point, providing that the outdoor temperature display setting is set to on.
If no temperature is received within a 4 hours timeframe, the outdoor temperature will disappear and the set point will be displayed.
In order to display the outdoor temperature, an external sensor needs to be part of the Z-Wave network. It may be a physical sensor or a weather station app.
Refer to your Z-Wave hub controller instructions manual to find how to associate both devices. On some Z-Wave hub controllers, an app may be used to provide the outdoor temperature.

```

## The hope
Is it possible to code something like this using zwavejs/zwavejs2mqtt ? I'm not afraid to code it (I did the exact same feature for the zigbee version of this thermostat on the Zigbee2Mqtt project).

I'll need some guidance...

**Comment by robertsLando** [comment]
@carldebilly I don't get this, did you tried to see if it works? What error do you see? Is zwavejs2mqtt creating a climate?

**Comment by carldebilly** [comment]
@robertsLando I can see and operate the climate device, that's not the problem.

What I don't know how - maybe it juste missing guidance - is how to "push" the external outdoor temperature to my thermostat.

**Comment by robertsLando** [comment]
> What I don't know how - maybe it juste missing guidance - is how to "push" the external outdoor temperature to my thermostat.

You can do this from the UI control panel, or via mqtt. Check docs: https://zwave-js.github.io/zwavejs2mqtt/#/guide/mqtt

**Comment by carldebilly** [comment]
I see.. but here's what I see in the UI for this device:
## Sections
![image](https://user-images.githubusercontent.com/4174207/105518056-cb979400-5ca5-11eb-9cea-c23dd6213bd1.png)

## Thermostat Mode
In the **Thermostat Mode** I can see a `manufacturerData` field... but setting it to something doesn't seem to produce what I want (nothing appears on the device by setting a temperature like 10.5)
![image](https://user-images.githubusercontent.com/4174207/105518424-48c30900-5ca6-11eb-995f-54e43bc3e3c1.png)

How can I know which field to use and the format of the data to send?

**Comment by robertsLando** [comment]
@carldebilly If your goal is to set the setpoint you should use the thermostat setpoint CC. ANyway when you say "How can I know which field to use and the format of the data to send" do you mean the MQTT format? If so follow docs: https://zwave-js.github.io/zwavejs2mqtt/#/guide/mqtt

**Comment by carldebilly** [comment]
@robertsLando I think I wasn't clear enough. I don't want to operate the thermostat - this already works well, that's not the problem.
![image](https://user-images.githubusercontent.com/4174207/105606491-c438bf00-5d67-11eb-9751-6f6419f26633.png)

What I want, is to PUSH the outdoor temperature (EXT) to the thermostat. As I described in previously, there's a manufacturer endpoint for that and I want to know how I can use zwavejs2mqtt to push that information for display on the thermostat. That's not the thermostat setpoint.

**Comment by robertsLando** [comment]
@carldebilly Do you see the configuration CC? If not Ithink that device hasn't a valid configuration in the database, could you print here here the device Id?

**Comment by carldebilly** [comment]
@robertsLando I'm not sure if that's what you want...  here's an export of the json for that device...
![image](https://user-images.githubusercontent.com/4174207/105607529-39f35980-5d6d-11eb-8d0b-a8f40d489c25.png)

`569-1-1 (0x0239-0x0001-0x0001)`

[node_4.zip](https://github.com/zwave-js/zwavejs2mqtt/files/5860519/node_4.zip)
