### ISSUE TITLE
Fibaro Roller Shutter 3 keep being added with no security

### ISSUE THREAD

**Issue by graphicsxp** [zwave-js/zwavejs2mqtt#2281]
This device supports S2 security. Whenever i include it, I choose the default mode (I also check Force Security), but it is added with no security

![image](https://user-images.githubusercontent.com/4160415/154810123-edabb588-f1aa-42e9-8cc1-b80f87a94bb1.png)

I excluded/included the device several times, restarted, factory reset my zwave controller. With no luck. Could this problem come from the zwavejs2mqtt add-on ?   (I'm on home assistant).

**Comment by robertsLando** [comment]
@graphicsxp Did you added all security keys in settings? Also be sure to put your device in secure inclusion mode, I know some devices have different ways to put it in normal and in secure inclusion. 

cc @blhoward2

**Comment by graphicsxp** [comment]
Yes I have filled all 4 security keys.

You are correct. On the Fibaro there is a QR code so I have tried using the inclusion option'Scan QR Code'. However I immedialely get an error 👍 
` ZWAVE: The controller does not support the SmartStart feature (ZW0207) provisionSmartStartNode undefined` 

My controller is a Aeotec Gen5 stick which does support SmartStart , strange ...

**Comment by robertsLando** [comment]
> My controller is a Aeotec Gen5 stick

It depends on the firmware it is running, only latest firmware supports SmartStart

**Comment by graphicsxp** [comment]
As displayed in my screenshot, the firmware version is 1.1  so it should be good. (unless there is a display bug and it is in fact 1.01, because I could not find 1.1 in the release notes). However 1.02 does not seem to bring support for SmartStart. There is no mention of that in the changelog : https://help.aeotec.com/support/solutions/articles/6000252294-z-stick-gen5-v1-02-firmware-update

**Comment by robertsLando** [comment]
@AlCalzone ?

**Comment by AlCalzone** [comment]
1.1 does NOT support smart start. 1.2 upgrades the Z-Wave SDK used in the firmware to a version that does, so you'll have to upgrade to use it.

This makes sense either way since 1.2 also changes the memory layout to a format which zwave-js is able to convert, should you choose to upgrade to a 700 series stick in the future.

**Comment by AlCalzone** [comment]
Anyways, if the device still fails to include with S2, I'm going to need to see driver logs of that. Note that they will include your network keys, so you might want to send them via e-mail or encrypted.

**Comment by graphicsxp** [comment]
That has worked just fine indeed :)   I upgraded the firmware of my controller to 1.2 (although the constructor mentions 1.02) and did a S2 scan inclusion of my Fibaro.
