### ISSUE TITLE
[Bug]: Cannot run latest container image.

### ISSUE THREAD

**Issue by jheddings** [zwave-js/zwavejs2mqtt#2283]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Zwavejs2Mqtt version

zwavejs/zwavejs2mqtt - 6bcae2030e1b   3 days ago

### ZwaveJS version

Unknown (cannot run container)

### Describe the bug

While attempting to run the latest Docker container, the following error occurs 100% of the time:

```
standard_init_linux.go:228: exec user process caused: no such file or directory
```

### To Reproduce

```
docker run --rm -it --publish 8091:8091 --publish 3000:3000  --device "/dev/ttyACM0:/dev/zwave"  --volume "/home/edwin/hass/config/zwavejs:/usr/src/app/store" "zwavejs/zwavejs2mqtt:latest"
```

The command fails every time immediately.  No further logging or output.

### Expected behavior

Expected container to run the service.

### Additional context

Environment:
- Raspberry Pi 4
- Debian GNU/Linux 11 (bullseye)
- Docker version 20.10.12

**Comment by robertsLando** [comment]
@jheddings Does running an older image works?

**Comment by jheddings** [comment]
Yeah, all previous images fail.  I believe this is due to the latest Bullseye image (using aarch64).  I’ve started poking around to get familiar with multi-arch container images, but it’s new territory for me :)

-jh

**Comment by jheddings** [comment]
For what it’s worth, I’m able to run latest by specifying the architecture: `--platform linux/arm/v7

**Comment by robertsLando** [comment]
Sorry for the delay.

I think your issue is due to the image you are using like you said, unfortunately I have no time to dig into dis, if specify armv7 platform fixes the issue use that for now

**Comment by jheddings** [comment]
No problem!  It has been working well with the `--platform` option.  If I get some time, I'll try to see if I can make an image for that arch and submit a PR.
