### ISSUE TITLE
[Bug]: Thermostat Mode CC not published under 'home assistant' tab or to MQTT discovery

### ISSUE THREAD

**Issue by jefft4** [zwave-js/zwavejs2mqtt#2298]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Snap

### Zwavejs2Mqtt version

Snap 6.4.1 rev329

### ZwaveJS version

Snap 6.4.1 rev329

### Describe the bug

My thermostatic radiator valves (Eurotronic Spirit) show the 'thermostat mode' command class in the zwjs control panel, but not in the 'home assistant' tab and nothing is published to MQTT to create a device for the mode during discovery.  This means that I have no device in my control system (domoticz) with which to set the mode.

Also - is it possible to override, via the device config file, the valid values for the mode?  I'm having difficulty with one valve in my set, that doesn't report 31/custom as an available mode (the others all do!).

### To Reproduce

Add TRV to zwjs, look at control panel & MQTT discovery messages.

### Expected behavior

There should be a switch, numeric value or other multi-state device created in discovery for the thermostat mode.

**Comment by jefft4** [comment]
<img width="1009" alt="image" src="https://user-images.githubusercontent.com/14252625/156930456-63c4f71c-a3f4-4ca5-8aa0-e44cbb8176dd.png">

**Comment by robertsLando** [comment]
thermostat mode is handeld in climate component
