### ISSUE TITLE
[feat] - pass the "transition duration" parameter to a dimmer device, especially (only ?) the Qubino mini Dimmer (ZMNHHD)

### ISSUE THREAD

**Issue by rezzalex** [zwave-js/zwavejs2mqtt#2305]
**Is your feature request related to a problem? Please describe.**
Problem described here : https://github.com/zwave-js/zwavejs2mqtt/issues/2226#issuecomment-1061792076

**Describe the solution you'd like**
A "native" integration via MQTT protocol will allow HA or Domoticz to natively integrated this parameter, allowing the dimming duration, when activated from a domotic gateway, to be decorrelated from the parameter [66] - Dimming Duration (physical switch Held)

**Describe alternatives you've considered**

**Additional context**

**Comment by robertsLando** [comment]
You can set options that will be passed to the setVlaue call by specify `options` in the JSON payload sent via mqtt
