### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by jjarokergc** [zwave-js/zwavejs2mqtt#2308]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Manually built (git clone - yarn build - yarn install

### Zwavejs2Mqtt version

Version: 6.5.2.c8e6d1a

### ZwaveJS version

Version: 6.5.2.c8e6d1a

### Describe the bug

I would like to disable HTTPS and access the control panel over port 80 (on my local LAN).  The `HTTPS` environment variable in the `.env.app` does not appear to have any effect.  The port can be changed to 80.  I am able to access the control panel over port 80 using HTTPS protocol (which is undesirable): `Listening on port 80 host 0.0.0.0 protocol HTTPS`

How can I disable https?

Configuration:
```bash
root@zwave1:/opt/zwave_v6.5.2# cat .env.app
#
# File Managed by Puppet
#

# The host address to bind to. Default is `0.0.0.0`
HOST="0.0.0.0"
# The port to listen to for incoming requests. Default is `8091`
PORT="80"
# The absolute path to the directory where all files will be stored. Default is `<path to your z2m dir>/store`
STORE_DIR="/etc/zwave"
# Used as secret for session. If not provided the default one is used
# SESSION_SECRET


# NETWORK_KEY
HTTPS=false
# Set the cookie [secure](https://github.com/expressjs/session#cookiesecure) option.
# USE_SECURE_COOKIE
# Mostly needed for docker users.
# https://zwave-js.github.io/node-zwave-js/#/usage/external-config?id=specifying-an-external-config-db-location
# ZWAVEJS_EXTERNAL_CONFIG
```
Running:
```bash
root@zwave1:/opt/zwave_v6.5.2# node server/bin/www.js 
2022-03-10 23:37:16.938 INFO APP: Version: 6.5.2.c8e6d1a
2022-03-10 23:37:16.945 INFO APP: Application path:/opt/zwave_v6.5.2

 ______                       _     ___                  _   _   
|___  /                      (_)   |__ \                | | | |  
   / /_      ____ ___   _____ _ ___   ) |_ __ ___   __ _| |_| |_ 
  / /\ \ /\ / / _` \ \ / / _ \ / __| / /| '_ ` _ \ / _` | __| __|
 / /__\ V  V / (_| |\ V /  __/ \__ \/ /_| | | | | | (_| | |_| |_ 
/_____|\_/\_/ \__,_| \_/ \___| |___/____|_| |_| |_|\__, |\__|\__|
                            _/ |                      | |        
                           |__/                       |_|        

2022-03-10 23:37:16.990 WARN STORE: scenes.json not found
2022-03-10 23:37:17.057 INFO APP: HTTPS is enabled. Loading cert and keys
2022-03-10 23:37:17.099 INFO APP: Listening on port 80 host 0.0.0.0 protocol HTTPS
2022-03-10 23:37:17.171 INFO MQTT: MQTT is disabled
2022-03-10 23:37:17.192 INFO ZWAVE: Connecting to /dev/serial/by-id/usb-0658_0200-if00
Logging to file:
        /etc/zwave/zwavejs_2022-03-10.log
2022-03-10 23:37:19.414 INFO ZWAVE: Zwave driver is ready
2022-03-10 23:37:19.416 INFO ZWAVE: Controller status: Driver ready
2022-03-10 23:37:19.446 DEBUG ZWAVE: Binding to node 1 events
```

### To Reproduce

Set `HTTPS` environment variable to `false` in any of the following ways:

- through .env.app file using `HTTPS=false` 
- within Bash using `HTTPS=false` and `export HTTPS`

### Expected behavior

Port 80 access to Control Panel should be over HTTP (not "s")

**Comment by robertsLando** [comment]
@jjarokergc Tried to just do not set HTTPS var at all?

**Comment by jjarokergc** [comment]
@robertsLando Thank you, that worked.
