### ISSUE TITLE
[feat] Send multicast when triggering multiple devices

### ISSUE THREAD

**Issue by oeiber** [zwave-js/zwavejs2mqtt#2320]
I have multiple cover groups in home assistant. The largest one includs 22 (all covers). Everytime the large groups where triggered, the response times are very slow. Is it possible to send multicast messages to the devices automatically, if zwavejs2mqtt detects the same command to multiple devices? Another solution for my opinion where, that multicast device groups can be defined in zwavejs2mqtt directly and then be exposed to homeassistant or mqtt.

**Comment by robertsLando** [comment]
You already could do this using mqtt multicast command. You could create a custom button in hass that sends that specific mqtt command when it's clicked.

**Comment by oeiber** [comment]
Ok. At the moment I'm using HAS's ZwaveJS integration with only websocket enabled in ZwaveJs2Mqtt. Can I use both simultaniously?
At the other side there's a lot of programming nessecary for each cover group I'm using. That means I have to create an action for each command (up, down, stop, set position). Additionaly I have to ensure current state of each group member and bring the information back to my "dummy cover".

**Comment by robertsLando** [comment]
> Ok. At the moment I'm using HAS's ZwaveJS integration with only websocket enabled in ZwaveJs2Mqtt. Can I use both simultaniously?

Sure! Zwavejs2mqtt can be used both as mqtt gateway and also, if you enable zwavejs server setting it can send values to the home assistant integration. Hass integration comes with zwavejs server pre-installed so can also work stand alone

>  Additionaly I have to ensure current state of each group member and bring the information back to my "dummy cover".

Unfortunately I don't think there are other solutions for this I'm sorry :(
