### ISSUE TITLE
Including a node tells me the security class twice

### ISSUE THREAD

**Issue by AlCalzone** [zwave-js/zwavejs2mqtt#2321]
First in a popup (which also says "undefined" for insecure nodes):
![grafik](https://user-images.githubusercontent.com/17641229/158477792-589a8767-e23c-4818-8979-247520447299.png)

And then in the dialog behind that (which says "None" for insecure nodes):
![grafik](https://user-images.githubusercontent.com/17641229/158477845-0dd2b7cf-390f-41da-876b-e1d2f5a4b902.png)

Seems a bit redundant (and inconsistent).

**Comment by robertsLando** [comment]
@AlCalzone This is because a user could close the dialog and in that case he will not receive this feedback. Would it be better if the dialog is shown only if the Nodes Manager dialog is not opened?

**Comment by AlCalzone** [comment]
Yeah.
