### ISSUE TITLE
[Bug]: Group Associations won't take

### ISSUE THREAD

**Issue by Snuffy2** [zwave-js/zwavejs2mqtt#2332]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Zwavejs2Mqtt version

6.6.0

### ZwaveJS version

8.11.9

### Describe the bug

I'm having trouble getting Group Associations to take. Using Zwavejs2mqtt through Home Assistant, but since this is solely about Group Associations, I don't believe it has anything to do with Home Assistant.

Z-wave Stick: Zooz ZST10 v2.3

Node 162: Fibaro FGMS-001 v3.3
Node 115: Inovelli Red Series Switch LZW30-SN v1.21 [Master Bedroom Closet - xxx]

I go into Zwavejs2mqtt and under the Motion Sensor Node 162, I setup a Group Association with Group 1 - Motion Sensor Status (I have also tried with Group 4 - Motion BC which also didn't work). When I click Add it says it was successful. I then wake up the Motion Sensor and the debug logs report success. However, when I refresh the Group Association List, the new association isn't there. The association also doesn't work. 

I've tried multiple times and tried restarting, rebooting, etc. without success. How can I further troubleshoot?

### To Reproduce

Before:
![2022-03-23_18-44-41 292](https://user-images.githubusercontent.com/6526076/159811392-2484c60f-03ee-4e03-9a1b-c1817adf1584.png)

![2022-03-23_19-08-40](https://user-images.githubusercontent.com/6526076/159811418-f3e6f859-2350-4525-8df7-5ac67d3e5c29.png)

![2022-03-23_19-08-40 (1)](https://user-images.githubusercontent.com/6526076/159811440-077ede70-0153-4529-a14c-3000d2c14b70.png)

Logs:
[debug.log](https://github.com/zwave-js/zwavejs2mqtt/files/8337213/debug.log)
[zwavejs.log](https://github.com/zwave-js/zwavejs2mqtt/files/8337214/zwavejs.log)

### Expected behavior

Group Associations to work.

**Comment by jmgiaever** [comment]
Can you try to re-interview the device?

**Comment by Snuffy2** [comment]
Yep, I've tried to reinterview and have excluded and readded the motion sensor without change. 

I just attempted to reinterview again and reapply the association. It still doesn't work unfortunately.

**Comment by jmgiaever** [comment]
Ok, I guess this is something for @AlCalzone

**Comment by AlCalzone** [comment]
If the motion sensor is battery powered, it needs to be woken up for the changes to take effect.

**Comment by jmgiaever** [comment]
As I understand from his initial post, he wakes it up and it's confirmed by the log.

**Comment by AlCalzone** [comment]
Then it might depend on the device, whether it accepts any more associations in the corresponding group. The manual should mention this.

**Comment by Snuffy2** [comment]
The full manual link is here: https://manuals.fibaro.com/motion-sensor/

But, from the snippet below, it sounds like it supports 5 devices per Group:
> The Motion Sensor in 2nd to 5th group allows to control 5 regular and 5 multichannel devices per an association group, with the exception of “LifeLine” that is reserved solely for the controller and hence only 1 node can be assigned.
It is not recommended to associate more than 10 devices in general, as the response time to control commands depends on the number of associated devices. In extreme cases, system response may be delayed.

**Comment by kpine** [comment]
What security class is the switch included with? The LZW30-SN supports S2, so with the default inclusion strategy it would be have been included with some level of S2 security. The sensor is included with no security, so it can only control other devices without security.

The LZW30-SN is not a multichannel device, but you are trying to set the association to endpoint 0. Does this matter (I don't know)? Is there a difference if you choose "No endpoint" instead for the target?

**Comment by AlCalzone** [comment]
I'm not sure which attempt was captured in the log above:
```
2022-03-23T22:46:17.912Z DRIVER » [Node 162] [REQ] [SendData]
                                  │ transmit options: 0x25
                                  │ callback id:      98
                                  └─[MultiChannelAssociationCCSet]
                                      group id:  1
                                      node ids:
                                      endpoints: 115:0
...
2022-03-23T22:46:17.970Z DRIVER » [Node 162] [REQ] [SendData]
                                  │ transmit options: 0x25
                                  │ callback id:      99
                                  └─[MultiChannelAssociationCCGet]
                                      group id: 1
...
2022-03-23T22:46:18.027Z DRIVER « [Node 162] [REQ] [ApplicationCommand]
                                  └─[MultiChannelAssociationCCReport]
                                      group id:           1
                                      maximum # of nodes: 1
                                      node ids:           1
                                      endpoints:
```
But in this case, the group 1 is already full and doesn't accept any more associations. Seeing more logs of the other attempts could help narrow this down.

@kpine The target node shouldn't affect this, unless the driver errors when trying to set an impossible association (don't remember if it does).

**Comment by kpine** [comment]
I think the problem here is that there are multiple versions of the FGMS device with different association groups. The Z-Wave JS device entry is for the old version.

**Comment by Snuffy2** [comment]
@kpine testing further the names of the groups in zwavejs2mqtt does differ from the manual. I was able to associate with groups 2 & 3 only. These are labelled as Tamper Alarm and Controller Updates in zwavejs2mqtt. It would not let me set an association with groups 1, 4 or 5.  Even though the name of the groups in zwavejs2mqtt differs from what is listed in the manual for firmware 3.2-3.3, it still seems like I should be able to set an association for groups 2-5, but it did not work for 4 or 5.

Also per the suggestion of @kpine, I did re-pair my light with no security. It was initially paired with S2. 

I'm not sure what to expect, but after setting those associations of groups 2 & 3, the motion sensor still did not trigger the light. I did also try changing Parameter 18 to from 15 to 0 so to not send as secure, but the motion sensor still didn't trigger the light.

![2022-03-25_17-55-00 (1)](https://user-images.githubusercontent.com/6526076/160488645-4cbd63da-270b-4071-8522-4b027f5888a8.png)

![2022-03-25_17-33-06 626](https://user-images.githubusercontent.com/6526076/160489602-91bb806e-36b2-4ed8-ad40-16e1a4c1cbba.png)

Logs of trying to associate groups 1-5. Motion sensor is Node 162 and Light is Node 163:
[zwavejs_2022-03-25.log](https://github.com/zwave-js/zwavejs2mqtt/files/8366387/zwavejs_2022-03-25.log)
[debug2.log](https://github.com/zwave-js/zwavejs2mqtt/files/8366388/debug2.log)

**Comment by AlCalzone** [comment]
> the names of the groups in zwavejs2mqtt does differ from the manual

This seems like there are multiple revisions (or differences in the firmware versions of the same device). We likely need to split the device files by version range to model the different association groups.

**Comment by AlCalzone** [comment]
I've raised https://github.com/zwave-js/node-zwave-js/issues/4410 to track that part - if anyone wants to help out, it would be appreciated.

**Comment by AlCalzone** [comment]
@Snuffy2 you've set the associations to endpoint 0 of the light, which means Multi Channel Associations are used. Not sure if the light understands those, try using Endpoint "None" which results in "normal" Associations.

**Comment by Snuffy2** [comment]
I tried to set the endpoint to None/Blank and this did not work either. At this point, I've given up on using the Fibaro FGMS-001 with associations and have repurposed it for a task not needing them. Instead I'm using a Zooz ZSE18 successfully with associations.

**Comment by AlCalzone** [comment]
Should we close here then?

**Comment by Snuffy2** [comment]
Ok with me. Will close. Thanks.
