### ISSUE TITLE
Dark Mode doesn't load on refresh. 

### ISSUE THREAD

**Issue by hessercan** [zwave-js/zwavejs2mqtt#2334]
You have to reload the settings tab everytime you refresh the page or it defaults to Light. The Dark Mode Toggle was removed from the menu and moved to the Settings Page. Now it doesn't call the function unless the settings page is loaded.

**Comment by robertsLando** [comment]
Version?  Thsi should be fixed in 6.6.1

**Comment by hessercan** [comment]
Um, I just updated the app today. It says version 0.37.0

**Comment by robertsLando** [comment]
Check on top right info icon the version shown there

**Comment by hessercan** [comment]
6.6.0

**Comment by robertsLando** [comment]
OK just wait for next release so :)

**Comment by deftdawg** [comment]
Have same issue (on the same version), dark mode is only applied when I click on the settings tab.   Glad to hear a fix is on the way.

**Comment by robertsLando** [comment]
6.7.0
