### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by reubenbijl** [zwave-js/zwavejs2mqtt#2338]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Manually built (git clone - yarn build - yarn install

### Zwavejs2Mqtt version

6.6.1 (jwave-js-9 branch)

### ZwaveJS version

9.0.0-beta.9

### Describe the bug

Startup fails:

19:15:30.775 DRIVER   driver ready
19:15:30.775 DRIVER   Checking for configuration updates...
19:15:30.778 DRIVER   Failed to initialize the driver: TypeError: zwaveNode.isControllerNode is not a function

[Zwave-beta.log](https://github.com/zwave-js/zwavejs2mqtt/files/8354842/Zwave-beta.log)

### To Reproduce

Checkout zwavejs2mqtt beta branch.
install dependencies
run zwavejs2mqtt

(environment macOS, node 16.4.2)

### Expected behavior

Expected to continue running

**Comment by robertsLando** [comment]
> Manually built (git clone - yarn build - yarn install

Did you forgot to run `yarn install` after switching to the branch? :)

**Comment by reubenbijl** [comment]
Ah yarn install, but not build, 🤦 , thanks for responding!
