### ISSUE TITLE
[feat] Entity that can return zwave device metadata

### ISSUE THREAD

**Issue by mmiller7** [zwave-js/zwavejs2mqtt#2339]
**Is your feature request related to a problem? Please describe.**
The old Home Assistant zwave provided a high level entity with overall status and metadata about the device with the "zwave.whatever" entities and associated attributes.

**Describe the solution you'd like**
I would like to see an entity or similar that passes thru the metadata about the named zwave device.
Example:
```
Entity: zwave.dining_room_gate_sensor
state: sleeping

Attributes:
node_id: 3
node_name: Ecolink Door/Window Sensor
manufacturer_name: Ecolink
product_name: Door/Window Sensor
query_stage: Complete
is_awake: false
is_ready: true
is_failed: false
is_info_received: true
max_baud_rate: 40000
is_zwave_plus: true
capabilities: beaming, zwave_plus, routing
(etc, you get the idea)
```

**Describe alternatives you've considered**
I am not able to locate any way to reference the metadata about a zwave device in templates, automatons, etc.

**Additional context**
Example usecases:

To make service calls, you sometimes need to reference the zwave device numerical ID.  It is good practice for code maintainability to not hard-code values.  When needed, this could be leveraged to put a template `{{ state_attr('zwave.dining_room_gate_sensor','node_id') }}` instead of hard-coded `3` everywhere

Also sometimes you want to be notified about abnormal conditions, it would be useful to be able to know for example if a device has been "not ready" or "not awake" for X time and get a notification to check on it, or if it shows "is_failed" to true as another example.  The metadata could be passed into an automation trigger that would make this possible.

I'm sure I could go on with many more examples, but at this time it seems there's no way to regain access to this type of metadata in a template/automation/dashboard.  I would like to see some kind of entity (even if its just exposed as a sensor with attributes) offered to leverage.

**Comment by robertsLando** [comment]
@mmiller7 If you are using zwavejs2mqtt paired with hass integration you should ask this question on hass core package. I have no control over what hass does
