### ISSUE TITLE
[Bug]: Unpowered/all devices show as having been active recently after a restart

### ISSUE THREAD

**Issue by TinkerWorX** [zwave-js/zwavejs2mqtt#2341]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Zwavejs2Mqtt version

6.5.2

### ZwaveJS version

8.11.6

### Describe the bug

Upon rebooting, all nodes in my zwave network get their "Last Active" time updated, even devices that are offline.

![image](https://user-images.githubusercontent.com/1730988/161281667-ed879b53-c22c-4024-ba50-0976e9973736.png)

Note the unnamed Smoke Detector that has no power, and has been without a battery for a few weeks at least.

### To Reproduce

Happens when I reboot my server.

Here is the same image as above, but after a restart.

![image](https://user-images.githubusercontent.com/1730988/161282244-d93d69d2-649f-41e6-aac6-614e48272510.png)

### Expected behavior

Only devices having activity should show up as active.

### Additional context

I was pointed here by @AlCalzone 
> zwavejs2mqtt reads all cached values on startup. I don't think it should consider that as the "last active" date - can you open an issue in the zwavejs2mqtt repo for this?

**Comment by robertsLando** [comment]
@AlCalzone Do I remember it correctly there should be an open issue on zwavejs to store last active and last update time on nodes and values? I mean on nodes cache?

**Comment by AlCalzone** [comment]
There is. But I still think reading potentially stale values from a cache should not mark the nodes as active.

**Comment by thecobra666** [comment]
> There is. But I still think reading potentially stale values from a cache should not mark the nodes as active, even without that feature.

They should display the last active time stamp and set the node status as waiting for update (example) after a restart of zwave. Then the user knows 2 things: 1 the last time the device was active and that it has not yet reported in after the restart.
