### ISSUE TITLE
[feat] Add interviewCC to the list of allowed APIs to call

### ISSUE THREAD

**Issue by stridger** [zwave-js/zwavejs2mqtt#2348]
**Is your feature request related to a problem? Please describe.**

I was trying to set the time on some thermostats, and as zwaveJS currently has an issue which does not allow setting the time for the Time Parameters CC (0x8b), I was hoping to do this via the interviewCC API which does a targeted interview of just one CC. That however seems to be excluded from the list of allowed API commands in ZwaveClient.ts. I thus have to call the "refreshInfo" API command which generates a lot more (unnecessary) traffic. So unless there is a reason the interviewCC command is excluded, perhaps it could just be added to the list? It does seem that exposing this API command would be useful more generally as well.

**Describe the solution you'd like**
Add interviewCC to the list of allowed API commands in lib/ZwaveClient.ts.

**Describe alternatives you've considered**
I have tried setting the time in many different ways, but the 0x8b Time Parameters command class is not implemented correctly for this and the only way to set the time is via the interview command. However it does seem that exposing this API command would be useful more generally as well.

**Comment by robertsLando** [comment]
@stridger Did you try with a driverFunction?

**Comment by stridger** [comment]
Thank you, that was exactly what was needed and @AlCalzone even provided the right syntax for me on https://github.com/zwave-js/node-zwave-js/issues/4265 (after I spent a couple of hours not being able to get it right :-( ).

Thanks for all your help with this!

**Comment by robertsLando** [comment]
You welcome :)
