### ISSUE TITLE
[Bug] Missing git

### ISSUE THREAD

**Issue by uberDoward** [zwave-js/zwavejs2mqtt#2352]
Updated to the latest container yesterday, and it's exiting with "/bin/sh: git not found"

Is git missing in the latest container?

**Comment by matjoker** [comment]
Same issue on my side

**Comment by robertsLando** [comment]
Git was never installed in docker containers. It's just used to retrive the commit sha to attach to the version

**Comment by matjoker** [comment]
Hi, thanks for your answer. So the issue is different as it doesn't start since the upgrade

**Comment by robertsLando** [comment]
@matjoker The issue should be solved, see https://github.com/zwave-js/zwavejs2mqtt/issues/2349

TLDR: try using `master` tag and let me know
