### ISSUE TITLE
[Bug]: Can't Use Duration when  setting brightness on lights any more

### ISSUE THREAD

**Issue by Botched1** [zwave-js/zwavejs2mqtt#2366]
### Checklist

- [ ]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Zwavejs2Mqtt version

6.7.0

### ZwaveJS version

9.0.1

### Describe the bug

I used to use the transition parameter in home assistant to specify the duration a light should change brightness over.

Not the transition parameter does nothing, and the light immediately goes to the new brightness (basically equivalent of duration=0).

This sued to work perfectly, but has been broken for a while - I'm just now getting around to reporting it.

### To Reproduce

Try to use a duration value when changing a light brightness. Either in an automation or node-red.

### Expected behavior

Should use pass the transition value as duration to the zwave device.

**Comment by Botched1** [comment]
More info..

From the z2m web interface, if I try to send a duration to a multilevel switch, I get this error:

![image](https://user-images.githubusercontent.com/19985320/162845793-542c33da-6909-4a2b-8510-7c82652583e3.png)

![image](https://user-images.githubusercontent.com/19985320/162845764-14c2bde3-0013-4a07-a027-692793abd243.png)

```
2022-04-11 17:49:45.709 INFO ZWAVE: Calling api writeValue with args: [
{ nodeId: 81, commandClass: 38, endpoint: 0, property: 'duration' },
{ unit: 'seconds', value: 20 },
{},
[length]: 3
]
2022-04-11 17:49:45.710 INFO ZWAVE: Writing { unit: 'seconds', value: 20 } to 81-38-0-duration
2022-04-11 17:49:45.710 ERROR ZWAVE: Unable to write { unit: 'seconds', value: 20 } on 81-38-0-duration
2022-04-11 17:49:45.711 INFO ZWAVE: Success zwave api call writeValue false
```

**Comment by Botched1** [comment]
And here is what it looks like if I do it form node-red... It LOOKS like it is sending a duration, but as you can see in the log the light is changing immediately. Maybe a zwavejs layer issue? @AlCalzone ?

```
2022-04-12T00:04:26.063Z SERIAL » 0x010f00a901510326011925000000000514 (17 bytes)
2022-04-12T00:04:26.065Z DRIVER » [Node 081] [REQ] [SendDataBridge]
│ source node id: 1
│ transmit options: 0x25
│ callback id: 5
└─[MultilevelSwitchCCSet]
target value: 25
duration: 5m
2022-04-12T00:04:26.072Z SERIAL « [ACK] (0x06)
2022-04-12T00:04:26.075Z SERIAL « 0x010401a90152 (6 bytes)
2022-04-12T00:04:26.077Z SERIAL » [ACK] (0x06)
2022-04-12T00:04:26.079Z DRIVER « [RES] [SendDataBridge]
was sent: true
2022-04-12T00:04:26.088Z SERIAL « 0x011d00a90500000100c37f7f7f7f00000300000000030100007f7f7f7f7ff2 (31 bytes)
2022-04-12T00:04:26.091Z SERIAL » [ACK] (0x06)
2022-04-12T00:04:26.093Z DRIVER « [REQ] [SendDataBridge]
callback id: 5
transmit status: OK, took 10 ms
routing attempts: 1
protocol & route speed: Z-Wave, 100 kbit/s
ACK RSSI: -61 dBm
ACK channel no.: 0
TX channel no.: 0
2022-04-12T00:04:26.105Z CNTRLR [Node 081] [~] [Multilevel Switch] currentValue: 99 => 25 [Endpoint 0]
2022-04-11 19:04:26.106 INFO ZWAVE: Node 81: value updated: 38-0-currentValue 99 => 25
2022-04-11 19:04:26.109 INFO ZWAVE: Node 81: value updated: 38-0-targetValue 99 => 25
```

**Comment by AlCalzone** [comment]
> Unable to write { unit: 'seconds', value: 20 } on 81-38-0-duration

Is there any error message from the driver? This looks like it didn't accept the value you sent.
Nonetheless, I wonder how setting the duration value could ever work in z2m. The `setValue` function doesn't have any implementation for the duration value, and it was last changed 9 months ago.

The node-red node most likely uses the `transitionDuration` `setValue` option, which is what these settings are meant for:
![grafik](https://user-images.githubusercontent.com/17641229/162916962-f34c1f05-19bb-452a-96e5-b06bac3d6308.png)
I'm not sure what z2m does with them though, @robertsLando?

---

This
```
2022-04-12T00:04:26.063Z SERIAL » 0x010f00a901510326011925000000000514 (17 bytes)
2022-04-12T00:04:26.065Z DRIVER » [Node 081] [REQ] [SendDataBridge]
│ source node id: 1
│ transmit options: 0x25
│ callback id: 5
└─[MultilevelSwitchCCSet]
target value: 25
duration: 5m
```
looks like a duration was passed, but it doesn't end up in the serialized data. I think I know why - the CC version shows `0`, i.e. unknown, but the duration is only used for V2 and above.

Try re-interviewing the node.

**Comment by Botched1** [comment]
Thanks all for the consideration. I did re-interview it, and it came back with the correct command classes:
![image](https://user-images.githubusercontent.com/19985320/162967968-4366ace0-bd0c-4671-89ab-d6dbe8b2484e.png)

I'm at work, so I'll try the fade again when I get home. I did try it from work, and the logs look the same as before, but as I can't actually see the light I don't want to say it is/is not working yet.

**Comment by AlCalzone** [comment]
The devil is in the details:
```
2022-04-12T13:01:19.416Z SERIAL » 0x011000a90151042601598425000000005a97 (18 bytes)
                                                        ^^--- Transition duration 5m
```
This wasn't there before.

**Comment by Botched1** [comment]
> This wasn't there before.

Ah.... Good eye!

Looking, I have a lot of devices with weird command classes listed. I'm sure it happened in the process of me switching back and forth between 500 and 700 controllers, across various software versions. I'll go re-interview them.

So, assuming the lights are really fading now (I'll verify this afternoon), I'll close this out.

**Comment by Botched1** [comment]
> I think I know why - the CC version shows `0`

That was the issue. After re-interviewing the device and getting a proper CC version, the duration value works again.

So... Once again it was not a software bug, but rather a user bug. :)

Thanks for helping me. I noticed the CC v0, but I didn't put 2 and 2 together to get to 4. I should have realized that was the issue.
