### ISSUE TITLE
[feat] IDLock 150 - report access notifications

### ISSUE THREAD

**Issue by Fr00t** [zwave-js/zwavejs2mqtt#2370]
Hi guys, I'm moving my smarthome from Homeseer to Homeassistant, and have successfully moved most of it over. I've just included my IDLock150 into Zwavejs2mqtt, but I'm missing a feature from Homeseer that I'm hoping you can add.

Their documentation is [here](https://idlock.no/wp-content/uploads/2019/08/IDLock150_ZWave_UserManual_v3.02.pdf). Notice page 12 where it reports various notification parametert depending on how the lock was last operated. This class is included in Zwavejs2mqtt, but apparently just sits "Idle".

I had a pretty significant automation hooked up to the report of "Keypad lock operation" because that was a clear signal we had left the house. Meaning I turned off all lights and such from this report. 

Thanks a lot!

**Comment by kpine** [comment]
Notifications are supported. You'll have to clarify if you are using MQTT, or are using HA's Z-Wave JS integration. Many of those are notification events, not values that you see in the control panel. For HA, those notification events like "Keypad lock operation" are HA [events](https://www.home-assistant.io/integrations/zwave_js/#node-events-notification).

**Comment by Fr00t** [comment]
> Notifications are supported. You'll have to clarify if you are using MQTT, or are using HA's Z-Wave JS integration. Many of those are notification events, not values that you see in the control panel. For HA, those notification events like "Keypad lock operation" are HA [events](https://www.home-assistant.io/integrations/zwave_js/#node-events-notification).

Thats great news! :)

I'm using the WS Server implementation. Does that also support notifications? Seems like I need to change log level to view events? Sorry for the newbish questions

**Comment by kpine** [comment]
> I'm using the WS Server implementation.

That doesn't really clarify anything. Are you using zwavejs2mqtt or not? Are you using the Z-Wave JS integration, or MQTT with HA?

**Comment by Fr00t** [comment]
> > I'm using the WS Server implementation.
> 
> That doesn't really clarify anything. Are you using zwavejs2mqtt or not? Are you using the Z-Wave JS integration (which uses the websocket), or MQTT with HA?

I'm sorry. I'm using zwavejs2mqtt in a docker container. It's not using MQTT, but the direct websocket integration with HA.

I just started listening to these events in the developer settings and can see that they fire :) It does however show as manual lock operation though, which is not correct. Keypad unlock operation doesn't seem to report at all.

RF unlock reports correctly, while RF lock still reports as "Manual lock"

**Comment by kpine** [comment]
You can use the [driver debug logs](https://zwave-js.github.io/zwavejs2mqtt/#/troubleshooting/generating-logs?id=driver-logs) in zwavejs2mqtt to see which events the device reports. HA only reports what the driver tells it about.

**Comment by Fr00t** [comment]
> You can use the [driver debug logs](https://zwave-js.github.io/zwavejs2mqtt/#/troubleshooting/generating-logs?id=driver-logs) in zwavejs2mqtt to see which events the device reports. HA only reports what the driver tells it about.

Thanks, I'll have to look into this later. Getting late here now :)

**Comment by Fr00t** [comment]
Attached the silly level logs for a quick test. I just performed the following sequence of operations.

1. manual unlock
2. autolock
3. manual unlock
4. open
5. close
6. keypad lock
7. keypad unlock
8. open
9. close
10. autolock

[zwavejs_2022-04-13.log](https://github.com/zwave-js/zwavejs2mqtt/files/8484831/zwavejs_2022-04-13.log)

**Comment by kpine** [comment]
It would be helpful if you annotate those steps with timestamps.

**Comment by Fr00t** [comment]
> It would be helpful if you annotate those steps with timestamps.

I could try. Thats almost 2.7k lines of log in 2 minutes though. All operations were run in pretty quick succession to keep the log as short as possible.

Would a different log level be better and contain enough?

**Comment by Fr00t** [comment]
So I had a sneaking feeling that something was off from my end as I remembered something similar happening under Homeseer. 

I reinstalled the firmware on the lock ("updating" from v. 1.59 to v. 1.59) and it reports correctly now. Gonna close this issue then. Thanks for your help @kpine :)

**Comment by prilly-dev** [comment]
How is your ID lock 150 zwave communication? are you having communication timeouts respons from your lock?

**Comment by Fr00t** [comment]
> How is your ID lock 150 zwave communication? are you having communication timeouts respons from your lock?

It's been very stable for me, and battery life has been solid too. Overall very pleased with the lock. The inner handle is not as firm as when I mounted it, and I fear it's gonne be losening over time though.
