### ISSUE TITLE
Will using zwavejs2mqtt over MQTT disable device resets on reboots?

### ISSUE THREAD

**Issue by pittbull** [zwave-js/zwavejs2mqtt#2377]
I haven't found anything on the topic so I would like to ask the question before I embark on a larger migration. :)

I have several devices running on zwavejs2mqtt, and integrated with HA working flawlessly - thank you so much for that! 

But one thing that annoys me is that when I reboot HA my shutters resets back to open. Now, I understand that is in the nature of zwave devices, but I wonder if I move devices fully to mqtt still using zwavejs2mqtt if that would leave my shutters closed when restarting HA? I already run mqtt for other stuff so shouldn't be much work.

Thank you kindly.

//Thomas

**Comment by robertsLando** [comment]
> but one thing that annoys me is that when I reboot HA my shutters resets back to open. 

The messages I send via mqtt is what I receive from zwave-js driver, If you see z2m sending a reset it means the device is sending a reset to driver. Do you see this in logs? Try to check logs when yopu reboot the application

**Comment by pittbull** [comment]
I started logging to file and grep'ed it whilst restarting HA and these lines came out related to the shutters. Suggesting that a shutter opening is happening. Anyway to mitigate this?

```2022-04-19 08:04:23.581 INFO ZWAVE: Node 21: value updated: 38-0-currentValue 0 => 99
2022-04-19 08:04:23.595 INFO ZWAVE: Node 21: value updated: 38-0-targetValue 0 => 99
2022-04-19 08:04:24.020 INFO ZWAVE: Node 22: value updated: 38-0-currentValue 99 => 99
2022-04-19 08:04:24.026 INFO ZWAVE: Node 22: value updated: 38-0-targetValue 99 => 99
2022-04-19 08:04:24.380 INFO ZWAVE: Node 23: value updated: 38-0-currentValue 99 => 99
2022-04-19 08:04:24.385 INFO ZWAVE: Node 23: value updated: 38-0-targetValue 99 => 99
2022-04-19 08:04:25.143 INFO ZWAVE: Node 21: value updated: 50-0-value-66049 0 => 102.4
2022-04-19 08:04:26.074 INFO ZWAVE: Node 22: value updated: 38-0-currentValue 99 => 99
2022-04-19 08:04:28.816 INFO ZWAVE: Node 21: value updated: 38-0-currentValue 99 => 17
2022-04-19 08:04:29.630 INFO ZWAVE: Node 23: value updated: 38-0-currentValue 99 => 99
2022-04-19 08:04:31.015 INFO ZWAVE: Node 23: value updated: 38-0-currentValue 99 => 99```

**Comment by robertsLando** [comment]
You could workaround this using custom send maybe but I think it would be better to find the root cause of the problem. @AlCalzone any clue?

**Comment by pittbull** [comment]
Just for the sake of clarity: I am not currently using the mqtt integration of zwavejs2mqtt.

**Comment by pittbull** [comment]
Attaching a [debug](https://pastebin.com/Bfez6gLg) log of a reboot done just now.

**Comment by AlCalzone** [comment]
Right at the start, something is setting the `targetValue` to 99, causing a command to be sent to the shutters.
```
2022-04-19T08:45:02.602Z DRIVER » [Node 021] [REQ] [SendData]
                                  │ transmit options: 0x25
                                  │ callback id:      8
                                  └─[MultilevelSwitchCCSet]
                                      target value: 99
```

Neither `node-zwave-js` nor `zwavejs2mqtt` do that on their own, this must be an automation in HA.

**Comment by pittbull** [comment]
Interesting - I have no automations in HA for this and the nodes are new, but I will for sure do a verification.

**Comment by pittbull** [comment]
Looking at the three devices in HA i have no automations, scenes or scripts using them. Any pointers on where I need to look?

**Comment by robertsLando** [comment]
@pittbull Do you have any group association?

**Comment by pittbull** [comment]
No I don't.

**Comment by robertsLando** [comment]
I dunno what could trigger that so, it's not z2m or zwavejs driver, it must be the device or another device in case it has an association with another one

**Comment by robertsLando** [comment]
> But when looking in the group section on the nodes I find this:

The lideline group is the default one that is created by the controller in order to receive updates from the device so that is not the issue

**Comment by pittbull** [comment]
But when you really start looking, you are bound to find out...

I am using nodered and I was absolutely sure I had disabled all of them, but turns out I've been neglecting to check properly.

Sorry for the inconvenience, but thank you so much for pointing me in the right direction :)
