### ISSUE TITLE
[Bug]: Missing devices in 'Devices values configuration'

### ISSUE THREAD

**Issue by stephanvierkant** [zwave-js/zwavejs2mqtt#2384]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Zwavejs2Mqtt version

6.7.3

### ZwaveJS version

9.0.3

### Describe the bug

The 'new item' dialog in 'Devices values configuration' doesn't show all my devices. It only shows every device type only once.

I've got two Greenwave Powernodes 6's and I want to pull the energy consumption data, but only one device shows up. `/api/settings` uses the device ID as a key, but the device ID isn't unique:

![Screenshot_20220421_205719](https://user-images.githubusercontent.com/601833/164535105-2e7faa9a-bc91-4179-ae56-0c0d3c3c9b95.png)

I've got 2x Greenwave Powernode 6, 2x TKB Home TZ68, 2x TKB Home TZ36D, etc. Some parts of my nodes_dump.json:

```
 {
    "id": 43,
    "name": "",
    "ready": true, 
    "available": true,
    "hassDevices": {},
    "failed": false,
    "inited": true,
    "hexId": "0x0099-0x0003-0x0004",
    "dbLink": "https://devices.zwave-js.io/?jumpTo=0x0099:0x0003:0x0004:4.21",
    "manufacturerId": 153,
    "productId": 4,
    "productType": 3,
    "deviceId": "153-4-3",
    "status": "Alive",
    "interviewStage": "Complete"
  },
  {
    "id": 51,
    "name": "Stekkerdoos",
    "loc": "Keuken",
    "productLabel": "NP240 / NP242",
    "productDescription": "Multi-socket PowerNode (6-plug)",
    "manufacturer": "GreenWave Reality Inc.",
    "firmwareVersion": "4.21",
    "protocolVersion": 3,
    "nodeType": 1,
    "deviceId": "153-4-3",
    "status": "Alive",
    "interviewStage": "Complete"
}
```

(I removed a lot of data from this example, but you'll get an idea)

### To Reproduce

Go to 'Devices values configuration' and click on New value. In my case it shows all device types I have, but not all device.

### Expected behavior

All my devices should show up.

### Additional context

I am using Home Assistant, but this problem is not related to it

**Comment by robertsLando** [comment]
> The 'new item' dialog in 'Devices values configuration' doesn't show all my devices. It only shows every device type only once.

This is what it should do, it allows you to add configurations to all devices of the same manufacturer/model in you network

**Comment by stephanvierkant** [comment]
So there is no way to add different configuration to those devices?

I've got two Powernodes and I want to pull the energy usage data from one of them.

**Comment by robertsLando** [comment]
> So there is no way to add different configuration to those devices?

Right now nope it's not possible
