### ISSUE TITLE
[question] how to add users

### ISSUE THREAD

**Issue by romleinster** [zwave-js/zwavejs2mqtt#2385]
Sorry if I missed this in the docs, but how do I add users? 

I see the store/users.json file but how do I encode the password string, what hashing algorithm do I use?

Thanks!

**Comment by robertsLando** [comment]
ATM there is no way to add multiple users, why do you need it?

**Comment by romleinster** [comment]
I wanted to increase security by enabling auth. But if the username/password is public in the docs, there's not much point to this. Is it possible to change the admin password?

**Comment by romleinster** [comment]
Ah, found the password change in the interface. That solves my issue!
