### ISSUE TITLE
[Bug]: Inclusion via QR code forgets supplied Name and Location

### ISSUE THREAD

**Issue by KevinCathcart** [zwave-js/zwavejs2mqtt#2389]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Zwavejs2Mqtt version

6.6.0

### ZwaveJS version

8.11.9

### Describe the bug

When adding a node in the UI as part of the `Actions -> Manage Nodes` flow if a SmartStart QR code, the entered Name and location are forgotten.

If I instead add the provisioning record to Smart Start screen, and then quickly edit it to add a name and location, then those are used when the device joins the network; however, there is a potential race against the device joining the network when doing it like that (unless I force the device off while adding the record, and only turn it on once I edit it to add the name and location).

This is obviously a rather minor issue, but it is convenient to have the name set correctly when a node first joins so that Home Assistant creates entities based on the desired name. (And I'm guessing some MQTT based clients would be better off that way too).

### To Reproduce

1. Click Actions -> Manage Nodes.
2. Chose Inclusion.
3. Enter a name and area for the node.
4. On the next page choose to scan a QR code.
5. Finish adding device.

### Expected behavior

The provided name and location are saved as part of the provisioning record, so that when the device joins the network, it has the name and location I typed.

### Additional context

I'd have tested this against newer versions, but I'm using the home assistant add-on, and the version that includes 6.7.2 does not work with SmartStart, due to a 9.x bug that was only fixed in 9.0.3, which is included with 6.7.3, which is not yet available as an addon.

But given the lack of anything relevant sounding in the changelog, I'm guessing this has not been addressed yet.

Based on how editing the provisioning entries appears to work, I'm pretty sure that all that is needed is to add the name and location properties to the `PlannedProvisioningEntry` before handing it off to `this.provisionSmartStartNode` here:
https://github.com/zwave-js/zwavejs2mqtt/blob/e6d17ad4f43791c7f4ccf16b9b5c2850ff13f909/lib/ZwaveClient.ts#L1904

**Comment by robertsLando** [comment]
@KevinCathcart Could you give a try to #2391 ?
