### ISSUE TITLE
[bug] propertyKeyName should be used instead of propertyKey if it exists

### ISSUE THREAD

**Issue by AlCalzone** [zwave-js/zwavejs2mqtt#239]
Found several locations where `propertyName` is used in place of `property`, but the same does not happen for `propertyKeyName`.

Also, this is completely wrong I think (`propertyName` instead of `propertyKeyName`):
https://github.com/zwave-js/zwavejs2mqtt/blob/6e2a0f726aa8f14bc06258860c002e6373697f05/lib/Gateway.js#L678

**Comment by AlCalzone** [comment]
propertyKeyName is missing completely here:
https://github.com/zwave-js/zwavejs2mqtt/blob/master/lib/ZwaveClient.js#L814

This should also append the propertyKey(Name) to uniquely identify the value:
https://github.com/zwave-js/zwavejs2mqtt/blob/master/lib/ZwaveClient.js#L819

This confuses propertyKey with property (should be the other way round):
https://github.com/zwave-js/zwavejs2mqtt/blob/master/lib/Gateway.js#L1534
and
https://github.com/zwave-js/zwavejs2mqtt/blob/6e2a0f726aa8f14bc06258860c002e6373697f05/lib/Gateway.js#L1697-L1701

This looks up the sensor type manually:
https://github.com/zwave-js/zwavejs2mqtt/blob/6e2a0f726aa8f14bc06258860c002e6373697f05/lib/Gateway.js#L1569-L1571
(I thought we added the `ccSpecific` stuff for this?)

This should probably use `property` instead of `propertyName`:
https://github.com/zwave-js/zwavejs2mqtt/blob/master/lib/ZwaveClient.js#L1036

**Comment by robertsLando** [comment]
Thanks, will look at this later

**Comment by bdbogjoe** [comment]
do you need any testing on this ?
