### ISSUE TITLE
[Home Assistant] Door/Windows sensors populated with wrong entity

### ISSUE THREAD

**Issue by Wri84** [zwave-js/zwavejs2mqtt#2392]
zwavejs2mqtt: 6.7.2
zwave-js: 9.0.2

HomeAssistant OS 7.6 on RPi4

### Describe the bug

I included several Door/Window sensors by three different hardware vendors, which are all the same hardware wise:

- D-Link DCH-Z110 
- Devolo MT02648
- Philio PST02C

These are included correctly in Zwavejs2mqtt and show up in HA as well. However, the open/close detection is not mapped correctly. HA creates entities for 

`binary_sensor.door_window_sensor_access_control_window_door_is_open`

![image](https://user-images.githubusercontent.com/66649500/165255107-5c26e602-fdf5-4b12-a768-66b7ddbc3138.png)

which reports status "Undefined" in ZWavejs2mqtt and therefore shows "Unknown" in HA. Open/closing the door doesn't change state. An entity for

`binary_sensor.door_window_sensor_door_window`

is created as well, but hidden by default in HA. This changes between true/false for open/close. Furthermore an (also hidden by default) entity for 

`sensor.door_window_sensor_access_control_door_state_2`

is created, which also switches between states.

I would expect the by default activated entity in HA to be the correct one, reporting the open/close state of the sensor. I don't know why the access control sensor is being mapped, and also why it's always undefined. 

Following is a debug example for one of the sensors
[D-Link_DCH-Z110.txt](https://github.com/zwave-js/zwavejs2mqtt/files/8561171/D-Link_DCH-Z110.txt)

**Comment by robertsLando** [comment]
Are you using hass integration? If so I cannot help you here
