### ISSUE TITLE
[Bug]: (snap) zwavejs2mqtt: [Error: EACCES: permission denied, mkdir '/usr/src/app']

### ISSUE THREAD

**Issue by LordMike** [zwave-js/zwavejs2mqtt#2398]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Snap

### Zwavejs2Mqtt version

6.7.4

### ZwaveJS version

N/A

### Describe the bug

My snap install auto-updated to the current `latest/stable` version (363 / 6.7.4), which encountered this issue. When I came to, it was on reboot 194, so it's quite persistent. A `snap revert zwavejs2mqtt` brought back 6.6.2, which starts cleanly.

```
Missing plug: «serial-port»
2022-04-28 22:50:59.099 INFO APP: Version: 6.7.4.e6d17ad
2022-04-28 22:50:59.104 INFO APP: Application path:/snap/zwavejs2mqtt/363/lib/node_modules/zwavejs2mqtt/server
 ______                       _     ___                  _   _
|___  /                      (_)   |__ \                | | | |
   / /_      ____ ___   _____ _ ___   ) |_ __ ___   __ _| |_| |_
  / /\ \ /\ / / _` \ \ / / _ \ / __| / /| '_ ` _ \ / _` | __| __|
 / /__\ V  V / (_| |\ V /  __/ \__ \/ /_| | | | | | (_| | |_| |_
/_____|\_/\_/ \__,_| \_/ \___| |___/____|_| |_| |_|\__, |\__|\__|
                            _/ |                      | |
                           |__/                       |_|
2022-04-28 22:50:59.162 WARN STORE: scenes.json not found
2022-04-28 22:50:59.227 INFO APP: Listening on port 80 host 192.168.1.3 protocol HTTP
2022-04-28 22:50:59.286 INFO MQTT: Connecting to mqtt://queue.home:1883
2022-04-28 22:50:59.380 INFO MQTT: MQTT client connected
2022-04-28 22:50:59.387 DEBUG MQTT: Subscribing to homeassistant/status with options { qos: 1 }
2022-04-28 22:50:59.392 DEBUG MQTT: Subscribing to zwavejs2mqtt/_CLIENTS/ZWAVE_GATEWAY-zwavejs2mqtt-2/broadcast/                                                                          # with options { qos: 1 }
2022-04-28 22:50:59.395 DEBUG MQTT: Subscribing to zwavejs2mqtt/_CLIENTS/ZWAVE_GATEWAY-zwavejs2mqtt-2/api/# with                                                                           options { qos: 1 }
2022-04-28 22:50:59.397 DEBUG MQTT: Subscribing to zwavejs2mqtt/_CLIENTS/ZWAVE_GATEWAY-zwavejs2mqtt-2/multicast/                                                                          # with options { qos: 1 }
[Error: EACCES: permission denied, mkdir '/usr/src/app'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/usr/src/app'
}
```

### To Reproduce

I guess installing 6.7.4 via. snap will result in this.

### Expected behavior

Start cleanly.

### Additional context

The host is a raspberry pi, the stick is a 700-series, but this seems like a packaging issue. I could not identify any commits that would result in this. I've checked [zwavejs2mqtt](https://github.com/zwave-js/zwavejs2mqtt/compare/v6.6.2..v6.7.4)

**Comment by jmgiaever** [comment]
Which OS are you using? I've been running this snap myself, until today (I'm on the `candidate` channel), without any issues. 

I'm now on 6.8.0.

**Comment by LordMike** [comment]
From googling, I think this could be something outside this project.. Other projects also encounter the path `/usr/src/app/` for their things. I was unable to locate anything specific to this path or mkdir in general, in the changes for the versions I had.

```
# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 21.10
Release:        21.10
Codename:       impish
```

**Comment by LordMike** [comment]
I can try candidate channel.

**Comment by LordMike** [comment]
So, I created the path it wanted and chmod'ed it to 777 to let it write. It then wanted more folders, until I had this: `/usr/src/app/store/config`. Then `6.8.0` happily starts up and begins loading the interface et.al.

It does not seem to write anything to the folders.

```
# find /usr/src/app/ -ls
   131781      4 drwxrwxrwx   3 root     root         4096 Apr 28 23:27 /usr/src/app/
   131939      4 drwxrwxrwx   3 root     root         4096 Apr 28 23:27 /usr/src/app/store
   134026      4 drwxrwxrwx   2 root     root         4096 Apr 28 23:27 /usr/src/app/store/config
```

**Comment by jmgiaever** [comment]
Hi,

Have you changed anything with in zwavejs2mqtt to use this directory, or did it happen automatically with version 6.7.x? 

Can you give me a dump of your `settings.json`? It should be located in `/var/snap/zwavejs2mqtt/current/settings.json`.

**Make sure** you'll remove your network keys if they are stored in the file.

**Comment by LordMike** [comment]
I noticed this update because it was automatic :P (new to snap) - so it apparently happened between v6.6.2 and v6.7.4.

I see the config has a `deviceConfigPriorityDir` which is set to `/usr/src/app/store/config` (which is also why I didn't find it - I grep'ed `/snap/zwavejs2mqtt/` for the path).. so that explains where it's coming from. I did see the use of this variable in the commits, but I imagined it was new so it didn't apply..

<details><summary>Settings.json</summary>

```json
{
    "mqtt": {
        "name": "zwavejs2mqtt-2",
        "host": "mqtt://queue.home",
        "port": 1883,
        "qos": 0,
        "prefix": "zwavejs2mqtt",
        "reconnectPeriod": 5000,
        "retain": true,
        "clean": true,
        "auth": true,
        "username": "zwavejs2mqtt",
        "password": "zwavejs2mqtt",
        "_ca": "",
        "ca": "",
        "_cert": "",
        "cert": "",
        "_key": "",
        "key": "",
        "store": true
    },
    "gateway": {
        "type": 0,
        "plugins": [],
        "authEnabled": false,
        "payloadType": 0,
        "nodeNames": true,
        "hassDiscovery": false,
        "discoveryPrefix": "homeassistant-zjs2m",
        "logEnabled": true,
        "logLevel": "debug",
        "logToFile": false,
        "values": [{
                "device": "150-1-16",
                "value": {
                    "id": "50-0-value-131073",
                    "commandClass": 50,
                    "commandClassName": "Meter",
                    "endpoint": 0,
                    "property": "value",
                    "propertyName": "value",
                    "propertyKey": 131073,
                    "propertyKeyName": "Gas_Cubic meters_Consumed",
                    "type": "number",
                    "readable": true,
                    "writeable": false,
                    "label": "Value (Gas, Consumed)",
                    "stateless": false,
                    "ccSpecific": {
                        "meterType": 2,
                        "rateType": 1,
                        "scale": 0
                    },
                    "unit": "Cubic meters",
                    "list": false,
                    "value": 536062.066,
                    "lastUpdate": 1611774934965
                },
                "enablePoll": true,
                "pollInterval": 900
            }
        ],
        "retainedDiscovery": true,
        "sendEvents": false,
        "publishNodeDetails": false,
        "ignoreLoc": true,
        "ignoreStatus": false,
        "manualDiscovery": true
    },
    "zwave": {
        "port": "/dev/ttyUSB0",
        "commandsTimeout": 60,
        "logLevel": "silly",
        "logEnabled": true,
        "securityKeys": {
            "S0_Legacy": "xx",
            "S2_Unauthenticated": "xx",
            "S2_AccessControl": "xx",
            "S2_Authenticated": "xx"
        },
        "deviceConfigPriorityDir": "/usr/src/app/store/config",
        "logToFile": true,
        "serverEnabled": false,
        "enableSoftReset": true,
        "enableStatistics": true,
        "serverPort": 3000,
        "logging": true,
        "saveConfig": true,
        "autoUpdateConfig": true,
        "pollInterval": 10000,
        "healNetwork": false,
        "refreshNodeInfo": false,
        "assumeAwake": false,
        "disclaimerVersion": 1
    }
}
```
</details>

**Comment by jmgiaever** [comment]
Hi,

That seems to be it. 

In the past Z2M didn't "ensure it exists". Guess that's why it's failing, possible on newer installs that didn't have this setting set and Z2M sets it something it finds "correct". 

I'm on revision 368, så my path is 

```
/var/snap/zwavejs2mqtt/368/config
```

The snap package will handle the revision jump (e.g from `368` to `xyz`) on each revision on the path, as long as it's within the `SNAP_DATA` directory (normally  `/var/snap/zwavejs2mqtt/REVISION/`), but I haven't taken into consideration to fix it if it's set outside of it. 

That's probably because z2m didn't "ensure it existed" and I didn't consider it critical. 

The snap has no access to write outside of the `SNAP_DATA` mount. 

I'll see how I should fix it. 😀 In the meantime you could change it to `/var/snap/zwavejs2mqtt/current/config`. 

The `current` directory is always a symlink to the revision that is running.

**Comment by jmgiaever** [comment]
https://github.com/home-assistant-snap/zwavejs2mqtt/blob/master/src/hooks/post-refresh#L15

**Comment by LordMike** [comment]
Yeap, I set it to `/var/snap/zwavejs2mqtt/current/config`, restarted - it (still) worked, changed back to stable channel, and it now works. The config was replaced with `/var/snap/zwavejs2mqtt/363/config`, as your hook describes.

All good. 👍

**Comment by LordMike** [comment]
Iirc I _did_ migrate from a different install in docker, to this, by copying the configs and settings. It's likely that the value was persisted from there. This will mean though, that you'll probably be seeing more and more users with snap installs come in, with all kinds of weird stuff there :P

Anyways - thanks for the help, it's much appreciated :)

**Comment by jmgiaever** [comment]
I guess the subdirectory (`config`) normally will be placed within the store folder (for snap `/var/snap/zwavejs2mqtt/revision/`), so I should probably just re-write this path to `SNAP_DATA/config` when it's wrong. 

Thanks for reporting it and bringing it to attention. :)

**Comment by robertsLando** [comment]
Thanks @jmgiaever :)
