### ISSUE TITLE
[question] API to trigger refresh value for a device

### ISSUE THREAD

**Issue by Scotty42** [zwave-js/zwavejs2mqtt#2416]
Hi all, 

I'm searching for a way to trigger the function behind the Advanced popup of the UI to trigger Refresh Values for a device. 
Like via some REST call. 
The idea involved is to allow some automation to call that function from outside in case values didn't seem to update for some time, so more or less a monitoring purpose. 
Pseudo `http://<ip>:<port>/api/v1/device/42/refresh`

thanks for any hints!
best, Markus

**Comment by robertsLando** [comment]
I suggest to use mqtt for that

**Comment by robertsLando** [comment]
Check https://github.com/zwave-js/zwavejs2mqtt/blob/master/src/App.vue#L722

**Comment by Scotty42** [comment]
thanks, @robertsLando, I'll try to implement a solution based of this hint.

**Comment by Scotty42** [comment]
I went with MQTT as I didn't feel an immediate euphoria to expose sockets. 
So e.g. created a JSON object:
`{
   "args": [
       36
  ]
}` and publish to:
`zwave/_CLIENTS/ZWAVE_GATEWAY-rabbitmq/api/refreshValues/set` and subscribe for responses without `/set`

Seems to achieve the API call as was to be expected.

I'll consider the question solved.
