### ISSUE TITLE
[Bug]: [ssl_client] zombies in docker container

### ISSUE THREAD

**Issue by flechaig** [zwave-js/zwavejs2mqtt#2422]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Zwavejs2Mqtt version

6.9.0

### ZwaveJS version

9.2.1

### Describe the bug

A zombie process named [ssl_client] is created once every minute:
`  692 root      0:00 [ssl_client]`

Restarting the container removes all the zombies.

### To Reproduce

Start the container
Wait 2 minutes
ps -ef

### Expected behavior

I expect no zombie process.

**Comment by robertsLando** [comment]
Hummm I have no clue. The only library I use is node-pem to create ssl certs when https is enabled but it's called only once and only if the certs are not already present. Dunno if it could be something related to docker node base image 🤔 

@chrisns any clue?

**Comment by chrisns** [comment]
Is this only observed when running in a container?

**Comment by flechaig** [comment]
Your answer make me think that I have custom healthcheck in docker-compose:
`    healthcheck:
      test: ["CMD-SHELL", "wget --server-response 'https://zwavejs2mqtt0.docker.tropicoco.ovh/' 2>&1 | egrep 'HTTP/1.1 200 OK' || exit 1"]
      interval: 1m
      timeout: 3s
      retries: 3`

The interval is 1 minute. Let me think about it.

**Comment by flechaig** [comment]
wget is causing the issue.
Sorry to have bothered you.
