### ISSUE TITLE
Aeotec Z-Stick 7 No Controller Neighbors

### ISSUE THREAD

**Issue by GitHubGoody** [zwave-js/zwavejs2mqtt#2424]
I have an Aeotec Z-Stick 7 with the latest FW 7.17.2.406 flashed and have only added 7 nodes so far to the network, which seems to be working great. All of those nodes have multiple neighbors when I hover over them, but the controller lists none. From reading past issues, I'm fairly certain that's why my network graph is not displaying properly:
![image](https://user-images.githubusercontent.com/46235745/168347157-1916e138-9b92-4f2d-9ce8-5cd579d4d6d7.png)

What steps can I take to get my controller to detect its neighbors?

**Comment by robertsLando** [comment]
Application version?

**Comment by GitHubGoody** [comment]
Sorry...

zwavejs2mqtt: 6.8.1
zwave-js: 9.0.7

**Comment by robertsLando** [comment]
I would recommend you to firstly try with latest version. If it still doesn't work please do a nodes export from control panel advanced dialog and upload it there

**Comment by GitHubGoody** [comment]
I installed via the HA add-on, so do I need to wait for that to be updated to pull in v6.9.1?

**Comment by robertsLando** [comment]
In the meanwhile just upload nodes export please

**Comment by GitHubGoody** [comment]
The add-on was just updated today, so I'm not running:

zwavejs2mqtt: 6.9.1
zwave-js: 9.2.2

My network graph still looks like the screenshot in the original post.

I tried to attach my nodes.json, but GitHub won't support .json (I tried a rename to nodes.txt too). But, my network isn't very large yet, so here's the contents:

```
{
  "1": {
    "name": "Aeotec Z-Stick 7",
    "loc": "Office"
  },
  "3": {
    "name": "GE ZW3101",
    "loc": "Study"
  },
  "6": {
    "name": "GE ZW3103",
    "loc": "Dining Room"
  },
  "10": {
    "name": "Zooz ZEN25A",
    "loc": "Master"
  },
  "13": {
    "name": "Zooz ZEN15B",
    "loc": "Laundry"
  },
  "14": {
    "name": "Zooz ZEN15C",
    "loc": "Study"
  },
  "15": {
    "name": "Zooz ZEN15A",
    "loc": "Hallway"
  },
  "16": {
    "name": "Zooz ZEN25B",
    "loc": "Study"
  }
}
```

**Comment by GitHubGoody** [comment]
@robertsLando Did I upload the right files?

**Comment by robertsLando** [comment]
Sorry @GitHubGoody Have been really busy, I have checked your nodes and them seems good at first sight, I need to try importing them manually on my UI to debug the issue

**Comment by GitHubGoody** [comment]
Ok, thank you. No problem. I just wanted to check in to make sure I provided the right files. Standing by.

**Comment by robertsLando** [comment]
@GitHubGoody just found some time to debug this. Seems your controller has no neighbors. I remember an issue similar to this but cannot find it right now. @AlCalzone any clue why this could happen?

**Comment by AlCalzone** [comment]
I've seen this before in networks with a bad controller location. @GitHubGoody did you follow the general troubleshooting steps?
https://zwave-js.github.io/node-zwave-js/#/troubleshooting/connectivity-issues?id=general-troubleshooting

**Comment by GitHubGoody** [comment]
Yeah, the Aeotec Z-Stick 7 was already on a USB extension cable. Randomly, I just checked my network graph and it's now reporting a single neighbor (3) which I don't understand because all of the other devices have the controller as a neighbor. Doesn't that mean there should also be a line connecting the controller with all of the nodes as well?

![image](https://user-images.githubusercontent.com/46235745/171459021-1d7e7e0e-8cf0-470c-97a1-60672f847553.png)

**Comment by robertsLando** [comment]
@GitHubGoody I removed the option to show all neighbors, I think I need to re-add it

**Comment by AlCalzone** [comment]
The thing is... Assuming this information is even correct, if the controller doesn't see a node, **is it** actually a neighbor?

That said, this view should really only be a fallback solution if the actual routes are not known. Too much confusion and time wasted on trying to fix things that might not be an issue.

**Comment by GitHubGoody** [comment]
How can all of the nodes have the controller as a neighbor, but the controller not have all of the nodes as neighbors? Is it a matter of signal strength (nodes have strong Rx weak Tx)?

Also, why would any of the nodes take more than one hop if they all have the controller as a neighbor? Or, is the network graph programmed to depict the strongest signal?

What do you mean by "fallback solution?" To what? Isn't the point to graphically depict the speed, redundancy, and robustness of the network to node failures?

**Comment by AlCalzone** [comment]
> How can all of the nodes have the controller as a neighbor, but the controller not have all of the nodes as neighbors? Is it a matter of signal strength (nodes have strong Rx weak Tx)?

Yes, either this or the information is wrong. I've seen it before.

Short answer: this graph is useless

Long answer: Z-Wave JS asks the controller for each node A which other nodes it reports as neighbors - that is the ones that responded to a ping from A during the last neighbor discovery.
This information is stored in the controller memory though, so it can be outdated or corrupted or whatever. For some users it works, for others it doesn't and we haven't been able to find out where the difference is.

Also, this graph does not convey **any information** about connection strength, or which routes are actually taken, or hops really. Just which routes could have been taken at the time this information was recorded - and even here I'm not sure. I've just seen it be totally wrong so often.

The driver supports building a dynamically updated map of the actual routes in use with statistics of signal strength and round-trip-time and potentially broken links. It's just that no application uses that information yet to draw one.
In Z2m you can see some of this information though when you click on a node in the map and look at the panel on the left.

**Comment by AlCalzone** [comment]
> Is that 'Repeaters' data more accurate at any point in time or does it also go stale?

Yeah, it gets updated whenever a message is exchanged with that node, so over time you can use it to build an "always" accurate map. This won't include routes that don't involve the controller though, because for these we don't get the information.

**Comment by GitHubGoody** [comment]
Better than nothing...and what we currently have? Worth submitting a feature request?

**Comment by AlCalzone** [comment]
I've talked with @robertsLando about it a while back, so it is somewhere on the to do list.

**Comment by robertsLando** [comment]
Refactoring zwavegraph requires lot of work but it's on my todo list. Closing this for now as the main issue is resolved
