### ISSUE TITLE
[feat] better documentation for upgrading and backing up docker-compose based installation

### ISSUE THREAD

**Issue by josh-m-sharpe** [zwave-js/zwavejs2mqtt#2428]
I'm using these docs to run zwavejs2mqtt: https://zwave-js.github.io/zwavejs2mqtt/#/getting-started/docker?id=run-as-a-service

My image is currently out of date.  What is the proper way to upgrade it?  Maybe `docker compose down && docker compose up -d` ?  Will that preserve my configuration?  Will it pull thew new latest image?

Also, it may be good to add some tips/ideas on how to back up the entire volume and thus the configuration that is on it.

Thanks!

**Comment by robertsLando** [comment]
About the backup there is an open issue to add an automatic backup of application/controller data that it's in my TODOs. About your question for upgrading just do:

```
docker-compose pull && docker-compose up -d
```
