### ISSUE TITLE
upgraded to latest version and lost all my devices

### ISSUE THREAD

**Issue by magimat** [zwave-js/zwavejs2mqtt#2430]
Hi,

I had zwavejs2mqtt running in a docker container for a few months and everything was working fine.

Yesterday, I pulled the latest image and restarted everything using the same config, but now I lost all my devices.

Is it to be expected?  Any easy way to recover everything other that rebinding al my devices??

thanks!

**Comment by robertsLando** [comment]
@magimat Send logs please, this is absolutely not an expected behaviour
