### ISSUE TITLE
[Home Assistant] HS1HT-Z wrong battery status report to HA

### ISSUE THREAD

**Issue by Fabio72** [zwave-js/zwavejs2mqtt#2431]
### Version

Build/Run method:

[x] Docker
[ ] Git Clone + yarn install + yarn run build + yarn start
[ ] Pkg

Zwavejs2Mqtt version: 6.9.1
Z-Wave JS version: 9.2.2
Home Assistant version: 2022.5.4

### Describe the bug

Battery Level and Low Battery Level are shown correctly on Control Panel, but HA shows 0% Battery Level and unknown Low Battery Level
Node #3
DeviceID 608-4096-32775 (0x0260-0x8007-0x1000) 

[zwave_js-Temperature_Humidity Sensor-.json.zip](https://github.com/zwave-js/zwavejs2mqtt/files/8727097/zwave_js-Temperature_Humidity.Sensor-.json.zip)
[nodes_dump.zip](https://github.com/zwave-js/zwavejs2mqtt/files/8727153/nodes_dump.zip)

**Comment by robertsLando** [comment]
Open this bug on Home assistant repo please, It's not something I can fix here
