### ISSUE TITLE
[question] Issue with Somfy Zwave-RTS II (ZRTSII) stop

### ISSUE THREAD

**Issue by jdiegmueller** [zwave-js/zwavejs2mqtt#2437]
I'm not sure if this is a zwavejs2mqtt thing or an HA thing -- hoping someone can point me in the right direction.

I have a Somy ZRTSII Zwave-to-RTS controller which remotely controls motors on window blinds.  The controller itelf gets included as the "base node" and each of the 16 RTS channel (blinds & blind groups) can be optionally presented to the Zwave network as a virtual node.  The virtual node is what you interact with.

From Homeassistant, cover.open_cover and cover.close_cover towards the virtual nodes work as expected.  Looking at things through a Zniffer, I see a single Zwave Switch Multilevel Set message get sent out and the respective RTS channel/blinds start moving up or down accordingly.  However, I'm getting undesired behavior with cover.stop_cover.  When I send a cover.stop_cover, I see two Switch Multilevel Stop Level Change messages send back-to-back.  

These Somfy motors have a "favorite position" concept they call My Somfy.  Under the hood the way they implemented it was such that a "stop" command when the blinds are not moving up or down will recall the My Somfy position.  Since cover.stop_cover to these Zwave devices result in back-to-back stops, the motors end up stopping on the first message but then changing to the My Somfy position on the second.  

My setup is HomeAssistant 2022.5.5->zwavejs2mqtt 6.10.0 -> zwavejs 9.3.0. 

I'm attaching a log snippet demonstrating the zwavejs2mqtt side of things.  Node 168 is the virtual node in question.  From Homeassistant I sent it a cover.close_cover, followed by a cover.open_cover, and then a cover.stop_cover.

Where should I be focusing my attention here?  Is Homeassisant simply instructing zwavejs2mqtt to send two stops, or is zwavejs2mqtt doing that of its' own accord?  

Thanks for any insight.

[zwsnippet.txt](https://github.com/zwave-js/zwavejs2mqtt/files/8767512/zwsnippet.txt)

**Comment by jdiegmueller** [comment]
![image](https://user-images.githubusercontent.com/18660571/170169578-b2075a27-12f1-4f1b-b1e4-ef228a212691.png)

Different timestamps than the log, but a simple Zniffer screenshot showing how up and down are sent as single commands, but stop gets sent as a double.

**Comment by kpine** [comment]
You didn't actually say how you are using Z-Wave JS with Home Assistant. If you are using the Z-Wave JS integration, then you should submit an issue there. https://github.com/home-assistant/core/issues/new/choose

I assume you're using the integration, because [its code](https://github.com/home-assistant/core/blob/209f37196e779d96da8451a31d712313e3ae29e2/homeassistant/components/zwave_js/cover.py#L164-L182) sends two stop commands.

**Comment by jdiegmueller** [comment]
Yes, I guess it is the HA ZwaveJS integration attached to zwavejs2mqtt's websocket server.  I figured the issue had to be either on this side or the HA side, and it seems you've rightly found it on the HA ZWaveJS side.  

Thank you for the pointer to the specific code; armed with that knowledge, I'm fairly sure I can cook up some sort of local hack to only send stop once.

**Comment by jdiegmueller** [comment]
> Yes, I guess it is the HA ZwaveJS integration attached to zwavejs2mqtt's websocket server. I figured the issue had to be either on this side or the HA side, and it seems you've rightly found it on the HA ZWaveJS side.
> 
> Thank you for the pointer to the specific code; armed with that knowledge, I'm fairly sure I can cook up some sort of local hack to only send stop once.

Thanks again for the pointer, I was able to hack the ZwaveJS cover integration to only send only a single stop command.  Empowered with the ability to stop the up/down events, I was able to hack together a virtual cover integration for each blind group that handles position by travel time.
