### ISSUE TITLE
[Bug]: Z-Wave js configuration with Razberry board

### ISSUE THREAD

**Issue by baldus88** [zwave-js/zwavejs2mqtt#2446]
### Checklist

- [ ]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Zwavejs2Mqtt version

6.9.1

### ZwaveJS version

9.2.2

### Describe the bug

Hi.
I have the the razberry board installed in my raspberry 3 b+:
https://z-wave.me/products/razberry-old/
The functionality was ok in old configuration (zwave) and follow this guide to do install the module and integration:
https://wiki.fhem.de/wiki/Raspberry_Pi_3:_GPIO-Port_Module_und_Bluetooth

This is the status:
![image](https://user-images.githubusercontent.com/57867040/171277480-cbf7f955-d3b1-4408-a32a-ac0ba76fe243.png)

But after the new release of home assistant need to migrate from zwave (depecreate) ->
https://www.home-assistant.io/blog/2022/03/02/release-20223/

_As Home Assistant is moving towards support for Python 3.10, it became clear that the old zwave integration isn’t compatible and thus is going to be removed for that reason._

to zwavejs2mqtt.
I followed the guided steps and arrived to this:
![image](https://user-images.githubusercontent.com/57867040/171277669-2fe307f8-0e8d-4e2b-acc1-6972920e503a.png)

The docker and the cointaner are already installed and the i have this configuration cointaner: 

```
version: "3.9"
services:
zwavejs2mqtt:
container_name: zwavejs2mqtt
image: zwavejs/zwavejs2mqtt:latest
restart: unless-stopped
devices:
- "/dev/ttyAMA0:/dev/zwave"
volumes:
- "/home/pi/zwavejs2mqtt:/usr/src/app/store"
ports:
- "3000:3000"
- "8091:8091"
```
I have use the port /dev/ttyAMA0 that already configured in the past configuration but I didn't find other device port.
When try to start the application have this error log:
```
2022-05-31T05:57:06.525Z DRIVER   ███████╗ ██╗    ██╗  █████╗  ██╗   ██╗ ███████╗             ██╗ ███████╗
                                  ╚══███╔╝ ██║    ██║ ██╔══██╗ ██║   ██║ ██╔════╝             ██║ ██╔════╝
                                    ███╔╝  ██║ █╗ ██║ ███████║ ██║   ██║ █████╗   █████╗      ██║ ███████╗
                                   ███╔╝   ██║███╗██║ ██╔══██║ ╚██╗ ██╔╝ ██╔══╝   ╚════╝ ██   ██║ ╚════██║
                                  ███████╗ ╚███╔███╔╝ ██║  ██║  ╚████╔╝  ███████╗        ╚█████╔╝ ███████║
                                  ╚══════╝  ╚══╝╚══╝  ╚═╝  ╚═╝   ╚═══╝   ╚══════╝         ╚════╝  ╚══════╝
2022-05-31T05:57:06.525Z DRIVER   version 9.2.2
2022-05-31T05:57:06.525Z DRIVER
2022-05-31T05:57:06.526Z DRIVER   starting driver...
2022-05-31T05:57:06.531Z DRIVER   opening serial port /dev/ttyAMA0
2022-05-31T05:57:15.561Z DRIVER   Failed to open the serial port: Error: No such file or directory, cannot open
                                  /dev/ttyAMA0
2022-05-31T05:57:15.564Z DRIVER   destroying driver instance...
```

This view in log page:
![image](https://user-images.githubusercontent.com/57867040/171278171-e114afe4-bc0a-4381-b6f4-890513a9c6a2.png)

Could you please help me?

Regards

### To Reproduce

Try to apply the application cointaner with this configuration:
```
version: "3.9"
services:
zwavejs2mqtt:
container_name: zwavejs2mqtt
image: zwavejs/zwavejs2mqtt:latest
restart: unless-stopped
devices:
- "/dev/ttyAMA0:/dev/zwave"
volumes:
- "/home/pi/zwavejs2mqtt:/usr/src/app/store"
ports:
- "3000:3000"
- "8091:8091"
```

Have this error:
```
2022-05-31T05:57:06.531Z DRIVER   opening serial port /dev/ttyAMA0
2022-05-31T05:57:15.561Z DRIVER   Failed to open the serial port: Error: No such file or directory, cannot open
                                  /dev/ttyAMA0
2022-05-31T05:57:15.564Z DRIVER   destroying driver instance...
```
Probably, in advance, I wrong the volumes, if i launch this log:
`pi@raspberrypi:~/zwavejs2mqtt $ docker container logs zwavejs2mqtt -f`

Have multiple lines of this:
```
Logging to file:
        /usr/src/app/store/zwavejs_2022-05-24.log
Logging to file:
        /usr/src/app/store/zwavejs_2022-05-24.log
Logging to file:
        /usr/src/app/store/zwavejs_2022-05-24.log
```

And the content is this:
```
pi@raspberrypi:~/zwavejs2mqtt $ cat /usr/src/app/store/zwavejs_2022-05-24.log
cat: /usr/src/app/store/zwavejs_2022-05-24.log: No such file or directory
```

The path is present but the container doesn't write anything:
```
pi@raspberrypi:~/zwavejs2mqtt $ cd /usr/src/app/store/
pi@raspberrypi:/usr/src/app/store $ ls -tlr
total 0
```

Regards

### Expected behavior

Open correctly the page of zwave js configuration.

**Comment by kpine** [comment]
```yaml
devices:
- "/dev/ttyAMA0:/dev/zwave"
```

With this you have configured your docker container to map the host device `/dev/ttyAMA0` into the container as `/dev/zwave`.  You have configured zwavejs2mqtt with the wrong path, it should be `/dev/zwave`.

**Comment by baldus88** [comment]
> With this you have configured your docker container to map the host device `/dev/ttyAMA0` into the container as `/dev/zwave`. You have configured zwavejs2mqtt with the wrong path, it should be `/dev/zwave`.

Sorry but this step is not properly clear for me. I have followed this steps:
https://flemmingss.com/how-to-set-up-zwavejs2mqtt-on-a-raspberry-pi-and-integrate-it-with-home-assistant/

And I am changed this configuration docker:
```
version: "3.9"
services:
  zwavejs2mqtt:
    container_name: zwavejs2mqtt
    image: zwavejs/zwavejs2mqtt:latest
    restart: always
    tty: true
    stop_signal: SIGINT
    networks:
      - zwave
    devices:
      - '/dev/ttyAMA0:/dev/ttyAMA0'
    volumes:
      - ./store:/usr/src/app/store
    ports:
      - "8091:8091"
      - "3000:3000"
networks:
  zwave:
```

After this have this error in page:
![image](https://user-images.githubusercontent.com/57867040/171509696-b4119f87-2b82-472e-9053-c9cb4b4add03.png)

In log view this:
```
2022-06-01 22:06:08.998 INFO ZWAVE-SERVER: Server closed
Logging to file:
        /usr/src/app/store/zwavejs_2022-06-01.log
```
This is the log
/home/pi/zwavejs2mqtt/store/zwavejs_2022-06-01.log

`2022-06-01T22:07:45.004Z CNTRLR   Failed to execute controller command after 1/3 attempts. Scheduling next try i
                                  n 100 ms.
2022-06-01T22:07:45.107Z SERIAL » 0x01030020dc                                                         (5 bytes)
2022-06-01T22:07:45.109Z DRIVER » [REQ] [GetControllerId]
2022-06-01T22:07:46.124Z CNTRLR   Failed to execute controller command after 2/3 attempts. Scheduling next try i
                                  n 1100 ms.
2022-06-01T22:07:47.229Z SERIAL » 0x01030020dc                                                         (5 bytes)
2022-06-01T22:07:47.232Z DRIVER » [REQ] [GetControllerId]
2022-06-01T22:07:48.266Z DRIVER   Failed to initialize the driver: ZWaveError: Timeout while waiting for an ACK
                                  from the controller (ZW0200)
                                      at Driver.sendMessage (/usr/src/app/node_modules/zwave-js/src/lib/driver/D
                                  river.ts:3479:23)
                                      at ZWaveController.identify (/usr/src/app/node_modules/zwave-js/src/lib/co
                                  ntroller/Controller.ts:692:33)
                                      at Driver.initializeControllerAndNodes (/usr/src/app/node_modules/zwave-js
                                  /src/lib/driver/Driver.ts:1071:26)
                                      at Immediate.<anonymous> (/usr/src/app/node_modules/zwave-js/src/lib/drive
                                  r/Driver.ts:878:16)
2022-06-01T22:07:48.273Z DRIVER   destroying driver instance...
2022-06-01T22:07:48.278Z DRIVER   driver instance destroyed
2022-06-01T22:07:48.343Z DRIVER   ███████╗ ██╗    ██╗  █████╗  ██╗   ██╗ ███████╗             ██╗ ███████╗
                                  ╚══███╔╝ ██║    ██║ ██╔══██╗ ██║   ██║ ██╔════╝             ██║ ██╔════╝
                                    ███╔╝  ██║ █╗ ██║ ███████║ ██║   ██║ █████╗   █████╗      ██║ ███████╗
                                   ███╔╝   ██║███╗██║ ██╔══██║ ╚██╗ ██╔╝ ██╔══╝   ╚════╝ ██   ██║ ╚════██║
                                  ███████╗ ╚███╔███╔╝ ██║  ██║  ╚████╔╝  ███████╗        ╚█████╔╝ ███████║
                                  ╚══════╝  ╚══╝╚══╝  ╚═╝  ╚═╝   ╚═══╝   ╚══════╝         ╚════╝  ╚══════╝
2022-06-01T22:07:48.344Z DRIVER   version 9.2.2
2022-06-01T22:07:48.345Z DRIVER
2022-06-01T22:07:48.345Z DRIVER   starting driver...
2022-06-01T22:07:48.352Z DRIVER   opening serial port /dev/ttyAMA0
2022-06-01T22:07:48.360Z DRIVER   serial port opened
2022-06-01T22:07:48.361Z SERIAL » [NAK]                                                                   (0x15)
2022-06-01T22:07:48.365Z DRIVER   loading configuration...
2022-06-01T22:07:48.370Z CONFIG   Using external configuration dir /usr/src/app/store/.config-db
2022-06-01T22:07:48.370Z CONFIG   version 9.2.2
`
Could you please support me?

Regards

**Comment by Thaui57** [comment]
It's quite easy. Install the away server come the razberry side. After installation stop or uninstall the package. The ttyAMA0 port will be available. I have spend also several hours to find the right way. This is the easiest and the fastest. Good luck

**Comment by baldus88** [comment]
> It's quite easy. Install the away server come the razberry side. After installation stop or uninstall the package. The ttyAMA0 port will be available. I have spend also several hours to find the right way. This is the easiest and the fastest. Good luck

Sorry what do you mean for "install the away server"? Could you please sent me the steps/guide for this?

Thanks
Regards

**Comment by Thaui57** [comment]
sorry this was a typo erroe. Insatll the Z-Way Server from there Suport page. This install skript will provide you with the ttyAMA0 port.

 

Install Zwave.me to get the Razberry Board activated

wget -q -O - https://storage.z-wave.me/RaspbianInstall | sudo bash

 

Check if the server is running  http://<ip>:8083/ and switch off Autostart

 

sudo /etc/init.d/z-way-server stop

sudo update-rc.d z-way-server disable

 

you can also uninstall the Z-way server. The ttyAMA0 will remain

 

sudo apt --purge remove zbw  ##remove Z-way

sudo apt --purge remove z-way-server  ##remove Z-way server

 

Von: baldus88 <> 
Gesendet: Montag, 13. Juni 2022 21:52
An: zwave-js/zwavejs2mqtt ***@***.***>
Cc: Thaui57 ***@***.***>; Comment ***@***.***>
Betreff: Re: [zwave-js/zwavejs2mqtt] [Bug]: Z-Wave js configuration with Razberry board (Issue #2446)

 

It's quite easy. Install the away server come the razberry side. After installation stop or uninstall the package. The ttyAMA0 port will be available. I have spend also several hours to find the right way. This is the easiest and the fastest. Good luck

Sorry what do you mean for "install the away server"? Could you please sent me the steps/guide for this?

Thanks
Regards

**Comment by baldus88** [comment]
Thanks for the support! After reboot the raspberry now the zwavejs2mqtt server go ok:

![image](https://user-images.githubusercontent.com/57867040/173694353-42687641-fe24-40b0-b3b9-e1abf5e16b51.png)

And home assistant migrate the integration correctly.

![image](https://user-images.githubusercontent.com/57867040/173694514-4a4824cc-8e7d-487c-ae2a-d6ee8a567b65.png)


Regards
