### ISSUE TITLE
[Bug]: Inclusion via SmartStart QR code forgets supplied Name 

### ISSUE THREAD

**Issue by tommyjlong** [zwave-js/zwavejs2mqtt#2447]
### Checklist

- [ ]  I am not using Home Assistant. Or: a developer has told me to come here.
- [ ] I have checked the troubleshooting section and my problem is not described there.
- [ ] I have read the changelog and my problem is not mentioned there.

### Deploy method

Manually built (git clone - yarn build - yarn install

### Zwavejs2Mqtt version

6.11.0 (tagged branch)

### ZwaveJS version

9.3.0

### Describe the bug

Inclusion via QR code Smart Start forgets supplied Name.

I don't know if this is the same as https://github.com/zwave-js/zwavejs2mqtt/issues/2389 or not, but since Changelog 6.8.0 says the issue was fixed, I wanted to reopen.

### To Reproduce

Steps: Action->Mange Nodes-> Inclusion, Next: Enter Name as `kitchen_ceiling_lights` (but did not enter any Location data), Next: selected "Scan QR Code" where I imported a picture of the QR code, and it returned "Node added to Provisioning List".  I did not close this dialog.  I went and powered up my node and a popup appeared: "node xxx added with security "S2 Authenticated".

I watched the logs until I saw that the device's interview process was completed.  I then closed out the dialogs and checked the control panel to see that the node was added, but there was no location data.  I checked the nodes.json and it was not there either.

I was able to manually enter the name afterwards.

### Expected behavior

Expected Name to be populated in the node's data after Smart Start based inclusion was successful.

**Comment by robertsLando** [comment]
> (but did not enter any Location data

Does it work if you provide both location and name?

**Comment by tommyjlong** [comment]
I just tried this on a new device. Its a battery device.  I repeated the above, but this time included both name and location.  After powering up the device, the S2 authentication completed and the device shows up in the control panel.  Although the interview process hasn't completed yet, there is still neither name nor location showing up in the control panel..

**Comment by robertsLando** [comment]
Found the bug and fixed. Anyway in the meanwhile you can add provisioning entries from provisioning entries tab, in that way it works and it doens't forget node name and location
