### ISSUE TITLE
[Bug]: Firmware updates not working 

### ISSUE THREAD

**Issue by Botched1** [zwave-js/zwavejs2mqtt#2468]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Zwavejs2Mqtt version

6.12.0

### ZwaveJS version

9.3.0

### Describe the bug

When attempting to update a firmware, it lets me select the device, and the firmware file and then does nothing. I also see a user disconnect/reconnect in the live debug logs.

### To Reproduce

1. Open z2m web interface
2. Select device, click advanced, Firmware update - begin
3. Use default of target 0
4. Select firmware file
5. Dialog closes, nothing happens, and I see this in the z2m debug screen

This is all that is logged in the z2m log (set to debug), and nothing at all is logged in the zwavejs log file:

2022-06-15 17:15:42.990 DEBUG SOCKET: User disconnected TRWpuXXUGzn_8xrDAAAZ
2022-06-15 17:15:44.314 DEBUG SOCKET: New connection kgRV8vkesEqQ4GO2AAAd
2022-06-15 17:15:44.325 DEBUG SOCKET: Event INITED emitted to kgRV8vkesEqQ4GO2AAAd

### Expected behavior

Firmware update should begin

**Comment by robertsLando** [comment]
@Botched1 do you press enter or click on the button to start the update?

**Comment by Botched1** [comment]
As soon as I click "open" on the file dialog where I select the firmware file, it immediately goes back to the advanced dialog. This is immediately after clicking "open" on the file selection dialog:

![image](https://user-images.githubusercontent.com/19985320/174188339-44254fad-1625-41ce-a719-ec7fd16fefa0.png)

**Comment by Botched1** [comment]
And of course the next time I tried it - it worked. Confusing, as I tried maybe 10 times before reporting (including after reboots, and restarts of the software)...

I would say ignore this for now and I'll see if I can reproduce it... If not, I'll just close this issue.

**Comment by Botched1** [comment]
I can't reproduce this, closing issue.

**Comment by mundschenk-at** [comment]
I don't have a way to reliably reproduce it either, but I've noticed the same issue as @Botched1: Very often the FW update does not "take". Also, there is no UI feedback for sleeping nodes (the circle only starts once the sleeping node has been woken up).
