### ISSUE TITLE
[Bug]: Log rotation not working

### ISSUE THREAD

**Issue by decairn** [zwave-js/zwavejs2mqtt#2471]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Zwavejs2Mqtt version

6.12

### ZwaveJS version

9.3.0

### Describe the bug

A couple of things here I notice:
1 - Expecting a 7-day (?) rotation but the logs are accumulating daily
2 - There's a gap or two in daily log name zips (and I haven't manually deleted any) e.g. June 1 and June 8 in attached file list.

The zwavejs log is rotating every 7 days so this is restricted to zwavejs2mqtt only.

Running from HA with Frenk add-on, if that matters

![Gaps in daily log list](https://user-images.githubusercontent.com/15806011/174346695-5e1ac45b-5822-47f3-87fc-584d78e8b259.JPG)
![Configuration](https://user-images.githubusercontent.com/15806011/174347005-53147278-726b-4149-a5bf-79c16f87d615.JPG)
.

### To Reproduce

Configure as per attached configure file.  Let it run > 1 week.

### Expected behavior

Logs rotate, directories don't grow with files unmanaged. One archive per day, no gaps.

**Comment by robertsLando** [comment]
I did some checks a while ago and it was working but I know you are not the only one having by this problem, I will investigate on this
