### ISSUE TITLE
[question]  Zwave driver not inited, no port configured 

### ISSUE THREAD

**Issue by Inquisitive-ME** [zwave-js/zwavejs2mqtt#2473]
I have been trying to get zwavejs2mqtt running in a docker container but it doesn't work.

My command is:
```
docker run --rm -it -p 8091:8091 -p 3000:3000 --device=/dev/serial/by-id/usb-0658_0200-if00:/dev/zwave -v $(pwd)/store:/usr/src/app/store zwavejs/zwavejs2mqtt:latest
```
which is from the getting started documentation but I get:
```
2022-06-18 22:27:51.761 WARN ZWAVE: Zwave driver not inited, no port configured
```
and my device doesn't show up on the webpage. I'm not sure what to do I already had this controller working with ozwdaemon so I am pretty sure everything works, and I am missing something in the setup of zwavejs2mqtt

**Comment by kpine** [comment]
You haven't configured the minimum required settings as mentioned in the Quick Start guide: https://zwave-js.github.io/zwavejs2mqtt/#/getting-started/quick-start?id=minimum-settings

See step 1, "Configure the serial port". Based on your docker command, the serial port needs to be configured as `/dev/zwave`. Even if it shows that when you go to the page, you still need to input it and save it.

**Comment by Inquisitive-ME** [comment]
Thank you that was my problem. It is not very obvious that you need to save the settings from the Quick Start Guide. To me saying "the template Docker Compose file maps the Z-Wave stick to /dev/zwave" made me assume that it would already be configured for /dev/zwave especially because this is pre-populated in the settings to make it seem like it is pre-configured.
