### ISSUE TITLE
[feat]: Allow to force disable SSL

### ISSUE THREAD

**Issue by alexruffell** [zwave-js/zwavejs2mqtt#2480]
### Checklist

- [ ]  I am not using Home Assistant. Or: a developer has told me to come here.
- [x] I have checked the troubleshooting section and my problem is not described there.
- [x] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Zwavejs2Mqtt version

6.12

### ZwaveJS version

9.3.0

### Describe the bug

When trying to scan QR code for DSK on Android and on Windows 11 (Chrome 102.0.5005.115) it fails with a "Socket Disconnected" error on Android and nothing on Windows. I also tried adding the full code typing it in with the same result.

Home Assistant OS
core-2022.6.7
ZwaveJS2MQTT installed using addon/integration method

### To Reproduce

ZwaveJS2MQTT >> Smart Start >> + >> SCAN
Scan QR and window closes immediately (no legible error on windows, but on Android is says "Socket Disconnected")
I have been able to provision entities before but had deleted the couple attempts

The same happens when you type everything instead of using camera/webcam to scan QR

### Expected behavior

Provisioned Entity gets added to list.

**Comment by alexruffell** [comment]
Just noticed the check boxes. I did 2 and 3, but missed 1. I am using HA so should I report this elsewhere?

**Comment by robertsLando** [comment]
Hi Alex, no worries you opened the issue in the right place :)

I'm wondering if Android has some king of debug console available, I need to know what causes the socket to disconnect, may be a permission issue for example, does your browser have permission to access the camera?

**Comment by alexruffell** [comment]
When I try to scan the QR, the image from the camera appears on screen both on my Android phone and on my Windows desktop so permissions shouldn't be an issue (at least not camera permissions). I also confirmed that the HA app on my phone has both Camera and Location permissions allowed. The error seems to occur at the exact moment the QR is recognized.

Since the issue happens on Windows using Chrome as well, can I use the Chrome debug console? I tried it but I am not sure where to poke to find any errors.

**Comment by robertsLando** [comment]
> Since the issue happens on Windows using Chrome as well, can I use the Chrome debug console? I tried it but I am not sure where to poke to find any errors.

Press F12 and check console for errors. Paste the content of console here if there are

**Comment by alexruffell** [comment]
There is no output. On another note, I noticed that if I access HA using the local method (http) then the entities I provisioned using ZwaveJS (not the MQTT variant) are listed while if I access HA using the NabuCasa URL (https) so that I can access the camera then they are not listed.

**Comment by robertsLando** [comment]
That's for sure something about security issues if http is working and https is not... how did you deployed z2m? did you enabled https on settings?

**Comment by alexruffell** [comment]
I turned it on and now I can't access ZwaveJS2MQTT any longer. I get a black screen and 502: Bad Gateway on both the http and https URLs for HA. How do I recover from this? I am quite sure my overall SSL configuration is broken... A while back I had set it up following online tutorials but I then subscribed to NabuCasa and tried to get rid of it due to the complications it was adding likely making things worse. It appears that addons all recommend/want SSL even when everything is running on the same device so I will try to figure out the best way to set it up again.

**Comment by robertsLando** [comment]
As setting says you have to restart application after switching https on/off, did you do it?


Anyway you cannot have mixed content on the page, if you are accessing it via https the application should also be served using https.

If the problem persists the onyl way to recover is to manually edit settings file in store and change `"https": true` -->  `"https": false`

**Comment by kpine** [comment]
The add-on does not support enabling SSL, and the container image doesn't even install the necessary SSL libraries. Once you enable it, you're hosed. You'll have to edit the filesystem files directory to recover. See https://github.com/hassio-addons/addon-zwavejs2mqtt/issues/309#issuecomment-1051342300, or restore from a backup.

**Comment by alexruffell** [comment]
While I can SSH into HASS, I can't run the docker command listed in that other post. I am looking into fixing my SSL issues... would  "retrofitting" SSL fix this issue or should I just try to restore?

**Comment by kpine** [comment]
Maybe you need to install the community SSH add-on. "Retrofit" is not an option.

**Comment by alexruffell** [comment]
I already have that, and am SSH'd into HASS but I can't see or get into any docker container.

**Comment by kpine** [comment]
Sorry, don't know what else to say, I don't use add-ons. Other users were successful, that's all I can point you to. Perhaps try the HA Community forums or Discord for additional help.

**Comment by alexruffell** [comment]
No worries, I restored and installed NGINX Proxy Manager. I followed a tutorial to setup SSL on my HASS install. Should I dare turn HTTPS on again? I just ran a full backup just in case.

**Comment by alexruffell** [comment]
Going back to square one on the ticket's issue... when I access zwavejs2mqtt via http://homeassistant.local:8123/a0d7b954_zwavejs2mqtt/dashboard I can see entities I provisioned using this:
<img width="933" alt="image" src="https://user-images.githubusercontent.com/4006944/175346815-0b042014-780c-47ec-a2e1-2dfd207c4c9a.png">

However, when I access the Smart Start tab in zwavejs2mqtt using the Nabu Casa URL I can no longer see them.

Regardless of how I access Smart Start, I cannot provision new entities. The local access method won't work because camera access is not supported with http (and that is ok), and the https method doesn't work as I get a "socket disconnected" error (on Android, on Windows not sure as it vanishes quickly).

**Comment by alexruffell** [comment]
Having a backup of the addon in my back pocket I tried to enable HTTPS again and I have access to zwavejs2mqtt via both homeassistant.local and the nabucasa urls. However, none of the issues in the previous post are fixed.

**Comment by alexruffell** [comment]
This morning I found zwavejs2mqtt crashed due to the https option being on. I had to restore the addon to before enabling it 3 days ago to recover. It would be awesome if it were easier to recover from this, and above all if it were documented (have yet to find it) on how ssl should be configured...

**Comment by kpine** [comment]
I can think of a number of things that could be done to address this.

1. Catch the exception that's thrown when `pem.createCertificate` fails because openssl is missing, then log some sort of warning, and prevent the functionality from being enabled. That would solve the problem for all users that don't have openssl installed, and not require some hack to restore functionality after-the-fact.
    1. Alternatively, detect on startup whether openssl is installed or not and enable/disable the functionality as appropriate. The pem module provides an `exec` API that lets you call arbitrary openssl commands. Simply checking `openssl version` might be sufficient. You could even [copy the function](https://github.com/Dexus/pem/blob/3a11f6340e70ee2803f3a50ccc0022dc0e7506f4/lib/openssl.js#L254-L261) that tests for the openssl command.
3. Update the installation documentation to mention the requirement of openssl.
4. Add some script to the yarn packaging that forces openssl to be checked for when z2m is installed. This would cause the add-on or any third party build to fail without it.
5. Work with the add-on maintainer and request that the library be added to avoid the problem.
6. Provide a way for the add-on maintainer to completely disable the SSL option in the GUI. It seems they don't want it to be used, maybe for valid reasons. This could be the environment variable you're thinking of. The add-on could set this option always, and the z2m UI could skip the cert stuff and hide the setting.

**Comment by robertsLando** [comment]
Thanks for all the suggestions @kpine ! I would skip only point 4 for now, the others looks good for me 👍🏼
