### ISSUE TITLE
[feat] create HASS sensor for CC 32 event

### ISSUE THREAD

**Issue by blhoward2** [zwave-js/zwavejs2mqtt#249]
**Is your feature request related to a problem? Please describe.**
Create new sensor for CC32 event notification. #116 

**Describe the solution you'd like**
The following works well when manually defined:

```
{
  "type": "sensor",
  "object_id": "double_tap",
  "discovery_payload": {
    "state_topic": "homeassistant/3/32/0/event",
    "value_template": "{{ value_json.value}}",
    "json_attributes_topic": "homeassistant/3/32/0/event",
    "device": {
      "identifiers": [
        "zwavejs2mqtt_0xeb87ad4a_node3"
      ],
      "manufacturer": "Jasco Products",
      "model": "In-Wall Dimmer Switch (GE 14294 (ZW3005))",
      "name": "nodeID_3",
      "sw_version": "5.29"
    },
    "name": "nodeID_3_double_tap",
    "unique_id": "zwavejs2mqtt_0xeb87ad4a_3-32-0-double_tap"
  },
  "discoveryTopic": "sensor/nodeID_3/double_tap/config",
  "values": [
    "32-0-event"
  ],
  "persistent": false,
  "ignoreDiscovery": false,
  "id": "sensor_double_tap"
}
```

**Comment by robertsLando** [comment]
@blhoward2 Could you send me the valueId object? Expoirt the node from the UI and attach it here please

**Comment by blhoward2** [comment]
[node_3.json.zip](https://github.com/zwave-js/zwavejs2mqtt/files/5821426/node_3.json.zip)

**Comment by robertsLando** [comment]
I still don't see the value id reported :thinking:

**Comment by blhoward2** [comment]
So, when we had the comapt flag to undo the mapping the basic value would appear in the Control Panel. Now that it is a notification not a value, it doesn't appear.

**Comment by robertsLando** [comment]
@AlCalzone ?

**Comment by blhoward2** [comment]
> @AlCalzone ?

I'm not yet running your PR, but I assume that doesn't affect the values being discovered?

**Comment by robertsLando** [comment]
The problem is: https://github.com/zwave-js/node-zwave-js/issues/1406
