### ISSUE TITLE
[Bug]: v6.13.0 does not start on Debian bullseye

### ISSUE THREAD

**Issue by phippodoplis** [zwave-js/zwavejs2mqtt#2501]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Manually built (git clone - yarn build - yarn install

### Zwavejs2Mqtt version

6.12.1.cdc1496

### ZwaveJS version

6.12.1.cdc1496

### Describe the bug

Debian bullseye only has nodejs version 12.22.5 and fs/promises has only been in nodejs since v14.0.0 . See this https://medium.com/@su_bak/how-to-solve-cannot-find-module-fs-promises-848c66fed6c9

### To Reproduce

Jun 28 14:39:47 wopr npm[523765]: > node --preserve-symlinks server/bin/www.js
Jun 28 14:39:48 wopr npm[523777]: Error: Cannot find module 'fs/promises'
Jun 28 14:39:48 wopr npm[523777]: Require stack:
Jun 28 14:39:48 wopr npm[523777]: - /var/local/hass/zwavejs2mqtt/server/lib/BackupManager.js
Jun 28 14:39:48 wopr npm[523777]: - /var/local/hass/zwavejs2mqtt/server/lib/ZwaveClient.js
Jun 28 14:39:48 wopr npm[523777]: - /var/local/hass/zwavejs2mqtt/server/config/store.js
Jun 28 14:39:48 wopr npm[523777]: - /var/local/hass/zwavejs2mqtt/server/bin/www.js
Jun 28 14:39:48 wopr npm[523777]:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
Jun 28 14:39:48 wopr npm[523777]:     at Function.Module._load (internal/modules/cjs/loader.js:667:27)
Jun 28 14:39:48 wopr npm[523777]:     at Module.require (internal/modules/cjs/loader.js:887:19)
Jun 28 14:39:48 wopr npm[523777]:     at require (internal/modules/cjs/helpers.js:74:18)
Jun 28 14:39:48 wopr npm[523777]:     at Object.<anonymous> (/var/local/hass/zwavejs2mqtt/server/lib/BackupManager.js:34:20)
Jun 28 14:39:48 wopr npm[523777]:     at Module._compile (internal/modules/cjs/loader.js:999:30)
Jun 28 14:39:48 wopr npm[523777]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
Jun 28 14:39:48 wopr npm[523777]:     at Module.load (internal/modules/cjs/loader.js:863:32)
Jun 28 14:39:48 wopr npm[523777]:     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
Jun 28 14:39:48 wopr npm[523777]:     at Module.require (internal/modules/cjs/loader.js:887:19)
Jun 28 14:39:48 wopr npm[523765]: npm ERR! code 1
Jun 28 14:39:48 wopr npm[523765]: npm ERR! path /var/local/hass/zwavejs2mqtt
Jun 28 14:39:48 wopr npm[523765]: npm ERR! command failed
Jun 28 14:39:48 wopr npm[523765]: npm ERR! command sh -c node --preserve-symlinks server/bin/www.js

### Expected behavior

It doesn't do that.

**Comment by robertsLando** [comment]
Nodejs 12 has reached its EOL on April, I don't think you cannot update your nodejs version, if v12 works also v16 will
