### ISSUE TITLE
[question] Identified a cause of "Unable to open serial port"

### ISSUE THREAD

**Issue by hansonap** [zwave-js/zwavejs2mqtt#2503]
Not sure where the best fit for this is as I already identified the cause of the issue but thought I would post it here to help others in the future.

If you have your z-wave device mapped correctly but it keeps failing to open the serial port, it could be an issue with your computer's BIOS settings. In my case, I recently flashed a new bios on my Gigabyte GA-990FXA-UD5 in order to boot from a NVME drive (via pci). This wipped out the Peripherals settings. IOMMU Controller needed to be enabled. Other suspects to watch out for are XHCI and EHCI.

Symptoms:
- Device was listed under /dev/... when plugged into USB 3.0 but not USB 2.0
- Keyboard worked when plugged into USB 3.0 but only worked in the BIOS / GRUB when plugged into USB 2.0
- ZWave To MQTT interface / logs kept reporting that the z-wave stick was connected but couldn't open the serial port.

I leave this issue open encase the info should be added to FAQ / troubleshooting section of the documentation.

**Comment by robertsLando** [comment]
Deploy method? Docker? Can I see your docker file? Your settings.json? I don't have any info to help you to solve your issue
