### ISSUE TITLE
[bug] Display issues on smartphones of healthchheck results table

### ISSUE THREAD

**Issue by robertsLando** [zwave-js/zwavejs2mqtt#2513]
![Screenshot_20220704-181336](https://user-images.githubusercontent.com/11502495/177299480-037451f7-0996-48b6-aac9-009d31d08725.png)

cc @jmgiaever

**Comment by jmgiaever** [comment]
Hi, thanks for the fix @robertsLando and to report the issue for me @AlCalzone :))
