### ISSUE TITLE
[bug] Home Assistant Auto Discover - Danalock V3 Status and Control Not Working

### ISSUE THREAD

**Issue by sembeeuk** [zwave-js/zwavejs2mqtt#252]
Version: 1.0.0-alpha.2

Build/Run method
- [x] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build ) 

zwavejs2mqtt version: 1.0.0-alpha2 (cannot get Docker to pull anything later). 
Raspberry PI. 

**Describe the bug**
Connecting a Danalock V3 BTZE. Connects fine and pulls in lots of information. However after running the Home Assistant Autodiscovery, the status node and command node seem to be wrong. 
Trying to lock/unlock the door from HA returns this error: 

Driver: Door Lock: "targetMode" must be of type "number", received "string"

For Status, it is looking at "Current Lock Mode" which doesn't appear to have anything connected to the state of the lock. 

Target Lock Mode list doesn't appear to have anything connected to lock. 
- Unsecured
- UnsecuredWithTimeout
- InsideUnsecured
- InsideUnsecuredWithTimeout
- OutsideUnscured
- OutsideUnsecuredWithTimeout

**To Reproduce**

Connect Danalock V3 BTZE to application.
Configure Autodiscover for the node - using the prefix homeassistant. 
Configure Home Assistant to auto discover. 
Attempt to lock/unlock the door.
Lock/Unlock the door manually and monitor the lock status. 

**Expected behavior**
Experimenting with MQTT Explorer, it seems that the status node is actually "boltStatus". I haven't established which node is the control node. 

**Additional context**
I have attached the node.json file. 

[node_2.json.txt](https://github.com/zwave-js/zwavejs2mqtt/files/5821232/node_2.json.txt)

**Comment by robertsLando** [comment]
You are speaking about this right?

```json
{
      "type": "lock",
      "object_id": "lock",
      "discovery_payload": {
        "command_topic": "zwave2mqtt/Garage/Side-Door/98/0/targetMode/set",
        "state_locked": "true",
        "state_unlocked": "false",
        "value_template": "{% if value_json.value == false %} false {% elif value_json.value == true %} true {% else %} unknown {% endif %}",
        "state_topic": "zwave2mqtt/Garage/Side-Door/98/0/currentMode",
        "json_attributes_topic": "zwave2mqtt/Garage/Side-Door/98/0/currentMode",
        "device": {
          "identifiers": ["zwavejs2mqtt_0xdcfeb435_node2"],
          "manufacturer": "Poly-control",
          "model": "Z-Wave controlled door lock with Bluetooth Smart (Danalock V3-BTZE)",
          "name": "Garage-Side-Door",
          "sw_version": "1.0.0-alpha.2"
        },
        "name": "Garage-Side-Door_lock",
        "unique_id": "zwavejs2mqtt_0xdcfeb435_2-98-0-currentMode"
      },
      "discoveryTopic": "lock/Garage-Side-Door/lock/config",
      "values": ["98-0-currentMode", "98-0-targetMode"],
      "persistent": true,
      "ignoreDiscovery": false
    },
```

If so, I suggest you to try to manually edit the template and try to make it working, you can do this in control panel, when you edit it press on rediscover and see if it fix, once you find a working template send it there so I can fix it. Unfortunally I don't own a lock to test this

**Comment by joeyb** [comment]
I just ran into the same issue with a Schlage lock and it looks like it was resolved with a really recent commit since switching to the `dev` docker image fixed it for me. There is some additional discussion in #178.

**Comment by robertsLando** [comment]
So closing this for now. Try to update the docker image @sembeeuk . Thanks @joeyb  for the feedback
