### ISSUE TITLE
[question] Getting a single device's values through MQTT

### ISSUE THREAD

**Issue by Lovasz-Akos** [zwave-js/zwavejs2mqtt#2524]
I'm having trouble finding an appropriate API or MQTT topic that would respond with the given device's values.
Let's say if there was an API called getNode(nodeId) that would send a JSON response containing every value, similar to getNodes but a specific one instead of all of them

**Comment by robertsLando** [comment]
There is no api to do that, what you could do is to use `driverFunction` api in order to get it

**Comment by robertsLando** [comment]
BTW I don't understand why you need to do so when you could simply subscribe to the desired valueId topic 🤔

**Comment by robertsLando** [comment]
This is not what's happening on my side, did you try to debug this by using mqtt explorer?

If you check this video: https://zwave-js.github.io/zwavejs2mqtt/#/guide/mqtt?id=example-setting-a-value

You will see I get updates of both target and current value in realtime

**Comment by Lovasz-Akos** [comment]
restarting worked, I think I even know what I managed to do here. 
if I rename a node, sending messages to the previous name's topic still updates the web UI but not the actual values on the device
