### ISSUE TITLE
[question] how to properly recreate from scratch an entity in homeassistant?

### ISSUE THREAD

**Issue by dvbit** [zwave-js/zwavejs2mqtt#254]
What would be the right sequence?
Remove entity from ha
Remove store in z2m
Stop ha
Delete entity from 
Mqtt 
Update node info in z2m
Heal node ?
Check log for the above to finish 
Restart ha
Rediscover node

Is that correct ?

**Comment by robertsLando** [comment]
@billiaz @chilicheech I can speak about the zwavejs2mqtt side, could one of you provide a detailed answer about the complete steps? Could also be added to hass docs too

**Comment by LordMike** [comment]
In HASS, it's quite simple. If you remove the retained discovery document for an entity, the entity disappears in HASS. If all entities from a device disappear, the device itself disappears.

An zwave2mqtt at least, did not push discovery documents unless it had to. So simply removing the mqtt topics, will remove it from HA "entirely".. .. in quotes, as the logger will still have data in it, so if you were to create entities with the same unique ids, they would "see" the historical data.

For z-wave, a refresh should be enough to clear all, right?.. Else, exclude (or remove failed & reset hardware device), then include again.

**Comment by robertsLando** [comment]
@LordMike This could be good to add to docs, if you have time :)

**Comment by dvbit** [comment]
Thanks! might be worth adding to the docs :-)

**Comment by LordMike** [comment]
@robertsLando I think this file is appropriate?

https://github.com/zwave-js/zwavejs2mqtt/blob/91eef10f24c6568aefd51aad5c77f7e771d8eb53/docs/guide/homeassistant.md

**Comment by robertsLando** [comment]
@LordMike Yepp!
