### ISSUE TITLE
[question] cannot get zwave2mqtt to save changes

### ISSUE THREAD

**Issue by SmartHomeNewbie** [zwave-js/zwavejs2mqtt#255]
> Hello
>
>Ive got some fibaro motion sensors where iam trying to change things like sensitivity in the configuration tab of the node.
>the first sensor i've had success chaning some parameters a week or two ago but when im trying now it keep jumping back to default, i guess i must be doing something wrong since it worked for me before?

 

So i installed zwavejs2mqtt but i still have the same problem, i have attached the "info" log 
[log.txt](https://github.com/zwave-js/zwavejs2mqtt/files/5823452/log.txt)

**Comment by SmartHomeNewbie** [comment]
So i tried changing the parameters alot of times yesterday, tried to combine it with refresh/heal node, restarting container & rebooting whole system and nothing was working.
But today when i woke up the parameters i had tried to change all night had changed...
So i tried again today on some other nodes that i need to adjust a bit, but ofcouse its not working :D can anyone tell me what the right procedure for changing parameters is ?

**Comment by robertsLando** [comment]
@SmartHomeNewbie YOu should attach the zwavejs log file to see what's happening on the low level

**Comment by SmartHomeNewbie** [comment]
Again this morgen more(not all) changes had taken effect.
zwavejs/low level?
i can choose between error/warn/info/verbose/debug/silly, witch one would you like?

**Comment by robertsLando** [comment]
@SmartHomeNewbie There are 2 loggers settings, one on zwave section and one on general section. YOu should enavble the one on general section and set it to silly level

**Comment by SmartHomeNewbie** [comment]
Ok i changed to silly level and made a change to "node 11"  [11-112-0-1] motion detection sensitivity from 100 to 75, the change  had taken effect when i checked a  few hours later.
It seems when i make a change i have to wait for the node to wake up, before it updates(without restarting the container) is that correct? if so is there a way to force it to wake up?
anyway the log is here:
[log.txt](https://github.com/zwave-js/zwavejs2mqtt/files/5826330/log.txt)

**Comment by cbho** [comment]
@SmartHomeNewbie: That is correct.
In general, battery devices only wake up once in a while - new settings will only be applied then.

Battery devices can usually be woken up by pressing the button you pressed when including the device once or three times (as stated in the manual).
To increase battery life you should go for long intervals...

(Fibaro Motion Sensors can actually be a bit stubborn sometimes, e.g. leave the motion alarm or the tamper alarm on for ages and stuff like that)...

Can recommend reading Christian Paetz' "Z-Wave Essentials" - that will give you a good idea about how z-wave works and spare you a lot of time not understanding what happens/doesn't happen.

**Comment by SmartHomeNewbie** [comment]
Makes sense then, screwed myself by restarting everytime it wouldnt update right away :D
Thanks alot for the help.
That book, 400 pages? think it would spare me more time asking you a question once iwahile :D

**Comment by FreelancerJay** [comment]
> That book, 400 pages? think it would spare me more time asking you a question once in awhile :D

@SmartHomeNewbie, it's time well spent, and that knowledge will help you make better informed choices on what devices to buy for what use etc. And for once for a book about networking, it's actually not a dry read ^_^

**Comment by robertsLando** [comment]
@SmartHomeNewbie Can I close this so? Thanks @cbho for the help

**Comment by SmartHomeNewbie** [comment]
Yes, Thank you
