### ISSUE TITLE
After restarting, most of the devices show Unknown manufacturer undefined [bug]

### ISSUE THREAD

**Issue by rotem925** [zwave-js/zwavejs2mqtt#256]
**Version**
latest docker dev build 1.0.0-beta.0
Build/Run method
- [x] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build ) 

zwavejs2mqtt version: latest docker dev build 1.0.0-beta.0

**Describe the bug**
Hi,
I had everything configured perfectly. All nodes were appearing with the correct manufacturer and product in the device list.
After a restart, I can see almost all nodes as Unknown manufacturer undefined. Tried to restart few times.
I was expected to see them all with the manufacturers that were before the restart.
Some of the devices show empty lines in the device list.
I have 40 zwave devices.
I hope I have enough information here, if something is missing, please let me know.

**Expected behavior**
All the devices should have loaded from the cache with their information.
Is this correct? is this get saved somewhere?

![Screen Shot 2021-01-16 at 9 05 33](https://user-images.githubusercontent.com/248898/104804304-06975480-57da-11eb-82a9-075b9c08728e.png)

**Comment by robertsLando** [comment]
So if you downgrade them are showed correctly? Could you send me a log output of both zwavejs and zwavejs2mqtt?

**Comment by rotem925** [comment]
What do you mean downgrade?
Also, can you point me to where I can find the logs please?

**Comment by robertsLando** [comment]
You find logs based on the logs settings you used in setting. If you have enabled the logToFile flag in settings them will be in store folder

**Comment by robertsLando** [comment]
With downgrade I mean if you try using a version before this one. Anyway does this only happens after restart so? This doesn't happen when you close and restart the entire docker container?

**Comment by rotem925** [comment]
See attached logs.
I've enabled it just now and then restarted the container.
So the logs were clean at startup.

> With downgrade I mean if you try using a version before this one. Anyway does this only happens after restart so? This doesn't happen when you close and restart the entire docker container?

Didn't try to downgrade...
I have restarted the container after a few hours. 
All nodes were queried fine prior to the restart, and where listed fine on the device list.
The problematic devices are battery devices (were Asleep on startup).

In which file should this be cached?

[zwavejs2mqtt.log](https://github.com/zwave-js/zwavejs2mqtt/files/5824234/zwavejs2mqtt.log)
[zwavejs_1.log](https://github.com/zwave-js/zwavejs2mqtt/files/5824235/zwavejs_1.log)

**Comment by SmartHomeNewbie** [comment]
same happend to one of my nodes, restarting cointainer didnt help but after a reboot of my whole system it back with all info-

**Comment by robertsLando** [comment]
Seems that we have figured out what's going on in #240 , please check updates on that

**Comment by rotem925** [comment]
Ok, thanks!
Will follow there. Will wait for this PT to be merged...
