### ISSUE TITLE
[Bug]: Icons not displaying correctly

### ISSUE THREAD

**Issue by jeffjumper** [zwave-js/zwavejs2mqtt#2564]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Zwavejs2Mqtt version

6.15.0

### ZwaveJS version

9.6.2

### Describe the bug

None of the icons are being displayed correctly in the UI.

<img width="1677" alt="Screen Shot 2022-08-02 at 9 12 22 AM" src="https://user-images.githubusercontent.com/47900427/182384252-8bddefee-bc6b-4118-a6f0-dda5ae8d2ed7.png">

These errors appear in the browser's console:

<img width="821" alt="Screen Shot 2022-08-02 at 9 20 42 AM" src="https://user-images.githubusercontent.com/47900427/182385381-edddcf4d-0d5d-48e9-ac9d-89ddc3da7d20.png">

### To Reproduce

Open the UI in a browser

### Expected behavior

Icons are displayed instead of text

**Comment by muddro1** [comment]
Noticed same thing in both Chrome and Firefox

**Comment by adamjernst** [comment]
Yep. material-design-icons.css.map is returning 404.

**Comment by JohnNeville** [comment]
I thought I was going crazy.

**Comment by robertsLando** [comment]
Sorry just saw this, not happening on my instance but only on production build, fixing it ASAP

**Comment by robertsLando** [comment]
6.15.1 is coming soon. Usually takes 1 hour to build

**Comment by robertsLando** [comment]
Build progress here: https://github.com/zwave-js/zwavejs2mqtt/runs/7635942465?check_suite_focus=true

**Comment by jeffjumper** [comment]
That fixed it. Thanks!
