### ISSUE TITLE
X-External-Path ignored

### ISSUE THREAD

**Issue by frenck** [zwave-js/zwavejs2mqtt#2568]
### Checklist

- [ ]  I am not using Home Assistant. Or: a developer has told me to come here.
- [ ] I have checked the troubleshooting section and my problem is not described there.
- [ ] I have read the changelog and my problem is not mentioned there.

### Deploy method

Manually built (git clone - yarn build - yarn install

### Zwavejs2Mqtt version

6.15.1

### ZwaveJS version

no relevant

### Describe the bug

Regression after v6.15.0 release caused this (described in #2564 as well).

![CleanShot 2022-08-04 at 16 16 15](https://user-images.githubusercontent.com/195327/182869615-a9fda767-9cdb-4e13-b9f2-d20b17c01bc9.png)

With the following console messages:

![CleanShot 2022-08-04 at 16 16 49](https://user-images.githubusercontent.com/195327/182869722-c5ac9837-f77f-464e-bd83-3231af720bcb.png)

However, that was fixed in 935a18d977d63087f4dcc6c6fd5a9d4e815e1e41, released with v6.15.1, which currently results in:

![CleanShot 2022-08-04 at 16 17 34](https://user-images.githubusercontent.com/195327/182869932-7ad8d71f-eff1-40a7-82c1-664913bebb3d.png)

Console messages:

![CleanShot 2022-08-04 at 16 17 58](https://user-images.githubusercontent.com/195327/182869995-cbf855a0-b168-4453-838c-6ec829d46651.png)

It seems that `X-External-Path` is completely ignored at this point.

### To Reproduce

Host Z-Wave JS behind a reverse proxy in a subfolder, passing the `X-External-Path` header, `FORCE_DISABLE_SSL=true`.

### Expected behavior

A UI.

**Comment by robertsLando** [comment]
Could you post here the nginx configuration you are using to proxy requests to zwavejs2mqtt?

**Comment by frenck** [comment]
<https://github.com/hassio-addons/addon-zwavejs2mqtt/blob/main/zwavejs2mqtt/rootfs/etc/nginx/templates/ingress.gtpl>

Full configuration here: <https://github.com/hassio-addons/addon-zwavejs2mqtt/blob/main/zwavejs2mqtt/rootfs/etc/nginx>

> What should be the url of the resources?

That differs per installation, but for the example:

here is a CSS request that does work correctly:

![CleanShot 2022-08-04 at 17 24 38](https://user-images.githubusercontent.com/195327/182885645-c11825a9-8c42-48b6-8110-21f2dd3c4cae.png)

(Partially makes out the token there)

**Comment by robertsLando** [comment]
I'm trying to reproduce the error on my side but seems that x-external-path is picked up correctly, are you sure that template is producing the correct nginx configuration and that x-external-path isn't left blank? If you open network tab does all css/js resources give 404 or only some of them?

**Comment by frenck** [comment]
Only some of them, see screenshot in the original issue posting.

I can produce it both manually and automated builds (from GitHub CI) on different systems.

**Comment by robertsLando** [comment]
I may have identified the root cause of the error,it's because I introduced lazy loading of main components, need to see if there is a way to tell vue how to load them correctly

**Comment by frenck** [comment]
Nice! ❤️

**Comment by robertsLando** [comment]
Could you give a try to linked PR? :)
