### ISSUE TITLE
[Bug]: Typo

### ISSUE THREAD

**Issue by thesebastianf** [zwave-js/zwavejs2mqtt#2573]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Zwavejs2Mqtt version

6.15.1

### ZwaveJS version

9.6.2

### Describe the bug

When checking to OTA Updates it says:

`Remember to weak up sleeping devices...`

### To Reproduce

UI: OTA

### Expected behavior

...wake...

**Comment by kpine** [comment]
Already fixed. https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v6.15.2
