### ISSUE TITLE
[feat] Have logging use time zone instead of UTC

### ISSUE THREAD

**Issue by kars85** [zwave-js/zwavejs2mqtt#2582]
https://github.com/zwave-js/node-zwave-js/issues/4088#issue-1104221784

**Is your feature request related to a problem? Please describe.**
Logging currently is in UTC format which is cumbersome when troubleshooting coordinating issues between UTC and actual user's time zone

**Describe the solution you'd like**
Have logging respect defined time zones (bare metal time, docker compose environment variable time zone, etc...)

**Additional context**
Added a request in the zwavejs github, but understand this is a zwavejs2mqtt change [here:](https://github.com/zwave-js/node-zwave-js/issues/4088#issue-1104221784)

**Comment by kpine** [comment]
It's already supported in z2m. Add the `TZ` environment variable to your configuration.

> Added a request in the zwavejs github, but understand this is a zwavejs2mqtt change https://github.com/zwave-js/node-zwave-js/issues/4088#issue-1104221784

I think you misunderstood the comments. The driver is hard-coded to use UTC time.

**Comment by robertsLando** [comment]
Thanks @kpine 🙏🏼
