### ISSUE TITLE
[feat] suggestions for OTA UI improvements

### ISSUE THREAD

**Issue by kpine** [zwave-js/zwavejs2mqtt#2583]
**Is your feature request related to a problem? Please describe.**
The OTA UI has a couple issues that could use improvement, IMO.

**Describe the solution you'd like**

First, it's more of an issue, but I'm lumping it together. The text in the version box overflows.

![image](https://user-images.githubusercontent.com/791794/183750279-875c7814-1692-4fc7-bf75-6faac219e5f2.png)

The main issue, is that the UI makes it too easy to accidentally perform a downgrade, if you aren't careful.

![image](https://user-images.githubusercontent.com/791794/183750418-44ca3ae5-a675-48d0-b498-d82a9b34ed21.png)

My switch is at v5.24, but z2m is prominently showing a version 5.22 that is available. I am making an assumption that z2m will show all versions, except for the current one (or maybe the API handles that, whatever...). I think there should be some sort of visual indication of older versions, versus new upgrades, as upgrading will be the more common action. Since the current version was far off on the right, I nearly tried to perform a downgrade.

I'm not proposing any particular UI design, just suggesting that there could be some improvement to distinguish older and newer upgrades, to support the most common use case of upgrading to new versions, not downgrading.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by robertsLando** [comment]
@kpine Thanks for your issue! That's really strange BTW! I only pass the node id and everything is handled by zwave-js.

@AlCalzone I think this may be a bug in fw updates service that doesn't fetch the correct versions?

**Comment by kpine** [comment]
Ah, I think you're right. If I call the API myself and pass in firmware version 5.22, it returns the single version 5.24. So it appears that the API should be returning the next upgrade version. If that's the case, I can submit a separate issue for the version problem.

**Comment by AlCalzone** [comment]
Supporting downgrades is intended. But it should be easier to spot that those are downgrades.

**Comment by robertsLando** [comment]
> But it should be easier to spot that those are downgrades.

Ok let me submit something for this

**Comment by robertsLando** [comment]
About downgrades I have opened an issue on fw updates repo, when implemented there I will add something on ui to highlight upgrades/downgrades
