### ISSUE TITLE
Most ADVANCED actions do not make sense for the controller

### ISSUE THREAD

**Issue by AlCalzone** [zwave-js/zwavejs2mqtt#2587]
I've highlighted them red:
![grafik](https://user-images.githubusercontent.com/17641229/184122534-73908f81-60b7-4bc3-b831-64be52cdbd00.png)

The firmware upgrade may become useful in the future but it will work differently than the OTA upgrade for nodes.

**Comment by robertsLando** [comment]
Them are just a way to make some operations faster, after you select one of them you will be asked to insert the nodeId.

Instead you should firstly find the node in the table, expand the row, click on advanced button

**Comment by AlCalzone** [comment]
Uh this is on the advanced actions button under the controller node. Not the one in the top corner.

**Comment by robertsLando** [comment]
Shit. 🤣

**Comment by robertsLando** [comment]
Fix is coming
