### ISSUE TITLE
[bug] UX issues for UI of selected nodes

### ISSUE THREAD

**Issue by ahochsteger** [zwave-js/zwavejs2mqtt#259]
**Version**

Build/Run method: Docker

zwavejs2mqtt version: 1.0.0-beta.0

**Describe the bug**

Currently I see a few UX issues for which I'd like to propose a solution and get some feedback before starting the implementation:

1. The UI specific to a selected node is located below the nodes table which causes a lot of scrolling up and down, if you have to do changes for a lot of nodes.
2. The node selection does not use the selection mechanism of v-data-table and has some bugs (e.g. de-selection by clicking on the selected node works does not reflect so in the UI).

**Expected behavior**

I'd propose the following changes to address these issues:

1. Use the [expandable rows](https://vuetifyjs.com/en/components/data-tables/#expandable-rows) feature and move all node-specific UI into the expanded row. This would also allow to see multiple node values in multiple expanded rows at once for comparison. E.g.:
![image](https://user-images.githubusercontent.com/207989/104843848-fdd37b00-58cc-11eb-8130-0529124b030e.png)

2. Use the [row selection](https://vuetifyjs.com/en/components/data-tables/#row-selection) feature that is available OOTB (using checkboxes). This also would allow for actions to be applied to selected nodes, if multi-select would be enabled in the future. E.g.:
![image](https://user-images.githubusercontent.com/207989/104843806-d41a5400-58cc-11eb-849d-eec88fc43145.png)

By using OOTB functionality of v-data-table I see the advantage that the implementation of zwavejs2mqtt can be simplified and maintenance improved. In addition the overall code quality is improved since it builds on well-tested functionality instead of re-implementing these features.

**Consequences**

* The selection would show up as a checkbox on the first column
* The node-specific UI would be moved completely into the expandable rows (shown as arrow buttons on the right).
* The node-specific UI would be able be shown simultaneously for multiple nodes.

**Comment by ahochsteger** [comment]
@robertsLando I'd be interested in your opinion to the proposed UI improvements.

**Comment by robertsLando** [comment]
@ahochsteger I think that the option 1 could be good but the things to show are a lot (there are also hass devices) and maybe the visualization could become even worst. I'm ok for option 2 but how do you handle the sent do multiple nodes? You should filter all the props that are in common like command classes valueids etc.

ATM I'm ok to use the row selection feature to replace the existing one, not sure about the other points, we should discuss about the final result

**Comment by ahochsteger** [comment]
@robertsLando thanks for your feedback, I'll create a branch so we can better discuss it.

**Comment by ahochsteger** [comment]
Here's a draft PR for the nodes table UI optimizations: https://github.com/zwave-js/zwavejs2mqtt/pull/332
