### ISSUE TITLE
[question] After unexpected power cut, most nodes are only partially working

### ISSUE THREAD

**Issue by Aephir** [zwave-js/zwavejs2mqtt#2595]
My power was unexpectedly cut, and after that happened, my Z-wave network mostly doesn't work.

I can't heal, but I can ping nodes. They only show very few of their "capabilities" (in home Assistant, I can see a `button.X_ping` and `sensor.X_node_status`, but nothing else. E.g. "switches" don't have any `switch.X` anymore. 

In the server "control-panel", I can see power usage (when updating under `Meter vundefined`), even when the node cannot successfully heal, and under status is just says `ProtocolInfo` (see example for a switch below, the `5.07 A` part updates
<img width="1566" alt="Screenshot 2022-08-15 at 08 10 11" src="https://user-images.githubusercontent.com/20152788/184585258-df78c38f-6b58-4d9d-b530-8539896c4128.png">

I'm using zwavejs2mqtt in a docker container (Version: 6.15.2).

I can provide a log file if needed, but it is very long, and I'm not sure what parts are relevant. 

Is there anything I can try to do to fix this, without factory resetting everything and starting over (and if not, what's best practice for doing the latter?)

**Comment by jmgiaever** [comment]
Hi,

It seems like your cache was corrupted. The node is in "Protocol info", which indicates that it's doing a re-interview to build that cache again. 

When a cache is corrupted and this re-interviews starts it will be high traffic on your network, so devices might become unresponsive. 

Wait until the re-interview process is done and they should act as normal. However, it might happen that some devices failed to interview (properly) and might not have all the properties it actually do have. Then you have to manually re-interview those nodes. 

For the future you should have a backup of your cache somewhere, when everything is back up, so you don't have to go through this process again in case of another power-loss.

**Comment by Aephir** [comment]
Hi,

Thanks for the hint. Any idea how long I should expect to wait?

I've been waiting about 30 hours now (with 10 devices, incl. the coordinator, in my network). I have also tried manually re-interviewing one (node 4) about four hours ago, but not much has changed yet; they all still show `ProtocolInfo`, and every device (except node 4) shows `?` for status.

In the logs (`docker logs`), I see that interview of each node failed. When I try manually re-interviewing node 4, I see

```
2022-08-15 16:45:03.548 ERROR ZWAVE: Interview of node 4 has failed: Attempt 1/5 failed
2022-08-15 16:45:09.780 ERROR ZWAVE: Interview of node 4 has failed: Attempt 2/5 failed
2022-08-15 16:45:21.017 ERROR ZWAVE: Interview of node 4 has failed: Attempt 3/5 failed
2022-08-15 16:45:37.248 ERROR ZWAVE: Interview of node 4 has failed: Attempt 4/5 failed
2022-08-15 16:45:58.479 ERROR ZWAVE: Interview of node 4 has failed: Maximum interview attempts reached
```

**Comment by jmgiaever** [comment]
Hi,

Have you tried to do a actually shutdown of the machine, not just the container (docker)?

It seems like the stick is stuck somehow, and a shutdown (power off, e.g `sudo shutdown -PH now` or similar) and boot up again. If it's a RPi or anything that will continue running, unplug the power.

When the power is off, detach and reattach the USB controller, before turning the computer on again.

**Comment by Aephir** [comment]
> It seems like the stick is stuck somehow

A full shutdown, unplugging both power supplies, unplugging and replugging the z-wave stick (aeotec gen 5; I accidentally pressed the button on it while it was unplugged, in case that ends up mattering), then replugging power and turning back on did the trick!

Thanks a lot!

**Comment by jmgiaever** [comment]
Great. I suspect that your stick was stuck and it just needed a cold boot. Maybe unplugging and re-plugging it, while z2m was stopped, would have been enough; you can try this the next time. 

It's just important that the zwave chip in the USB device will loose its power and has the chance to re-boot. 

But a complete shutdown is great if things doesn't work. 

Glad you fixed it!
