### ISSUE TITLE
[Bug]: Symlinks not attached to zip files

### ISSUE THREAD

**Issue by jmgiaever** [zwave-js/zwavejs2mqtt#2599]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Snap

### Zwavejs2Mqtt version

6.15.2.5c2434f

### ZwaveJS version

9.6.2

### Describe the bug

Selecting the zwavejs_current.log and then choose to download it would result in an empty zip. I guess its because this file is a symlink.

### To Reproduce

![image](https://user-images.githubusercontent.com/7188121/185936654-197318fc-58da-41f0-93e6-f75118c1d86b.png)

### Expected behavior

That the zip contained the linked file.

**Comment by robertsLando** [comment]
Ok just found the reason this is not working. It's actually not a file but a symbolic link to a file, for security reasons I'm not allowing that. You should just download the correct file it is pointing to (the last one created)

**Comment by robertsLando** [comment]
Fixed by #2611
