### ISSUE TITLE
[feat] Move logs to an subfolder of the store

### ISSUE THREAD

**Issue by jmgiaever** [zwave-js/zwavejs2mqtt#2600]
**Is your feature request related to a problem? Please describe.**
The store folder is starting to pile up and quite large, with a mix of files. 

**Describe the solution you'd like**
A log folder where logs are stored. Would be great if the corresponding `<hex>.audit.json` files could be moved out from the root of the store folder too.

This could possibly be set by the user itself with an env-var, if such a feature might break compability.

**Comment by robertsLando** [comment]
makes sense to me. Doing it asap! :)
