### ISSUE TITLE
[feat] built in prometheus metrics

### ISSUE THREAD

**Issue by onedr0p** [zwave-js/zwavejs2mqtt#2604]
**Is your feature request related to a problem? Please describe.**

Hi 👋🏼 

I would like to get notified if a device battery is low, or becomes unpair / unavailable. I already use prometheus and alertmanager so if zwavejs2mqtt could support this feature out of the box I could have alerts and metrics. There's a lot of people using prometheus and alertmanager so this would not only benefit me :)

**Describe the solution you'd like**

Build into zwavejs2mqtt something like https://github.com/kvaster/zwavejs-prom found in this issue https://github.com/zwave-js/zwavejs2mqtt/issues/1303

Thanks!

**Comment by robertsLando** [comment]
No problem, I could add it to deps so you just have to specify it in plugins to use it

**Comment by robertsLando** [comment]
@kvaster Is the plugin pèublished to npm? If not could you publish it to npm?

I could suggest to use `@zwave-js-ui/plugin-prometheus` as name

**Comment by kvaster** [comment]
@robertsLando, it's not yet published. I will do it in a one week as soon as I will settle in a new place...

**Comment by robertsLando** [comment]
Ok thanks! :)

**Comment by kvaster** [comment]
Published to: https://www.npmjs.com/package/@kvaster/zwavejs-prom

**Comment by robertsLando** [comment]
Thanks @kvaster ! :)

**Comment by onedr0p** [comment]
@robertsLando and @kvaster much appreciated on this. Thanks for the quick turn around!

**Comment by robertsLando** [comment]
Available in 7.1.0 🚀
