### ISSUE TITLE
[question]  zwavejs2mqtt container starts then shuts down on reboot

### ISSUE THREAD

**Issue by stevebus** [zwave-js/zwavejs2mqtt#2613]
I'm running zwavejs2mqtt in a docker container managed by docker compose (file below).  My configuration is very simple in terms of devices as I'm just getting started.

When I bring the containers up and down manually (via docker compose up and down), I have no problems and everything works as it should.  However, upon reboot, zwavejs2mqtt container starts (and thus home-assistant, which 'depends' on it starts too), but after all the initialization is done, zwavejs2mqtt container shuts itself down (or more accurately, per the logs, it seems to think that something else has asked it to shut down).  Docker makes no attempt to restart it.  I can manually go in and bring it right back up with no problems, but obviously I want it to come up automatically after a restart.

from zwavejs2mqtt logs:
![image](https://user-images.githubusercontent.com/11857454/187536055-db2b9c30-19f0-46e0-a23d-fb47ecfeff82.png)

The previous log entries all look 'normal' to me.  You can see from the WARN line, it has detected a shutdown..  but I have no idea why.

This is my docker compose file:

version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /home/stevebus/homeassist:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
    depends_on:
      - zwavejs2mqtt

  zwavejs2mqtt:
    container_name: zwavejs2mqtt
    image: zwavejs/zwavejs2mqtt:latest
    restart: unless-stopped
    stop_signal: SIGINT
    tty: true
    devices:
      - /dev/serial/by-id/usb-Silicon_Labs_Zooz_ZST10_700_Z-Wave_Stick_0001-if00-port0:/dev/ttyACM0
    volumes:
      - /home/stevebus/zwavejs2mqtt/store:/usr/src/app/store
    ports:
      - 8091:8091
      - 3000:3000
    environment:
      TZ: 'America\Chicago'

  esphome:
      container_name: esphome
      image: esphome/esphome
      privileged: true
      volumes:
        - '/home/stevebus/esphome:/config:rw'
      network_mode: host
      restart: unless-stopped

Any ideas?

**Comment by stevebus** [comment]
Actually, as I dig a little deeper, based on the log timestamps, the above 'shutdown' messages are from the reboot...  it appears that docker never gets the container running enough for it to log anything after the reboot (but HA, which 'depends' on it, does start)

I also found this in the docker daemon logs (journalctl)

Aug 30 15:31:42 nuc1 dockerd[713]: time="2022-08-30T15:31:42.647052938-05:00" level=error msg="65eb4d8ab7c6a1504610736cf0dcce04f2dfcbde94debfd24a5471cb190314bc cleanup: failed to delete container from containerd: no such container"
Aug 30 15:31:42 nuc1 dockerd[713]: time="2022-08-30T15:31:42.649471130-05:00" level=error msg="failed to start container" container=65eb4d8ab7c6a1504610736cf0dcce04f2dfcbde94debfd24a5471cb190314bc error="error gathering device information while adding custom device \"/dev/serial/by-id/usb-Silicon_Labs_Zooz_ZST10_700_Z-Wave_Stick_0001-if00-port0\": no such file or directory"
Aug 30 15:31:44 nuc1 dockerd[713]: time="2022-08-30T15:31:44.765254308-05:00" level=info msg="Loading containers: done."

So maybe docker is trying to start the container before the USB stick is available?  Is there a way to make it wait?

**Comment by stevebus** [comment]
Closing my own issue because I now know it's a general docker device dependency issue and not a zwavejs2mqtt issue.   FWIW (for others), i just put a systemd-level delay on of 60 seconds on the docker daemon per this thread (using ExecPreStart) ->  https://www.reddit.com/r/docker/comments/ke3twe/how_to_delay_the_start_of_a_container_at_system/ and that worked

**Comment by robertsLando** [comment]
Another possible solution could be to change the stop signal but that could lead to other unexpected errors. 
The problem here as you find out is that docker starts right before the usb stick is mounted and this causes docker to fail the startup when it tries to map that device to `/dev/ttyACM0`

**Comment by stevebus** [comment]
Yeah, I agree.   I think the work around of just having the delay is sufficient for me for now.  I know it's not 100% reliable, but seems ok.  

The interesting thing about the docker failure is that the container starts "enough" for the 'depends' relationship for the HA container to start, but not enough for zwavejs2mqtt to log anything, which I assume it does (haven't looked at the code) nearly immediately upon entry.  i.e. my guess is that the docker startup of that module never even makes it to the entry point (fails at the resource mapping stage).   So I'm left with a module with a docker dependency on another module that starts, while the dependency has failed to start.  Seems like a nice little bug/gap in the docker dependency logic.

**Comment by robertsLando** [comment]
> Seems like a nice little bug/gap in the docker dependency logic.
