### ISSUE TITLE
How to use Parse send

### ISSUE THREAD

**Issue by markruys** [zwave-js/zwavejs2mqtt#2626]
I've a [NAS-WR01ZE](https://github.com/zwave-js/node-zwave-js/issues/2692) for which I want to fix the MSB. MQTT sub shows:

```shell
markr@Yavin4:~$ mosquitto_sub -h alderaan.paracas.nl -u domoticz -p 1883 -P xxx  -t 'zwave/11/50/0/value/65537' -v
zwave/11/50/0/value/65537 {"time":1662221570016,"value":-21474833.6,"nodeName":"Leeslamp","nodeLocation":"Woonkamer"}
```

I want to fix the :-21474833.6 value, and it seems that Devices values configuration should work.  I added an item:

- Selected the correct device
- Selected "Electric consumption (kWh)" as value
- Selected "energy" as device class (leaving it empty gives similar results)
- Enabled Parse Send
- Entered "return 999;" in the text box

I would expect to get "999" in the MQTT subscription, but it doesn't. What am I missing here?

**Comment by markruys** [comment]
Ah, I forgot to click on Save at the bottom.

**Comment by markruys** [comment]
BTW, this is sooo nice. This is how to get reasonable readings kWh from this el cheapo wall plug:
```javascript
return Math.round(((value * 100) & 0x7fffffff) * 0.26) / 100;
```

I got the correction factor 0.26 from https://gist.github.com/KloudJack/4489ffcbeae58b88072f391dca55b40d.

**Comment by robertsLando** [comment]
Glad you like it @markruys 🎉
