### ISSUE TITLE
[question] 7.x changes behavior or Aeotec door/window sensors (ZWA187 and ZWA008)

### ISSUE THREAD

**Issue by drizuid** [zwave-js/zwavejs2mqtt#2638]
Hello, I just finished running through some tests to verify my findings. I tested a Zooz S2 ZST10 500 and Zooz S2 ZST10 700 stick with zwavejs2mqtt 6.16 and 7.x (both 7.0 and 7.1).

In my testing, with 6.x `5-113-0-Access Control-Door state` would reflect [23] Window/door is closed or [22] Window/door is open. In Home assistant, this would also expose `access_control_door_open` which had an `on` or `off` state to home assistant (core). Moving to 7.x now gives `access_control_door_state` which has a `22` or `23 Door/window is closed` state.  

Oddly enough, 22 under 7.x never shows Window/door is open in the zwavejs2mqtt web ui, while in 6.x it would show the words, not just the numeric state. 

My question is, is this the new and intended behavior for door/window sensors (the same issue presents on both my recessed door sensor 7 (ZW187) and my windows sensor 7 pro (ZWA008)). I am happy to provide some logs if anyone has any that will be the most useful. I have no problem flipping back and forth between 6.x and 7.x during testing. (though i'll stay on the zst 10 500 stick for now due to some quirky issues with the 700)

thanks in advance for all you guys do :)

**Comment by drizuid** [comment]
I believe I may have found my mistake. Under the binary sensorv2 there is now 5-48-0-Door/Window which will show false when closed and true when open. So looks like just a change in location and which code I need to pay attention to. I will dig in and see if this is correct.

**Comment by drizuid** [comment]
to add some missing details, on 6.16.0 the binary sensor for the ZWA0008 is still just the tilt sensor, but the `8-113-0-Access Control-Door state` shows `[23] Window/Door is closed` and `[22] Window/Door is open` this is really the only difference I'm seeing. (7.x shows `[23] Window/Door is closed` and `[22]`)

**Comment by drizuid** [comment]
Great news and I'm glad I'm not just crazy. I'm building the container from master now to test out! thank you!

**Comment by robertsLando** [comment]
Feel free to close this if it's fixed

**Comment by drizuid** [comment]
I'm not seeing a change in the behavior I've described with the updated node-zwave-js, but I can work around the issues manually or by going back to 6.16, so I am good to go on my question as it seems the changes are indeed by design. thank you all for all you do!
<img width="142" alt="image" src="https://user-images.githubusercontent.com/40674481/189720819-a4e708fa-7024-46e2-aa8e-045ccf345590.png">
