### ISSUE TITLE
Door/window sensor issues in zwave-js 10.0.4

### ISSUE THREAD

**Issue by doug-hoffman** [zwave-js/zwavejs2mqtt#2653]
Door/window sensors are very broken in zwave-js 10.0.4. They're fixed in zwave-js/node-zwave-js#5037, which is included in 10.1.0. Please release an update with #2643.

Related issues:

zwave-js/node-zwave-js#5027
hassio-addons/addon-zwavejs2mqtt#409

**Comment by robertsLando** [comment]
Released 7.2.0
