### ISSUE TITLE
[bug] Sending '000000' to new hexColor yields error

### ISSUE THREAD

**Issue by LordMike** [zwave-js/zwavejs2mqtt#269]
**Version**

Build/Run method
- [x] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build ) 

zwavejs2mqtt version: `dev`, with new hexColor valueId

**Describe the bug**
The new hass templates indicated to me the format of the RGB value was all hex, ie `112233`, and not as with Z2M: `#112233`. So I went with this.

Sending f.ex. `ffffff` turns a light all white, but conversely `000000` yields an error. It's interpreted as a number. 

**To Reproduce**
1. Send `000000` to `zwavejs2mqtt/NAME/51/1/hexColor/set`
2. Observe error in logs and no color change

**Expected behavior**
Value is interpreted as hexadecimal value, and lights turn off.

**Additional context**
Log of error:
![image](https://user-images.githubusercontent.com/1027111/104973375-d2e44680-59f4-11eb-87fe-b7f30d8440aa.png)

Log of success:
![image](https://user-images.githubusercontent.com/1027111/104973421-f3ac9c00-59f4-11eb-89d8-466fabf70003.png)

**Comment by LordMike** [comment]
I'm workarounding this by sending `#000000`, which works like in Z2M. Luckily, `#FFFFFF` also works, so all my values will be with a hashtag :).

**Comment by LordMike** [comment]
@robertsLando you can optimize the template here, by not parsing the value as hexadecimal, to present as integers ... you can just return hexadecimal :)

F.ex., `{{ value_json.value[0:2] | int(0, 16) }},{{ value_json.value[2:4] | int(0, 16) }},{{ value_json.value[4:6] | int(0, 16) }}` can become: `#{{ value_json.value }}`

https://github.com/zwave-js/zwavejs2mqtt/blob/fe2c214f3b2270c5671f761e8818b26850dbe970/hass/configurations.js#L164

**Comment by robertsLando** [comment]
> F.ex., {{ value_json.value[0:2] | int(0, 16) }},{{ value_json.value[2:4] | int(0, 16) }},{{ value_json.value[4:6] | int(0, 16) }} can become: #{{ value_json.value }}

Are you sure about that? Did you tested it in hass?

@LordMike about the issue, are you sending the value from mqtt or from the ui?

**Comment by LordMike** [comment]
I tested it in HASS - and the colors changed on my lights, but I _am_ seeing logs that indicate it doesn't work.. So I'm not sure why the color changes I see, happen.. :|
