### ISSUE TITLE
[bug] node process exit when saving config.

### ISSUE THREAD

**Issue by billiaz** [zwave-js/zwavejs2mqtt#27]
**Version**

Build/Run method
- [x] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build ) 

zwavejs2mqtt version: master

When saving the configuration on zwavejs2mqtt web interface process exits

running npm with trace-exit
```
Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:208:20)
18:27:41.267 DRIVER   destroying driver instance...
18:27:41.269 DRIVER   destroying driver instance...
18:27:41.270 DRIVER   destroying driver instance...
(node:66) WARNING: Exited the environment with code 1
    at exit (internal/process/per_thread.js:172:13)
    at /usr/src/app/node_modules/@sentry/node/dist/handlers.js:231:24
    at onfulfilled (/usr/src/app/node_modules/@sentry/utils/dist/syncpromise.js:138:33)
    at /usr/src/app/node_modules/@sentry/utils/dist/syncpromise.js:67:33
    at SyncPromise._executeHandlers (/usr/src/app/node_modules/@sentry/utils/dist/syncpromise.js:60:28)
    at SyncPromise._setResult (/usr/src/app/node_modules/@sentry/utils/dist/syncpromise.js:45:19)
    at SyncPromise._resolve (/usr/src/app/node_modules/@sentry/utils/dist/syncpromise.js:28:19)
    at onfulfilled (/usr/src/app/node_modules/@sentry/utils/dist/syncpromise.js:138:25)
    at /usr/src/app/node_modules/@sentry/utils/dist/syncpromise.js:67:33
    at SyncPromise._executeHandlers (/usr/src/app/node_modules/@sentry/utils/dist/syncpromise.js:60:28)
/usr/src/app #zwavejs2mqtt 
```
i receive as error

**Comment by robertsLando** [comment]
> 18:27:41.267 DRIVER   destroying driver instance...
18:27:41.269 DRIVER   destroying driver instance...
18:27:41.270 DRIVER   destroying driver instance...

I don't understand why there are 3 logs, like that, also seems something related to `@sentry` module used by zwave-js, @AlCalzone do you have any idea?

**Comment by AlCalzone** [comment]
The destroying driver instance **should** be no problem, but we can just avoid executing the method multiple times.

About sentry: I haven't seen that warning before. It is probably because it was trying to send an error log while shutting down the process.

**Comment by robertsLando** [comment]
The problem is that based on what @billiaz said to me that caused the process to exit

**Comment by AlCalzone** [comment]
Sentry should do nothing **until** a fatal error occurs (or I tell it to capture a message).
So it is more likely that something crashed, sentry tries to capture the error, then calls `process.exit(1)`.

**Comment by robertsLando** [comment]
Ok what I'm missing so is that fatal error, cannot see any stack trace of that and that's why I don't understand where it's coming from :confused: 

@billiaz Does this happens EVERY time you save new settings?

**Comment by billiaz** [comment]
@robertsLando noticed it happens 99% of the times.

**Comment by AlCalzone** [comment]
That does sound like something crashes. I've never seen the warning before

**Comment by billiaz** [comment]
i had to run and get this using the --trace-exit command or something similar in node, otherwise logs where giving nothing.

**Comment by AlCalzone** [comment]
Any chance to narrow down where the error is coming from? E.g. an unhandledException handler in z2m? @robertsLando

**Comment by robertsLando** [comment]
@billiaz Could try with https://github.com/zwave-js/zwavejs2mqtt/pull/32 ?

**Comment by AlCalzone** [comment]
@robertsLando did you find out whats happening?

**Comment by robertsLando** [comment]
@AlCalzone Not sure but I'm trying :)

**Comment by robertsLando** [comment]
Now it's fixed :tada:
