### ISSUE TITLE
[question] Creating custom "climate" device

### ISSUE THREAD

**Issue by ivdimitro** [zwave-js/zwavejs2mqtt#270]
In zwave2MQTT i had created custom configuration for Aeotec TRV (SPIRIT ZWAVE PLUS). But unfortunately i can't migrate the configuration. I have tried two different customDevices.json files but both of them throw different error: 

> [customDevices.json.migrated](https://github.com/ivdimitro/node-zwave-js/blob/wrong_custom_files/customDevices.json.migrated) the error is: 

 ```
zwaveJS2mqtt    | 2021-01-19 01:46:27.382 ERROR GATEWAY: Error while discovering device climate_thermostat of node 8: Cannot read property 'id' of undefined Cannot read property 'id' of undefined
zwaveJS2mqtt    | TypeError: Cannot read property 'id' of undefined
zwaveJS2mqtt    |     at Gateway.valueTopic (/usr/src/app/lib/Gateway.js:879:23)
zwaveJS2mqtt    |     at Gateway.discoverDevice (/usr/src/app/lib/Gateway.js:1147:16)
zwaveJS2mqtt    |     at /usr/src/app/lib/Gateway.js:360:40
zwaveJS2mqtt    |     at Array.forEach (<anonymous>)
zwaveJS2mqtt    |     at Gateway.onNodeStatus (/usr/src/app/lib/Gateway.js:360:17)
zwaveJS2mqtt    |     at ZwaveClient.emit (events.js:314:20)
zwaveJS2mqtt    |     at ZwaveClient.EventEmitter.emit (domain.js:483:12)
zwaveJS2mqtt    |     at ZwaveClient.onNodeStatus (/usr/src/app/lib/ZwaveClient.js:270:10)
zwaveJS2mqtt    |     at ZwaveClient.onNodeReady (/usr/src/app/lib/ZwaveClient.js:310:16)
zwaveJS2mqtt    |     at ZWaveNode.emit (events.js:326:22)
zwaveJS2mqtt    |     at ZWaveNode.EventEmitter.emit (domain.js:483:12)
zwaveJS2mqtt    |     at ZWaveNode.onReadyChange (/usr/src/app/node_modules/zwave-js/src/lib/node/Node.ts:420:19)
zwaveJS2mqtt    |     at /usr/src/app/node_modules/zwave-js/src/lib/node/Node.ts:214:10
zwaveJS2mqtt    |     at Interpreter.update (/usr/src/app/node_modules/xstate/lib/interpreter.js:253:17)
zwaveJS2mqtt    |     at /usr/src/app/node_modules/xstate/lib/interpreter.js:125:23
zwaveJS2mqtt    |     at Scheduler.process (/usr/src/app/node_modules/xstate/lib/scheduler.js:60:13)
```

> [customDevices.json.single_entity](https://github.com/ivdimitro/node-zwave-js/blob/wrong_custom_files/customDevices.json.single_entity)

```
`zwaveJS2mqtt    | 2021-01-19 01:48:42.857 ERROR GATEWAY: Unable to discover climate device. nodeDevices.push is not a function
zwaveJS2mqtt    | TypeError: nodeDevices.push is not a function
zwaveJS2mqtt    |     at Gateway.discoverClimates (/usr/src/app/lib/Gateway.js:1405:17)
zwaveJS2mqtt    |     at Gateway.onNodeStatus (/usr/src/app/lib/Gateway.js:357:10)
zwaveJS2mqtt    |     at ZwaveClient.emit (events.js:314:20)
zwaveJS2mqtt    |     at ZwaveClient.EventEmitter.emit (domain.js:483:12)
zwaveJS2mqtt    |     at ZwaveClient.onNodeStatus (/usr/src/app/lib/ZwaveClient.js:270:10)
zwaveJS2mqtt    |     at ZwaveClient.onNodeReady (/usr/src/app/lib/ZwaveClient.js:310:16)
zwaveJS2mqtt    |     at ZWaveNode.emit (events.js:326:22)
zwaveJS2mqtt    |     at ZWaveNode.EventEmitter.emit (domain.js:483:12)
zwaveJS2mqtt    |     at ZWaveNode.onReadyChange (/usr/src/app/node_modules/zwave-js/src/lib/node/Node.ts:420:19)
zwaveJS2mqtt    |     at /usr/src/app/node_modules/zwave-js/src/lib/node/Node.ts:214:10
zwaveJS2mqtt    |     at Interpreter.update (/usr/src/app/node_modules/xstate/lib/interpreter.js:253:17)
zwaveJS2mqtt    |     at /usr/src/app/node_modules/xstate/lib/interpreter.js:125:23
zwaveJS2mqtt    |     at Scheduler.process (/usr/src/app/node_modules/xstate/lib/scheduler.js:60:13)
zwaveJS2mqtt    |     at Scheduler.schedule (/usr/src/app/node_modules/xstate/lib/scheduler.js:44:14)
zwaveJS2mqtt    |     at Proxy.Interpreter.send (/usr/src/app/node_modules/xstate/lib/interpreter.js:121:29)
zwaveJS2mqtt    |     at ZWaveNode.onStatusChange (/usr/src/app/node_modules/zwave-js/src/lib/node/Node.ts:362:21)
```

Around the Node Id discovery code I found comments "// TODO: Zwavejs doesn't support polling right now"
So I am not sure if adding custom climate devices is supported at all or am I messing up mu json files. 
Thanks for the help.

**Comment by robertsLando** [comment]
Hi @ivdimitro, in docs I have explained that the old devices need to be translated: https://zwave-js.github.io/zwavejs2mqtt/#/guide/migrating

Anyway now climate devices should be automatically discovered. Could you try to remove it from customDevices and see if it's discovered?

**Comment by ivdimitro** [comment]
Hi, the auto discovery of "climate" works OK. The issue is with applying the customDevices.json. I want to expose the valve control of the thermostat and a few values as stand alone sensors. 
From the error message "Cannot read property 'id' of undefined Cannot read property 'id' of undefined" I can't understand what id it is missing. The "device ID" is clearly visible in the GUI and is the same as the one in the json. 
Also in the begging of the trace it is visible that the json is parsed and the device is discovered: 
`zwaveJS2mqtt    | 2021-01-19 09:51:50.612 INFO GATEWAY: Loading custom devices from /usr/src/app/store/customDevices.json
zwaveJS2mqtt    | 2021-01-19 09:51:50.618 INFO GATEWAY: Loaded 1 custom Hass devices configurations`

So I am not sure what ID I need to specify in order to map to the custom device?

**Comment by robertsLando** [comment]
> The issue is with applying the customDevices.json

Send me the template you used so we can check. Anyway that errors about the undefined id means that a value id in your template is wrong

**Comment by ivdimitro** [comment]
Here is template which can not add the climate object but adds the "cover" and the sensors. The topics for the cover and the sensors are not corrected as I stuck on the climate which should be correct. 
[tempalte](https://github.com/ivdimitro/node-zwave-js/blob/wrong_custom_files/customDevices.json.migrated)

**Comment by robertsLando** [comment]
```
 "67-0-setpoint-heat",
 "67-0-setpoint-eco"
```

This are wrong, if you check your valueids you will not find this ids in control panel. `heat` and `eco` should be a number property, `heat` it's `1` eco I don't remember. Check the thermostat setpoint cc in control panel and copy the value ids you see there

**Comment by ivdimitro** [comment]
Thanks for the quick reply. I thought I can define more human readable values.

**Comment by robertsLando** [comment]
@ivdimitro I don't decide the valueIds, those come from zwave-js

**Comment by ivdimitro** [comment]
Thanks for the help, everything works as before.

**Comment by maivorbim** [comment]
Hi @ivdimitro 

Could you please explain how to expose valve percentage control and set manufacturer specific mode on the TRV? I have tried contacting you via PM on Home Assistant forum. Sorry for writing on a closed thread. Thanks
