### ISSUE TITLE
[question] Fibaro roller shutter unable to control using MQTT

### ISSUE THREAD

**Issue by Pentelfrost** [zwave-js/zwavejs2mqtt#275]
Not sure if this is a bug or user error on my part.

I've got a Fibaro roller shutter which I included correctly and I am able to control it from the web interface just fine. It shows up as a dimmer and a switch both of which operate as expected.

My MQTT broker gets topics added which match what is expect and I can see currentValue for both and it looks to be correct.
It also publishes the correct HASS device discovery messages so it shows up in home assistant. However the switches in home assistant don't do anything.

On further investigation I notice that I don't have matching targetValue topics for this node on either the dimmer or the switch.

In the home assistant config message I see the command topic as zwavejs2mqtt/Cinema_Screen/38/0/targetValue/set however publishing any value to this topic does nothing.

I have a bunch of actual dimmers and switches (manufactured by zwave.me) which all have similar topics but they all have a corresponding targetValue topic and publishing to targetValue/set works as expected.

Did I miss a step or do something wrong? If not and it is a bug, what information or logs would be helpful in this case.

**Comment by Pentelfrost** [comment]
Also I'm running this using the docker container which I deployed a couple of days ago.

**Comment by robertsLando** [comment]
@Pentelfrost Firstly try to use latest `dev` docker container. Then also attach some logs here when you send commands so I can see what's happening

**Comment by Pentelfrost** [comment]
Actually I'm going to close this. Late last night I pulled the docker container again using latest and now I see the correct topics under zwavejs2mqtt/Cinema_Screen/38/0/ one of which is targetValue and now publishing a set value correctly passes through to the device.
