### ISSUE TITLE
[bug] Marking excluded node as failed, yields error

### ISSUE THREAD

**Issue by LordMike** [zwave-js/zwavejs2mqtt#277]
**Version**

Build/Run method
- [x] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build ) 

zwavejs2mqtt version: d98fd7e8541a722b89a0e65fcfaca14b6b589cb2

**Describe the bug**
I excluded a node, and wanted to re-include it with the same id. Couldn't do that, as the replace failed required it to be failed - so I used "mark node as failed". That in turn errored out. I have not tested marking a working node as failed.

```
zwavejs2mqtt_1  | 2021-01-19 18:17:41.975 INFO ZWAVE: Node 28: value added 28-38-5-duration => [Duration: 0seconds]
zwavejs2mqtt_1  | 2021-01-19 18:17:42.361 INFO ZWAVE: Node 28: value added 28-38-5-currentValue => 99
zwavejs2mqtt_1  | 2021-01-19 18:17:42.362 INFO ZWAVE: Node 28: value added 28-38-5-Up => undefined
zwavejs2mqtt_1  | 2021-01-19 18:17:42.362 INFO ZWAVE: Node 28: value added 28-38-5-Down => undefined
zwavejs2mqtt_1  | 2021-01-19 18:17:42.365 INFO ZWAVE: Node 28 ready: Logic Group - ZDB5100 (MATRIX Switch with Dimmer and Backlight)
zwavejs2mqtt_1  | 2021-01-19 18:17:42.372 INFO APP: Zwave api call: markNodeAsFailed [ 20, [length]: 1 ]
zwavejs2mqtt_1  | 2021-01-19 18:17:42.373 INFO ZWAVE: this.driver.controller.markNodeAsFailed is not a function markNodeAsFailed
zwavejs2mqtt_1  | 2021-01-19 18:17:42.715 INFO ZWAVE: Node 30 is alive
zwavejs2mqtt_1  | 2021-01-19 18:17:43.074 INFO ZWAVE: Node 30: value added 30-91-0-slowRefresh => true
zwavejs2mqtt_1  | 2021-01-19 18:17:43.074 INFO ZWAVE: Node 30: value added 30-91-0-scene-001 => undefined
zwavejs2mqtt_1  | 2021-01-19 18:17:43.074 INFO ZWAVE: Node 30: value added 30-91-0-scene-002 => undefined
zwavejs2mqtt_1  | 2021-01-19 18:17:43.075 INFO ZWAVE: Node 30: value added 30-91-0-scene-003 => undefined
zwavejs2mqtt_1  | 2021-01-19 18:17:43.075 INFO ZWAVE: Node 30: value added 30-91-0-scene-004 => undefined
```

![image](https://user-images.githubusercontent.com/1027111/105076105-f063ef80-5a8a-11eb-912e-5294a9dd4431.png)

**To Reproduce**
N/A

**Expected behavior**
Function fails because the node is excluded properly, or works, and fails an excluded node.

**Additional context**
N/A

**Comment by robertsLando** [comment]
@LordMike I think that the actual zwave js version still doesn't have the api?

**Comment by LordMike** [comment]
Exciting - it's _that_ new? :)

If so - we can just close this.

**Comment by robertsLando** [comment]
@LordMike It has been removed after some thoughts, check #289
