### ISSUE TITLE
[question] GE fan switches

### ISSUE THREAD

**Issue by towerhand** [zwave-js/zwavejs2mqtt#280]
This is the Hass device JSON that was created by zjs2m for the GE fan I have, which doesn't work with HA.
```
{
  "type": "fan",
  "object_id": "dimmer",
  "values": [
    "38-0-currentValue",
    "38-0-targetValue"
  ],
  "discovery_payload": {
    "command_topic": "zwave2jsmqtt/master_bedroom_fan/38/0/currentValue/set",
    "speed_command_topic": "zwave2jsmqtt/master_bedroom_fan/38/0/targetValue/set",
    "speed_state_topic": "zwave2jsmqtt/master_bedroom_fan/38/0/currentValue",
    "state_topic": "zwave2jsmqtt/master_bedroom_fan/38/0/currentValue",
    "speeds": [
      "off",
      "low",
      "medium",
      "high"
    ],
    "payload_low_speed": 24,
    "payload_medium_speed": 50,
    "payload_high_speed": 99,
    "payload_off": 0,
    "payload_on": 255,
    "state_value_template": "{% if (value_json.value | int) == 0 %} 0 {% else %} 255 {% endif %}",
    "speed_value_template": "{% if (value_json.value | int) == 0 %} 0 {% elif (value_json.value | int) <= 32 %} 24 {% elif (value_json.value | int) <= 66 %} 50 {% elif (value_json.value | int) <= 99 %} 99 {% endif %}",
    "device": {
      "identifiers": [
        "zwavejs2mqtt_0x_node17"
      ],
      "manufacturer": "GE/Jasco",
      "model": "In-Wall Smart Fan Control (ZW4002)",
      "name": "master_bedroom_fan",
      "sw_version": "5.22"
    },
    "name": "master_bedroom_fan_dimmer",
    "unique_id": "zwavejs2mqtt_0x_Node17_dimmer"
  },
  "discoveryTopic": "fan/master_bedroom_fan/dimmer/config",
  "persistent": false,
  "ignoreDiscovery": false,
  "id": "fan_dimmer"
}
```

After changing the "command_topic" to "targetValue/set" seems to work for turning it on and off in HA and showing "99" as a Current value in the Multilevel switch info for the node (in zjs2m) but changing the speed shows 19 for low and 38 for medium instead of the 24 and 50 like the in the JSON.

So I'm just wondering if I need to change anything else to make this fan switch work properly.

**Comment by robertsLando** [comment]
@towerhand That's a typo, fixing now, about the payload check: https://www.home-assistant.io/integrations/fan.mqtt/

COuld you try to set it as a string instead of a number? Unfortunally I don't have a fun to test so you should try to fix the template your own then I can fix it on my side once you find a working one. ATM I will fix the command template

**Comment by robertsLando** [comment]
Here is the fix: 0d0fbd678070dc2e979a809363815628b5a8a5d8

**Comment by towerhand** [comment]
Looks like the same is happening with the dimmers, for example I have the outside lights to turn on at brightness 62 and 255 depending if there’s motion or not, but it’s not activating the right value (9 and 38 instead).I think It’s due to a newer change, I think I would have noticed earlier otherwise.

**Comment by towerhand** [comment]
Which is the same as #285 so we can close this issue, I just stumbled on the same problem when trying to get my fan switch to work.

**Comment by towerhand** [comment]
> Here is the fix: [0d0fbd6](https://github.com/zwave-js/zwavejs2mqtt/commit/0d0fbd678070dc2e979a809363815628b5a8a5d8)

The docs have the same typo in the custom component fan example.
https://zwave-js.github.io/zwavejs2mqtt/#/guide/homeassistant

**Comment by robertsLando** [comment]
This is fixed in #290 . COuld you give it a try?

**Comment by towerhand** [comment]
I’ll try testing in a few hours when I get home if know else beat me to it.

**Comment by towerhand** [comment]
Looks like someone already confirmed this fix works. Thanks.
