### ISSUE TITLE
Unable to run via docker - manifest unknown

### ISSUE THREAD

**Issue by petrovcicklemen** [zwave-js/zwavejs2mqtt#29]
While attempting to run the platform via docker, the following message is printed out:

```
root@klemen-VirtualBox:/home/klemen# docker run --rm -it -p 8091:8091 --device=/dev/ttyS0 --mount source=zwavejs2mqtt,target=/usr/src/app/store zwavejs/zwavejs2mqtt:latest
Unable to find image 'zwavejs/zwavejs2mqtt:latest' locally
docker: Error response from daemon: manifest for zwavejs/zwavejs2mqtt:latest not found: manifest unknown: manifest unknown.
See 'docker run --help'.
```

**Comment by robertsLando** [comment]
@petrovcicklemen If you check dockerhub, there isn't a `latest` tag yet as there isn't any release, use `dev` tag for now :)

**Comment by petrovcicklemen** [comment]
> @petrovcicklemen If you check dockerhub, there isn't a `latest` tag yet as there isn't any release, use `dev` tag for now :)

Already am. Just wanted to alert you to this, since the instructions point to the `latest` tag.

**Comment by robertsLando** [comment]
@petrovcicklemen You right, sorry for this
