### ISSUE TITLE
[question] is the information on node state transmitted via mqtt?

### ISSUE THREAD

**Issue by dvbit** [zwave-js/zwavejs2mqtt#292]
Is there a way to know if a device is unavailable , in sleep state or dead via mqtt?

**Comment by LordMike** [comment]
There is this setting in the settings page:

![image](https://user-images.githubusercontent.com/1027111/105247764-9e4bc880-5b75-11eb-8468-cfcc565309f7.png)

So I'd think yes, since you can disable it. Have you looked at the topics available?

**Comment by LordMike** [comment]
On my mqtt server, I get these topics:

![image](https://user-images.githubusercontent.com/1027111/105248055-0b5f5e00-5b76-11eb-8bfa-515cfcf7f67b.png)

**Comment by robertsLando** [comment]
Thanks @LordMike
