### ISSUE TITLE
[feat] Avoid issuing noop-commands

### ISSUE THREAD

**Issue by LordMike** [zwave-js/zwavejs2mqtt#296]
**Is your feature request related to a problem? Please describe.**
I have a light-dimming thingy that gradually changes light brightness during the day, it works through HASS by setting the brightness on lights it controls. HASS then in turn sends the command to zwavejs2mqtt, but since HASS doesn't check if the brightness being set is the same as it was already, it sometimes sends commands that don't actually make sense.

This snippet from zwave-js just passed by me, as I was looking for something else.

```
23:40:08.540 CNTRLR   [Node 046] [~] [Multilevel Switch] targetValue: 15 => 15          [Endpoint 5]
23:40:08.543 CNTRLR   [Node 046] [~] [Multilevel Switch] duration: [Duration: 0seconds] [Endpoint 5]
                       => [Duration: 0seconds]
23:40:08.546 CNTRLR   [Node 046] [~] [Multilevel Switch] currentValue: 15 => 15         [Endpoint 5]
23:40:08.547 SERIAL » [ACK]                                                                   (0x06)
23:40:08.549 DRIVER « [Node 046] [REQ] [ApplicationCommand]
```

The software I'm using sends commands every 90 seconds by default. So looking through the logs, I see the above regularly.. 

**Describe the solution you'd like**
Would it make sense for zwavejs2mqtt to ignore these commands? This is for Multilevel switch, but maybe others make sense too - like the RGB / Color switch we touched on lately.. if one or more components are unchanged, it could make sense to _not_ update those.

**Describe alternatives you've considered**
N/A

**Additional context**
I'm not sure if this is the correct place to put this logic.. Maybe the user (me) _wants_ to send these nonsensical commands..

Perhaps I should poke the guys doing the dimming software?

**Comment by robertsLando** [comment]
> Perhaps I should poke the guys doing the dimming software?

What I don't understand is why you are sending this commands every 90 seconds. IMO this should be handled on your side

**Comment by LordMike** [comment]
I figured as much. I'll poke at the guys making the dimming thingy.... Just looked it up.. "Adaptive Lighting" they call it.. :P
