### ISSUE TITLE
[bug] Sound Switch and other User params show under System

### ISSUE THREAD

**Issue by billiaz** [zwave-js/zwavejs2mqtt#31]
zwavejs2mqtt version: hass#discovery - lastest

My Aeotec ZW164 is a sound switch device (I would say). Many executeable commands under CC 121 (sound switch) are showing under system tab and not user or config.

Can this be corrected somehow?
Attached a screen shot, used a tool to capture while scrolling

![screencapture-z2m-rb11-eu-2020-11-25-21_03_48](https://user-images.githubusercontent.com/4048920/100276537-01e4bb80-2f62-11eb-9c03-4f43d9f690c9.png)

**Comment by robertsLando** [comment]
@billiaz Thanks for this issue, it's not really a bug, actually I'm looking for a way to identify `system` command classes, actually I'm doing it like this: https://github.com/zwave-js/zwavejs2mqtt/blob/master/lib/ZwaveClient.js#L656 

But It was a guess, do you know if there is a list of 'system' command classes?

**Comment by aretakisv** [comment]
@robertsLando I can Read the spec classes from the Excel file they have and add exception for  any >=94 that is not system in this ZwaveClient.js, to their category.
then only new CC will need adjustment

**Comment by robertsLando** [comment]
@aretakisv Fixed!
