### ISSUE TITLE
[bug] Set-commands from MQTT not working

### ISSUE THREAD

**Issue by sneakpaw** [zwave-js/zwavejs2mqtt#310]
### Version

Build/Run method

- [x] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build )

zwavejs2mqtt version: 1.0.0-rc.1
zwavejs version: 6.0.0

### Describe the bug

MQTT "set"-messages don't work. Triggering the same from the web-ui works.

### To Reproduce

Set Gateway to payload-type JSON time-value

#### Example 1 (Zipato | RGBW Bulb V2)
Current Value: 
* Topic: `raw/z-wave/LB__01/38/0/Up`
* Payload: `{"time":1611248166243, "value": false}`
Setting Value:
* Topic: `raw/z-wave/LB__01/38/0/Up/set`
* Payload: `{ "value": true }`
Log:
`2021-01-21 21:00:41.436 INFO MQTT: Message received on raw/z-wave/LB__01/38/0/Up/set, '{ "value": true }'`

#### Example 2 (Fibargroup | Single Switch 2)
Current Value: 
* Topic: `raw/z-wave/IWS_01/37/1/CurrentValue`
* Payload: `{"time":1611251607553,"value":false}`
Current Value: 
* Topic: `raw/z-wave/IWS_01/37/1/TargetValue`
* Payload: `{"time":1611248166006,"value":false}`
Setting Value:
* Topic: `raw/z-wave/IWS_01/37/1/targetValue/set`
* Payload: `{ "value": true }`
Log:
`2021-01-21 21:06:55.624 INFO MQTT: Message received on raw/z-wave/IWS_01/37/1/targetValue/set, '{ "value": true }'`

### Expected behavior

The MQTT set messages should work.

### Additional context

* I recently switched from zwave2mqtt to zwavejs2mqtt 
* The MQTT-broker in use is mosquitto:2.0.
* As zwave(js)2mqtt doesn't support multipart mqtt-topic prefixes I added an additional endpoint for zwave(js)2mqtt which has `raw/` as mount-point. In my opinion zwavejs2mqtt shouldn't actually see the topics as `raw/z-wave/#` but only `z-wave/#`, but the logs show differently. This setup worked in zwave2mqtt

**Comment by sneakpaw** [comment]
The idea I had while writing the "Additional context" seems to be part of the issue. I reconfigured to remove the `raw/` mount-point. and when trying to set my first example from above actually leads to further log-messages:
```
2021-01-22 10:09:03.988 INFO MQTT: Message received on z-wave/LB__01/38/0/Up/set, '{\n "value": true\n}'
2021-01-22 10:09:03.991 INFO ZWAVE: Writing true to 38-0-Up
2021-01-22 10:09:04.168 INFO ZWAVE: Node 13: value updated: 38-0-currentValue 0 => 99
```
(the payload can actually be just `true` too)

I cannot see the visible results right now, but I will check later.
I'm not sure if that's an issue with zwavejs2mqtt or mosquitto (I think mosquitto is at fault here).

In my case this circumvents the issue, because the `raw/` prefix is obsolete in my setup (the raw layer has its own broker now), but others may still encounter this issue.

**Comment by robertsLando** [comment]
@sneakpaw When you say mount point, you mean the prefix set on mqtt settings?

**Comment by sneakpaw** [comment]
No. Mosquitto has the ability to restrict a tcp-listener to a specific topic (and its subtopics). In my case that would be:
```
listener 1873
mount_point raw/
```
zwave2mqtt only has `z-wave` configured.
So anyone who connects to 1873 should only see `raw/#`, but as `#` (without the `raw/`).
This was the behaviour in mosquitto 1.6, but it seems, that the upgrade to 2.0 broke that.

The main reason, why I had the end point was because zwave2mqtt didn't support `raw/z-wave/` as prefix (at least not in the ui)

**Comment by robertsLando** [comment]
> This was the behaviour in mosquitto 1.6, but it seems, that the upgrade to 2.0 broke that.

So It's a bug with mosquitto not zwavejs2mqtt?

**Comment by sneakpaw** [comment]
Yes, I think so too.
But the bug just broke a workaround I had for a missing feature in zwave2mqtt.

The issue I had is "fixed", or rather no longer relevant here.
If you want to add support for multi-part mqtt prefixes, that would be nice, but not strictly necessary any more for me.
