### ISSUE TITLE
MQTT retain setting per item in Gateway config [feat]

### ISSUE THREAD

**Issue by chrish987** [zwave-js/zwavejs2mqtt#311]
It would be nice to be able to set the RETAIN flag on a per message basis in the gateway config rather than just globally. Some messages (e.g. light status) are more relevant for retained messages than others (e.g. a PIR motion alert).

Setting could either replace or override the global setting in MQTT config.

Not sure if this is useful for others, I am using the software with all messages manually configured in the gateway. I use node-red for most of the workflow items, driven from Zwave2Mqtt messages, with retain every time node-red restarts or deploys it reloads the messages and runs any workflows. Can put a check in the node-red code on message age, but nicer to be able to configure as required at source.

**Comment by LordMike** [comment]
I suppose it would be possible to identify the longevity of a value based on the command class being used.. Meters and switches could be retained, as their state is always "correct" (whatever was received last) - while motion sensors and the like are "events" ... 

Could this be done?

**Comment by chrish987** [comment]
I would prefer just being able to set the option in the 'Configured Manually' gateway section under each added value. Manual config would allow override of the default and give the highest level of control.

**Comment by robertsLando** [comment]
Yep this is something that could be easily done using gateway values

**Comment by chrish987** [comment]
did you mean this is already possible using existing gateway configuration, or that it can easily be added as a feature?

**Comment by robertsLando** [comment]
this is my next feature in todos, along with custom qos level :)

**Comment by robertsLando** [comment]
PR ready
