### ISSUE TITLE
[bug] Gateway -  Manual mode not working

### ISSUE THREAD

**Issue by tommyjlong** [zwave-js/zwavejs2mqtt#312]
Before submitting a bug please read: <https://zwave-js.github.io/zwavejs2mqtt/#/troubleshooting/bug_report>

### Version
 
Build/Run method

- [ ] Docker
- [ ] PKG
- [x] Manually built (git clone - npm install - npm run build )

zwavejs2mqtt version: 1.0.0-rc.1.5846763
zwavejs version: 6.0.0

### Describe the bug
Using the GUI, I have configured the gateway Type for "Configured Manually" mode with payload type "Just Value".

Using the GUI, I have configured one entry in the Gateway Table to receive a central scene from an aeotec wallmote quad for scene1 and output an mqtt topic of "button1".

settings.json (gateway portion)
```
"gateway":{"type":2,"payloadType":2,"nodeNames":true,"hassDiscovery":false,"discoveryPrefix":"homeassistant","logEnabled":true,"logLevel":"silly","logToFile":true,"values":[{"device":"134-130-258","value":{"id":"91-0-scene-001","commandClass":91,"commandClassName":"Central Scene","endpoint":0,"property":"scene","propertyName":"scene","propertyKey":"001","propertyKeyName":"001","type":"number","readable":true,"writeable":false,"label":"Scene 001","stateless":false,"min":0,"max":255,"list":true,"states":[{"text":"KeyPressed","value":0},{"text":"KeyReleased","value":1},{"text":"KeyHeldDown","value":2}],"lastUpdate":1611261756079},"topic":"button1"}]}
```

The node in this case is node 8.
When I snoop on mqtt (subscribe to all topics) I see node 8's status:
```z2mqtt/nodeID_8/status true```
So I know mqtt is working.  

When I press button 1 on the wall mote quad I see in the logs:
```
2021-01-21 16:31:06.870 INFO ZWAVE: Node 8: interview completed, all values are updated
2021-01-21 16:31:06.871 DEBUG MQTT: Publishing to z2mqtt/nodeID_8/status: true with options { qos: 1, retain: false }
2021-01-21 16:31:08.033 INFO ZWAVE: Node 8 is now asleep
2021-01-21 16:31:08.035 DEBUG MQTT: Publishing to z2mqtt/nodeID_8/status: true with options { qos: 1, retain: false }
2021-01-21 16:31:14.736 INFO ZWAVE: Node 8: value notification: 91-0-scene-001 0
2021-01-21 16:31:14.791 INFO ZWAVE: Node 8: value updated: 32-1-currentValue 255 => 0

```
However no mqtt topic gets published to the broker and subsequently doesn't show up at my mqtt snooper.

**Comment by robertsLando** [comment]
@tommyjlong Thanks for the issue, PR ready
