### ISSUE TITLE
[bug] Unable to create scene with one node which requires boolean value as targetValue

### ISSUE THREAD

**Issue by bdbogjoe** [zwave-js/zwavejs2mqtt#320]
Before submitting a bug please read: <https://zwave-js.github.io/zwavejs2mqtt/#/troubleshooting/bug_report>

### Version

Build/Run method

- [X] Docker
- [ ]   PKG
- [ ]   Manually built (git clone - npm install - npm run build )

zwavejs2mqtt version: 1.0.0
zwavejs version: 6.0.0

### Describe the bug

I want to create one scene with one node accepting boolean value (level up), but getting error while activating the scene.
**Note : Using numeric value, works fine**

### To Reproduce

1. create one scene
2. add node (like switch accepting boolean value for level up)
3. Try to activate the scene

zwave2mqtt     | 2021-01-22 14:33:36.678 INFO MQTT: Message received on zwave/_CLIENTS/ZWAVE_GATEWAY-dongles/api/_activateScene/set, '{"args":[1]}'
zwave2mqtt     | 2021-01-22 14:33:36.680 INFO ZWAVE: Success zwave api call _activateScene true
zwave2mqtt     | 2021-01-22 14:33:36.683 INFO ZWAVE: Writing null to 38-0-On
zwave2mqtt     | 2021-01-22 14:33:36.685 INFO ZWAVE: Controller status: Driver: Multilevel Switch: "On" must be of type "number", received "object"
zwave2mqtt     | 2021-01-22 14:33:36.689 ERROR ZWAVE: Unable to write null on 38-0-On

### Expected behavior

The scene should be activated

### Additional context
here the scene definition : 

[
  {
    "sceneid": 1,
    "label": "test",
    "values": [
      {
        "id": "39-38-0-On",
        "nodeId": 39,
        "commandClass": 38,
        "commandClassName": "Multilevel Switch",
        "endpoint": 0,
        "property": "On",
        "propertyName": "On",
        "type": "boolean",
        "readable": true,
        "writeable": true,
        "label": "Perform a level change (On)",
        "stateless": false,
        "ccSpecific": {
          "switchType": 1
        },
        "list": false,
        "lastUpdate": 1611313453143,
        "value": null,
        "timeout": 0
      }
    ]
  }
]

**Comment by robertsLando** [comment]
@bdbogjoe Fixed :rocket:
