### ISSUE TITLE
Best practice for MQTT server location? [question] 

### ISSUE THREAD

**Issue by ragenhe** [zwave-js/zwavejs2mqtt#321]
First, the intended question:
Is is best practice, or better, to locate the MQTT server on the same host via Docker as zwavejs2mqtt?  Or is it more of a personal preference to the individual?

Next, I decided to run the DEV tag in docker, and if needed would like to help the project by testing, or offering feedback of what I am experiencing within my home automation environment, which consists of Home Assistance, Node-Red, Mosquitto MQTT broker and my z-wave network with about 10 devices.

**Comment by robertsLando** [comment]
> Is is best practice, or better, to locate the MQTT server on the same host via Docker as zwavejs2mqtt? Or is it more of a personal preference to the individual?

Most times broker is on the same host as zwavejs2mqtt, it's easier and in most cases there are no reasons to don't do this, it's a personal choice. 

About the help, feel free to update/add docs, it's more then welcome :)
