### ISSUE TITLE
[bug] Notification going to Node_id topic instead of Node_name topic.

### ISSUE THREAD

**Issue by towerhand** [zwave-js/zwavejs2mqtt#334]
Before submitting a bug please read: <https://zwave-js.github.io/zwavejs2mqtt/#/troubleshooting/bug_report>

### Version

- Custom with latest changes on both masters.

Build/Run method

- [x] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build )

zwavejs2mqtt version: 1.0.0 rc.1+cd11214.cd11214
zwavejs version: 6.0.1-798516f

### Describe the bug

In the gateway settings I have turned on the option to use node names instead of node ids and it's working properly for all nodes except one, node 22 which is a door lock. The status, node info and CCs are getting published to the node name topic (zwave2jsmqtt/yale_door_lock) as expected, but the notifications are getting published to node_22 topic (zwave2jsmqtt/nodeID_22/notification), what a getting published there are: manual_unlock_operation, manual_lock_operation, RF_lock_operation, RF_unlock_operation.

### To Reproduce

I'm checking the mqtt information and topics with MQTT explorer, I have erased the nodeID_22.

Manually locking and unlocking the lock creates the manual_unlock_operation and manual_lock_operation on nodeID_22, locking and unlocking from HA creates the RF_lock_operation and RF_unlock_operation on nodeID_22.

### Expected behavior

I would assume the notification topic should be under the node name topic, like everything else. (zwave2jsmqtt/yale_door_lock/notification)

### Additional context

I have refreshed values and re-interview the node.

**Comment by larstobi** [comment]
Related to #217 ?

**Comment by towerhand** [comment]
[node_22.json.zip](https://github.com/zwave-js/zwavejs2mqtt/files/5860779/node_22.json.zip)

**Comment by towerhand** [comment]
I'll close this issue if it's the same underlying problem, just let me know.

**Comment by robertsLando** [comment]
@towerhand @larstobi FIxed on master

**Comment by towerhand** [comment]
Thanks @robertsLando, you are always so fast to fix issues. Really appreciate it.

**Comment by larstobi** [comment]
Thanks!!! 😊

**Comment by towerhand** [comment]
I just noticed the lock doesn't update the state in home assistant when manually operated, I can see the state change with the debug console in zjs2m. Is there something in this fix that could have caused that? otherwise I'll create a new issue.

**Comment by robertsLando** [comment]
>  I can see the state change with the debug console in zjs2m

Could you enable debug logging and attach the logs? With the debug logleve you should see the mqtt message sent (if any) after the state update

**Comment by towerhand** [comment]
I'm trying but my rp3 is struggling. The logs are growing considerably with the debug log level, over 200 MB when all nodes are completed. 

2021-02-02 09:19:01.924 INFO ZWAVE: Node 22: notification: Manual lock operation 
2021-02-02 09:19:01.927 DEBUG MQTT: Publishing to zwave2jsmqtt/yale_door_lock/notification/Manual_lock_operation: { time: 1612279141925, value: null } with options { qos: 0, retain: true }
2021-02-02 09:19:02.321 DEBUG MQTT: Publishing to zwave2jsmqtt/_EVENTS/ZWAVE_GATEWAY-zwavejs2mqtt/node/node_notification: {
  data: [
    {
      id: 22,
      deviceId: '297-1536-32770',
      manufacturer: 'ASSA ABLOY',
      manufacturerId: 297,
      productType: 32770,
      productId: 1536,
      name: 'yale_door_lock',
      loc: '',
      values: {
        '98-0-currentMode': {
          id: '22-98-0-currentMode',
          nodeId: 22,
          commandClass: 98,
          commandClassName: 'Door Lock',
          endpoint: 0,
          property: 'currentMode',
          propertyName: 'currentMode',
          propertyKey: undefined,
          propertyKeyName: undefined,
          type: 'number',
          readable: true,
          writeable: false,
          description: undefined,
          label: 'Current lock mode',
          default: undefined,
          stateless: false,
          min: 0,
          max: 255,
          step: undefined,
          unit: undefined,
          list: true,
          states: [Array],
          value: 255,
          isCurrentValue: true,
          targetValue: '98-0-targetMode',
          lastUpdate: 1612278707658
        },
        '98-0-targetMode': {
          id: '22-98-0-targetMode',
          nodeId: 22,
          commandClass: 98,
          commandClassName: 'Door Lock',
          endpoint: 0,
          property: 'targetMode',
          propertyName: 'targetMode',
          propertyKey: undefined,
          propertyKeyName: undefined,
          type: 'number',
          readable: true,
          writeable: true,
          description: undefined,
          label: 'Target lock mode',
          default: undefined,
          stateless: false,
          min: 0,
          max: 255,
          step: undefined,
          unit: undefined,
          list: true,
          states: [Array],
          value: 255,
          lastUpdate: 1612278680986
        },
        '98-0-outsideHandlesCanOpenDoor': {
          id: '22-98-0-outsideHandlesCanOpenDoor',
          nodeId: 22,
          commandClass: 98,
          commandClassName: 'Door Lock',
          endpoint: 0,
          property: 'outsideHandlesCanOpenDoor',
          propertyName: 'outsideHandlesCanOpenDoor',
          propertyKey: undefined,
          propertyKeyName: undefined,
          type: 'any',
          readable: true,
          writeable: false,
          description: undefined,
          label: 'Which outside handles can open the door (actual status)',
          default: undefined,
          stateless: false,
          list: false,
          value: [Array],
          lastUpdate: 1612278707986
        },
        '98-0-insideHandlesCanOpenDoor': {
          id: '22-98-0-insideHandlesCanOpenDoor',
          nodeId: 22,
          commandClass: 98,
          commandClassName: 'Door Lock',
          endpoint: 0,
          property: 'insideHandlesCanOpenDoor',
          propertyName: 'insideHandlesCanOpenDoor',
          propertyKey: undefined,
          propertyKeyName: undefined,
          type: 'any',
          readable: true,
          writeable: false,
          description: undefined,
          label: 'Which inside handles can open the door (actual status)',
          default: undefined,
          stateless: false,
          list: false,
          value: [Array],
          lastUpdate: 1612278708259
        },
        '98-0-latchStatus': {
          id: '22-98-0-latchStatus',
          nodeId: 22,
          commandClass: 98,
          commandClassName: 'Door Lock',
          endpoint: 0,
          property: 'latchStatus',
          propertyName: 'latchStatus',
          propertyKey: undefined,
          propertyKeyName: undefined,
          type: 'any',
          readable: true,
          writeable: false,
          description: undefined,
          label: 'The current status of the latch',
          default: undefined,
          stateless: false,
          list: false,
          value: 'open',
          lastUpdate: 1612278708576
        },
        '98-0-boltStatus': {
          id: '22-98-0-boltStatus',
          nodeId: 22,
          commandClass: 98,
          commandClassName: 'Door Lock',
          endpoint: 0,
          property: 'boltStatus',
          propertyName: 'boltStatus',
          propertyKey: undefined,
          propertyKeyName: undefined,
          type: 'any',
          readable: true,
          writeable: false,
          description: undefined,
          label: 'The current status of the bolt',
          default: undefined,
          stateless: false,
          list: false,
          value: 'locked',
          lastUpdate: 1612278708829
        },
        '98-0-doorStatus': {
          id: '22-98-0-doorStatus',
          nodeId: 22,
          commandClass: 98,
          commandClassName: 'Door Lock',
          endpoint: 0,
          property: 'doorStatus',
          propertyName: 'doorStatus',
          propertyKey: undefined,
          propertyKeyName: undefined,
          type: 'any',
          readable: true,
          writeable: false,
          description: undefined,
          label: 'The current status of the door',
          default: undefined,
          stateless: false,
          list: false,
          value: 'open',
          lastUpdate: 1612278709257
        },
        '98-0-lockTimeout': {
          id: '22-98-0-lockTimeout',
          nodeId: 22,
          commandClass: 98,
          commandClassName: 'Door Lock',
          endpoint: 0,
          property: 'lockTimeout',
          propertyName: 'lockTimeout',
          propertyKey: undefined,
          propertyKeyName: undefined,
          type: 'number',
          readable: true,
          writeable: false,
          description: undefined,
          label: 'Seconds until lock mode times out',
          default: undefined,
          stateless: false,
          min: undefined,
          max: undefined,
          step: undefined,
          unit: undefined,
          list: false,
          value: undefined,
          lastUpdate: 1612278681017
        },
        '98-0-operationType': {
          id: '22-98-0-operationType',
          nodeId: 22,
          commandClass: 98,
          commandClassName: 'Door Lock',
          endpoint: 0,
          property: 'operationType',
          propertyName: 'operationType',
          propertyKey: undefined,
          propertyKeyName: undefined,
          type: 'number',
          readable: true,
          writeable: true,
          description: undefined,
          label: 'Lock operation type',
          default: undefined,
          stateless: false,
          min: 0,
          max: 255,
          step: undefined,
          unit: undefined,
          list: true,
          states: [Array],
          value: 1,
          lastUpdate: 1612278700003
        },
        '98-0-outsideHandlesCanOpenDoorConfiguration': {
          id: '22-98-0-outsideHandlesCanOpenDoorConfiguration',
          nodeId: 22,
          commandClass: 98,
          commandClassName: 'Door Lock',
          endpoint: 0,
          property: 'outsideHandlesCanOpenDoorConfiguration',
          propertyName: 'outsideHandlesCanOpenDoorConfiguration',
          propertyKey: undefined,
          propertyKeyName: undefined,
          type: 'any',
          readable: true,
          writeable: true,
          description: undefined,
          label: 'Which outside handles can open the door (configuration)',
          default: undefined,
          stateless: false,
          list: false,
          value: [Array],
          lastUpdate: 1612278700303
        },
        '98-0-insideHandlesCanOpenDoorConfiguration': {
          id: '22-98-0-insideHandlesCanOpenDoorConfiguration',
          nodeId: 22,
          commandClass: 98,
          commandClassName: 'Door Lock',
          endpoint: 0,
          property: 'insideHandlesCanOpenDoorConfiguration',
          propertyName: 'insideHandlesCanOpenDoorConfiguration',
          propertyKey: undefined,
          propertyKeyName: undefined,
          type: 'any',
          readable: true,
          writeable: true,
          description: undefined,
          label: 'Which inside handles can open the door (configuration)',
          default: undefined,
          stateless: false,
          list: false,
          value: [Array],
          lastUpdate: 1612278700525
        },
        '98-0-lockTimeoutConfiguration': {
          id: '22-98-0-lockTimeoutConfiguration',
          nodeId: 22,
          commandClass: 98,
          commandClassName: 'Door Lock',
          endpoint: 0,
          property: 'lockTimeoutConfiguration',
          propertyName: 'lockTimeoutConfiguration',
          propertyKey: undefined,
          propertyKeyName: undefined,
          type: 'number',
          readable: true,
          writeable: true,
          description: undefined,
          label: 'Duration of timed mode in seconds',
          default: undefined,
          stateless: false,
          min: 0,
          max: 65535,
          step: undefined,
          unit: undefined,
          list: false,
          value: undefined,
          lastUpdate: 1612278681036
        },
        '99-0-userIdStatus-1': {
          id: '22-99-0-userIdStatus-1',
          nodeId: 22,
          commandClass: 99,
          commandClassName: 'User Code',
          endpoint: 0,
          property: 'userIdStatus',
          propertyName: 'userIdStatus',
          propertyKey: 1,
          propertyKeyName: '1',
          type: 'number',
          readable: true,
          writeable: true,
          description: undefined,
          label: 'User ID status (1)',
          default: undefined,
          stateless: false,
          min: undefined,
          max: undefined,
          step: undefined,
          unit: undefined,
          list: true,
          states: [Array],
          value: 1,
          lastUpdate: 1612278715721
        },
        '99-0-userCode-1': {

here start listing all user codes.

**Comment by towerhand** [comment]
Please let me know if you need anything else. Is it related to the PR fixing the notification path, or a new issue, or on my end?

**Comment by robertsLando** [comment]
I'm going to release a new version, could be also a deivce issue btw. Open a separete log and attach all logs (both zwavejs and zwavejs2mqtt)
