### ISSUE TITLE
[feature request] add an API to execute arbitrary Z-Wave commands

### ISSUE THREAD

**Issue by carldebilly** [zwave-js/zwavejs2mqtt#336]
## Introduction
I have a bunch of Stelpro Ki thermostats that I installed few years ago when I was using SmartThings. Those thermostats were always working great.

## The feature: display outdoor temperature
The have a feature to show outdoor temperature that works well with SmartThings [the code for that is here](https://github.com/stelpro/Ki-Z-Wave-Thermostat/blob/d106ec8c640d3288850e672bf88352beff6f57c7/devicetypes/stelpro/stelpro-ki-thermostat.src/stelpro-ki-thermostat.groovy#L359_L371).

## The failure
I switched to Home Assistant (which is using OpenZWave) and I never found how to use this feature.

## Specs
On SmartThings, it's using the [`sensorMultilevelV3.sensorMultilevelReport`](https://graph.api.smartthings.com/ide/doc/zwave-utils.html#sensorMultilevelV3) to send this information to the device.

[spec sheet on z-wave alliance](https://products.z-wavealliance.org/products/1603):
```
Outdoor Temperature

When connected to a Z-Wave network, the thermostat may display the outdoor temperature provided by an external sensor.
When available, the outdoor temperature is displayed instead of the set point, providing that the outdoor temperature display setting is set to on.
If no temperature is received within a 4 hours timeframe, the outdoor temperature will disappear and the set point will be displayed.
In order to display the outdoor temperature, an external sensor needs to be part of the Z-Wave network. It may be a physical sensor or a weather station app.
Refer to your Z-Wave hub controller instructions manual to find how to associate both devices. On some Z-Wave hub controllers, an app may be used to provide the outdoor temperature.

```

## The hope
Is it possible to code something like this using zwavejs/zwavejs2mqtt ? I'm not afraid to code it (I did the exact same feature for the zigbee version of this thermostat on the Zigbee2Mqtt project).

I'll need some guidance...

**Comment by robertsLando** [comment]
@carldebilly You can try with https://github.com/zwave-js/zwavejs2mqtt/pull/360

**Comment by carldebilly** [comment]
I'll try this weekend...

**Comment by robertsLando** [comment]
@carldebilly Check the PR for more information. In your case the command to send will be `sendReport` and the args `[sensorType, scale, value]` like described here: https://github.com/zwave-js/node-zwave-js/blob/c695ee81cb2b1d3cf15e3db1cc14b1e41a911cc0/packages/zwave-js/src/lib/commandclass/MultilevelSensorCC.ts#L149

@AlCalzone how does he can identify the correct values to use as `sensorType` and `scale` ?

**Comment by AlCalzone** [comment]
sensor types are the first level keys here:
https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/sensorTypes.json
scales are the second level keys (or for the named scales the keys here https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/scales.json)

**Comment by robertsLando** [comment]
Ok so the args could be in this case `[1, 0, <value>]` (air temperature, celsius, the value).

Topic: `zwavejs/_CLIENTS/ZWAVE_GATEWAY-<yourName>/api/sendCommand/set`

Payload: 

```js
{ "args": [
  {
    "nodeId": 4,
    "commandClass": 49,
    "endpoint": 0,
    "property": "Air temperature"
  }, 
  "sendReport",
  [1, 0, <value>]
  ]
}

**Comment by AlCalzone** [comment]
Should be the correct one. Maybe another endpoint, but that must be mentioned in the manual in that case.

**Comment by robertsLando** [comment]
@carldebilly Ok so try with the example I showed you with endpoint 1-2-3 until you see the desired outcome :)

**Comment by carldebilly** [comment]
![](https://media.giphy.com/media/h5dV53fnJksOxmIedp/giphy.gif)
It worked on the very first try!  Thanks good work!
