### ISSUE TITLE
[bug] change secure inclusion dialog to yes / no 

### ISSUE THREAD

**Issue by scyto** [zwave-js/zwavejs2mqtt#348]
Before submitting a bug please read: <https://zwave-js.github.io/zwavejs2mqtt/#/troubleshooting/bug_report>

### Version
1.0.0-rc.1
Build/Run method

- [ x ] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build )

zwavejs2mqtt version: 1.0.0
zwavejs version: 6.0.0

### Describe the bug

When starting an inclusion you are prompted if you want secure inclusion.
The option provided is yes / cancel
This caught me out the first time or two.
With all the new folks expected soon changing this (if quick) will avoid i lot of spurious reports IMO.

### To Reproduce

start inclusion - look at dialog

### Expected behavior

say yes / no instead  yes / cancel
(or better yet is it possible on the command drop down to have one dropdown for each type of inclusion?)

**Comment by robertsLando** [comment]
Fixed on master
