### ISSUE TITLE
[bug] status text is black in dark mode 

### ISSUE THREAD

**Issue by scyto** [zwave-js/zwavejs2mqtt#349]
Before submitting a bug please read: <https://zwave-js.github.io/zwavejs2mqtt/#/troubleshooting/bug_report>

### Version
1.0.0-rc.1
Build/Run method

- [ x ] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build )

zwavejs2mqtt version: 1.0.0
zwavejs version: 6.0.0

### Describe the bug

text is black in dark theme

![image](https://user-images.githubusercontent.com/11369180/105801608-50a4d680-5f4e-11eb-9f4f-661c6e67681a.png)

### To Reproduce

set dark theme, 
select heal from right menu (which changes focus)
click execute arrow
look at status messages for say heal network

### Expected behavior

not be black, be same as other status messages, note it is black text on white background if i click the status error - not sure what is going on.

### Additional context

browser is edge-chromium

**Comment by robertsLando** [comment]
@scyto I think that's a browser error, it's ok on my side: 

![Schermata da 2021-01-26 10-53-40](https://user-images.githubusercontent.com/11502495/105829531-c64b8980-5fc4-11eb-9106-2bb036dcb0d6.png)
