### ISSUE TITLE
[bug] my gateway devices section is empty after upgrading to :dev container is this normal?

### ISSUE THREAD

**Issue by scyto** [zwave-js/zwavejs2mqtt#350]
Before submitting a bug please read: <https://zwave-js.github.io/zwavejs2mqtt/#/troubleshooting/bug_report>

### Version
1.0.0-rc.1
Build/Run method

- [ x ] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build )

zwavejs2mqtt version: 1.0.0
zwavejs version: 6.0.0

### Describe the bug

I upgraded from :latest to :dev today by doing docker-compose down, editing my yamp to change the tag and then docker compose up.  I can still see my devices, i added a device ok, it propagated to HAAS with node ID instead of name.  I have use name instead of ID and normally add the name and area and the re-publish so that the device/entities have friendly name

However now i see no devices in the hass area and no ability to republish.  Did the feature change from :latest to :dev ?

### To Reproduce

start with working test version from a couple of weeks ago (sorry i have no idea what version it was)
keep all state as-is but change to dev:
add a device in zwave inclusion and watch it appear in HASS
go rename device and area
the go here to republish:
![image](https://user-images.githubusercontent.com/11369180/105803709-df1b5700-5f52-11eb-9f5c-a3d78eac0332.png)

### Expected behavior

It worked like it did before?

### Additional context

I tried switching back to :latest container, but that didn't solve the issue, i don't know if this area in the UI was ok before i upgraded, sorry.

the version of latest i had had this image tag and date and Id ```zwavejs/zwavejs2mqtt                       latest     5a7390c3f212   3 weeks ago    178MB```

![image](https://user-images.githubusercontent.com/11369180/105803999-88624d00-5f53-11eb-85fa-0454b5e1f5bf.png)

**Comment by scyto** [comment]
logs and config if required
[zwavejs2mqtt-store (1).zip](https://github.com/zwave-js/zwavejs2mqtt/files/5871361/zwavejs2mqtt-store.1.zip)

**Comment by scyto** [comment]
ignore me I am idiot

**Comment by robertsLando** [comment]
:laughing:
