### ISSUE TITLE
[bug] cannot call refreshValues from HA because cannot send array

### ISSUE THREAD

**Issue by blhoward2** [zwave-js/zwavejs2mqtt#362]
Before submitting a bug please read: <https://zwave-js.github.io/zwavejs2mqtt/#/troubleshooting/bug_report>

### Version

Build/Run method

- [ ] Docker
- [ ] PKG
- [X ] Manually built (git clone - npm install - npm run build )

zwavejs2mqtt version: 1.0.0
zwavejs version: 6.0.0

### Describe the bug

In #246 we added a refreshValues api. This works fine from MQTT sending an array:

```
{
"args": [12]
}
```

In HA, however, mqtt.publish will only send a string as the payload. Trying to send an array results in the error:

"Failed to call service mqtt/publish. value should be a string for dictionary value @ data['payload']"

Sending through mqtt.publish works in other contexts. On one device expecting a true/false for set value, it works when I send the payload '[True]':

```
payload: '[True]'
topic: homeassistant/54/37/0/targetValue/set
```

When trying to call refreshValues() however, it fails when I try to send the payload "[12]" to homeassistant/_CLIENTS/ZWAVE_GATEWAY-12/api/refreshValues/set through mqtt.publish.

```
topic: homeassistant/_CLIENTS/ZWAVE_GATEWAY-12/api/refreshValues/set
payload: '[12]'
```
Trying to do so results in:
`{"success":false,"message":"Cannot read property 'refreshValues' of undefined","args":[]}`

The `"args":[]` part of the error message is blank no matter how I format the payload. Since we're calling the node itself "homeassistant/_CLIENTS/ZWAVE_GATEWAY-**12**/api/refreshValues/set" is there a way to turn this into a True/False situation and take the node that should be refreshed from the topic? We should fix this string problem anyway but it seems odd to me that we have to list the node number twice...

I've tried every which I can think of to format the payload but cannot seem to send a payload in a compatible format.

### To Reproduce

1. Go to run mqtt.publish
2. Failure

### Expected behavior

The refreshValues api should be called, resulting in a refresh instead of an undefined value error.

**Comment by blhoward2** [comment]
And...I'm an idiot. For future searchers, the proper payload is:

```
topic: homeassistant/_CLIENTS/ZWAVE_GATEWAY-12/api/refreshValues/set
payload: '{"args": [12]}'
```

**Comment by robertsLando** [comment]
@blhoward2 :laughing:
