### ISSUE TITLE
[feat]Better Z-wave network graph

### ISSUE THREAD

**Issue by maivorbim** [zwave-js/zwavejs2mqtt#370]
Currently Zwave-js has the option of displaying a SVG graph of all connected nodes. However, the information presented is basic and is lacking additional information such as list of neighbours for each node, latencies, node errors, queue size, topology/hierarchy.

I find that the following implementation is more clear and helps diagnose network issues faster and could thus serve as reference: https://github.com/AdamNaj/ZWaveGraphHA

As such, a better network graph would be a nice-to-have feature for zwave-js .

**Comment by robertsLando** [comment]
Instead of copy that one, we could improve the existing one. Anyway by clicking on a node you will get some informations about this

**Comment by FreelancerJay** [comment]
I had three thoughts on the Z-Wave graph, just as suggestions for down the road:

- allow grouping nodes by the “location” parameter, so you can quickly tell “hey, everything in the garage is only on the network by a single node”. Wouldn’t be on by default, but just as a toggle switch you can quickly flick on and off on the display.
- when you select a node, grey out or drop the opacity of all the nodes not neighbours to the selected node.
- I don’t know if the signal strength between nodes is reported when they build their neighbours list, but if it is we could colour or adjust the line thickness on node connections to reflect that?

Just wanted to put those out in the universe and see what people’s thoughts on them are

**Comment by robertsLando** [comment]
The ideas are good, I keep this in my TODOs but dunno when I will implement this. There are some things more important for now

**Comment by robertsLando** [comment]
Dups of #384
