### ISSUE TITLE
[bug] Hass Discovery for Euronics Sprit sending Valve Opening as Light

### ISSUE THREAD

**Issue by DamianFlynn** [zwave-js/zwavejs2mqtt#380]
Before submitting a bug please read: <https://zwave-js.github.io/zwavejs2mqtt/#/troubleshooting/bug_report>

### Version

Build/Run method

- [X] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build )

zwavejs2mqtt version: 1.0.0-rc.1
zwavejs version: 6.1.0

### Describe the bug

The HASS Discovery payload sends a Dimmer Light as the sensor type for the Valve Opening 

This is a sample of the current payload

```
{
  "type": "light",
  "object_id": "dimmer",
  "discovery_payload": {
    "command_topic": "zwave/Girls/trvGirlsWest/38/0/targetValue/set",
    "state_topic": "zwave/Girls/trvGirlsWest/38/0/currentValue",
    "state_value_template": "{{ \"OFF\" if value_json.value == 0 else \"ON\" }}",
    "brightness_command_topic": "zwave/Girls/trvGirlsWest/38/0/targetValue/set",
    "brightness_scale": 99,
    "brightness_state_topic": "zwave/Girls/trvGirlsWest/38/0/currentValue",
    "brightness_value_template": "{{ value_json.value }}",
    "on_command_type": "brightness",
    "device": {
      "identifiers": [
        "zwavejs2mqtt_0xee4e64d7_node18"
      ],
      "manufacturer": "Eurotronics",
      "model": "Thermostatic Valve (Spirit)",
      "name": "Girls-trvGirlsWest",
      "sw_version": "0.15"
    },
    "name": "Girls-trvGirlsWest_dimmer",
    "unique_id": "zwavejs2mqtt_0xee4e64d7_18-38-0-currentValue"
  },
  "discoveryTopic": "light/Girls-trvGirlsWest/dimmer/config",
  "values": [
    "38-0-currentValue",
    "38-0-targetValue"
  ],
  "persistent": false,
  "ignoreDiscovery": false,
  "id": "light_dimmer"
}
```

### To Reproduce

Add a Euronics Spirit Device, 
In the Home Assistant Properties page
We will see the Valve Position 38-0-currentValue mapped to a Light_Dimmer discovery template instead of a Sensor_Opening template

### Expected behavior

A correct Template to send for discovery would be a Sensor, with a Class of Opening - for example

```
{
  "type": "sensor",
  "object_id": "opening",
  "discovery_payload": {
    "value_template": "{{ value_json.value }}",
    "device_class": "opening",
    "unit_of_measurement": "%",
    "state_topic": "zwave/Kitchen/trvKitchenIsland/38/0/currentValue",
    "json_attributes_topic": "zwave/Kitchen/trvKitchenIsland/38/0/currentValue",
    "device": {
      "identifiers": [
        "zwavejs2mqtt_0xee4e64d7_node10"
      ],
      "manufacturer": "Eurotronics",
      "model": "Thermostatic Valve (Spirit)",
      "name": "Kitchen-trvKitchenIsland",
      "sw_version": "0.15"
    },
    "name": "Kitchen-trvKitchenIsland_valve",
    "unique_id": "zwavejs2mqtt_0xee4e64d7_10-38-0-currentValue"
  },
  "discoveryTopic": "light/Kitchen-trvKitchenIsland/sensor/config",
  "values": [
    "38-0-currentValue"
  ],
  "persistent": false,
  "ignoreDiscovery": false,
  "id": "sensor_valve"
}
```

**Comment by ivdimitro** [comment]
The idea of representing the multi-level switch as a dimmer is to allow for the valve to be controllable. 
It is not a bug. 
Also you can define the additional sensor with the valve position in your customDevices. This is what I am doing as well because the reporting to influxDB is easier.

**Comment by robertsLando** [comment]
@DamianFlynn yep it is not a bug, you could try to do like ivdimitro suggested or maually edit the discovery payload to fit your needs

**Comment by DamianFlynn** [comment]
ok - i understand that we can set the TRV in manual mode, and then in theory us this dimmer to control the valve. However the template for discovery of the Climate modes also does not offer manual as an operating mode - which i assume makes the Light object readonly.

@ivdimitro Can you tell/point me at how you added the additional sensor in customDevices as you mention?

**Comment by ivdimitro** [comment]
Please find my customDevices.json 

`{
  "881-21-2": [
    {
      "type": "climate",
      "object_id": "thermostat",
      "values": [
        "64-0-mode",
        "49-0-Air temperature",
        "67-0-setpoint-1",
        "67-0-setpoint-11"
      ],
      "mode_map": {
        "off": 0,
        "heat": 1,
        "cool": 11,
        "dry": 15,
        "fan_only": 31
      },
      "setpoint_topic": {
        "1": "67-0-setpoint-1",
        "11": "67-0-setpoint-11"
      },
      "default_setpoint": "67-0-setpoint-1",
      "discovery_payload": {
        "min_temp": 8,
        "max_temp": 28,
        "modes": [
          "off",
          "heat",
          "cool",
          "dry",
          "fan_only"
        ],
        "mode_state_topic": "64-0-mode",
        "mode_command_topic": true,
        "current_temperature_topic": "49-0-Air temperature",
        "temp_step": 0.1,
        "current_temperature_template": "{{ value_json.value }}",
        "temperature_state_template": "{{ value_json.value }}",
        "temperature_command_topic": true
      }
    },
    {
      "type": "cover",
      "object_id": "valve_control",
      "discovery_payload": {
        "position_topic": "38-0-currentValue",
        "set_position_topic": "38-0-targetValue",
        "value_template": "{{ (value_json.value / 99 * 100) | round(0) }}",
        "position_open": 99,
        "position_closed": 0
      },
      "values": [
        "38-0-currentValue",
        "38-0-targetValue"
      ]
    },
    {
      "type": "sensor",
      "object_id": "valve_position",
      "discovery_payload": {
        "icon": "mdi:valve",
        "value_template": "{{ value_json.value }}",
        "state_topic": "38-0-currentValue"
      },
      "values": [
        "38-0-currentValue"
      ]
    },
    {
      "type": "sensor",
      "object_id": "current_temperature",
      "discovery_payload": {
        "value_template": "{{ value_json.value }}",
        "device_class": "temperature",
        "unit_of_measurement": "°C",
        "state_topic": "49-0-Air temperature"
      },
      "values": [
        "49-0-Air temperature"
      ]
    },
    {
      "type": "sensor",
      "object_id": "target_temperature",
      "discovery_payload": {
        "icon": "mdi:thermometer-lines",
        "value_template": "{{ value_json.value }}",
        "device_class": "temperature",
        "unit_of_measurement": "°C",
        "state_topic": "67-0-setpoint-1"
      },
      "values": [
        "67-0-setpoint-1"
      ]
    }
  ]
}`


I am using the cover for valve control as. The crucial part is that you have to expose the "manufacturer specific" mode for the thermostat. I have mapped it to the "fan only mode" 
So in order to control the valve manually you have to set the mode to dan only and then change the valve opening via the cover.

**Comment by DamianFlynn** [comment]
Awsome - the customDevices.json i did not know about, this rocks. @idyedov Thank you!

**Comment by billiaz** [comment]
@DamianFlynn can you please send me the node export? want to see some details of this
