### ISSUE TITLE
[bug]G/W Manual mode - Topic Value expected to be text instead of numeric value

### ISSUE THREAD

**Issue by tommyjlong** [zwave-js/zwavejs2mqtt#392]
Before submitting a bug please read: <https://zwave-js.github.io/zwavejs2mqtt/#/troubleshooting/bug_report>

### Version

Build/Run method

- [ ] Docker
- [ ] PKG
- [x] Manually built (git clone - npm install - npm run build )

zwavejs2mqtt version: 1.0.1.e227f5b
zwavejs version: 6.1.0

### Describe the bug
G/W is in Configured Manually/Just Value mode.
Used the GUI to create entry in the G/W table for a Aeotec Wallmote quad scene based on a button press.
An MQTT topic is generated/sent to the broker, but only numerical values are sent.  Instead a text string should be sent based on the numeric value.

_Note: Migrating from Zwave2MQTT but starting with blank Zwavejs2MQTT settings.json and reconfiguring accordingly._

For example, when the button is pressed, the following MQTT topics are generated
```
z2mqtt/nodeID_8/button1 0
z2mqtt/nodeID_8/button1 (null)
```

What is expected. As a reference, this is what the Zwave2MQTT outputs:
```
z2mqtt/nodeID_8/button1 "Pressed 1 Time"
z2mqtt/nodeID_8/button1 "Inactive"
```

Relevant zwavejs2mqtt settings.json file
```
{"device":"134-130-258","value":{"id":"91-0-scene-001","commandClass":91,"commandClassName":"Central Scene","endpoint":0,"property":"scene","propertyName":"scene","propertyKey":"001","propertyKeyName":"001","type":"number","readable":true,"writeable":false,"label":"Scene 001","stateless":false,"min":0,"max":255,"list":true,"states":[{"text":"KeyPressed","value":0},{"text":"KeyReleased","value":1},{"text":"KeyHeldDown","value":2}],"lastUpdate":1611261756079},"topic":"button1"}
```

As a reference, this is what the zwave2mqtt settings.json looks like:
``` 
{"device":"134-130-258","value":{"value_id":"91-1-1","class_id":91,"type":"list","genre":"user","instance":1,"index":1,"label":"Instance 1: Scene 1","units":"","help":"","read_only":true,"write_only":false,"min":0,"max":0,"is_polled":false,"values":["Inactive","Pressed 1 Time","Key Released","Key Held down"],"value":"Inactive","lastUpdate":1592157553363},"topic":"button1"}

```

**Comment by robertsLando** [comment]
@tommyjlong This is by design now. What I can suggest to you is to choose valueId topics so you will also see states where you will be able to see the actual text value. Otherwise you can use parseSend and parseReceive functions to send/write the value using states

**Comment by tommyjlong** [comment]
I hope you don't mind giving me a helpful hint for how to start out writing a function for the Parse Send (I'm not very familiar with node programming).

I have the following that I have been playing with
```
(function() {
        console.log('value is  ' + value)
        value = 45
        console.log('value is ' + value)
        console.log('valueId is ' + valueId)
        console.log('valueId.value is ' + valueId.value)
        console.log('node is ' + node)
        console.log('node.id is ' + node.id)
        return 'Hello'
    })();
```
The log output is:
```
value is  0
value is 45
valueId is [object Object]
valueId.value is 0
node is [object Object]
node.id is 8
2021-02-01 19:25:34.904 INFO ZWAVE: Node 8: value notification: 91-0-scene-002 0
value is  undefined
value is 45
valueId is [object Object]
valueId.value is undefined
node is [object Object]
node.id is 8
```
I just can't get the return to work.

**Comment by robertsLando** [comment]
@tommyjlong the function doesn't need to have the signature specified, only the body. What you need to write inside the parseSend function is something like: 

```js
const txtVal = valueId.states.find(s => s.value === value)

return txtVal ? txtVal.text :  null
```

**Comment by tommyjlong** [comment]
Thanks!
This is what I ended up with....had to add a case for wallmote sending null to also produce "Inactive" text in order to match zwave2mqtt's behavior.  :)
```
const txtVal = valueId.states.find(s => s.value === value)
return txtVal ? txtVal.text :  "Inactive"
```

**Comment by robertsLando** [comment]
@tommyjlong Glad it worked for you, you also need to do the opposite and write a parseReceive function to support writes using text values
