### ISSUE TITLE
[bug] gateway device dropdown does not include devices in RestartFromCache interview stage

### ISSUE THREAD

**Issue by jonathan-reisdorf** [zwave-js/zwavejs2mqtt#394]
Before submitting a bug please read: <https://zwave-js.github.io/zwavejs2mqtt/#/troubleshooting/bug_report>

### Version

Build/Run method

- [ ] Docker
- [ ] PKG
- [x] Manually built (git clone - npm install - npm run build )

zwavejs2mqtt version: latest master (1.0.1)
zwavejs version: 6.1.0

### Describe the bug

Not sure if that's already been brought up, but when adding or modifying values in the gateway section, the device dropdown does not include devices in RestartFromCache interview stage, only those from Complete stage. So, passive devices are unfortunately not available right away in that dropdown e.g. after restart or after saving the gateway settings, which seems to trigger a reset.

### To Reproduce

1. Go to Settings > Gateway
2. Click on 'New Value'
3. Device dropdown does not contain devices currently in RestartFromCache stage

### Expected behavior

If possible, it would be very helpful if all devices from cache could be included as well so we can add gateway values right away. If that's not feasible, a small help text would be great explaining that only devices in completed interview stage are available.

### Additional context

Thanks for your work!

**Comment by robertsLando** [comment]
@jonathan-reisdorf Devices are added only when the interview completes. The reason is that only on that stage I'm completely sure all values are there

**Comment by jonathan-reisdorf** [comment]
Thanks. I guess then unless we have a way of also caching/persisting the values from last time when the interview was completed, the only thing we can do here is show a small hint so that others know they have to wake up their passive device first in order for it to show up in the list.

**Comment by robertsLando** [comment]
@jonathan-reisdorf  Made it more clear in docs :)
