### ISSUE TITLE
[bug]G/W Manual Mode - Multisensor6 missing HomeSecurity topic choice

### ISSUE THREAD

**Issue by tommyjlong** [zwave-js/zwavejs2mqtt#395]
Before submitting a bug please read: <https://zwave-js.github.io/zwavejs2mqtt/#/troubleshooting/bug_report>

### Version

Build/Run method

- [ ] Docker
- [ ] PKG
- [x] Manually built (git clone - npm install - npm run build )

zwavejs2mqtt version: 1.0.1.e227f5b
zwavejs version:  6.1.0

### Describe the bug

G/W is in Configured Manually/Just Value mode.
Using the GUI, I want to create an entry in the G/W table for a Aeotec Multisensor 6's "Home Security" parameter (i.e. motion/tampering detection).

In the GUI Pull-down which allows the user to select a CC parameter, there is a long list such as Air Temperature, Humdity, etc.  However there does not seem to be a parameter for motion/tampering detection.

As a reference, doing the same using Zwave2MQTT, the pull down item shows up as "Home Security".

ZWavejs2MQTT does know about this parameter. In the Control Panel, for the Aeotec Multisensor 6, there are several categories of "Values": `Binary Sensor`, `Multilevel Sensor`, `Configuration`,`Notification`, etc.  Within the `Notification`  category there are 2 values:  (Node 2 here is the Aeotec Multisensor6)
```
(2-113-Home Security-Motion sensor status)  Motion sensor...  
(2-113-Home Security-Cover status) Cover status...
```

As a reference, in ZWave2MQTT this shows up as `Home Security (2-113-7)`.  There are is not a separate one for motion versus cover. 

Note: the Notification CC for Home Security 113-7 is multivalued and in the Multisensor6 case it uses values: 0 - Cleared, 3 - Tampering, Product covering removed, 8 - Motion Detection Unknown Location.

**Comment by robertsLando** [comment]
@tommyjlong Do you see that value added in logs? Could you attach logs please?

**Comment by tommyjlong** [comment]
My mistake. After further investigation, in the G/W entry pull down, the item is actually present. It is listed as `Motion Status` as well as `Cover Status`.
