### ISSUE TITLE
Super Minor Display Update -- Does Not Impact Function [bug]

### ISSUE THREAD

**Issue by scott7685** [zwave-js/zwavejs2mqtt#398]
Before submitting a bug please read: <https://zwave-js.github.io/zwavejs2mqtt/#/troubleshooting/bug_report>

1.01

Build/Run method

- [ ] Docker
- [X] PKG
- [ ] Manually built (git clone - npm install - npm run build )

zwavejs2mqtt version: 1.0.1
zwavejs version: 6.0.0

### Describe the bug

Just a minor display issue I noticed on the pop-up dialogue for the Replace Failed Node. The inclusion comes up and asks whether to use Secure Mode. Instead of the "Yes" or "No" options that are used in the normal "Start Inclusion" pop-up dialogue, the pop-up has "Yes" and "Cancel". Cancel does correctly start non-secure inclusion but could generate confusion for people thinking they are canceling the Replace Failed Node process.

### To Reproduce

1. Go to any node
2. Expland the details 
3. Scroll down to Replace Failed Node
4. Click start command

### Expected behavior

Pop-up should have Yes and No, not Yes and Cancel

### Additional context

Did I mention this is minor? Great job on this, only bringing it up since I noticed it whilst replacing a failed node today.

**Comment by robertsLando** [comment]
This is already fixed
