### ISSUE TITLE
[bug] Can't scroll device horizontally without opening home assistant tab

### ISSUE THREAD

**Issue by crxporter** [zwave-js/zwavejs2mqtt#399]
Before submitting a bug please read: <https://zwave-js.github.io/zwavejs2mqtt/#/troubleshooting/bug_report>

### Version

Build/Run method

- [ ] Docker
- [ ] PKG
- [x] Manually built (git clone - npm install - npm run build )

zwavejs2mqtt version: 1.0.1
zwavejs version: 6.1.0

### Describe the bug

When using using mobile, the configure screen on multi-column devices always scrolls to the "Home Assistant" tab instead of allowing to scroll over to the columns to the right. 

### To Reproduce

Screenshot will be attached, I have a Multisensor 6 which has a lot of config options. I'm unable to get to the right 2 columns. 

![](https://media.discordapp.net/attachments/737678372049780788/805617620224311296/unknown.png)

### Expected behavior

I would like access to these config items when using safari on iPhone. 

### Additional context

Downloaded and built from GitHub about 24 hours ago. Running on a raspberry pi 4. Using safari on iPhone 11 Pro.

**Comment by robertsLando** [comment]
@crxporter Could you send me a screenshot of the problem from your mobile? The screenshot attached isn't showing any bug

cc @ahochsteger

**Comment by crxporter** [comment]
Sure, the screenshot was to show that there are indeed columns to the right.

Here's what the experience looks like on mobile. Instead of getting columns on the right, the screen flashes a bit and I end up at "Home Assistant" tab.

![IMB_FcWtKT](https://user-images.githubusercontent.com/38265886/106464905-e9f84f00-645e-11eb-8064-7e3cd6c10efd.gif)

**Comment by robertsLando** [comment]
@crxporter It was supposed to work in that way but some of latest UI changes have break this. WIll fix ASAP. Thanks for reporting

**Comment by ahochsteger** [comment]
@crxporter I've created a PR to disable touch support for `<v-tabs-items>` that triggers a swipe of the tabs and hinders horizontal scrolling.
Would you be able to test this PR and confirm if it solves the issue for you?
cc @robertsLando

**Comment by ahochsteger** [comment]
@crxporter the PR #414 is obsolete now since it was just a workaround.
@robertsLando is working on a real fix in PR #413.

**Comment by robertsLando** [comment]
@ahochsteger Could you give that a try?

**Comment by ahochsteger** [comment]
@robertsLando looks much better.
When I simulate a IPhone X (same applies to a Pixel 2) in the Chrome developer tools there still seem to be the problem that some controls (colapse icon, selection checkbox) are not visible without scrolling even though there should be enough space available:
![image](https://user-images.githubusercontent.com/207989/106516187-f9b37a00-64d6-11eb-90a4-b8557ad67583.png)
It seems that the `<td>` elements take more space than required. If I reduce them in the Chrome developer tools the label and data is visible in most cases.

**Comment by robertsLando** [comment]
Not so good yet

**Comment by matejdro** [comment]
This is still broken in  2.1.1:

![output](https://user-images.githubusercontent.com/507922/110933373-f78dd800-832c-11eb-847b-3ca793caf522.gif)

**Comment by robertsLando** [comment]
@matejdro Try to hide some columns from the table, the bug will fix in this way

**Comment by matejdro** [comment]
It helps, but it is only a workaround, not a fix. What if I want to see all columns?

**Comment by robertsLando** [comment]
the problem is that if there are too much columns we can't show all the content and the table becomes scrollable causing this kind of issue. Even if we submit a fix to this the fix would be to hide some columns on lower screens sizes. Another fix woulud be to remove the expandable rows and put all the content in a window. But this will make loose the possibility to have more then one node properties showing all togheter

**Comment by matejdro** [comment]
What if you disable scroll-to-swipe-through-tabs if width of the table exceeds width of the screen? I can still manually tap on Home Assistant tab to get there.

**Comment by ahochsteger** [comment]
@matejdro, @robertsLando the PR #878  should fix the annoying behavior by annotating `<v-tabs-items>` with `touchless`.
