### ISSUE TITLE
[bug] Dongle-Test in zwavejs2mqtt. All existing associations are deleted.

### ISSUE THREAD

**Issue by hvorragend** [zwave-js/zwavejs2mqtt#409]
### Version

Build/Run method

- [x] Docker - (**dev-tag**)
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build )

zwavejs2mqtt version: 1.0.1 (and all versions from 1.0.0-beta.0 till now)
zwavejs version: 6.0.? (the version which is included in your docker-image)

### Describe the bug

I am using the ZMEEUZB-Dongle (https://z-wave.me/products/uzb/) with Vers:5 Rev:39 in FHEM.
I am currently looking for another Z-Wave-implementation and I like zwavejs2mqtt.
So I create another docker container and I've mounted the stick to zwavejs2mqtt. And yes, the stick is not mounted to FHEM simultaneously.

After a few minutes all devices are recognized and I can use zwavejs2mqtt without any problems.
But all my associations (and multi channel assocations) are deleted.
It looks very much as if zwavejs2mqtt will automatically remove the associations.
I can see that in zwavejs2mqtt and in FHEM. All associations are cleaned there.

### To Reproduce

(empty)

### Expected behavior

I expect the associations in the stick to be permanently stored and used.

**Comment by robertsLando** [comment]
@AlCalzone Are associations stored on controller?

**Comment by AlCalzone** [comment]
Associations are stored on each node. zwave-js does not remove associations, except misconfigured lifelines to the controller (e.g. node associations that should be endpoint associations).

**Comment by robertsLando** [comment]
@hvorragend We need some logs to see what's going on here so

**Comment by hvorragend** [comment]
I've created a zwavejs and zwavejs2mqtt debug-log.
Is it possible to send you these files via email?

**Comment by AlCalzone** [comment]
> I don't use the mutlichannel-device, because I don't see any advantages.

That might be the issue. In some configurations, you won't receive all Lifeline reports **unless** you use a Multi Channel Association. You should let zwave-js manage the associations to your controller - it probably knows better. Associations to other nodes are not touched.

**Comment by hvorragend** [comment]
It was working fine in FHEM with the lifeline reports. 
But I will try to fix it on my side.

In the logs I can see that the there are some assocation adjustments.

**Comment by AlCalzone** [comment]
I don't understand tbh. Is there something that is not working now - except that the lifeline associations are not what you're used to?

**Comment by hvorragend** [comment]
Yes, I need the lifeline associations. But they are working fine and without any problem when I just set them to the master device. 

Just ignore this now. I will now try to use the multichannel-associations in FHEM and after that I try another migration to your zwavejs2mqtt.

Thank you very much.

**Comment by AlCalzone** [comment]
It might work for you but trust me that there are devices that react really strange if they don't get multi channel associations if the specifications say they should but they don't have them.
I've spent hours on figuring out what the correct strategy is

**Comment by hvorragend** [comment]
Thank you for the clarification. It may very well be that I've been doing this wrong for years. :-)
