### ISSUE TITLE
[question] GE motion sensor not being identified 

### ISSUE THREAD

**Issue by djaydev** [zwave-js/zwavejs2mqtt#416]
Running zwavejs/zwavejs2mqtt:master DIGEST:sha256:e4b7bf22fa8b4936a3f463817722cc1c1080245a4ae57de0388f66e7fab2c567

I have the motion sensor below that shows up as unkown product.  The motion on/off alerts still seem to work. 

Device info from ozw:
Manufacturer id="63" name="GE (Jasco Products)"
Product type="4953" id="3133" name="ZW6302 Portable Smart Motion Sensor"
"OzwInfoPage" http://www.openzwave.com/device-database/0063:3133:4953

![node 71](https://user-images.githubusercontent.com/33335484/106502434-59d3fd00-6492-11eb-9f52-df73217a60c9.PNG)
[node_71.json.txt](https://github.com/zwave-js/zwavejs2mqtt/files/5905923/node_71.json.txt)

**Comment by blhoward2** [comment]
This should be opened at the node-zwave-js project. It will be fixed as part of our importation of the zwave alliance files (Nos. 2189, 2157, 1901, and 2124). Recommend closing @robertsLando.

**Comment by robertsLando** [comment]
Tx @blhoward2
