### ISSUE TITLE
Graph view duplicate location values [bug]

### ISSUE THREAD

**Issue by chrish987** [zwave-js/zwavejs2mqtt#443]
Before submitting a bug please read: <https://zwave-js.github.io/zwavejs2mqtt/#/troubleshooting/bug_report>

### Version

Build/Run method

- [X] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build )

zwavejs2mqtt version: 1.0.4
zwavejs version: 6.1.1

latest Release version

### Describe the bug

Cosmetic, does not seem to impact any functionality. 

When navigating to the Network Graph tab and turning on the Location, then moving back to the Control Panel the device name now includes the Location in the name (although this does not appear to affect topics). Moving back to Network Graph location slider is turned off again, yet Location is still visible. Repeating the process keeps concatenating Location value to the end of the display strings.

Observed in Chrome - not tested in other browsers.

### To Reproduce

As above

### Expected behavior

Would not expect Control Panel name to change, would not expect concat of values.

**Comment by robertsLando** [comment]
@chrish987 Fixed in #456
