### ISSUE TITLE
Docker pull manifest unknown error

### ISSUE THREAD

**Issue by Altycoder** [zwave-js/zwavejs2mqtt#45]
`docker pull zwavejs/zwavejs2mqtt:latest` or `docker pull zwavejs/zwavejs2mqtt` gives the following error:

`Error response from daemon: manifest for zwavejs/zwavejs2mqtt:latest not found: manifest unknown: manifest unknown`

I can pull other images from other developers no problem

**Comment by robertsLando** [comment]
Pull `dev` tag

**Comment by Altycoder** [comment]
I suggest you update readme to state this :-)  currently the readme says to pull latest
