### ISSUE TITLE
New to zwavejs - ProtocolInfo questions [question] 

### ISSUE THREAD

**Issue by majorsl** [zwave-js/zwavejs2mqtt#459]
I'm moving over from OpenZWave and am using Zwave to MQTT.  I was able to use my existing network key and all of the devices from my controller show up.  So far so good.

Wired devices are working perfectly.  Every battery device I have is reporting ProtocolInfo under the interview stage.  I understand battery devices can take a few hours.

However, I have one of the motion sensors I moved to my desk.  It is constantly being woken up and it has been almost an hour.  Shouldn't this one, at least, have completed the interview stage by now?  Or is it not a question of the activity?  I can see in the logs it is tripping every time I move.

I'd hate to have to exclude/include 30 battery devices to get it working.

**Comment by Giel538** [comment]
I have also one question about migrating from OpenZwave.

The MQTT topics in OZW where:

zwave prefex - node id - sub topic - 1 - all information

But in Zwave-JS it is 

zwave prefex - node id - sub topic - 0 - all information

Is there anyway to change the 0 to a 1?  Otherwise i have te rewrite my complete code.

**Comment by ODINServ** [comment]
> However, I have one of the motion sensors I moved to my desk. It is constantly being woken up and it has been almost an hour. Shouldn't this one, at least, have completed the interview stage by now? Or is it not a question of the activity? I can see in the logs it is tripping every time I move.
> 
> I'd hate to have to exclude/include 30 battery devices to get it working.

This sounds simmilair to a thinking error I made: #48

**Comment by majorsl** [comment]
Ah, I see. Sending event doesn't always equal awake.  I see some of my devices are set to wake up every 12 hours.  I did manually do this by hitting the pairing button while issuing a Re-interview node which has those working.  I'm going to wait for some of the less important things for 12 hours to pass and see where I'm at.  Thanks!
