### ISSUE TITLE
[feat]Option to turn off MQTT server

### ISSUE THREAD

**Issue by Chaotic** [zwave-js/zwavejs2mqtt#472]
**Is your feature request related to a problem? Please describe.**
A way to shut off the MQTT server in the docker while using the websocket

**Describe the solution you'd like**
I'd like a way to shut off the MQTT portion of the gateway while still being able to use the websocket gateway.  It seems there is a way to shut off the websocket gateway and just use the MQTT one but not a way to do the reverse.  I can just leave it pointing to localhost but that continues to attempt to connect and refuses filling the logs with unneeded errors.

**Describe alternatives you've considered**
None

**Additional context**
Using the new Homeassistant integration and using websockets and not MQTT the MQTT gateway is redundant in my setup

**Comment by towerhand** [comment]
Try the disable gateway toggle.

**Comment by Chaotic** [comment]
That also hides all the options for the websocket gateway so I assumed that shut that off as well.

I just quickly tested it and it does seem to shut off the websocket as well as MQTT.

**Comment by FreelancerJay** [comment]
I've been running with "Disable Gateway" ticked, and my Home Assistant instance connecting to it via WebSocket:
![Screen Shot 2021-02-06 at 5 14 15 pm](https://user-images.githubusercontent.com/67540736/107110812-03eec300-689f-11eb-98a3-0cbd68b9d801.png)

**Comment by robertsLando** [comment]
Just toggle the disable gateway flag, that's the way to do it. If you are using docker use the dev tag instead of the latest
