### ISSUE TITLE
[bug] Docker install on Unraid - not working

### ISSUE THREAD

**Issue by shreram** [zwave-js/zwavejs2mqtt#476]
Before submitting a bug please read: <https://zwave-js.github.io/zwavejs2mqtt/#/troubleshooting/bug_report>

### Version

Build/Run method

- [x ] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build )

zwavejs2mqtt version: 1.0.5
zwavejs version: 6.0.0

### Describe the bug

I installed this on Unraid but this container is not working correctly.

Here is the install command.

```
root@localhost:# /usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker run -d --name='zwavejs2mqtt' --net='bridge' -e TZ="America/Chicago" -e HOST_OS="Unraid" -p ':8091/tcp' -p '3000:3000/tcp' -v '/mnt/user/appdata/zwavejs2mqtt/store':'/usr/src/app/store':'rw' --device='/dev/ttyACM0' 'zwavejs/zwavejs2mqtt'
06920177860a5eda09104141cc23598b45d2e020f62230d4ef1e9167f51dd475
The command finished successfully!

```

Container log file:

[ 90m 2021-02-04 12:03:02.969 [39m [ 33mWARN [ 39m [ 1m STORE [ 22m: settings.json not found
[ 90m 2021-02-04 12:03:02.976 [39m [ 33mWARN [ 39m [ 1m STORE [ 22m: scenes.json not found
[ 90m 2021-02-04 12:03:02.977 [39m [ 33mWARN [ 39m [ 1m STORE [ 22m: nodes.json not found
/bin/sh: git: not found
[ 90m 2021-02-04 12:03:04.958 [39m  [ 32mINFO [ 39m [ 1m APP [ 22m: Version: 1.0.5

[ 90m 2021-02-04 12:03:04.958 [39m  [ 32mINFO [ 39m [ 1m APP [ 22m: Application path:/usr/src/app
[ 90m 2021-02-04 12:03:04.992 [39m  [ 31mERROR [ 39m [ 1m GATEWAY [ 22m: Zwave settings are not valid
[ 90m 2021-02-04 12:03:04.994 [39m  [ 32mINFO [ 39m [ 1m APP [ 22m: Listening on port 8091

**Comment by robertsLando** [comment]
@shreram what isn't working properly? logs are good, they just say that you haven't added any settings yet

**Comment by shreram** [comment]
I couldn't access http://localhost:8091 site to add any settings. I tried using the IP address but the same issue.

**Comment by shreram** [comment]
Nevermind. I found the issue with the docker container setup. For some reason, the 'host port' was empty. I corrected that and added 8091. Now I can access the UI.

![image](https://user-images.githubusercontent.com/16169720/107122383-1d6f1b00-685d-11eb-8f7a-43274c4f5d20.png)

**Comment by shreram** [comment]
How do I troubleshoot this error message?

[90m2021-02-06 10:04:47.776 [39m  [32mINFO [39m  [1mAPP [22m:  [0mGET /api/store  [32m200 [0m 2.648 ms - 220 [0m
[90m2021-02-06 10:04:49.044 [39m  [32mINFO [39m [1mAPP [22m:  [0mGET /api/store/%2Fusr%2Fsrc%2Fapp%2Fstore%2Fzwavejs_1.log [32m200 [0m 5.901 ms - 19155 [0m
[90m2021-02-06 10:04:59.962 [39m [32mINFO [39m [1mAPP [22m:  [0mGET /api/settings  [32m200 [0m 61.511 ms - 682 [0m
[90m2021-02-06 10:05:16.396 [39m  [32mINFO [39m  [1mGATEWAY [22m: Closing Gateway...
[90m2021-02-06 10:05:16.397 [39m  [32mINFO [39m  [1mZWAVE-SERVER [22m: Server closed
[90m2021-02-06 10:05:16.402 [39m  [32mINFO [39m  [1mMQTT [22m: Connecting to mqtt://192.168.86.226:1883
Logging to file:
/usr/src/app/store/zwavejs_1.log
[90m2021-02-06 10:05:16.406[39m [32mINFO[39m [1mZWAVE[22m: Connecting to /dev/ttyACM0
[90m2021-02-06 10:05:16.411[39m [32mINFO[39m [1mAPP[22m: [0mPOST /api/settings [32m200[0m 15.550 ms - 63[0m
[90m2021-02-06 10:05:16.412 [39m  [32mINFO [39m  [1mMQTT [22m: MQTT client connected
[90m2021-02-06 10:05:16.415 [39m  [32mINFO [39m  [1mZWAVE-SERVER [22m: ZwaveJS server listening on port 3000
[90m2021-02-06 10:05:21.676 [39m [32mINFO [39m  [1mAPP [22m:  [0mGET /api/store  [32m200 [0m 4.174 ms - 220 [0m
[90m2021-02-06 10:05:22.388 [39m  [32mINFO [39m  [1mZWAVE [22m: **Controller status: Driver: Failed to initialize the driver: Timeout while waiting for an ACK from the controller**

![image](https://user-images.githubusercontent.com/16169720/107123853-a68a5000-6865-11eb-892e-e00308a15b89.png)

**Comment by robertsLando** [comment]
@shreram Wrong path to controller I think

**Comment by shreram** [comment]
I had to restart my Unraid server to resolve this issue. It's all good. My Home Assistant instance was able to talk to Zwave WS server (via port 3000)

```
[90m2021-02-07 01:18:06.473[39m [33mWARN[39m [1mSTORE[22m: scenes.json not found
[90m2021-02-07 01:18:06.567[39m [33mWARN[39m [1mSTORE[22m: nodes.json not found
[90m2021-02-07 01:19:26.348[39m [32mINFO[39m [1mAPP[22m: Version: 1.0.5

[90m2021-02-07 01:19:26.348[39m [32mINFO[39m [1mAPP[22m: Application path:/usr/src/app
/bin/sh: git: not found
[90m2021-02-07 01:19:31.258[39m [32mINFO[39m [1mMQTT[22m: Connecting to mqtt://192.168.86.226:1883
Logging to file:
/usr/src/app/store/zwavejs_1.log
[90m2021-02-07 01:19:31.769[39m [32mINFO[39m [1mZWAVE[22m: Connecting to /dev/ttyACM0
[90m2021-02-07 01:19:31.811[39m [32mINFO[39m [1mAPP[22m: Listening on port 8091
[90m2021-02-07 01:19:31.823[39m [32mINFO[39m [1mMQTT[22m: MQTT client connected
[90m2021-02-07 01:19:31.837[39m [32mINFO[39m [1mZWAVE-SERVER[22m: ZwaveJS server listening on port 3000
[90m2021-02-07 01:19:48.954[39m [32mINFO[39m [1mZWAVE[22m: Zwave driver is ready

[90m2021-02-07 01:19:48.955[39m [32mINFO[39m [1mZWAVE[22m: Controller status: Driver ready

[90m2021-02-07 01:19:48.958[39m [32mINFO[39m [1mZWAVE[22m: Scanning network with homeid: 0xd7ddf230
[90m2021-02-07 01:19:49.498[39m [32mINFO[39m [1mZWAVE[22m: Node 1 is alive
[90m2021-02-07 01:19:49.500[39m [33mWARN[39m [1mZWAVE[22m: Node 1 doesn't support groups associations
[90m2021-02-07 01:19:49.501[39m [32mINFO[39m [1mZWAVE[22m: Node 1 ready: AEON Labs - ZW090 (Z‐Stick Gen5 USB Controller)

[90m2021-02-07 01:19:49.501[39m [32mINFO[39m [1mZWAVE[22m: Node 1: interview completed, all values are updated
[90m2021-02-07 01:19:49.586[39m [32mINFO[39m [1mZWAVE[22m: Node 2 is alive
[90m2021-02-07 01:19:49.622[39m [32mINFO[39m [1mZWAVE[22m: Node 4 is alive
[90m2021-02-07 01:19:49.676[39m [32mINFO[39m [1mZWAVE[22m: Node 8 is alive
[90m2021-02-07 01:19:49.706[39m [32mINFO[39m [1mZWAVE[22m: Node 9 is alive

```
