### ISSUE TITLE
[bug] Cannot send association to battery device becouse it is sleeping, but it's not

### ISSUE THREAD

**Issue by ODINServ** [zwave-js/zwavejs2mqtt#48]
Hi :),

Running the NPM way 3th december master (no more links to the node-zwave-js project)

Well i've got a new device (According to gateway webpage):
ThermoFloor | Wall Mounted Switch | Heatit Z Push Button 8

I want to create an association but it is not working, because the z wave software states that the device is asleep:
```zwavejs2mqtt/landing_buttons/status``` is ```{"time":1607006651989,"value":true,"status":"Asleep"}```

I see that the message is put into a queue:
```[REQ] SendData (SecurityCCCommandEncapsulation) [Node 18, asleep]```

Since it is a battery device i know that it needs to be woken before sending associations, which i do.
When i do that i see a new central scene updated on mqtt, so it should be awake, but the status stays asleep in the topic, even after receiving the central scene, and the queue is not send to the device.

According to the manual of the device it stays awake for 30 seconds after the button was pressed.

I send multiple times using the gateway webpage the association, and pressed multiple time a button on the device.

Console: [zwave-5945-console.log](https://github.com/zwave-js/zwavejs2mqtt/files/5636882/zwave-5945-console.log)
See logs: [zwave-5945.log](https://github.com/zwave-js/zwavejs2mqtt/files/5636884/zwave-5945.log)

Thnx!

**Comment by robertsLando** [comment]
@AlCalzone CC

**Comment by AlCalzone** [comment]
> Since it is a battery device i know that it needs to be woken before sending associations, which i do.
> When i do that i see a new central scene updated on mqtt, so it should be awake, but the status stays asleep in the topic

Battery-powered devices often send notifications or sensor readings while still asleep. When they do wake up, they send a `WakeUpNotification` (or sometimes a node information frame), after which the driver knows it can send its queued messages.

It is a common misconception that sending messages equals awake, although it might be true for this device. The manual is terrible in this regard. Please try one of the following procedures from the manual:
> press and hold down both the I- and O-buttons of Group 2 for 1 second to activate the Push Button for 7s. 

\- or -

> **How to send out Node Information Frame:**  
> Set the Push Button to adding/removing mode: Press and hold down both I- and O-buttons of Group 2 for 3 seconds. The LED indicator turns on to indicate that the Push Button has already sent out a Node Information Frame. The user may repeat the operation to turn the adding/removing mode of

**Comment by ODINServ** [comment]
Ah well indeed #RTFM, i was indeed misled from the fact it was reporting values!

Thnx for the support..
