### ISSUE TITLE
[bug] zwavejs2mqtt not starting - out of memory

### ISSUE THREAD

**Issue by dvbit** [zwave-js/zwavejs2mqtt#485]
Before submitting a bug please read: <https://zwave-js.github.io/zwavejs2mqtt/#/troubleshooting/bug_report>

### Version 
latest

Build/Run method
- [ X] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build )

zwavejs2mqtt version: latest
zwavejs version: latest

### Describe the bug

node bails out with out of memory message
`|___  /                      (_)   |__ \                | | | |  
   / /_      ____ ___   _____ _ ___   ) |_ __ ___   __ _| |_| |_ 
  / /\ \ /\ / / _` \ \ / / _ \ / __| / /| '_ ` _ \ / _` | __| __|
 / /__\ V  V / (_| |\ V /  __/ \__ \/ /_| | | | | | (_| | |_| |_ 
/_____|\_/\_/ \__,_| \_/ \___| |___/____|_| |_| |_|\__, |\__|\__|
                            _/ |                      | |        
                           |__/                       |_|        

2021-02-06 17:23:03.794 WARN STORE: scenes.json not found
/bin/sh: git: not found
2021-02-06 17:23:14.007 INFO APP: Version: 1.0.5
2021-02-06 17:23:14.012 INFO APP: Application path:/usr/src/app
2021-02-06 17:23:14.604 INFO MQTT: Connecting to mqtt://hass.fritz.box:1883
2021-02-06 17:23:15.117 INFO ZWAVE: Connecting to /dev/ttyACM0
2021-02-06 17:23:15.343 INFO APP: Listening on port 8091

<--- Last few GCs --->
lu[1:0x3541c30]    22946 ms: Mark-sweep 231.6 (234.8) -> 231.5 (234.8) MB, 191.4 / 0.1 ms  (+ 81.2 ms in 13 steps since start of marking, biggest step 16.1 ms, walltime since start of marking 295 ms) (average mu = 0.140, current mu = 0.081) allocation failu[1:0x3541c30]    23213 ms: Mark-sweep 231.9 (234.8) -> 231.8 (234.8) MB, 201.5 / 0.1 ms  (+ 54.8 ms in 5 steps since start of marking, biggest step 15.1 ms, walltime since start of marking 266 ms) (average mu = 0.093, current mu = 0.041) allocation failur

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x32600469 <JSObject>
    0: builtin exit frame: stringify(this=0x3260f925 <Object map = 0x5f3c1b1d>,0x3e180279 <undefined>,0x5d85a289 <JSFunction (sfi = 0x212fef8d)>,0x370ad5dd <Object map = 0x5f3fe185>,0x3260f925 <Object map = 0x5f3c1b1d>)

    1: arguments adaptor frame: 2->3
    2: serialize [0x277a2615] [/usr/src/app/node_modules/nedb/lib/model.js:~69] [pc=0x599f2ec8](this=0x27798219 <Object map = 0x3c25cb75>,0x370a...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory`

### Expected behavior

Zwavejs2mqtt running

**Comment by robertsLando** [comment]
@dvbit Disable persistent storage in mqtt settings, it's bugged

**Comment by robertsLando** [comment]
Ref #220

**Comment by dvbit** [comment]
@robertsLando grazie. I searched the issues before opening and could not find it. By the way, sticking to zwavejs2mqtt despite homeassistant is introducing a new integration. Your development is by far more flexible modular and advanced ;-)

**Comment by robertsLando** [comment]
Grazie a te :pray: :)

**Comment by RezzZ** [comment]
> @dvbit Disable persistent storage in mqtt settings, it's bugged

you mean disable this in mosquitto or in the settings inside zwavejs2mqtt.
it's a bit hard to disable in zwavejs2mqtt if it crashes on start.

I'll try to edit the settings.json then.
TIP: perhaps the file can be properly formatted as json instead of a 1liner?
makes it easier to edit.

**Comment by robertsLando** [comment]
@RezzZ Glad you fixed!
