### ISSUE TITLE
[bug] Issue with HASS discovery 

### ISSUE THREAD

**Issue by haavardNO** [zwave-js/zwavejs2mqtt#486]
Before submitting a bug please read: <https://zwave-js.github.io/zwavejs2mqtt/#/troubleshooting/bug_report>

### Version

Build/Run method

- [x] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build )

zwavejs2mqtt version: 1.0.5
zwavejs version: 6.1.2

### Describe the bug
After zwavejs2mqtt restart states will be repopulated in HASS and then retrigger automations.
Screenshot below is after delete data of device in mqtt explorer:
<img width="497" alt="Skjermbilde 2021-02-04 kl  20 00 07" src="https://user-images.githubusercontent.com/27728530/107125253-f8a09500-68a8-11eb-9474-9938c268478d.png">

Screenshot below is after zwavejs2mqtt restart.
<img width="498" alt="Skjermbilde 2021-02-06 kl  17 02 00" src="https://user-images.githubusercontent.com/27728530/107125204-becf8e80-68a8-11eb-82ff-0da676765024.png">

It has been a bit back and forth with this issue, and where to post it, so I hope I am doing it right 😊

**Comment by robertsLando** [comment]
After HASS first official release of zwave-js the number of issues have increased a lot. For this reason I have decided to focus on the issues related to the control panel functionalities and automatically close the ones related to MQTT discovery. I will not remove MQTT discovery support, I just prefer to focus on the control panel as the discovery is the focus of the zwavejs server now

**Comment by haavardNO** [comment]
@billiaz Did you have a chance to look at this?
I have had to disable my garage remote due to this behavior.
Can't risk my garage open in the middle of the night 😊

**Comment by aretakisv** [comment]
@haavardNO you are using MQTT discovery i suspect?
if so please export the Node using export button, next to the node causing this issue.
I remember we need to set a default value for HASS to understand if state is 0! but I am curious how HASS stays on 0

Giving me that ZIP can probably help me get it

**Comment by billiaz** [comment]
@haavardNO you are using MQTT discovery i suspect?
if so please export the Node using export button, next to the node causing this issue.
I remember we need to set a default value for HASS to understand if state is 0! but I am curious how HASS stays on 0

Giving me that ZIP can probably help me get it

**Comment by haavardNO** [comment]
Can get you that zip later today.

**Comment by haavardNO** [comment]
@billiaz see below.
[node_71.json.zip](https://github.com/zwave-js/zwavejs2mqtt/files/5986426/node_71.json.zip)

**Comment by haavardNO** [comment]
@billiaz Did you get the needed info from the zip? Let me know if there is anything else I can do to help

**Comment by billiaz** [comment]
omg! I forgot this! yes and no.  let me make a payload patch( and see if works). Will try to post asap the new payload

**Comment by haavardNO** [comment]
I have now actually put a small test environment with a dedicated pi and z-stick, so I can test on these devices without messing with the live z-wave network. So I am ready :)

**Comment by billiaz** [comment]
@haavardNO I am still scrambled :)

**Comment by haavardNO** [comment]
I am running the latest version.
When I was using zwave2mqtt the scene state would be set to "inactive" until a button was pressed, then it would represent pressed / hold / release etc...
