### ISSUE TITLE
[question] Failed to initialize the driver: Timeout while waiting for an ACK from the con troller

### ISSUE THREAD

**Issue by biiiink** [zwave-js/zwavejs2mqtt#487]
I am getting this error:

`18:13:25.087 SERIAL » 0x01030015e9 (5 bytes)
18:13:25.088 DRIVER » [REQ] [GetControllerVersion]
18:13:26.091 CNTRLR Failed to execute controller command after 2/3 attempts. Scheduling next try i
n 1100 ms.
18:13:27.193 SERIAL » 0x01030015e9 (5 bytes)
18:13:27.194 DRIVER » [REQ] [GetControllerVersion]
18:13:28.199 DRIVER Failed to initialize the driver: Timeout while waiting for an ACK from the con
troller
2021-02-06 18:13:28.199 INFO ZWAVE: Controller status: Driver: Failed to initialize the driver: Timeout while waiting for an ACK from the controller
18:13:28.200 DRIVER destroying driver instance...`

I am running this on Rancher/Kubernetes (which I am still learning) on a Proxmox VM.  I have passed the USB device through to the VM and can confirm it is working.  

I have created a HostPath to /dev/serial/by-id/usb-0658_0200-if00
I have then added a volume that directs to that hostpath with the mount point of /zwavestick
I enter in /zwavestick as the Serial Port in the Control Panel.

I'm not 100% sure this is the correct way of doing it, but its the only one i know at this point.

Also, every time i redeploy the workload, all the settings are reset.

**Comment by LordMike** [comment]
You can test by giving your pod access to all devices, via the [`privileged` option](https://docs.docker.com/engine/reference/run/#runtime-privilege-and-linux-capabilities). It's "worse" for security, but it could reveal if this is a permissions thing.

**Comment by biiiink** [comment]
> You can test by giving your pod access to all devices, via the [`privileged` option](https://docs.docker.com/engine/reference/run/#runtime-privilege-and-linux-capabilities). It's "worse" for security, but it could reveal if this is a permissions thing.

I did just try that.  Same result

**Comment by LordMike** [comment]
Oh - but wait.. You're using the device as a volume.. Devices are special in docker.. You need the `--device` parameter, and not volumes. What happens with `privileged`, and then using `/dev/serial/by-id/usb-0658_0200-if00` in zwavejs2mqtt ?

**Comment by biiiink** [comment]
> Oh - but wait.. You're using the device as a volume.. Devices are special in docker.. You need the `--device` parameter, and not volumes. What happens with `privileged`, and then using `/dev/serial/by-id/usb-0658_0200-if00` in zwavejs2mqtt ?

Just tried that.  still the same error. and then the serial port setting reverts back to the previous setting

**Comment by robertsLando** [comment]
THis is a user error, you need to check the correct path to the device and map it to the docker volume

**Comment by t-kozak** [comment]
Just FYI - I had the same problem. In my case, I am using a RaspberryPi, with the zwavejs2mqtt server running within container. I had a correct use of device config of docker compose, paths where correct.

In my case, I had to simply restart Raspi for the device to be visible.

**Comment by gmalbert** [comment]
> Just FYI - I had the same problem. In my case, I am using a RaspberryPi, with the zwavejs2mqtt server running within container. I had a correct use of device config of docker compose, paths where correct.
> 
> In my case, I had to simply restart Raspi for the device to be visible.

Thanks for this. I had the identical problem and a restart fixed it.

**Comment by seanmccabe** [comment]
Had the same issue, restart didnt resolve the issue, but a different USB port did.

**Comment by robertsLando** [comment]
For personal experience I can say this is not related to zwave-js or z2m, it's just the serial port that is not setup correctly from the OS for some reason
