### ISSUE TITLE
GC-TBZ48 gets 40 as max_temp setting in HASS JSON.

### ISSUE THREAD

**Issue by crzykidd** [zwave-js/zwavejs2mqtt#488]
### Version  

Build/Run method

- [X] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build )

zwavejs2mqtt version: 1.0.5
zwavejs version: 6.1.3

### Describe the bug
When adding the GC-TBZ48 thermostat the max_temp is set in the JSON for HASS to 40.  I believe this is being pulled from: ./hass/configuration.js    This is the only place I can find reference to it.  The device has a setting for max temp and the default is 90.   

In addition the temp_step is set to 0.5 for this device is really should be 1  

### To Reproduce
Add GC-TBZ48 and notice that max temp in HA is 40 and the step temp is 0.5

### Expected behavior

max temp should be 90, and step temp should be 1

### Additional context

The GC-TBZ48 I am discovering comes in as:
0x014f-0x5437-0x5442

More details in Slack convo:  https://zwave2mqtt.slack.com/archives/C01DQ24SDKL/p1612651938354900
[node53_debug.txt](https://github.com/zwave-js/zwavejs2mqtt/files/5937867/node53_debug.txt)

**Comment by robertsLando** [comment]
@crzykidd Change it in devices.js?
