### ISSUE TITLE
Valueup arrows in Graph view not working in Chrome [bug]

### ISSUE THREAD

**Issue by chrish987** [zwave-js/zwavejs2mqtt#491]
Before submitting a bug please read: <https://zwave-js.github.io/zwavejs2mqtt/#/troubleshooting/bug_report>

### Version

Build/Run method

- [X ] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build )

Latest release image

### Describe the bug

In the graph view clicking on the UP arrow to increase one of the display values does not work, value goes down. Seems like down arrow is selected instead and value decreases.

Works in Firefox, broken in Chrome (both Windows).

Not a major - but worth reporting.

**Comment by robertsLando** [comment]
@chrish987 The graph has been completely rewritten. Wait for it: #458
