### ISSUE TITLE
Update Aeotec Nano Dimmer firmware not working

### ISSUE THREAD

**Issue by atterdal** [zwave-js/zwavejs2mqtt#493]
I've downloaded the EU version of the latest Aeotec Nano Dimmer (v2.03) from aeotecs support site. Changed the name of the .ex_ file to .exe. 

When I try to update the old device (v1.2?) I get the message: Error while calling api beginFirmwareUpdate: Unable to extract firmware from file: This does not appear to be a valid Aeotec updater (invalid firmware length)!

What am I doing wrong?

**Comment by robertsLando** [comment]
@AlCalzone Sugestions here?

**Comment by AlCalzone** [comment]
@atterdal send me the file please

**Comment by atterdal** [comment]
[OTA of Nano Dimmer_EU_C_V2_03.zip](https://github.com/zwave-js/zwavejs2mqtt/files/5938870/OTA.of.Nano.Dimmer_EU_C_V2_03.zip)

**Comment by atterdal** [comment]
The .exe file's in that zip. Thank you!

**Comment by scott7685** [comment]
I believe that EXE is the standalone firmware update w/ an EXE designed to be used as an executable whilst the Aeotec stick is plugged into your PC. Ie, it is not the raw hex version you would need for a firmware update through a controller like ZWaveJS2MQTT.

Not for this particular one, but I have found there are people on various forums that have extracted the hex firmware out of the exe and posted the file for download to use.

Example:
https://forums.homeseer.com/forum/homeseer-products-services/system-software-controllers/z-flash-software/105783-hex-file-for-aeotec-multisensor-6

**Comment by AlCalzone** [comment]
@scott7685 zwave-js supports extracting the raw firmware from Aeotec updater exes.

**Comment by scott7685** [comment]
MIND = BLOWN @AlCalzone 

That is phenomenal. I have used it to upload the extracted hex but have never tried a full exe

**Comment by AlCalzone** [comment]
@atterdal seems like that file had another variation that I haven't encountered yet. The linked PR should fix this.

**Comment by atterdal** [comment]
There's a standard for everything I guess. Thank you so much!

**Comment by AlCalzone** [comment]
> There's a standard for everything I guess

Not when it comes to reverse-engineering 😅

**Comment by billiaz** [comment]
@AlCalzone Faced the same with TriSensor, I will try to test with your PR

**Comment by razvanws** [comment]
It seems that it's the same issue with v3.02 EU firmware of Aeotec ZW132. Please see the firmware below:
https://aeotec.freshdesk.com/helpdesk/attachments/6120512641

**Comment by AlCalzone** [comment]
Found it - just a matter of allowing spaces in the embedded firmware name. Fix is on the way.

**Comment by atterdal** [comment]
I've pulled the latest Docker image (master, updated 8 hours ago) but I still get the same error message.

Is the Docker not in sync with this repo?

**Comment by robertsLando** [comment]
@atterdal Docker image is sync with zwavejs2mqtt master branch, and latest zwave-js __release__

**Comment by atterdal** [comment]
Too be safe I waited for new release and updated to latest master on docker. Still get this message when trying to update:

```
zwavejs2mqtt     | 2021-02-17 13:42:47.495 INFO ZWAVE: Failed to start the update: Invalid manufacturer or firmware id! beginFirmwareUpdate {
zwavejs2mqtt     |   success: false,
zwavejs2mqtt     |   message: 'Failed to start the update: Invalid manufacturer or firmware id!'
zwavejs2mqtt     | }


```

Is it related to the node I'm trying to update register as "Unkown product 111" from "Unkown Manufacturer 134"?
<img width="1564" alt="Skärmavbild 2021-02-17 kl  14 50 15" src="https://user-images.githubusercontent.com/2734444/108213580-7b3e1580-712f-11eb-9851-8afd7e690c48.png">

**Comment by AlCalzone** [comment]
Hmm, my test case with current node-zwave-js master still works. So there's probably some version mismatch.

**Comment by atterdal** [comment]
It says "App version: 1.1.1" "Zwavejs Version: 6.4.0"

**Comment by AlCalzone** [comment]
You did load the exe from the zip file above?
@robertsLando maybe another artefact of the duplicate dependencies due to zwave-js-server?

**Comment by atterdal** [comment]
Yes, same .exe as I sent before. Is it expected that the node shows up as "Unkown product 111" and "Unkown manufacturer 134"?

**Comment by robertsLando** [comment]
> @robertsLando maybe another artefact of the duplicate dependencies due to zwave-js-server?

I'm waiting for the new beta 7 release, that should be fixed then

**Comment by robertsLando** [comment]
@atterdal just to be sure, are you using `master` or `dev` tag ?

**Comment by atterdal** [comment]
@robertsLando master

**Comment by robertsLando** [comment]
Ok that should have the latest things so. Sincerly I dunno what's wrong here :(

**Comment by johanschelin** [comment]
Hi!
@robertsLando - I have a bunch of Heltun Devices that i need to firmware update, and was hoping that 
ZWaveJSMQTT would help me to do. I can use my firmware update files in the ZWave.me application, but am unable to update through ZwaveJSmqtt. No issues adding them to my controller, but when i try a OTA update it gives me
"Error when calling API befinFirmwareUpdate: Unable to extract firmware from file: Could not parse HEX firmware file!"

![image](https://user-images.githubusercontent.com/65488934/119550662-f51e1480-bd98-11eb-8e54-d71bfedabcc6.png)

Attached the .ota file zipped if you can see anything that makes the update crash?

[TPS03_EU_v2_3_3.zip](https://github.com/zwave-js/zwavejs2mqtt/files/6541596/TPS03_EU_v2_3_3.zip)

**Comment by johanschelin** [comment]
> Hi!
> @robertsLando - I have a bunch of Heltun Devices that i need to firmware update, and was hoping that
> ZWaveJSMQTT would help me to do. I can use my firmware update files in the ZWave.me application, but am unable to update through ZwaveJSmqtt. No issues adding them to my controller, but when i try a OTA update it gives me
> "Error when calling API befinFirmwareUpdate: Unable to extract firmware from file: Could not parse HEX firmware file!"
> 
> ![image](https://user-images.githubusercontent.com/65488934/119550662-f51e1480-bd98-11eb-8e54-d71bfedabcc6.png)
> 
> Attached the .ota file zipped if you can see anything that makes the update crash?
> 
> [TPS03_EU_v2_3_3.zip](https://github.com/zwave-js/zwavejs2mqtt/files/6541596/TPS03_EU_v2_3_3.zip)

And - as @atterdal above, my device is also "unknown" manufacturer by zwavejsmqtt.
![image](https://user-images.githubusercontent.com/65488934/119551008-69f14e80-bd99-11eb-8b31-dc94de104e18.png)

Is there a way to make zwavejs read the manufacturer xml from the device? Zwave.me can read this. :)

**Comment by AlCalzone** [comment]
@johanschelin can you open a new issue for this in https://github.com/zwave-js/node-zwave-js please?

**Comment by tommyjlong** [comment]
For the record, using zwjs2mqtt 5.2 zwjs 7.10, was successful in updating .exe firmware to Aeotec HEM-G5.
