### ISSUE TITLE
[feat] Frontend Authentication

### ISSUE THREAD

**Issue by MikeFez** [zwave-js/zwavejs2mqtt#505]
**Is your feature request related to a problem? Please describe.**
This isn't a problem, but I'd like to see support for an authentication method for the UI. I plan on setting up a reverse proxy for this service, and while I can set up basic auth through NGINX, having a UI for username/password would allow for easier auth population for those of us who use password managers.

**Describe the solution you'd like**
An auth setting which allows for a username & password. Unauthenticated users would face a login prompt upon navigating to the UI. LDAP (or other identity services) would be a nice-to-have feature, but could be implemented further down the road.

**Describe alternatives you've considered**
nginx (or alternative services) can provide basic auth at this time

**Additional context**
N/A

**Comment by robertsLando** [comment]
Actually this can be done by using nginx. BTW this is in my TODOs

**Comment by MikeFez** [comment]
Absolutely, I also included the ability to use basic auth via nginx in the original post for the people out there who stumble across it. Great to know it's on the list of TODO's, thanks @robertsLando
