### ISSUE TITLE
Avoid stopping the container before zwave-js has shut down and saved the cache

### ISSUE THREAD

**Issue by AlCalzone** [zwave-js/zwavejs2mqtt#506]
> Whoa that shouldn't happen. @robertsLando any idea how we could avoid stopping the container before zwave-js has shut down and saved the cache?

We should listen for the container kill command with `process.on` and try to gracefully close it there

_Originally posted by @robertsLando in https://github.com/zwave-js/node-zwave-js/issues/1578#issuecomment-775251454_

**Comment by snagytx** [comment]
This might be caused by the fact that the shutdown takes more than 10 seconds.

https://docs.docker.com/engine/reference/commandline/stop/

**Comment by robertsLando** [comment]
@snagytx On my side I look for `SIGINT`, if you are using docker compose or docker could you set `SIGINT` as stop signal? 

I remember now I already worked on this in the past and it was working: https://github.com/zwave-js/zwavejs2mqtt/blob/master/docker/docker-compose.yml#L8

Source code: https://github.com/zwave-js/zwavejs2mqtt/blob/master/app.js#L477

**Comment by roflmao** [comment]
Discussion: https://stackoverflow.com/questions/50898134/what-does-docker-stopsignal-do
Docs: https://docs.docker.com/engine/reference/builder/#stopsignal

**Comment by robertsLando** [comment]
I used SIGINT as that is the signal sent when you press Ctrl+C in the terminal. BTW I could add the stop signal to the dockerfile instread of just leaving it on docker compose. Like @roflmao pointed out in docs link, Thoughts?

**Comment by snagytx** [comment]
My docker-compose.yaml has `stop_signal: SIGINT` but the issue was still sporadically seen. 

I can also see:

```
2021-02-09 16:16:42.253 INFO APP: Closing clients...
2021-02-09 16:16:42.254 INFO GATEWAY: Closing Gateway...
2021-02-09 16:16:42.279 INFO ZWAVE-SERVER: Server closed
```

but I did not capture the logs in the bad case.

I just added `stop_grace_period: 30s` just for extra safety, in case the driver needs more than 10s to stop.

**Comment by robertsLando** [comment]
If you see those lines it means I'm catchin the stop signal correctly. BTW I don't think that the driver needs more then few seconds to store its context to files. @AlCalzone ?

**Comment by snagytx** [comment]
Just to clarify, the file `f4c9e959.json` is only sporadically left empty, I was not able to find a pattern.

**Comment by AlCalzone** [comment]
I don't suppose that should take long, only for large networks maybe.

**Comment by scyto** [comment]
I have seen the same issue, when it happens to me the main cache file is not left empty, rather it is zeroed on next start with this error
```
16:52:20.677 DRIVER   Cache file for homeId 0xdef5ff7b found, attempting to restore the network from cache...
16:52:20.698 DRIVER   Restoring the network from cache failed: SyntaxError: Unexpected end of JSON input
```
This was generated using docker-compose stop and docker-compose start.
I had `stop_signal: SIGINT` in my docker-compose.yml
I did NOT have `stop_grace_period: 10s` in my docker-compose.yml  (off to test that now, just need to wait 30 mins)

(as an aside i now realize this plus the lock code enumeration time at boot is why i get 26 minute first start many times, not comms issues, in my repro earlier in the week it seems manually deleting the main cache file is not enough to trip the same behavior).

**Comment by scyto** [comment]
and on my second test after adding `stop_grace_period: 10s` the file was zeroed after doing docker-compose stop

I also notice that after i stopped the container something was writing to zwavejs2mqtt.log - for like a minutes or two after the container was stopped and reported as `stopped by docker container ls` how is that possible?  (i was running tail -f against both logs).

**Comment by scyto** [comment]
> Just to clarify, the file `f4c9e959.json` is only sporadically left empty, I was not able to find a pattern.

did you manage to stop this happening?

**Comment by robertsLando** [comment]
@scyto I don't think this is something on my side, maybe the driver destroy method isn't waiting enough? @AlCalzone 

SIGINT detected: https://github.com/zwave-js/zwavejs2mqtt/blob/master/app.js#L850
Gsateway close is called: https://github.com/zwave-js/zwavejs2mqtt/blob/master/lib/Gateway.js#L940
Zwave client close and driver destroy: https://github.com/zwave-js/zwavejs2mqtt/blob/master/lib/ZwaveClient.js#L1404

**Comment by AlCalzone** [comment]
Hmm, to debug you could try adding a log message just before the driver destroy method ends:
`node_modules\zwave-js\build\lib\driver\Driver.js`, line 874 (probably)

```diff
        // destroy loggers as the very last thing
+       this.driverLog.print("driver instance destroyed");
        this._logContainer.destroy();
```

From the log above it does look like it all goes through. Would be interesting to see what exactly is logged after the container is stopped.
