### ISSUE TITLE
[bug] v1.1.0 does not include upstream fixes for zwave-js, despite changelog

### ISSUE THREAD

**Issue by openfirmware** [zwave-js/zwavejs2mqtt#511]
Before submitting a bug please read: <https://zwave-js.github.io/zwavejs2mqtt/#/troubleshooting/bug_report>

### Version

Build/Run method

- [ ] Docker
- [X] PKG
- [ ] Manually built (git clone - npm install - npm run build )

zwavejs2mqtt version: 1.1.0
zwavejs version: 6.1.3 (see context section)

### Describe the bug

I downloaded the latest zwavejs2mqtt release ([v1.1.0](https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v1.1.0)) so that I could test an upstream bugfix in zwave-js ([link](https://github.com/zwave-js/node-zwave-js/pull/1583)). As the v1.1.0 patch notes mention that zwave-js 6.1.3 is included, the fix should be there.

Unfortunately, it is not; when trying to update the LED parameter on the switches, it reverts to the previous value, just as it did before the fix made for zwave-js.

### To Reproduce

1. Download zwavejs2mqtt v1.1.0 release from GitHub to Debian/Ubuntu
2. Unzip and copy the store directory from previous version of zwavejs2mqtt
3. Start up zwavejs2mqtt, goto web interface
4. Try to change Configuration Parameter 15-112-0-13 "LED Indicator Color" on Inovelli LZW31-SN switch to 170 from 42
5. Watch it "submit", then revert to the previous value in a second

### Expected behavior

The submitted value should be accepted. Last week I tried deploying zwavejs2mqtt via NodeJS with a manual patch to `@zwave-js` in the `node_modules` to fix the configuration parameter, and it did work then.

### Additional context

The [dependabot PR for the zwave-js 6.1.3 update](https://github.com/zwave-js/zwavejs2mqtt/pull/464) did get merged for v1.1.0, and this can be seen in the `package.json` ([permalink](https://github.com/zwave-js/zwavejs2mqtt/blob/3c5f617b0b8b25b6a8f7084e87ed8359d94458f8/package.json#L132)). However in the `package-lock.json` we can see that `@zwave-js/core` is still 6.1.1 ([permalink](https://github.com/zwave-js/zwavejs2mqtt/blob/3c5f617b0b8b25b6a8f7084e87ed8359d94458f8/package-lock.json#L4342)).

I haven't tried building it locally from source and forcing an update to the package lock file so I don't know for sure if this is the cause, but it is odd!

**Comment by jcam** [comment]
As you can see here, zwave-js/core is still at version 6.1.1 even in the final 6.1.3 update of node-zwave-js, so that is not a clear indication that it hasn't actually picked up the changes.
![image](https://user-images.githubusercontent.com/98744/107320637-19b2e280-6a6f-11eb-8acd-e0e0e244548d.png)

**Comment by openfirmware** [comment]
Yes, that makes sense. I checked with the zwavejs2mqtt dashboard that I am running and noticed that it says App Version 1.1.0 with Zwavejs version 6.1.2, so something appears to be missing.
