### ISSUE TITLE
Add a unique message id to each mqtt message [feat]

### ISSUE THREAD

**Issue by chrish987** [zwave-js/zwavejs2mqtt#512]
I have some workflows that need to ensure that they are not processing an 'old' message.

I can kind of tell message uniqueness by checking for a number of fields (currently lastupdate + nodeid + property) but it would be better to have a unique message id in every message.

Maybe a UUID?

I think ok to use a new message id on restart etc when publishing all current values. So every message that is sent would be 'new' from zwavejs2mqtt perspective, but when external clients are picking retained messages they can see if they processed it before.

**Comment by robertsLando** [comment]
Isn't the time in the payload like an uuid? YOu could simply store the timestamp in unix format along with the topic, if the received message in a specific topic has the same timestamp it means it's an old one

**Comment by chrish987** [comment]
can you guarantee that the timestamp is unique? there are multiple nodes sending to the same topics. I know that you can be 'fairly certain' be comparing a few fields (timestamp, nodeid, property) that the message is unique - but I guess it is pretty easy to add a unique message id - then we can be sure.

**Comment by robertsLando** [comment]
it's a serial protocol, it's impossible that two messages are emitted with the same timestamp, at least for sure not from the same device. If you keep track of ` valueId topic ---> timestamp ` you are done.
