### ISSUE TITLE
Saving config always needs to do a restart? [feat]

### ISSUE THREAD

**Issue by chrish987** [zwave-js/zwavejs2mqtt#513]
It seems that any config change (and clicking save on the bottom of the config page) does a full restart and all nodes go back to RefreshFromCache / through the startup process - which can take some time.

Is it always necessary to do a restart?

For example when adding a new gateway config item. Even a simple change seems to need a restart to take affect. For example changing the retain setting (with the new feature - great thanks).

**Comment by robertsLando** [comment]
@chrish987 Checking all config changes and apply them when possible and rtestart only in some conditions is really difficult to handle and also could cause many inconsistence problems. BTW you shouldn't need to modify those settings very often so the effort to implement such feature wouldn't be so useful
