### ISSUE TITLE
[feat] Get Zwave2Mqtt version over MQTT

### ISSUE THREAD

**Issue by Diddlik** [zwave-js/zwavejs2mqtt#53]
Is it possible to send a version of currently installed zwave2mqtt to mqtt?

The Idea is to create one atomation / notification if there are a new version

 Ideal would be a topic with the current version and the currently available master/dev. But the current one would be very helpful.

**Comment by robertsLando** [comment]
Done

**Comment by Diddlik** [comment]
When I update docker, is the new version automatically downloaded or only when it is released?

**Comment by robertsLando** [comment]
@Diddlik If you are using `dev` tag that is always synced with latest master commit. Just wait 30 min after the commit is done to let the build create and push the image to dockerhub
