### ISSUE TITLE
[feat] Only reload Zwave driver if changes to Zwave-partition in settings were made 

### ISSUE THREAD

**Issue by jmgiaever** [zwave-js/zwavejs2mqtt#539]
**Is your feature request related to a problem? Please describe.**

It seems like the zwave driver is destroyed and re-initialized whenever you update any settings in the UI. Is this necessary? 

**Describe the solution you'd like**
E.g fiddling with the settings in general, MQTT Gateway and Home Assistant sections shouldn't require this action, since a restart can take a long time.

**Comment by robertsLando** [comment]
> It seems like the zwave driver is destroyed and re-initialized whenever you update any settings in the UI. Is this necessary?

I got this question many times. The short answer is Yes, it is. The effort to make updates based on the changed settings is huge and still could create some other bugs I want to prevent. In general settings should never change once you set the correct driver path. The only thing that could someway be loaded without a restart is the zwavejs2mqtt logs settings. All the others settings require a restart to make sure everything is correct

**Comment by jmgiaever** [comment]
I see. Thanks for clearing this up. :)
