### ISSUE TITLE
[bug] Battery devices shows as powered in mesh

### ISSUE THREAD

**Issue by jmgiaever** [zwave-js/zwavejs2mqtt#546]
### Version

Build/Run method

- [ ] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build )
- [x] Snap package

zwavejs2mqtt version: 1.1.1
zwavejs version: 6.2.0

### Describe the bug

![Screenshot from 2021-02-10 21-05-12](https://user-images.githubusercontent.com/7188121/107565324-db8aff80-6be3-11eb-9872-1227dd5302f7.png)

This is a Fibaro door/window sensor

Let me know which files you'll need and I'll send them to you :)

**Comment by robertsLando** [comment]
@jmgiaever a node export would be good :)

**Comment by chrish987** [comment]
i see this as well on Aeon/Aeotec MultiSensor 6 devices. Icon is correct in the graph, but hovering over a mains node shows power source as battery in the popup.

![snip](https://user-images.githubusercontent.com/77754678/107690171-a29b7980-6d0e-11eb-878a-ec16c8045d56.JPG)

**Comment by robertsLando** [comment]
Strange, so the hover shows it's battery, the icon is wrong. Could someone send me a node export?

**Comment by jmgiaever** [comment]
> @jmgiaever a node export would be good :)

Hi, which file would that be? HomeHex.json?

**Comment by robertsLando** [comment]
I think that could be due to this statements: 

`forwards: node.ready && !node.failed && node.isListening`

`entity.shape =
            entity.forwards || batlev === undefined ? 'rect' : 'battery'`

Based on this it could be that `forwards` is evaluated to `true` even if the device is a battery device. @AlCalzone AFAIK a battery device cannot forword packets, so based on this what do you think it's wrong in the `forwords` formula?

**Comment by AlCalzone** [comment]
I think this is another case of that sensor thinking it is USB powered:
https://github.com/zwave-js/node-zwave-js/issues/1578
https://github.com/zwave-js/node-zwave-js/issues/1504

It was likely included with USB and then used with Batteries - but as far as the Z-Wave network is concerned, it looks like a listening device.

**Comment by robertsLando** [comment]
Humm, I think that instead of doing that check, I will just check if battery CC exiusts, in that case I will use the battery shape...

**Comment by jmgiaever** [comment]
> It was likely included with USB and then used with Batteries - but as far as the Z-Wave network is concerned, it looks like a listening device.

Mine is a Fibaro Door/Window sensor 2, and it wasn't included with USB (it doesn't have any).

@robertsLando Let me know if you need files. :)

**Comment by AlCalzone** [comment]
> Mine is a Fibaro Door/Window sensor 2

Does zwave-js know the battery level yet?
