### ISSUE TITLE
[bug] Memory leak when using with UNRAID

### ISSUE THREAD

**Issue by cazador481** [zwave-js/zwavejs2mqtt#548]
Before submitting a bug please read: <https://zwave-js.github.io/zwavejs2mqtt/#/troubleshooting/bug_report>

### Version

Build/Run method

- [X ] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build )

docker 1.1.1
### Describe the bug
After about 3 hours I have over a gig of memory usage used.  After about 12 hours, I have over 12 gigs.  Those numbers are reported via unraid , but I ran top to verify that the node/www was using that amount too. 

I tried to turn off logging, to see if that would help it slowed the memory expansion but did not stop it.
What information can I provide you to help debug the problem?

**Comment by robertsLando** [comment]
How many devices do you have in your network?

**Comment by robertsLando** [comment]
@cazador481 Could you also provide some logs files or else?
