### ISSUE TITLE
Shouldn't npm run build generate a new copy of bin/www?

### ISSUE THREAD

**Issue by ratsputin** [zwave-js/zwavejs2mqtt#554]
Okay, maybe I'm missing something here, but I follow the instructions at `https://zwave-js.github.io/zwavejs2mqtt/#/getting-started/quick-start` and the `npm run build` isn't generating a new version of `bin/www`, nor is it generating any errors.

Here's what I'm seeing:

```
zwave@zwave:~ $ git clone https://github.com/zwave-js/zwavejs2mqtt
Cloning into 'zwavejs2mqtt'...
remote: Enumerating objects: 51, done.
remote: Counting objects: 100% (51/51), done.
remote: Compressing objects: 100% (39/39), done.
remote: Total 6710 (delta 23), reused 31 (delta 12), pack-reused 6659
Receiving objects: 100% (6710/6710), 9.26 MiB | 3.55 MiB/s, done.
Resolving deltas: 100% (4672/4672), done.
zwave@zwave:~ $ cd zwavejs2mqtt/
zwave@zwave:~/zwavejs2mqtt $ npm install

added 2229 packages, and audited 2230 packages in 5m

found 0 vulnerabilities
zwave@zwave:~/zwavejs2mqtt $ ls -Flash bin
total 12K
4.0K drwxr-xr-x  2 zwave zwave 4.0K Feb 11 06:52 ./
4.0K drwxr-xr-x 22 zwave zwave 4.0K Feb 11 06:52 ../
4.0K -rw-r--r--  1 zwave zwave 1.7K Feb 11 06:52 www
zwave@zwave:~/zwavejs2mqtt $ mv bin/www bin/save-www
zwave@zwave:~/zwavejs2mqtt $ npm run build

> zwavejs2mqtt@1.1.1 build
> node build/build.js

assets by path static/favicons/ 49.4 KiB
  assets by path static/favicons/*.png 46.3 KiB 6 assets
  asset static/favicons/safari-pinned-tab.svg 2.51 KiB [emitted] [from: static/favicons/safari-pinned-tab.svg] [copied]
  asset static/favicons/site.webmanifest 409 bytes [emitted] [from: static/favicons/site.webmanifest] [copied]
  asset static/favicons/browserconfig.xml 246 bytes [emitted] [from: static/favicons/browserconfig.xml] [copied]
assets by info 2.71 MiB [immutable]
  assets by path static/fonts/ 500 KiB 4 assets
  assets by status 2.22 MiB [big]
    asset static/js/app.30b0f469d1365694e17a.js 1.61 MiB [emitted] [immutable] [minimized] [big] (name: app) 2 related assets
    asset static/css/app.fdb61245954270e06feb.css 626 KiB [emitted] [immutable] [big] (name: app) 1 related asset
asset static/favicon.ico 14.7 KiB [emitted] [from: static/favicon.ico] [copied]
asset static/logo.png 9.78 KiB [emitted] [from: static/logo.png] [copied]
asset static/.gitkeep 0 bytes [emitted] [from: static/.gitkeep] [copied]
Entrypoint app [big] 2.22 MiB (1.2 MiB) = static/js/app.30b0f469d1365694e17a.js 1.61 MiB static/css/app.fdb61245954270e06feb.css 626 KiB 6 auxiliary assets

WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets:
  static/js/app.30b0f469d1365694e17a.js (1.61 MiB)
  static/css/app.fdb61245954270e06feb.css (626 KiB)

WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  app (2.22 MiB)
      static/js/app.30b0f469d1365694e17a.js
      static/css/app.fdb61245954270e06feb.css


WARNING in webpack performance recommendations:
You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
For more info visit https://webpack.js.org/guides/code-splitting/

webpack 5.21.2 compiled with 3 warnings in 112358 ms

  Build complete.

  Tip: built files are meant to be served over an HTTP server.
  Opening index.html over file:// won't work.

zwave@zwave:~/zwavejs2mqtt $ ls -Flash bin
total 12K
4.0K drwxr-xr-x  2 zwave zwave 4.0K Feb 11 06:58 ./
4.0K drwxr-xr-x 23 zwave zwave 4.0K Feb 11 07:00 ../
4.0K -rw-r--r--  1 zwave zwave 1.7K Feb 11 06:52 save-www
zwave@zwave:~/zwavejs2mqtt $
```
Note there is no fresh version of `bin/www`.

Am I missing something here?  Do I need to do something differently?  I'm running on a Raspberry Pi.

**Comment by robertsLando** [comment]
I don't get your question, it doesn't mean anything, what do you want to do?? 

The build command generates the files needed on the ffront end in dist folder

**Comment by ratsputin** [comment]
Ah.  I guess I was confused.  How do I generate a fresh version of `bin/www` to use the latest version of any module (such as an updated version of zwave-js) I install?  I thought the commands in the quick start would build it.

**Comment by robertsLando** [comment]
how much familiar are you with nodejs?

**Comment by ratsputin** [comment]
Not at all.  While I have a development background, I have zero experience with this.

If there is a set of instructions for doing the build, I'm happy to read and follow them.  I had just expected that running the build would generate a new version of the executable.  I'm certainly not expecting you to hold my hand through learning how to build a nodejs package.

If there aren't instructions, feel free to close this; you have much more important things to do than teach me how to do a build.

**Comment by robertsLando** [comment]
The project has a frontend and a backend. When you need to run the application in a production environment you have to build the frontend (in poor words all the vue stuff is translated intto css/js/html files) to do this you run `npm run build` and you will see all the generated files in `dist` folders. Now to run the server just run `npm run start` and a server listening on portr 8091 will be started.


Don't forget to also run an `npm install` before everything in order to install all dependencies needed

**Comment by ratsputin** [comment]
Understood.  As far as I can tell, behind the scenes, `npm run start` just executes `bin/www`.  Apparently, the release process is creating a new version with the appropriate `zwave-js` libraries that provides `bin/www`.  I noticed the following when I was testing `fix-555`:
```
zwave@zwave:~/zwavejs2mqtt $ git fetch origin fix-555
From https://github.com/zwave-js/zwavejs2mqtt
 * branch            fix-555    -> FETCH_HEAD
zwave@zwave:~/zwavejs2mqtt $ git checkout fix-555
M       bin/www
M       package-lock.json
Branch 'fix-555' set up to track remote branch 'fix-555' from 'origin'.
Switched to a new branch 'fix-555'
zwave@zwave:~/zwavejs2mqtt $
```
Looking at the `Dockerfile.contrib` file, it looks like I need to build the latest `node-zwave-js` first by running all of the `yarn` commands to get a fresh copy of `bin/www`.

I suppose I could start using Docker but I'm really not a fan.

In any case, thanks for all of your hard work on this.  It's really appreciated.  This has allowed me to get off of SmartThings and gain local control of my Z-Wave network.
