### ISSUE TITLE
Cover state is not being interpreted correctly in Home Assistant

### ISSUE THREAD

**Issue by ratsputin** [zwave-js/zwavejs2mqtt#555]
Before submitting a bug please read: <https://zwave-js.github.io/zwavejs2mqtt/#/troubleshooting/bug_report>

### Version

Build/Run method

- [ ] Docker
- [ ] PKG
- [x] Manually built (git clone - npm install - npm run build )

zwavejs2mqtt version: `1.1.1.5bba9ae`
zwavejs version: `6.1.3-0-pr-1337-77c6cad`

### Describe the bug

While new cover feature works correctly from zwavejs2mqtt control panel, cover is showing an "unknown" state in Home Assistant and cannot be controlled.

### To Reproduce

1. Add cover device in zwavejs2mqtt with Home Assistant discovery enabled
2. Check that device shows up in Home Assistant (in my case, it's `home_garagedoor`)
3. From the Developer Tools, check the status of the cover (in my case, `cover.home_garagedoor_barrier_state`)
4. Status is "unknown"

### Expected behavior

Status should be Open or Closed with the ability to open/close the garage door.

### Additional context

From MQTT: `cover/Home-GarageDoor/barrier_state/config`:
```
{
	"command_topic": "zwave/Home/34/102/0/targetState/set",
	"state_topic": "zwave/Home/34/102/0/currentState",
	"value_template": "{{ value_json.value }}",
	"device_class": "garage",
	"payload_open": "Opened",
	"payload_close": "Closed",
	"payload_stop": "Stopped",
	"state_open": "Opened",
	"state_opening": "Opening",
	"state_closed": "Closed",
	"state_closing": "Closing",
	"device": {
		"identifiers": [
			"zwavejs2mqtt_0xca51aa0a_node34"
		],
		"manufacturer": "Nortek Security & Control LLC",
		"model": "Garage Door Controller (NGD00Z-4)",
		"name": "Home-GarageDoor",
		"sw_version": "2.1"
	},
	"name": "Home-GarageDoor_barrier_state",
	"unique_id": "zwavejs2mqtt_0xca51aa0a_34-102-0-currentState"
}
```
From MQTT: `Home/34/102/0/currentState`:
```
{
	"id": "34-102-0-currentState",
	"nodeId": 34,
	"commandClass": 102,
	"commandClassName": "Barrier Operator",
	"endpoint": 0,
	"property": "currentState",
	"propertyName": "currentState",
	"type": "number",
	"readable": true,
	"writeable": false,
	"label": "Current Barrier State",
	"stateless": false,
	"min": 0,
	"max": 255,
	"list": true,
	"states": [
		{
			"text": "Closed",
			"value": 0
		},
		{
			"text": "Closing",
			"value": 252
		},
		{
			"text": "Stopped",
			"value": 253
		},
		{
			"text": "Opening",
			"value": 254
		},
		{
			"text": "Open",
			"value": 255
		}
	],
	"value": 0,
	"isCurrentValue": true,
	"targetValue": "102-0-targetState",
	"lastUpdate": 1613050943752
}
```
Home Assistant version 2021.1.5 shows:
![image](https://user-images.githubusercontent.com/32401888/107645206-0b66f100-6c3e-11eb-99f9-29e5b2f353de.png)

**Comment by robertsLando** [comment]
@billiaz

**Comment by billiaz** [comment]
@ratsputin we need to replace strings with numbers in statuses
Reading the states from mqtt:
```	"states": [
		{
			"text": "Closed",
			"value": 0
		},
		{
			"text": "Closing",
			"value": 252
		},
		{
			"text": "Stopped",
			"value": 253
		},
		{
			"text": "Opening",
			"value": 254
		},
		{
			"text": "Open",
			"value": 255
		}```
		
		
I would change discovery payload to:
```{
	"command_topic": "zwave/Home/34/102/0/targetState/set",
	"state_topic": "zwave/Home/34/102/0/currentState",
	"value_template": "{{ value_json.value }}",
	"device_class": "garage",
	"payload_open": "Opened",
	"payload_close": "Closed",
	"payload_stop": "Stopped",
	"state_open": 255,
	"state_opening": 254,
	"state_closed": 0,
	"state_closing": 252",
	"device": {
		"identifiers": [
			"zwavejs2mqtt_0xca51aa0a_node34"
		],
		"manufacturer": "Nortek Security & Control LLC",
		"model": "Garage Door Controller (NGD00Z-4)",
		"name": "Home-GarageDoor",
		"sw_version": "2.1"
	},
	"name": "Home-GarageDoor_barrier_state",
	"unique_id": "zwavejs2mqtt_0xca51aa0a_34-102-0-currentState"
}```

can you try this and report back to me?

**Comment by ratsputin** [comment]
Okay, I updated as suggested:

```
  "discovery_payload": {
    "command_topic": "zwave/Home/34/102/0/targetState/set",
    "state_topic": "zwave/Home/34/102/0/currentState",
    "value_template": "{{ value_json.value }}",
    "device_class": "garage",
    "payload_open": "Opened",
    "payload_close": "Closed",
    "payload_stop": "Stopped",
    "state_open": 255,
    "state_opening": 254,
    "state_closed": 0,
    "state_closing": 252,
    "device": {
      "identifiers": [
        "zwavejs2mqtt_0xca51aa0a_node34"
      ],
      "manufacturer": "Nortek Security & Control LLC",
      "model": "Garage Door Controller (NGD00Z-4)",
      "name": "Home-GarageDoor",
      "sw_version": "2.1"
    },
    "name": "Home-GarageDoor_barrier_state",
    "unique_id": "zwavejs2mqtt_0xca51aa0a_34-102-0-currentState"
  }
```
The current state is now reporting correctly:
![image](https://user-images.githubusercontent.com/32401888/107659693-052c4100-6c4d-11eb-9f22-07e70c29b3b2.png)

So, that is fixed.

I cannot, however, _control_ the cover.  Sending an open command doesn't do anything.  Would you prefer I open a separate issue?

**Comment by ratsputin** [comment]
Oh, and thank you for responding so quickly.

I think I may see the issue.  Here is the MQTT command that was sent:

![image](https://user-images.githubusercontent.com/32401888/107660091-7ff55c00-6c4d-11eb-929f-7667ba4d6187.png)

However, the ZwaveJS2Mqtt control panel says this:

![image](https://user-images.githubusercontent.com/32401888/107660159-94d1ef80-6c4d-11eb-8dd0-eba255bca040.png)

**Comment by ratsputin** [comment]
Never mind.  I manually set targetState to "Open" via MQTT Explorer and it didn't open the garage door.

**Comment by ratsputin** [comment]
Oh!  This does seem to be related.  I manually set `targetState` to 255 and the door opened.

**Comment by ratsputin** [comment]
Okay, adjusting the payload values in the same way fixed the opening/closing.  Note that I have no idea what the proper value is to do a "stop" so I didn't adjust that value.

```
  "discovery_payload": {
    "command_topic": "zwave/Home/34/102/0/targetState/set",
    "state_topic": "zwave/Home/34/102/0/currentState",
    "value_template": "{{ value_json.value }}",
    "device_class": "garage",
    "payload_open": 255,
    "payload_close": 0,
    "payload_stop": "Stopped",
    "state_open": 255,
    "state_opening": 254,
    "state_closed": 0,
    "state_closing": 252,
    "device": {
      "identifiers": [
        "zwavejs2mqtt_0xca51aa0a_node34"
      ],
      "manufacturer": "Nortek Security & Control LLC",
      "model": "Garage Door Controller (NGD00Z-4)",
      "name": "Home-GarageDoor",
      "sw_version": "2.1"
    },
    "name": "Home-GarageDoor_barrier_state",
    "unique_id": "zwavejs2mqtt_0xca51aa0a_34-102-0-currentState"
  },
```

Thanks again for the quick response and help!

**Comment by billiaz** [comment]
@ratsputin please try to build my pr. It will use only numeric for all commands. or change these based on the pr changes I made

**Comment by ratsputin** [comment]
@billiaz This addressed that issue.  Here is the updated discovery payload:

```
  "discovery_payload": {
    "command_topic": "zwave/Home/34/102/0/targetState/set",
    "state_topic": "zwave/Home/34/102/0/currentState",
    "value_template": "{{ value_json.value }}",
    "device_class": "garage",
    "payload_open": 255,
    "payload_close": 0,
    "payload_stop": 253,
    "state_open": 255,
    "state_opening": 254,
    "state_closed": 0,
    "state_closing": 252,
    "device": {
      "identifiers": [
        "zwavejs2mqtt_0xca51aa0a_node34"
      ],
      "manufacturer": "Nortek Security & Control LLC",
      "model": "Garage Door Controller (NGD00Z-4)",
      "name": "Home-GarageDoor",
      "sw_version": "2.1"
    },
```

What is odd, however, is I just saw the same issue someone else mentioned when I sent a command to open the garage door.  It opened successfully; however, the position of the garage door still showed shut (0).

This fix does, however, address the issue where Home Assistant wasn't seeing the status correctly.

**Comment by aretakisv** [comment]
@ratsputin I believe this is a bug on Hass too, as it does not support intermediate state

Can you open or Clsoe the door, stuck it on a percentage and post a node export? I want to see some details!

It might be possible to make the value to show OPEN if it is not closed! as default state! this way  we make the user aware that something is wrong!

Cover is not supporting position, from what I know!... but we can "script" the template to show it in a state that keeps you aware

**Comment by ratsputin** [comment]
@aretakisv Apologies but I really can't test this.  The reason is, my garage door isn't truly integrated.  I have a third-party controller that has a physical tilt switch attached to the garage door itself.  It can't detect intermediate (partially open/closed) states.  Just whether the door is completely open or completely closed.

**Comment by billiaz** [comment]
Then I suspect this is somethign we can accept as is. I will check the FGR222, separately

**Comment by quadhammer** [comment]
I'm getting an 'unknown' value from Fibaro FGR222 with the latest Home Assistant 2023.7.1.  The curtains still work to open/close, but the state is unknown.

**Comment by robertsLando** [comment]
@quadhammer are you using mqtt discovery or home assistant integration?

**Comment by quadhammer** [comment]
The home assistant z-wave JS addon
Driver version: 11.0.0
Server version: 1.29.0

**Comment by robertsLando** [comment]
Ok so you should open the issue on home assistant core
