### ISSUE TITLE
[question] : Can you help me to check my configuration: I have this error : Driver: Failed to initialize the driver: Timeout while waiting for an ACK from the controller

### ISSUE THREAD

**Issue by Thomasdmm** [zwave-js/zwavejs2mqtt#557]
Hello Every Body, I try to create a docker for zwavejs2mqtt But I have this Error 
"Driver: Failed to initialize the driver: Timeout while waiting for an ACK from the controller"

Can you help me to check my configuration
Here screeshoot of my docker config : 
![image](https://user-images.githubusercontent.com/53251953/107663383-9a4e2a80-6c8b-11eb-8f43-58cc2961a601.png)
![image](https://user-images.githubusercontent.com/53251953/107663423-a76b1980-6c8b-11eb-8ef6-18dded0b76f8.png)
![image](https://user-images.githubusercontent.com/53251953/107663457-b0f48180-6c8b-11eb-869a-2fd8b2265da8.png)
![image](https://user-images.githubusercontent.com/53251953/107663512-bd78da00-6c8b-11eb-9c97-bf08eb27ead8.png)
![image](https://user-images.githubusercontent.com/53251953/107663561-ca95c900-6c8b-11eb-9330-fdfee0b95ceb.png)

And here the config 👍 
![image](https://user-images.githubusercontent.com/53251953/107663716-f9ac3a80-6c8b-11eb-82f3-4b8976d54e2c.png)
![image](https://user-images.githubusercontent.com/53251953/107663944-3841f500-6c8c-11eb-89ea-1a258c977407.png)
![image](https://user-images.githubusercontent.com/53251953/107664031-4e4fb580-6c8c-11eb-9c0e-8cfa00ba96ce.png)
![image](https://user-images.githubusercontent.com/53251953/107664112-5dcefe80-6c8c-11eb-9457-9e3dc7b027c9.png)

Thank for you futur help

Thomas

**Comment by decairn** [comment]
I have it running on Synology.  Differences in my setup are no need for the '--device' environment line, I leave the ports as standard (don't have any overlap with other services), and I set '/usr/src/app/store' to a specific location only.  Serial port location is same as you have set within zwavejs2mqtt.

**Comment by Thomasdmm** [comment]
Hello Decairn Thanks but I don't understand:( 
it's possible to see your screenshoot ? the docker is on synology too

**Comment by decairn** [comment]
Sure - Synology docker like this.  ZWavejs2mqtt settings are same except I have Disable Gateway set (as WS Server is set).

![1](https://user-images.githubusercontent.com/15806011/107714834-cca75a00-6c82-11eb-9f8c-295286a057e1.PNG)
![2](https://user-images.githubusercontent.com/15806011/107714845-d03ae100-6c82-11eb-8a84-13c656bd7f6d.PNG)
![3](https://user-images.githubusercontent.com/15806011/107714847-d29d3b00-6c82-11eb-93d8-2e4164bf8cec.PNG)
![4](https://user-images.githubusercontent.com/15806011/107714851-d4ff9500-6c82-11eb-8c1a-84ba91ee80da.PNG)
![5](https://user-images.githubusercontent.com/15806011/107714858-d6c95880-6c82-11eb-9af8-2e561eb749fd.PNG)

**Comment by robertsLando** [comment]
Thanks for the help with this issue @decairn
