### ISSUE TITLE
[question] Is there a setting to enable scenes on dimmers/switches?

### ISSUE THREAD

**Issue by cts1085** [zwave-js/zwavejs2mqtt#566]
I am not sure if this is part of the devices config migration or not.  I have two types of devices, Zooz and Innoveli that have the capability under OZW1.6 / Zwave2MQTT to pass scene events to Home Assistant. Under Zwave2MQTT this is since under the node information "scene_state_2", etc.  Under ZWaveJS2MQTT I only am seeing "light_dimmer" or "switch" nothing about scenes.

Is there something that I need to do to enable this or should I just wait for the configs to be completed?

Thank you for all you are doing - this is a great improvement!

**Comment by robertsLando** [comment]
@AlCalzone are scenes 100% supported in zwave-js?

**Comment by AlCalzone** [comment]
We should clarify first what is meant with scenes:
* `Central Scene`? --> supported, is emitted as `"value notification"` event ✔
* `Scene Activation`? --> supported, is emitted as `"value notification"` event ✔
* Something device specific that is called "scene" in the manual? ❌

@robertsLando you should also take a look at https://github.com/zwave-js/node-zwave-js/issues/1560#issuecomment-775057740, I suspect zwavejs2mqtt isn't doing that.

**Comment by robertsLando** [comment]
I already do that

**Comment by cts1085** [comment]
Here are two screen shots - First from Zwave2MQTT second from ZwaveJS2MQTT - the different is in the node json created for the scenes for the device.  I believe the devices/configs are similar between OZW and Zwave-js as far as I can tell. Note: I am running both via docker on a raspberry pi. No HW changes between screenshots - just downed one container and started the other.

![image](https://user-images.githubusercontent.com/30473948/107947499-737c4680-6f60-11eb-8480-c8d5c10e4a51.png)

![image](https://user-images.githubusercontent.com/30473948/107947922-1cc33c80-6f61-11eb-8b78-98a9b7e3c6ce.png)

**Comment by robertsLando** [comment]
@cts1085 Did you also tried the hass ws server integration?

**Comment by cts1085** [comment]
Same:
![image](https://user-images.githubusercontent.com/30473948/107977711-8f481280-6f89-11eb-9c1c-08f16e230605.png)

**Comment by robertsLando** [comment]
@AlCalzone I have a feel that the device isn't reporting the meter CC correctly, maybe it requires a compat flag?

**Comment by AlCalzone** [comment]
Can't say anything without a log 🤷🏻‍♂️

**Comment by robertsLando** [comment]
@cts1085 Please add logs file... sorry @AlCalzone Thought them was there

**Comment by cts1085** [comment]
My apologies - logs and other files located in ../store attached...

[zwavejs2mqtt-store.zip](https://github.com/zwave-js/zwavejs2mqtt/files/5988665/zwavejs2mqtt-store.zip)

**Comment by AlCalzone** [comment]
"Secure: unknown" makes me suspicious. Try re-interviewing it and send me a log of that if it doesn't work afterwards.

**Comment by cts1085** [comment]
Just to be clear - I did select "Rediscover Node" before I downloaded the logs - is there another command you want me to run?

**Comment by AlCalzone** [comment]
I'm not sure where the "re-interview" button is hidden now - @robertsLando ?

**Comment by cts1085** [comment]
I found it under Node Actions - I will select that and re-collect the logs.

**Comment by cts1085** [comment]
Now - is there anything I need to do to see the scenes in HA via WS integration?

**Comment by cts1085** [comment]
I am going to close this as this original issue seems to be resolved with the re-interview.  I will open another issue on ZWave-JS-Server regarding the scenes not showing up via WS integration.
