### ISSUE TITLE
[bug] Silicon Labs UZB controller being reported as a humidity sensor?

### ISSUE THREAD

**Issue by MaxVonEvil** [zwave-js/zwavejs2mqtt#572]
Build/Run method: [X] Manually built (git clone - npm install - npm run build )
zwavejs2mqtt version:  1.1.1.94ff7ed

### Describe the bug
While it's working as expected, z-wave controller is identified wrongly on both manufacturer and product description. This shows both in the console log:
   Node 1 ready: Sigma Designs (Former Zensys) - M417_9E (Smart Temperature & Humidity Sensor)
And in the web interface:
![image](https://user-images.githubusercontent.com/19863636/107846940-a249bf80-6d9c-11eb-992f-de1d3be70086.png)

The controller is this one:
https://www.digikey.com/en/products/detail/ACC-UZB3-U-STA/703-1128-ND/6111632

### To Reproduce
Get one and add it as a controller on /dev/ttyACM0

### Expected behavior
That it is correctly identified and/or it would be possible to edit the details.

**Comment by blhoward2** [comment]
Please reopen at the node-zwave-js project. Device support lives in that project.

@robertsLando Please close.

**Comment by robertsLando** [comment]
Thanks @blhoward2
