### ISSUE TITLE
[bug] Schlage BE469 lock status not updating.

### ISSUE THREAD

**Issue by gravyflex** [zwave-js/zwavejs2mqtt#576]
Before submitting a bug please read: <https://zwave-js.github.io/zwavejs2mqtt/#/troubleshooting/bug_report>

### Version

Build/Run method

- [ x ] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build )

zwavejs2mqtt version: 1.1.1
zwavejs version: 6.2.0

### Describe the bug

The binary_sensor.schlagebe469_the_current_status_of_the_door remains in that state when I close or open the lock manually or in home assistant. 

![image](https://user-images.githubusercontent.com/7466316/107862042-9b0fc980-6e0f-11eb-98ab-17df80534ac8.png)

### To Reproduce

1. Go to the entity in home assistant
2. Click on lock or unlock
3. The lock open or close
4. But the state of the binary sensor that tracks the state of the lock remains unchanged. 

![image](https://user-images.githubusercontent.com/7466316/107862190-c0510780-6e10-11eb-8a10-70ef932c03f4.png)

### Expected behavior

1. When the lock is open (via home assistant and manually) the binary sensor's state should change to open/unlocked.
2. When the lock is closed (via home assistant and manually) the binary sensor's state should be changed to closed/locked

### Additional context
I see the [someone](https://community.home-assistant.io/t/issue-with-schlage-after-zwavejs-migration/278958) else has the issue on the home assistant forum and they have deployed a work around. 

[node_43.zip](https://github.com/zwave-js/zwavejs2mqtt/files/5976584/node_43.zip)
[zwavejs2mqtt-logs.zip](https://github.com/zwave-js/zwavejs2mqtt/files/5976586/zwavejs2mqtt-logs.zip)

**Comment by ttcole1254** [comment]
I actually had this issue when I originally switched from OZW to this, but found that simply excluding and including it again fixed the issue. I also restarted zwavejs2mqtt and home Assistant afterwards if that matters. Not that it's a great solution, but it seemed that any device that I "carried over" from OZW had a similar issue.

**Comment by gravyflex** [comment]
I had excluded and included the lock before creating this ticket. 

I upgraded from zwave2mqtt where I was never able to include the lock securely as I had the security key in the wrong format.  I did several rounds of restarts of both hass and zwavejs2mqtt with no success. 

I'm using the hass integration with MQTT disabled.

**Comment by kaplan-max** [comment]
I have the same exact issue with a Kwikset 910 lock. Whether I lock/unlock manually or via home assistant the state doesn't change. I ended setting up polling on the lock status in ZwaveJS2MQTT to help with the issue but that's far from ideal.

**Comment by blhoward2** [comment]
Please reopen this issue at the node-zwave-js project. Lock statues updating for some devices was recently updated. For other older models like the 910 it is in progress. Regardless that support lives in the other project.

@robertsLando Please close.
