### ISSUE TITLE
[question] Possible to connect to websocket with Node-Red?

### ISSUE THREAD

**Issue by Andoramb** [zwave-js/zwavejs2mqtt#580]
Is it possible to connect directly to the websocket with Node-Red?
This way the network/automations could be independent of Home Assistant (in case it is down).

So far I've got (changed the websocket port in docker compose to 3333 for testing):
![image](https://user-images.githubusercontent.com/3399628/107885392-51e87400-6efa-11eb-8f61-b5be0a4c246a.png)
But there's no other activity reported for _Scene ID_.
*it works fine in HA

**Comment by kpine** [comment]
This is question for zwave-js-server project, but you need to setup the connection handshake as documented: https://github.com/zwave-js/zwave-js-server/#api

 > To start receive the state and get events, the client needs to send the start_listening command.

Send a JSON payload to the server to start listening:
```json
{"command": "start_listening"}
```

**Comment by Andoramb** [comment]
But of  course! 👍 
Thanks!
