### ISSUE TITLE
[feat]Better visualization for partial parameters

### ISSUE THREAD

**Issue by ivdimitro** [zwave-js/zwavejs2mqtt#581]
**Is your feature request related to a problem? Please describe.**
Currently the [partial parameters (bit fields)](https://zwave-js.github.io/node-zwave-js/#/development/config-files?id=partial-parameters) in device configuration are represented as any other configuration parameter which creates clutter in GUI and it is a bit confusing. For example in order to describe on which alarms a switch should react currently 3 lines are occupied by the options: 
![current implementation](https://user-images.githubusercontent.com/6159024/107888257-6d0faf80-6f0b-11eb-9216-ad26f949b5fe.png)
 

**Describe the solution you'd like**
As the partial parameters represent different options which can all be enabled at the same time, the option of using drop down list is not suitable. The recommended option for visualizing the parameters in the Aeotec manual is checkboxes. 

> The format of the parameter is Bit field (Checkboxes). The parameter MUST
be treated as a bit field where each individual bit can be set or reset. A graphical
configuration tool SHOULD present this parameter as a series of checkboxes.

Example mockup: 
![checkboxes](https://user-images.githubusercontent.com/6159024/107888062-bca1ab80-6f0a-11eb-8e5f-b923a9b7f938.png)

**Describe alternatives you've considered**
Alternative representation can be: 
- a list of on/off switches that are currently used in the binary/multilevel switch visualization
- multi selection dropdown list (not sure how it is JS but usually those are pain to implement and not very intuitive) 

**Additional context**
It is a cosmetic change but I think it will reduce the clutter for devices using partial parameters. 

What are your thoughts? 
Thanks.

**Comment by robertsLando** [comment]
@AlCalzone Are there any work in progress to make those booleans?

**Comment by AlCalzone** [comment]
https://github.com/zwave-js/node-zwave-js/issues/1717

Also related:
https://github.com/zwave-js/node-zwave-js/issues/1347
https://github.com/zwave-js/node-zwave-js/issues/1644
and https://github.com/zwave-js/node-zwave-js/issues/1675 - I want to allow setting the values as either one compound value or the partial params

**Comment by ivdimitro** [comment]
> [zwave-js/node-zwave-js#1717](https://github.com/zwave-js/node-zwave-js/issues/1717)
> 
> Also related:
> [zwave-js/node-zwave-js#1347](https://github.com/zwave-js/node-zwave-js/issues/1347)
> [zwave-js/node-zwave-js#1644](https://github.com/zwave-js/node-zwave-js/issues/1644)
> and [zwave-js/node-zwave-js#1675](https://github.com/zwave-js/node-zwave-js/issues/1675) - I want to allow setting the values as either one compound value or the partial params

Wow, great minds think alike :). I understand sooner or later this issue will be addressed. Thanks.
