### ISSUE TITLE
[bug] vision 2102-5 door/window sensor showing alarm type and event but no values

### ISSUE THREAD

**Issue by apaperclip** [zwave-js/zwavejs2mqtt#592]
### Version

Build/Run method

- [x] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build )

zwavejs2mqtt version: 1.1.1
zwavejs version: 6.2.0

### Describe the bug

A Vision 2102-5 (labeled as monoprice) door/window sensor has 4 items in the notification section. All are CC 113.
Alarm Type, Alarm Level,  Home Security (property), and Door State. The two alarm events never show values, the other two appear to work fine.  When looking through the zwavejs logs I did not see any alarm events discovered. I'm not sure where these are coming from and I am happy to test any device config changes if needed.

### To Reproduce

1. include device
2. wake up device a couple of times so inclusion completes 
3. observe the notification section

### Expected behavior

Either the alarm type and level values should populate or maybe they should not appear if there is some version backwards compatibility capability with Alarm v1 and Notification v14 (since alarm was renamed to notification)  .  Looking at the device manual https://usermanual.wiki/Vision-Automobile-Electronics-Co/ZD2102US5/html there is both Alarm v1 and Notification v4 CC support.  

### Additional context

In addition to the door state/home security events, I also see basic class reports of 0 or 255, I think this is a default behavior of the basic class but I do not see basic documented in the manual,  the basic 0/255 does match the Alarm level though.  However there is an interesting comment in the device configuration  https://github.com/zwave-js/node-zwave-js/blob/910155c88ffb2f8ab6ddce6adc2c0dbb57a135f6/packages/config/config/devices/0x0109/zd2102-5.json#L51

The included logs show an exclusion of the device has node04, and including it as node5.  

[zwavejs_1-vision-2102-5-exc_inc.log](https://github.com/zwave-js/zwavejs2mqtt/files/5982467/zwavejs_1-vision-2102-5-exc_inc.log)
[zwavejs2mqtt-vision-2102-5-exc_inc.log](https://github.com/zwave-js/zwavejs2mqtt/files/5982469/zwavejs2mqtt-vision-2102-5-exc_inc.log)

[node_5.json.log.txt](https://github.com/zwave-js/zwavejs2mqtt/files/5982477/node_5.json.log.txt)

Lastly, I though  I see mqtt stuff in the logs but I have that turned off and am only using zwavejs2mqtt for zwave management (using ws for HA)

Thank you!

**Comment by robertsLando** [comment]
If you are using ws server integration you shgould open the bug on hass repo not here

**Comment by apaperclip** [comment]
I am using WS, but my observations are the zwavejs2mqtt ui and with the zwavejs discovery.

**Comment by robertsLando** [comment]
@AlCalzone

**Comment by AlCalzone** [comment]
I'm not sure why the empty values are displayed in zjs2m. At least I see no message in the log where a V1 value is received. Might have to do with how zjs2m decides what to display. Since the device claims it supports V1 alarms, we cannot be sure that it does not use them in some situation.

**Comment by apaperclip** [comment]
Ok, thanks guys - 
so,
```14:29:59.398 CNTRLR   [Node 005] [+] [Notification] supportsV1Alarm: true    [Endpoint 0] [internal] ```

Tells us the device says it supports Alarm V1 and therefor the alarm level and alarm type. This results in type/level showing up, even if the device never sends anything to them.  

What about the note in the device config: 

```	"compat": {
		"commandClasses": {
			"add": {
				"0x20": {
					// This device should send Notification Reports, but they seem to get lost often
					// Basic Set comes through
					"isSupported": true
```

Shouldn't the device already support basic by default?

**Comment by AlCalzone** [comment]
It does, but zwave-js hides the Basic CC by default if there's a more specific actuating CC supported. That compat option forces it not to be hidden.

**Comment by macf0x** [comment]
Appears the Vision Security ZG8101 has the same issue. At least the symptoms are the same. Values are populate in the Node view (notifications), but the values aren't shown in HA. The initial entities are hidden in HA, when I exclude/include.

Happy to provide more detail if below is insufficient.

[265-2562-8202 (Node23).txt](https://github.com/zwave-js/zwavejs2mqtt/files/6033575/265-2562-8202.Node23.txt)
[zwavejs.log](https://github.com/zwave-js/zwavejs2mqtt/files/6033592/zwavejs.log)

**Comment by AlCalzone** [comment]
@macf0x zwave-js translates the Basic Set into a Binary Sensor Report, so there's no need to expose it:
```
15:59:29.680 CNTRLR [Node 023] treating BasicCC Set as a report
2021-02-24 15:59:29.681 INFO ZWAVE: Node 23: value updated: 48-0-Any false => true
```

**Comment by macf0x** [comment]
@AlCalzone Thanks for the prompt response.

The ZG8101 has 3 inputs. The tilt sensor (shown in HA), a reed switch and tamper. It these latter two that aren't exposed into HA.

I apologies if this isn't related.

These are the specific values and clearly zwavejs2mqtt receives the updates via BasicCC, but HA never gets the value.

15:59:22.447 CNTRLR [Node 023] treating BasicCC Set as a report
2021-02-24 15:59:22.450 INFO ZWAVE: Node 23: value updated: 48-0-Any false => true
2021-02-24 15:59:22.508 INFO ZWAVE: Node 23: value updated: 113-0-Home Security-Sensor status 2 => 2
2021-02-24 15:59:23.046 INFO ZWAVE: Node 23: value updated: 113-0-Home Security-unknown 254 => 254
2021-02-24 15:59:26.805 INFO ZWAVE: Node 23: value updated: 113-0-Home Security-unknown 254 => 254
15:59:28.977 CNTRLR [Node 023] treating BasicCC Set as a report
2021-02-24 15:59:28.979 INFO ZWAVE: Node 23: value updated: 48-0-Any true => false
2021-02-24 15:59:29.082 INFO ZWAVE: Node 23: value updated: 113-0-Home Security-Sensor status 2 => 2
15:59:29.680 CNTRLR [Node 023] treating BasicCC Set as a report
2021-02-24 15:59:29.681 INFO ZWAVE: Node 23: value updated: 48-0-Any false => true
2021-02-24 15:59:29.699 INFO ZWAVE: Node 23: value updated: 113-0-Home Security-Sensor status 2 => 2
2021-02-24 15:59:34.302 INFO ZWAVE: Node 23: value updated: 113-0-Home Security-Cover status 0 => 3
2021-02-24 15:59:36.698 INFO ZWAVE: Node 23: value updated: 113-0-Home Security-Cover status 3 => 3

[HA device.txt](https://github.com/zwave-js/zwavejs2mqtt/files/6034284/HA.device.txt)

FWIW these were exposed in OZW prior to cutting over. ZWJS is a massive improvement over the OZW. So much easier to work with Zwave devices. I really appreciate the teams efforts in Zwave. Couple of the device that were problematic are now working sweet. ;)

**Comment by AlCalzone** [comment]
> zwavejs2mqtt receives the updates via BasicCC

No, it receives them via the Notification CC (113)

> 113-0-Home Security-Sensor status 2 => 2

means "intrusion"

> Cover status 3 => 3

means "Tampering, product cover removed"

So as far as I can see, they are received correctly, but aren't correctly discovered by HA. I suggest you open an issue in the HomeAssistant repo, so they can track it down.

**Comment by macf0x** [comment]
Thanks AlCalzone.

**Comment by macf0x** [comment]
Where can one find the info such as Cover status (3) = Tamper?

**Comment by AlCalzone** [comment]
That should be included in the metadata for the value ID. HA has access to that. zwavejs2mqtt should already display it on the UI (maybe not in the logs).

**Comment by macf0x** [comment]
[zwavejs_357.log](https://github.com/zwave-js/zwavejs2mqtt/files/6393109/zwavejs_357.log)
[zwavejs2mqtt (1).log](https://github.com/zwave-js/zwavejs2mqtt/files/6393111/zwavejs2mqtt.1.log)

It appears these values are still not recognised in the latest release.

**Comment by AlCalzone** [comment]
What do you mean by "recognized"? Can you share screenshots or something?

**Comment by macf0x** [comment]
Values are reported as unknown.

**Comment by AlCalzone** [comment]
I think we discussed this already somewhere. The notification the device sends is actually using `0xfe` ("unknown notification") as the notification event.

**Comment by macf0x** [comment]
If this is by design, which seems weird choice by the manufacture, Perhaps I'll need to look at tracking the notifications in HA, rather than expecting values/states.

**Comment by AlCalzone** [comment]
> which seems weird choice by the manufacture

True, but trust me, there are far weirder choices manufacturers have made.
