### ISSUE TITLE
[bug]  Aeotec Switch 6 - binary switch doesn't work any more as it has wrong (light) domain.

### ISSUE THREAD

**Issue by scyto** [zwave-js/zwavejs2mqtt#595]
Before submitting a bug please read: <https://zwave-js.github.io/zwavejs2mqtt/#/troubleshooting/bug_report>

### Version
1.1.1+94ff7ed.94ff7ed

Build/Run method

- [X] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build )

zwavejs2mqtt version: 1.1.1+94ff7ed.94ff7ed
zwavejs version: 6.3.0-8f22052

### Describe the bug

The Aeotec Switch 6 - binary switch doesn't work any more.
This breaks the switch when using MQTT and HASS discovery. 
This seems to be a regression and was fine in earlier versions.

### To Reproduce

1. Install latest version.
2. Look at the device value and see  binary switch 
 ![image](https://user-images.githubusercontent.com/11369180/108007609-4311c800-6fb3-11eb-9f6c-d5e8d13b8704.png)

5. Look at discovery code and note it an rgb switch.

7. In previous version this was discovered as switch.masterbedroom_outlet_rgb_switc.   In this version it is discovered as light.masterbedroom_outlet_rgb_switch

10. This binary switch is not a color light - it only controls load for the outlet on this device.
11. Yes this device has am rgb color device - but that is purely for reporting status, energy use etc.
12. the binary switch doesn't control the rgbw device in an way.

### Expected behavior

I expect this to work as it did in earlier versions and be surfaced as a binary switch.

### Additional context

@billiaz not sure if this is related to any of the changes to making color lights works?

**Comment by scyto** [comment]
[node_11.json.txt](https://github.com/zwave-js/zwavejs2mqtt/files/5985276/node_11.json.txt)

**Comment by scyto** [comment]
I note the whole device is now in the light discovery section, on previous versions it was in the switch discover section (which would be correct, this is a switch not a light).  

![image](https://user-images.githubusercontent.com/11369180/108015189-7dd02c00-6fc4-11eb-83f6-e81d57504334.png)

**Comment by scyto** [comment]
With help from RobC pretty certain it is these changes that caused this. One can't assume a device with a switch and rgbw is an rgbw dimmer / light https://github.com/zwave-js/zwavejs2mqtt/pull/290/files.

The switch in this device just controls the 120v outlet on it.

**Comment by billiaz** [comment]
I am going to test thorrowly once the RGB light is here. the change made on pr, is a Draft and needs work! 

I already expected some mixup.

@scyto if this outlet has already an color switch CC! and is not a Colorswitch device.. then probably they do something wrong. But want to be sure for this. Good to know something is broken, to take a look on this

**Comment by scyto** [comment]
Yes it is interesting. I think this device is doing it right.  It has a binary switch - which is just that a plain binary switch for controlling any binary load connected to it.
It also has a color switch which controls the rgb color indicator on it. this seems right to me.
Lastly it has a multi level switch that does ¯\(°_o)/¯ (so maybe it doesn't do it right, lol).

At least on this device each endpoint doesn't affect the other endpoints  - unlike the fibaro which seems to have muddled the the endpoints.

For reference this is the device - https://help.aeotec.com/support/solutions/articles/6000056905-smart-switch-6-user-guide-
And FWIW seems the smart things community created custom device files for the device, maybe that will help expose more insight   https://aeotec.freshdesk.com/support/solutions/articles/6000086383-using-smart-switch-6-with-smartthings-hub-s-custom-device-type

**Comment by blhoward2** [comment]
> I am going to test thorrowly once the RGB light is here. the change made on pr, is a Draft and needs work! 
> 
> 
> 
> I already expected some mixup.
> 
> 
> 
> @scyto if this outlet has already an color switch CC! and is not a Colorswitch device.. then probably they do something wrong. But want to be sure for this. Good to know something is broken, to take a look on this

The color switch here is to control the LED color when it's off or under load. It doesn't affect the load.

**Comment by robertsLando** [comment]
Fixed by #568
