### ISSUE TITLE
[bug] Fibaro Roller Shutter 3

### ISSUE THREAD

**Issue by HWL1968** [zwave-js/zwavejs2mqtt#599]
Build/Run method

- [ ] Docker

App Version
1.1.1
Zwavejs Version
6.2.0 

### Describe the bug
Hi all,

I am using a Fibaro roller shutter 3 (FGR223) to control my roller shutter ( :-) ). Through the webinterface everything is working fine:
- positioning (including the update of the currentValue)
- moving up / down

Also the control via MQTT works fine:

positioning:
ZWAVEMQTT/RolluikWoonkamer/switch_multilevel/endpoint_1/targetValue/set 95.04

up / down commands:
ZWAVEMQTT/RolluikWoonkamer/switch_multilevel/endpoint_1/Up/set true
ZWAVEMQTT/RolluikWoonkamer/switch_multilevel/endpoint_1/Up/set false
ZWAVEMQTT/RolluikWoonkamer/switch_multilevel/endpoint_1/Down/set true
ZWAVEMQTT/RolluikWoonkamer/switch_multilevel/endpoint_1/Down/set false

However: if I set the up/down button, there is no update returned by ZwaveJS2MQTT to MQTT (as in: if I change the up / down button to ON or OFF in the webinterface, there is no reporting to MQTT that the button changed, nor is it the other way around: sending the MQTT command does not change the value in the webinterface). The variable currentValue is updated however.

### Expected behaviour:
- in my automation software changing the button Up / Down from ON to OFF (or vv) should change the button in the webinterface
- in the webinterface changing the button Up / Down from ON to OFF (or vv) should send a MQTT messing with the new value

### To Reproduce

1. subscribe to the MQTT topic you are using
2. Go to your automation software and press up / down
2. watch your MQTT messages and watch the zwave control panel (status of value [24-38-1-Up] Perform a level change (Up) in the multi level switch part)
3. change button ON/OFF and watch the MQTT messages

### Additional context

I am not sure if this is a bug or due to zwave (maybe it doesn't report any update). Any additional information needed?

Best regards,

HWL

**Comment by robertsLando** [comment]
Could you try to send 'start' and 'stop' via mqtt?

**Comment by HWL1968** [comment]
"ZWAVEMQTT/RolluikWoonkamer/switch_multilevel/endpoint_1/Down/set" -m "stop" / "start" actually moves up (and stops). Moving down via true / false is working fine (as expected). Weird. 

Moving up via true / false or start / stop also works as expected.

However: no update of the switch states is being performed (on the webpage) nor is a message send to MQTT about the switch being changed. It can be due to the fibaro, I don't know if the fibaro sends a message!

The only update when stopped: 

ZWAVEMQTT/RolluikWoonkamer/switch_multilevel/endpoint_1/currentValue {"time":1613560594211,"value":87} 

As an example. "value" is the relative position of the shutter.

Thanks again.

**Comment by robertsLando** [comment]
> no update of the switch states is being performed (on the webpage) nor is a message send to MQTT about the switch being changed

Humm this could be due to some device settings about reports. @AlCalzone ?

**Comment by AlCalzone** [comment]
Do I understand correctly, you want to display somehow that the `UP/DOWN` command is in progress or not?
So far that is not intended as the buttons are writeonly. It **might** be possible that it is possible for some devices (like this one) due to Supervision support, but I'd need to see a zwave-js log.

**Comment by robertsLando** [comment]
I think that the problem is that the state change is not reported by the device while it's going up and down

**Comment by AlCalzone** [comment]
Well that is entirely possible.

**Comment by HWL1968** [comment]
If the device doesn't report it, it is indeed no bug, but I don't know if it is reported nor do I know how to see that.

What I noticed is that the webinterface doesn't change when I send the up or down command via MQTT. I would expect that to be shown (and the device should report the state as an currentValue or something). Also I would expect that the webinterface should send an update when I 'push' the button up (on/off) or down (on/off). Since I do not know how you guys implemented the 'report to MQTT functionality' but I could imagine that this is done based on the webinterface. Then again it would be a bug. At least: I would call this a bug. :-)  (please no offence, just kidding).

Please take into consideration: I did not connect a real switch to the device (that broke while implementing this... long story, another time). So I can't check if it reports that state back to zwavejs2mqtt.

To be clear the usecases again:
- push button on webinterface: roller starts / stops moving but no update send to mqtt (on/of for both up and down)
- send mqtt message to move up / down  (via true / false): no update of the webinterface
- "ZWAVEMQTT/RolluikWoonkamer/switch_multilevel/endpoint_1/Down/set" -m "stop" / "start" actually moves up (and stops). Moving down via true / false is working fine (as expected).

I assume (and might be wrong) that this is related to zwavejs2mqtt (or an underlying library).

How can I help (generating logfiles)?

**Comment by AlCalzone** [comment]
@HWL1968 lets put it this way: Your device supports Supervision CC, which tells us if the device accepted the Up/Down command. If it does not accept the command, setting the value will fail (unless zwavejs2mqtt ignores that for writeonly values).

**Comment by HWL1968** [comment]
@AlCalzone: off course. It took me quite some time to figure out which command is accepted to move the shutter. But since the shutters move on the mqtt command, I assume it is accepted. Or do I understand your reaction wrong? Therefor I think the issue of not changing the website of zwavejs2mqtt (the controlpanel view) is the issue.

Just for better understanding by me: if I issue a command towards zwave using mqtt, then it is being accepted and transmitted towards the zwave device (in my case the aeon stick). Does the controlpanel wait for a respons before it updates the value shown? Or does it update the value and transmits it toward the zwave stick? If it transmits and waits for a respons that is being translated, I assume that @robertsLando is right and they are write only. Using the website to change up/down could be explained since the controlpanel view is updated and afterwards (or at least independent of the result) the command is being send. Sounds feasible. Can I somehow check whether it is write only?

**Comment by robertsLando** [comment]
@HWL1968 After sending the command, try to refresh the page,, you will see that the on/off comes back to the previous value

**Comment by HWL1968** [comment]
@robertsLando: tried it just now, and you are right. Seems there is no feedback from the fibaro? Can I somehow check it (in a logfile?) as far as you know? Then we would know for sure that 'no feedback' is a feature by Fibaro.

**Comment by robertsLando** [comment]
I think it's not really a feature or bug of the device, that value just don't expect a feedback at all, the feedback you can check is the current value of the multilevel sensor

**Comment by AlCalzone** [comment]
Up/Down is just a command that tells the shutter to move. If the command succeeds and the device supports Supervision (like this one), that is positive feedback. If the command fails, that is negative feedback.

Not sure how that translates over to the MQTT API though.

**Comment by HWL1968** [comment]
@robertsLando @AlCalzone : feature was not meant as a positive thing. If you control it by 2 different instances (which is the clue while using mqtt) you lose the current value. How can I use Supervision? If I turn on to send all events, none of them relate to the button used (on/off). 

Can we conclude: no bug but a feature (as a joke) and the only way to know whether a button is pressed: use the currentValue as an indicator that it had been pressed? (since it is being send after the shutter stops)? 
Thanks for helping me out.

**Comment by AlCalzone** [comment]
> How can I use Supervision?

It is used under the hood automatically if supported by the device.

> you lose the current value

What do you mean by that?

**Comment by HWL1968** [comment]
@AlCalzone : losing the current value (better should have been 'current state' since it is a switch). If I press in the first instance of my home automation (let's say: openhab) the shutter has to move down, than I can keep a record of that and the state will represent the state of the switch in the fibaro. However if I choose to move the shutter up in another instance (for example Home Assistant), the first instance is not aware of this, since the state is not being returned. Why would one do this? If you plan to migrate, you can setup a new environment without loosing the functionality until everything is ready (like I am doing at the moment) or if you are having a production environment and a test environment (like I had and will have in the near future again). I think this can be resolved via some additional logic (in NodeRed or something) which acts as an intermediate and is keeping track of the state.

**Comment by AlCalzone** [comment]
> If I press in the first instance of my home automation (let's say: openhab) the shutter has to move down, than I can keep a record of that and the state will represent the state of the switch in the fibaro. However if I choose to move the shutter up in another instance (for example Home Assistant), the first instance is not aware of this, since the state is not being returned. 

There exists no command from devices that can tell us that it **started** moving. So if your two instances use different drivers, you're out of luck.

Like I outlined above, what could be done is update the value you set, so there is a notification for all mqtt listeners.

**Comment by HWL1968** [comment]
@AlCalzone : thx. I was looking for something which showed that the up/down button is on or off. But since it is no bug, I will close it. Thanks to both for helping.
