### ISSUE TITLE
[bug] Hass Discovery Motion Sensor & Cover Status name issues

### ISSUE THREAD

**Issue by chilicheech** [zwave-js/zwavejs2mqtt#60]
**Version**

Build/Run method
- [x] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build ) 

zwavejs2mqtt version: master

**Describe the bug**
Some devices create `113-0-Home_Security-Motion_sensor_status` and `113-0-Home_Security-Cover_status` values. Hass discovery creates `sensor_notification_Home_Security` for motion and `sensor_notification_Home_Security_Home Security` for cover. These names could be better represented. Maybe as `sensor_notification_home_security_motion` and `sensor_notification_home_security_cover` or something in those lines. I'm not sure what the appropriate name should be. I can look at what z2m/ozw creates and post them here for reference.

![Screen Shot 2020-12-08 at 11 12 14 AM](https://user-images.githubusercontent.com/732659/101530546-e8bb1200-3946-11eb-8920-fa15360c9847.png)

The other issue is that the payload also has those names and they're not good names. They should also be improved:
Motion sensor:
```
{
  "type": "sensor",
  "object_id": "notification_Home Security",
  "discovery_payload": {
    "value_template": "{{ value_json.value }}",
    "icon": "mdi:alarm-light",
    "state_topic": "z2m/24/113/0/Home_Security/Motion_sensor_status",
    "json_attributes_topic": "z2m/24/113/0/Home_Security/Motion_sensor_status",
    "device": {
      "identifiers": [
        "zwavejs2mqtt_0xc5b5c9e5_node24"
      ],
      "manufacturer": "Vision Security",
      "model": "Zooz 4-in-one motion/temperature/humidity/luminance sensor (ZSE40)",
      "name": "master",
      "sw_version": "5.1"
    },
    "name": "master_notification_Home Security",
    "unique_id": "zwavejs2mqtt_0xc5b5c9e5_24-113-0-Home Security-Motion sensor status"
  },
  "discoveryTopic": "sensor/master/notification_Home Security/config",
  "values": [
    "113-0-Home Security-Motion sensor status"
  ],
  "persistent": false,
  "ignoreDiscovery": false,
  "id": "sensor_notification_Home Security"
}
```
Cover sensor:
```
{
  "type": "sensor",
  "object_id": "notification_Home Security_Home Security",
  "discovery_payload": {
    "value_template": "{{ value_json.value }}",
    "icon": "mdi:alarm-light",
    "state_topic": "z2m/24/113/0/Home_Security/Cover_status",
    "json_attributes_topic": "z2m/24/113/0/Home_Security/Cover_status",
    "device": {
      "identifiers": [
        "zwavejs2mqtt_0xc5b5c9e5_node24"
      ],
      "manufacturer": "Vision Security",
      "model": "Zooz 4-in-one motion/temperature/humidity/luminance sensor (ZSE40)",
      "name": "master",
      "sw_version": "5.1"
    },
    "name": "master_notification_Home Security_Home Security",
    "unique_id": "zwavejs2mqtt_0xc5b5c9e5_24-113-0-Home Security-Cover status"
  },
  "discoveryTopic": "sensor/master/notification_Home Security_Home Security/config",
  "values": [
    "113-0-Home Security-Cover status"
  ],
  "persistent": false,
  "ignoreDiscovery": false,
  "id": "sensor_notification_Home Security_Home Security"
}
```

The other thing is that both the motion and cover sensors don't show up in Hass. I haven't seen any errors in the logs in Hass. I'll keep digging.

![Screen Shot 2020-12-08 at 11 37 18 AM](https://user-images.githubusercontent.com/732659/101532677-bbbc2e80-3949-11eb-9e9a-b59b5ba4003e.png)

**Comment by robertsLando** [comment]
@chilicheech Notifications are discovered [here](https://github.com/zwave-js/zwavejs2mqtt/blob/master/lib/Gateway.js#L1447), could you play around with those 3 lines of code until you make it work? I don't own any device that sends notifications and I cannot debug this :( Also could it be that them are not showing because the object_id has a space? Maybe not all chars are allowed in object_id?

**Comment by robertsLando** [comment]
Also I think that notifications could be improved by using this: https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/notifications.json. We could lookup for notification type and based on it set the correct icon for the sensor

**Comment by katiuskt** [comment]
+1 Same issue reported by @chilicheech here with Fibaro Motion Sensor (FGMS001): Sensor detects there is motion (light is on when its does) but there is no HASS discovered object to manage it:
![image](https://user-images.githubusercontent.com/75622100/102024763-42329f00-3d94-11eb-81bc-de0da308cc47.png)

In zwavejs2mqtt GUI there are two sensors created both for cover status (blue marked) and for motion status (yellow marked). None of them are discovered by HASS (I've selected discover node and also selected each sensor and clicked on rediscover option with no luck):
![image](https://user-images.githubusercontent.com/75622100/102024818-95a4ed00-3d94-11eb-9346-d081c3d000d5.png)

**Comment by robertsLando** [comment]
@katiuskt When a discovery fails there is an hass log that explain what's wrong. That could help me to fix the disovery of such devices, could you check it please?

**Comment by katiuskt** [comment]
@robertsLando : As @chilicheech said, I'm not able to find relevant information in HASS logs regarding this :-(

Regarding that node (Motion sensor) I only see these messages:

> 2020-12-13 22:30:19 ERROR (MainThread) [homeassistant.helpers.event] Error while processing state changed for sensor.hc_motionsensor_temperature
> Traceback (most recent call last):
> File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 257, in _async_state_change_dispatcher
> hass.async_run_hass_job(job, event)
> File "/usr/src/homeassistant/homeassistant/core.py", line 433, in async_run_hass_job
> hassjob.target(*args)
> File "/usr/src/homeassistant/homeassistant/components/min_max/sensor.py", line 210, in _async_min_max_sensor_state_listener
> if new_state.state is None or new_state.state in [
> AttributeError: 'NoneType' object has no attribute 'state'
> 2020-12-13 22:39:47 ERROR (MainThread) [homeassistant.helpers.event] Error while processing state changed for sensor.hc_motionsensor_temperature
> Traceback (most recent call last):
> File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 257, in _async_state_change_dispatcher
> hass.async_run_hass_job(job, event)
> File "/usr/src/homeassistant/homeassistant/core.py", line 433, in async_run_hass_job
> hassjob.target(*args)
> File "/usr/src/homeassistant/homeassistant/components/min_max/sensor.py", line 210, in _async_min_max_sensor_state_listener
> if new_state.state is None or new_state.state in [
> AttributeError: 'NoneType' object has no attribute 'state'

Also another error involving another a Fibaro FGS213 node:

> 2020-12-13 20:34:04 ERROR (MainThread) [homeassistant.helpers.template] Error parsing value: 'dict object' has no attribute 'value' (value: {"id":"13-38-0-currentValue","nodeId":13,"commandClass":38,"commandClassName":"Multilevel Switch","endpoint":0,"property":"currentValue","propertyName":"currentValue","type":"number","readable":true,"writeable":false,"label":"Current value","genre":"user","min":0,"max":99,"list":false,"isCurrentValue":true,"targetValue":"38-0-targetValue","lastUpdate":1607888042521}, template: {{ (value_json.value / 99 * 255) | round(0) }})

But I'm afraid nothing else

**Comment by katiuskt** [comment]
Just in case it helps: Using ZWave2MQTT the information for all the entities of the Fibaro FGMS001 are shown properly in HASS:
![image](https://user-images.githubusercontent.com/75622100/102546243-a072c100-40b7-11eb-8add-7f54bfb728a4.png)

**Comment by katiuskt** [comment]
> +1 Same issue reported by @chilicheech here with Fibaro Motion Sensor (FGMS001): Sensor detects there is motion (light is on when its does) but there is no HASS discovered object to manage it:

The root cause of this is the same issue as it has been reported in https://github.com/zwave-js/zwavejs2mqtt/issues/91. Removing the blank space in the Discovery topic the entities are detected by HASS finally


Still missing several entities detected by OZW and not reported now (those relative to X, Y, Z acceleration or seismic sensor) but I guess it deserves another issue report.

**Comment by chilicheech** [comment]
Sweet, this fixed made the entities show up in hass for me. I now have motion detection and door open/closed status :)

**Comment by robertsLando** [comment]
@chilicheech with last commit from @billiaz now notifications also reports the string and not the numeric value :tada:
