### ISSUE TITLE
[bug] Dependabot "updated" from Debian Buster to Alpine, which breaks the custom container build

### ISSUE THREAD

**Issue by rccoleman** [zwave-js/zwavejs2mqtt#600]
Before submitting a bug please read: <https://zwave-js.github.io/zwavejs2mqtt/#/troubleshooting/bug_report>

### Version

Build/Run method

- [x] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build )

zwavejs2mqtt version: 1.1.1
zwavejs version: 6.3.0

### Describe the bug

It looks like dependabot "upgraded" the base docker image from Debian to Alpine, which broke the custom docker build process.

### To Reproduce

Follow the custom Docker [build instructions](https://zwave-js.github.io/zwavejs2mqtt/#/troubleshooting/docker_custom_builds) exactly, and see it fail with
```
 => CACHED [git-clone-src 2/4] WORKDIR /home/node                                                                                           0.0s
 => CANCELED [git-clone-src 3/4] RUN git clone -b master --depth 1 https://github.com/zwave-js/node-zwave-js                                0.8s
 => ERROR [stage-3 2/4] RUN apt-get update && apt-get install -y git && rm -rf /var/lib/apt/lists/*                                         0.7s
------
 > [stage-3 2/4] RUN apt-get update && apt-get install -y git && rm -rf /var/lib/apt/lists/*:
#6 0.600 /bin/sh: apt-get: not found
------
executor failed running [/bin/sh -c apt-get update && apt-get install -y git && rm -rf /var/lib/apt/lists/*]: exit code: 127
```

### Expected behavior

I expect the build to succeed, as it has been.  

### Additional context

I reverted commit c990ecac393d5fc0637c05debc9e4772d67bfed2 and the build succeeds.

**Comment by robertsLando** [comment]
@rccoleman You are speaking about the Dockerfiule.contrib right?

**Comment by rccoleman** [comment]
It just did it again: https://github.com/zwave-js/zwavejs2mqtt/commit/1bb27519c0b92a63621f15116c83f118e7e8949a#diff-4ddc2e10398d5c169795b7937f893ec72d2619b395259c592156a5dd0b476c9f
