### ISSUE TITLE
[bug] Do not start ZJS Server before the `driver ready` event

### ISSUE THREAD

**Issue by balloob** [zwave-js/zwavejs2mqtt#602]
### Version

Build/Run method

- [x] Docker
- [x] PKG
- [x] Manually built (git clone - npm install - npm run build )

zwavejs2mqtt version: 1.1.1
zwavejs version: 6.4.0

### Describe the bug

Z-Wave JS 2 MQTT will start the Z-Wave JS Server before the Driver object has emitted the `driver ready` event. This is causing bad information to be sent by Z-Wave JS Server. This is not supported.

Related bugs:

https://github.com/home-assistant/core/issues/46180#issuecomment-775125292

https://github.com/home-assistant/core/issues/46279

https://github.com/home-assistant-libs/zwave-js-server-python/issues/102

Bugs are closed because we now handle it from a Python side correctly if we receive bad data. Better would be if we didn't had the error to begin with.

CC @MartinHjelmare

### To Reproduce

1. Set up Home Assistant to connect to ZJS2MQTT via the ZJS Server
2. Restart ZJS2MQTT

### Expected behavior

The WS server should not come up until the driver is ready to serve data.

**Comment by balloob** [comment]
An alternative could be that we update [`Server.start`](https://github.com/zwave-js/zwave-js-server/blob/master/src/lib/server.ts#L251) to not start the server until the driver is ready. However that seems weird because `start` then doesn't automatically start. 

We could update `Server.start()` to raise if the driver is not ready maybe. That would help make it clear we're not ready to serve yet.

**Comment by robertsLando** [comment]
Let me fix this :)

**Comment by balloob** [comment]
Thanks!

**Comment by balloob** [comment]
@zwavejs/server 1.0.0-beta.7 will now raise if the driver is not ready when the server starts.
