### ISSUE TITLE
[question] Danfoss LC13 not discovering all values

### ISSUE THREAD

**Issue by Wojcioo** [zwave-js/zwavejs2mqtt#607]
Hello
I have 3 different Danfoss Living Connect Z Thermostat. For two of them all values are identified properly and I can see them in the ZWaveJS2MQTT Control Panel. This are:
climate_thermostat
sensor_battery_level
binary_sensor_battery_islow

But for one I can only:
sensor_battery_level
binary_sensor_battery_islow

I've installed this on RPI3 using this instruction: https://flemmingss.com/how-to-set-up-zwavejs2mqtt-on-a-raspberry-pi-and-integrate-it-with-home-assistant/
My question is, how can I get the other values to show up as home assistant devices?
Cheers,

![image](https://user-images.githubusercontent.com/33394332/108202562-96a22400-7121-11eb-9da3-318aedd1bb24.png)
![image](https://user-images.githubusercontent.com/33394332/108202581-9e61c880-7121-11eb-8a97-5716120088f6.png)

**Comment by robertsLando** [comment]
@Wojcioo Logs please

**Comment by Wojcioo** [comment]
@robertsLando 
[zwavejs2mqtt.log](https://github.com/zwave-js/zwavejs2mqtt/files/5997384/zwavejs2mqtt.log)

**Comment by robertsLando** [comment]
```
2021-02-17 17:09:08.453 INFO ZWAVE: Node 2 is now awake
2021-02-17 17:09:08.455 WARN GATEWAY: Unable to discover climate device, there is no valid temperature valueId
```

Do you have any air temperature value id in your values?

**Comment by robertsLando** [comment]
cc @billiaz

**Comment by Wojcioo** [comment]
> ```
> 2021-02-17 17:09:08.453 INFO ZWAVE: Node 2 is now awake
> 2021-02-17 17:09:08.455 WARN GATEWAY: Unable to discover climate device, there is no valid temperature valueId
> ```
> 
> Do you have any air temperature value id in your values?

Do you mean in this place?
![image](https://user-images.githubusercontent.com/33394332/108323009-72e4e980-71c6-11eb-80f8-cc462d2d7c7d.png)
I've got 21.

**Comment by robertsLando** [comment]
Nope, it's a mulilevel sensor CC, do you have any sensor multilevel defined? Try to send me a node export

**Comment by billiaz** [comment]
Danfoss has no feedback of temp.
I will test my lc13 i have and try to make a patch

**Comment by robertsLando** [comment]
Lol so we need to patch the discover climate funcion to work even without a temp

**Comment by Wojcioo** [comment]
> Nope, it's a mulilevel sensor CC, do you have any sensor multilevel defined? Try to send me a node export

**Comment by robertsLando** [comment]
Yep the temperature is missing, that's why the climate device isn't discovered. As I said this requires a patch in Gateway discoverClimate function to allow create climate devices without a temperature

**Comment by billiaz** [comment]
I will look into this, probably tomorrow After I fiind one LC13/12 which has the same CC/values

**Comment by billiaz** [comment]
@Wojcioo can you also export node 3? It will help me understand why one works, when the other just not

**Comment by Wojcioo** [comment]
> I will look into this, probably tomorrow After I fiind one LC13/12 which has the same CC/values

Thank you :)

**Comment by billiaz** [comment]
I see, the Air temp is hardcoded to Climate control, which makes no sense to me

can you delete from device 11 the  discovery payload and add a new one as the one i paste here?

```
{
            "type": "climate",
            "object_id": "thermostat_test",
            "values": [
                "67-0-setpoint-1"
            ],
            "setpoint_topic": {
                "1": "67-0-setpoint-1"
            },
            "default_setpoint": "67-0-setpoint-1",
            "discovery_payload": {
                "min_temp": 4,
                "max_temp": 28,
                "mode_command_topic": false,
                "temp_step": 0.5,
                "temperature_state_template": "{{ value_json.value }}",
                "temperature_command_topic": "zwave2mqtt/danfoss-alek/67/0/setpoint/1/set",
                "temperature_state_topic": "zwave2mqtt/danfoss-alek/67/0/setpoint/1",
                "device": {
                    "identifiers": [
                        "zwavejs2mqtt_0xe6dcf749_node11"
                    ],
                    "manufacturer": "Danfoss",
                    "model": "Living Connect Z Thermostat (LC-13)",
                    "name": "danfoss-alek",
                    "sw_version": "1.1"
                },
                "name": "danfoss-alek_thermostat_test",
                "unique_id": "zwavejs2mqtt_0xe6dcf749_Node11_thermostat_test"
            },
            "discoveryTopic": "climate/danfoss-alek/thermostat_test/config",
            "persistent": false,
            "ignoreDiscovery": false,
            "id": "climate_thermostat_test"
        }
```

this should create a thermostat_test !!!! if this works, I will need to look into automating this

**Comment by Wojcioo** [comment]
> this should create a thermostat_test !!!! if this works...

this works with 11

![image](https://user-images.githubusercontent.com/33394332/108678585-8c01d900-74eb-11eb-9d95-7327ccb984b3.png)

but 2 was working wrong....

**Comment by billiaz** [comment]
@Wojcioo knowing how HASS works! i believe node 11 will work until for some reason is unregistered from HASS
they have the same payload.
is thei thermostat_test showing in HASS?

if so I will send you also a test for node 3! and then we will delete them and try a patch.

**Comment by Wojcioo** [comment]
> is thei thermostat_test showing in HASS?

Yes, it is.
![image](https://user-images.githubusercontent.com/33394332/108681770-d422fa80-74ef-11eb-9e5f-da088a0f3336.png)

> if so I will send you also a test for node 3! and then we will delete them and try a patch.

Thank you.

**Comment by billiaz** [comment]
seems nice! I think it is easy to fix in short term. Do you know how to run/build from branch? @Wojcioo 
do you use docker?

**Comment by Wojcioo** [comment]
I'm using docker.....

**Comment by billiaz** [comment]
@Wojcioo I will try to make a docker image for testing! but It will take a bit as I need to test the source code works myself, to submit in one go.

**Comment by billiaz** [comment]
@Wojcioo can you try container `varet/zj2m:fix-607` 

and give me feedback

**Comment by Wojcioo** [comment]
> and give me feedback
@billiaz it looks ok.
![image](https://user-images.githubusercontent.com/33394332/108825006-be323a00-75c2-11eb-8a5d-21b3d17c118d.png)
![image](https://user-images.githubusercontent.com/33394332/108825272-18cb9600-75c3-11eb-837a-c372653e947d.png)

**Comment by billiaz** [comment]
@robertsLando we need to wait a bit for this
On Eurotronic, modes are not properly populated, when I remove the hardcoded device! I will also fix that! and then we can merge!

Testing with
- Danfoss
- Eurotronic

This was never tested as there was a `hass/device.js` declaration! which I try to also cleanup :)

**Comment by Wojcioo** [comment]
I've uploaded new version, and this node is correct discovered both in zwavejs2mqtt and in Home Assistant, but in HA in logs there is an error
```
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:489
Integration: Sensor (documentation, issues)
First occurred: 12:49:31 (3 occurrences)
Last logged: 16:22:09

Platform mqtt does not generate unique IDs. ID zwavejs2mqtt_0xe6dcf749_2-128-0-level already exists - ignoring sensor.sypialnia_danfoss_sypialnia_battery_level
```

I can't also find battery level in mqtt integration / devices.

![image](https://user-images.githubusercontent.com/33394332/110002314-88552a00-7d15-11eb-8ed6-728abf841623.png)

I've check all entities and I can't find more then one NodeID: 2. Where I should look for the error?

**Comment by billiaz** [comment]
LC 13 has one battery level. therefore what you see is right.
the ID is uniquie.

can you please export the node you receie this message from?
also would be nice if this issue was separate
