### ISSUE TITLE
[bug] Add AEON Labs ZW112 Door Window Sensor 6 Sensor Support

### ISSUE THREAD

**Issue by ggruner** [zwave-js/zwavejs2mqtt#610]
Before submitting a bug please read: <https://zwave-js.github.io/zwavejs2mqtt/#/troubleshooting/bug_report>

### Version
Home-Assistant: 2021.2.3

Build/Run method

- [ X ] Docker

zwavejs2mqtt version: 1.1.1
zwavejs version: 6.2.0

### Describe the bug
I have switched from the "old" Zwave 1.4 Migration to the new ZwaveJS2MQTT Migration in Home Assistant. I am using the "AEON Labs ZW112 Door Window Sensor 6 Sensor" Sensor and it seems that this device is at the moment not support.

In the Control Panel I can see the NodeID 007, but no Manufacturer and Product Information are stored. I have wake up the device and the "Last active" was set, but still no Manufacturer and Product Information.

### To Reproduce

-

### Expected behavior

I want to use this sensor as a Window Sensor, where I can see the status if the window is open or closed.

Best Regards,
Gregor

[zwavejs_1.log](https://github.com/zwave-js/zwavejs2mqtt/files/5997595/zwavejs_1.log)

**Comment by ggruner** [comment]
Here is also the zwavejs2mqtt.
[zwavejs2mqtt.log](https://github.com/zwave-js/zwavejs2mqtt/files/5997612/zwavejs2mqtt.log)

**Comment by billiaz** [comment]
@ggruner can you share also an node export from the node itself?

do you see multilevel sensor discovered?

Manual too! I think this is for Zwavejs, to be included as device but also I want to see if Hass works

**Comment by ggruner** [comment]
@billiaz Thanks for the quick response. I have attached the manual and the debug info "node export?" of the Node itself. I hope this is the requested node export that you want.

[ES - Door Window Sensor 6.pdf](https://github.com/zwave-js/zwavejs2mqtt/files/6000826/ES.-.Door.Window.Sensor.6.pdf)
[node007.json.txt](https://github.com/zwave-js/zwavejs2mqtt/files/6000827/node007.json.txt)

**Comment by gilbertand** [comment]
@ggruner running a very similar set up to you with a ZW112. I had to do a long wake up the device and interview the node again from zwavejs and it came good.

`Press and hold the Action Button on the back of theSensor unit until the LED turns yellow (3 seconds in), then your Sensor will wake up for 10 minutes. During this time, the orange LED will fast blink while it is awake.`

**Comment by ggruner** [comment]
@gilbertand I did a long wake up twice now and I see in the logs some information like:

15:24 - > First long wake up
15:24:18.984 CNTRLR « [Node 007] received response for manufacturer information:
                        manufacturer: AEON Labs (0x86)
                        product type: 0x02
                        product id:   0x70

15:57 - > Second long wake up

In the GUI I do not see any manufactur or other information updated.

[zwavejs_1.log](https://github.com/zwave-js/zwavejs2mqtt/files/6004313/zwavejs_1.log)
![Unknown_Node007](https://user-images.githubusercontent.com/4263704/108388331-d3981480-720e-11eb-942d-1b8d845faeb1.PNG)

**Comment by BluGeni** [comment]
I have this exact  door/window sensor and it came in perfect.

**Comment by ggruner** [comment]
@BluGeni thanks also for your feedback and confirmation that this is working.

@ALL I have excluded and included the sensor on my zwave stick and now it seems to working fine and it was recognized on the webui.
