### ISSUE TITLE
[question] Disable zwave logging completely

### ISSUE THREAD

**Issue by Illsley** [zwave-js/zwavejs2mqtt#613]
Hi,

It seems that values are logged to the xxxxx_values.jsonl file in the store despite zwave (and all other logs) logs being disabled in the settings. Is this an expected behavior?

/J

**Comment by robertsLando** [comment]
That is used as cache by zwavejs

**Comment by Illsley** [comment]
Ok thanks. Is it possible to disable the zwavejs cache?

**Comment by robertsLando** [comment]
Nope AFAIK. @AlCalzone

**Comment by AlCalzone** [comment]
That doesn't make sense. You don't want to re-query everything on every restart.
