### ISSUE TITLE
[feat] Targeted debug logs

### ISSUE THREAD

**Issue by mgriffin13** [zwave-js/zwavejs2mqtt#621]
**Is your feature request related to a problem? Please describe.**
I'm trying to debug a specific node, so I want to enable debug logs, but I get flooded with debug logs from every node

**Describe the solution you'd like**
The ability to enable debug logs for anything regarding specific nodes, while leaving the rest of the nodes as INFO logging

**Describe alternatives you've considered**
I can use text tools like grep and less (search), but it's cumbersome and not easy to do inside the UI

**Additional context**

**Comment by robertsLando** [comment]
this is actually possible in zwavejs side using the nodes array env var, btw this is difficult to apply on my side as logs most times has no idea about the node, is the zwavejs side enough?

**Comment by mgriffin13** [comment]
Right now, we can change the log level in real time via the control panel, right? Would there be a way to update that array from the UI without requiring a modification of my docker-compose file?

**Comment by robertsLando** [comment]
> Would there be a way to update that array from the UI without requiring a modification of my docker-compose file?

Changing the env var on fly isn't so good. @AlCalzone We could support that as a log configuration

**Comment by AlCalzone** [comment]
> We could support that as a log configuration

👍🏻 - wanna make a PR? :)

**Comment by robertsLando** [comment]
issue for now :laughing:

**Comment by robertsLando** [comment]
Closed bt #728
