### ISSUE TITLE
Garage Door Openers/Kwikset 910 locks

### ISSUE THREAD

**Issue by drjjr2** [zwave-js/zwavejs2mqtt#624]
Hello,
I know there was an open zwavejs issue about barrier operators not returning the proper states to Home Assistant. After updating to 1.2.1 with zwavejs 6.4, what do I need to do in order to update the device for HA? I thought re-interview node might do it, but that doesn't seem to update the MQTT payload.
Separately, way back in the day there was an openzwave fix for the Kwikset 910s that used the alarm level to indicate locked or unlocked. I saw the 910 mentioned in zwavejs release docs. Do I need to do something similar to update the lock information now that I've upgraded to 1.2.1?

Thank you in advance.

**Comment by drjjr2** [comment]
OK, I see that the barrier operator fix isn't implemented yet.

**Comment by jonathanware** [comment]
@drjjr2 I have a Kwikset 910 and am having some issues. Can I pick your brain on a few things?

**Comment by drjjr2** [comment]
> @drjjr2 I have a Kwikset 910 and am having some issues. Can I pick your brain on a few things?

Certainly. I ended up doing template binary sensors to track the lock/unlock states of my 910s until they get it working right in zwavejs.

**Comment by jonathanware** [comment]
> > @drjjr2 I have a Kwikset 910 and am having some issues. Can I pick your brain on a few things?
> 
> Certainly. I ended up doing template binary sensors to track the lock/unlock states of my 910s until they get it working right in zwavejs.

So my initial problem was not being able to actually unlock/lock via MQTT but it turns out I was just missing the final /set on the targetMode topic. 

My next step is probably what you are talking about. I've found that in the alarm topic (I can't remember the exact one, I'm not at home right now) I'm able to see state changes in the lock. I'm using MQTT-Thing in HomeBridge to control/manage the lock and I've been working on honing my JSON to be able to read/interpret those state changes.

In your original post you mentioned the alarm level. Are you not seeing those state changes in the alarm topic?

**Comment by jonathanware** [comment]
Ok, I was able to come up with a similar looking script in my homebridge MQTT plugin (Just last night actually! It was a glorious moment,) but I only noticed the 21, 22, 24, and 25 states. What are 18 and 19? Locked or unlocked from the keypad?

**Comment by drjjr2** [comment]
Exactly, 18 is locked at keypad and 19 is unlocked from keypad

**Comment by drjjr2** [comment]
> Ok, I was able to come up with a similar looking script in my homebridge MQTT plugin (Just last night actually! It was a glorious moment,) but I only noticed the 21, 22, 24, and 25 states. What are 18 and 19? Locked or unlocked from the keypad?

Heads up, I just upgraded to v3.0.2 and the lock status is now properly reported. But the alarm types are not begging updated so my binary sensors quit working. Not a big deal because now I can just use the lock state like the old days.

**Comment by robertsLando** [comment]
>  But the alarm types are not being updated so my binary sensors quit working

Could you better explain this?

**Comment by drjjr2** [comment]
> > But the alarm types are not being updated so my binary sensors quit working
> 
> Could you better explain this?

Certainly.
Prior to switching to zwavejs2mqtt, the lock state for my Kwikset 910s was properly reported in Home Assistant when I manually locked or unlocked the device. After the switch that state did not get updated but I was able to create the sensors mentioned earlier in the thread to use the alarm type to determine the state of the lock.
After updating to 3.0.2, I no longer see the alarm type change. However the lock state is now correct. The only message I see in the log is
```
2021-03-28 12:34:35.830 INFO ZWAVE: Node 53: value updated: 98-0-currentMode 255 => 0
2021-03-28 12:34:35.830 INFO ZWAVE: Node 53 CC Notification {
type: 6,
event: 2,
label: 'Access Control',
eventLabel: 'Manual unlock operation',
parameters: undefined
}

```

**Comment by robertsLando** [comment]
@AlCalzone ?

**Comment by AlCalzone** [comment]
That's the result of https://github.com/zwave-js/node-zwave-js/pull/2045, which fixes https://github.com/zwave-js/node-zwave-js/issues/1713

Lock/Unlock operations are not state, they are events. They have always been handled as events for devices that support Notification CC V2+. Now we do the same for V1 devices where a mapping from alarmType/Level to notification events is defined.

> However the lock state is now correct

Yeah, use that or listen for the events if you need to distinguish between keypad/RF/manual lock operations.

**Comment by drjjr2** [comment]
Should the alarmtype and alarmlevel entities be removed? MQTT still thinks they are a thing for my Kwikset 910 locks, but if they do nothing do we need them?

**Comment by robertsLando** [comment]
> MQTT still thinks they are a thing for my Kwikset 910 locks

Maybe something retained from previous versions?

**Comment by drjjr2** [comment]
If I delete the store, delete the messages using MQTT Explorer, re-interview and then rediscover the node, they show up again. 
```
{
  "type": "sensor",
  "object_id": "notification_alarmtype",
  "discovery_payload": {
    "value_template": "{{ {}[value_json.value] | default(value_json.value) }}",
    "icon": "mdi:alarm-light",
    "state_topic": "homeassistant/Front_Door_Lock/113/0/alarmType",
    "json_attributes_topic": "homeassistant/Front_Door_Lock/113/0/alarmType",
    "device": {
      "identifiers": [
        "zwavejs2mqtt_0xefa976a8_node53"
      ],
      "manufacturer": "Kwikset",
      "model": "Smart Code with Home Connect Technology (910)",
      "name": "Front_Door_Lock",
      "sw_version": "3.37"
    },
    "name": "Front_Door_Lock_notification_alarmtype",
    "unique_id": "zwavejs2mqtt_0xefa976a8_53-113-0-alarmType"
  },
  "discoveryTopic": "sensor/Front_Door_Lock/notification_alarmtype/config",
  "values": [
    "113-0-alarmType"
  ],
  "persistent": false,
  "ignoreDiscovery": false,
  "id": "sensor_notification_alarmtype"
}
```

**Comment by AlCalzone** [comment]
We cannot be sure that there isn't a value that we can't translate. For these values, we need the alarm type and level to exist.
