### ISSUE TITLE
Issue with climate entity discovery after updating to 1.2.1

### ISSUE THREAD

**Issue by PatrickNByrne** [zwave-js/zwavejs2mqtt#626]
Great work with this so far! Most of my devices are working quite well but I seem to be having a minor issue with HASS discovery of climate devices after updating to 1.2.1. 

Discovery worked in version 1.1.1, but after updating, the existing climate entities are marked unavailable. I have tried re-interviewing the node (works fine), rediscovering it (again seems fine), removed the entity in hass (never came back), and fully removing and reinstalling the HASS integration (lost naming, but otherwise seems to work fine). When I watch the HASS logs, the sensors and binary_sensors are discovered, but the climate entities seem to be completely ignored. I have triple checked that discovery is enabled for these nodes, so I would expect that they would show back up. 

Here is the discovery payload for an example climate device: 

`{
  "type": "climate",
  "object_id": "climate",
  "discovery_payload": {
    "min_temp": 5,
    "max_temp": 40,
    "temp_step": 0.5,
    "modes": [
      "off",
      "heat",
      "cool",
      "auto"
    ],
    "mode_state_template": "{{ {0: \"off\", 1: \"heat\", 2: \"cool\", 3: \"auto\"}[value_json.value] | default('off') }}",
    "current_temperature_topic": "zwave/Master_Bedroom_Thermostat/49/0/Air_temperature",
    "current_temperature_template": "{{ value_json.value }}",
    "temperature_state_topic": "zwave/Master_Bedroom_Thermostat/67/0/setpoint/1",
    "temperature_state_template": "{{ value_json.value }}",
    "temperature_command_topic": "zwave/Master_Bedroom_Thermostat/67/0/setpoint/1/set",
    "mode_state_topic": "zwave/Master_Bedroom_Thermostat/64/0/mode",
    "mode_command_topic": "zwave/Master_Bedroom_Thermostat/64/0/mode/set",
    "action_topic": "zwave/Master_Bedroom_Thermostat/66/0/state",
    "action_template": "{{ {0: \"idle\", 1: \"heating\", 2: \"cooling\", 3: \"fan\", 4: \"idle\", 5: \"idle\", 6: \"fan\", 7: \"heating\", 8: \"heating\", 9: \"cooling\", 10: \"heating\", 11: \"heating\"}[value_json.value] | default('idle') }}",
    "temperature_unit": "F",
    "precision": 0.1,
    "device": {
      "identifiers": [
        "zwavejs2mqtt_0xc4468d53_node7"
      ],
      "manufacturer": "Residential Control Systems, Inc. (RCS)",
      "model": "Thermostat (TBZ48)",
      "name": "Master_Bedroom_Thermostat",
      "sw_version": "1.2"
    },
    "name": "Master_Bedroom_Thermostat_climate",
    "unique_id": "zwavejs2mqtt_0xc4468d53_Node7_climate"
  },
  "values": [
    "49-0-Air temperature",
    "64-0-mode",
    "67-0-setpoint-1",
    "67-0-setpoint-2",
    "66-0-state"
  ],
  "mode_map": {
    "off": 0,
    "heat": 1,
    "cool": 2,
    "auto": 3
  },
  "setpoint_topic": {
    "1": "67-0-setpoint-1",
    "2": "67-0-setpoint-2"
  },
  "default_setpoint": "67-0-setpoint-1",
  "action_map": {
    "0": "idle",
    "1": "heating",
    "2": "cooling",
    "3": "fan",
    "4": "idle",
    "5": "idle",
    "6": "fan",
    "7": "heating",
    "8": "heating",
    "9": "cooling",
    "10": "heating",
    "11": "heating"
  },
  "discoveryTopic": "climate/Master_Bedroom_Thermostat/climate/config",
  "persistent": false,
  "ignoreDiscovery": false,
  "id": "climate_climate"
}`

The device does seem to work correctly in the zwave2js GUI, so this may be an upstream issue with HASS or zwavejs-server. If there are any other logs that may help, please let me know. 

Thanks!

**Comment by PatrickNByrne** [comment]
Adding node dump.

[zwave_js_dump.jsonl.zip](https://github.com/zwave-js/zwavejs2mqtt/files/6006028/zwave_js_dump.jsonl.zip)

**Comment by otherwish** [comment]
Updated to 1.2.1 as well and the climate entity is not being discovered by HA. Exclude and include did not help. Thermostat is Honeywell TH6320ZW.

**Comment by kpine** [comment]
zwave-js 6.3.0+ is not compatible with the current release of HA, in regards to thermostats and some RGB devices. If you need the functionality, aside from modifying HA code yourself, you must run the dev version of HA, or rollback to the 6.2.0 version of zwave-js.

**Comment by kpine** [comment]
FYI, if you are using the Z-Wave JS HA integration, then the MQTT discovery is not used at all.

**Comment by PatrickNByrne** [comment]
@kpine Ah, that would explain it. Thank you! 

I replaced my local instance of discovery.py for the zwave_js integration with the one from this PR: [46355](https://github.com/home-assistant/core/pull/46355) and they are now being discovered as expected.

Thank you again for pointing me in the correct direction. I will mark this solved.

**Comment by 1iveowl** [comment]
> 
> 
> @kpine Ah, that would explain it. Thank you!
> 
> I replaced my local instance of discovery.py for the zwave_js integration with the one from this PR: [46355](https://github.com/home-assistant/core/pull/46355) and they are now being discovered as expected.
> 
> Thank you again for pointing me in the correct direction. I will mark this solved.

How exactly did you do this? I'm running HASS.IO and I can't find the directory with the zwave_js integration. In fact I can find any of the integrations. Is the directory accessable from the Home Assistant Command Line?

**Comment by PatrickNByrne** [comment]
@1iveowl I believe HASS.IO is container based, which means you wouldn't have direct access to the native integration code directories. I suspect that it would be possible to copy the full integration into your local integrations folder however, and update the discovery there.
