### ISSUE TITLE
[question] Home-assistant (docker) zwavejs integration will not start

### ISSUE THREAD

**Issue by zeddski** [zwave-js/zwavejs2mqtt#627]
It has worked before, but after a restart of both HA and zwave-server, HA-integration seems unwilling to start. My zwave units are no longer available from HA.
Relevant logs:

> 2021-02-18 20:55:41 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Z-Wave JS' for zwave_js integration not ready yet. Retrying in 10 seconds,
> 2021-02-18 22:25:11 WARNING (MainThread) [slixmpp.basexmpp] Legacy XMPP 0.9 protocol detected.,
> 2021-02-18 22:33:02 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Z-Wave JS' for zwave_js integration not ready yet. Retrying in 80 seconds,
> 2021-02-18 22:31:42 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Z-Wave JS' for zwave_js integration not ready yet. Retrying in 80 seconds,
> 2021-02-18 22:30:22 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Z-Wave JS' for zwave_js integration not ready yet. Retrying in 80 seconds,
> 2021-02-18 22:29:02 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Z-Wave JS' for zwave_js integration not ready yet. Retrying in 80 seconds,
> 2021-02-18 22:27:42 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Z-Wave JS' for zwave_js integration not ready yet. Retrying in 80 seconds,
> 2021-02-18 22:26:22 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Z-Wave JS' for zwave_js integration not ready yet. Retrying in 80 seconds,
> 2021-02-18 22:25:57 ERROR (stream_worker) [libav.h264] error while decoding MB 5 17, bytestream -32,
> 2021-02-18 22:25:42 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Z-Wave JS' for zwave_js integration not ready yet. Retrying in 40 seconds,
> 2021-02-18 22:25:12 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Z-Wave JS' for zwave_js integration not ready yet. Retrying in 10 seconds,
> 2021-02-18 22:25:22 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Z-Wave JS' for zwave_js integration not ready yet. Retrying in 20 seconds
> 

port 3000 is reachable from HA (as stated it worked before).
Any idea on how to go debug this?

**Comment by robertsLando** [comment]
Please open this on hass side
