### ISSUE TITLE
[bug] unsupported valueIds should be hidden (Single Switch 2)

### ISSUE THREAD

**Issue by larstobi** [zwave-js/zwavejs2mqtt#63]
**Version**

Build/Run method
- [x] Docker
- [ ] PKG
- [x] Manually built (git clone - npm install - npm run build ) 

zwavejs2mqtt version: master

**Describe the bug**
The switch is identified as a dimmer, and I cannot turn it on of of. 
I can set Target value and Transition duration in the zwavejs2mqtt web UI, which doesn't work. The same happens in Home Assistant.

**To Reproduce**
1. Include such switch into network
2. Go to user values
3. Observe dimmer properties

**Expected behavior**
Expected result is to have an on/off switch and not a dimmer value.

**Additional context**
The same happens with my Aeotec Smart Swich 6 wall switch. However, my Neo CoolCam NAS-WR01ZE wall switch works as expected.

**Comment by QNimbus** [comment]
Can confirm the same issue with my Fibaro FGS213 & FGS223 (Single and double switch, built in wall box)

![image](https://user-images.githubusercontent.com/3206309/101620544-f63ecd80-3a14-11eb-966d-08f38ead3e13.png)

![image](https://user-images.githubusercontent.com/3206309/101620356-bbd53080-3a14-11eb-910f-0c2b11abf998.png)

![image](https://user-images.githubusercontent.com/3206309/101620441-d5767800-3a14-11eb-8a17-c8f1c395c757.png)

This produces the following error when using HASS discovery via MQTT:

```bash
2020-12-09 11:31:38 ERROR (MainThread) [homeassistant.helpers.template] Error parsing value: 'dict object' has no attribute 'value' (value: {"id":"8-38-0-currentValue","nodeId":8,"commandClass":38,"commandClassName":"Multilevel Switch","endpoint":0,"property":"currentValue","propertyName":"currentValue","type":"number","readable":true,"writeable":false,"label":"Current value","genre":"user","min":0,"max":99,"list":false,"isCurrentValue":true,"targetValue":"38-0-targetValue","lastUpdate":1607507618211}, template: {{ (value_json.value / 99 * 255) | round(0) }})
2020-12-09 11:31:38 WARNING (MainThread) [homeassistant.components.mqtt.light.schema_template] Invalid brightness value received
2020-12-09 11:31:38 ERROR (MainThread) [homeassistant.helpers.template] Error parsing value: 'dict object' has no attribute 'value' (value: {"id":"22-38-0-currentValue","nodeId":22,"commandClass":38,"commandClassName":"Multilevel Switch","endpoint":0,"property":"currentValue","propertyName":"currentValue","type":"number","readable":true,"writeable":false,"label":"Current value","genre":"user","min":0,"max":99,"list":false,"isCurrentValue":true,"targetValue":"38-0-targetValue","lastUpdate":1607507662260}, template: {{ (value_json.value / 99 * 255) | round(0) }})
2020-12-09 11:31:38 WARNING (MainThread) [homeassistant.components.mqtt.light.schema_template] Invalid brightness value received
```

**Comment by robertsLando** [comment]
@larstobi Wait but it's reported as CC 38 that means it's a multilevel switch not a binary switch, or am I missing something? @AlCalzone

**Comment by larstobi** [comment]
It's definitely a regular switch, on or off, nothing in between.

**Comment by AlCalzone** [comment]
Certainly looks like it. I'll need to see the zwave-js log of the interview to know for sure 😬

**Comment by larstobi** [comment]
[zwave-9.log](https://github.com/zwave-js/zwavejs2mqtt/files/5668264/zwave-9.log)

Look for Node 64.

**Comment by larstobi** [comment]
@AlCalzone And Node 28 is the Aeotec Smart Switch 6.

**Comment by AlCalzone** [comment]
Sorry, I wasn't clear. I need a fresh interview (refreshInfo or what its called here).

**Comment by larstobi** [comment]
[zwave-10.log](https://github.com/zwave-js/zwavejs2mqtt/files/5668612/zwave-10.log)

Here you go, @AlCalzone :-)

**Comment by robertsLando** [comment]
@larstobi In your image I don't see only the light dimmer but also 2 switch discovered `switch_switch` and `switch_switch2`.

**Comment by larstobi** [comment]
When I add it to a Fibaro Home Center Light gateway, the switch actually shows two devices there: one is the switch and one is displayed as a "remote control".  I'm not sure what the purpose of this is.

**Comment by AlCalzone** [comment]
@larstobi I don't see a fresh interview of nodes 28 or 64 in that log. @robertsLando how can he restart the interview through the dashboard?

**Comment by robertsLando** [comment]
@AlCalzone `refresh node info` ?

**Comment by larstobi** [comment]
I did a fresh "Refresh info", and I watched it happening in the log. I can see it at "20:52:29.593 CNTRLR" in the -10 log.

**Comment by AlCalzone** [comment]
Eh, something is wrong with that log. I can't see the messages and some of the info logs half the time - that's why I didn't notice that there's a complete interview.

**Comment by AlCalzone** [comment]
I can check later if that is a problem on my end. But as far as I remember my console outputs during local testing were complete 🤷🏻‍♂️

**Comment by AlCalzone** [comment]
What I can tell from that file:
Node 28 seems to support Multilevel Switch and responds to the Multilevel Switch interview.
Not sure about 64, I couldn't find any mention of Multilevel Switch that in the log.

**Comment by katiuskt** [comment]
Same issue reported by @larstobi and @QNimbus here with my Fibaro Single Switch FGS213. 
It is detected a light_dimmer object I think shouldn't be there.
![image](https://user-images.githubusercontent.com/75622100/102008035-f220f180-3d2d-11eb-902e-9ba5238ef315.png)

Node 8: [json_values.zip](https://github.com/zwave-js/zwavejs2mqtt/files/5684398/json_values.zip)

**Comment by AlCalzone** [comment]
@katiuskt Your cache files show the root endpoint **controls** `Multilevel Switch` in version 3, but does not **support** it. In this case, the value ID probably shouldn't be returned.

**Comment by AlCalzone** [comment]
https://github.com/zwave-js/node-zwave-js/pull/1207 should fix the issue for some of the devices here (including the one from @katiuskt)

**Comment by robertsLando** [comment]
@AlCalzone @larstobi Can I close this as it's not something on my side? or should we move the issue to zwave-js repo?

**Comment by larstobi** [comment]
It's okay with me to close it here. I will include the Fibaro Switch into my Fibaro Home Center Light gateway, and take screenshots of how it looks there. Then I'll open an issue in zwave-js repo. I'll link back here.

**Comment by robertsLando** [comment]
@larstobi Have you tried the fix proposed by @AlCalzone ?

**Comment by larstobi** [comment]
No, not yet. Will do!
