### ISSUE TITLE
[feat] Enable/disable logging to file without restarting network

### ISSUE THREAD

**Issue by larstobi** [zwave-js/zwavejs2mqtt#64]
**Is your feature request related to a problem? Please describe.**
When I need to provide debug logs to debug an issue, I need to enable logging and bump up the log level to debug. When I hit "save" the zwave network restarts and we need do interview all nodes again. This takes a while.

**Describe the solution you'd like**
It would be great if I could enable and disable logging, and change loglevel without the entire network being restarted.

**Describe alternatives you've considered**
Keeping debug logging on all the time. But this creates big files.

**Comment by robertsLando** [comment]
@larstobi this is a WIP, I have submitted a pr on zwave-js that will be released with verison 6.0.0, once that is ready this will be fixed

**Comment by larstobi** [comment]
#47

**Comment by robertsLando** [comment]
Nope, it's not #47, that is for z2m logging. Check pr for 6.0.0 draft on zwavejs

**Comment by larstobi** [comment]
zwave-js/node-zwave-js#1062

**Comment by AlCalzone** [comment]
@robertsLando I think that PR was missing an export for `updateLogConfig` from `zwave-js`

**Comment by robertsLando** [comment]
@AlCalzone because the updateLogConfig is called when creating a new driver instance, but if you want to expose it to users so yes I think it's not exposed

**Comment by AlCalzone** [comment]
I mean if you want to change the logging on the fly, you'll need to use that method from outside zwave-js. Or we need to expose it through the driver class (which probably makes sense if we plan to refactor the logging to be instance-scoped)

**Comment by robertsLando** [comment]
> Or we need to expose it through the driver class

Personally I would prefer this solution!

**Comment by robertsLando** [comment]
@larstobi I will close this in favor of: https://github.com/zwave-js/zwavejs2mqtt/issues/23
