### ISSUE TITLE
[bug] climate.thermostat entity became unavailable after install hass.io addon 0.4.2

### ISSUE THREAD

**Issue by JAAlperin** [zwave-js/zwavejs2mqtt#648]
Before submitting a bug please read: <https://zwave-js.github.io/zwavejs2mqtt/#/troubleshooting/bug_report>

### Version

Build/Run method

- [X] Docker (via hassio addon)
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build )

zwavejs2mqtt version: 1.2.1
zwavejs version: 6.0.0 ???

### Describe the bug

climate.thermostat entity of Nortek Security & Control LLC Z-Wave Plus Thermostat GoControl GC-TBZ48 Thermostat
became unavailable after install hass.io addon 0.4.2.  

### To Reproduce

update hassio addon from 0.4.1 to 0.4.2 - changelog:
⬆️ Bump release-drafter/release-drafter from v5.13.0 to v5.14.0 @dependabot (#34)
⬆ Upgrades nodejs to 14.15.5-r0 @frenck (#37)
⬆ Upgrades libusb to 1.0.24-r1 @frenck (#38)
⬆️ Bump docker/build-push-action from v2.2.2 to v2.3.0 @dependabot (#36)
Upgrade add-on base image to 9.1.3 @frenck (#39)
⬆ Upgrades ZwaveJS2Mqtt to v1.2.0 @frenck (#40)
Update database to bcb1feca586b2fe1dc584283e548e1441d188547 @frenck (#41)
⬆ Upgrades ZwaveJS2Mqtt to v1.2.1 @frenck (#42)

### Expected behavior

Expected thermostat to remain available and useable as it was perviously.

**Comment by robertsLando** [comment]
Please opne this kind of errors on hass core repo, it's not an error on my side :)

**Comment by JAAlperin** [comment]
The hass core repo did not change, only the addon did.  Frenck maintains addon, commented it only wraps the application, and suggested opening the issue with you.

**Comment by hmorkemo** [comment]
FWIW: The same happened recently with Heatit thermostats too. Both versions 2 and 3. The error's there at least on version 2012.02.09

**Comment by JAAlperin** [comment]
2012.02.09 is a supervisor version not core.  Was the Heatit problem resolved?  Got a link?
