### ISSUE TITLE
IDLock 150, erratic behaviour

### ISSUE THREAD

**Issue by hmorkemo** [zwave-js/zwavejs2mqtt#651]
Before submitting a bug please read: <https://zwave-js.github.io/zwavejs2mqtt/#/troubleshooting/bug_report>

### Version

Build/Run method

- [x ] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build )

zwavejs2mqtt version: 1.2.1
zwavejs version: 6.4.0

### Describe the bug

IDLock 150 often doesn't come in as expected.
One came in fine (227), another (10) was very sparse, with very few entities, and the lock entity is unavailable.
I have waited for hours after adding, and also tried re-interviewing the lock.
The attached zip file shows the zwavejs .json debug files for the two locks, screen shots from zwavejs2mqtt and the ha integration.
It also includes my zwavejs2mqtt settings.
[idlock.zip](https://github.com/zwave-js/zwavejs2mqtt/files/6010888/idlock.zip)

### To Reproduce

1. Try to add (secure mode) an idlock 150
2. Observe the added device and it's entities

### Expected behavior

Adding should be easy, and behave the same way every time.

### Additional context
Home Assistant 2021.02.11 on an Intel NUC. Debian 10. All addins are up-to-date

**Comment by robertsLando** [comment]
are you using zwavejs integration?

**Comment by hmorkemo** [comment]
zwavejs2mqtt and zwavejs integration.

**Comment by robertsLando** [comment]
ok so please open this issue on home assistant repo. It's not something that I can fix on my side
