### ISSUE TITLE
Notifications not sent when node not completed interview stage [bug]

### ISSUE THREAD

**Issue by chrish987** [zwave-js/zwavejs2mqtt#658]
Before submitting a bug please read: <https://zwave-js.github.io/zwavejs2mqtt/#/troubleshooting/bug_report>

### Version

Build/Run method

- [X ] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build )

Latest release

### Describe the bug

Not sure if this is a bug, or working as designed, but causes usability issues.

When a node has not completed the interview process after a server restart configured alerts in the gateway are not sent. Name of node is not shown in the gateway config (see attach)
![Capture-zw1](https://user-images.githubusercontent.com/77754678/108571185-7b7b2280-7374-11eb-86d5-2ab00b4b6c8a.JPG)
, and no mqtt message is sent. I can see that the node is sending the value as can see the update from the node in the debug window. This is mainly an issue for devices that have a long wakeup period (maybe 24 hours).

### Expected behavior

Node can send configured mqtt notifications even if still undergoing interview process after server restart.

**Comment by robertsLando** [comment]
This is intended
