### ISSUE TITLE
[question] Best way to update when building from git?

### ISSUE THREAD

**Issue by crxporter** [zwave-js/zwavejs2mqtt#659]
I'm running this with the `git clone ...` then manual build way. I'm wondering what the preferred way to update would be. I've tried a few things and always manage to get things updated - but I often get an error that `package-lock.json` has been changed locally.

Today I did a 2 step before the pull:
```
git stash
git stash drop
git pull
npm install
npm run build
```

Before restarting my system service. Is there a better recommendation to trash the locally changed files?

**Comment by blhoward2** [comment]
I always just clone again. Otherwise you need to re-merge the upstream master into your master.

**Comment by robertsLando** [comment]
```
git reset --hard
git pull
npm install
npm run build
```
