### ISSUE TITLE
[question] ThermoFloor Z-TRM2fx climate/thermostat

### ISSUE THREAD

**Issue by johanko** [zwave-js/zwavejs2mqtt#661]
I moved from a dev env to docker and also made the migration to Zwavejs2mqtt. First tried with websocket and all devices except my ThermoFloor Z-TRM2fx worked fine.

I run the thermostat in Floor sensor mode(F-mode, floor sensor mode(Default). However there are two Multilevel sensors in the device config:
[7-49-2-Air temperature] Air temperature  and [7-49-3-Air temperature] Air temperature(this one is the floor sensor).
Home Assistant uses the [7-49-2-Air temperature] Air temperature topic,  which always is 0.

I had to change the zwave2mqtt from ws to mqtt. Then change Hass Device JSON to use "current_temperature_topic" : "zwave/nodeID_7/49/3/Air_temperature" and state values from "49-2-Air temperature" to "49-3-Air temperature".

So my question, is this intended setup in the config? It seems not right, both in naming and behaviour. Let me know if you need more info.

**Comment by johanko** [comment]
Also, great work on this repo :)

**Comment by michelwilson** [comment]
I have a similar issue with a Z-TRM3, it has an internal air sensor, external air sensor, and external floor sensor. The climate device via websocket in Home assistant uses the first sensor to show the current temperature. The second and third sensor are shown as sensor device. I'm trying to get the climate device to use the 3rd sensor (the floor one) instead, but not having much success so far, as the documentation on this is not very extensive.

Ideally, the device would work as follows:
- climate device uses '112-0-2 Sensor mode' to determine which sensor is used to control the thermostat, and uses this to select the correct current temperature
- all three temperature sensors are also exported as sensor, possibly even with the correct name

But, how to achieve this! Can someone point me into the right direction? I probably have to write a `customDevices.json`, but so far the one I have is throwing errors. Are there any good, current examples?

**Comment by johanko** [comment]
I just made the following in customDevices.json, which works for me using websockets.
```
{
  "411-514-3": [
    {
      "type": "climate",
      "object_id": "thermostat",
      "values": ["64-1-mode", "49-3-Air temperature", "67-1-setpoint-1", "67-1-setpoint-2"],
      "mode_map": { "off": "Off", "heat": "Heat", "cool": "Cool" },
      "setpoint_topic": { "Heat": "67-1-setpoint-1", "Cool": "67-1-setpoint-2" },
      "default_setpoint": "67-1-setpoint-1",
      "discovery_payload": {
        "min_temp": 15,
        "max_temp": 30,
        "temp_step": 0.5,
        "modes": ["off", "heat", "cool" ],
        "mode_state_topic": "64-1-mode",
        "mode_command_topic": true,
        "current_temperature_topic": "49-3-Air temperature",
        "current_temperature_template": "{{ value_json.value }}",
        "temperature_state_template": "{{ value_json.value }}",
        "temperature_command_topic": true
      }
    }
  ]
}
```
Might be some firmware update on the device. But doublecheck in your nodes in zwave2mqtt for the complete "topic". Eg. [49-3-Air temperature] which atleast for me is the Floor sensor.

**Comment by robertsLando** [comment]
You are speaking about websockes and also mqtt discovery, I don't understand which one discovery methoid you are using. If it works with the custom devices it means you are using mqtt discovery

**Comment by michelwilson** [comment]
I am using the websocket connection method between HA and zwavejs2mqtt. But from what you're saying I understand that using custom devices does not work at all for websockets? So with this method the default behavior is it, no customization? That kinda explains that nothing seems to change even if the json is parsed correctly ;)

**Comment by robertsLando** [comment]
@michelwilson There are 2 ways to discover devices, using MQTT discovery or using zwave js integration (with zwavejs server option enabled on settings). In theory you coul duse both, but they could have some conflicts/dups in entities created

**Comment by michelwilson** [comment]
So, sorry for asking possibly stupid questions, but: if I use websocket integration, zwavejs "decides" which devices HA sees, based on ... some kind of internal device library?, and if I use MQTT discovery, zwavejs2mqtt "decides" which devices HA sees, based on for example `customDevices.json`?

**Comment by robertsLando** [comment]
@michelwilson both try to guess the correct entities to create based on different things (CC, property, device class etc). On my side to fix some devices incompatibilities there are the custom devices files, it's like a db for non compatible devices

**Comment by michelwilson** [comment]
Clear. I've currently set things up using mqtt and that works like a charm, after manually adding a temperature sensor for the air temperature (which is normally provided via the climate entity), and changing the climate entity to use the floor temperature as current temperature.
Before I start trying something impossible: is there a way to dynamically select the current temperature topic (using a template for example), based on a configuration value? Specifically, based on "112-0-2 Sensor mode", this thermostat uses one out of three temperature sensor readings as current temperature, and it would be very nice to automatically generate the climate entity using the correct temperature sensor.

**Comment by robertsLando** [comment]
> dynamically select the current temperature topic (using a template for example), based on a configuration value

Unfortunally nope, configuration values are device specific and so If I would add the support for this device that would not work with another one that has multiple sensors for temperature. The best thing you can do in this case if you have multiple deivces like that is to create an entry in customDevices so this will be applied to all them
