### ISSUE TITLE
How to update value_template

### ISSUE THREAD

**Issue by wranglatang** [zwave-js/zwavejs2mqtt#662]
Hi, Im trying to update the the value template of a device I have from what is in the attached screen grab to: 

`"value_template": "{% if (value_json.value | int) == 21 %} 'Locked Manually' {% else %} 'other' {% endif %}",`

Im able to update and store it but HA doesn't seem to pick up the change. Any ideas?

<img width="1213" alt="image" src="https://user-images.githubusercontent.com/30660751/108602809-0885a200-739c-11eb-89e3-15a2bf50395c.png">

**Comment by ivdimitro** [comment]
Have clicked "rediscover node"?

**Comment by wranglatang** [comment]
Yes I have. This seems to just reset all the settings back to what they were by default.

**Comment by robertsLando** [comment]
pressing rediscover should do the trick.

**Comment by wranglatang** [comment]
> pressing rediscover should do the trick.

Thanks Robert - However it doesn't, it just overwrites my update. Please take a look at the at the attached screen recording.

https://user-images.githubusercontent.com/30660751/108694140-95447300-74f6-11eb-9348-815f20ba1596.mov

**Comment by robertsLando** [comment]
Try to press on rediscover first and then on update

**Comment by wranglatang** [comment]
Okay, that seems to have got the configuration to stick. But home assistant is not reflecting that change.

**Comment by robertsLando** [comment]
> But home assistant is not reflecting that change.

If you have mqtt explorer you could check the payload sent to hass, if it matches the one you inserted the problem is in hass side (check hass logs to see if the template contains errors

**Comment by wranglatang** [comment]
Im not using MQTT - Im using the web server integration.

**Comment by robertsLando** [comment]
> Im not using MQTT - Im using the web server integration.

LOL so you are wasting your time here, that's for MQTT discovery, hass zwavejs integration uses the zwave js server

**Comment by wranglatang** [comment]
Doh!

So how do I update the configuration for ZWave JS Server?

**Comment by robertsLando** [comment]
You can't AFAIK, it is plug and play

**Comment by wranglatang** [comment]
Thanks fo your help!
