### ISSUE TITLE
[question] How to enable the Home Assistant tab in Control Panel

### ISSUE THREAD

**Issue by avanstiphout** [zwave-js/zwavejs2mqtt#667]
I apologize if I missed something obvious, but how does one enable the Home Assistant "tab" in the control panel?

I see Node, Groups and Debug Info, but not Home Assistant? I am running the "latest" docker. 

Great work by the way on the project! Being able to restart HA without bringing down and restarting the ZWave network is a huge change!

**Comment by avanstiphout** [comment]
I answered my own question. But, for anybody else, the answer is in the documentation (where else?) :)

https://zwave-js.github.io/zwavejs2mqtt/#/guide/homeassistant

**Comment by robertsLando** [comment]
Thanks !
