### ISSUE TITLE
[bug] Docker: Adding "HTTPS = true" as environment variable throws an error causing the docker to crash upon startup

### ISSUE THREAD

**Issue by avanstiphout** [zwave-js/zwavejs2mqtt#670]
### Version

Build/Run method

- [X] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build )

zwavejs2mqtt version: 1.2.2
zwavejs version: 6.4.0

### Describe the bug

Adding HTTPS=true as an environment variable in docker-compose leads to the following error (as per the docker log):

2021-02-21 18:26:19.785 INFO APP: HTTPS is enabled. Loading cert and keys from store...

2021-02-21 18:26:19.842 INFO APP: Cert and key not found in store, generating fresh new ones...

Error: Could not find openssl on your system on this path: openssl

    at /usr/src/app/node_modules/pem/lib/openssl.js:237:23

The docker container fails to start and restarts only to crash with the same error.

### To Reproduce

As per the above

### Expected behavior

Docker started with HTTPS support.

**Comment by robertsLando** [comment]
PR created
