### ISSUE TITLE
[question] Missing entities on switch

### ISSUE THREAD

**Issue by scaarup** [zwave-js/zwavejs2mqtt#672]
Hi.
It is suggested here https://community.home-assistant.io/t/logic-group-zdb5100-matrix-switch/144295/79 that I should modify some discovery package to get missing LED entities on my wall switch.

```
    "payload_off": false,
    "payload_on": true,
    "value_template": "{{ value_json.value }}",
```
I am not using mqtt for discovery. How do I accomplish this?

Thanks.

**Comment by billiaz** [comment]
@scaarup How do you discover your devices? with the server?

**Comment by scaarup** [comment]
> @scaarup How do you discover your devices? with the server?

Yeah I am using ws and the zwavejs integration (default discovery). I found out, that I could create my missing light entities manually as mqtt lights - but I really think they should be discovered in stead.

**Comment by robertsLando** [comment]
If you are using the zwave js integration there is nothing I can do here to help. You should instead open this bug on hass repo
