### ISSUE TITLE
[bug] Manufacturer/product names missing on all nodes

### ISSUE THREAD

**Issue by michelwilson** [zwave-js/zwavejs2mqtt#673]
Before submitting a bug please read: <https://zwave-js.github.io/zwavejs2mqtt/#/troubleshooting/bug_report>

### Version

Build/Run method

- [ ] Docker
- [ ] PKG
- [X ] Manually built (git clone - npm install - npm run build )

zwavejs2mqtt version: 1.2.2.80163d1
zwavejs version: 6.4.0

### Describe the bug

After updating to the latest git version (including `npm install`) _none_ of my nodes show the manufacturer and product names anymore, including the controller USB stick. It does show the ids, so all I see is "Unknown manufacturer 134", "Unknown product 90".

### Additional context

Before updating to the current version I was at commit `94ff7ed`, and all the manufacturers/product names did show up correctly. I of course tried downgrading to that commit, but the issue persists, even after removing all the json data from `store`, except the config with the network key etc.

**Comment by nooogs** [comment]
Seeing this as well. I will note that everything appears to work properly and all values/attributes are pulled from the respective devices. It just seems as though translation between the manufacturer and product IDs and their corresponding names is broken.

**Comment by robertsLando** [comment]
Please add logs

**Comment by michelwilson** [comment]
Unclear which logs you're looking for, but here are some snippets that seem like they could be of interest. This is the controller:

```
2021-02-21 20:22:52.407 INFO ZWAVE: Node 1 is alive
2021-02-21 20:22:52.413 WARN ZWAVE: Node 1 doesn't support groups associations
2021-02-21 20:22:52.416 INFO ZWAVE: Node 1 ready: Unknown manufacturer 134 - Unknown product 90 (1)
2021-02-21 20:22:52.419 INFO ZWAVE: Node 1: interview completed, all values are updated
```

And for another node:

```
2021-02-21 20:22:52.551 INFO ZWAVE: Node 5 is alive
2021-02-21 20:23:02.823 INFO ZWAVE: Node 5: value added: 114-0-manufacturerId => 411
2021-02-21 20:23:02.825 INFO ZWAVE: Node 5: value added: 114-0-productType => 3
2021-02-21 20:23:02.827 INFO ZWAVE: Node 5: value added: 114-0-productId => 515
...
2021-02-21 20:23:27.560 INFO ZWAVE: Node 5 ready: Unknown manufacturer 411 - Unknown product 515 (3)
2021-02-21 20:23:27.563 INFO ZWAVE: Node 5: interview completed, all values are updated
```

I also have some zwavejs snippets, this is the controller manufacturer and product id, they match with what zwavejs2mqtt shows:
```
20:46:23.054 CNTRLR   received API capabilities:
                        serial API version:  1.1
                        manufacturer ID:     0x86
                        product type:        0x01
                        product ID:          0x5a
                        supported functions: 
```

I also tried triggering an interview for node 5, the zwavejs log shows, among a lot of other info:
```
17:47:54.972 CNTRLR » [Node 005] querying manufacturer information...
17:47:55.312 CNTRLR « [Node 005] received response for manufacturer information:
                        manufacturer: ThermoFloor (0x019b)
                        product type: 0x03
                        product id:   0x0203
```
So here the manufacturer at least is resolved correctly. Still nothing in zwavejs2mqtt:
```
2021-02-22 17:47:44.682 INFO ZWAVE: Node 5 is alive
2021-02-22 17:47:55.302 INFO ZWAVE: Node 5: value added: 114-0-manufacturerId => 411
2021-02-22 17:47:55.304 INFO ZWAVE: Node 5: value added: 114-0-productType => 3
2021-02-22 17:47:55.304 INFO ZWAVE: Node 5: value added: 114-0-productId => 515
...
2021-02-22 17:48:17.885 INFO ZWAVE: Node 5 ready: Unknown manufacturer 411 - Unknown product 515 (3)
2021-02-22 17:48:17.887 INFO ZWAVE: Node 5: interview completed, all values are updated
```
Please let me know if you want to see more log files :) I can also poke around and add debugging statements in various places, if it helps.

**Comment by robertsLando** [comment]
@AlCalzone missing config? 

cc @blhoward2

**Comment by AlCalzone** [comment]
Nope: https://devices.zwave-js.io/?jumpTo=0x019b:0x0003:0x0203:0.0

**Comment by michelwilson** [comment]
Ah, I just noticed that all the config parameter descriptions are also suddenly gone. These used to be there! So looks like something breaks in the interaction between zwavejs and zwavejs2mqtt?

**Comment by blhoward2** [comment]
According to discord the current Zwave2jsmqtt doesn't work with the js server and isn't meant to, right? They need to change some things.

**Comment by michelwilson** [comment]
In `lib/ZwaveClient.js` I added some debugging code in `onNodeReady`, and there I see that `zwaveNode.deviceConfig` is `undefined`. So the problem is probably in zwavejs then?

**Comment by michelwilson** [comment]
So, I also tried downgrading to the latest version of zwavejs2mqtt using zwave-js 6.3.0, and 6.2.0, neither of those had any effect. I'm starting to doubt my sanity, I'm pretty sure that at the point of my unadvised update to the latest version of master I had manufacturer and product types and all the config settings working just fine!

**Comment by michelwilson** [comment]
Ok, I want to apologize for wasting any of your time looking into this. I feel pretty stupid right now. After the update I did a rebuild under my user account, not under the user account running zwavejs2mqtt, and apparently `@zwave-js/config` requires _write_ access to the `node_modules/@zwave-js/config/devices` directory. Seems a bit odd that it's writing here, but at least it's working properly again!

**Comment by syphernl** [comment]
Weird. I'm having the same problem but am using the pkg version. Started since 1.2.0, wasn't a problem before that. All files and folders are owned and accessible for the user that runs the app... 

But if it wants to write to files included in the `bindings.node` or `fibers.node` that would be a bit problematic...

**Comment by AlCalzone** [comment]
> `@zwave-js/config` requires _write_ access

Yes. The index file used to look up configuration files is generated on demand to avoid permanent conflicts on git.

**Comment by nooogs** [comment]
@syphernl, are you still seeing this? I know this is closed but I'm actually still seeing this using the packaged version. I've tried redownloading and re-extracting it, making sure owner on all files is the user the service is running as, and even changing the user it's running as and updating the permissions accordingly. I'm not sure what I'm missing here. There's nothing that I can see in my logs. Here is the beginning of a recent log. If I can include any further logs to help with this I'm all for it.
`
 ______                       _     ___                  _   _
|___  /                      (_)   |__ \                | | | |
   / /_      ____ ___   _____ _ ___   ) |_ __ ___   __ _| |_| |_
  / /\ \ /\ / / _` \ \ / / _ \ / __| / /| '_ ` _ \ / _` | __| __|
 / /__\ V  V / (_| |\ V /  __/ \__ \/ /_| | | | | | (_| | |_| |_
/_____|\_/\_/ \__,_| \_/ \___| |___/____|_| |_| |_|\__, |\__|\__|
                            _/ |                      | |
                           |__/                       |_|

2021-02-22 23:54:03.953 WARN STORE: scenes.json not found
2021-02-22 23:54:03.955 WARN STORE: nodes.json not found
fatal: not a git repository (or any of the parent directories): .git
2021-02-22 23:54:04.761 INFO APP: Version: 1.2.3
2021-02-22 23:54:04.762 INFO APP: Application path:/etc/zwavejs2mqtt
2021-02-22 23:54:04.819 INFO MQTT: MQTT is disabled
2021-02-22 23:54:04.825 INFO ZWAVE: Connecting to /dev/ttyACM0
2021-02-22 23:54:04.840 INFO APP: Listening on port 8091 host 0.0.0.0 protocol HTTP
2021-02-22 23:54:09.368 INFO ZWAVE: Zwave driver is ready
2021-02-22 23:54:09.370 INFO ZWAVE: Controller status: Driver ready
2021-02-22 23:54:09.374 INFO ZWAVE: Scanning network with homeid: 0xdf5c1aa5
2021-02-22 23:54:09.376 INFO ZWAVE-SERVER: ZwaveJS server listening on port 3000
2021-02-22 23:54:09.422 INFO ZWAVE: Node 1 is alive
`

**Comment by syphernl** [comment]
@nooogs Yes, I am still seeing this problem with the packaged version as well.  Hoping this can get fixed.

**Comment by AlCalzone** [comment]
I guess we could ignore write errors during index generation. The downside is that the index will be regenerated on every restart.

**Comment by syphernl** [comment]
@AlCalzone Wouldn't it be possible to write the index to the store directory instead? That one exists for all run methods.

**Comment by michelwilson** [comment]
@nooogs to be sure you're having the same problem, enable zwave-js logging, and look for `CONFIG` entries in the zwave-js log file. Mine contained a pretty obvious "no access" error, including the path to the file.

**Comment by AlCalzone** [comment]
@syphernl it should be, but it is a bit more difficult to do. Since I'm looking to release today, I'm going with the quick fix for now.

**Comment by nooogs** [comment]
@michelwilson it's definitely the same issue. Here's the associated logs.
`08:37:14.673 DRIVER   version 6.4.0
08:37:14.674 DRIVER
08:37:14.674 DRIVER   starting driver...
08:37:14.678 DRIVER   opening serial port /dev/ttyACM0
08:37:14.693 DRIVER   serial port opened
08:37:14.693 SERIAL » [NAK]                                                                   (0x15)
08:37:16.197 DRIVER   loading configuration...
08:37:19.000 CONFIG   Could not load or regenerate device config index: File or directory '/**/zwave
                      js2mqtt/node_modules/@zwave-js/config/config/devices/index.json' was not inclu
                      ded into executable at compilation stage. Please recompile adding it as asset
                      or script.
08:37:19.029 DRIVER   beginning interview...
08:37:19.029 DRIVER   added request handler for AddNodeToNetwork (0x4a)...
                      1 registered
08:37:19.029 DRIVER   added request handler for RemoveNodeFromNetwork (0x4b)...
                      1 registered
08:37:19.030 DRIVER   added request handler for ReplaceFailedNode (0x63)...
                      1 registered
`

**Comment by syphernl** [comment]
Appears to be working fine now with `App Version 1.4.0 | Zwavejs Version 6.5.0 | Zwavejs-server Version 1.0.0`

**Comment by syphernl** [comment]
@AlCalzone Unfortunately 1.4.0 seems causing some issues here, I've created a new issue for that: #734
