### ISSUE TITLE
[bug] Cannot find module '/usr/src/app/bin/www'

### ISSUE THREAD

**Issue by HannesDi** [zwave-js/zwavejs2mqtt#682]
Probally my fault but i cannot get it to start..

at startup i got the following log infos:

----------------------------------------------------------------------------------------------------------------
node:internal/modules/cjs/loader:926
throw err;
^

Error: Cannot find module '/usr/src/app/bin/www'

at Function.Module._resolveFilename (node:internal/modules/cjs/loader:923:15)
at Function.Module._load (node:internal/modules/cjs/loader:768:27)
at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
at node:internal/main/run_main_module:17:47 {
code: 'MODULE_NOT_FOUND',
requireStack: []
}
----------------------------------------------------------------------------------------------------------------

what did i miss or doing wrong?

**Comment by robertsLando** [comment]
I need to know how you build the app. Docker? Git clone and npm run build ?

**Comment by HannesDi** [comment]
Hello, t think i found the Problem... 

I running the "Unraid" Docker Container and  in the Settings for persistant path there are 2 Entrys...

Initial both empty:

"Appdata:"
Container Path: /usr/src/app/store -> 

"Zwavejs Log:"
Container Path: /usr/src/app/bin ->

and i filled up the to:

"Appdata:"
Container Path: /usr/src/app/store -> /mnt/user/appdata/zwavejs2mqtt

"Zwavejs Log:"
Container Path: /usr/src/app/bin -> /mnt/user/appdata/zwavejs2mqtt/log

and thats the problem.. i guess the Label: "Zwavejs Log:" is wrong or i am dumb and dont get what i should fill in here? 
when i leave this empty it starts fine...

I think we can close this and i will contact the maintainer from the "zwavejs2docker unraid docker container" for a better description of the entry..

Thank you for your great Work and Sorry for Stealing your Time.

**Comment by robertsLando** [comment]
No worries, glad you fixed the problem :)
