### ISSUE TITLE
bug: Named Topics missing endpoint in topic

### ISSUE THREAD

**Issue by Lopton** [zwave-js/zwavejs2mqtt#69]
I am trying out Zwavejs2mqtt and thought that this time I'd try Type: "Named Topics" in the Gateway. 

It worked find for sending data to Home Assistant, but when I tried to send commands (like toggling a switch) I could see the commands being received in the console output (I am attached to the docker container and I would set "z2m:Mqtt: Message received on zwavJs2Mqtt/Patio/Shades_Ext_South_West/switch_multilevel/targeValue/set"), but no Z-wave commands would be sent and the device would not operate.

I then changed my Type to "ValueID topics" and the commands were now being received ("z2m:Mqtt: Message received on zwaveJs2Mqtt/Patio/5/38/0/targetValue/set"), and the Z-wave commands would be sent and the device responded.

I'm not sure if I was doing something wrong, or if I should be using ValueID instead of Named, but I figured I'd let you know that Named wasn't working for inbound messages from Home Assistant for me.

**Comment by ODINServ** [comment]
Hi,

I guess you might miss the endpoint in the topic:

So your request:
```zwavJs2Mqtt/Patio/Shades_Ext_South_West/switch_multilevel/targeValue/set```

Beside the type in ```targeValue```i guess it should be:
```zwavJs2Mqtt/Patio/Shades_Ext_South_West/switch_multilevel/endpoint_1/targetValue/set```

I also have lots of multi level switches and this is working for me:
```zwavejs2mqtt/bathroom/switch_multilevel/endpoint_1/targetValue/set```

Hope  it helps!

**Comment by Lopton** [comment]
Thanks, I was just using the auto generated discovery values, so I kinda expected them to be correct. I may trying adding the endpoints manually and seeing if that works.

**Comment by robertsLando** [comment]
This is actually a bug, the gateway is actually missing endpoints in named mode. Thanks for the issue will fix this tomorrow!

**Comment by robertsLando** [comment]
Can someone try with #74

**Comment by ODINServ** [comment]
I can but not sure how, i have them inside the discovery topic already.
I''m running master a little bit behind @ ```64dbcd5902d30b2fc5320011f9d0b92efa235379```

look: ```hass/cover/bedroom_left/position/config``` contains already:
* ```"command_topic":"zwavejs2mqtt/bedroom_left/switch_multilevel/endpoint_1/targetValue/set"```
* ```"set_position_topic":"zwavejs2mqtt/bedroom_left/switch_multilevel/endpoint_1/targetValue/set"```

**Comment by robertsLando** [comment]
@ODINServ Because when endpoint is > 1 it was already added, with that fix it is always added in the topic
