### ISSUE TITLE
[feat] Indicate FW update progress in the node details

### ISSUE THREAD

**Issue by dnakamura** [zwave-js/zwavejs2mqtt#691]
**Is your feature request related to a problem? Please describe.**
Location of current firmware update progress is not immediately obvious if the "Controller Status" text box is scrolled out of view

**Describe the solution you'd like**
Add a progress indication in the node details right by the button to start the firmware update. Ideally a nice graphical progress bar, but a simple text status would also suffice.

**Additional context**
![image](https://user-images.githubusercontent.com/12418336/108764865-203a6300-7521-11eb-8002-2f3c1b5e94e7.png)

**Comment by robertsLando** [comment]
Added to todos :)

**Comment by towerhand** [comment]
If you look here: https://github.com/zwave-js/zwavejs2mqtt/discussions/461 there are plans to move the “controller status”  and always have it visible.

**Comment by robertsLando** [comment]
If that is enough for you I can reference it to that PR. I though you was looking for something more like a progress bar
