### ISSUE TITLE
[bug] Gateway not listening on proper topic after node rename unless container is restarted

### ISSUE THREAD

**Issue by DanielWinks** [zwave-js/zwavejs2mqtt#693]
Before submitting a bug please read: <https://zwave-js.github.io/zwavejs2mqtt/#/troubleshooting/bug_report>

### Version 1.2.2

Build/Run method

- [ X ] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build )

zwavejs2mqtt version: 1.0.0
zwavejs version: 6.0.0

### Describe the bug

When adding a new node (a lock in this example), I am unable to set any values until I restart ZwaveJS2MQTT, if I give the newly added node a name.

### To Reproduce

1. Set 'Use nodes name instead of numeric nodeIDs' in options. If it might matter, I have "Ignore location" off, and do not use location on any node, just a descriptive name, such as "kitchen_door_lock".
2. Include new node, which will not have a "Name" upon initial inclusion
3. Open node config, set "Name" (ie, 'kitchen_door_lock'), this will cause all of the published values in MQTT to update from `z2m/nodeID_XX` to `z2m/kitchen_door_lock`. If I lock/unlock the lock from the admin panel, I see these updates published on the new node_name based topic. `z2m/kitchen_door_lock/98/0/currentMode` will receive updates when I lock/unlock the lock, all other topics are published to the new name-based topics as expected.
4. Publishing 0 or 255 to `z2m/kitchen_door_lock/98/0/targetMode/set` results in nothing whatsoever happening. Nor does anything happen if I publish 0 or 255 to z2m/XX/98/0/targetMode/set where XX is the node ID.
5. Restarting the docker container causes the gateway to listen to incoming messages on new name-based topic as expected.

Both published messages and received messages are updated to use new MQTT topic immediately, without requiring a restart. Giving the node a name causes everything it publishes to MQTT to immediately update, but it doesn't seem to switch to listening to the new topic properly.

### Additional context

Example of entirely ignored MQTT messages:
````
2021-02-22 16:04:08.911 INFO MQTT: Message received on z2m/kitchen_door_lock/98/0/targetMode/set, '255'
2021-02-22 16:04:09.098 INFO MQTT: Message received on z2m/kitchen_door_lock/98/0/targetMode/set, '255'
2021-02-22 16:04:09.270 INFO MQTT: Message received on z2m/kitchen_door_lock/98/0/targetMode/set, '255'
2021-02-22 16:04:09.459 INFO MQTT: Message received on z2m/kitchen_door_lock/98/0/targetMode/set, '255'
2021-02-22 16:04:09.647 INFO MQTT: Message received on z2m/kitchen_door_lock/98/0/targetMode/set, '255'
````

This is a fairly minor bug, since it 'fixes' itself if you restart the container, however it is unexpected since everything else on MQTT seems to immediately update to the new topic, just the gateway seems to forget to actually listen to the new topics.

**Comment by robertsLando** [comment]
@DanielWinks Yep right
