### ISSUE TITLE
[feat] Clean-up log files regularly

### ISSUE THREAD

**Issue by SeraphimSerapis** [zwave-js/zwavejs2mqtt#705]
**Is your feature request related to a problem? Please describe.**
While checking out my zwavejs2mqtt log files, I noticed that both `zwavejs2mqtt.log` and my `zwavejs_1.log` seem to grow in size quite rapidly. I only just started using zwavejs2mqtt with Home Assistant's latest release and wonder what the filesize for both logs will look like after 3, 6, or 12 months of usage.

This is with log level set to `DEBUG` using the latest docker image.

**Describe the solution you'd like**
It would be great if we could set how many log lines to keep or how many days of logs we'd like to preserve. This could be handled either via the UI or by passing an environment variable.

**Describe alternatives you've considered**
I could run a cron job that deletes the file regularly.

**Additional context**
![Screen Shot 2021-02-23 at 11 02 52](https://user-images.githubusercontent.com/160543/108828155-cab89180-75c6-11eb-9bfc-86c7f29b2ca1.png)

**Comment by robertsLando** [comment]
@SeraphimSerapis Logs are intended to be used only for debug purposes. If you want to keep them on set loglevel to error, otherwise you should setup some logrotate rule

**Comment by SeraphimSerapis** [comment]
Sounds great. Thank you!
