### ISSUE TITLE
[bug] failednodes wont remove from control panel, same as closed bug #318

### ISSUE THREAD

**Issue by deccos** [zwave-js/zwavejs2mqtt#713]
Before submitting a bug please read: <https://zwave-js.github.io/zwavejs2mqtt/#/troubleshooting/bug_report>

### Version
1.3.0

Build/Run method

- [ X] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build )

zwavejs2mqtt version: 1.3.0
zwavejs version: 6.4.0

### Describe the bug

I have a number of nodes that are totally dead.  Tehy show up in the control panel when I enable "show hidden nodes" option.  I cannot remove them.  The "Is Failed Node" commands works succesfully (UI reports success), the Remove Failed Node options fails with "Error while calling api removeFailedNode: Node 2 was not found! "

### To Reproduce

1. Show hidden nodes
2. Perform IS Failed Node option
3. Attempt Remove Failed Node option
4.

### Expected behavior

I would expect a success to eb returned after #3 above
### Additional context
This appears to be the same as #318 

In a (possibly misguided) attempt to get "clean" logs, I deleted the two log files in the control panel.  Performed a docker pull (and got latest version in proces) and the container started again.

In timestamp 21:22:54.020, the ISFailedNode command can be seen.  There is no Remove Failed Node after that that I can see (the REmove was requested in the UI withing seconds of the IsFailedNode)

The good nodes are not all showing complete as the battery ones havent worken up yet since container restart.  But I had this issue before I did the restart of the container as well. (I have another much larger set of logs available as well - pasted in as well)
[zwavejs2mqtt-store - Logs from before 1.3.0 update.zip](https://github.com/zwave-js/zwavejs2mqtt/files/6031918/zwavejs2mqtt-store.-.Logs.from.before.1.3.0.update.zip)
[zwavejs2mqtt-store Logs from after 1.3.0 update.zip](https://github.com/zwave-js/zwavejs2mqtt/files/6031919/zwavejs2mqtt-store.Logs.from.after.1.3.0.update.zip)

**Comment by deccos** [comment]
[zwavejs2mqtt-store- SILLY log mode.zip](https://github.com/zwave-js/zwavejs2mqtt/files/6031969/zwavejs2mqtt-store-.SILLY.log.mode.zip)

Just got new log dump in Silly mode.  Have done another IsFailedNode and attempted Remove Failed Node at end of log

**Comment by robertsLando** [comment]
Could you show me a screenshot of what you see? BTW you shouldn't enable that flag 'show hidden nodes' in most cases it just cause confusion, I will remove it in next major

**Comment by deccos** [comment]
![zw-controlpanel](https://user-images.githubusercontent.com/35493983/108980355-7a533980-7683-11eb-83ba-2eb9387d0154.PNG)
Enclosed screengrab.  I an see the node is "REmoved" accoring to the column, but I was trying to get it to fully remove entirley.  I may be trying to do somethign that doesnt make sense.  my OCD just kicking in wanting things to be "clean".

**Comment by robertsLando** [comment]
Shold be fixed in #710

**Comment by deccos** [comment]
thanks

**Comment by cbho** [comment]
Isn't that inherent z-wave behaviour?
As far as I remember, it works (on a controller-level) like this:
When you remove a node, the ID is not "reused" initially - when adding a new node, it will get the highest "never-used" available node-ID - until you reach the limit of 254 nodes - then adding a new node will result in using the "once-used" node-IDs from the beginning

**Comment by robertsLando** [comment]
This is not really a bug, it's kind of an UI issue due to the fact on UI side and backend I was using an array for nodes where the index was the nodeId. As you said when a user removes/add a new node it takes the highest id (or he could use the replceFailed to give the node a specific id of a failed node), the node you see as removed are dummy nodes I add in the positions I don't have anything.
