### ISSUE TITLE
[feat]replace failed node should use the new include UI.

### ISSUE THREAD

**Issue by scyto** [zwave-js/zwavejs2mqtt#714]
The replace failed node UI doesn't use the new inclusion UI but the old one.
This has the following problems:

- confusing start / cancel option to the question 'do you want to start secure inclusion` - needs to be option to do secure, insecure or cancel.
- clicking cancel to do non-secure results in the dialog disappearing; this means you don't know if system is ready to start inclusion or if timer for inclusion timeout started - i had to watch z-wave logs to make sure i knew when i could press action button on the device.

**Comment by robertsLando** [comment]
I add this to my todos :)

**Comment by scyto** [comment]
sorry, i can't helping being a PM (i am terrible at everything else)

**Comment by robertsLando** [comment]
No worries :) @jarrettv if you can check this before me feel free to submit a PR :)

**Comment by robertsLando** [comment]
It has been fixed when including new S2 inclusions mode
