### ISSUE TITLE
[bug] Issues with Trane XL624 climate entity in Home Assistant being unavailable but other entities work

### ISSUE THREAD

**Issue by miguelarios** [zwave-js/zwavejs2mqtt#715]
Before submitting a bug please read: <https://zwave-js.github.io/zwavejs2mqtt/#/troubleshooting/bug_report>

### Version
1.3.0

Build/Run method

- [x] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build )

zwavejs2mqtt version: 1.0.0
zwavejs version: 6.4.0

### Describe the bug

In home assistant I am seeing the climate entity appear is unavailable, while the other entities appear working and updating. I am able to still use the zwavejs webUI to update the mode but I can't update it inside home assistant.

### To Reproduce

1. Add zwavejs integration in home assistant using websocket
2. wait for climate node to be discovered
3. go to climate node
4. notice that climate shows unavailable.

### Expected behavior

Be able to control the climate mode and fan from inside home assistant

### Additional context

If it helps I am using a Trane XL624 Zwave thermostat

**Comment by miguelarios** [comment]
It use to work. I just tried to regress to a previous docker image, but I can't get it to work now.

**Comment by robertsLando** [comment]
@miguelarios Please open this bug on hass core repo, I don't handle the zwavejs integration
