### ISSUE TITLE
[bug] 1.4.0 breaks Home Assistant integration through WS

### ISSUE THREAD

**Issue by aneisch** [zwave-js/zwavejs2mqtt#735]
Before submitting a bug please read: <https://zwave-js.github.io/zwavejs2mqtt/#/troubleshooting/bug_report>

### Version

Build/Run method

- [x] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build )

zwavejs2mqtt version: 1.4.0
zwavejs version: 6.5.0

### Describe the bug

The bump to zwave-js/server 1.0.0 https://github.com/zwave-js/zwavejs2mqtt/commit/a89643eb72b30d0974154b6eb382db21a025c33c seems to have broken the integration with the latest stable version of Home Assistant via websocket. Devices show up as orphaned and entities unavailable. 

When reverting to 1.3.0 (zwave-js/server 1.0.0-beta.8), things work as expected.

**Comment by aneisch** [comment]
This issue might be more appropriate in the downstream https://github.com/zwave-js/zwave-js-server repo, but I've submitted here as this I believe it is applicable.

**Comment by ggruner** [comment]
My Z-Wave setup is also broken after updating from zwavejs2mqtt 1.3.0 -> 1.4.0 in latest Home Assistant version. All my entities are in an "unavailable" state.

**Comment by prilly-dev** [comment]
I can confirm

**Comment by towerhand** [comment]
You gotta wait for the HA beta release in a few hours since the WS 1.0.0 is already in zjs2m.

**Comment by dgooglr** [comment]
My zwave is also down now, any workaround?

**Comment by aneisch** [comment]
> My zwave is also down now, any workaround?

I'm using `image: zwavejs/zwavejs2mqtt:sha-fec72b7` in my compose file to revert to 1.3.0

**Comment by towerhand** [comment]
The HA beta images are already building, should be available pretty soon.

**Comment by dgooglr** [comment]
> > My zwave is also down now, any workaround?
> 
> I'm using `image: zwavejs/zwavejs2mqtt:sha-fec72b7` in my compose file to revert to 1.3.0

Thanks, worked for me

**Comment by dgooglr** [comment]
> The HA beta images are already building, should be available pretty soon.

Not going to beta with my main setup :) Thanks!

**Comment by brianhanifin** [comment]
@aneisch, @towerhand Thank you for explaining why I was having problems. And thank you for the downgrade id!

_I've been banging my head against the wall all day today. I was having problems so I poked around and ended up deleting some of my devices so I decided to start from scratch._

**Comment by marcelveldt** [comment]
Please do NOT update to zwavejs2mqtt 1.4 if you're running the stable version of HA due to a version incompatability.
Next version of HA (beta released today) 2021.3 will be compatible again.
Thanks!

**Comment by eddiezane** [comment]
@robertsLando any chance you can add that disclaimer to the 1.4.0 release notes to help out some future folks?

**Comment by BluGeni** [comment]
> Please do NOT update to zwavejs2mqtt 1.4 if you're running the stable version of HA due to a version incompatability.
> Next version of HA (beta released today) 2021.3 will be compatible again.
> Thanks!

I am now running core-2021.3.0b0 on docker with zwavejs2mqtt at 1.4 with the same issue.

**Comment by bs42** [comment]
Yeah, just found this out the hard way.  Also tried the beta docker image which didn't communicate, additionally after reverting back both HA and zwavejs2mqtt I have a ton of excess orphan entities attached to my devices now.  Thankfully the original ones are still there.

![image](https://user-images.githubusercontent.com/611706/109108329-8d502300-76f0-11eb-90da-b9221a823ea0.png)

**Comment by karl-gustav** [comment]
I just updated HA docker to run `:beta` and I also ended up with the orphaned etries; but it looks like the orphaned entres are the originals, and I have gotten new entries that works... I.e. I need to rename all my entries again.

**Comment by robertsLando** [comment]
Will add this disclaimer: 

> Please do NOT update to zwavejs2mqtt 1.4 if you're running the stable version of HA due to a version incompatability.
> Next version of HA (beta released today) 2021.3 will be compatible again.

**Comment by labaland** [comment]
Lastest HA Beta 2021.2.3, and latest zwavejs

**Comment by labaland** [comment]
> > Next version of HA (beta released today) 2021.3 will be compatible again.

Okay, so a second beta will be today?

**Comment by towerhand** [comment]
Looks like a PR was merged to fix the broken migration https://github.com/home-assistant/core/pull/47031

**Comment by labaland** [comment]
New Beta update now, now i also get vocer Up/stop/Down buttons! Awesome!
