### ISSUE TITLE
Loosing ALL settings and Node info after each docker versions update

### ISSUE THREAD

**Issue by joshewing02** [zwave-js/zwavejs2mqtt#737]
I have 27 nodes that I have had to rebuild multiple time now.  Not sure what I am doing wrong when upgrading but is there a way to backup and or save all the Node info?  I have to run around the house and reintegrate every battery device to get them to repopulate.  

Here are my docker install settings
![image](https://user-images.githubusercontent.com/30333859/109101830-5e2fb680-76dc-11eb-9d4e-c7e354ade601.png)

![image](https://user-images.githubusercontent.com/30333859/109101732-23c61980-76dc-11eb-8108-414630f9913c.png)

**Comment by prilly-dev** [comment]
Set up a persistant store for your container,

**Comment by robertsLando** [comment]
As @prilly-dev said you can both use volumes or map a local folder to a folder in docker to store persistent files. You can find everything needed here: https://github.com/zwave-js/zwavejs2mqtt/blob/master/docker/README.md#install

**Comment by joshewing02** [comment]
Thank you both.  I was able to map the Appdata to a share I can access through the Unraid shares.  Thanks for the point in the correct direction.
