### ISSUE TITLE
[bug]

### ISSUE THREAD

**Issue by cts1085** [zwave-js/zwavejs2mqtt#749]
Before submitting a bug please read: <https://zwave-js.github.io/zwavejs2mqtt/#/troubleshooting/bug_report>

### Version 1.4.0

Build/Run method

- [ X] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build )

zwavejs2mqtt version: 1.4.0
zwavejs version: 6.5.0
Zwavejs-server Version: 1.0.0

### Describe the bug

After re-interview I see "scenes" for my inovelli Red Series Dimmer under Node->Home Assistant but when i check the WS integration in HA the entity is only listing the light and two sensors, no scenes are exposed via WS

### To Reproduce

Start docker for ZWaveJS2MQTT and inspect "Integration"->ZWave-JS devices

1. Go to 'HA Integrations'
2. Click on 'ZWave-JS Devices.'
3. Scroll down to 'Red Series Dimmer'
4. See no scenes are listed - just the electric totals/metrics

### Expected behavior

See the scenes similar to OZW->MQTT

### Additional context

Zwave-JS integration:
![image](https://user-images.githubusercontent.com/30473948/109204529-76064980-7773-11eb-97b5-b037e3141d43.png)

OZW->MQTT Integration
![image](https://user-images.githubusercontent.com/30473948/109204604-8e766400-7773-11eb-9e1a-00a18956a0a7.png)

ZwaveJS2MQTT - Node->Home Assistant
![image](https://user-images.githubusercontent.com/30473948/109204684-a6e67e80-7773-11eb-9e4d-d9d48915d944.png)

"silly" logs
[zwavejs2mqtt-store.zip](https://github.com/zwave-js/zwavejs2mqtt/files/6045237/zwavejs2mqtt-store.zip)

**Comment by towerhand** [comment]
Did you press the green "rediscover node"? I have had to do that in the past.

**Comment by cts1085** [comment]
When I did the re-interview then the scene's showed up in ZwaveJS2MQTT, but they did not show up in HA - I will try what you suggested and see if that helps however.

**Comment by cts1085** [comment]
no change with the "rediscover node"

**Comment by robertsLando** [comment]
I dunno if you are aware of this but mqtt discovery != zwavejs integration, them are two different things and they essentially prtovide two different ways to integrate your zwave devices with hass.

**Comment by cts1085** [comment]
I do understand and I am planning on migrating to use zwavejs integration. I am just wanting to make sure that I am not losing any functionality.  It appears the only item left is the scene events being seen by hass.  Unless there is a different method or implementation to use scenes from these devices into hass via zwavejs?

**Comment by robertsLando** [comment]
> I am just wanting to make sure that I am not losing any functionality.

I cannot answer to this question as I'm not using zwavejs integration and I dunno its support, I can only speak about the mqtt discovery that is maintained by me

**Comment by cts1085** [comment]
ok - so is there a different place I should be posting this issue or question?

**Comment by robertsLando** [comment]
Home assistant core github repo
