### ISSUE TITLE
[bug] climate missing for Eurotronic Spirit since recent update

### ISSUE THREAD

**Issue by NicoLeOca** [zwave-js/zwavejs2mqtt#759]
Before submitting a bug please read: <https://zwave-js.github.io/zwavejs2mqtt/#/troubleshooting/bug_report>

### Version

Build/Run method

- [x] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build )

Installed Z-Wave JS to MQTT addon in Home Assistant

zwavejs2mqtt version: 2.0.0
zwavejs version: ?

### Describe the bug
Equipement: Eurotronic Spirit
The climate entity became unavailable, not with the last update but with the one before.
I suspect the bug appeared with ZwaveJS2Mqtt addon v0.4.4, eg ZwaveJS2Mqtt v1.2.3 
It still exists with ZwaveJS2Mqtt v2.0.0.

**Comment by NicoLeOca** [comment]
node.json
[node_14.txt](https://github.com/zwave-js/zwavejs2mqtt/files/6054007/node_14.txt)

**Comment by ropeguru** [comment]
Not sure if it is related, but climate for my Honeywell TH6320ZW has disappeared also

**Comment by robertsLando** [comment]
@NicoLeOca Are you using zwavejs integration or mqtt discovery? If you are using zwavejs integration please close this issue and open it in hass repo

**Comment by NicoLeOca** [comment]
@robertsLando 
Thanks for your reply
I use zwavejs integration.
So I close this issue
