### ISSUE TITLE
[bug] Options for configuration values not handled properly 

### ISSUE THREAD

**Issue by NYZack** [zwave-js/zwavejs2mqtt#763]
Before submitting a bug please read: <https://zwave-js.github.io/zwavejs2mqtt/#/troubleshooting/bug_report>

### Version

Build/Run method

- [X ] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build )

zwavejs2mqtt version: 1.3.0
zwavejs version: 6.4.0

### Describe the bug

When options are listed for configuration parameters in device configuration files on zwavejs and allowManualEntry is true, the options don't show up in the zwavejs2mqtt configuration interface: one can only enter the value manually, and there is no dropdown.  On the attached node export (see config parameter 5 [32-112-0-5], for instance, and the attached configuration json file), it doesn't look like the options data actually make it over from zwavejs.

Also, if I have options set for a read-only parameter (and allowManualEntry is set to true) - if the actual value returned isn't one of the options, the value doesn't show up.

### Expected behavior

If options are listed in a configuration file and allowManualEntry is set to true, there should be a dropdown with the options, or the user should be able to enter the value manually.  On a read-only parameter, if the returned value matches one of the options, the option should appear; otherwise, the raw value should appear.

![image](https://user-images.githubusercontent.com/8227920/109386681-52094c00-78ca-11eb-8d92-84223b1d1623.png)
[node_32.json.txt](https://github.com/zwave-js/zwavejs2mqtt/files/6054352/node_32.json.txt)
[zse29.json.txt](https://github.com/zwave-js/zwavejs2mqtt/files/6054353/zse29.json.txt)

**Comment by robertsLando** [comment]
@NYZack did you try to re-interview your device?

**Comment by NYZack** [comment]
Yes. This is the issue in #779 so closing this one.
