### ISSUE TITLE
[HASS] Entity Name Template - Index missing in Friendly Name

### ISSUE THREAD

**Issue by etamminga** [zwave-js/zwavejs2mqtt#764]
### Version

zwavejs2mqtt version: 2.0.0
zwavejs version: 6.5.0

### Describe the problem
When discovering a device with multiple similar entities the Friendly name of the entity cannot be configured to include the index of the entity.

We'd like to have the option to specify the Index in the "Entity Name Template" in Settings->Home Assistant of ZwaveJs2Mqtt. 

Example: on a Greenwave Powernode with 6 sockets the Friendly Name of the entity cannot be configured to include numbers 1-6. 

When using %o for friendly name you get  "electric_kwh_value_1" to "electric_kwh_6"
When using %pn for friendly name you get "value" to "value" (without the index 1-6)
When using %l for friendly name you get "Electric Consumed [W]" to "Electric Consumed [W]" (without the index 1-6)

Can we get a %i (for Index) that matches the index of the (in this case) Socket of this PowerNode ?

(I'm trying to upload an image to show my issue, but image upload to github failed. See Slack discussion: https://zwave2mqtt.slack.com/archives/C01DQ24SDKL/p1614370414351100)

**Comment by robertsLando** [comment]
@billiaz

**Comment by billiaz** [comment]
I am thinking! not sure yet what is best to be used.
Maybe exposing the ability to include Entrypoint or property key might help.

**Comment by billiaz** [comment]
@etamminga currently friendly names 1-6 are not always calculated based on endpoint.
can you share the specific device node export? I want to figure out the posibilities...

Would be interesting to include the endpoint as suffix on names. And this way we could "separate" devices or reuse the discovered name (%o in your suggestion).

**Comment by etamminga** [comment]
@billiaz here you go, node 34 export. 

Have the endpoint id as a separate item to put in the template would be sufficient in my opinion. As most devices only have 1 endpoint adding it a s suffix to all names would not be beneficial I guess.

[node_34.zip](https://github.com/zwave-js/zwavejs2mqtt/files/6089411/node_34.zip)

**Comment by billiaz** [comment]
@etamminga will look into this soon!
been a few days with a broken laptop! just installed basic tools
