### ISSUE TITLE
[BUG] Display bug in associations

### ISSUE THREAD

**Issue by radiationnow** [zwave-js/zwavejs2mqtt#766]
Description:
Using the ZwaveJS2MQTT HomeAssistant addon (V0.5.0), the control panel shows lifeline associations to node 2, not to node 1.  The associations themselves appear to be made to node 1, so this seems to be purely a display bug.

Describe the bug
Lifeline group associations show association to node 2, instead of the expected association to the controller (node 1).  Removing the association and adding an association to node 1 again displays as an association to node 2.

I also verified that other associations, at least in group 1, also exhibit this off-by-1 behavior.  (E.G., association to node 5 displays as an association to node 6.)

Expected behavior
Name of associated node displayed should reflect the associated node, rather than the name of nodenumber+1.

**Comment by osenft** [comment]
Please see proposed fix in PR #769.

**Comment by osenft** [comment]
This problem is caused by looking up by index, rather than ID. The off-by 1 was pure coincidence: while the array is indexed from 0 and IDs start at 1, this breaks if an ID is skipped. The lookup was plainly wrong.
