### ISSUE TITLE
[bug] ZW132 MeterCCReport not published to mqtt

### ISSUE THREAD

**Issue by razvanws** [zwave-js/zwavejs2mqtt#778]
Before submitting a bug please read: <https://zwave-js.github.io/zwavejs2mqtt/#/troubleshooting/bug_report>

### Version

Build/Run method

- [x] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build )

zwavejs2mqtt version: 2.0.0
zwavejs version: 6.5.0

### Describe the bug

Aeotec ZW132 dual nano switch meter reports are not published to mqtt. Please see below an example.
```
11:01:22.924 SERIAL « 0x01100004000d0a3202217400001c9c000009                              (18 bytes)
11:01:22.927 CNTRLR   [Node 013] [~] [Meter] value[66049]: 7.338 => 7.324               [Endpoint 0]
11:01:22.929 CNTRLR   [Node 013] [~] [Meter] deltaTime[66049]: 0 => 0                   [Endpoint 0]
11:01:22.929 SERIAL » [ACK]                                                                   (0x06)
11:01:22.930 DRIVER « [Node 013] [REQ] [ApplicationCommand]
                      └─[MeterCCReport]
                          type:       Electric
                          scale:      W
                          rate type:  Consumed
                          value:      7.324
                          time delta: 0 seconds
```

### To Reproduce

1. Add a ZW132 device to your network.
2. Set parameter 13-112-0-101 (Group 1 reports) to value 2 (report watts)
3. Set parameter 13-112-0-111 (Automatic report interval) to value 10 (10 seconds interval reports)
4. Do a tail -f to zwavejs_PID.log and you will see the reports.
5. Use mosquitto_sub to subscribe to the mqtt topic and you won't see any report.

### Expected behavior

The reports should be posted to mqtt the same way they are posted for ZW111 devices.

### Additional context

I attached the zwavejs2mqtt logs as well as zwavejs logs. Please look at the Node 013 as that's a ZW132 device. As far as I see, there are no errors in the logs.

[zwavejs_358.log](https://github.com/zwave-js/zwavejs2mqtt/files/6060449/zwavejs_358.log)
[zwavejs2mqtt.log](https://github.com/zwave-js/zwavejs2mqtt/files/6060451/zwavejs2mqtt.log)

**Comment by robertsLando** [comment]
@razvanws In the logs search for `Node 13: value updated: 50-1-value`. You wiull see that the event is catched, you may have gateway disabled

**Comment by razvanws** [comment]
@robertsLando I don't have the gateway disabled. See attached screenshot. 
Also, I believe that the event you saw catched was from the time that zwavejs2mqtt started. I provided the logs as soon as I restarted zwavejs2mqtt. Whenever I restart zwavejs2mqtt or do a "refresh values" node action, the value gets published. 

<img width="1645" alt="Screenshot 2021-03-01 at 12 32 06" src="https://user-images.githubusercontent.com/8041398/109485635-95aab400-7a8a-11eb-9ebf-5d4d240a13d8.png">

**Comment by robertsLando** [comment]
Please delete actual logs file, set general loglevel to debug and restart the application and send me logs again

**Comment by razvanws** [comment]
Please see attached the new log file. It's a brand new file which shows everything from the start of the app until the Interview stage is complete for all nodes (+ a couple of minutes after just to get enough data) except of the battery powered ones.

Node 13 is reporting the meter value each 10 seconds so I believe we should see a `Node 13: value updated: 50-1-value` message in the log file each 10 seconds. However, I can only see that message one time, right after the app started and the node was interviewed.

[zwavejs2mqtt.log](https://github.com/zwave-js/zwavejs2mqtt/files/6060965/zwavejs2mqtt.log)

**Comment by robertsLando** [comment]
@razvanws please search for `Publishing to zwavejs/dormitor_mic/lustra_si_scafa/50/1/value/` in your logs, the messages are sent, maybe you are checking the wrong topic?

**Comment by razvanws** [comment]
I'm actually subscribing to `zwavejs/#` so that I can see all the messages sent by zwavejs and nothing comes on `zwavejs/dormitor_mic/lustra_si_scafa/50/1/value/` except the first time the app is starting.

Which are the messages that you saw in the logs?

I did the following:
```
root@rasp4:/usr/share/hassio/addons/data/a0d7b954_zwavejs2mqtt/store# cat zwavejs2mqtt.log | grep "Node 13: value updated: 50-1-value"
2021-03-01 12:40:38.375 INFO ZWAVE: Node 13: value updated: 50-1-value-65537 0.169 => 0.169
2021-03-01 12:40:39.670 INFO ZWAVE: Node 13: value updated: 50-1-value-66049 0 => 0
2021-03-01 12:40:40.845 INFO ZWAVE: Node 13: value updated: 50-1-value-66561 231.88 => 230.991
2021-03-01 12:40:42.065 INFO ZWAVE: Node 13: value updated: 50-1-value-66817 0 => 0
```

There are only 4 messages which are sent in a 3 seconds interval. Those messages are the initial messages from the initial interview of the node. Those are not the reports that are automatically sent by the device each 10 seconds. I cannot find the reports that are sent each 10 seconds.

**Comment by razvanws** [comment]
I'm just wondering, could it be related to the fact that the values that are showed in the "Meters" tab of zwavejs2mqtt are also not updated? 
See attached screenshot, it says "Electric consumed [w]: 0W", while as you can see below, the last value showed in zwavejs log (see below) is 16.61.

```
14:01:32.921 SERIAL « 0x01100004000d0a32022174000040e200002b                              (18 bytes)
14:01:32.922 CNTRLR   [Node 013] [~] [Meter] value[66049]: 16.63 => 16.61               [Endpoint 0]
14:01:32.923 CNTRLR   [Node 013] [~] [Meter] deltaTime[66049]: 0 => 0                   [Endpoint 0]
14:01:32.923 SERIAL » [ACK]                                                                   (0x06)
14:01:32.924 DRIVER « [Node 013] [REQ] [ApplicationCommand]
                      └─[MeterCCReport]
                          type:       Electric
                          scale:      W
                          rate type:  Consumed
                          value:      16.61
                          time delta: 0 seconds
```

<img width="1237" alt="Screenshot 2021-03-01 at 14 01 08" src="https://user-images.githubusercontent.com/8041398/109494784-0788fa80-7a97-11eb-9a54-d27848979b27.png">

**Comment by robertsLando** [comment]
@AlCalzone IS there any reason why that event could not be emitted by zwavejs? Maybe some regression in latest releases? Because this issue makes no sense to me

**Comment by AlCalzone** [comment]
Is there a full zwave-js log?

**Comment by robertsLando** [comment]
> How is the automatic reporting configured

Like all other values, the event `value updated` is emitted and I publish the packet to mqtt

**Comment by AlCalzone** [comment]
I meant on the device. Those meters have options to configure what gets reported and when.
Also which associations exist? @razvanws

**Comment by razvanws** [comment]
Those are the associations:
<img width="1610" alt="Screenshot 2021-03-01 at 16 28 03" src="https://user-images.githubusercontent.com/8041398/109510974-45901980-7aab-11eb-8882-46fcffebb7a4.png">

Those are the relevant configured options:
<img width="1224" alt="Screenshot 2021-03-01 at 16 28 27" src="https://user-images.githubusercontent.com/8041398/109511032-55a7f900-7aab-11eb-801b-cf2f5c73d90d.png">


Those are messages received each 10 seconds in zwavejs logs:
```
16:30:05.837 SERIAL « 0x01100004000d0a3202217400003fa0000016                              (18 bytes)
16:30:05.838 CNTRLR   [Node 013] [~] [Meter] value[66049]: 16.316 => 16.288             [Endpoint 0]
16:30:05.839 CNTRLR   [Node 013] [~] [Meter] deltaTime[66049]: 0 => 0                   [Endpoint 0]
16:30:05.839 SERIAL » [ACK]                                                                   (0x06)
16:30:05.840 DRIVER « [Node 013] [REQ] [ApplicationCommand]
                      └─[MeterCCReport]
                          type:       Electric
                          scale:      W
                          rate type:  Consumed
                          value:      16.288
                          time delta: 0 seconds
16:30:15.837 SERIAL « 0x01100004000d0a3202217400003faa00001c                              (18 bytes)
16:30:15.838 CNTRLR   [Node 013] [~] [Meter] value[66049]: 16.288 => 16.298             [Endpoint 0]
16:30:15.839 CNTRLR   [Node 013] [~] [Meter] deltaTime[66049]: 0 => 0                   [Endpoint 0]
16:30:15.839 SERIAL » [ACK]                                                                   (0x06)
16:30:15.840 DRIVER « [Node 013] [REQ] [ApplicationCommand]
                      └─[MeterCCReport]
                          type:       Electric
                          scale:      W
                          rate type:  Consumed
                          value:      16.298
                          time delta: 0 seconds
```

**Comment by razvanws** [comment]
I don't know if it makes any sense but here there is the same report by a ZW111 which is successfully published to mqtt:

```
10:41:05.615 SERIAL « 0x01140004000b0e32022174000000000000000000008f                      (22 bytes)
10:41:05.616 CNTRLR   [Node 011] [~] [Meter] value[66049]: 0 => 0                       [Endpoint 0]
10:41:05.620 CNTRLR   [Node 011] [~] [Meter] deltaTime[66049]: 0 => 0                   [Endpoint 0]
10:41:05.622 SERIAL » [ACK]                                                                   (0x06)
10:41:05.624 DRIVER « [Node 011] [REQ] [ApplicationCommand]
                      └─[MeterCCReport]
                          type:       Electric
                          scale:      W
                          rate type:  Consumed
                          value:      0
                          time delta: 0 seconds
```

Here it is the ZW132 report that it's not published to mqtt:
```
10:41:12.921 SERIAL « 0x01100004000d0a3202217400000000000089                              (18 bytes)
10:41:12.922 CNTRLR   [Node 013] [~] [Meter] value[66049]: 0 => 0                       [Endpoint 0]
10:41:12.923 CNTRLR   [Node 013] [~] [Meter] deltaTime[66049]: 0 => 0                   [Endpoint 0]
10:41:12.923 SERIAL » [ACK]                                                                   (0x06)
10:41:12.924 DRIVER « [Node 013] [REQ] [ApplicationCommand]
                      └─[MeterCCReport]
                          type:       Electric
                          scale:      W
                          rate type:  Consumed
                          value:      0
                          time delta: 0 seconds
```

The only difference between them is the 22 bytes vs 18 bytes, don't know if it makes sense.

**Comment by AlCalzone** [comment]
@razvanws The ZW132 has 2 endpoints, which should both have Meter support. Since it also supports Multi Channel Association CC V3, the reports to the root endpoint are not automatically mapped to endpoint 1 (spec requirement).

However it seems like the device incorrectly uses the root endpoint to report combined meter reports for both channels - which are hidden, because they should not be sent. We need to add a compat flag to preserve them.

**Comment by AlCalzone** [comment]
@razvanws do you have the option to test the config files in https://github.com/zwave-js/node-zwave-js/pull/1966?
Should I make you a test release?

**Comment by razvanws** [comment]
@AlCalzone you can make me a test release if possible. Right now I'm using the hassio addon but I could spin a separate docker instance for testing.

**Comment by AlCalzone** [comment]
The bot should comment with an install command in the PR soon. Alternatively you can build a custom zjs2m container against the PR branch: https://zwave-js.github.io/zwavejs2mqtt/#/troubleshooting/docker_custom_builds

**Comment by razvanws** [comment]
@AlCalzone I just tested it and it looks like it's working properly. 
Please see below, the values are published each 10 seconds. Perfect!
I also attached 2 screenshots so that you can see the mqtt messages themselves. The meters values in the UI also update properly. Everything looks very good!

```
2021-03-02 09:21:15.872 DEBUG MQTT: Publishing to zwavejs/dormitor_mic/lustra_si_scafa/50/0/value/66049: { time: 1614676875872, value: 7.297 } with options { qos: 1, retain: true }
2021-03-02 09:21:15.873 INFO ZWAVE: Node 13: value updated: 50-0-value-66049 7.29 => 7.297
2021-03-02 09:21:15.875 DEBUG MQTT: Publishing to zwavejs/dormitor_mic/lustra_si_scafa/50/0/deltaTime/66049: { time: 1614676875875, value: 0 } with options { qos: 1, retain: true }
2021-03-02 09:21:15.876 INFO ZWAVE: Node 13: value updated: 50-0-deltaTime-66049 0 => 0

2021-03-02 09:21:25.873 DEBUG MQTT: Publishing to zwavejs/dormitor_mic/lustra_si_scafa/50/0/value/66049: { time: 1614676885873, value: 7.311 } with options { qos: 1, retain: true }
2021-03-02 09:21:25.874 INFO ZWAVE: Node 13: value updated: 50-0-value-66049 7.297 => 7.311
2021-03-02 09:21:25.876 DEBUG MQTT: Publishing to zwavejs/dormitor_mic/lustra_si_scafa/50/0/deltaTime/66049: { time: 1614676885876, value: 0 } with options { qos: 1, retain: true }
2021-03-02 09:21:25.877 INFO ZWAVE: Node 13: value updated: 50-0-deltaTime-66049 0 => 0
```

<img width="793" alt="Screenshot 2021-03-02 at 11 23 56" src="https://user-images.githubusercontent.com/8041398/109627123-f64cf600-7b49-11eb-9ce2-5443bef4cc9f.png">

<img width="1248" alt="Screenshot 2021-03-02 at 11 23 32" src="https://user-images.githubusercontent.com/8041398/109627146-fcdb6d80-7b49-11eb-9e8a-cf2cd5f16d28.png">

**Comment by AlCalzone** [comment]
> Indeed as far as I know, those devices never reported the power meter for both channels separately. Only one combined report.

Seems pointless to have two endpoints that support Meter CC then 🤷🏻‍♂️
