### ISSUE TITLE
[feat] Rgb colors management

### ISSUE THREAD

**Issue by robertsLando** [zwave-js/zwavejs2mqtt#78]
zwave-js/node-zwave-js#806

**Comment by LordMike** [comment]
Quick question. If i set the current RGB colors (three values), will there be three messages over ZW?

From the other projects, I expect the actual color value to be one value, meaning one message is more than enough to set it. Sending three is really wasteful.

**Comment by robertsLando** [comment]
@LordMike There is an open PR on zwavejs to fix this, actually yes it is splitted in 3 (or 4 if there is alpha too) values

**Comment by LordMike** [comment]
I'm adjusting some entities to send color commands from HASS to ZW. HASS only sends to one topic - is it not currently possible, at all, to set one value?

I found some code that seemingly splits by commas and does RGB stuff.. but I can't find out how it's invoked, so I'm not sure what to send to.

**Comment by robertsLando** [comment]
@LordMike If you check the linked pr with that there will be the support for a new valueId with colors in the hex format. That code you linked here should handle the commands that are sent from hass to mqtt when changing a color

**Comment by jcam** [comment]
I have an RGBW dimmer that I attempted to set up. It used to just show up as 4 separate "dimmers" with one master dimmer that controlled the rest.
With this RGB support I can now control the three colors from the color dial in Home Assistant, but not white. Not sure what would be needed to make that work.
Also, the off switch doesn't work :)

**Comment by robertsLando** [comment]
@jcam Could you open an issue and send the node export ?
