### ISSUE TITLE
[question] Docker dev tag

### ISSUE THREAD

**Issue by towerhand** [zwave-js/zwavejs2mqtt#785]
Dev tag seems to be behind by a few days. It used to be cut daily so I'm just wondering if there was a change of plans.

Thanks for all your hard work.

Currently:
dev tag - App version 1.4.0, Zwavejs Version 6.5.0 and Zwavejs-server Version 1.0.0
and
latest tag - App version 2.0.1, Zwavejs Version 6.5.1 and Zwavejs-server Version 1.1.0

**Comment by robertsLando** [comment]
@towerhand Dev tag is died in favour of `master` tag, I wrote a post about this in slack channel :)

**Comment by towerhand** [comment]
Ok, thanks. I’m not on slack.

**Comment by robertsLando** [comment]
Yep not everyone is there, hope that next ones will see this issue :)
