### ISSUE TITLE
Node interview fails

### ISSUE THREAD

**Issue by barti04** [zwave-js/zwavejs2mqtt#807]
### 2.1.0 

Build/Run method

Home Assistant addon

zwavejs2mqtt version:  2.1.0 
zwavejs version:  6.6.0

### Describe the bug

First Interview of all nodes except the z-wave stick is not working, also re-interview fails.

**Comment by AlCalzone** [comment]
Please make a zwave-js log, loglevel `debug` or `silly` and attach it here as a file.
