### ISSUE TITLE
[bug] ZwaveJS server crashing/not responding after container restart

### ISSUE THREAD

**Issue by lolautruche** [zwave-js/zwavejs2mqtt#815]
### Version

Build/Run method

- [x] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build )

zwavejs2mqtt version: 2.1.0 (master tag)
zwavejs version: 6.6.0
zwavejs server version: 1.1.0

### Describe the bug

When zw2m container is restarted (stop/start, computer reboot...), it often happens that the zwavejs server (websocket) is not available. As a result, the zwavejs integration in HASS stops working correctly (no response when triggering switches, no value from sensors...).
Please note that triggering switches from zw2m works fine and using the MQTT integration in HASS works fine as well. This is why I'm suspecting the zwavejs server not to be correctly started or to be crashing.

The workaround I found is to disable/re-enable the zwavejs server in the zw2m config panel.

### To Reproduce

1. Completely stop zwavejs2mqtt container
2. Start it again
3. In HASS, using the zwavejs integration, try to activate a light
4. Nothing happens and the switch in HASS should toggle to its original position

### Expected behavior

zwavejs server should be available, responding to HASS requests.

### Additional context

Using HA with a Docker container on the same physical machine. zwavejs integration is configured to reach `ws://localhost:3000`

**Comment by robertsLando** [comment]
I need some logs

**Comment by lolautruche** [comment]
I know, I needed some time to get them :wink: 
Here you go.
[zwavejs2mqtt.log.gz](https://github.com/zwave-js/zwavejs2mqtt/files/6082907/zwavejs2mqtt.log.gz)
[zwavejs_1.log.gz](https://github.com/zwave-js/zwavejs2mqtt/files/6082908/zwavejs_1.log.gz)

**Comment by lolautruche** [comment]
I stopped my containers as described and started them over, and noted the issue

**Comment by robertsLando** [comment]
@lolautruche Are you sure the server is enabled in settings? I cannot see anything that says the server is started in logs

**Comment by lolautruche** [comment]
Yes I'm sure, it's a must in my installation.
I had to disable/enable it to make it work (I ensured to have the logs enabled when I did it)

**Comment by robertsLando** [comment]
When zwavejs server is started a log like this should be shown: 

`INFO ZWAVE-SERVER: ZwaveJS server listening on port`

Now I dunno what could prevent it to start, it's the first user that reports this problem

**Comment by lolautruche** [comment]
That's weird, indeed. But I can confirm from within my settings.json.

```json
{"mqtt":{"name":"zwavejs2mqtt","host":"mosquitto","port":1883,"qos":1,"prefix":"zwave","reconnectPeriod":3000,"retain":true,"clean":true,"auth":false,"username":"","_ca":"","ca":"","_cert":"","cert":"","_key":"","key":""},"gateway":{"type":0,"plugins":[],"authEnabled":false,"payloadType":0,"nodeNames":true,"hassDiscovery":true,"discoveryPrefix":"homeassistant","logEnabled":true,"logLevel":"info","logToFile":false,"values":[]},"zwave":{"port":"/dev/ttyACM0","commandsTimeout":30,"networkKey":"my_network_key","logLevel":"info","logToFile":false,"serverEnabled":true,"serverPort":3000,"logEnabled":true}}
```

**Comment by lolautruche** [comment]
Is there a way to check if it's started from within the container somehow? 
Could you point me in the code where this is handled? I might be able to help here :)

**Comment by robertsLando** [comment]
https://github.com/zwave-js/zwavejs2mqtt/blob/master/lib/ZwaveClient.js#L1754
https://github.com/zwave-js/zwavejs2mqtt/blob/master/lib/ZwaveClient.js#L187

**Comment by lolautruche** [comment]
I might be wrong, but as I understand it, ZWaveJSServer is instantiated using a different log channel (`Zwave-Server`), not the same than zw2m or zwavejs. However I cannot control where the corresponding logs are dumped (log file, stdout...), nor the verbosity.
AFAIU, the zwavejs log doesn't show the server logs.

Furthermore, something I didn't mention in the description, this issue occurs since I started using the `master` tag (for solving #782). That was a big jump (from zw2m 1.0.5 to 2.1.0 / zwavejs 6.0 to 6.6, don't know the server version I had).

**Comment by robertsLando** [comment]
On my instance the server is logging correctly when starts listening and also when I close it, I really dunno why this isn't happening on your side BTW

**Comment by lolautruche** [comment]
Hello @robertsLando 

It seems that my last update fixed the problem. I don't have any issue any more.

**Comment by robertsLando** [comment]
Good! Thanks for reporting :)
