### ISSUE TITLE
Platform mqtt does not generate unique IDs. ID zwavejs2mqtt

### ISSUE THREAD

**Issue by Wojcioo** [zwave-js/zwavejs2mqtt#819]
I've uploaded new version, and this node is correct discovered both in zwavejs2mqtt and in Home Assistant, but in HA in logs there is an error
```
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:489
Integration: Sensor (documentation, issues)
First occurred: 12:49:31 (3 occurrences)
Last logged: 16:22:09

Platform mqtt does not generate unique IDs. ID zwavejs2mqtt_0xe6dcf749_2-128-0-level already exists - ignoring sensor.sypialnia_danfoss_sypialnia_battery_level
```

I can't also find battery level in mqtt integration / devices.

![image](https://user-images.githubusercontent.com/33394332/110002314-88552a00-7d15-11eb-8ed6-728abf841623.png)

I've checked all entities and I can't find more then one NodeID: 2. Where should  I look for the error?

_Originally posted by @Wojcioo in https://github.com/zwave-js/zwavejs2mqtt/issues/607#issuecomment-790781505_

**Comment by Wojcioo** [comment]
But I've got three LC13 for two I can see battery level and for one not?

![image](https://user-images.githubusercontent.com/33394332/110017546-9fe8de80-7d26-11eb-9073-ece973f5cadc.png)

I've attached node with the issue.
[node_2.txt](https://github.com/zwave-js/zwavejs2mqtt/files/6086078/node_2.txt)

**Comment by robertsLando** [comment]
@billiaz ?

**Comment by billiaz** [comment]
I am going to see that.
I faced it before, it was 99% issue of discovery on HASS side. I had to:
1. Delete all topic on Mqtt server,
2. cleanup hass mqtt topics from entities and put it back online!
I then move to retained HASS discovery and stopped having this.

you could probably @Wojcioo do cleanup this node from your hass (by removeing the discovery only for this node and then cleanup failed entities) but first need to check the file you posted.

Will reply in a few hours

**Comment by billiaz** [comment]
@Wojcioo checked the file, i find no duplicate on this discovery! I seriously believe it is stuck on hass side

can you also aupload another LC-13 node? like the one with 53% battery.
I want to compare payloads

**Comment by Wojcioo** [comment]
> can you also aupload another LC-13 node? like the one with 53% battery

@billiaz 
[node_3.txt](https://github.com/zwave-js/zwavejs2mqtt/files/6089131/node_3.txt)

**Comment by billiaz** [comment]
@Wojcioo looking this file too, it clearly is a hass mixup with cached discoveries

node 2 unique_ids:
```
        "unique_id": "zwavejs2mqtt_0xe6dcf749_Node2_climate"
        "unique_id": "zwavejs2mqtt_0xe6dcf749_2-128-0-level"
        "unique_id": "zwavejs2mqtt_0xe6dcf749_2-128-0-isLow"
```

node 3 unique_ids:
```
        "unique_id": "zwavejs2mqtt_0xe6dcf749_Node3_thermostat"
        "unique_id": "zwavejs2mqtt_0xe6dcf749_3-128-0-level"
        "unique_id": "zwavejs2mqtt_0xe6dcf749_3-128-0-isLow"
```

**Comment by Wojcioo** [comment]
so I've to remove the discovery for this node in Zwavejs2mqtt, then cleanup failed entities in HASS, and restart discovery in Zwavejs2mqtt?

**Comment by billiaz** [comment]
I do it differently.
I delete the topics from mqtt `homeassistant/*`
only for node 2!
then i clean the mqtt entities once they become with a RED symbol (meaning unavailable)

and send `online` to `homeassistant/status`

**Comment by Wojcioo** [comment]
> I delete the topics from mqtt `homeassistant/*`
> only for node 2!

sorry for stupid questions - I should remove in Zwavejs2mqtt for this node from json  lines with "state_topic"  and  "discoveryTopic" for both sensors that are not correct discovered in HA.
Than I should wait until they will be unavailable in HA, to remove this entities, and again I should restore json with this two lines.

I'm still new in this topics....

**Comment by billiaz** [comment]
@Wojcioo No!
you do not need to touch zj2m!

you need to access HASS configuration - >entities
you need to access the MQTT

clean mqtt, clean hass, if the nodes are red (on side) then run the topic i told you (this will fake the HASS been restarted) you can ofcourse restart HASS

Alternative:
Stop MQTT access for HASS, clean entities failed and reconnect it! but up to you how you want it.


Both are Hacky but to the point!

**Comment by towerhand** [comment]
I have this happen when adding new devices.

For settings in zjs2m I'm using MQTT discovery with the retain discovery on, what happens is that the devices get auto discovered right away after adding the node (example "homeassistant/switch/node 22"), then when you rename the node in zjs2m a new discovery topic gets published (example "homeassistant/switch/kitchen light), if you rename it again then another get published, and so on. 

I usually just clear the old topics with MQTT Explorer and restart HA, but a real solution would be for zjs2m to clear the old topic when sending one if the retain discovery option is on.

**Comment by billiaz** [comment]
@robertsLando maybe worth adding devices with disabled discovery. or have the option to add them with disabled discovery (when included) and users to enable it afterwards?
I have similar issues but I am faster than device can interview! to rename etc.

**Comment by cbho** [comment]
That would definitely be nice... (@billiaz' suggestion, I mean)

To avoid trouble, I'm stopping Home Assistant when adding devices and only restarting after renaming them etc. in zwavejs2mqtt (and cleaning up MQTT (that is, before I just went for using the js server-function)).

**Comment by robertsLando** [comment]
We could a dd an option like `Manual Discovery`, with that no discovery payload will be sent automatically but you will have to discover them manually
