### ISSUE TITLE
[bug]Custom values not being set when configuration parameter has options

### ISSUE THREAD

**Issue by NYZack** [zwave-js/zwavejs2mqtt#829]
Build/Run method
- [X] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build )

zwavejs2mqtt version: 2.1.1
zwave-js version: 6.6.0

### Describe the bug
Reposting an issue with the closed feature request [https://github.com/zwave-js/zwavejs2mqtt/issues/779](url) - not sure if this is still monitored.  When I enter a manual value for a parameter that also has options set (where allowManualEntry is set to true), the value is ignored, and instead the existing parameter (corresponding to an option) is re-written.

### To Reproduce

1. Go to a device configuration option parameter that has allow allowManualEntry set to true and also has options.  
2. Set the value to an option.
3. Now try to set a manual value.
4. The manual value won't be set; instead the existing option will be re-set.

### Expected behavior

The manual value should be set properly.

### Additional context

In this example, the value 1 corresponded to the already-set option. I changed it to 500 (a manual value), and the log showed this:

2021-03-05 15:17:17.543 INFO ZWAVE: Calling api writeValue with args: [
{ nodeId: 36, commandClass: 112, endpoint: 0, property: 4 },
1,
[length]: 2
]

The corresponding parameter description in the configuration file is - 
		"4": {
			"$if": "firmwareVersion >= 2.0",
			"label": "Brightness Threshold",
			"description": "The sensor will report motion only if brightness level is below the set value (10 is the lowest value the sensor reports).",
			"unit": "lux",
			"valueSize": 2,
			"minValue": 0,
			"maxValue": 900,
			"defaultValue": 0,
			"readOnly": false,
			"writeOnly": false,
			"allowManualEntry": true,
			"options": [
				{
					"label": "Set by knob on sensor",
					"value": 0
				},
				{
					"label": "Ignore brightness",
					"value": 1
				}
			]
		},

**Comment by robertsLando** [comment]
> The manual value won't be set; instead the existing option will be re-set.

You have to enter your custom value, press Enter and then press the icon on the right of the input to send it

**Comment by NYZack** [comment]
I understand about pressing the icon to submit the value.  As I mentioned above, when there is an option value already set, if I enter a manual value (and press the "submit" icon), the *existing* value is resubmitted, and the manual value is ignored.  I don't know whether it is relevant that the parameter value starts out with an option value set, because I can't experiment by changing it to a manual value (for reasons just stated).

 I updated to the latest version (2.1.2), and the behavior persists.  

Here's where I start ("Ignore brightness" corresponds to a value of 1):
![image](https://user-images.githubusercontent.com/8227920/110328946-fa659180-7fe9-11eb-9be1-469654bfcfb3.png)

Then I type in 500 and press the arrow icon:
![image](https://user-images.githubusercontent.com/8227920/110329021-136e4280-7fea-11eb-89da-2aedafaaadd6.png)

Now look at the log; the value "1" (not "500") gets rewritten:
![image](https://user-images.githubusercontent.com/8227920/110329132-37ca1f00-7fea-11eb-8e13-cc7387ba2385.png)

Refresh the interface, and there's no sign of 500:
![image](https://user-images.githubusercontent.com/8227920/110329245-56c8b100-7fea-11eb-9349-7ebc87ad52ae.png)

**Comment by robertsLando** [comment]
> Then I type in 500 and press the arrow icon:

You have to type, press enter or outside the input and then press the arrow icon. BTW I fixed this on master now and press enter is no longer needed

**Comment by NYZack** [comment]
Yes! That works.

**Comment by NYZack** [comment]
@robertsLando Sorry, I still think this doesn't work properly.  Here I start at a custom value of 1:

![image](https://user-images.githubusercontent.com/8227920/111905981-d14ef300-8a24-11eb-9d31-a62843dd2baf.png)

I change it to 10:

![image](https://user-images.githubusercontent.com/8227920/111906186-c34da200-8a25-11eb-9502-60df05db1fcd.png)

And the log confirms the change.

Now I change my mind and try to change it back to 1, and this is impossible.  In fact, no matter what I change it to, the interface selects 0:

(Select option 1:)
![image](https://user-images.githubusercontent.com/8227920/111906219-e2e4ca80-8a25-11eb-9258-247356e74c33.png)

(Press arrow button:)
![image](https://user-images.githubusercontent.com/8227920/111906228-f001b980-8a25-11eb-83da-e5205e00d32f.png)

Log:
![image](https://user-images.githubusercontent.com/8227920/111905815-eecf8d00-8a23-11eb-975f-bc693f656903.png)

If I refresh my browser, I can mitigate this to an extent (the currently set value on this battery-powered device shows up, and I can change it again; but I can't revert back to the value that I started with since it is the currently set value).

**Comment by robertsLando** [comment]
Fixed in https://github.com/zwave-js/zwavejs2mqtt/pull/925
