### ISSUE TITLE
[Bug] Inovelli LZW36 Light+Dimmer discovered in Home Assistant as two lights

### ISSUE THREAD

**Issue by XtremeOwnageDotCom** [zwave-js/zwavejs2mqtt#832]
Device is properly populated in ZWave, and contains the proper settings for both light and fan. However- when discovered in Home Assistant, appears as two light switches instead.

It technically works- however, this is not ideal.

Relavent setup guide from Inovelli.
https://support.inovelli.com/portal/en/kb/articles/installation-setup-lzw36-fan-light-red-series-gen-2-home-assistant-hass-io

Device links to this: https://devices.zwave-js.io/?jumpTo=0x031e:0x000e:0x0001:1.34

**Comment by robertsLando** [comment]
@billiaz

**Comment by billiaz** [comment]
@XtremeOwnageDotCom can you kindly upload your node export.

exporting the specific now will show values discovered And the hass payloads

**Comment by XtremeOwnageDotCom** [comment]
[node_dump.txt](https://github.com/zwave-js/zwavejs2mqtt/files/6104369/node_dump.txt)

Attached.

**Comment by XtremeOwnageDotCom** [comment]
I believe the key areas, would be......

Line 1,848

```json
        {
            "id": "16-38-1-targetValue",
            "nodeId": 16,
            "commandClass": 38,
            "commandClassName": "Multilevel Switch",
            "endpoint": 1,
            "property": "targetValue",
            "propertyName": "targetValue",
            "type": "number",
            "readable": true,
            "writeable": true,
            "label": "Target value",
            "stateless": false,
            "min": 0,
            "max": 99,
            "list": false,
            "value": 0,
            "lastUpdate": 1615208380194,
            "newValue": 0
        },
```       

And, line 1,954
```json
  {
            "id": "16-38-2-targetValue",
            "nodeId": 16,
            "commandClass": 38,
            "commandClassName": "Multilevel Switch",
            "endpoint": 2,
            "property": "targetValue",
            "propertyName": "targetValue",
            "type": "number",
            "readable": true,
            "writeable": true,
            "label": "Target value",
            "stateless": false,
            "min": 0,
            "max": 99,
            "list": false,
            "value": 0,
            "lastUpdate": 1615208341281,
            "newValue": 0
        },
```

**Comment by XtremeOwnageDotCom** [comment]
Also- Here is the manufacturer provided config file (for OpenZWave):

https://raw.githubusercontent.com/InovelliUSA/OpenZWave/master/config/inovelli/lzw36.xml

```xml
  <!-- This shows the device names, but removes some other fields (increment/decrement, target level, etc)  -->
  <CommandClass id="38">
    <Instance index="1" label="Fan/Light" />
    <Instance index="2" endpoint="1" label="Light" />
    <Instance index="3" endpoint="2" label="Fan" />
  </CommandClass>
```

It appears to expose three separate entities.

**Comment by kpine** [comment]
You need to specify a device specific override to configure the 2nd endpoint as a fan, such as:

https://github.com/zwave-js/zwavejs2mqtt/blob/9669cce977e1412023c7bc9b53c9981ded1f225f/hass/devices.js#L338-L340

The endpoint would need to be specified in this case to avoid converting the light to fan, so it requires some new logic to handle the endpoint.

ZWave Plus V2 doesn't have a fan device type, so it must be detected based on the product. This is how HA is handling it via the zwave_js integration.

**Comment by XtremeOwnageDotCom** [comment]
FYI- this issue has been resolved through an unidentified change, somewhere...

As of now, the device appears in home assistant with entities for both the light, and fan.
