### ISSUE TITLE
[feat] store directory env var

### ISSUE THREAD

**Issue by jmgiaever** [zwave-js/zwavejs2mqtt#85]
How to change the path where the store-data is stored?

**Comment by robertsLando** [comment]
Why would you need this?

**Comment by jmgiaever** [comment]
I want to make a snap package of it, but all the system-files lives in a read-only mount and I will need to specify where the store directory, that needs to be in a writable mount, is located. It's common to be able to set "config directories" through a flag or something?At the moment it will try to write to this directory in the r/o space, and fail. On Dec 18, 2020 7:32 AM, Daniel Lando <notifications@github.com> wrote:
Why would you need this?

**Comment by robertsLando** [comment]
@jmgiaever You could create a symlink ?

**Comment by jmgiaever** [comment]
No, the path to the writable directory is changed for every revision of the snap, and the symlink will break. The symlink must also be created after installation to determine the writable location, and then the filesystem is readable and not possible to add a symlink to. On Dec 18, 2020 10:50 AM, Daniel Lando <notifications@github.com> wrote:
@jmgiaever You could create a symlink ?

**Comment by robertsLando** [comment]
@jmgiaever I could make it configurable using env vars. Would it be ok for you?

**Comment by robertsLando** [comment]
It comes from: https://github.com/zwave-js/zwavejs2mqtt/blob/master/config/app.js#L4

**Comment by jmgiaever** [comment]
> @jmgiaever I could make it configurable using env vars. Would it be ok for you?

That would be perfectly fine :D Highly appreciated! :)

**Comment by robertsLando** [comment]
@jmgiaever Sorry for the delay in this, there is an open PR ready :)

**Comment by jmgiaever** [comment]
Thank you! :+1: Appriciated!

**Comment by jmgiaever** [comment]
@robertsLando  PS! The snap package is now live: https://community.home-assistant.io/t/zwavejs2mqtt-snap-package/278994 / https://snapcraft.io/zwavejs2mqtt

**Comment by robertsLando** [comment]
Thanks @jmgiaever ! If you would like to add it to docs feel free to open a PR :)

**Comment by jmgiaever** [comment]
Thanks, I will. Just want to run it for some days, and fix the env.vars in the configuration script. 

I also read that zwavejs is pulling device configuration, so I need to find out a solution on how I can make that directory readable in this confined environment. Do you happen to know if this is the only file zwave-js is writing to? Maybe @AlCalzone knows?

**Comment by AlCalzone** [comment]
The configs come from node_modules/@zwave-js/confif/config. That directory and it's sub dirs must be writable.

**Comment by jmgiaever** [comment]
Noted and fixed! Thanks :)
