### ISSUE TITLE
Node management from HA

### ISSUE THREAD

**Issue by ldymek** [zwave-js/zwavejs2mqtt#855]
Hello, 

Is it possible to create scripts from Home Assistant to update node settings values from device control panel? I have fibaro wallie dimmers switches and outlets with configurable color led circles on devices. I would like to set color on device based on air quality sensor which is not zwave device.

Thanks

**Comment by ldymek** [comment]
To be more clear, I want to pass device Configuration to HASS excactly this:

![image](https://user-images.githubusercontent.com/56914130/110509801-cd58d200-8102-11eb-92fe-37715649fd2d.png)

- [2-112-0-11] LED frame – colour when ON
- [2-112-0-12] LED frame – colour when OFF

This can be done from manual entity creation as you pointed above? Can you share one example of above?

**Comment by robertsLando** [comment]
> This can be done from manual entity creation as you pointed above? Can you share one example of above?

Yes, the examples are in the docs I linked
