### ISSUE TITLE
Sunricher RGBW controller super slow color switch

### ISSUE THREAD

**Issue by PhAzE-Variance** [zwave-js/zwavejs2mqtt#856]
### Version

**Checklist:**

- [X] I am **not** using HomeAssistant. **Or:** a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is **not** described there.
- [X] I have read the changelog problem was **not** mentioned there.
- [X] I am using Home Assistant but the issue exhibits from the ZwaveJS2Mqtt UI

Build/Run method

- [X] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build )

zwavejs2mqtt version:  2.1.0
zwave-js version: 6.6.0

### Describe the bug

When changing colors on the Sunricher SR-ZV9101FA-RGBW controller, sometimes colors will change quickly, other times the transition speed takes well over 60 seconds as each color is slowly transitioned one after the other.  

### To Reproduce

1. Go to zwavejs2mqtt UI
2. Expand the device color switch option
3. Select a color in the [10-51-0-hexColor] RGB Color field
4. Click the arrow to execute
5. Color transition may be quick or may take over 60 seconds with each color channel updating slowly one after another

### Expected behavior

As with the old integration in home assistant, or with integration with smartThings, this color transition should be near instant to switch between colors.

### Additional context

It appears there are extra configuration options showing in the zwave2jsmqtt UI that are not listed on the devices manual.  These extra values (such as transition duration) do not appear to work or have any effect. Node 10 is the device in question.

Device Manual: 
https://www.sunricher.com/media/resources/manual/SR-ZV9101FA-RGBW%20Instruction%20V1.pdf

Node Export:
[node_10.json.txt](https://github.com/zwave-js/zwavejs2mqtt/files/6112971/node_10.json.txt)

Log Capture:
[zwavejs_1.log](https://github.com/zwave-js/zwavejs2mqtt/files/6113017/zwavejs_1.log)

**Comment by robertsLando** [comment]
@AlCalzone thoughts about the delay?

**Comment by AlCalzone** [comment]
I think there are two things at play here.
1. Short term solution: use the configuration parameters to change the default dimming duration that gets used when zwave-js specifies no dimming duration
![grafik](https://user-images.githubusercontent.com/17641229/110591477-69252500-8179-11eb-8654-c9a7d30b6584.png)
2. Wait for https://github.com/zwave-js/node-zwave-js/issues/1321 to get implemented to specify a dimming duration per command

**Comment by PhAzE-Variance** [comment]
So, the dimming duration listed there is only for "stage mode" which is the mode where the lights are continuously transitioning like a light display.  It doesn't affect the regular color switch speed.

**Comment by AlCalzone** [comment]
> will work once or twice instantly then it starts to incorrectly slow down.

tbh that sounds like a device bug. From your log, the only thing I can imagine that could cause this is that 2-3 times you just update the color and after that the brightness also gets changed. Maybe the device does not like doing two different transitions at once?
