### ISSUE TITLE
Cant find my removed nodes anymore

### ISSUE THREAD

**Issue by Keldandorin** [zwave-js/zwavejs2mqtt#865]
After one of the latest updates I can no longer see my removed nodes. Is that intended or bug?
What I like to do is to tap replace node and get the nod back in normal view. For some reason that I dont know the node got diasble/removed
thx
/Håkan

**Comment by robertsLando** [comment]
@Keldandorin the approach has changed, removed nodes doesn't really exists was just dummy nodes I added on the missing ids. Just ignore this :) If you need to replace a node just call the replace from the controller action dropdown and it will ask you to type the id of the node you want to replace

**Comment by Keldandorin** [comment]
@robertsLando 
Hi! problem is that my node for some reason was removed and is no longer available to pic in dropdown. If I take My aeon Stick and look at it from Aeon IMA tools its there "but in removed state". Any chance to get that node back with same ID so I don't have to redo all my automations in HASS?

**Comment by robertsLando** [comment]
Like I said, just send the "Replace Failed Node" action from the controller actuons dropdown (it's on the top of the nodes table), it will ask you the node id you want to replace and if you want to include the new device securely

**Comment by Keldandorin** [comment]
Like I said, That dos not make me choose the same Id the device hade before so all my HA automations need to be reconfigured. To bad I would say :(
