### ISSUE TITLE
Using the mqtt broker [question] 

### ISSUE THREAD

**Issue by ulfur8149** [zwave-js/zwavejs2mqtt#872]
Hi,

I migrated with zwave fully to zwavejs2mqtt and have it running via docker and zwave js plugin in Home Assistant on my raspberry pi. 
I have version zwave js server 1.1 and app version 2.1.1
Now I wanted to go a step further and use the mqtt also for other published services. 
I understood that in the settings tab, that I have to leave the button 'Disable MQTT gateway' to off.

However In Home Assistant I cant connect via the MQTT integration to the ip of the docker container and the port 1883
In the docker compose.yml file is the port enabled.
>docker compose.yml
>version: '3.7'
>services:
>  zwavejs2mqtt:
>    container_name: zwavejs2mqtt
>    image: zwavejs/zwavejs2mqtt:latest
>    restart: always
>    tty: true
>    stop_signal: SIGINT
>    environment:
>      - SESSION_SECRET=mysupersecretkey
>    networks:
>      - zwave
>      - mqtt
>    devices:
>      - '/dev/ttyACM0:/dev/ttyACM0'
>    volumes:
>      - ./store:/srv/zwave-js-server/store
>      - ./certs:/etc/letsencrypt/live/home.xxx.xx
>      - ./zwavejs2mqtt:/srv/zwave-js-server/zwavejsmqtt/
>    ports:
>      - '8091:8091' # port for web interface
>      - '3000:3000' # port for zwave-js websocket server
>      - '1883:1883' # mqtt

Am I missing something? Or do I need to enable something else to use the mqtt broker also for other services?

Regards,

Thomas

**Comment by ivdimitro** [comment]
zwavejs2mqtt is a client. You do not have to expose the 1883 port on the zwavejs2mqtt container. 
For other services to use the MQTT broker you should give them the IP you have given the zwavejs2mqtt configuration. 
zwavejs2mqtt does not influence how you use your broker with other MQTT clients.

**Comment by ulfur8149** [comment]
For my understanding. 
The Docker Zwave js 2 mqtt image does not contain an mqtt broker?

**Comment by robertsLando** [comment]
> The Docker Zwave js 2 mqtt image does not contain an mqtt broker?

No it doesn't. You can use your own broker or use the one provied by hass mqtt integration.
