### ISSUE TITLE
[question] Where did the debug menu/button go on the Control Panel?

### ISSUE THREAD

**Issue by Madelaide** [zwave-js/zwavejs2mqtt#874]
There used to be Node Groups and Debug buttons, now the Debug button has disappeared and it was very useful, especially showing the node's neighbours and other low-level details.

Please advise how to access the same information, or how to get the button/control back?

**Comment by robertsLando** [comment]
@ahochsteger It was there ?

**Comment by Madelaide** [comment]
Debug button? Yes, listed the node’s json. Was very useful for me.

**Comment by ahochsteger** [comment]
@robertsLando yes, I just found out as well that it's not there anymore and miss it too - was very helpful to debug node data that is otherwise not visible in the UI.
It was this PR: https://github.com/zwave-js/zwavejs2mqtt/pull/462

**Comment by Madelaide** [comment]
Yes, that is it, "Debug Info" - was useful to check neighbours without switching to the nodes-graph
