### ISSUE TITLE
[bug] The location field doesn't allow to use a space in the name

### ISSUE THREAD

**Issue by bogdanr** [zwave-js/zwavejs2mqtt#877]
Pretty much everywhere in HA I can use location fields with a space. And I have a bunch defined like this. But in the zwavejs2mqtt UI I can't do that so when I migrate it creates a bit of a mess.
![b](https://user-images.githubusercontent.com/1079875/110957706-ca005900-8343-11eb-80f7-93f3dc558a6a.png)
Can we allow a space in the location and the name?

**Comment by robertsLando** [comment]
@bogdanr Could you use underscores? The problem is that locations are then used on topics, even if spaces are allowed in topics I would prefer not have them...

**Comment by bogdanr** [comment]
I actually used underscores, then moved every device in the locations with
space and then deleted the locations with underscores. I belive that since
HA allows using space, for the sake of consistency, we should allow the
same here.

**Comment by dwradcliffe** [comment]
I agree, I had spaces in names and locations before (in ozwd and HA) and this is going to create a mess if we have 2 versions of the same name/location. Please allow spaces for both of these fields.

**Comment by robertsLando** [comment]
> __Never use spaces in a topic__
> A space is the natural enemy of every programmer. When things are not going the way they should, spaces make it much harder to read and debug topics. As with leading forward slashes, just because something is allowed, doesn’t mean it should be used. UTF-8 has many different white space types, such uncommon characters should be avoided.

From: https://www.hivemq.com/blog/mqtt-essentials-part-5-mqtt-topics-best-practices/

I have no problem adding spaces on location, it's just not a good practise when it needs to be used with mqtt.

**Comment by dwradcliffe** [comment]
Perhaps a different compromise would be to allow spaces but then translate to underscores for MQTT topics? That doesn't completely solve this but at least fixes it for users that don't need MQTT.
