### ISSUE TITLE
[question] Migration from openzwave/zwave2mqtt?

### ISSUE THREAD

**Issue by crxporter** [zwave-js/zwavejs2mqtt#9]
Is there a recommended or "easy" migration path from zwave2mqtt to zwavejs2mqtt? I'm very interested in getting more of my system moved to javascript and hopefully leaving behind the bug which is making my setup struggle.

Thanks! I'm excited for this project!

**Comment by robertsLando** [comment]
@crxporter Unfortunally nope, and I don't think there will be one in the near future, it depends if you are interested in hass discovery or not

**Comment by crxporter** [comment]
I do not want or need hass discovery. I'm integrating with node-red.

I guess the more important question is whether a fresh install of this will bring in all of my paired devices from the z-stick database? I've only set up zwave2mqtt once so I'm not especially familiar with what's stored in config files and what's stored on the stick itself.

**Comment by robertsLando** [comment]
> I guess the more important question is whether a fresh install of this will bring in all of my paired devices from the z-stick database? I've only set up zwave2mqtt once so I'm not especially familiar with what's stored in config files and what's stored on the stick itself.


It should without any problems :) Just run the project and fill the settings in settings ui (just the zwave settings are a little bit different but the rest is almost the same)


Let me know!

**Comment by crxporter** [comment]
Alright I've stopped the OZW docker and started the JS program (using npm start). The first start up took a while, as expected, to learn about all of my devices. Things look good though! I haven't tested mqtt yet, I'll get to it as I have time.

My dimmer switches are unknown product, this also happened with OZW... Apparently I have a new and uncommon version of the common honeywell/jasco dimmers

Battery devices are filling in as they get to their time to sync.

Where is the correct place for me to help add my "unknown product"? Would that be on the zwavejs issues page?

**Comment by robertsLando** [comment]
> Where is the correct place for me to help add my "unknown product"? Would that be on the zwavejs issues page?

I think you know now right? :) I saw your pr on zwave-js, thank you!

**Comment by roflmao** [comment]
@robertsLando Is zwave2mqtt superseded by this project now? What is the reasoning around creating a new project?

**Comment by robertsLando** [comment]
It will, but I will keep maintaining z2m until this will be mature enought (and tested) :)

You can find the reasons here: https://github.com/zwave-js/zwavejs2mqtt/pull/20/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R165

(Sorry it's a work in progress so I have pointed you to a change in a pr that hasn't been merged yet)

**Comment by jonathan-reisdorf** [comment]
Thanks @robertsLando for all your hard work you're putting into this project! And what an excellent tech stack choice, I'm really excited. :)
