### ISSUE TITLE
[bug] Failed to initialize the driver sometimes

### ISSUE THREAD

**Issue by CarsonF** [zwave-js/zwavejs2mqtt#901]
### Version

**Checklist:**

- [ ] I am **not** using HomeAssistant. **Or:** a developer has told me to come here.
- [x] I have checked the troubleshooting section and my problem is **not** described there.
- [x] I have read the changelog problem was **not** mentioned there.

Build/Run method

- [x] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build )

zwavejs2mqtt version: 2.3.0
zwave-js version: 6.6.2

### Describe the bug

Failed to initialize the driver due to timeout as soon as the container starts. It just happened again after pulling the latest image.
I went to the settings control panel, changed nothing, and clicked save. Connection restart logic happens and everything works.

Maybe a short delay is needed when starting?

This happens frequently as I restart the container nightly after pulling the image. Quite frequently I'll wake up to my zwave network being down due to this. Restarting the container or giving it a push with re-saving current settings fixes it. 

I would upload logs but it's just the one statement saying timeout waiting for driver.
### To Reproduce

1. Start the container

### Expected behavior

Zwave connects to usb stick successfully.

**Comment by robertsLando** [comment]
> I would upload logs but it's just the one statement saying timeout waiting for driver.

Could you show me that log please?

**Comment by CarsonF** [comment]
Will post it when it happens again. I restarted too quickly this time and didn't grab it before it was replaced.

**Comment by CarsonF** [comment]
I found some logs in journalctl. It hasn't happened in 4 days though.
```
 ______                       _     ___                  _   _
|___  /                      (_)   |__ \                | | | |
   / /_      ____ ___   _____ _ ___   ) |_ __ ___   __ _| |_| |_
  / /\ \ /\ / / _` \ \ / / _ \ / __| / /| '_ ` _ \ / _` | __| __|
 / /__\ V  V / (_| |\ V /  __/ \__ \/ /_| | | | | | (_| | |_| |_
/_____|\_/\_/ \__,_| \_/ \___| |___/____|_| |_| |_|\__, |\__|\__|
                            _/ |                      | |
                           |__/                       |_|

2021-03-08 15:51:18.198 WARN STORE: scenes.json not found
/bin/sh: git: not found
2021-03-08 15:51:19.130 INFO APP: Version: 2.1.1
2021-03-08 15:51:19.131 INFO APP: Application path:/usr/src/app
2021-03-08 15:51:19.209 INFO MQTT: MQTT is disabled
2021-03-08 15:51:19.216 INFO ZWAVE: Connecting to /dev/ttyACM0
15:51:19.217 DRIVER   ███████╗ ██╗    ██╗  █████╗  ██╗   ██╗ ███████╗             ██╗ ███████╗
                      ╚══███╔╝ ██║    ██║ ██╔══██╗ ██║   ██║ ██╔════╝             ██║ ██╔════╝
                        ███╔╝  ██║ █╗ ██║ ███████║ ██║   ██║ █████╗   █████╗      ██║ ███████╗
                       ███╔╝   ██║███╗██║ ██╔══██║ ╚██╗ ██╔╝ ██╔══╝   ╚════╝ ██   ██║ ╚════██║
                      ███████╗ ╚███╔███╔╝ ██║  ██║  ╚████╔╝  ███████╗        ╚█████╔╝ ███████║
                      ╚══════╝  ╚══╝╚══╝  ╚═╝  ╚═╝   ╚═══╝   ╚══════╝         ╚════╝  ╚══════╝
15:51:19.218 DRIVER   version 6.6.0
15:51:19.218 DRIVER
2021-03-08 15:51:19.231 INFO APP: Listening on port 8091 host 0.0.0.0 protocol HTTP
15:51:19.242 DRIVER   unexpected response, discarding...
15:51:19.243 DRIVER   unexpected response, discarding...
15:51:19.245 DRIVER   Cannot handle message because the driver is not ready to handle it yet.
15:51:23.680 CNTRLR   beginning interview...
15:51:23.680 CNTRLR   querying version info...
15:51:23.771 DRIVER   Dropping message because it contains invalid data
15:51:23.780 DRIVER   Dropping message because it contains invalid data
15:51:24.771 CNTRLR   Failed to execute controller command after 1/3 attempts. Scheduling next try in 100 ms.
15:51:25.874 CNTRLR   Failed to execute controller command after 2/3 attempts. Scheduling next try in 1100 ms.
15:51:27.980 DRIVER   Failed to initialize the driver: Timeout while waiting for an ACK from the controller
2021-03-08 15:51:27.981 INFO ZWAVE: Controller status: Driver: Failed to initialize the driver: Timeout while waiting for an ACK from the controller
```

**Comment by robertsLando** [comment]
@CarsonF This happens to me too when I start the application and the usb stick has just been plugged in, it requires some time on startup but then it should start. @AlCalzone Do you have some kind of retry strategy when this happens?

**Comment by AlCalzone** [comment]
You're seeing it in the last few lines of the log. Nothing aside from that.

**Comment by CarsonF** [comment]
I haven't unplugged my stick. Just restarted the process.

Could it be left over messages from the previous run that scramble the init message?

**Comment by robertsLando** [comment]
> Could it be left over messages from the previous run that scramble the init message?

HUmm I don't think so it depends on how you start it

**Comment by AlCalzone** [comment]
> Could it be left over messages from the previous run that scramble the init message?

Not sure - do you have logs with a higher loglevel?

**Comment by CarsonF** [comment]
Bah it hasn't happened in days now. Let's just close. I'll open a new issue or comment here if I find something more concrete.

I really appreciate everything yall are doing for the zwave community @AlCalzone @robertsLando! ❤️
