### ISSUE TITLE
[bug] Garbage characters in name property

### ISSUE THREAD

**Issue by astrandb** [zwave-js/zwavejs2mqtt#908]
### Version

**Checklist:**

- [x] I am **not** using HomeAssistant. **Or:** a developer has told me to come here.
- [x] I have checked the troubleshooting section and my problem is **not** described there.
- [x] I have read the changelog problem was **not** mentioned there.

Build/Run method

- [ ] Docker
- [x] PKG
- [ ] Manually built (git clone - npm install - npm run build )

zwavejs2mqtt version: 2.1.1
zwave-js version: 6.6.0

### Describe the bug

The name property contains garbage characters on a few old devices e.g. zwave.me keyfob. The field is blank in the zw2mqtt control panel but garbage is sent to HomeAssistant. Same happens with wall plugs from Popp. Note that I have not touched the Name and Location fields in control panel.
[zwave_js_dump(2).json.txt](https://github.com/zwave-js/zwavejs2mqtt/files/6154784/zwave_js_dump.2.json.txt)
The issue was initially reported in https://github.com/home-assistant/core/issues/47661

From zwave_js_dump.json:
```
"manufacturerId": 277,
"productId": 2,
"productType": 256,
"firmwareVersion": "1.3",
"name": "\u0000\u0002\u0004\u0006\b\n\f\u000e\u0001\u0003\u0005\u0007\t\u000b\r\u000f",
"location": "",
"deviceConfig": {
    "filename": "/snapshot/zwavejs2mqtt/node_modules/@zwave-js/config/config/devices/0x0115/kfob.json",
    "manufacturerId": 277,
    "manufacturer": "Z-Wave.Me",
    "label": "KFOB",
    "description": "4 button keyfob",
```
From nodes_dump.json:
```
    {
        "id": 45,
        "deviceId": "277-2-256",
        "manufacturer": "Z-Wave.Me",
        "manufacturerId": 277,
        "productType": 256,
        "productId": 2,
        "name": "",
        "loc": "",
        "values": [
            {
                "id": "45-45-0-sceneId-1",
                "nodeId": 45,
                "commandClass": 45,
                "commandClassName": "Scene Controller Configuration",
```
### To Reproduce

1. Add a ZWave.Me KEYFOB to your network.
2. Look at name in zwave_js_dump.json in HA

### Expected behavior
Name property should be empty (or absent) when sent to HomeAssistant as long as a name has not been entered in the control panel.

**Comment by robertsLando** [comment]
Did you try to override them?

**Comment by astrandb** [comment]
I did now.
Entered a new name in zw2m -> New name appears in HA after restart
Removed the new name in zw2m -> "4 button keyfob" appears as name in HA

The workaround is simple - but there must be a bug somewhere. I see same phenomenon with two device types (Popp wall plug) and Z-Wave.me KEYFOB) in two different Zwave-js/Homeassistant installations in different houses.

**Comment by robertsLando** [comment]
By looking at this it's difficult to understand the root cause of the issue. Nodes name and locations are stored in a json file named `nodes.json` in `store` directory. You could take a look at that file when the bug shows up to see if it comes from there, it maybe that your sd card is corrupted (if you are using an rpi) or something else, that's strange

**Comment by astrandb** [comment]
Nothing of interest in nodes.json. There are no sd cards in my setup. I'm running HA core and zwavejs2mqtt in VM:s on new HP ProLiant servers.

I found this in one of the zwave logs:
```
23:06:12.392 CNTRLR « [Node 045] TODO: no handler for application command
23:06:47.182 CNTRLR « [Node 045] TODO: no handler for application command
23:07:00.525 CNTRLR « [Node 045] Received updated node info
23:07:00.530 CNTRLR   [Node 045] The node is now awake.
23:07:00.551 CNTRLR « [Node 045] received wakeup notification
23:07:00.555 CNTRLR   Failed to execute controller command after 1/3 attempts. Scheduling next try i
                      n 100 ms.
23:07:00.705 CNTRLR « [Node 045] is named "^@^B^D^F^H^L^N^A^C^E^G^K^M^O"
23:07:00.705 CNTRLR » [Node 045] retrieving node location...
23:07:00.762 CNTRLR « [Node 045] received location: 
23:07:00.801 CNTRLR   [Node 045] BatteryCC: doing a partial interview...
23:07:00.802 CNTRLR » [Node 045] querying battery status...
23:07:00.855 CNTRLR « [Node 045] received response for battery information:
                      level:                           50
23:07:00.856 CNTRLR   [Node 045] WakeUpCC: doing a partial interview...
```

**Comment by robertsLando** [comment]
@astrandb Lol that's coming from zwavejs it means that for some weird reason is the node reporting that name... @AlCalzone ?

**Comment by astrandb** [comment]
I dont know how the messages are routed but you obviously clean out the garbage for use in zw2mqtt while it is passed along unaltered to HA.

**Comment by AlCalzone** [comment]
```
"name": "\u0000\u0002\u0004\u0006\b\n\f\u000e\u0001\u0003\u0005\u0007\t\u000b\r\u000f"
```
That is just a raw buffer:
```
0,2,4,6,8,10,12,14,1,3,5,7,9,11,13,15
```
Wonder why the device is reporting that - maybe the old integration set some weird value on the device?

**Comment by astrandb** [comment]
@AlCalzone A zero-terminated empty string??

**Comment by AlCalzone** [comment]
I would agree normally, but zwave does not do zero termination and the command tells us how long the string is supposed to be.

**Comment by robertsLando** [comment]
@AlCalzone Is this fixed? I remember you pushed some changes on your side

**Comment by AlCalzone** [comment]
That was a different CC. Imo the correct thing here would be to manually set a no-nonsense name for the device.
