### ISSUE TITLE
[bug] Entities missing in Home Assistant

### ISSUE THREAD

**Issue by oxgl** [zwave-js/zwavejs2mqtt#91]
Build/Run method
- [X] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build ) 

zwavejs2mqtt version: 1.0.0-alpha.1

**Describe the bug**
Some entities are missing in Home Assistant. The problem is that zwavejs2mqtt is creating topics in MQTT with spaces in topic name. As an example, one of sensor configurations is under topic
`homeassistant/sensor/n015_ws_boilerw/notification_Water Alarm/config` (space between Water and Alarm). 
If I replace the space with underscore in the topic name: `homeassistant/sensor/n015_ws_boilerw/notification_Water_Alarm/config`, the entity shows up in home assistant. It would be also nice to have topic name all lower case.
Thank you!

**Comment by billiaz** [comment]
I will test this
