### ISSUE TITLE
[question] USB power switch to Battery

### ISSUE THREAD

**Issue by bushvin** [zwave-js/zwavejs2mqtt#913]
I have the AEON Labs Multisensor 6 device.
It can be connected to USB for power, or have internal batteries.

When pairing them to a controller they advise powering over USB, and then change to battery once paired.

I have noticed when adding them using USB differs from adding them on Battery.
A device paired with USB and then switched to Battery' status is `Dead` upon restart of the controller. It's status is reverted to `Alive` once it reports (after the configured sleep time, or by manually waking the device up).
A device paired using batteries' status is `Asleep`

Is this a known issue?

**Comment by robertsLando** [comment]
I think this is normal but for sure let's see what @AlCalzone says about this
