### ISSUE TITLE
nodeName and nodeLocation missing from update messages [bug]

### ISSUE THREAD

**Issue by chrish987** [zwave-js/zwavejs2mqtt#917]
### Version

**Checklist:**

- [x ] I am **not** using HomeAssistant. **Or:** a developer has told me to come here.
- [ x] I have checked the troubleshooting section and my problem is **not** described there.
- [ x] I have read the changelog problem was **not** mentioned there.

Build/Run method

- [x ] Docker
- [ ] PKG
- [ ] Snap package
- [ ] Manually built (git clone - npm install - npm run build )

zwavejs2mqtt version: 2.3.0
zwave-js version: 6.6.2

### Describe the bug

nodeName and NodeLoction are no longer present in the mqtt messages. I have the gateway configured manually and have entire z-wave value object selected as the payload. Ignore Location is off. I think this disappeared in the 2.3.0 version (but not completely sure).

Current JSON (version 2.3.0):
{
   "id":"15-49-0-Ultraviolet",
   "nodeId":15,
   "commandClass":49,
   "commandClassName":"Multilevel Sensor",
   "endpoint":0,
   "property":"Ultraviolet",
   "propertyName":"Ultraviolet",
   "type":"number",
   "readable":true,
   "writeable":false,
   "label":"Ultraviolet",
   "stateless":false,
   "ccSpecific":{
      "sensorType":27,
      "scale":0
   },
   "list":false,
   "value":0,
   "lastUpdate":1616194887275
}

Previous JSON:
ommandClassName":"Multilevel Sensor",
   "endpoint":0,
   "property":"Illuminance",
   "propertyName":"Illuminance",
   "type":"number",
   "readable":true,
   "writeable":false,
   "label":"Illuminance",
   "stateless":false,
   "ccSpecific":{
      "sensorType":3,
      "scale":1
   },
   "unit":"Lux",
   "list":false,
   "value":76,
   "lastUpdate":1613014309453,
   "nodeName":"MultiSensor6",
   "nodeLocation":"MasterBedroom"
}

**Comment by robertsLando** [comment]
Is `Include Node info` enabled in your settings?

**Comment by chrish987** [comment]
I don't see a setting for that. but under the gateway setting:
Ignore Location: off
Ignore Status Updates: off
Send Zwave Events: off
Publish node details: on

attached settings.json (renamed as settings.txt)

[settings.txt](https://github.com/zwave-js/zwavejs2mqtt/files/6180532/settings.txt)

**Comment by robertsLando** [comment]
@chrish987 I have found an UI issue and submitted a fix for that. For now try to do this: Set gateway type to something different then manually configured, the `Include node info` should show up, set it to true, set the gateway type back to manually confugured and press save
