### ISSUE TITLE
[bug] Thermostat operating state value is not displayed as text

### ISSUE THREAD

**Issue by kpine** [zwave-js/zwavejs2mqtt#92]
**Version**

Build/Run method
- [X] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build ) 

zwavejs2mqtt version: v1.0.0-alpha.1

Using tag `latest` so I'm not sure the exact build.

**Describe the bug**
For a climate device, the control panel is not displaying the "Operating state" text value (Heating, Cooling, etc), instead it is an integer. Compare that with the "Thermostat mode" which does display the text.

**To Reproduce**
1. Go to 'Control Panel'
2. Click on a thermostat node
3. Scroll down to 'User Values' and expand
4. Observe the thermostat operating state

**Expected behavior**
Instead of the numerical value, e.g. `1`, it should display the text, e.g. `Heating`. This would be consistent with mode, and more user friendly.

**Additional context**
I've setup the MQTT gateway with type ValueID topics and payload entire z-wave object. Here is the payload for the operating state value. As you can see, the text values are available, the same way as the thermostat mode is.

topic: `z2m/5/66/1/state`
payload:
```
json
{
  "id": "5-66-1-state",
  "nodeId": 5,
  "commandClass": 66,
  "commandClassName": "Thermostat Operating State",
  "endpoint": 1,
  "property": "state",
  "propertyName": "state",
  "type": "number",
  "readable": true,
  "writeable": false,
  "label": "Operating state",
  "genre": "user",
  "min": 0,
  "max": 255,
  "list": true,
  "states": [
    {
      "text": "Idle",
      "value": 0
    },
    {
      "text": "Heating",
      "value": 1
    },
    {
      "text": "Cooling",
      "value": 2
    },
    {
      "text": "Fan Only",
      "value": 3
    },
    {
      "text": "Pending Heat",
      "value": 4
    },
    {
      "text": "Pending Cool",
      "value": 5
    },
    {
      "text": "Vent/Economizer",
      "value": 6
    },
    {
      "text": "Aux Heating",
      "value": 7
    },
    {
      "text": "2nd Stage Heating",
      "value": 8
    },
    {
      "text": "2nd Stage Cooling",
      "value": 9
    },
    {
      "text": "2nd Stage Aux Heat",
      "value": 10
    },
    {
      "text": "3rd Stage Aux Heat",
      "value": 11
    }
  ],
  "value": 1,
  "lastUpdate": 1608134706720
}
```

**Comment by robertsLando** [comment]
@kpine Thanks for the issue, I'm not able to repro this on my side (I don't have a thermostat). Could you show me a screenshot? Could you also try to use `dev` tag instead?

**Comment by robertsLando** [comment]
Dup of #101 , @kpine follow updates there
