### ISSUE TITLE
[question] Simple way to backup setup / move to other host?

### ISSUE THREAD

**Issue by TheDK** [zwave-js/zwavejs2mqtt#928]
I am currently running zwavejs2mqtt as an add-on on Home Assistant on a RasPi3b. I can use the Snapshot und Restore function of HAss to backup the whole system and recover more or less on any hardware I can run HAss on - also can use this to migrate to different host. 

Now the open issues on HA (store access not working, problem with OTA updates, etc.) for the add-on seem to show that this is not a priority for the HAss team (which is somehow understable given the primary role of the own Z-Wave JS add-on). This is why I contemplate to run it myself using this guide (without MQTT):
https://flemmingss.com/how-to-set-up-zwavejs2mqtt-on-a-raspberry-pi-and-integrate-it-with-home-assistant/

Question: If I want to make sure I have an easy way to recover if I lose the RasPI how would that work? I am new to docker on Linux, so this might be totally standard and easy, just wanted to know what your way would be to do that.

Just FYI: I have a backup of the Aoetec Z-Wave Stick so you can presue that the controller including all node information is still present. I just want to make sure that if I move the controller to a new host I want to make sure that HA on a different host doesn't note it all...

**Comment by robertsLando** [comment]
Just backup everything that you actually have in the `store` folder of the project and restore it on the new instance and you are done

**Comment by TheDK** [comment]
Is it also possible to move between the HA add-on and the stand-alone version as long as it is the same version?

I am new to docker and tried to find out how to cop files out of / into a container and it seems to be rather tricky (either by installing SSH or a storage driver). In another issue you considered providing an upload option - together with the existing batch download as an archive that I believe would fix this challenge for people like me. Is that realistic or rather far down the line if at all?

Thanks for the feedback!

**Comment by robertsLando** [comment]
If you go to store in the ui, select all files in the list, press on the fab icon on bottom right corner you will be able to download all files in a zip archive. Then simply start the application as standalone and map store directory to a local folder where you will unzip all the content of the previously downloaded zip file and you are done

**Comment by TheDK** [comment]
Thanks, understood. Apparently I really have to get into docker... :)

**Comment by robertsLando** [comment]
>  Apparently I really have to get into docker.

Nope, you can do almost all from the UI. Then if you map the volume to a local golder it's as easy as unzip the content to a folder

**Comment by TheDK** [comment]
UI as in ZWaveJS2MQTT UI or a Linux distri with an UI? I noticed that you can edit all files in Store using the UI - so worst case would be copy / paste the content of a couple of files using the UI, reboot, and good to go without even having to mount?

Full disclosure: I google Docker mount local host folder and got results from a one line command to editing config files, persitency, etc. -> This I why I wrote "have to get into docker" as I don't have a real grasp of the difference between a VM and a container, but probably should have.

Sorry for bugging you with basic topics and thanks for the feedback - greatly appreciated! I sent a little tip your way over PayPal just now.

**Comment by robertsLando** [comment]
> o worst case would be copy / paste the content of a couple of files using the UI, reboot, and good to go without even having to mount?

That's another possible solution if you only need settings backup you can download them as json file and import them directly in settings page

> Sorry for bugging you with basic topics and thanks for the feedback - greatly appreciated! I sent a little tip your way over PayPal just now.

Saw it, thanks :pray: :heart:

**Comment by kj4qyf** [comment]
I'd like to be sure to understand the process. I have activated the backup in Zwave JS UI and I can see the daily backups in Store-Backup-NVM.  That folders has 4.0  KB for 7 backups, which sounds very small to me.
My simple question is that I want to make sure that I can restore my Zwave network in case my Zooz 800 dongle goes bad and needs to be replaced. How would I do that ?

**Comment by kj4qyf** [comment]
Many thanks, I think that I have it set up.  My Store backups are about 175 kb (I have some 80 Zwave devices) and the NVM backups don't show the kb size. I should be ok. Thanks again.

**Comment by robertsLando** [comment]
You welcome :)

**Comment by TheKorn2** [comment]
I'm looking at backing up and restoring (preventative maintenance), and stumbled across this thread. 

Is it accurate to say that I only need to regularly copy backup/nvm and backup/store someplace safe to have everything I need to fully restore zwave-js-ui in the case of complete system failure?

Let's say someone absconds with my mini pc. I'd need to:

1. procure identical zwave stick (not 100% necessary but let's assume this for now)
2. install zwave-js-ui
3. in advanced options, do a backup import
4. restore the stick's nvm using NVM management

Is this accurate? Is that really all that's necessary? Is there really a Santa Claus?

**Comment by kj4qyf** [comment]
I think that this may be accurate but I have also resd somewhere that this does not yet work with the Zooz 800 stick. What I have done is to (every few months)  use the Simplicity Studio App to backup my stick. It is bit complicated but it is my safety solution.

**Comment by TheKorn2** [comment]
Well, sadly this process doesn't work. Restoring zwave-js-ui from the backup store works, but restoring the NVM faceplants and says "error while calling resoreNVM: did not find a matching NVM 500 parser implementation! Make sure that the nvm data belongs to a controller with zwave SDK 6.61 or higher (zw0280)"

Of course, the backup file was created with a zstick with zwave SDK 7.19.3, sooo...  yeah.  

Any hints @robertsLando ?

**Comment by TheKorn2** [comment]
Ahhh, dangit...  this is a zwave-js issue, not js-ui.  I searched for nvm and 800 in issues here, but really [I should have been looking here.](https://github.com/zwave-js/node-zwave-js/issues/5257)

**Comment by robertsLando** [comment]
> Ahhh, dangit... this is a zwave-js issue, not js-ui. I searched for nvm and 800 in issues here, but really https://github.com/zwave-js/node-zwave-js/issues/5257

Yeah :)

**Comment by kj4qyf** [comment]
Thanks for the info. Should the Simplicity Studio backup/restore work ?  I have made several backups in Simplicity Studio but have not tried (and don't need) a restore.
________________________________

**Comment by robertsLando** [comment]
> Should the Simplicity Studio backup/restore work

I think it should but I never used it. cc @AlCalzone

**Comment by kj4qyf** [comment]
thanks
________________________________

**Comment by TheKorn2** [comment]
@kj4qyf I just backed up one of my zst39s to another with simplicity studio, then used that second stick with zwave-js-ui to lock/unlock a s2 device. Works.

**Comment by kj4qyf** [comment]
That is great news for you and for me 🙂
________________________________
