### ISSUE TITLE
[HASS] Honeywell T6 Pro Temperature sensor not appearing in HA

### ISSUE THREAD

**Issue by phipolis** [zwave-js/zwavejs2mqtt#939]
### Version

Build/Run method - Docker

zwavejs2mqtt version: 2.4.1
zwavejs version: 6.6.3

[node_2.json.txt](https://github.com/zwave-js/zwavejs2mqtt/files/6198779/node_2.json.txt)
[zwave_js_dump.json.txt](https://github.com/zwave-js/zwavejs2mqtt/files/6198780/zwave_js_dump.json.txt)
![Screenshot from 2021-03-24 12-48-30](https://user-images.githubusercontent.com/6742702/112349664-4cbbd900-8c9f-11eb-8650-33ddb2ba0e57.png)

### Describe the bug

Regarding a Honeywell T6 Pro Z-Wave Programmable Thermostat TH6320ZW

The Zwavejs2mqtt node tab for the device shows a multilevel sensor containing `[2-49-0-Air temperature] Air temperature` and `[2-49-0-Humidity] Humidity`. However the Home Assistant Devices tab (and in home assistant itself) only has sensor_humidity_air. It's strange because the node export contains values for ids 2-49-0-Air temperature and 2-49-0-Humidity. For that matter, the air temperature property shows up in the HA Websocket integration dump, but as with the Home Assistant Devices, it doesn't show up anywhere else in HA.

**Comment by robertsLando** [comment]
Temperature is discovered in climate device, ATM you cannot discover multiuple entities with the same value

**Comment by phipolis** [comment]
> Temperature is discovered in climate device, ATM you cannot discover multiuple entities with the same value

That's strange, because it definitely used to work. Both the temperature and humidity sensors were exposed by older verzions of zwavejs2mqtt. I don't know exactly when because I ignored the entity showing up as "not found" for several weeks.

**Comment by robertsLando** [comment]
@phipolis Never tried to use zwavejs integration?

**Comment by phipolis** [comment]
@robertsLando I have used both the WS and MQTT integrations, at times simultaneously while testing. Are you implying the temperature sensor could be provided by a secondary integration? I'm not sure I understand.

**Comment by robertsLando** [comment]
Usually you can use both to fix the issue of one with the other, like I said I never supported to have more then one valueId discovered with multiple entities

**Comment by phipolis** [comment]
@robertsLando Thanks for explaining. I wish I understood why it ever worked, but there's a lot of packages interacting here. Closing since it's working as intended.
