### ISSUE TITLE
Network not meshing?

### ISSUE THREAD

**Issue by Goldwing1973** [zwave-js/zwavejs2mqtt#956]
Yesterday i started moving (unpairing/pairing)my devices from Z-Wave 1.4 in Home Assistant to Z-WaveJS2MQTT running in a Docker Container on a Synology DS1821+ (zwave stick is a Aeon Labs GEN5 ZW090)
So far so good, but when i look at the graph all the nodes are behind each other and i'm having difficulty to add a node on the other side of my house.
Between the node i'm trying to add there are multiple Electrical Powered nodes (Fibaro wall plugs and Neo Coolcam wall light switches) each within visual range at max 3 meters away.

Zwavejs2mttq 2.4.1
Zwavejs 6.6.3

Am i doing something wrong?

![afbeelding](https://user-images.githubusercontent.com/67235461/112675408-6871db80-8e67-11eb-8d8d-66a823d36b6b.png)

**Comment by robertsLando** [comment]
Please try to update to zwavejs2mqtt 3.0.2 first

**Comment by Goldwing1973** [comment]
> 
> 
> Please try to update to zwavejs2mqtt 3.0.2 first

Updated the Docker container fixed it.
Thanks!

![afbeelding](https://user-images.githubusercontent.com/67235461/112838313-3649bf00-909d-11eb-8464-3eadc972a879.png)
