### ISSUE TITLE
[bug] Zooz ZEN25: toggling 2nd switch shows both as on/off

### ISSUE THREAD

**Issue by Stickshift87** [zwave-js/zwavejs2mqtt#957]
### Version

**Checklist:**

- [X] I am **not** using HomeAssistant. **Or:** a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is **not** described there.
- [X] I have read the changelog problem was **not** mentioned there.

Build/Run method

- [X] Docker
- [ ] PKG
- [ ] Snap package
- [ ] Manually built (git clone - npm install - npm run build )

zwavejs2mqtt version: 3.0.2
zwave-js version: 7.0.0
### Describe the bug

With the ZEN25 when the 2nd switch is changed to on/off it also toggles the 1st switch so that the first switch shows it's on when it physically is not.

Open Control under ZEN25 Binary Switch toggle, target value 37-2 to on.  Both current values for 37-1 and 37-2 change to "true", despite only 37-2 physically turning on.  Changing it back to off will also change both values to false.

### Expected behavior

Only 37-2 changes to true.

### Additional context

Just updated from V2.0.0 where it was working and it also seems to work on V2.1.0 but, all versions after that give me the same result.  The result is the same regardless of where you trigger the change, in the control panel, in Home Assistant, or physically hitting the switch.  Also, I have 4 of the same switch ( Nodes 8, 9, 19, 20 ), and all 4 produce the same results. 

[zwavejs_1.log](https://github.com/zwave-js/zwavejs2mqtt/files/6214396/zwavejs_1.log)

**Comment by blhoward2** [comment]
This should be fixed by https://github.com/zwave-js/node-zwave-js/pull/2160
