### ISSUE TITLE
[bug] Getting unexpected currentValue message for a level change with Qubino Flush Shutter

### ISSUE THREAD

**Issue by Shaft405** [zwave-js/zwavejs2mqtt#958]
### Version

**Checklist:**

- [X] I am **not** using HomeAssistant. **Or:** a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is **not** described there.
- [X] I have read the changelog problem was **not** mentioned there.

Build/Run method

- [X] Docker
- [ ] PKG
- [ ] Snap package
- [ ] Manually built (git clone - npm install - npm run build )

zwavejs2mqtt version: 3.0.2
zwave-js version: 7.0.0

### Describe the bug

I have this issue with Qubino Flush Shutter (ZMNHCD).
When I send a level change command to .../38/1/targetValue/set, I instantly get an unexpected update to .../38/1/currentValue with the final target value before the motor starts. Like if the position was already reached.
Then a few seconds after the motor starts I get a correct intermediary update for .../38/1/currentValue while the shutter is moving.
When it reaches the target position I get the final expected update to .../38/1/currentValue matching the target value.

I do not experience this issue when using another driver like Z-Wave.Me.

### Expected behavior

There should not be a message from .../38/1/currentValue with the target position before the shutter reaches that position.

**Comment by robertsLando** [comment]
@AlCalzone ? Maybe the duration is set to 0?

**Comment by AlCalzone** [comment]
This is expected. When a multilevel switch acknowledges a SET command, we optimistically update the currentValue and verify that the change worked after a few seconds.

Not doing this often results in a weird user experience where it looks like the command did not do anything. Even worse, HomeAssistant's UI toggles back and forth between the set value and the previous one after about a second.

**Comment by Shaft405** [comment]
Thanks for clearing this up!

Well in my case getting currentValue set at targetValue before the level change starts, and then getting an intermediate update with a different level followed eventually by the expected final currentValue is more confusing.

I am not using HomeAssistant but consuming messages with Node-Red. As a workaround I guess I can just have the flow ignore the first message... But for some reason I did not find out at this time, I have a case where I am not getting this unexpected first update.

**Comment by AlCalzone** [comment]
We could add a driver option to disable the optimistic update globally. IMO that comes down to preference.

However that will mean that devices which don't report updates on their own won't change the current value until the verification poll gets answered.

**Comment by Shaft405** [comment]
I think that this would be very valuable in my case. I have no idea how it's done for instance in Z-Wave.Me, but none of my devices (shutter or relay) had issue with not getting timely updates, and they don't seem to be doing optimistic updates.

So being able to disable the optimistic update in zwavejs2mqtt should work just fine for me. I would be very thankful if you could add this option :)

**Comment by Shaft405** [comment]
Just tested the new option and it works like a charm for me now. @AlCalzone thanks a lot 👍
