### ISSUE TITLE
add support new fibaro heat controller (FGT001)

### ISSUE THREAD

**Issue by RezzZ** [zwave-js/zwavejs2mqtt#972]
Just got a new fibaro heat controller and it's a newer model. The generated climate component for HA is now missing the current temperature in the json, giving me a half working climate component in Homeassistant.
Please let me know how I can assist in adding support for this device.

FYI, existing and working device id: 271-4096-4865
new device id: 271-4097-4865

Both have a 58-49-2-Air temperature sensor but its not added to the climate component for some reason.

**Comment by robertsLando** [comment]
You should manually fix the discovered climate template in order to use the correct temperature sensor. 

`58-49-1-Air temperature` --> `58-49-2-Air temperature`

Also remember to update the topics according to the change and store the climate

**Comment by RezzZ** [comment]
Yes I did update the climate json manually now. I get the current temp in HA. Perhaps this can be fixed so it automatically  generates the correct json on the fly like with the previous build of the heatcontroller?

**Comment by ElVit** [comment]
Hi,
I have still this issue with the wrong temperature sensor for the FGT001 (FW 4.7). Is there an other issue for this problem open?
Unfortunately the link "here" from the last post is not working anymore. 
@robertsLando where can I find the customDevices.js|json? How can I solve this problem by myself?

**Comment by robertsLando** [comment]
@ElVit That file should be placed on store directory and has the same format of hass/devices.js

**Comment by ElVit** [comment]
OK thanks for the fast reply. 
I found the device.js (file extension was .ts not .js) file in this repository.
But apparently this issue was already fixed. 
I just reinterviewd the FGT001 and restarted homeassistant.
After that it worked all just fine for me 😃

**Comment by ElVit** [comment]
Here some pictures:
![image](https://github.com/zwave-js/zwave-js-ui/assets/54866762/611421f9-bec6-4487-bf4e-0c4f21ff8d9b)
![image](https://github.com/zwave-js/zwave-js-ui/assets/54866762/4b851310-3f6c-4269-8584-852e01cdf820)

**Comment by robertsLando** [comment]
> Hi, is it possible to add a preset "manufacturer specific" to the home assistant entity?

You could try by manual creating the entity you need: https://zwave-js.github.io/zwave-js-ui/#/homeassistant/homeassistant-mqtt?id=manually-create-entities

**Comment by ElVit** [comment]
Thanks for your answer.
This would mean I have to enable MQTT in the ZWave-JS UI Addon right?
Currently I do not use MQTT but the "WS Server".

Would it not be better to add the the "manufacturer specific" option directly in the Zwave-JS config?
I tried that but somehow this didn't worked for me.

This is how I have done it:
- Copy the file "fgt001.json" from the node-zwave-js repo ([packages/config/config/devices/0x010f/fgt001.json](https://github.com/zwave-js/node-zwave-js/blob/000d8f0e29dfbce041dd6d9dd483979c3442ee10/packages/config/config/devices/0x010f/fgt001.json)) to the ZWave JS UI Store (store/config/fgt001.json)
- Add "getSupportedModes" to the element "compact -> overrideQueries -> Thermostat Mode" (copied from [packages/config/config/devices/0x0148/spirit.json](https://github.com/zwave-js/node-zwave-js/blob/cb42fc52ff9fde109c5f316573f06bf177278b46/packages/config/config/devices/0x0148/spirit.json#L144))
- Restarted the ZWave-JS UI Addon
- Re-Interview my device

I assume that my custom config is not overwriting the existing config. What am I doing wrong?

Here my fgt001.json file:

```
{
	"manufacturer": "Fibargroup",
	"manufacturerId": "0x010f",
	"label": "FGT001",
	"description": "Thermostatic Valve",
	"devices": [
		{
			"productType": "0x1301",
			"productId": "0x1000"
		},
		{
			"productType": "0x1301",
			"productId": "0x1001"
		},
		{
			"productType": "0x1301",
			"productId": "0x4001"
		}
	],
	"firmwareVersion": {
		"min": "0.0",
		"max": "255.255"
	},
	"paramInformation": [
		{
			"#": "1",
			"label": "Override Schedule Duration",
			"description": "Duration of Override Schedule after turning knob",
			"valueSize": 4,
			"unit": "minutes",
			"minValue": 10,
			"maxValue": 10000,
			"defaultValue": 240
		},
		{
			"#": "2[0x01]",
			"$import": "~/templates/master_template.json#base_enable_disable",
			"label": "Open Window Detector (Normal)",
			"valueSize": 4,
			"defaultValue": 1
		},
		{
			"#": "2[0x02]",
			"$import": "~/templates/master_template.json#base_enable_disable",
			"label": "Open Window Detector (Rapid)",
			"valueSize": 4
		},
		{
			"#": "2[0x04]",
			"$import": "~/templates/master_template.json#base_enable_disable",
			"label": "Increase Receiver Sensitivity",
			"description": "Increase receiver sensitivity, but shortens battery life",
			"valueSize": 4
		},
		{
			"#": "2[0x08]",
			"$import": "~/templates/master_template.json#base_enable_disable",
			"label": "Remote LED",
			"description": "Enable LED indications when controlling remotely",
			"valueSize": 4
		},
		{
			"#": "2[0x10]",
			"$import": "~/templates/master_template.json#base_enable_disable",
			"label": "Protect Setting Full ON/OFF",
			"description": "Protect from setting Full ON and Full OFF mode by turning the knob manually",
			"valueSize": 4
		},
		{
			"#": "2[0x20]",
			"$if": "firmwareVersion >= 4.7",
			"$import": "~/templates/master_template.json#base_enable_disable",
			"label": "Vertical Mount",
			"description": "Device mounted in vertical position",
			"valueSize": 4
		},
		{
			"#": "2[0x40]",
			"$if": "firmwareVersion >= 4.7",
			"$import": "~/templates/master_template.json#base_enable_disable",
			"label": "Moderate Regulator Behaviour",
			"valueSize": 4
		},
		{
			"#": "2[0x80]",
			"$if": "firmwareVersion >= 4.7",
			"$import": "~/templates/master_template.json#base_enable_disable",
			"label": "Inverted Knob Operation",
			"valueSize": 4
		},
		{
			"#": "2[0x100]",
			"$if": "firmwareVersion >= 4.7",
			"$import": "~/templates/master_template.json#base_enable_disable",
			"label": "Heating Medium Demand Reports",
			"valueSize": 4
		},
		{
			"#": "2[0x200]",
			"$if": "firmwareVersion >= 4.7",
			"$import": "~/templates/master_template.json#base_enable_disable",
			"label": "Detecting Heating System Failures",
			"valueSize": 4
		},
		{
			"#": "3[0x01]",
			"$import": "~/templates/master_template.json#base_true_false",
			"label": "Temperature Sensor",
			"description": "Optional temperature sensor connected and operational",
			"valueSize": 4,
			"readOnly": true
		},
		{
			"#": "3[0x02]",
			"$import": "~/templates/master_template.json#base_true_false",
			"label": "Open Window Detected",
			"valueSize": 4,
			"readOnly": true
		},
		{
			"#": "3[0x04]",
			"$if": "firmwareVersion >= 4.7",
			"$import": "~/templates/master_template.json#base_true_false",
			"label": "Provide Heat",
			"description": "Provide heat in order to maintain set temperature",
			"valueSize": 4,
			"readOnly": true
		},
		{
			"#": "3[0x08]",
			"$if": "firmwareVersion >= 4.7",
			"$import": "~/templates/master_template.json#base_true_false",
			"label": "Malfunctioning Heating System",
			"description": "Malfunctioning heating system - cannot reach set temperature",
			"valueSize": 4,
			"readOnly": true
		}
	],
	"compat": {
		// The device has two endpoints with different device classes, but both need to exist
		"preserveEndpoints": [1, 2],
		// Not sure if necessary, but this can prevent missing updates on endpoint 1
		"mapRootReportsToEndpoint": 1,
		// Hide CCs from root endpoint that are duplicated on the manually preserved endpoint 1
		"commandClasses": {
			"remove": {
				"Battery": {
					"endpoints": [0]
				}
			}
		},
		"overrideQueries": {
			// The device does not report "Manufacturer specific" as a supported thermostat mode
			"Thermostat Mode": [
				{
					"method": "getSupportedModes",
					"result": [0, 1, 31], // Off / Heat / Manufacturer specific
					"persistValues": {
						"supportedModes": [0, 1, 31]
					},
					"extendMetadata": {
						"thermostatMode": {
							"states": {
								"0": "Off",
								"1": "Heat",
								"31": "Manufacturer specific"
							}
						}
					}
				}
			]
		}
	}
}
```

**Comment by robertsLando** [comment]
Oh sorry @ElVit I misunderstood your question, I tought you were already using MQTT discovery and you was missing that control in Home Assistant so my answer...


Your problem is that you want to add that missing value by using a custom config.

> I assume that my custom config is not overwriting the existing config. What am I doing wrong?

You can see this from logs, could you upload them please?

@AlCalzone I'm not an expert with config files but that file looks good and also the configuration directory is ok

**Comment by kimbo1st** [comment]
Just added the heat controller via zwave JS and I cannot set the temperature. Any idea how to solve?

**Comment by ElVit** [comment]
I have several FGT001 thermostats and can see the sensor "Air temperature". Mine have the Firmware v4.9. 
Maybe there was an update?
Also sometimes the sensors are hidden, so you have to press "+x entities not shown" button.

**Comment by robertsLando** [comment]
cc @AlCalzone

**Comment by AlCalzone** [comment]
What's the problem?

**Comment by robertsLando** [comment]
I tagged you as I didn't saw any response of: https://github.com/zwave-js/zwave-js-ui/issues/972?notification_referrer_id=MDE4Ok5vdGlmaWNhdGlvblRocmVhZDEzMTk0NTY5MTY4OjExNTAyNDk1#issuecomment-2047621858

maybe there has been a configuration update that fixed the issue?

@kimbo1st try to re-interview your device to see if the missing value appears or check for device firmware updates

**Comment by kimbo1st** [comment]
> What's the problem?

I have no option to set the temperature.

![IMG_0854](https://github.com/user-attachments/assets/84ecf085-e0e8-4390-9037-de16a869ef3d)

this is the pop-up I see:
![IMG_0853](https://github.com/user-attachments/assets/3e9c46e2-2938-45b7-a747-52fa923c1266)

Re-interview already done.
Firmware version is 4.9.

**Comment by kimbo1st** [comment]
Last update of  HA and  jwave-js seems to have it solved.

**Comment by kimbo1st** [comment]
Working for a few months fine. What I notice is the temp update time is slow and only get an update when an action is sent. Any idea how to get the currect temp every 30mins? or even faster...

Other thing I would like to see is if there's a calibration error or not... I sometimes notice that the valve didn't close and even the temp was set correctly.. .resulting in being the room too hot.
