### ISSUE TITLE
[HASS] Preset modes  for fans payload.

### ISSUE THREAD

**Issue by towerhand** [zwave-js/zwavejs2mqtt#982]
### Version

Docker

zwavejs2mqtt version: 3.0.2
zwavejs version: 7.0.0
Home Assistant version: 2021.3.4

### Describe the bug

Home assistant changed the way the fan integrations  works, my GE 14287 fan used to show up with the low, medium, high and off options but now there is a slider to turn the fan to 33%, 66%, 100% and 0% instead. Not sure if a "preset_mode" option can be added to the discovery topic so we have the option for low, medium and high again.

The breaking change info for fans explains the change pretty well:
https://www.home-assistant.io/blog/2021/03/03/release-20213/#breaking-changes

More info:
https://www.home-assistant.io/blog/2021/03/03/release-20213/#fan-speeds-100
https://www.home-assistant.io/integrations/fan/

Hopefully this is something that can be addressed from the zjs2m side.

**Comment by robertsLando** [comment]
@towerhand What is the preset mode value that should be added to the discovery payload? BTW fans are currently handeld in custom devices so this could be fixed by adding that property to the payloads

**Comment by towerhand** [comment]
I should have also specified that I’m referring to mqtt discovery, I don’t use the WS server.

Preset mode for this fan switch should be low, medium, high.

I understand the concerns of backwards compatibility at least for a couple more versions, in the meantime, can you please point out what I need to add to the payload?

**Comment by robertsLando** [comment]
@towerhand Not 100% sure about it but it should work by adding `"preset_mode": "???"` in discovery payload [here](https://github.com/zwave-js/zwavejs2mqtt/blob/master/hass/devices.js#L7)

I used `???` as I don't find allowed values in their mqtt discovery docs yet: https://www.home-assistant.io/integrations/fan.mqtt/

**Comment by towerhand** [comment]
Ok thanks for the info, looks like they need to add the payload option to their mqtt integration first. I’ll do some testing after work with the payload in zjs2m and create an issue in their repository if needed.

**Comment by towerhand** [comment]
There is a merged PR for this in the HA side, I’m assuming it will be available in today’s HA beta release.

https://github.com/home-assistant/core/pull/47944

**Comment by blhoward2** [comment]
Just a note that low/medium/high isn't necessarily universal equivalent to any one number across devices. The smartthings handler lets you choose which percentage to send for each. Some fan devices come with preset levels in the firmware and any setting between them is set at the next lowest level, others allow for a true range of settings.

**Comment by robertsLando** [comment]
You could try with something like this, not sure about what to place in `percentage_command_template`, maybe nothing just ignore it:

```js
const FAN_DIMMER = {
  type: 'fan',
  object_id: 'dimmer',
  values: ['38-0-currentValue', '38-0-targetValue'],
  discovery_payload: {
    command_topic: '38-0-targetValue',
	percentage_command_template: '??',
	percentage_value_template: '{{ value_json.value }}'
    percentage_command_topic: '38-0-targetValue',
    percentage_state_topic: '38-0-currentValue',
    state_topic: '38-0-currentValue',
    payload_off: 0,
    payload_on: 255,
    state_value_template:
      '{% if (value_json.value | int) == 0 %} 0 {% else %} 255 {% endif %}'
  }
}
```

**Comment by towerhand** [comment]
I tried this in the home assistant option for the fan, then tapped update and rediscover but it doesn't save it in zjs2m so I must be doing something wrong.
```
"discovery_payload": {
    "command_topic": "zwave2jsmqtt/master_bedroom_fan/38/0/targetValue/set",
    "percentage_command_topic": "zwave2jsmqtt/master_bedroom_fan/38/0/targetValue/set",
    "percentage_state_topic": "zwave2jsmqtt/master_bedroom_fan/38/0/currentValue",
    "state_topic": "zwave2jsmqtt/master_bedroom_fan/38/0/currentValue",
    "preset_modes": [
      "off",
      "low",
      "medium",
      "high"
    ],
    "payload_low_preset_mode": 24,
    "payload_medium_preset_mode": 50,
    "payload_high_preset_mode": 99,
    "payload_off": 0,
    "payload_on": 255,
    "state_value_template": "{% if (value_json.value | int) == 0 %} 0 {% else %} 255 {% endif %}",
    "percentage_value_template": "{% if (value_json.value | int) == 0 %} 0 {% elif (value_json.value | int) <= 32 %} 24 {% elif (value_json.value | int) <= 66 %} 50 {% elif (value_json.value | int) <= 99 %} 99 {% endif %}",
```

**Comment by blhoward2** [comment]
You have to hit store first. Then change it. Then save.

**Comment by towerhand** [comment]
Thanks, but I broke things with the changes I made. The current discovery payload will work for another couple months until they remove the backward compatibility in version 2021.7.0.

**Comment by jerobins** [comment]
This is still an issue.

**Comment by bcrochet** [comment]
+1 to this one. This seems to still be an issue. All of these values are deprecated.

**Comment by robertsLando** [comment]
@bcrochet Did you also try with zwavejs integrationo?

**Comment by towerhand** [comment]
That’s what I ended up doing a couple months ago.

**Comment by robertsLando** [comment]
It is now th official way to handle hass discovery, z2m should be used just as Control Panel and (if needed) mqtt gateway. MQTT discovery is limited compared to a native integration, it'a also hard and gets broken very frequently by hass updates

**Comment by gsmiler** [comment]
This is an old post, but just wanted to share a version HA discovery JSON settings snippet in case someone else wants to use it.  Nothing against the ZwaveJS integratio, it works perfectly.   It just makes more sense in my case to use MQTT...
BTW -- major kudos to the developers for allowing custom HA AutoDiscovery setup, right in the GUI!  I really appreciate this feature.

If you use this, be sure to replace <LOCATION>, <FAN NAME>, etc, with the correct values...

{
  "type": "fan",
  "object_id": "dimmer",
  "values": [
    "38-0-currentValue",
    "38-0-targetValue"
  ],
  "discovery_payload": {
    "state_topic": "zwave/<LOCACTION>/<FAN NAME>/38/0/currentValue",
    "state_value_template": "{% if (value_json.value | int) == 0 %} 0 {% else %} 255 {% endif %}",
    "command_topic": "zwave/<LOCATION>/<FAN NAME>/38/0/targetValue/set",
    "percentage_state_topic": "zwave/<LOCATION>/<FAN NAME>/38/0/currentValue",
    "percentage_value_template": "{{ value_json.value  }}",
    "percentage_command_topic": "zwave/<LOCATION>/<FAN NAME>/38/0/targetValue/set",
    "percentage_command_template": "{% if   (value | int) <= 15 %}0 {% elif (value | int) <= 45 %}24 {% elif (value | int) <= 80 %}50 {% else %}99 {% endif %}",
    "preset_mode_state_topic": "zwave/<LOCATION>/<FAN NAME>/38/0/currentValue",
    "preset_mode_value_template": "{{ {0:'Off', 24:'Low', 50:'Medium', 99:'High'}[value_json.value]}}",
    "preset_mode_command_topic": "zwave/<LOCATION>/<FAN NAME>/38/0/targetValue/set",
    "preset_mode_command_template": "{{ {'Off':0, 'Low':24, 'Medium':50, 'High':99}[value] | default ('') }}",
    "payload_on": 255,
    "payload_off": 0,
    "preset_modes": [
      "Off",
      "Low",
      "Medium",
      "High"
    ],
    "device": {
      "identifiers": [
        "zwavejs2mqtt__node"
      ],
      "manufacturer": "GE/Jasco",
      "model": "In-Wall Smart Fan Control (14287 / ZW4002)",
      "name": "Fan",
      "sw_version": "5.24"
    },
    "name": "Fan_dimmer",
    "unique_id": "zwavejs2mqtt_node_38-0-currentValue"
  },
  "discoveryTopic": "fan/<LOCATION>/dimmer/config",
  "persistent": false,
  "ignoreDiscovery": false,
  "id": "fan_dimmer"
}

**Comment by blhoward2** [comment]
I'm curious, why do you think mqtt discovery makes more sense in your setup? I struggle to think of why that would be...

**Comment by bcrochet** [comment]
This is an old issue, but I do have the question of how to be able to get the speed presets with that native integration? I've only been able to use percentage numbers to set the speed.

**Comment by blhoward2** [comment]
Please open a new issue if you need support. You’ll get better support on the HA discord in the #zwave channel, though if it relates to the native integration.

**Comment by gsmiler** [comment]
@bcrochet  - to summarize, the speed presets in the snippet above are converted to percentage numbers by the command and value templates.

**Comment by robertsLando** [comment]
@gsmiler The only problem is that like I wrote on Mqtt Discovery docs I don't plan to keep it maintained since there is the integration. Mqtt dicovery is a mess and is much less powerful then a native integration, it is frequently brokoen by hass updates too and I prefer to focus on control panel features instead that is what is most used by users

**Comment by gsmiler** [comment]
@robertsLando Completely understand.  You need to work on the most important and used features.  I wouldn't consider autodiscovery a core feature by any means; especially since issues like this can also be solved by defining a custom mqtt device in HA as well.  This is all a very minor issue.
Keep up the great work on this project!
