### ISSUE TITLE
[feat] Failed Nodes - Remove All should skip sleepy devices

### ISSUE THREAD

**Issue by steve28** [zwave-js/zwavejs2mqtt#983]
**Is your feature request related to a problem? Please describe.**
If using Failed Nodes - Remove All, the system will remove ALL sleeping nodes.  This is non-intuitive and quite destructive.  I would expect this command to only remove nodes which are _already_ marked dead.  

**Describe the solution you'd like**
The Failed Nodes - Remove All command should skip sleepy devices.  I think it's ok to keep for the individual node level "Remove Failed Node" but for a network-wide operation it should skip a device that could be asleep.  

**Describe alternatives you've considered**
A compromise could be to show a warning dialog that indicates any device that is currently asleep will be removed.  However, this would mean this button is useless for anyone that has battery devices in their network.

**Additional context**
N/A

**Comment by robertsLando** [comment]
@AlCalzone Should also this be an option to add to removeFailed call? Like `ignoreSleeping`

**Comment by AlCalzone** [comment]
Seems unnecessary. If you call removeFailed for a single node, it is very very likely that you want to do exactly that.
The mentioned call only exists in zwavejs2mqtt, so zwavejs2mqtt should make sure that all calls make sense.
