### ISSUE TITLE
Bump ZwaveJS version in ZwaveJS2MQTT to V7.0.1 to fix ZEN16 Multirelay mapping issues[bug]

### ISSUE THREAD

**Issue by DayRunner131** [zwave-js/zwavejs2mqtt#986]
### Version

**Checklist:**

- [ Am, HA-ZwaveJS2MQTT sent me here: https://github.com/hassio-addons/addon-zwavejs2mqtt/issues/104#issuecomment-811534384] I am **not** using HomeAssistant. **Or:** a developer has told me to come here.
- [ X] I have checked the troubleshooting section and my problem is **not** described there.
- [ X] I have read the changelog problem was **not** mentioned there.

Build/Run method

- [ ] Docker
- [ ] PKG
- [ ] Snap package
- [ ] Manually built (git clone - npm install - npm run build )

zwavejs2mqtt version: <version here, you can find it on control panel>
zwave-js version: <version here, you can find it on control panel>

### Describe the bug

To fix duplicate mapping for ZEN16 Multirelay. See https://github.com/zwave-js/node-zwave-js/issues/1748#issuecomment-811516907
### To Reproduce

With a Zen16 running firmware V1.04b, under binary switch, toggle on/off for either RLY2 or RLY3. RLY1 will report a current state in duplicate to RLY2 or RLY3. This is a mapping issue potentially fixed under ZwaveJS v7.0.1

### Expected behavior

RLY1 will not duplicate the current state of RLY2 or RLY3

### Additional context

See ZwaveJS issue https://github.com/zwave-js/node-zwave-js/pull/2160

**Comment by blhoward2** [comment]
You don't need to open an issue to have this bumped. It'll get bumped automatically. We release 1-2 times per week most weeks.

**Comment by DayRunner131** [comment]
> You don't need to open an issue to have this bumped. It'll get bumped automatically. We release 1-2 times per week most weeks. You can build your own off both masters right now if you like. Or run a dev docker image.

Great, and thank you for the additional information on your processes.

**Comment by robertsLando** [comment]
Done, release is coming
