### ISSUE TITLE
[feat] Show heal in progress status

### ISSUE THREAD

**Issue by robertsLando** [zwave-js/zwavejs2mqtt#993]
Ref: https://github.com/zwave-js/zwavejs2mqtt/issues/969#issuecomment-812457763

**Comment by jmgiaever** [comment]
Hi,

is there some function we can call through `driver function`-feature to get a list of healed nodes (or possibly "unhealed" nodes) while waiting for this feature?

**Comment by robertsLando** [comment]
Hi @jmgiaever I dunno, @AlCalzone is there a method to actually check if a node is healing?

**Comment by AlCalzone** [comment]
What's wrong with the progress events that the driver emits while healing?

**Comment by robertsLando** [comment]
Nothing wrong with them, that's the way I will implement this. It's just a temporary solution asked by @jmgiaever until I implement one on the UI.

BTW I will try to implement it this afternoon if I have some free time

**Comment by jmgiaever** [comment]
At the moment, you can't see in zwjs2m which nodes that is healed and which isn't. Some battery powered devices takes a long time (in this case days, about a week now and still waiting) to heal. 

Manual wake-up helps this process, but it would be nice to have a solution to easily see which nodes is not healed yet. I guess this is something that lacks in zwjs2m.

But we have the option to issue a «custom JS call» through the UI, and I was hoping that a call to the driver could help me figure out which nodes I need to wake up - while waiting for the feature in zwjs2m.

**Comment by AlCalzone** [comment]
@jmgiaever 
> I was hoping that a call to the driver could help me figure out which nodes I need to wake up

That's not possible, because the feature is designed differently.

**Comment by jmgiaever** [comment]
Thank you so much @robertsLando. Just upgraded and now doing a heal. How can I use the new feature?

**Comment by robertsLando** [comment]
You should just see a new column in control panel ui that shows heal status of the nodes

**Comment by jmgiaever** [comment]
Hm, but I can't see it.

![Screenshot from 2021-05-25 18-28-49](https://user-images.githubusercontent.com/7188121/119534525-4fae7500-bd87-11eb-9569-2b8ed503cbbd.png)

Tried clearing cache too.

**Comment by jmgiaever** [comment]
Doh, my mistake! I had obviously selected columns sometime in the past, and pressing «reset table» fixed it. 

Sorry for that.... but the column is empty. Had to stop the heal and start it over again. Not sure if that's related to that the field was hidden when starting the first heal.

**Comment by robertsLando** [comment]
ATM that field is refreshed only while doing an heal, no info is persisted on the nodes :)

**Comment by jmgiaever** [comment]
Ah, then it makes sense why it disappears. I've seen that you're going to store the state now on nodes, from the bug I filed. It will make this feature golden, as the heal might take long an there's big chances that I will close the browser (e.g turn of machine to bring with on a remote job) before I'll start investigate which nodes I must wake up manually. Thank you. Great job! :)

**Comment by robertsLando** [comment]
PR reaedy to fix this
